import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosTraffic {
  static List<Scenario> get list => [
        // 1. Traffic Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_1',
          categoryId: 'traffic',
          titleAr: 'حادث سير متسلسل على طريق سريع',
          titleEn: 'Highway Multi-Vehicle Crash Response',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتأمين موقع الحادث، الإسعاف الأولي، والإبلاغ الرسمي.',
          descriptionEn: 'Interactive 5-station scenario to secure highway crash site and call 911/996.',
          difficulty: 'صعب',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'وقع حادث تصادم أمامك على الخط السريع. كيف توقف مركبتك لتفادي التصادم؟',
              'sitEn': 'Sudden crash occurs on high-speed highway ahead. How to park safely?',
              'hintAr': 'التوقف على الكتف الأيمن الآمن، تفعيل أضواء التحذير (الفلاشر)، والابتعاد عن المسارات',
              'hintEn': 'Park on safe right shoulder, turn hazard lights on, clear active travel lanes',
              'safeTextAr': 'التوقف على الأكتاف الترابية الجانبية وتفعيل أضواء التحذير الرباعية (الفلاشر)',
              'safeTextEn': 'Pull onto far right shoulder and activate hazard emergency flasher lights',
              'safeExpAr': 'تصرف مثالي؛ يمنع ارتطام الشاحنات والسيارات القادمة بمركبتك.',
              'safeExpEn': 'Ideal action; prevents oncoming high-speed traffic from rear-ending your vehicle.',
              'safeOutAr': 'أمّنت سيارتك وتوجهت للمحطة 2.',
              'safeOutEn': 'Parked vehicle safely, advancing to Station 2.',
              'unsafeTextAr': 'التوقف المفاجئ وسط المسار السريع والترجل من السيارة فجأة',
              'unsafeTextEn': 'Slam brakes mid-fast lane and step out immediately onto active lane',
              'unsafeExpAr': 'خطأ قاتل؛ التوقف في المسار السريع يسبب حادثاً متسلسلاً ودهساً فورياً.',
              'unsafeExpEn': 'Fatal mistake; stopping mid-lane triggers chain collisions and pedestrian hit.',
              'unsafeOutAr': 'تعرض موقعك لخطر التصادم.',
              'unsafeOutEn': 'Triggered high risk of secondary crash.',
            },
            {
              'sitAr': 'تأمين الخلفية من الشاحنات القادمة بسرعات عالية. كيف تنبه الطريق؟',
              'sitEn': 'Warning oncoming traffic on high-speed road. Triangle placement?',
              'hintAr': 'وضع مثلث السلامة العاكس على مسافة 100 متر خلف الحادث لتنبيه السيارات السريعة',
              'hintEn': 'Place reflective warning triangle 100 meters behind crash site',
              'safeTextAr': 'وضع مثلث السلامة العاكس على مسافة 100 متر خلف موقع الحادث',
              'safeTextEn': 'Place reflective safety triangle 100m upstream behind accident site',
              'safeExpAr': 'إجراء أمني معتمد؛ يمنح سائقي الطريق السريع مسافة كافية للتبريز والتهدئة.',
              'safeExpEn': 'Standard safety rule; gives highway drivers stopping distance awareness.',
              'safeOutAr': 'حميت الموقع وانتقلت للمحطة 3.',
              'safeOutEn': 'Protected site from rear impact for Station 3.',
              'unsafeTextAr': 'وضع المثلث ملاصقاً تماماً لصدام السيارة المتضررة',
              'unsafeTextEn': 'Set warning triangle right against damaged rear bumper',
              'unsafeExpAr': 'غير مجدي؛ وضع المثلث قريباً لا يعطي السيارات السريعة أي وقت للتوقف.',
              'unsafeExpEn': 'Inadequate; zero stopping warning provided to oncoming fast cars.',
              'unsafeOutAr': 'لم تتنبه السيارات السريعة للحادث.',
              'unsafeOutEn': 'Oncoming cars lacked warning distance.',
            },
            {
              'sitAr': 'فحص المصاب داخل السيارة المصابة. كيف تضمن سلامة عموده الفقري؟',
              'sitEn': 'Checking victim inside wrecked car. Spinal safety protocol?',
              'hintAr': 'عدم تحريك المصاب إطلاقاً إلا في حالة خطورة حريق مؤكد، لمنع الشلل الرقبي',
              'hintEn': 'Do NOT move spinal crash victim unless immediate vehicle fire threatens life',
              'safeTextAr': 'تثبيت رأس المصاب وعدم سحبه من المركبة إلا عند وجود خطر حريق داهم',
              'safeTextEn': 'Stabilize victim head/neck and refrain from pulling unless fire threatens',
              'safeExpAr': 'قاعدة طبية ذهبية؛ تحريك ركاب حوادث السيارات دون نقالة قد يسبب الشلل الدائم.',
              'safeExpEn': 'Golden trauma rule; moving crash victims without neck brace risks paralysis.',
              'safeOutAr': 'حميت الحبل الشوكي للمصاب للمحطة 4.',
              'safeOutEn': 'Protected spinal cord safely for Station 4.',
              'unsafeTextAr': 'سحب المصاب بقوة من نافذة السيارة وإجلاسه على الإسفلت',
              'unsafeTextEn': 'Yank victim forcefully through broken window laying them on asphalt',
              'unsafeExpAr': 'خطأ جسيم؛ السحب العشوائي يسبب قطع الحبل الشوكي عند وجود كسور فقارية.',
              'unsafeExpEn': 'Severe mistake; rough pulling severs spinal cord if cervical vertebrae fractured.',
              'unsafeOutAr': 'تسببت في تفاقم إصابة العمود الفقري.',
              'unsafeOutEn': 'Exacerbated spinal cord trauma.',
            },
            {
              'sitAr': 'إجراء الاتصال الفوري بالطوارئ الموحدة (911 أو 996 أمن الطرق). ماذا تبلغ؟',
              'sitEn': 'Calling unified emergency (911 or 996 Highway Security). Information needed?',
              'hintAr': 'إعطاء الموقع بدقة عبر تحديد اسم الطريق، الاتجاه، عدد السيارات والمصابين',
              'hintEn': 'Specify exact highway name, direction, landmark, vehicle count, and injuries',
              'safeTextAr': 'تحديد اسم الطريق السريع، الكيلومتر أو المعلم القريب، عدد السيارات المحتجزة، وحالة المصابين',
              'safeTextEn': 'Report highway route, direction, nearby landmark/KM, car count, and condition',
              'safeExpAr': 'بلاغ متكامل؛ يتيح توجيه سيارات الإسعاف والمرور ونجم ونشير الدفاع المدني فوراً.',
              'safeExpEn': 'Complete dispatch call; allows fast routing of ambulance, police, and CD cutters.',
              'safeOutAr': 'تم إرسال فرق الاستجابة للمحطة 5.',
              'safeOutEn': 'Response units dispatched, advancing to Station 5.',
              'unsafeTextAr': 'الصراخ بالهاتف دون ذكر المكان ثم إغلاق المكالمة فوراً',
              'unsafeTextEn': 'Scream into phone without providing exact location then hang up',
              'unsafeExpAr': 'خطأ؛ غياب تحديد الموقع يمنع وصول فرق الإنقاذ لمكان الحادث.',
              'unsafeExpEn': 'Error; lack of location data leaves emergency teams unable to respond.',
              'unsafeOutAr': 'تأخرت فرق الإنقاذ.',
              'unsafeOutEn': 'Emergency response delayed.',
            },
            {
              'sitAr': 'لاحظت تسرب وقود بنزين تحت محرك السيارة المتضررة. ما تصرف الأمان النهائي؟',
              'sitEn': 'Fuel leak noticed beneath crashed car engine. Final safety action?',
              'hintAr': 'إطفاء محرك المركبة، فصل بطارية السيارة إن أمكن، وإبعاد الجمهور وتجنب التدخين',
              'hintEn': 'Turn off ignition, disconnect battery if safe, clear bystanders, prohibit smoking',
              'safeTextAr': 'إطفاء السويتش، فصل أطراف البطارية، وإبعاد جميع المجمهرين عن أبخرة البنزين',
              'safeTextEn': 'Turn ignition key off, disconnect battery terminals, clear bystanders from fumes',
              'safeExpAr': 'حماية فائقة؛ قطع الدائرة الكهربائية يبطل احتمال اشتعال الوقود المتسرب.',
              'safeExpEn': 'Supreme protection; breaking electrical circuit removes fuel flashpoint trigger.',
              'safeOutAr': 'أكملت محطات إدارة حوادث الطرق بنجاح!',
              'safeOutEn': 'Successfully completed all 5 traffic safety response stations!',
              'unsafeTextAr': 'إشعال ولاعة للتأكد من حجم وقوة تسرب البنزين',
              'unsafeTextEn': 'Light a cigarette lighter near leak to check fuel spray',
              'unsafeExpAr': 'خطأ كارثي؛ أبخرة البنزين تشتعل فوراً وتسبب انفجاراً مدققعاً.',
              'unsafeExpEn': 'Catastrophic mistake; petrol vapors ignite instantly causing engine bay explosion.',
              'unsafeOutAr': 'تسببت في حريق الحادث.',
              'unsafeOutEn': 'Triggered immediate fuel fire explosion.',
            },
          ],
        ),

        // Scenarios 2 to 9 for TRAFFIC...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_2',
          categoryId: 'traffic',
          titleAr: 'انفجار إطار السيارة أثناء السرعة',
          titleEn: 'High-Speed Tire Blowout Recovery',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتحكم في المركبة عند انفجار الإطار والتوقف الآمن.',
          descriptionEn: 'Interactive 5-station scenario for managing high-speed tire blowouts.',
          difficulty: 'صعب',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'سمعت صوت انفجار مدوٍ واهتزت عجلة القيادة بقوة أثناء قيادتك بسرعة 120 كم/س. ما الحركة؟',
              'sitEn': 'Loud bang and violent steering wheel shake at 120 km/h. First action?',
              'hintAr': 'الإمساك بالمقود بكلتا اليدين بقوة وعدم الضغط على دواسة الفرامل',
              'hintEn': 'Grip wheel firmly with both hands; do NOT hit brake pedal',
              'safeTextAr': 'الإمساك بعجلة القيادة بكلتا اليدين بقوة للحفاظ على استقامة السيارة',
              'safeTextEn': 'Grip steering wheel tightly with both hands keeping vehicle straight',
              'safeExpAr': 'تصرف ممتاز؛ الإمساك بقوة يمنع انحراف المركبة نحو الحاجز الخرساني.',
              'safeExpEn': 'Excellent response; tight grip counteracts drag force keeping car in lane.',
              'safeOutAr': 'حافظت على اتجاه السيارة للمحطة 2.',
              'safeOutEn': 'Maintained lane direction for Station 2.',
              'unsafeTextAr': 'الضغط على دواسة الفرامل بأقصى قوة (Slam Brakes)',
              'unsafeTextEn': 'Slam foot down on brake pedal violently',
              'unsafeExpAr': 'خطأ؛ الفرملة المفاجئة تجعل الجنط المعدني يحتك بالإسفلت وينقلب بالسيارة.',
              'unsafeExpEn': 'Error; hard braking during blowout catches rim edge causing instant rollover.',
              'unsafeOutAr': 'انقلبت المركبة.',
              'unsafeOutEn': 'Vehicle rolled over.',
            },
            {
              'sitAr': 'السيارة تتباطأ تدريجياً بسبب احتكاك الإطار الذائب. متى تبدأ التبريز؟',
              'sitEn': 'Vehicle decelerating from rim friction. When to begin braking?',
              'hintAr': 'رفع القدم عن البنزين ودع السيارة تتباطأ تلقائياً لـ 40 كم/س قبل الفرملة',
              'hintEn': 'Lift off gas allowing natural deceleration to 40 km/h before light braking',
              'safeTextAr': 'رفع القدم عن البنزين وترك السيارة تتباطأ حتى 40 كم/س ثم الضغط الخفيف على الفرامل',
              'safeTextEn': 'Release gas pedal letting car coast down to 40 km/h before applying gentle brakes',
              'safeExpAr': 'تكتيك محترف؛ التباطؤ الطبيعي يمنع اختلال التوازن مع الإطار التالف.',
              'safeExpEn': 'Pro tactic; coasting allows aerodynamic drag to safely slow vehicle.',
              'safeOutAr': 'تباطأت السرعة بسلام للمحطة 3.',
              'safeOutEn': 'Coasted down safely for Station 3.',
              'unsafeTextAr': 'شد الفرامل اليدوية (Handbrake) بسرعة',
              'unsafeTextEn': 'Yank mechanical handbrake leverage up suddenly',
              'unsafeExpAr': 'خطأ؛ شد الهندبريك يقفل العجلات الخلفية ويسبب التفحيط والدوران.',
              'unsafeExpEn': 'Error; pulling handbrake locks rear wheels causing uncontrollable tail spin.',
              'unsafeOutAr': 'دارت السيارة حول نفسها.',
              'unsafeOutEn': 'Vehicle tail-spun out of control.',
            },
            {
              'sitAr': 'كيف توقف السيارة خارج مسارات السير على الخط السريع؟',
              'sitEn': 'How to bring car to complete stop outside active highway lanes?',
              'hintAr': 'التوجه للأكتاف الترابية البعيدة وتفعيل الفلاشر الرباعي',
              'hintEn': 'Steer to far right shoulder and turn on hazard emergency flashers',
              'safeTextAr': 'التوجه بمرونة للكتف الترابي الأيمن وتفعيل أضواء التحذير الرباعية',
              'safeTextEn': 'Steer smoothly onto right shoulder and switch on hazard warning lights',
              'safeExpAr': 'إجراء آمن؛ التوقف بعيداً عن حارة السير يقي من الحوادث الخلفية.',
              'safeExpEn': 'Safe procedure; clearing active traffic lanes prevents rear-end collisions.',
              'safeOutAr': 'أوقفت المركبة بالكتف الأيمن للمحطة 4.',
              'safeOutEn': 'Parked on right shoulder for Station 4.',
              'unsafeTextAr': 'التوقف في المسار الوسطي بين الشاحنات',
              'unsafeTextEn': 'Stop dead in center lane between heavy trucks',
              'unsafeExpAr': 'خطأ؛ التوقف بوسط المسارات يسبب دهس مركبتك من الشاحنات.',
              'unsafeExpEn': 'Error; stopping mid-lane exposes car to high-speed truck impacts.',
              'unsafeOutAr': 'اصطدمت شاحنة بالمركبة.',
              'unsafeOutEn': 'Struck by rear truck.',
            },
            {
              'sitAr': 'تأمين سلامة الركاب أثناء التواجد على الخط السريع. ماذا يفعل الركاب؟',
              'sitEn': 'Securing passenger safety while stranded on highway shoulder. Action?',
              'hintAr': 'ترجل الركاب والوقوف خلف الحاجز الخرساني أو الشبك الخارجي للطريق',
              'hintEn': 'Passengers exit car standing safely behind guardrail or perimeter fence',
              'safeTextAr': 'ترجل جميع الركاب والوقوف خلف الحاجز الخرساني الخارجي البعيد عن الإسفلت',
              'safeTextEn': 'Have all passengers exit car and stand behind steel/concrete guardrail',
              'safeExpAr': 'تأمين ممتاز؛ البقاء داخل السيارة المتوقفة بالأكتاف ينطوي على خطورة اصطدام بالسيارات.',
              'safeExpEn': 'Great safety step; standing behind guardrails protects against shoulder crashes.',
              'safeOutAr': 'وقفت الأسرة خلف الحاجز للمحطة 5.',
              'safeOutEn': 'Passengers safe behind guardrail for Station 5.',
              'unsafeTextAr': 'بقاء الركاب داخل السيارة وأبوابها مفتوحة نحو الإسفلت',
              'unsafeTextEn': 'Keep passengers seated inside car with doors open toward active lane',
              'unsafeExpAr': 'خطأ؛ بقاء الركاب بالسيارة يضعهم في منطقة خطر التصادم.',
              'unsafeExpEn': 'Error; sitting inside shoulder-parked car risks severe crash injuries.',
              'unsafeOutAr': 'عرضت الركاب لخطر التصادم.',
              'unsafeOutEn': 'Exposed passengers to crash zone.',
            },
            {
              'sitAr': 'الاتصال بخدمات الطريق ونجم/أمن الطرق (996/199033). ما الخطوة النهائية؟',
              'sitEn': 'Calling Highway Security (996) or Najm (199033). Final step?',
              'hintAr': 'طلب ساطحة أو المساعدة وإبراز مثلث السلامة على 100م',
              'hintEn': 'Request roadside tow service and set warning triangle 100m back',
              'safeTextAr': 'الاتصال بـ 996 وطلب المساعدة الميدانية مع التأكد من بقاء المثلث العاكس خلف المركبة',
              'safeTextEn': 'Call 996 Roadside Security requesting tow service keeping warning triangle set',
              'safeExpAr': 'إتمام كامل؛ تأمين الطريق واستدعاء الخدمة ينهي حادث الانفجار بسلام.',
              'safeExpEn': 'Complete resolution; site warning and professional tow resolves blowout safely.',
              'safeOutAr': 'أكملت محطات نجاة انفجار الإطار بنجاح!',
              'safeOutEn': 'Successfully completed high-speed blowout scenario!',
              'unsafeTextAr': 'محاولة تغيير الإطار بنفسك بمنتصف الليل بدون إضاءة أو مثلث',
              'unsafeTextEn': 'Attempt changing tire at midnight without torch or warning triangle',
              'unsafeExpAr': 'خطأ؛ العمل بالظلام على طريق سريع يسبب دهسك.',
              'unsafeExpEn': 'Error; working in dark on unlit highway risks fatal pedestrian strike.',
              'unsafeOutAr': 'تعرضت لخطر الدهس بالليل.',
              'unsafeOutEn': 'Pedestrian strike hazard in dark.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_3',
          categoryId: 'traffic',
          titleAr: 'انزلاق المركبة في المطر (Hydroplaning)',
          titleEn: 'Rain Hydroplaning & Skid Control',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتحكم في طفو وانزلاق المركبة فوق تجمع مياه المطر.',
          descriptionEn: 'Interactive 5-station scenario for rain hydroplaning skid control.',
          difficulty: 'متوسط',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'فقدت إطارات السيارة التماس مع الإسفلت وبدأت بالطوفان فوق طبق المطر (Hydroplaning). ما الحركة؟',
              'sitEn': 'Tires lose contact with wet road floating on water layer (Hydroplaning). Action?',
              'hintAr': 'رفع القدم عن دواسة البنزين فوراً وعدم تدوير المقود بشدة',
              'hintEn': 'Ease off gas pedal completely; do NOT jerk steering wheel aggressively',
              'safeTextAr': 'رفع القدم عن البنزين فوراً والاحتفاظ بالجهد المستقيم للمقود دون تدوير عنيف',
              'safeTextEn': 'Ease off gas pedal completely keeping steering wheel straight without jerking',
              'safeExpAr': 'تصرف ممتاز؛ رفع البنزين يقلل سرعة المركبة حتى يعود الإطار لملامسة الإسفلت.',
              'safeExpEn': 'Excellent step; easing off gas drops vehicle speed allowing tires to reconnect with road.',
              'safeOutAr': 'استعادت الإطارات التلامس للمحطة 2.',
              'safeOutEn': 'Tires reconnected with asphalt for Station 2.',
              'unsafeTextAr': 'تدوير المقود بأقصى سرعة يميناً ويساراً',
              'unsafeTextEn': 'Jerk steering wheel violently back and forth to regain grip',
              'unsafeExpAr': 'خطأ؛ تدوير المقود أثناء الانزلاق يسبب انحراف السيارة فور ملامستها الأرض.',
              'unsafeExpEn': 'Error; jerking wheel while hydroplaning causes violent fishtail spin upon contact.',
              'unsafeOutAr': 'انحرفت السيارة وانزلقت.',
              'unsafeOutEn': 'Vehicle fishtailed violently.',
            },
            {
              'sitAr': 'بدأ الجزء الخلفي للسيارة بالانحراف نحو اليمين (Fishtailing). كيف تصحح مسار الانزلاق؟',
              'sitEn': 'Rear of car starts sliding right (oversteer skid). How to correct skid?',
              'hintAr': 'تدوير المقود ببطء بنحسه اتجاه الانزلاق (توجيه النواة نحو اليمين)',
              'hintEn': 'Steer smoothly INTO the direction of the skid (steer right into slide)',
              'safeTextAr': 'توجيه عجلة القيادة ببطء نحو اتجاه الانزلاق نفسه (نحو اليمين) لاستعادة التوازن',
              'safeTextEn': 'Turn steering wheel smoothly in the direction the rear is skidding (steer right)',
              'safeExpAr': 'تكتيك عالمي؛ التوجيه باتجاه الانزلاق يوازن قوة القصور الذاتي ويعيد استقامة السيارة.',
              'safeExpEn': 'Universal skid control rule; steering into the skid realigns front and rear tires.',
              'safeOutAr': 'استعادت السيارة استقامتها للمحطة 3.',
              'safeOutEn': 'Realigned vehicle trajectory for Station 3.',
              'unsafeTextAr': 'التوجيه بعنف نحو الاتجاه المعاكس (نحو اليسار)',
              'unsafeTextEn': 'Steer violently in opposite direction of skid (steer hard left)',
              'unsafeExpAr': 'خطأ؛ التوجيه المعاكس العنيف يضاعف قوة الدوران ويسبب انقلاب المركبة.',
              'unsafeExpEn': 'Error; overcorrecting opposite to skid multiplies rotational momentum causing rollover.',
              'unsafeOutAr': 'تضاعف دوران المركبة.',
              'unsafeOutEn': 'Rotational spin doubled.',
            },
            {
              'sitAr': 'كيف تستخدم الفرامل عند الانزلاق في المطر مع وجود نظام ABS؟',
              'sitEn': 'How to apply brakes during rain skid if vehicle has ABS?',
              'hintAr': 'الضغط المستمر على دواسة الفرامل دون ضخها (Don\'t Pump ABS Brakes)',
              'hintEn': 'Apply firm steady pressure on brake pedal; do NOT pump ABS brakes',
              'safeTextAr': 'الضغط بثبات واستمرار على دواسة الفرامل وترك نظام ABS يعمل تلقائياً',
              'safeTextEn': 'Apply firm continuous pressure on brake pedal letting ABS pulse system work',
              'safeExpAr': 'إجراء صحيح؛ نظام ABS يضخ الفرامل 15 مرة بالثانية لمنع انقلاق العجلات.',
              'safeExpEn': 'Correct method; ABS automatically pulses brakes 15 times/sec preventing lockup.',
              'safeOutAr': 'عمل نظام ABS بفعالية للمحطة 4.',
              'safeOutEn': 'ABS safely slowed vehicle for Station 4.',
              'unsafeTextAr': 'ضخ وتخفيف الضغط على دواسة الفرامل بالقدم مراراً (Pumping Brakes)',
              'unsafeTextEn': 'Rapidly pump and release brake pedal repeatedly with foot',
              'unsafeExpAr': 'خطأ؛ ضخ الفرامل بالقدم يعطل عمل نظام ABS الذكي بالسيارات الحديثة.',
              'unsafeExpEn': 'Error; manual brake pumping overrides and disables smart ABS computer control.',
              'unsafeOutAr': 'تعطل نظام الفرملة الذكي.',
              'unsafeOutEn': 'Disabled computer ABS system.',
            },
            {
              'sitAr': 'الوصول للسرعة الآمنة أثناء القيادة بالجو الممطر. ما السرعة المناسبة؟',
              'sitEn': 'Establishing safe driving speed during rainstorm. Speed adjustment?',
              'hintAr': 'تخفيض السرعة بمقدار 20-30 كم/س عن السرعة المحددة وزيادة مسافة الأمان',
              'hintEn': 'Reduce speed by 20-30 km/h below posted limit & double safety distance',
              'safeTextAr': 'تخفيض السرعة ومضاعفة مسافة الأمان بينك وبين السيارة الأمامية إلى 4 ثوانٍ',
              'safeTextEn': 'Reduce speed by 20-30 km/h and double following distance to 4 full seconds',
              'safeExpAr': 'تأمين ممتاز؛ مسافة التوقف على الإسفلت المبلل تتضاعف 3 مرات مقارنة بالجاف.',
              'safeExpEn': 'Great safety buffer; wet asphalt stopping distance triples compared to dry roads.',
              'safeOutAr': 'أمّنت مسافة الأمان للمحطة 5.',
              'safeOutEn': 'Doubled following distance for Station 5.',
              'unsafeTextAr': 'القيادة بالسرعة القصوى المحددة في الأيام الجافة',
              'unsafeTextEn': 'Drive at maximum posted dry weather speed limit during heavy rain',
              'unsafeExpAr': 'خطأ؛ السرعة العالية بالمطر تلغي التماس الهيدروليكي بين الإطار والإسفلت.',
              'unsafeExpEn': 'Error; high speed in rain strips tire tread of water evacuation ability.',
              'unsafeOutAr': 'تعرضت لانزلاق مجدد.',
              'unsafeOutEn': 'Re-entered hydroplaning zone.',
            },
            {
              'sitAr': 'فحص الإطارات بعد انتهاء المطر. ما المواصفة الهامة للوقاية من الانزلاق؟',
              'sitEn': 'Inspecting tires post-rain. Vital spec for wet grip prevention?',
              'hintAr': 'التأكد من عمق نقشة الإطار (أن لا تقل عن 3 ملم) ومعامل التماس Traction A',
              'hintEn': 'Ensure tread depth is above 3mm & check Traction A wet grip rating',
              'safeTextAr': 'فحص عمق قناة نقشة الإطار وتغير الإطار عند تآكل القنوات المخصصة لتصريف المياه',
              'safeTextEn': 'Audit tire tread groove depth ensuring rain channels are deep enough to clear water',
              'safeExpAr': 'إتمام كامل؛ قنوات النقشة العميقة تطرد المياه جانباً وتمنع طفو السيارة بالمطر.',
              'safeExpEn': 'Complete resolution; deep tread grooves channel water out maintaining road contact.',
              'safeOutAr': 'أكملت محطات التحكم في انزلاق المطر بنجاح!',
              'safeOutEn': 'Successfully completed rain hydroplaning scenario!',
              'unsafeTextAr': 'القيادة بإطارات ملساء مسحوقة النقشة (Mascot / Bald Tires)',
              'unsafeTextEn': 'Drive on bald smooth worn tires in rainy winter season',
              'unsafeExpAr': 'خطأ؛ الإطارات الملساء تطفو على أول قطرة مطر وتسبب الحوادث.',
              'unsafeExpEn': 'Error; bald tires act as water skis causing hydroplaning at low speeds.',
              'unsafeOutAr': 'تسبب الإطار الأملس بانزلاق.',
              'unsafeOutEn': 'Bald tire caused instant skid.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_4',
          categoryId: 'traffic',
          titleAr: 'تعطل فرامل السيارة أثناء القيادة',
          titleEn: 'Total Brake Failure Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتطبيق خطوات إيقاف السيارة عند تعطل دواسة الفرامل.',
          descriptionEn: 'Interactive 5-station scenario for managing complete brake failure.',
          difficulty: 'صعب',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'ضغطت دواسة الفرامل ووجدتها هابطة للأرض تماماً والسيارة تسير بسرعة 90 كم/س. ما أول تصرف؟',
              'sitEn': 'Pressed brake pedal and it went completely soft to floor at 90 km/h. First step?',
              'hintAr': 'ضخ الدواسة مراراً لتجميع الضغط الهيدروليكي وتنبيه السيارات بالفلاشر والنظارة',
              'hintEn': 'Pump brake pedal repeatedly to build hydraulic pressure & sound horn/flashers',
              'safeTextAr': 'ضخ دواسة الفرامل بسرعة وتكرار لتجميع ضغط الزيت وتفعيل أضواء التحذير والهورن',
              'safeTextEn': 'Pump brake pedal rapidly & repeatedly to build pressure; activate hazard lights & horn',
              'safeExpAr': 'تصرف ممتاز؛ ضخ الدواسة قد يعيد تجميع ضغط الزيت بالنظام المزدوج.',
              'safeExpEn': 'Excellent response; pumping can restore residual fluid pressure in dual master cylinders.',
              'safeOutAr': 'ضخخت الفرامل وحذرت الطريق للمحطة 2.',
              'safeOutEn': 'Pumped brakes & alerted traffic for Station 2.',
              'unsafeTextAr': 'إغلاق سويتش السيارة وإخراج المفتاح أثناء السرعة العالية',
              'unsafeTextEn': 'Turn key ignition completely off and pull key out while moving fast',
              'unsafeExpAr': 'خطأ قاتل؛ إخراج المفتاح يقفل عجلة القيادة (Steering Lock) ويعطل المقود كلياً.',
              'unsafeExpEn': 'Fatal mistake; pulling ignition key locks steering wheel causing crash.',
              'unsafeOutAr': 'انقفل مقود السيارة.',
              'unsafeOutEn': 'Steering wheel locked locked.',
            },
            {
              'sitAr': 'لم يستجب ضغط الزيت بالفرامل. كيف تستخدم ناقل الحركة (القير) للتهدئة؟',
              'sitEn': 'Hydraulic pressure failed. How to use transmission (gears) to slow car?',
              'hintAr': 'التبديل إلى النمر الأقل تدريجياً (Engine Braking N -> 3 -> 2 -> 1)',
              'hintEn': 'Shift to lower gears progressively (Engine Braking: D -> 3 -> 2 -> 1)',
              'safeTextAr': 'تعشيق القير إلى النمر الأقل تدريجياً (استخدام فرملة المحرك Engine Braking)',
              'safeTextEn': 'Downshift transmission to lower gears progressively using engine braking',
              'safeExpAr': 'تكتيك محترف؛ فرملة المحرك تخفض سرعة المركبة هيدروليكياً وبشكل آمن.',
              'safeExpEn': 'Pro tactic; engine compression braking downshifts vehicle momentum safely.',
              'safeOutAr': 'خففت السرعة عبر القير للمحطة 3.',
              'safeOutEn': 'Slowed vehicle via downshifting for Station 3.',
              'unsafeTextAr': 'تعشيق القير في وضعية الخلفي (Reverse R) أثناء حركة السيارة للأمام',
              'unsafeTextEn': 'Slam transmission gear lever into Reverse (R) while driving 80 km/h forward',
              'unsafeExpAr': 'خطأ؛ التعشيق في R يدمر تروس القير ويحيد كفاءة فرملة المحرك.',
              'unsafeExpEn': 'Error; shifting into R shears transmission teeth losing engine braking power.',
              'unsafeOutAr': 'تكسرت تروس القير.',
              'unsafeOutEn': 'Transmission gears stripped.',
            },
            {
              'sitAr': 'انخفضت السرعة لـ 30 كم/س. كيف تستخدم الفرامل اليدوية (Handbrake)؟',
              'sitEn': 'Vehicle slowed to 30 km/h. How to apply parking handbrake?',
              'hintAr': 'سحب الفرامل اليدوية ببطء وثبات مع الضغط على زر الأمان',
              'hintEn': 'Pull handbrake up slowly & steadily while holding release button down',
              'safeTextAr': 'سحب الفرامل اليدوية ببطء وثبات مع الضغط على زر الأمان لمنع انغلاق العجلات',
              'safeTextEn': 'Pull emergency handbrake up slowly and steadily while holding release button',
              'safeExpAr': 'إجراء صحيح؛ السحب التدريجي يوقف العجلات الخلفية دون تفحيط أو انحراف.',
              'safeExpEn': 'Correct procedure; gradual handbrake pull slows rear axle without spinning car.',
              'safeOutAr': 'أوقفت المركبة بالفرامل اليدوية للمحطة 4.',
              'safeOutEn': 'Stopped car using handbrake for Station 4.',
              'unsafeTextAr': 'شد الفرامل اليدوية بأقصى قوة فجأة وبشكل عنيف',
              'unsafeTextEn': 'Yank emergency handbrake lever up violently to top lock position',
              'unsafeExpAr': 'خطأ؛ الشد العنيف يقفل العجلات الخلفية فجأة ويؤدي لدوران السيارة.',
              'unsafeExpEn': 'Error; violent handbrake yanking locks rear tires causing 360-degree spinout.',
              'unsafeOutAr': 'دارت السيارة حول نفسها.',
              'unsafeOutEn': 'Car spun out completely.',
            },
            {
              'sitAr': 'إذا فشلت جميع الوسائل السابقة واقتربت من تقاطع. كيف تستخدم الحواف لإيقافها؟',
              'sitEn': 'All mechanical methods failed approaching barrier. How to use terrain to stop?',
              'hintAr': 'الاحتراف مع الأكتاف الترابية أو حك الإطارات بالحاجز الخرساني الجانبي',
              'hintEn': 'Steer into loose dirt shoulder or sideswipe tires against concrete barrier wall',
              'safeTextAr': 'التوجيه نحو الأكتاف الترابية أو الاحتكاك التدريجي المائل بالحاجز الخرساني',
              'safeTextEn': 'Steer into loose gravel shoulder or gently friction-rub tires against side barrier wall',
              'safeExpAr': 'تكتيك نجاة اضطراري؛ احتكاك الإطارات بالحاجز يستهلك الطاقة الحركية بسلام.',
              'safeExpEn': 'Emergency friction tactic; sideswiping guardrail converts kinetic energy into stopping force.',
              'safeOutAr': 'أوقفت السيارة باحتكاك الحاجز للمحطة 5.',
              'safeOutEn': 'Stopped car via guardrail friction for Station 5.',
              'unsafeTextAr': 'الاصطدام المباشر وجه لوجه بشجرة أو عمود إنارة خرساني',
              'unsafeTextEn': 'Drive head-on straight into a massive tree or concrete pole',
              'unsafeExpAr': 'خطأ قاتل؛ الاصطدام المباشر بالعمود يسبب صدمة قاتلة وتدمير الكابينة.',
              'unsafeExpEn': 'Fatal error; head-on impact into fixed rigid poles causes catastrophic deceleration force.',
              'unsafeOutAr': 'اصطدام مباشر بـ عمود خرساني.',
              'unsafeOutEn': 'Catastrophic head-on pole crash.',
            },
            {
              'sitAr': 'توقف المركبة بسلام وتأمين المكان. ما الصيانة الوقائية للفرامل؟',
              'sitEn': 'Car stopped safely. Preventive brake maintenance protocol?',
              'hintAr': 'فحص زيت الفرامل وسماكة أقمشة الفرامل (الفحمات) كل 20,000 كم',
              'hintEn': 'Inspect brake fluid level and brake pad thickness every 20,000 km',
              'safeTextAr': 'فحص مستوى زيت الفرامل وتغيير فحمات الفرامل (Brake Pads) عند سماع صوت الصفير',
              'safeTextEn': 'Inspect brake fluid reservoir level and replace brake pads when squeal wear bar sounds',
              'safeExpAr': 'إتمام كامل؛ الصيانة الدورية للفرامل تمنع 99% من حالات تسرب الزيت وتعطل الفرامل.',
              'safeExpEn': 'Complete resolution; routine brake inspection prevents 99% of hydraulic fluid leaks.',
              'safeOutAr': 'أكملت محطات التعامل مع تعطل الفرامل بنجاح!',
              'safeOutEn': 'Successfully completed total brake failure scenario!',
              'unsafeTextAr': 'إهمال صوت صفير الفرامل الحاد والقيادة بزيت فرامل ناقص',
              'unsafeTextEn': 'Ignore loud metallic brake squealing and drive on low brake fluid',
              'unsafeExpAr': 'خطأ؛ إهمال أقمشة الفرامل يسبب احتكاك الحديد بالدسك وتلف الهيدروليك.',
              'unsafeExpEn': 'Error; ignoring worn brake pads destroys brake rotors causing fluid blowout.',
              'unsafeOutAr': 'تلف دسك الفرامل كلياً.',
              'unsafeOutEn': 'Brake rotors destroyed.',
            },
          ],
        ),

        // Scenarios 5 to 9 for TRAFFIC...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_5',
          categoryId: 'traffic',
          titleAr: 'انقلاب مركبة على جانب الطريق',
          titleEn: 'Vehicle Rollover Crash Response',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حوادث انقلاب السيارات والإنقاذ.',
          descriptionEn: 'Interactive 5-station scenario for vehicle rollover emergency response.',
          difficulty: 'صعب',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'شاهدت مركبة تنقلب أمامك وتستقر على سقفها بجانب الطريق. ما أول تصرف؟',
              'sitEn': 'Vehicle rolls over ahead landing upside down on its roof. Immediate response?',
              'hintAr': 'التوقف بمكان آمن وتفعيل أضواء التحذير والاتصال بـ (911/998)',
              'hintEn': 'Park safely, turn on hazard lights, and dial 911/998 immediately',
              'safeTextAr': 'إيقاف سيارتك بمكان آمن على الكتف الترابي وتفعيل أضواء الفلاشر والاتصال بـ (911)',
              'safeTextEn': 'Park your car on safe right shoulder, turn hazard lights on, and dial 911 dispatch',
              'safeExpAr': 'تصرف ممتاز؛ تأمين سيارتك أولاً يضمن عدم تعرضك للدهس أثناء الإسعاف.',
              'safeExpEn': 'Excellent first step; securing your vehicle prevents secondary crashes while aiding.',
              'safeOutAr': 'أمّنت الموقع وأبلغت 911 للمحطة 2.',
              'safeOutEn': 'Secured scene and dialed 911 for Station 2.',
              'unsafeTextAr': 'التوقف المفاجئ في حارة السير والركض نحو المركبة',
              'unsafeTextEn': 'Slam brakes mid-lane and run blindly across active highway traffic',
              'unsafeExpAr': 'خطأ؛ الركض عبر المسارات السريعة يعرضك للدهس الفوري من السيارات القادمة.',
              'unsafeExpEn': 'Error; running across active high speed traffic risks pedestrian strike.',
              'unsafeOutAr': 'تعرضت لخطر الدهس.',
              'unsafeOutEn': 'Pedestrian strike hazard.',
            },
            {
              'sitAr': 'الاقتراب من السيارة المنقلبة على سقفها. كيف تفحص تسرب الوقود؟',
              'sitEn': 'Approaching upside-down vehicle. How to check for fire/fuel risk?',
              'hintAr': 'فحص تسرب البنزين والشرر وإطفاء محرك المركبة المنقلبة إن أمكن',
              'hintEn': 'Check for fuel leaks/sparks and switch off overturned car ignition',
              'safeTextAr': 'الاقتراب بحذر، فحص رائحة الوقود المتسرب، وإطفاء مفتاح محرك السيارة المنقلبة',
              'safeTextEn': 'Approach carefully, check for fuel leaks/fumes, and turn off overturned car ignition key',
              'safeExpAr': 'إجراء حيوي؛ إيقاف السويتش يمنع حدوث شرارة تشعل البنزين المنسكب على السقف.',
              'safeExpEn': 'Vital safety step; turning off ignition prevents sparks igniting spilled fuel.',
              'safeOutAr': 'أطفأت سويتش المحرك للمحطة 3.',
              'safeOutEn': 'Turned off overturned car ignition for Station 3.',
              'unsafeTextAr': 'إشعال سيجارة أو استخدام كشاف ولاعة قرب السيارة المنقلبة',
              'unsafeTextEn': 'Light a cigarette near overturned car leaking gas',
              'unsafeExpAr': 'خطأ كوارثي؛ أبخرة الوقود المتجمعة تحت السقف تشتعل فوراً.',
              'unsafeExpEn': 'Catastrophic error; fuel vapors trapped under inverted chassis ignite instantly.',
              'unsafeOutAr': 'حدث اشتعال وقود.',
              'unsafeOutEn': 'Fuel vapor ignited.',
            },
            {
              'sitAr': 'الركاب معلقون بأحزمة الأمان داخل المركبة المنقلبة. كيف تثبت المصاب؟',
              'sitEn': 'Occupants suspended upside down by seatbelts. How to support victim?',
              'hintAr': 'دعم وتثبيت ظهر ورأس المصاب قبل فك حزام الأمان لتفادي كسور الرقبة',
              'hintEn': 'Support victim head and back before releasing seatbelt to prevent neck fall',
              'safeTextAr': 'دعم وإسناد ظهر ورأس المصاب بيديك قبل الضغط على زر فك حزام الأمان',
              'safeTextEn': 'Support victim head/torso with hands before pressing seatbelt release button',
              'safeExpAr': 'تكتيك طب حوادث ممتاز؛ فك الحزام دون إسناد يسبب سقوط المصاب على رأسه بالفقرات.',
              'safeExpEn': 'Pro trauma move; unbuckling suspended victims without support drops them on neck.',
              'safeOutAr': 'أسندت المصاب وفككت الحزام للمحطة 4.',
              'safeOutEn': 'Supported torso and unbuckled for Station 4.',
              'unsafeTextAr': 'فك حزام الأمان فجأة والمصاب معلق دون إسناد',
              'unsafeTextEn': 'Press seatbelt release button suddenly while victim hangs unsupported',
              'unsafeExpAr': 'خطأ؛ الفك المفاجئ يسبب سقوط ثقل الجسد على الرقبة المنكسرة.',
              'unsafeExpEn': 'Error; sudden unbuckling drops full body weight onto potentially fractured spine.',
              'unsafeOutAr': 'سقط المصاب على رأسه.',
              'unsafeOutEn': 'Victim dropped on neck.',
            },
            {
              'sitAr': 'إخراج المصاب من المركبة المنقلبة. متى تخرجه ومتى تنتظر الدفاع المدني؟',
              'sitEn': 'Extracting victim from overturned car. When to wait for Civil Defense?',
              'hintAr': 'عدم إخراج المصاب إلا عند وجود حريق، والانتظار لفرق الإنقاذ والمقصوصات',
              'hintEn': 'Do NOT extract unless fire threatens; wait for CD hydraulic jaws of life',
              'safeTextAr': 'إبقاء المصاب مثبتاً والانتظار لفرقة الدفاع المدني (قص السقف) إلا لخطورة حريق',
              'safeTextEn': 'Keep victim stabilized in place waiting for Civil Defense hydraulic jaws unless fire',
              'safeExpAr': 'قاعدة إنقاذ ذهبية؛ استخدام مقصوصات الهيدروليك يمنع مضاعفات الشلل عند الإخراج.',
              'safeExpEn': 'Golden rescue rule; hydraulic cutters remove roof safely without worsening spinal trauma.',
              'safeOutAr': 'ثبّت المصاب بانتظار المقصوصات للمحطة 5.',
              'safeOutEn': 'Stabilized victim for CD cutters for Station 5.',
              'unsafeTextAr': 'سحب المصاب بقوة ولويه للخروج عبر النافذة المكسورة',
              'unsafeTextEn': 'Twist and yank victim violently through broken side window',
              'unsafeExpAr': 'خطأ؛ سحب الجسد الملتوي يسبب قطع النخاع الشوكي.',
              'unsafeExpEn': 'Error; twisting and yanking spinal trauma victim severs spinal cord.',
              'unsafeOutAr': 'تسببت في مضاعفات الحبل الشوكي.',
              'unsafeOutEn': 'Severed spinal cord.',
            },
            {
              'sitAr': 'وصول فرقة الإنقاذ المائي والمقصوصات (998) والهلال الأحمر (997). ما الإجراء؟',
              'sitEn': '998 Rescue and 997 Paramedics arrive on scene. Final handoff?',
              'hintAr': 'إبلاغ المسعف بحالة وعي المصاب وأماكن الألم وتسهيل مسار المقصوصات',
              'hintEn': 'Brief paramedics on victim consciousness & pain spots; clear path for cutters',
              'safeTextAr': 'تزويد المسعفين بتقرير سريع عن علامات وعي المصاب وأماكن النزيف الواضحة',
              'safeTextEn': 'Brief 997 paramedics on victim responsiveness, bleeding sites, and time of impact',
              'safeExpAr': 'إتمام ناجح؛ التقرير السريع يسرع عملية التثبيت بالرقبة الخشبية والنقل الفوري.',
              'safeExpEn': 'Successful completion; concise brief speeds cervical collar placement & IV setup.',
              'safeOutAr': 'أكملت محطات التعامل مع انقلاب المركبة بنجاح!',
              'safeOutEn': 'Successfully completed vehicle rollover scenario!',
              'unsafeTextAr': 'عرقلة عمل رجال الإنقاذ والتصوير بالجوال ملاصقاً للحادث',
              'unsafeTextEn': 'Stand inside rescue perimeter filming closeup videos blocking paramedics',
              'unsafeExpAr': 'خطأ؛ عرقلة فرق الإسعاف تضيع الدقائق الذهبية لإنقاذ مصابي الحوادث.',
              'unsafeExpEn': 'Error; blocking rescue crew wastes golden minutes of critical trauma care.',
              'unsafeOutAr': 'أعقت عمل الفرق الطبية.',
              'unsafeOutEn': 'Obstructed emergency trauma team.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_6',
          categoryId: 'traffic',
          titleAr: 'دهس مشاة على طريق غير مخصص',
          titleEn: 'Pedestrian Hit & Run Emergency Response',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حوادث دهس المشاة وتقديم الإسعاف الأولي.',
          descriptionEn: 'Interactive 5-station scenario for pedestrian crash first aid.',
          difficulty: 'متوسط',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'تعرض شخص للدهس على الطريق أثناء عبوره. ما أول تصرف بحذر؟',
              'sitEn': 'Pedestrian hit by car while crossing road. Immediate first step?',
              'hintAr': 'إيقاف سيارتك بحاوية حماية لمنع دهس المصاب مرة أخرى من السيارات القادمة',
              'hintEn': 'Park your car as a protective shield upstream to protect victim from oncoming traffic',
              'safeTextAr': 'إيقاف مركبتك كدرع حماية قبل المصاب وتفعيل أضواء التحذير لتنبيه السيارات',
              'safeTextEn': 'Park your vehicle upstream as a barrier shield and turn hazard lights on to warn traffic',
              'safeExpAr': 'تصرف ممتاز؛ درع المركبة يمنع وقوع دهس ثانٍ للمصاب المستلقي على الإسفلت.',
              'safeExpEn': 'Excellent response; vehicle barrier shields prone victim from secondary strikes.',
              'safeOutAr': 'أمّنت المصاب بمسار الشارع للمحطة 2.',
              'safeOutEn': 'Shielded victim from oncoming traffic for Station 2.',
              'unsafeTextAr': 'الوقوف بجانب المصاب دون أضواء تحذيرية أو حماية بالطريق',
              'unsafeTextEn': 'Stand right beside victim on active lane without hazard lights',
              'unsafeExpAr': 'خطأ قاتل؛ الوقوف بمنتصف الطريق المظلم يعرضك والمصاب للدهس المباشر.',
              'unsafeExpEn': 'Fatal error; standing on dark active lanes exposes helper & victim to fast traffic.',
              'unsafeOutAr': 'تعرضت لخطر دهس ثانٍ.',
              'unsafeOutEn': 'Secondary hit-and-run hazard.',
            },
            {
              'sitAr': 'فحص استجابة ومجرى تنفس المصاب على الإسفلت. كيف تفحص الحيوية؟',
              'sitEn': 'Checking victim responsiveness & airway on asphalt. Vital signs check?',
              'hintAr': 'النداء على المصاب وفحص حركة الصدر دون تحريك الرأس أو الرقبة',
              'hintEn': 'Call out to victim and check chest movement without turning head/neck',
              'safeTextAr': 'النداء بصوت واضح على المصاب وفحص حركة الصدر وتثبيت الرأس بين يديك',
              'safeTextEn': 'Speak clearly to victim, watch chest rise/fall, and gently hold head inline',
              'safeExpAr': 'إجراء طب حوادث سليم؛ تثبيت الرأس يمنع تلف العمود الفقري.',
              'safeExpEn': 'Correct trauma protocol; manual inline head stabilization protects cervical spine.',
              'safeOutAr': 'فحصت العلامات الحيوية وثبّت الرأس للمحطة 3.',
              'safeOutEn': 'Checked vitals and stabilized head for Station 3.',
              'unsafeTextAr': 'هز رأس المصاب بعنف وتدويره يميناً ويساراً',
              'unsafeTextEn': 'Shake victim head violently side to side to check waking up',
              'unsafeExpAr': 'خطأ؛ هز الرأس قد يسبب قطع الحبل الشوكي عند وجود كسر رقبي.',
              'unsafeExpEn': 'Error; shaking head severs spinal cord if cervical vertebrae are fractured.',
              'unsafeOutAr': 'تسببت بمضاعفات بالرقبة.',
              'unsafeOutEn': 'Cervical spine injury worsened.',
            },
            {
              'sitAr': 'ملاحظة نزيف شرياني بغزارة من ساق المصاب. كيف توقف النزيف الحاد؟',
              'sitEn': 'Profuse arterial bleeding noticed from victim leg. How to stop severe bleeding?',
              'hintAr': 'الضغط المباشر على موضع النزيف بشاش معقم أو قماش نظيف',
              'hintEn': 'Apply direct firm pressure on wound using sterile gauze or clean cloth',
              'safeTextAr': 'الضغط المباشر والقوي على موضع النزيف بقماش نظيف أو شاش معقم دون رفعه',
              'safeTextEn': 'Apply firm continuous direct pressure on bleeding site using clean cloth/gauze',
              'safeExpAr': 'تكتيك إسعافي ذهبي؛ الضغط المباشر يوقف 90% من حالات النزيف الشرياني.',
              'safeExpEn': 'Golden first aid tactic; continuous direct pressure controls 90% of arterial bleeding.',
              'safeOutAr': 'سيطرت على النزيف بالضغط للمحطة 4.',
              'safeOutEn': 'Controlled severe bleeding for Station 4.',
              'unsafeTextAr': 'ترك النزيف دون ضغط وسكب الماء على الجرح المفتوح',
              'unsafeTextEn': 'Leave wound uncompressed pouring bottled water into deep open gash',
              'unsafeExpAr': 'خطأ؛ سكب الماء يمنع تجلط الدم ويسبب هبوط صدمة النزيف.',
              'unsafeExpEn': 'Error; pouring water prevents blood clotting accelerating hemorrhagic shock.',
              'unsafeOutAr': 'استمر النزيف الشديد.',
              'unsafeOutEn': 'Arterial bleeding accelerated.',
            },
            {
              'sitAr': 'الاتصال بالهلال الأحمر (997) وأمن الطرق/الشرطة (911). ماذا تبلغ؟',
              'sitEn': 'Calling Red Crescent 997 & Police 911. Dispatch details?',
              'hintAr': 'تحديد اسم الشارع، معلم قريب، درجة وعي المصاب، ونزيف الجراح',
              'hintEn': 'Provide street name, nearby landmark, victim consciousness & bleeding status',
              'safeTextAr': 'إعطاء الموقع بدقة، وذكر حالة حادث دهس المشاة ودرجة وعي المصاب والنزيف',
              'safeTextEn': 'Relay exact location, landmark, hit-and-run status, consciousness level & bleeding',
              'safeExpAr': 'بلاغ نموذجية؛ يساعد على توجيه سيارة إسعاف عناية مركزة (Advanced Life Support).',
              'safeExpEn': 'Model dispatch; enables 997 operators to route Advanced Life Support (ALS) rig.',
              'safeOutAr': 'أبلغت الإسعاف والشرطة للمحطة 5.',
              'safeOutEn': 'Reported to 997 & 911 for Station 5.',
              'unsafeTextAr': 'الإبلاغ دون ذكر حالة وعي المصاب أو وجود نزيف حاد',
              'unsafeTextEn': 'Call reporting minor accident without mentioning severe bleeding or unconsciousness',
              'unsafeExpAr': 'خطأ؛ غياب تفاصيل النزيف يقلل أولوية استجابة سيارات الإسعاف.',
              'unsafeExpEn': 'Error; omitting severe trauma details lowers dispatch priority.',
              'unsafeOutAr': 'تأخرت سيارة العناية المركزة.',
              'unsafeOutEn': 'ALS unit dispatch delayed.',
            },
            {
              'sitAr': 'وصول سيارة الإسعاف 997 وتسليم المصاب. ما الخطوة النهائية؟',
              'sitEn': '997 ALS Ambulance arrives. Final medical handoff protocol?',
              'hintAr': 'تزويد المسعف بتفاصيل وقت الحادث، كمية الدم المفقودة، والإسعافات المطبقة',
              'hintEn': 'Brief paramedics on time of impact, estimated blood loss, & direct pressure applied',
              'safeTextAr': 'تزويد المسعفين بتقرير عن الضغط المباشر المطبق، وقت النزيف، والعلامات الحيوية',
              'safeTextEn': 'Brief 997 paramedics on direct pressure duration, blood loss, & responsiveness',
              'safeExpAr': 'إتمام ناجح؛ يساعد التقرير المسعف على البدء الفوري بنقل الدم والمحاليل.',
              'safeExpEn': 'Successful completion; detailed handoff allows instant IV fluid/blood protocols.',
              'safeOutAr': 'أكملت محطات إسعاف دهس المشاة بنجاح!',
              'safeOutEn': 'Successfully completed pedestrian crash scenario!',
              'unsafeTextAr': 'إزالة الضماد والضغط المباشر فجأة قبل وصول المسعفين',
              'unsafeTextEn': 'Remove direct pressure gauze right before paramedics step up',
              'unsafeExpAr': 'خطأ؛ إزالة الضغط تسبب عودة النزيف الشرياني الحاد.',
              'unsafeExpEn': 'Error; lifting direct pressure breaks formed clot causing massive re-bleeding.',
              'unsafeOutAr': 'تجدد النزيف الشديد.',
              'unsafeOutEn': 'Arterial bleeding reignited.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_7',
          categoryId: 'traffic',
          titleAr: 'تعطل مثبت السرعة على الطريق السريع',
          titleEn: 'Stuck Cruise Control Highway Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تعطل وسلسلة إجراءات إيقاف مثبت السرعة.',
          descriptionEn: 'Interactive 5-station scenario for stuck cruise control emergencies.',
          difficulty: 'صعب',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'تعطل زر إلغاء مثبت السرعة واستمرت السيارة بالمسير بسرعة 120 كم/س. ما أول خطوة؟',
              'sitEn': 'Cruise control cancel button stuck; car stays fixed at 120 km/h. First step?',
              'hintAr': 'التركيز على الطريق، تفعيل الفلاشر، والضغط على زر Cancel أو الفرامل بثبات',
              'hintEn': 'Stay calm, turn on hazard lights, press Cancel button or hold brake firmly',
              'safeTextAr': 'التزام الهدوء، التركيز على مسار الطريق، وتفعيل أضواء التحذير الرباعية (الفلاشر)',
              'safeTextEn': 'Stay calm, focus on road ahead, and switch on hazard emergency flasher lights',
              'safeExpAr': 'تصرف ممتاز؛ الفلاشر ينبه جميع السيارات بوجود حالة طارئة بمركبتك.',
              'safeExpEn': 'Excellent first step; hazard lights warn surrounding motorists of emergency vehicle.',
              'safeOutAr': 'نبهت السيارات بالطريق للمحطة 2.',
              'safeOutEn': 'Alerted surrounding traffic for Station 2.',
              'unsafeTextAr': 'الارتباك والقفز من السيارة أثناء تسارعها بالخط السريع',
              'unsafeTextEn': 'Panic and jump out of moving car at 120 km/h',
              'unsafeExpAr': 'خطأ قاتل؛ القفز من السيارة بالسرعات العالية يسبب الوفاة الفورية.',
              'unsafeExpEn': 'Fatal error; jumping out of a 120 km/h vehicle causes immediate death.',
              'unsafeOutAr': 'تعرضت لإصابة قاتلة.',
              'unsafeOutEn': 'Fatal jump off moving car.',
            },
            {
              'sitAr': 'استمرار تعطل مثبت السرعة. كيف تخفف الحركة عبر قير السيارة (N)?',
              'sitEn': 'Cruise control still engaged. How to disengage drive using transmission (N)?',
              'hintAr': 'تحويل قير السيارة إلى وضعية الفاضي (Neutral N)',
              'hintEn': 'Shift transmission gear lever into Neutral (N) position',
              'safeTextAr': 'وضع قير السيارة في وضعية الفاضي (Neutral N) لفصل التغذية عن المحرك',
              'safeTextEn': 'Shift transmission gear lever smoothly into Neutral (N) to disconnect engine drive',
              'safeExpAr': 'تكتيك إنقاذ ذهبي؛ تحويل القير لـ N يفصل قوة المحرك عن العجلات فوراً.',
              'safeExpEn': 'Golden rescue tactic; shifting into N disconnects engine power from drive wheels instantly.',
              'safeOutAr': 'فصلت القير على وضعية N للمحطة 3.',
              'safeOutEn': 'Shifted transmission into Neutral for Station 3.',
              'unsafeTextAr': 'سحب مفتاح السويتش وإقفال عجلة القيادة',
              'unsafeTextEn': 'Turn key off and remove ignition key while moving 120 km/h',
              'unsafeExpAr': 'خطأ؛ سحب المفتاح يقفل عجلة القيادة ويمنعك من توجيه المركبة.',
              'unsafeExpEn': 'Error; pulling key locks steering wheel column resulting in violent crash.',
              'unsafeOutAr': 'انقفل المقود وانحرفت السيارة.',
              'unsafeOutEn': 'Steering wheel locked column.',
            },
            {
              'sitAr': 'إذا رفض القير التحول لـ N، كيف تستخدم زر إيقاف المحرك (Push Start)؟',
              'sitEn': 'If transmission refuses Neutral shift. How to use Push Start button?',
              'hintAr': 'الضغط المستمر على زر التشغيل (Engine Start) لمدة 3 ثوان متصلة',
              'hintEn': 'Press and hold Engine Start/Stop button continuously for 3 full seconds',
              'safeTextAr': 'الضغط المستمر والمتصل على زر (Engine Start) لمدة 3 ثوانٍ لإطفاء المحرك طارئاً',
              'safeTextEn': 'Press and hold Push Start/Stop button continuously for 3 full seconds to emergency stop',
              'safeExpAr': 'برمجة أمان حاسمة؛ الضغط المتصل لـ 3 ثوانٍ يفصل المحرك بالسيارات الحديثة.',
              'safeExpEn': 'Critical safety logic; holding Push Start for 3 seconds forces emergency engine shutdown.',
              'safeOutAr': 'أطفأت المحرك بالزر للمحطة 4.',
              'safeOutEn': 'Emergency shut engine via button for Station 4.',
              'unsafeTextAr': 'الضغط على زر التشغيل ضغطات سريعة متقطعة',
              'unsafeTextEn': 'Tap Push Start button rapidly in short bursts',
              'unsafeExpAr': 'خطأ؛ الضغط السريع المتقطع لا يفعل برنامج الإطفاء الطارئ.',
              'unsafeExpEn': 'Error; rapid tapping fails to trigger computer emergency shutdown logic.',
              'unsafeOutAr': 'لم ينطفئ المحرك.',
              'unsafeOutEn': 'Engine failed to shut off.',
            },
            {
              'sitAr': 'انطفأ المحرك وفصلت القوة. كيف توقف المركبة بالأكتاف الآمنة؟',
              'sitEn': 'Engine shut off and drive power cut. How to steer car onto shoulder?',
              'hintAr': 'التوجيه الحذر نحو الكتف الأيمن مع العلم أن المقود والفرامل ستكون أثقل',
              'hintEn': 'Steer carefully to right shoulder knowing steering and brakes will feel heavier',
              'safeTextAr': 'التوجيه باليدين نحو الكتف الأيمن والضغط القوي بثبات على دواسة الفرامل',
              'safeTextEn': 'Steer firmly with both hands to right shoulder applying heavy steady brake pressure',
              'safeExpAr': 'توجيه آمن؛ توقف الباور تجعل المقود والفرامل أثقل ولكنها تعمل ميكانيكياً.',
              'safeExpEn': 'Safe steering; power assist loss makes steering/brakes heavy but fully functional.',
              'safeOutAr': 'أوقفت المركبة بالكتف الأيمن للمحطة 5.',
              'safeOutEn': 'Parked on right shoulder for Station 5.',
              'unsafeTextAr': 'ترك المقود والهلع دون توجيه المركبة',
              'unsafeTextEn': 'Let go of steering wheel panicking without directional control',
              'unsafeExpAr': 'خطأ؛ ترك المقود يجعل المركبة تنحرف نحو حارات السيارات.',
              'unsafeExpEn': 'Error; abandoning steering causes car to drift into active high-speed lanes.',
              'unsafeOutAr': 'انحرفت المركبة.',
              'unsafeOutEn': 'Vehicle drifted off course.',
            },
            {
              'sitAr': 'توقف المركبة بسلام وتأمين الركاب. ما الخطوة الوقائية والتنسيقية؟',
              'sitEn': 'Car stopped safely on shoulder. Post-emergency coordination step?',
              'hintAr': 'الاتصال بأمن الطرق (996/911) ونقل المركبة بسطحة لفحص الكمبيوتر',
              'hintEn': 'Contact Highway Security 996 and tow car to dealer for computer diagnostic',
              'safeTextAr': 'الاتصال بـ 996 ونقل السيارة بسطحة لوكالة الصيانة لفحص برمجة مثبت السرعة',
              'safeTextEn': 'Call 996 Highway Security and tow car to authorized service center for computer check',
              'safeExpAr': 'إتمام كامل؛ الفحص البرمجي يضمن عدم تكرار تعطل المثبت مستقبلاً.',
              'safeExpEn': 'Complete resolution; computer diagnostic identifies and fixes ECU cruise control bugs.',
              'safeOutAr': 'أكملت محطات التعامل مع تعطل مثبت السرعة بنجاح!',
              'safeOutEn': 'Successfully completed cruise control emergency scenario!',
              'unsafeTextAr': 'إعادة تشغيل السيارة ومواصلة القيادة بالمثبت التالف',
              'unsafeTextEn': 'Restart car immediately and re-engage faulty cruise control system',
              'unsafeExpAr': 'خطأ؛ استخدام مثبت سرعة تالف يعرض حياتك للخطر الكارثي.',
              'unsafeExpEn': 'Error; re-engaging known faulty cruise control risks catastrophic high-speed crash.',
              'unsafeOutAr': 'تجدد تعطل مثبت السرعة.',
              'unsafeOutEn': 'Faulty cruise control stuck again.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_8',
          categoryId: 'traffic',
          titleAr: 'اصطدام بجمل سائب بالليل',
          titleEn: 'Nighttime Stray Camel Highway Collision',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجنب والتعامل مع حوادث الجمال السائبة بالطرق السريعة.',
          descriptionEn: 'Interactive 5-station scenario for stray camel highway hazards at night.',
          difficulty: 'صعب',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'أثناء القيادة ليلاً على طريق غير مضاء ظهرت هيئة جمل سائب على الطريق. ما أول حركة؟',
              'sitEn': 'Stray camel outline appears suddenly on unlit rural highway at night. First step?',
              'hintAr': 'استخدام العالي المخفي والضغط الثابت على الفرامل دون الانحراف المفاجئ',
              'hintEn': 'Apply firm steady brakes; steer around camel rear if possible, do NOT swerve violently',
              'safeTextAr': 'الضغط الثابت والقوي على دواسة الفرامل والتوجيه نحو خلف الجمل إذا لزم',
              'safeTextEn': 'Apply firm heavy brakes while steering smoothly toward the REAR of the camel',
              'safeExpAr': 'تكتيك أمني معتمد؛ الجمل يتحرك للأمام دائماً والتوجيه لخلفه يجنبك الاصطدام.',
              'safeExpEn': 'Certified safety tactic; camels move forward; steering behind their rear avoids impact.',
              'safeOutAr': 'تفاديت الجمل بحكمة للمحطة 2.',
              'safeOutEn': 'Steered behind camel safely for Station 2.',
              'unsafeTextAr': 'الانحراف المفاجئ الشديد بعجلة القيادة نحو اليسار (Swerving)',
              'unsafeTextEn': 'Swerve violently at high speed into left oncoming lane',
              'unsafeExpAr': 'خطأ قاتل؛ الانحراف السريع بالسرعات العالية يسبب انقلاب المركبة فجأة.',
              'unsafeExpEn': 'Fatal error; sudden violent swerving at high speed causes vehicle rollover.',
              'unsafeOutAr': 'انقلبت المركبة بالطريق.',
              'unsafeOutEn': 'Vehicle rolled over on highway.',
            },
            {
              'sitAr': 'إذا تعذر التفادي وحدث اصطدام بالجمل. كيف تحمي رأسك وجسدك بالكابينة؟',
              'sitEn': 'If collision is unavoidable. How to brace body inside cabin?',
              'hintAr': 'الانخفاض لمستوى عجلة القيادة لحماية الرأس من دخول كتلة الجمل للزجاج',
              'hintEn': 'Duck low toward steering wheel level to protect head from windshield collapse',
              'safeTextAr': 'الانخفاض أسفل مستوى عجلة القيادة لحماية الرأس والرقبة من تهشم الزجاج',
              'safeTextEn': 'Duck down below dashboard level shielding head and neck from collapsing glass',
              'safeExpAr': 'تكتيك نجاة حرج؛ الاصطدام بالجمل يقطع أرجل الجمل وتسقط كتلته الضخمة فوق السقف.',
              'safeExpEn': 'Critical survival tactic; hitting camels breaks long legs causing torso to crush roof.',
              'safeOutAr': 'حميت الرأس من الانهيار للمحطة 3.',
              'safeOutEn': 'Ducked low protecting head for Station 3.',
              'unsafeTextAr': 'الجلوس واقفا والنظر مباشرة نحو الزجاج الأمامي',
              'unsafeTextEn': 'Sit fully upright staring straight into collapsing front windshield',
              'unsafeExpAr': 'خطأ؛ سقوط جسم الجمل على السقف يسبب إصابات قاتلة بالرأس والرقبة.',
              'unsafeExpEn': 'Error; heavy camel torso crushes front roof pillars causing fatal head/neck trauma.',
              'unsafeOutAr': 'تعرض الرأس لإصابة.',
              'unsafeOutEn': 'Severe head trauma from roof collapse.',
            },
            {
              'sitAr': 'توقف المركبة بعد الاصطدام. كيف تتأكد من سلامة الركاب وإخلاء الكابينة؟',
              'sitEn': 'Car stopped post-impact. How to check passengers & clear cabin?',
              'hintAr': 'فحص استجابة الركاب، التوجه للكتف الترابي، وتفعيل أضواء التحذير',
              'hintEn': 'Check passenger response, move behind guardrail, activate hazard flashers',
              'safeTextAr': 'فحص استجابة الركاب، الخروج وتوجيه الجميع خلف الحاجز الخرساني وتفعيل الفلاشر',
              'safeTextEn': 'Audit passenger responsiveness, exit cabin to stand behind guardrail, keep hazards on',
              'safeExpAr': 'إجراء أمني رائع؛ الخروج خلف الحاجز يحمي المصابين من السيارات القادمة بالليل.',
              'safeExpEn': 'Great safety step; moving behind guardrails protects survivors from night traffic.',
              'safeOutAr': 'وقفت الأسرة خلف الحاجز للمحطة 4.',
              'safeOutEn': 'Passengers safe behind guardrail for Station 4.',
              'unsafeTextAr': 'البقاء جالسين بوسط الطريق المظلم داخل المركبة التالفة',
              'unsafeTextEn': 'Sit inside dark wrecked car parked mid-lane on unlit highway',
              'unsafeExpAr': 'خطأ؛ البقاء بالمركبة المظلمة بوسط الطريق ينطوي على خطورة اصطدام خلفي.',
              'unsafeExpEn': 'Error; sitting in unlit disabled car in middle of dark road invites high speed rear crashes.',
              'unsafeOutAr': 'تعرضت لاصطدام خلفي.',
              'unsafeOutEn': 'Struck by rear oncoming vehicle.',
            },
            {
              'sitAr': 'الاتصال بأمن الطرق (996/911) والهلال الأحمر (997). ماذا تبلغ؟',
              'sitEn': 'Calling Highway Security 996 & Red Crescent 997. What dispatch details to provide?',
              'hintAr': 'تحديد اسم الطريق، اتجاه المسار، الكيلومتر الدقيق، ووجود الجمل بالطريق',
              'hintEn': 'Provide highway name, travel direction, exact KM marker, & stray animal hazard',
              'safeTextAr': 'إعطاء اسم الطريق السريع، الكيلومتر، اتجاه السير، وجود الجمل بالطريق، وحالة المصابين',
              'safeTextEn': 'Report highway name, exact KM marker, direction, stray camel hazard, & injuries to 996/997',
              'safeExpAr': 'بلاغ شمولية؛ يساعد دوريات أمن الطرق على سحب الجمل وتنبيه المسارات.',
              'safeExpEn': 'Comprehensive report; enables highway patrol to clear animal and warn oncoming traffic.',
              'safeOutAr': 'أبلغت 996 و997 للمحطة 5.',
              'safeOutEn': 'Reported details to 996/997 for Station 5.',
              'unsafeTextAr': 'مغادرة الموقع دون إبلاغ أمن الطرق عن الجمل الملقى بالطريق',
              'unsafeTextEn': 'Drive away leaving dead stray camel lying across dark active highway lane',
              'unsafeExpAr': 'خطأ؛ ترك الجمل بالطريق يسبب حوادث لسيارات قادمة أخرى.',
              'unsafeExpEn': 'Error; leaving dead animal on dark active lanes causes secondary fatal crashes.',
              'unsafeOutAr': 'تسبب الجمل بحوادث أخرى.',
              'unsafeOutEn': 'Secondary crashes caused by stray animal.',
            },
            {
              'sitAr': 'نقل المصابين وسحب السيارة. ما الحلول الوقائية الوطنية ضد الجمال السائبة؟',
              'sitEn': 'Passengers cared for. National preventive solutions against stray camels?',
              'hintAr': 'التزام السياج الشجري، تركيب الشريحة الإلكترونية للإبل، والقيادة بحذر بالليل',
              'hintEn': 'Advocate for highway perimeter fencing, microchipping camels, & cautious night driving',
              'safeTextAr': 'تخفيض السرعة ليلاً بالخطوط غير المضاءة والاستفادة من السياج السلكي الواقي',
              'safeTextEn': 'Maintain reduced speed on unlit rural highways and rely on microchipped camel fences',
              'safeExpAr': 'إتمام كامل؛ القيادة الحذرة بالليل والسياج الواقي يمنعان حوادث الإبل بنسبة 90%.',
              'safeExpEn': 'Complete resolution; cautious night speeds and highway fencing prevent 90% of stray camel crashes.',
              'safeOutAr': 'أكملت محطات نجاة حوادث الجمال بنجاح!',
              'safeOutEn': 'Successfully completed stray camel collision scenario!',
              'unsafeTextAr': 'القيادة بالسرعة العالية 140 كم/س ليلاً بالخطوط البرية',
              'unsafeTextEn': 'Drive 140 km/h with low beam headlights on unlit desert highways',
              'unsafeExpAr': 'خطأ؛ السرعة العالية بالليل تفوق مدى رؤية أضواء السيارة.',
              'unsafeExpEn': 'Error; high night speeds overdrive headlight reach leaving zero stopping distance.',
              'unsafeOutAr': 'تجاوزت مدى أضواء السيارات.',
              'unsafeOutEn': 'Overdrove headlight stopping distance.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_traffic_9',
          categoryId: 'traffic',
          titleAr: 'سقوط حمولة شاحنة أمام المركبة',
          titleEn: 'Highway Truck Cargo Spillage Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تساقط حمولة الشاحنات والأجسام الصلبة.',
          descriptionEn: 'Interactive 5-station scenario for highway truck cargo spillage hazards.',
          difficulty: 'متوسط',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          stations: [
            {
              'sitAr': 'أثناء تسير خلف شاحنة بالخط السريع سقطت أخشاب وحاوية من حمولتها أمامك. ما أول تصرف؟',
              'sitEn': 'Cargo wooden pallets drop off truck ahead onto your lane. Immediate action?',
              'hintAr': 'تخفيف السرعة، تفعيل الفلاشر، والانحراف للمسار الآمن الخالي بحذر',
              'hintEn': 'Brake smoothly, turn on hazard lights, & steer into open clear adjacent lane',
              'safeTextAr': 'الضغط المتزن على الفرامل، تفعيل أضواء الفلاشر، والتوجيه للمسار الآمن الخالي',
              'safeTextEn': 'Apply smooth steady brakes, turn hazard lights on, & steer into clear adjacent lane',
              'safeExpAr': 'تصرف ممتاز؛ الانحراف المرن للمسار الخالي يجنبك الارتطام بالحمولة المباشرة.',
              'safeExpEn': 'Excellent response; smooth lane change avoids direct impact with heavy fallen cargo.',
              'safeOutAr': 'تجنبت الحمولة للمحطة 2.',
              'safeOutEn': 'Avoided fallen cargo safely for Station 2.',
              'unsafeTextAr': 'الانحراف المفاجئ الحاد نحو المسار الأيسر دون فحص المرايا',
              'unsafeTextEn': 'Swerve violently into left lane without checking side mirrors',
              'unsafeExpAr': 'خطأ؛ الانحراف العشوائي يسبب الاصطدام بسيارات مسرعة بالمسار المجهول.',
              'unsafeExpEn': 'Error; blind violent swerving side-swipes high speed cars in adjacent lane.',
              'unsafeOutAr': 'اصطدمت بسيارة مجاورة.',
              'unsafeOutEn': 'Sideswiped car in adjacent lane.',
            },
            {
              'sitAr': 'تعذر التفادي التام ودهست بقايا الخشب وتضررت عجلة القيادة. كيف تتوقف؟',
              'sitEn': 'Ran over minor debris damaging tire/undercarriage. How to bring car to safe stop?',
              'hintAr': 'التمسك بالمقود جيداً والانتقال التدريجي نحو الكتف الأيمن',
              'hintEn': 'Hold wheel firmly and transition smoothly to far right shoulder',
              'safeTextAr': 'التثبيت الجيد بعجلة القيادة والانتقال التدريجي الهادئ نحو الأكتاف الترابية الأيمن',
              'safeTextEn': 'Hold steering wheel firmly and transition smoothly across lanes to right shoulder',
              'safeExpAr': 'تكتيك سليم؛ الانتقال المرن يمنع فقدان التوازن بعد الدهس على الأخشاب.',
              'safeExpEn': 'Correct tactic; smooth lane transitions prevent control loss after debris impact.',
              'safeOutAr': 'أوقفت المركبة بالأكتاف للمحطة 3.',
              'safeOutEn': 'Parked on right shoulder for Station 3.',
              'unsafeTextAr': 'التوقف الفوري المفاجئ في حارة السير الوسطى',
              'unsafeTextEn': 'Slam brakes stopping dead in center active travel lane',
              'unsafeExpAr': 'خطأ؛ التوقف بوسط الطريق ينطوي على خطورة تصادم متسلسل.',
              'unsafeExpEn': 'Error; stopping dead in travel lane invites high-speed chain collisions.',
              'unsafeOutAr': 'تعرضت لاصطدام خلفي.',
              'unsafeOutEn': 'Rear-ended by active traffic.',
            },
            {
              'sitAr': 'تأمين الخلفية وتنبيه باقي السيارات من الحمولة الساقطة بالشارع. الإجراء؟',
              'sitEn': 'Securing site & warning oncoming traffic of cargo debris on road. Action?',
              'hintAr': 'وضع مثلث السلامة العاكس والاتصال بأمن الطرق (996/911)',
              'hintEn': 'Set reflective triangle 100m back & report cargo hazard to 996/911',
              'safeTextAr': 'وضع مثلث السلامة على مسافة 100م والاتصال الفوري بـ (996 أمن الطرق)',
              'safeTextEn': 'Position warning triangle 100m upstream & dial 996 Highway Security dispatch',
              'safeExpAr': 'تأمين أمني رائع؛ المثلث والأمن ينبهان الشاحنات القادمة ويمسحان الطريق.',
              'safeExpEn': 'Great safety step; triangle warning & 996 alert dispatch sweepers to clear debris.',
              'safeOutAr': 'أمّنت الطريق وأبلغت 996 للمحطة 4.',
              'safeOutEn': 'Secured scene and reported to 996 for Station 4.',
              'unsafeTextAr': 'النزول لوسط الخط السريع لجمع الأخشاب بيدك',
              'unsafeTextEn': 'Run onto active highway lane to pick up heavy wooden debris barehanded',
              'unsafeExpAr': 'خطأ؛ الجمع اليدوي بالخط السريع يسبب دهسك من السيارات المسرعة.',
              'unsafeExpEn': 'Error; walking on active high-speed highway lanes to pick up trash risks death.',
              'unsafeOutAr': 'تعرضت لخطر الدهس بالشارع.',
              'unsafeOutEn': 'Pedestrian strike hazard on highway.',
            },
            {
              'sitAr': 'وصول دوريات أمن الطرق (996). كيف تصف الشاحنة المتسببة بسقوط الحمولة؟',
              'sitEn': '996 Highway Security patrol arrives. How to describe fleeing truck?',
              'hintAr': 'إعطاء لوحة الشاحنة، لونها، اتجاه السير، ونوع الحمولة المسقطة',
              'hintEn': 'Provide truck plate number, color, direction of travel, & cargo type',
              'safeTextAr': 'تزويد رجال الأمن برقم لوحة الشاحنة، لون الكابينة، اتجاه السير، ونوع الحمولة',
              'safeTextEn': 'Provide patrol officers with truck license plate, cabin color, direction, & cargo details',
              'safeExpAr': 'بلاغ أمني دقيق؛ يتيح استقاط الشاحنة عند نقطة التفتيش التالية.',
              'safeExpEn': 'Accurate police report; enables next highway checkpoint to intercept fleeing truck.',
              'safeOutAr': 'أعطيت بيانات الشاحنة للمحطة 5.',
              'safeOutEn': 'Provided truck details to 996 for Station 5.',
              'unsafeTextAr': 'ملاحقة الشاحنة بسرعة جنونية 180 كم/س لإيقافها بنفسك',
              'unsafeTextEn': 'Chase truck recklessly at 180 km/h attempting to force it off road',
              'unsafeExpAr': 'خطأ؛ الملاحقة العنيفة تسبب حوادث مروعة وانقلاب السيارات.',
              'unsafeExpEn': 'Error; high-speed vigilante car chases cause catastrophic highway fatal crashes.',
              'unsafeOutAr': 'تعرضت لحادث ملاحقة.',
              'unsafeOutEn': 'High-speed chase accident.',
            },
            {
              'sitAr': 'تم سحب الحمولة وتأمين الطريق بالكامل. ما المعيار الوقائي للشاحنات؟',
              'sitEn': 'Road cleared and safe. National truck cargo safety standard?',
              'hintAr': 'التأكد من تربيع وتغطية الحمولة بالشراب والأربطة المعتمدة قبل الانطلاق',
              'hintEn': 'Ensure cargo is strapped, covered with tarpaulin, & secured before departure',
              'safeTextAr': 'إلزام جميع الشاحنات بتثبيت الحمولة بأحزمة حزام الصلب وتغطيتها بالطاربولين',
              'safeTextEn': 'Enforce mandatory heavy-duty cargo strapping and waterproof tarpaulin covers on all trucks',
              'safeExpAr': 'إتمام كامل؛ تربيع الحمولة والتغطية المحكمة يمنعان تساقط الأجسام بالطرق.',
              'safeExpEn': 'Complete resolution; proper cargo tie-down & tarpaulins eliminate highway drop hazards.',
              'safeOutAr': 'أكملت محطات التعامل مع تساقط الحمولة بنجاح!',
              'safeOutEn': 'Successfully completed truck cargo spillage scenario!',
              'unsafeTextAr': 'القيادة القريبة جداً خلف الشاحنات المحملة دون مسافة أمان',
              'unsafeTextEn': 'Tailgate closely behind loaded trucks with zero safety distance',
              'unsafeExpAr': 'خطأ؛ القيادة الملاصقة للشاحنات تقلل زاوية الرؤية وتصعب التفادي.',
              'unsafeExpEn': 'Error; tailgating trucks blinds forward vision giving zero time to dodge falling objects.',
              'unsafeOutAr': 'تعرضت لخطر الالتصاق بالشاحنة.',
              'unsafeOutEn': 'Tailgating cargo hazard.',
            },
          ],
        ),
      ];
}
