import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosElectric {
  static List<Scenario> get list => [
        // 1. Electric Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_1',
          categoryId: 'electric',
          titleAr: 'ماس كهربائي وصعق بالمنزل',
          titleEn: 'Home Electrical Short Circuit & Shock',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع الماس الكهربائي، فصل القواطع، وإنقاذ المصعوق.',
          descriptionEn: 'Interactive 5-station scenario for electrical short circuit and shock rescue.',
          difficulty: 'متوسط',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'تصاعد شرر وتصاعد رائحة احتراق من مقبس الكهرباء بالجدار. ما أول خطوة؟',
              'sitEn': 'Sparks and burning smell from wall outlet. Immediate action?',
              'hintAr': 'فصل القاطع الرئيسي لشبكة الكهرباء قبل لمس المقبس أو الأجهزة',
              'hintEn': 'Shut off main circuit breaker before touching outlet or appliances',
              'safeTextAr': 'التوجه للوحة التوزيع الرئيسية وفصل قاطع الكهرباء العام فوراً',
              'safeTextEn': 'Head to main panel and switch off main circuit breaker immediately',
              'safeExpAr': 'تصرف أساسي؛ قطع التيار من المصدر يعزل الخطر كلياً ويمنع نشوب حريق.',
              'safeExpEn': 'Primary response; shutting main breaker isolates hazard and prevents electrical fire.',
              'safeOutAr': 'فصلت الكهرباء بنجاح للمحطة 2.',
              'safeOutEn': 'Cut power successfully for Station 2.',
              'unsafeTextAr': 'محاولة سحب السلك المحترق باليد المباشرة من المقبس',
              'unsafeTextEn': 'Pull burning cord directly with bare hands from socket',
              'unsafeExpAr': 'خطأ جسيم؛ سحب السلك والكهرباء متصلة يعرضك للصعق المباشر.',
              'unsafeExpEn': 'Severe error; pulling live cord with bare hands causes direct electric shock.',
              'unsafeOutAr': 'تعرضت لشرر كهربائي.',
              'unsafeOutEn': 'Exposed to live spark hazard.',
            },
            {
              'sitAr': 'شخص ممسك بسلك مكشوف ويتعرض للصعق الكهربائي أمامك. كيف تسعفه؟',
              'sitEn': 'Person holding live wire receiving active electric shock. How to rescue?',
              'hintAr': 'عدم لمس المصاب مباشرة باليد، واستخدام أداة عازلة كعصا خشبية أو بلاستيكية لدفع السلك',
              'hintEn': 'Do NOT touch victim directly; use wooden/plastic non-conductive object to push wire',
              'safeTextAr': 'استخدام لوح خشبي جاف أو عصا بلاستيكية عازلة لفصل السلك عن يد المصاب',
              'safeTextEn': 'Use dry wooden board or plastic pole to pry live wire away from victim',
              'safeExpAr': 'إنقاذ احترافي؛ الأداة العازلة تمنع سريان التيار الكهربائي إلى جسمك.',
              'safeExpEn': 'Pro rescue; non-conductive tool breaks electrical circuit protecting rescuer.',
              'safeOutAr': 'فصلت السلك العاري للمحطة 3.',
              'safeOutEn': 'Separated live wire for Station 3.',
              'unsafeTextAr': 'الإمساك بيد المصاب بقوة لسحبه بعيداً عن السلك',
              'unsafeTextEn': 'Grab victim\'s hands directly with bare arms to pull away',
              'unsafeExpAr': 'خطأ قاتل؛ جسم الإنسان موصل للكهرباء وسينتقل التيار إليك فوراً.',
              'unsafeExpEn': 'Fatal mistake; human body conducts electricity, causing rescuer to get shocked.',
              'unsafeOutAr': 'سرى التيار لجسدك.',
              'unsafeOutEn': 'Electric current transferred to rescuer.',
            },
            {
              'sitAr': 'سقوط المصاب أرضاً بعد فصل التيار وهو غير فاقد للوعي لكنه يتنفس بصعوبة. ما الإسعاف؟',
              'sitEn': 'Victim falls floor conscious but breathing with difficulty post-shock. Aid?',
              'hintAr': 'تمديد المصاب على ظهره مع رفع قدميه قليلاً وتغطية مكان حروق الصعق بقماش نظيف',
              'hintEn': 'Lay victim flat on back, elevate feet slightly, cover burn sites with clean cloth',
              'safeTextAr': 'تمديد المصاب مستلقياً على ظهره، رفع القدمين 30 سم، والاطمئنان على مجرى التنفس',
              'safeTextEn': 'Lay victim flat on back, elevate feet 30cm, and monitor airway',
              'safeExpAr': 'إسراء سليم؛ وضعية الصدمة تضمن تدفق الدم للقلب والدماغ وتدعم التنفس.',
              'safeExpEn': 'Correct aid; shock position maintains vital blood supply to brain and heart.',
              'safeOutAr': 'أمنت وضعية المصاب للمحطة 4.',
              'safeOutEn': 'Stabilized victim for Station 4.',
              'unsafeTextAr': 'إجبار المصاب على المشي أو إعطائه ماء بارد ليشربه فوراً',
              'unsafeTextEn': 'Force victim to walk around or make them drink cold water',
              'unsafeExpAr': 'خطأ؛ إعطاء السوائل أثناء صدمة الصعق قد يسبب الاختناق والتراجع القلبي.',
              'unsafeExpEn': 'Error; giving fluids during electric shock can trigger choking or cardiac strain.',
              'unsafeOutAr': 'تدهورت حالة المصاب.',
              'unsafeOutEn': 'Victim condition deteriorated.',
            },
            {
              'sitAr': 'اندلاع حريق صغير في التوصيلات الكهربائية خلف المكتب. ما نوع الطفاية المناسبة؟',
              'sitEn': 'Small electrical fire behind office desk. Which fire extinguisher to use?',
              'hintAr': 'استخدام طفاية ثاني أكسيد الكربون (CO2) أو البودرة الجافة، وتجنب الماء تماماً',
              'hintEn': 'Use CO2 or Dry Powder extinguisher; NEVER use water on live electrical fire',
              'safeTextAr': 'استخدام طفاية غاز ثاني أكسيد الكربون (CO2) المخصصة للحرائق الكهربائية',
              'safeTextEn': 'Use Carbon Dioxide (CO2) fire extinguisher rated for Class C electrical fires',
              'safeExpAr': 'اختيار صحي؛ غاز CO2 غير موصل للكهرباء ولا يخرب الأجهزة أو يسبب صعقاً.',
              'safeExpEn': 'Correct choice; CO2 gas is non-conductive and leaves no residue on electronics.',
              'safeOutAr': 'أخمدت حريق التوصيلة للمحطة 5.',
              'safeOutEn': 'Extinguished electrical fire for Station 5.',
              'unsafeTextAr': 'سكب جردل ماء على التوصيلات الكهربائية المشتعلة',
              'unsafeTextEn': 'Throw bucket of tap water onto burning electrical extension strip',
              'unsafeExpAr': 'خطأ كارثي؛ الماء غير النقي موصل ممتاز للكهرباء ويزيد الصعق والحريق.',
              'unsafeExpEn': 'Catastrophic mistake; water conducts electricity rapidly causing major shock hazard.',
              'unsafeOutAr': 'حدث انشقاق وتشرر كهربائي.',
              'unsafeOutEn': 'Triggered severe arc flash.',
            },
            {
              'sitAr': 'وصول فريق الإسعاف (997) وطوارئ الكهرباء (933). ما الإجراء الوقائي الدائم؟',
              'sitEn': 'Paramedics (997) & SEC emergency (933) arrive. Permanent prevention step?',
              'hintAr': 'عدم تحميل التوصيلات أكثر من طاقتها وفحص القواطع الذكية (GFCI)',
              'hintEn': 'Avoid overloading multi-plugs and install GFCI circuit breakers',
              'safeTextAr': 'فحص قواطع تسريب الأرضي (GFCI) وتجنب توصيل عدة أجهزة عالية القوة بتوصيلة واحدة',
              'safeTextEn': 'Install GFCI breakers and avoid daisy-chaining high-wattage heavy appliances',
              'safeExpAr': 'إتمام كامل؛ صيانة التوصيلات وحماية GFCI تقي من 95% من حوادث الصعق.',
              'safeExpEn': 'Complete protocol; GFCI protection and balanced loads prevent 95% of shock hazards.',
              'safeOutAr': 'أكملت محطات سلامة الكهرباء بنجاح!',
              'safeOutEn': 'Successfully completed electrical safety stations!',
              'unsafeTextAr': 'ترك التوصيلات التالفة مكشوفة وإعادة تشغيل القاطع القوي فوراً',
              'unsafeTextEn': 'Leave frayed wires exposed and force reset tripped breaker repeatedly',
              'unsafeExpAr': 'خطأ؛ تكرار تشغيل القاطع دون إصلاح العطل يسبب حريقاً كبيراً بالحوائط.',
              'unsafeExpEn': 'Error; forcing reset on a shorted breaker causes catastrophic in-wall electrical fires.',
              'unsafeOutAr': 'استمر خطر الماس الكهربائي.',
              'unsafeOutEn': 'Electrical short circuit risk persisted.',
            },
          ],
        ),

        // 2. Electric Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_2',
          categoryId: 'electric',
          titleAr: 'سقوط كابل كهرباء رئيسي بالشارع',
          titleEn: 'Fallen High-Voltage Power Line Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع سقوط كابلات الضغط العالي أثناء العواصف.',
          descriptionEn: 'Interactive 5-station scenario for fallen high-voltage lines during storms.',
          difficulty: 'صعب',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'سقط كابل كهرباء ضغط عالي على الشارع المبلل أمام سيارتك. ما أول تصرف؟',
              'sitEn': 'High-voltage power cable falls onto wet street in front of your car. Action?',
              'hintAr': 'البقاء داخل السيارة وعدم الترجل منها نهائياً لأن الإطارات تعزلك',
              'hintEn': 'Stay INSIDE vehicle; rubber tires insulate car from energized ground',
              'safeTextAr': 'البقاء داخل السيارة والتوقف التام دون الخروج أو لمس الهيكل الخارجي',
              'safeTextEn': 'Stay calm inside car, stop completely without stepping out onto wet pavement',
              'safeExpAr': 'تصرف ذكي؛ إطارات المطاط تعزل السيارة وتمنع تكوّن فرق الجهد (Step Potential).',
              'safeExpEn': 'Smart response; rubber tires insulate car while ground around has high step potential.',
              'safeOutAr': 'بقيت بالسيارة بآمان للمحطة 2.',
              'safeOutEn': 'Stayed safely inside car for Station 2.',
              'unsafeTextAr': 'فتح الباب والترجل فوراً للمشي على الأسفلت المبلل',
              'unsafeTextEn': 'Open door and step out onto wet asphalt near cable',
              'unsafeExpAr': 'خطأ قاتل؛ الأرض المبللة تشحن بجهد كهربائي عالي يصعق المشاة.',
              'unsafeExpEn': 'Fatal error; energized wet ground creates high step voltage shock zone.',
              'unsafeOutAr': 'تعرضت لجهد الخطوة الكهربائي.',
              'unsafeOutEn': 'Exposed to step potential voltage.',
            },
            {
              'sitAr': 'بدأ الكابل يشرر بقوة بجانب الإطار. كيف تتصل بالطوارئ بأمان؟',
              'sitEn': 'Cable sparking near car tire. How to call emergency safely?',
              'hintAr': 'الاتصال بمركز الطوارئ (911 أو 933) وإبلاغهم بالموقع الدقيق للضغط العالي',
              'hintEn': 'Call 911 or SEC 933 giving precise high-voltage cable location',
              'safeTextAr': 'الاتصال بالهاتف من داخل السيارة بـ 911 أو طوارئ الكهرباء (933)',
              'safeTextEn': 'Call 911 or SEC emergency line 933 from inside phone',
              'safeExpAr': 'إجراء ممتاز؛ إبلاغ طوارئ الكهرباء يتيح فصل التيار من المحطة الفرعية فوراً.',
              'safeExpEn': 'Excellent step; notifying SEC enables immediate remote substation power cutoff.',
              'safeOutAr': 'بلغت طوارئ الكهرباء للمحطة 3.',
              'safeOutEn': 'Alerted SEC emergency for Station 3.',
              'unsafeTextAr': 'الخروج من السيارة لجلب عصا وإبعاد الكابل بنفسك',
              'unsafeTextEn': 'Get out of car to grab a branch and push cable away',
              'unsafeExpAr': 'خطأ مهلك؛ جهد الضغط العالي يخترق الخشب الرطب ويبيد المسعف.',
              'unsafeExpEn': 'Fatal error; high voltage arcs directly through wet wood electrocuting responder.',
              'unsafeOutAr': 'خاطرت بالاقتراب من الكابل.',
              'unsafeOutEn': 'Risked high-voltage electrical arc.',
            },
            {
              'sitAr': 'اشتعال إطار السيارة وتعين عليك الإخلاء الاضطراري. كيف تقفز دون لمس السيارة والأرض معاً؟',
              'sitEn': 'Tire catches fire requiring emergency car evacuation. How to jump safely?',
              'hintAr': 'القفز بكلتا القدمين معاً دون لمس هيكل السيارة والأرض في وقت واحد',
              'hintEn': 'Jump out landing on BOTH feet together without touching vehicle and ground simultaneously',
              'safeTextAr': 'القفز بكلتا القدمين ملتصقتين معاً للأسفل دون لمس المعدن الخارجي للسيارة',
              'safeTextEn': 'Bunny-hop jump with both feet together landing clear of car body',
              'safeExpAr': 'تقنية النجاة؛ القفز بالقدمين الملتصقتين يمنع تكوّن مسار فرق الجهد بين الساقين.',
              'safeExpEn': 'Survival jump; landing feet together eliminates voltage differential between legs.',
              'safeOutAr': 'قفزت بسلام للمحطة 4.',
              'safeOutEn': 'Jumped landed safely for Station 4.',
              'unsafeTextAr': 'وضع قدم على الأرض وقدم أخرى على عتبة السيارة المعدنية',
              'unsafeTextEn': 'Place one foot on ground while keeping other foot on metal car step',
              'unsafeExpAr': 'خطأ قاتل؛ اللمس المزدوج يجعل جسمك جسراً موصلاً للتيار العالي.',
              'unsafeExpEn': 'Fatal error; bridging car metal and ground completes circuit electrocuting person.',
              'unsafeOutAr': 'أصبحت جسراً للتيار.',
              'unsafeOutEn': 'Bridged circuit with body.',
            },
            {
              'sitAr': 'أصبحت على الأرض بجانب الكابل الساقط. كيف تبتعد مسافة 10 أمتار عن الكابل؟',
              'sitEn': 'On ground near fallen line. How to move 10 meters away safely?',
              'hintAr': 'التحرك بالضم والقفز الصغير بكلتا القدمين معاً (Bunny Hop) أو السحب البطيء',
              'hintEn': 'Shuffle feet together without lifting them off ground or hop on both feet together',
              'safeTextAr': 'القفز بكلتا القدمين ملتصقتين معاً أو زلق القدمين ببطء دون رفعهما عن الأرض',
              'safeTextEn': 'Shuffle feet continuously without lifting soles, or hop on both feet together',
              'safeExpAr': 'طريقة الأمان؛ إبقاء القدمين متلاصقتين يمنع مرور التيار الكهربائي بين الساقين.',
              'safeExpEn': 'Safety shuffle; keeping feet touching prevents step potential difference.',
              'safeOutAr': 'ابتعدت مسافة 10 أمتار للمحطة 5.',
              'safeOutEn': 'Moved 10 meters away for Station 5.',
              'unsafeTextAr': 'الركض بخطوات واسعة وسريعة بعيداً عن الكابل',
              'unsafeTextEn': 'Run with wide open strides away from fallen power cable',
              'unsafeExpAr': 'خطأ خطير؛ الخطوات الواسعة تخلق فرق جهد عالي بين القدمين يسبب الصعق.',
              'unsafeExpEn': 'Dangerous error; wide strides create massive voltage gap between feet causing shock.',
              'unsafeOutAr': 'تعرضت لفرق جهد الساقين.',
              'unsafeOutEn': 'Suffered step potential shock.',
            },
            {
              'sitAr': 'وصول فنيي شركة الكهرباء وفصل خط الضغط العالي. ما المعيار الوقائي؟',
              'sitEn': 'SEC technicians arrive and isolate line. Safety standard?',
              'hintAr': 'الابتعاد مسافة لا تقل عن 10 أمتار عن أي كابل كهربائي ساقط بالشارع',
              'hintEn': 'Maintain minimum 10-meter (35 ft) safety distance from any downed cable',
              'safeTextAr': 'إقامة منطقة أمان بقطر 10 أمتار وتحذير المشاة حتى وصول الفنيين',
              'safeTextEn': 'Maintain 10-meter perimeter and warn pedestrian traffic until line de-energized',
              'safeExpAr': 'إتمام كامل؛ حظر الاقتراب مسافة 10 أمتار يقيك من قوس الكهرباء عالي الجهد.',
              'safeExpEn': 'Complete resolution; 10m exclusion radius shields against high-voltage arc flash.',
              'safeOutAr': 'أكملت محطات طوارئ كابلات الشارع بنجاح!',
              'safeOutEn': 'Successfully completed power line emergency scenario!',
              'unsafeTextAr': 'الاقتراب من الكابل للتقاط صور وفيديوهات للجوال',
              'unsafeTextEn': 'Approach downed live cable to record mobile videos',
              'unsafeExpAr': 'خطأ؛ الاقتراب يكسر مسافة الأمان ويعرضك لقوس كهربائي قاتل.',
              'unsafeExpEn': 'Error; approaching breaks safe radius exposing user to deadly electrical arc.',
              'unsafeOutAr': 'عرضت نفسك لخطر القوس.',
              'unsafeOutEn': 'Exposed to arc flash hazard.',
            },
          ],
        ),

        // Scenarios 3 to 9 for ELECTRIC...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_3',
          categoryId: 'electric',
          titleAr: 'سقوط جهاز كهربائي في الماء',
          titleEn: 'Appliance Dropped in Water Hazard',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع الأجهزة الكهربائية الساقطة بالماء بالحمام أو المطبخ.',
          descriptionEn: 'Interactive 5-station scenario for electrical appliances dropped into water.',
          difficulty: 'سهل',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'سقط مجفف الشعر الموصول بالكهرباء داخل حوض الاستحمام المليء بالماء. ما أول حركة؟',
              'sitEn': 'Plugged hairdryer falls into bathtub filled with water. First action?',
              'hintAr': 'عدم وضع يدك بالماء مطلقاً، والتوجه فوراً لفصل الفيش أو القاطع الرئيسي',
              'hintEn': 'NEVER reach into water; immediately unplug cord at wall or flip breaker',
              'safeTextAr': 'فصل فيش الكهرباء من المقبس الجداري بأيدٍ جافة أو فصل قاطع الحمام',
              'safeTextEn': 'Unplug hairdryer from wall socket with dry hands or flip bathroom GFCI breaker',
              'safeExpAr': 'تصرف آمن؛ فصل المصدر الجداري يقطع التيار الكهربائي قبل ملامسة الماء.',
              'safeExpEn': 'Safe action; unplugging wall source kills live voltage in tub water.',
              'safeOutAr': 'فصلت الفيش بنجاح للمحطة 2.',
              'safeOutEn': 'Unplugged wall power for Station 2.',
              'unsafeTextAr': 'إدخال اليد في حوض الاستحمام لسحب الجهاز بسرعة',
              'unsafeTextEn': 'Reach bare hand into bath water to pull hairdryer out quickly',
              'unsafeExpAr': 'خطأ قاتل؛ الماء المشحون بالكهرباء يسبب صعقاً قلبي فيزيائياً فورياً.',
              'unsafeExpEn': 'Fatal mistake; energized water conducts current directly through heart.',
              'unsafeOutAr': 'تعرضت لصعق مائي.',
              'unsafeOutEn': 'Electrocuted in energized bath.',
            },
            {
              'sitAr': 'المقبس الجداري مبتل أيضاً بالرذاذ. كيف تفصل القاطع الرئيسي بسلامة؟',
              'sitEn': 'Wall outlet wet from splashing. How to safely turn off circuit breaker?',
              'hintAr': 'ارتداء حذاء مطاطي والتأكد من جفاف اليدين قبل لمس لوحة القواطع',
              'hintEn': 'Wear rubber-soled shoes and dry hands before touching main panel switch',
              'safeTextAr': 'جفاف اليدين جيداً بالمنشفة والوقوف على أرضية جافة تفادياً لنقل التيار',
              'safeTextEn': 'Dry hands thoroughly with towel and stand on dry floor before touching breaker',
              'safeExpAr': 'خطوة صحية؛ العزل الجاف يضمن عدم سريان أي شحنة متبقية لجسمك.',
              'safeExpEn': 'Correct step; dry isolation ensures no residual voltage travels through skin.',
              'safeOutAr': 'فصلت القاطع بأمان للمحطة 3.',
              'safeOutEn': 'Flipped breaker safely for Station 3.',
              'unsafeTextAr': 'لمس مفتاح القاطع بأيدٍ مبللة بالماء وأقدام حافية',
              'unsafeTextEn': 'Touch metal breaker switch with dripping wet hands while barefoot',
              'unsafeExpAr': 'خطأ؛ الرطوبة والأقدام الحافية تنقص المقاومة الكهربائية وتسرع الصعق.',
              'unsafeExpEn': 'Error; wet hands and bare feet drop electrical resistance to dangerously low levels.',
              'unsafeOutAr': 'حدث ماس بالقاطع.',
              'unsafeOutEn': 'Short circuit at panel.',
            },
            {
              'sitAr': 'إخراج الجهاز الكهربائي من الماء بعد التأكد التام من فصل التيار. كيف تتعامل معه؟',
              'sitEn': 'Removing appliance from water after power confirmed cut. Handling protocol?',
              'hintAr': 'ترك الجهاز لليجف تماماً لعدة أيام وعدم تشغيله إطلاقاً وهو مبتل',
              'hintEn': 'Allow appliance to dry completely for days; NEVER plug in wet electronics',
              'safeTextAr': 'سحب الجهاز وتركه يجف في مكان مشمس ومعد للتهوية وعدم توصيله مطلقاً',
              'safeTextEn': 'Remove device and place in ventilated dry area for full air-drying',
              'safeExpAr': 'معالجة سريعة؛ تشغيل الجهاز المبتل يسبب انفجار المكثفات وتلف المحرك.',
              'safeExpEn': 'Smart handling; powering wet circuits causes short circuits and capacitor explosion.',
              'safeOutAr': 'وضعت الجهاز للجفاف للمحطة 4.',
              'safeOutEn': 'Set appliance to dry for Station 4.',
              'unsafeTextAr': 'توصيل الفيش بالكهرباء فوراً للتأكد من أنه ما زال يعمل',
              'unsafeTextEn': 'Plug appliance back into wall socket immediately to test if it still works',
              'unsafeExpAr': 'خطأ جسيم؛ الرطوبة الداخلية تسبب انفجار القابس وتلف الشبكة.',
              'unsafeExpEn': 'Severe error; internal moisture sparks immediate short circuit explosion.',
              'unsafeOutAr': 'حدث انفجار بالمقبس.',
              'unsafeOutEn': 'Outlet exploded from short.',
            },
            {
              'sitAr': 'فحص مقبس الحمام للتأكد من حماية السلامة المائية. ما النوع الواجب توفره؟',
              'sitEn': 'Inspecting bathroom wall socket for water safety compliance. Type required?',
              'hintAr': 'تركيب مقابس ذات غطاء حماية ضد الماء وتوفر خاصية قاطع GFCI',
              'hintEn': 'Install waterproof cover plates and GFCI Ground Fault Circuit Interrupter outlets',
              'safeTextAr': 'التأكد من أن المقبس مزود بغطاء مطاطي عازل وقاطع تسريب GFCI',
              'safeTextEn': 'Ensure bathroom outlet features a waterproof flip cover and GFCI trip button',
              'safeExpAr': 'معيار عالمي؛ مقابس GFCI تقطع الكهرباء في 0.02 ثانية عند رصد أي تسريب مائي.',
              'safeExpEn': 'Global standard; GFCI outlets cut power within 0.02 seconds of water grounding.',
              'safeOutAr': 'تأكدت من معيار GFCI للمحطة 5.',
              'safeOutEn': 'Verified GFCI compliance for Station 5.',
              'unsafeTextAr': 'استخدام توصيلات عادية مكشوفة بجانب مغاسل المياه',
              'unsafeTextEn': 'Use ordinary bare power strips directly next to wash basins',
              'unsafeExpAr': 'خطأ؛ التوصيلات العادية تنقل الرطوبة والكهرباء وتسبب الحوادث.',
              'unsafeExpEn': 'Error; standard power strips invite splashing and fire risk.',
              'unsafeOutAr': 'مخاطرة بالمقابس العادية.',
              'unsafeOutEn': 'Standard power strip risk.',
            },
            {
              'sitAr': 'استبدال الجهاز وتأمين الحمام. ما النصيحة الوقائية الدائمة بالأماكن الرطبة؟',
              'sitEn': 'Replaced device and secured room. Permanent prevention tip for wet areas?',
              'hintAr': 'إبعاد الأجهزة الكهربائية مسافة مترين على الأقل عن المصادر المائية',
              'hintEn': 'Keep all plugged electronics at least 2 meters away from water sinks & tubs',
              'safeTextAr': 'فصل جميع الأجهزة الكهربائية بعد الاستخدام وإبعادها مسافة كافية عن المياه',
              'safeTextEn': 'Always unplug personal care electric items after use keeping 2m clear distance from water',
              'safeExpAr': 'إتمام كامل؛ فصل الأجهزة بعد الاستخدام يلغي مخاطر السقوط الحر بالمياه.',
              'safeExpEn': 'Complete resolution; unplugging after use eliminates accidental immersion shocks.',
              'safeOutAr': 'أكملت محطات سلامة أجهزة المياه بنجاح!',
              'safeOutEn': 'Successfully cleared water appliance safety scenario!',
              'unsafeTextAr': 'ترك جهاز حلاقة موصولاً بالكهرباء على حافة المغسلة الممتلئة',
              'unsafeTextEn': 'Leave plugged shaver resting on rim of filled water sink',
              'unsafeExpAr': 'خطأ؛ الاهتزاز قد يسقط الجهاز داخل الماء بالخطأ.',
              'unsafeExpEn': 'Error; minor bumps can knock plugged shaver into filled sink water.',
              'unsafeOutAr': 'مخاطرة بالسقوط المائي.',
              'unsafeOutEn': 'Immersion hazard remained.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_4',
          categoryId: 'electric',
          titleAr: 'تحميل التوصيلات وأحمال الدفايات صيفاً وشتاءً',
          titleEn: 'Overloaded Multi-Plugs & Heater Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع أحمال التوصيلات الكبيرة وحرائق الدفايات.',
          descriptionEn: 'Interactive 5-station scenario for electrical load overload and heater fires.',
          difficulty: 'متوسط',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'توصيل دفاية كهربائية عالية القوة (2400 واط) بتوصيلة مشتركة مع غلاية ومكواة. ماذا تلاحظ؟',
              'sitEn': 'Plugging 2400W space heater, electric kettle, and iron into single power strip. Observation?',
              'hintAr': 'ارتفاع حرارة السلك وانبعاث رائحة بلاستيك محترق بسبب الأحمال الزائدة',
              'hintEn': 'Wire overheats rapidly and emits melting plastic smell due to heavy current overload',
              'safeTextAr': 'فصل الدفاية فوراً وتوصيلها بمقبس الجدار المباشر دون استخدام توصيلات',
              'safeTextEn': 'Unplug space heater immediately and plug directly into dedicated wall socket',
              'safeExpAr': 'تصرف ممتاز؛ الأجهزة عالية الاستهلاك يجب توصيلها بالمقبس الجداري المباشر.',
              'safeExpEn': 'Excellent choice; heavy thermal appliances must connect directly to dedicated wall outlets.',
              'safeOutAr': 'فصلت الأحمال الكبيرة للمحطة 2.',
              'safeOutEn': 'Isolated heavy load for Station 2.',
              'unsafeTextAr': 'تجاهل رائحة البلاستيك ومواصلة تشغيل جميع الأجهزة معا',
              'unsafeTextEn': 'Ignore melting plastic smell and run all 3 appliances simultaneously',
              'unsafeExpAr': 'خطأ خطير؛ انصهار عازل السلك يسبب حريقاً داخلياً سريع الاندلاع.',
              'unsafeExpEn': 'Dangerous error; melting PVC wire insulation leads to instant high-heat electrical fire.',
              'unsafeOutAr': 'انصهر عازل السلك.',
              'unsafeOutEn': 'Insulation melted.',
            },
            {
              'sitAr': 'شراء توصيلة كهربائية جديدة من السوق. ما المواصفة السعودية المعتمده بالمنتج؟',
              'sitEn': 'Purchasing new power extension strip. Mandatory SASO Saudi quality standard?',
              'hintAr': 'وجود شريحة الحماية (Fuse)، السلك السميك (3x1.5mm)، وعلامة الجودة السعودية (SASO)',
              'hintEn': 'Check for built-in fuse breaker, heavy gauge wire, and SASO Quality Mark',
              'safeTextAr': 'اختيار توصيلة تحمل علامة الجودة السعودية (SASO) وقاطع حماية أوتوماتيكي',
              'safeTextEn': 'Select SASO Quality Mark certified extension lead with integrated circuit fuse breaker',
              'safeExpAr': 'شراء آمن؛ المنتجات المعتمدة تضمن سُمك النحاس وعدم الانصهار أثناء الضغط.',
              'safeExpEn': 'Safe purchase; SASO certified leads guarantee proper copper wire cross-section and thermal safety.',
              'safeOutAr': 'اخترت توصيلة معتمدة للمحطة 3.',
              'safeOutEn': 'Selected certified lead for Station 3.',
              'unsafeTextAr': 'شراء توصيلة رخيصة مقلدة بسلك خفيف وبدون قاطع أمان',
              'unsafeTextEn': 'Buy cheap counterfeit uncertified extension strip with thin light cable',
              'unsafeExpAr': 'خطأ؛ الأسلاك النحاسية الرقيقة تنصهر بسهولة تحت أدنى حمولة.',
              'unsafeExpEn': 'Error; thin counterfeit copper wires heat up and catch fire easily under moderate loads.',
              'unsafeOutAr': 'مخاطرة بالتوصيلات المقلدة.',
              'unsafeOutEn': 'Counterfeit wire hazard.',
            },
            {
              'sitAr': 'توصيل التوصيلات الكهربائية ببعضها البعض (سلسلة التوصيل). ما مدى سلامة ذلك؟',
              'sitEn': 'Daisy-chaining multiple power strips into one another. Safety assessment?',
              'hintAr': 'حظر توصيل توصيلة داخل توصيلة أخرى نهائياً لمخاطر ارتفاع المقاومة والحرارة',
              'hintEn': 'STRICTLY forbidden to daisy-chain power strips due to resistance buildup',
              'safeTextAr': 'فصل السلسلة فوراً واستخدام توصيلة واحدة طويلة بطول مناسب',
              'safeTextEn': 'Disconnect daisy chain immediately and use a single long certified extension lead',
              'safeExpAr': 'قاعدة سلامة؛ تسلسل التوصيلات يضاعف المقاومة الكهربائية ويسبب حرائق غير مرئية.',
              'safeExpEn': 'Safety rule; daisy-chaining multiplies electrical resistance creating hidden fire risks.',
              'safeOutAr': 'ألغيت تسلسل التوصيلات للمحطة 4.',
              'safeOutEn': 'Eliminated daisy chain for Station 4.',
              'unsafeTextAr': 'ربط 4 توصيلات متتالية للوصول لغرفة بعيدة',
              'unsafeTextEn': 'Connect 4 power strips in series to reach a distant bedroom corner',
              'unsafeExpAr': 'خطأ؛ تسبب هذه الحركة انخفاض الجهد وارتفاع الحرارة حتى الاشتعال.',
              'unsafeExpEn': 'Error; creates cumulative resistance leading to insulation failure and wall fire.',
              'unsafeOutAr': 'ارتفعت حرارة السلسلة.',
              'unsafeOutEn': 'Daisy chain overheated.',
            },
            {
              'sitAr': 'وضع السلك الكهربائي الممتد تحت السجاد أو الفرش بالمنزل. ما خطورة ذلك؟',
              'sitEn': 'Running extension lead wire underneath carpet or rugs. Danger level?',
              'hintAr': 'حظر تمديد الأسلاك تحت السجاد لأن المشي فوقها يكسر النحاس ويحبس الحرارة',
              'hintEn': 'NEVER run cords under rugs; walking crushes wires and traps thermal heat',
              'safeTextAr': 'إزالة السلك من تحت السجاد وتمديده بجانب الجدار في مجرى بلاستيكي مخصص',
              'safeTextEn': 'Remove cord from under rug and secure along wall using plastic cable trunking',
              'safeExpAr': 'إجراء ممتاز؛ التمديد الظاهر في مجاري الحماية يمنع دهس الأسلاك وانحصار الحرارة.',
              'safeExpEn': 'Great action; surface trunking prevents wire friction damage and heat accumulation.',
              'safeOutAr': 'أمنت مسار السلك للمحطة 5.',
              'safeOutEn': 'Secured cable path for Station 5.',
              'unsafeTextAr': 'ترك الأسلاك تحت السجاد والمشي الفوقي المباشر عليها يومياً',
              'unsafeTextEn': 'Leave wires permanently hidden under thick rug walking over them daily',
              'unsafeExpAr': 'خطأ؛ تكسر الشعيرات النحاسية بالداخل ينتج قوسي كهربائي تحت الفرش.',
              'unsafeExpEn': 'Error; foot pressure breaks copper strands causing silent arcing under flammable rug.',
              'unsafeOutAr': 'تلف الشعيرات النحاسية.',
              'unsafeOutEn': 'Internal copper strands severed.',
            },
            {
              'sitAr': 'ضبط سلامة التوصيلات والدفايات بالمنزل بالكامل. ما التوجيه الوقائي النهائي؟',
              'sitEn': 'Final check of all household heating & multi-plug setups. Final protocol?',
              'hintAr': 'فصل الدفايات والتوصيلات عند النوم أو الخروج من المنزل',
              'hintEn': 'Always turn off and unplug space heaters before sleeping or leaving home',
              'safeTextAr': 'إيقاف وفصل الدفايات والأجهزة الكهربائية غير الضرورية قبل النوم أو مغادرة المنزل',
              'safeTextEn': 'Turn off and unplug space heaters and non-essential appliances before sleep or leaving',
              'safeExpAr': 'إتمام كامل؛ فصل الأحمال الليلية يمنع 80% من حرائق المنازل أثناء النوم.',
              'safeExpEn': 'Complete protocol; disconnecting overnight thermal loads eliminates major cause of house fires.',
              'safeOutAr': 'أكملت محطات أحمال التوصيلات والدفايات بنجاح!',
              'safeOutEn': 'Successfully cleared extension load safety scenario!',
              'unsafeTextAr': 'ترك الدفاية تعمل بجانب المفارش طوال الليل أثناء النوم',
              'unsafeTextEn': 'Leave high-power radiant heater glowing next to bed curtains all night',
              'unsafeExpAr': 'خطأ قاتل؛ ملامسة المفارش للدفاية أثناء النوم يسبب حرائق اختناق صامتة.',
              'unsafeExpEn': 'Fatal mistake; curtain or bedding contact with radiant heater ignites rapid night fire.',
              'unsafeOutAr': 'مخاطرة الحريق الليلي.',
              'unsafeOutEn': 'Overnight fire risk persisted.',
            },
          ],
        ),

        // Scenarios 5 to 9 for ELECTRIC...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_5',
          categoryId: 'electric',
          titleAr: 'سخانات المياه الكهربائية وصمام الأمان',
          titleEn: 'Electric Water Heater & Pressure Valve Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتفادي انفجار سخانات المياه وضبط الثرموستات.',
          descriptionEn: 'Interactive 5-station scenario for electric water heater maintenance & safety.',
          difficulty: 'متوسط',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'سمعت صوت غليان شديد وانبعاث بخار كثيف من سخان المياه بالحمام. ما التصرف الأول؟',
              'sitEn': 'Loud boiling sound and heavy steam leaking from bathroom water heater. First step?',
              'hintAr': 'فصل قاطع الكهرباء الخاص بالسخان فوراً وعدم فتح صنبور الماء الساخن',
              'hintEn': 'Instantly turn off dedicated heater circuit breaker; do NOT touch hot faucet',
              'safeTextAr': 'التوجه لقاطع سخان المياه باللوحة وفصله فوراً لإيقاف عنصر التسخين',
              'safeTextEn': 'Go to electrical panel and switch off dedicated water heater breaker instantly',
              'safeExpAr': 'تصرف سليم؛ قطع التغذية يوقف ارتفاع الضغط البخاري القاتل داخل الخزان.',
              'safeExpEn': 'Correct step; cutting power stops dangerous internal steam pressure build-up.',
              'safeOutAr': 'فصلت كهرباء السخان للمحطة 2.',
              'safeOutEn': 'Isolated heater electrical supply for Station 2.',
              'unsafeTextAr': 'فتح صنبور المياه الساخنة تحت السخان مباشرة بكلتا اليدين',
              'unsafeTextEn': 'Reach up directly under heater to blast open hot water valve by hand',
              'unsafeExpAr': 'خطأ خطير؛ البخار المضغوط والماء المغلي يسببان حروقاً بالغة بالوجه واليدين.',
              'unsafeExpEn': 'Dangerous error; superheated steam explosion causes severe 3rd degree skin burns.',
              'unsafeOutAr': 'تعرضت لحروق البخار.',
              'unsafeOutEn': 'Burned by superheated steam blast.',
            },
            {
              'sitAr': 'فحص صمام الأمان العاطلي (Safety Relief Valve) أسفل السخان. ما وظيفته الإلزامية؟',
              'sitEn': 'Inspecting bottom Safety Pressure Relief Valve. What is its mandatory function?',
              'hintAr': 'تفريغ الضغط الزائد تلقائياً عند ارتفاع الحرارة لمنع انفجار الخزان',
              'hintEn': 'Automatically bleeds excess water pressure to prevent catastrophic tank explosion',
              'safeTextAr': 'التأكد من أن صمام الأمان غير مسدود ويقطر بشكل طبيعي عند ارتفاع الضغط',
              'safeTextEn': 'Verify pressure relief valve is clean, unblocked, and operational',
              'safeExpAr': 'معيار حاسما؛ صمام الأمان هو خط الدفاع الأخير لمنع تحول السخان لقنبلة بخارية.',
              'safeExpEn': 'Critical standard; safety relief valve prevents pressure buildup from rupturing metal tank.',
              'safeOutAr': 'فحصت صمام الأمان للمحطة 3.',
              'safeOutEn': 'Checked safety relief valve for Station 3.',
              'unsafeTextAr': 'إغلاق أو سد فتحة صمام الأمان بسدادة معدنية لمنع تنقيط الماء',
              'unsafeTextEn': 'Cap off or seal dripping pressure relief valve pipe with metal plug',
              'unsafeExpAr': 'خطأ قاتل؛ سد الصمام يحبس الضغط البخاري حتى ينفجر الخزان بالكامل.',
              'unsafeExpEn': 'Fatal error; plugging safety valve traps pressure turning tank into a missile bomb.',
              'unsafeOutAr': 'احتبس الضغط بالخزان.',
              'unsafeOutEn': 'Trapped internal tank pressure.',
            },
            {
              'sitAr': 'ضبط درجة حرارة الثرموستات (Thermostat) الخاص بالسخان. ما الدرجة الآمنة الموصى بها؟',
              'sitEn': 'Setting water heater thermostat temperature dial. Recommended safe temperature?',
              'hintAr': 'ضبط الدرجة بين 60 إلى 65 درجة مئوية للوقاية من البكتيريا والحروق',
              'hintEn': 'Set thermostat between 60°C to 65°C to kill Legionella while avoiding scalding',
              'safeTextAr': 'ضبط منظّم الحرارة (الثرموستات) عند 60 درجة مئوية لضمان التعقيم والأمان',
              'safeTextEn': 'Set thermostat dial precisely to 60°C (140°F) for sterilization and energy safety',
              'safeExpAr': 'ضبط مثالي؛ 60°C تقضي على بكتيريا الليجيونيلا وتمنع الغليان وتوفر الطاقة.',
              'safeExpEn': 'Ideal setting; 60°C kills waterborne bacteria without overheating steel shell.',
              'safeOutAr': 'ضبطت الثرموستات للمحطة 4.',
              'safeOutEn': 'Calibrated thermostat for Station 4.',
              'unsafeTextAr': 'رفع الثرموستات لأقصى درجة (90 درجة مئوية) طوال العام',
              'unsafeTextEn': 'Crank thermostat dial to max limit 90°C continuously',
              'unsafeExpAr': 'خطأ؛ الرفع الأقصى يسبب غليان الماء وانصهار الأسلاك وتراكم الكلس.',
              'unsafeExpEn': 'Error; max temperature causes water boiling, wire degradation, and heavy scaling.',
              'unsafeOutAr': 'غليان مستمر وترسبات.',
              'unsafeOutEn': 'Continuous boiling and scale buildup.',
            },
            {
              'sitAr': 'ملاحظة صدأ وتسريب مائي من القشرة الخارجية للسخان القديم. ما الإجراء الصحيح؟',
              'sitEn': 'Rust corrosion and water leakage visible on outer shell of old heater. Correct action?',
              'hintAr': 'استبدال السخان القديم فوراً وعدم محاولة تلميع الصدأ أو لحامه',
              'hintEn': 'Replace corroded heater immediately; never attempt welding a rusted water tank',
              'safeTextAr': 'إيقاف تشغيل السخان واستبداله بسخان جديد مطابق للمواصفات السعودية',
              'safeTextEn': 'Decommission rusted heater and replace with certified SASO unit',
              'safeExpAr': 'قرار آمن؛ الصدأ يضعف الجدران المعدنية مما ينبئ بانهيار الخزان تحت الضغط.',
              'safeExpEn': 'Safe decision; metal corrosion compromises structural wall integrity risking tank burst.',
              'safeOutAr': 'استبدلت السخان التالف للمحطة 5.',
              'safeOutEn': 'Replaced corroded heater for Station 5.',
              'unsafeTextAr': 'وضع شريط لاصق على مكان التسريب ومواصلة الاستخدام',
              'unsafeTextEn': 'Apply waterproof tape over leaking rusted hole and continue running',
              'unsafeExpAr': 'خطأ؛ الشريط اللاصق لا يتحمل الضغط المائي وينفجر فجأة.',
              'unsafeExpEn': 'Error; adhesive tape cannot withstand internal hydraulic pressure bursting under load.',
              'unsafeOutAr': 'انفجر الشريط اللاصق.',
              'unsafeOutEn': 'Tape burst under pressure.',
            },
            {
              'sitAr': 'تركيب السخان الجديد بسلامة. ما الجدول الدوري الموصى به للصيانة؟',
              'sitEn': 'New heater installed safely. Recommended periodic maintenance schedule?',
              'hintAr': 'فحص صمام الأمان وتفريغ الرواسب الجيرية مرة واحدة سنوياً',
              'hintEn': 'Test safety valve and drain sediment scale once every year',
              'safeTextAr': 'إجراء صيانة سنوية لشطف الكلس واختبار حركة صمام الأمان',
              'safeTextEn': 'Schedule annual maintenance to flush sediment scale and test pressure valve lever',
              'safeExpAr': 'إتمام كامل؛ الصيانة السنوية تزيد عمر السخان وتضمن عمل أجهزة الأمان.',
              'safeExpEn': 'Complete resolution; annual flushing extends tank life and guarantees relief valve functionality.',
              'safeOutAr': 'أكملت محطات سلامة سخانات المياه بنجاح!',
              'safeOutEn': 'Successfully cleared water heater safety scenario!',
              'unsafeTextAr': 'إهمال السخان لمدة 10 سنوات دون فحص صمام الأمان إطلاقاً',
              'unsafeTextEn': 'Ignore water heater for 10 years without ever checking pressure valve',
              'unsafeExpAr': 'خطأ؛ التكلس ينسد صمام الأمان بمرور السنوات مما يخلق خطراً شديداً.',
              'unsafeExpEn': 'Error; lime scale seizes relief valves over time creating severe explosion hazards.',
              'unsafeOutAr': 'انسداد صمام الأمان الكلسي.',
              'unsafeOutEn': 'Calcified relief valve hazard.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_6',
          categoryId: 'electric',
          titleAr: 'الماس الكهربائي أثناء الأمطار الغزيرة',
          titleEn: 'Electrical Short Circuits During Heavy Rains',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجنب الصعق والماس الكهربائي بالأسوار الخارجية والمطابخ أثناء الأمطار.',
          descriptionEn: 'Interactive 5-station scenario for outdoor shorts and wet wall safety during rains.',
          difficulty: 'متوسط',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'هطلت أمطار غزيرة وتوضأت الجدران الخارجية للمنزل بالماء وأحدثت نقعاً بالمقابس. ما الإجراء؟',
              'sitEn': 'Heavy rain drenches outdoor yard walls soaking exterior power outlets. First step?',
              'hintAr': 'فصل قواطع الإضاءة والمقابس الخارجية من اللوحة الرئيسية فوراً',
              'hintEn': 'Instantly turn off dedicated outdoor lighting and yard breaker at main panel',
              'safeTextAr': 'فصل مفتاح القاطع المخصص للمقابس والإضاءة الخارجية من اللوحة العامة',
              'safeTextEn': 'Switch off outdoor lighting and exterior yard outlet breaker from main distribution panel',
              'safeExpAr': 'تصرف ممتاز؛ فصل الدوائر الخارجية يعزل تسريب الأمطار ويمنع الصعق.',
              'safeExpEn': 'Excellent step; isolating outdoor circuits prevents rain moisture ground leaks.',
              'safeOutAr': 'فصلت القاطع الخارجي للمحطة 2.',
              'safeOutEn': 'Isolated exterior circuit for Station 2.',
              'unsafeTextAr': 'لمس المفاتيح والمقابس الخارجية المبتلّة لتشغيل كشافات الحوش',
              'unsafeTextEn': 'Touch wet outdoor switches with bare hands to turn on yard floodlights',
              'unsafeExpAr': 'خطأ خطير؛ لمس المفاتيح المبتلّة يسبب تسرب الشحنات الكهربائية لجسمك.',
              'unsafeExpEn': 'Dangerous error; touching soaked switches transfers current directly into skin.',
              'unsafeOutAr': 'تعرضت لشحنة مائية.',
              'unsafeOutEn': 'Suffered wet switch shock.',
            },
            {
              'sitAr': 'تراكم مياه الأمطار حول أعمدة الإضاءة الخارجية بالحوش. كيف تتحرك بالداخل؟',
              'sitEn': 'Rainwater accumulating around outdoor yard light poles. How to move in yard safely?',
              'hintAr': 'تجنب الملامسة أو الخوض بالمياه المحيطة بالأعمدة والمحولات الخارجية',
              'hintEn': 'Avoid touching or walking through water pooling around light poles and transformers',
              'safeTextAr': 'الابتعاد مسافة مترين عن الأعمدة والمحولات الخارجية وعدم الخوض بالماء المحيط بها',
              'safeTextEn': 'Stay 2 meters clear of metal light poles and avoid wading near electrical bases',
              'safeExpAr': 'تجنب ذكي؛ أعمدة الإضاءة قد تسرب تياراً بالماء المجمع حولها.',
              'safeExpEn': 'Smart avoidance; grounded metal poles can leak current into surrounding wet puddles.',
              'safeOutAr': 'ابتعدت عن أعمدة الحوش للمحطة 3.',
              'safeOutEn': 'Kept clear of yard poles for Station 3.',
              'unsafeTextAr': 'الاستناد بيدك على العمود المعدني المبتل أثناء السير بالمياه',
              'unsafeTextEn': 'Lean bare hand against metal light pole while wading through puddle',
              'unsafeExpAr': 'خطأ؛ العمود المبتل المشحون يسبب صعقاً كلياً أثناء خوض الماء.',
              'unsafeExpEn': 'Error; leaning on energized wet metal pole while grounded in water causes fatal shock.',
              'unsafeOutAr': 'صعق عبر العمود.',
              'unsafeOutEn': 'Pole contact electrocution.',
            },
            {
              'sitAr': 'تسرب مياه الأمطار من السقف فوق لوحة القواطع الرئيسية بالمنزل. ما الإجراء الفوري؟',
              'sitEn': 'Rainwater leaking from ceiling directly onto main breaker panel board. Immediate act?',
              'hintAr': 'عدم لمس اللوحة، وتغطيتها بعازل بلاستيكي واستدعاء طوارئ الكهرباء أو فني مختص',
              'hintEn': 'Do NOT touch panel; isolate main power if safe from dry distance and call electrician',
              'safeTextAr': 'الوقوف على لوح خشبي جاف واستخدام عصا عازلة لإغلاق القاطع الرئيسي وتغطيتها بجلاد بلاستيك',
              'safeTextEn': 'Stand on dry wooden board using insulating rod to trip main breaker, cover panel with plastic',
              'safeExpAr': 'تصرف احترافي؛ تجنب اللمس المباشر مع عزل مصدر المياه يحمي الشبكة من الانفجار.',
              'safeExpEn': 'Pro step; avoiding direct contact while isolating panel protects home grid from arc blowout.',
              'safeOutAr': 'حميت لوحة القواطع للمحطة 4.',
              'safeOutEn': 'Shielded breaker panel for Station 4.',
              'unsafeTextAr': 'مسح المياه عن لوحة القواطع بقماش رطب بيدك المباشرة',
              'unsafeTextEn': 'Wipe water off live breaker panel with damp cloth using bare hands',
              'unsafeExpAr': 'خطأ قاتل؛ القماش الرطب واللوحة المشحونة يسبب انغلاق دائرة صعق عالية.',
              'unsafeExpEn': 'Fatal mistake; damp cloth completes high-voltage arc path to human body.',
              'unsafeOutAr': 'حدث قوس صعق باللوحة.',
              'unsafeOutEn': 'Panel arc flash shock.',
            },
            {
              'sitAr': 'فصل التيار الكهربائي وتوقف المطر. متى تعيد تشغيل الدوائر المبتلة؟',
              'sitEn': 'Rain stopped and main power off. When is it safe to re-energize wet outdoor circuits?',
              'hintAr': 'الانتظار حتى جفاف المقابس والأعمدة تماماً وفحصها بواسطة فني كهربائي',
              'hintEn': 'Wait until all outlets & poles are 100% dry and tested by qualified electrician',
              'safeTextAr': 'ترك الدوائر الخارجية مفصولة حتى جفافها الكلي وفحص العزل بواسطة فني مختص',
              'safeTextEn': 'Keep outdoor circuits isolated until fully air-dried and insulation tested by electrician',
              'safeExpAr': 'صبر آمن؛ إعادة الكهرباء والرطوبة موجودة يسبب ماساً كبيراً فجائياً.',
              'safeExpEn': 'Safe patience; energizing wet insulation triggers destructive short circuit faults.',
              'safeOutAr': 'انتظرت الجفاف التام للمحطة 5.',
              'safeOutEn': 'Waited for complete dry out for Station 5.',
              'unsafeTextAr': 'إعادة رفع القاطع فور توقف المطر والمقابس ما زالت ممتلئة بالماء',
              'unsafeTextEn': 'Flip breaker switch back on immediately while outlets are still dripping wet',
              'unsafeExpAr': 'خطأ؛ الرطوبة المحتبسة بالداخل تفجر المقابس فور سريان التيار.',
              'unsafeExpEn': 'Error; trapped moisture blows out sockets instantly upon re-energizing.',
              'unsafeOutAr': 'انفجرت المقابس المبتلة.',
              'unsafeOutEn': 'Wet sockets blew out.',
            },
            {
              'sitAr': 'إصلاح عزل المقابس الخارجية بتثبيت أغطية مطاطية محكمة. ما الوقاية الدائمة؟',
              'sitEn': 'Replaced outdoor sockets with IP66 weatherproof units. Permanent safety rule?',
              'hintAr': 'تركيب مقابس مقاومة للمياه والمعايير الجوية (IP66 Weatherproof) بكافة الساحات',
              'hintEn': 'Install IP66 NEMA-rated weatherproof sealed covers on all outdoor outlets',
              'safeTextAr': 'تركيب مقابس معزولة ضد الماء والأتربة بدرجة حماية (IP66) بكافة حوائط الحوش الخارجية',
              'safeTextEn': 'Install IP66 heavy-duty weatherproof sealed outlets across all exterior yard walls',
              'safeExpAr': 'إتمام كامل؛ غطاء IP66 يحمي المقابس من غزارة الأمطار والأتربة نهائياً.',
              'safeExpEn': 'Complete resolution; IP66 enclosures guarantee 100% water and dust isolation.',
              'safeOutAr': 'أكملت محطات الماس الكهربائي بالأمطار بنجاح!',
              'safeOutEn': 'Successfully cleared rain short circuit safety scenario!',
              'unsafeTextAr': 'تركت المقابس التجارية العادية مكشوفة للسماء بالحديقة',
              'unsafeTextEn': 'Leave cheap indoor commercial sockets exposed to sky in outdoor garden',
              'unsafeExpAr': 'خطأ؛ المقابس غير المعزولة تضمن تكرار الماس الكهربائي في كل مطر.',
              'unsafeExpEn': 'Error; unsealed indoor sockets guarantee short circuits during every rainfall.',
              'unsafeOutAr': 'تكرار مخاطر الماس بالسيول.',
              'unsafeOutEn': 'Recurrent wet short hazard.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_7',
          categoryId: 'electric',
          titleAr: 'سخونة الشواحن وبطاريات الليثيوم',
          titleEn: 'Lithium Battery & Charger Thermal Runaway',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انتفاخ بطاريات الجوال وسخونة الشواحن.',
          descriptionEn: 'Interactive 5-station scenario for lithium battery swelling & overheating safety.',
          difficulty: 'سهل',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'شعرت بسخونة عالية وانتفاخ في ظهر الجوال أثناء الشحن تحت الوسادة. ما الإجراء الأول؟',
              'sitEn': 'Phone feeling extremely hot with swollen back cover while charging under pillow. First action?',
              'hintAr': 'فصل الشاحن فوراً ونقل الجوال إلى سطح غير قابل للاشتعال بعيداً عن المفارش',
              'hintEn': 'Unplug charger immediately and move phone to non-flammable surface away from bedding',
              'safeTextAr': 'فصل الشاحن من المقبس ونقل الجوال فوراً إلى أرضية بلاط أو سطح معدني مفتوح',
              'safeTextEn': 'Unplug charger from wall and move phone immediately to bare tile floor away from fabrics',
              'safeExpAr': 'تصرف ممتاز؛ إبعاد البطارية الساخنة عن المفارش يمنع اندلاع حريق الليثيوم.',
              'safeExpEn': 'Excellent step; moving thermal runaway battery away from bedding prevents bedroom fire.',
              'safeOutAr': 'نقلت الجوال لسطح آمن للمحطة 2.',
              'safeOutEn': 'Moved phone to safe tile surface for Station 2.',
              'unsafeTextAr': 'ترك الجوال يشحن تحت الوسادة ومواصلة النوم',
              'unsafeTextEn': 'Leave hot phone charging under pillow and go back to sleep',
              'unsafeExpAr': 'خطأ جسيم؛ احتباس حرارة الليثيوم تحت الوسادة يسبب انفجار البطارية واشتعال السرير.',
              'unsafeExpEn': 'Severe error; trapping lithium thermal heat under pillow causes explosive battery fire.',
              'unsafeOutAr': 'احتبست الحرارة بالوسادة.',
              'unsafeOutEn': 'Thermal heat trapped in bedding.',
            },
            {
              'sitAr': 'تصاعد دخان رمادي ذو رائحة كيميائية نافذة من البطارية المنتفخة. كيف تتعامل معها؟',
              'sitEn': 'Gray chemical smoke venting from swollen swollen lithium battery. How to handle?',
              'hintAr': 'عدم استنشاق الغازات، عدم ثقب البطارية، وإبعاد جميع الأشخاص عن الغرفة',
              'hintEn': 'Do NOT inhale toxic battery fumes, NEVER puncture swelling cells, ventilate room',
              'safeTextAr': 'فتح النوافذ لتهوية الغرفة، تجنب استنشاق الدخان السام، وعدم ثقب البطارية مطلقاً',
              'safeTextEn': 'Open windows for room ventilation, avoid breathing toxic venting gas, NEVER puncture cell',
              'safeExpAr': 'إجراء سليم؛ ثقب بطارية الليثيوم المنتفخة يطلق لهباً كيميائياً شديد الانفجار.',
              'safeExpEn': 'Correct rule; puncturing swollen lithium cells causes violent atmospheric chemical ignition.',
              'safeOutAr': 'هويت الغرفة وحميت البطارية للمحطة 3.',
              'safeOutEn': 'Ventilated room safely for Station 3.',
              'unsafeTextAr': 'الضغط على البطارية المنتفخة بآلة حادة لثقبها وتفريغ الغاز',
              'unsafeTextEn': 'Press sharp needle into swollen battery casing to release trapped gas',
              'unsafeExpAr': 'خطأ قاتل؛ ثقب الليثيوم ينتج نفوذاً حرارياً وشعلة نارية مفاجئة بوجهك.',
              'unsafeExpEn': 'Fatal error; puncturing lithium cell instantly spews 1000°C chemical fire stream.',
              'unsafeOutAr': 'حدث انفجار كيميائي شعلاني.',
              'unsafeOutEn': 'Lithium jet fire explosion.',
            },
            {
              'sitAr': 'استخدام شواحن تجارية مقلدة بدون مواصفات. ما خطورتها على السلامة الكهربائية؟',
              'sitEn': 'Using cheap uncertified knock-off wall wall chargers. Fire safety risk?',
              'hintAr': 'الشواحن المقلدة تفتقر لدوائر الفصل التلقائي وتسبب ماساً وانفجار البطاريات',
              'hintEn': 'Knock-off chargers lack auto-cut circuits causing battery overcharging and voltage spikes',
              'safeTextAr': 'التخلص من الشواحن المقلدة واستخدام شواحن ذات جودة معتمدة تحمل قواطع ذكية',
              'safeTextEn': 'Dispose of knock-off plugs and use manufacturer-certified smart chargers with auto-cutoff',
              'safeExpAr': 'اختيار صحي؛ الشواحن الأصلية تضبط شدة التيار وتتوقف تلقائياً عند اكتمال الشحن.',
              'safeExpEn': 'Smart choice; certified chargers regulate current and cut off power upon 100% charge.',
              'safeOutAr': 'استبدلت الشاحن بالمستوفي للمواصفات للمحطة 4.',
              'safeOutEn': 'Replaced with certified charger for Station 4.',
              'unsafeTextAr': 'شراء أرخص شاحن تجاري بالأسواق واستخدامه للشحن طوال الليل',
              'unsafeTextEn': 'Buy cheapest dollar charger in market running heavy overnight battery charges',
              'unsafeExpAr': 'خطأ؛ الشواحن التالفة تسرب تياراً متردداً عالياً يدمّر دوائر الجوال الداخلية.',
              'unsafeExpEn': 'Error; cheap uncertified adapters leak AC ripple voltage blowing up battery chips.',
              'unsafeOutAr': 'تلف دائرة الشحن.',
              'unsafeOutEn': 'Charger chip blown.',
            },
            {
              'sitAr': 'اندلاع حريق صغير في بنك الطاقة (Power Bank) على المكتب. ما الوسيلة المثالية لإطفائه؟',
              'sitEn': 'Small lithium fire erupts on power bank unit on desk. Ideal extinguishing method?',
              'hintAr': 'استخدام غمر الماء بكميات كبيرة أو طفاية البودرة الجافة وتجنب غطائها بالوسائد',
              'hintEn': 'Use copious amounts of water or ABC dry chemical extinguisher; never cover with towels',
              'safeTextAr': 'استخدام طفاية حريق البودرة الجافة (ABC) أو ركب كمية مياه وفيرة للتبريد الكيميائي',
              'safeTextEn': 'Use ABC dry chemical extinguisher or douse with heavy water stream to cool thermal runaway',
              'safeExpAr': 'إطفاء آمن؛ تبريد الليثيوم بالماء الكثيف يوقف التسلسل الحراري التفاعلي.',
              'safeExpEn': 'Safe extinguishment; heavy water deluge cools cells stopping internal thermal cascade.',
              'safeOutAr': 'أخمدت حريق بنك الطاقة للمحطة 5.',
              'safeOutEn': 'Extinguished power bank fire for Station 5.',
              'unsafeTextAr': 'تغطية بنك الطاقة المشتعل ببطانية قماشية أو وسادة ناعمة',
              'unsafeTextEn': 'Throw soft fabric blanket or pillow over burning lithium power bank',
              'unsafeExpAr': 'خطأ؛ حرارة الليثيوم تخترق البطانيات وتزيد اشتعال الأقمشة بسرعة.',
              'unsafeExpEn': 'Error; lithium fire burns at extreme temperature instantly igniting fabric covers.',
              'unsafeOutAr': 'اشتعلت البطانية.',
              'unsafeOutEn': 'Blanket caught fire.',
            },
            {
              'sitAr': 'التخلص من البطاريات المنتفخة والتالفة. ما الطريق البيئي والآمن الصحيح؟',
              'sitEn': 'Disposing of swollen or damaged lithium batteries. Safe environmental route?',
              'hintAr': 'تسليمها لحاويات إعادة التدوير المخصصة للنفايات الإلكترونية وعدم رميها بالحاويات العادية',
              'hintEn': 'Deposit at designated e-waste recycling collection points; NEVER toss in household trash',
              'safeTextAr': 'تسليم البطاريات المنتفخة لمراكز تدوير النفايات الإلكترونية المعتمده وتعديل المقابس',
              'safeTextEn': 'Take damaged batteries to designated e-waste recycling collection drop-boxes',
              'safeExpAr': 'إتمام كامل؛ عزل البطاريات يمنع انضغاطها بالثرامات وضغط حاويات البلدية.',
              'safeExpEn': 'Complete resolution; proper e-waste disposal prevents garbage truck compaction fires.',
              'safeOutAr': 'أكملت محطات سلامة بطاريات الليثيوم بنجاح!',
              'safeOutEn': 'Successfully completed lithium battery safety scenario!',
              'unsafeTextAr': 'رمي البطارية المنتفخة في سلة المهملات المنزلية مع الأوراق',
              'unsafeTextEn': 'Toss swollen lithium battery directly into kitchen trash can with papers',
              'unsafeExpAr': 'خطأ؛ انضغاط النفايات يثقب البطارية ويشعل حريقاً ضخماً بحاوية القمامة.',
              'unsafeExpEn': 'Error; trash compaction punctures swollen cell starting heavy garbage fires.',
              'unsafeOutAr': 'اشتعلت سلة المهملات.',
              'unsafeOutEn': 'Garbage container ignited.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_8',
          categoryId: 'electric',
          titleAr: 'تأمين ألعاب الأطفال الكهربائية والشواحن',
          titleEn: 'Electric Toys & Low-Voltage Child Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لحماية الأطفال من ابتلاع البطاريات وعبث المقابس.',
          descriptionEn: 'Interactive 5-station scenario protecting children from battery ingestion & socket tampering.',
          difficulty: 'سهل',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'طفل صغير يحاول إدخال مسمار معدني داخل فتحة مقبس الكهرباء الجداري. ما الإجراء الفوري؟',
              'sitEn': 'Toddler trying to insert metal pin into wall electrical outlet socket. Immediate action?',
              'hintAr': 'إبعاد الطفل هادئاً فورا وتغطية المقابس بأغطية الأمان البلاستيكية',
              'hintEn': 'Gently pull child away immediately and install plastic safety outlet plugs',
              'safeTextAr': 'إبعاد الطفل بآمان فوراً وتركيب أغطية الحماية البلاستيكية (Outlet Caps) على جميع المقابس المنخفضة',
              'safeTextEn': 'Safely pull child away and install child-proof plastic outlet caps over all low wall sockets',
              'safeExpAr': 'استجابة حاسمة؛ أغطية السلامة تغلق الفتحات وتمنع عبث الأطفال بالأجسام المعدنية.',
              'safeExpEn': 'Critical response; safety caps block socket contacts preventing child insertion injuries.',
              'safeOutAr': 'ركبت أغطية الحماية للمحطة 2.',
              'safeOutEn': 'Installed child outlet caps for Station 2.',
              'unsafeTextAr': 'ترك المقابس المنخفضة مكشوفة والاعتماد على التنبيه الشفهي للطفل',
              'unsafeTextEn': 'Leave low sockets open relying solely on verbal warnings to a 2-year-old child',
              'unsafeExpAr': 'خطأ؛ الأطفال ينسون التحذيرات والشغوف يدفعهم لإدخال المعادن بالقابس.',
              'unsafeExpEn': 'Error; toddlers are curious and lack risk awareness inserting conductive items.',
              'unsafeOutAr': 'مخاطرة بعبث الأطفال.',
              'unsafeOutEn': 'Child socket tampering risk.',
            },
            {
              'sitAr': 'انكشاف غطاء غلاف بطارية القرص الصغيرة (Button Battery) في لعبة الطفل. ما الخطورة؟',
              'sitEn': 'Button cell battery compartment loose on child toy. What is the severe risk?',
              'hintAr': 'بطاريات القرص تسبب ثقباً كيميائياً قاتلاً بالمرئ خلال ساعتين عند ابتلاعها',
              'hintEn': 'Swallowed button batteries cause catastrophic chemical esophageal tissue burns in 2 hours',
              'safeTextAr': 'تثبيت غطاء البطارية ببرغي معدني محكم وتفقد سلامة ألعاب الأطفال دائماً',
              'safeTextEn': 'Ensure battery cover is tightly secured with a screw, inspecting all child toys regularly',
              'safeExpAr': 'وعي تام؛ غطاء البرغي المجهّز يمنع سقوط بطاريات القرص وابتلاعها الصامت.',
              'safeExpEn': 'Full awareness; screw-secured compartments prevent accidental child battery swallowing.',
              'safeOutAr': 'أمنت غطاء ألعاب الأطفال للمحطة 3.',
              'safeOutEn': 'Secured toy battery hatch for Station 3.',
              'unsafeTextAr': 'إغلاق الغطاء بشريط لاصق ضعيف يسهل نزعه بأسنان الطفل',
              'unsafeTextEn': 'Tape battery cover loosely with clear tape easily peeled off by child teeth',
              'unsafeExpAr': 'خطأ؛ الشريط الضعيف ينزع بأسنان الطفل مما يتيح الابتلاع الخطير.',
              'unsafeExpEn': 'Error; flimsy tape is easily chewed off by toddlers leading to battery ingestion.',
              'unsafeOutAr': 'انزع الشريط اللاصق.',
              'unsafeOutEn': 'Tape peeled off easily.',
            },
            {
              'sitAr': 'اشتباه في ابتلاع الطفل لبطارية قرصية صغيرة. ما الإجراء الطبي الطارئ؟',
              'sitEn': 'Suspecting child swallowed a button battery. Immediate emergency medical step?',
              'hintAr': 'التوجه فوراً لطوارئ المستشفى (997/937) وعدم إجبار الطفل على التقيؤ',
              'hintEn': 'Rush to ER immediately (997); NEVER induce vomiting or give food/water',
              'safeTextAr': 'التوجه فوراً لأقرب طوارئ مستشفى والاتصال بـ 997 وعدم إعطاء أي طعام أو إحداث تقيؤ',
              'safeTextEn': 'Rush instantly to hospital ER, alert 997, and strictly avoid inducing vomiting',
              'safeExpAr': 'إجراء طبي حرج؛ التقيؤ قد يسبب تآكلاً مزدوجاً بالمرئ والقصبة الهوائية.',
              'safeExpEn': 'Critical medical protocol; inducing vomiting amplifies esophageal chemical tissue destruction.',
              'safeOutAr': 'توجّهت للطوارئ الطبية للمحطة 4.',
              'safeOutEn': 'Rushed to ER for Station 4.',
              'unsafeTextAr': 'إعطاء الطفل عصيراً أو ماء وجعله يستفرغ في المنزل',
              'unsafeTextEn': 'Make child drink juice and force them to vomit at home',
              'unsafeExpAr': 'خطأ قاتل؛ التقيؤ يوزع الحمض الكيميائي للبطارية في الأنسجة الحساسة.',
              'unsafeExpEn': 'Fatal mistake; forcing vomiting spreads corrosive battery alkali across internal tissue.',
              'unsafeOutAr': 'تسبب التقيؤ بتآكل الأنسجة.',
              'unsafeOutEn': 'Caused secondary corrosive tissue damage.',
            },
            {
              'sitAr': 'تشغيل سيارة الأطفال الكهربائية بالقرب من مسبح المنزل. ما تقييم السلامة؟',
              'sitEn': 'Riding electric ride-on toy car near home swimming pool. Safety evaluation?',
              'hintAr': 'إبعاد السيارات الكهربائية عن حواف المسبح ومنع القيادة بدون إشراف',
              'hintEn': 'Keep electric ride-on toys away from pool edges; strictly supervise play',
              'safeTextAr': 'منع قيادة السيارات الكهربائية بالقرب من المسبح وإغلاق سياج حماية المسبح دائماً',
              'safeTextEn': 'Strictly ban electric ride-on cars near pool area maintaining locked safety pool fence',
              'safeExpAr': 'تأمين ممتاز؛ سقوط سيارة كهربائية ببطاريتها بالمسبح يسبب الغرق والصعق.',
              'safeExpEn': 'Great securing; ride-on car falling into pool risks both drowning and electrical hazards.',
              'safeOutAr': 'أمنت منطقة لعب الأطفال للمحطة 5.',
              'safeOutEn': 'Secured safe play zone for Station 5.',
              'unsafeTextAr': 'سماح للطفل بالقيادة على حافة المسبح المفتوحة',
              'unsafeTextEn': 'Allow toddler to drive electric ride-on along slippery edge of open pool',
              'unsafeExpAr': 'خطأ؛ فقدان السيطرة قد يسقط الطفل والسيارة الثقيلة داخل الماء.',
              'unsafeExpEn': 'Error; minor steering slip plunges heavy battery car and child into water.',
              'unsafeOutAr': 'سقطت السيارة بالمسبح.',
              'unsafeOutEn': 'Ride-on car plunged into pool.',
            },
            {
              'sitAr': 'فحص كامل للأجهزة والمقابس المخصصة لغرف الأطفال. ما المعيار الدائم؟',
              'sitEn': 'Complete electrical audit of child bedrooms and playroom. Permanent standard?',
              'hintAr': 'تطبيق نظام السلامة الشامل للأطفال (Childproofing) بكافة الأجهزة والمقابس',
              'hintEn': 'Implement 100% child-proof electrical standard with tamper-resistant outlets (TR)',
              'safeTextAr': 'تركيب مقابس مقاومة للعبث (TR Outlets) وإخفاء أسلاك التوصيل خلف الأثاث',
              'safeTextEn': 'Upgrade to Tamper-Resistant (TR) electrical sockets and hide all wiring behind heavy furniture',
              'safeExpAr': 'إتمام كامل؛ مقابس TR تحتوي أبواباً داخلية تفتح فقط عند دخول الفيش المزدوج.',
              'safeExpEn': 'Complete resolution; TR sockets feature internal shutters opening only under dual-prong pressure.',
              'safeOutAr': 'أكملت محطات سلامة ألعاب وأجهزة الأطفال بنجاح!',
              'safeOutEn': 'Successfully completed child electrical safety scenario!',
              'unsafeTextAr': 'ترك أسلاك الشواحن متدلية بجانب سرير الطفل في الليل',
              'unsafeTextEn': 'Leave live phone charger cables dangling directly onto child bed mattress',
              'unsafeExpAr': 'خطأ؛ قد يضع الطفل الطرف المباشر للشاحن في فمه مما يسبب حروقاً كهربائية.',
              'unsafeExpEn': 'Error; infants often put live 5V/12V charger ends in mouth causing severe lip burns.',
              'unsafeOutAr': 'مخاطرة بحروق الفم.',
              'unsafeOutEn': 'Lip electrical burn hazard.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_electric_9',
          categoryId: 'electric',
          titleAr: 'طوارئ المحولات الكهربائية وغرف الكبائن',
          titleEn: 'Neighborhood Electric Substation & Cabinet Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجنب مخاطر كبائن ومحولات الكهرباء بالحياء والشارع.',
          descriptionEn: 'Interactive 5-station scenario for outdoor electric cabinet & substation safety.',
          difficulty: 'صعب',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          stations: [
            {
              'sitAr': 'لاحظت باب كبينة كهرباء بالشارع مفتوحاً وتدلي أسلاك ضغط عالي منها. ما أول إجراء؟',
              'sitEn': 'Neighborhood street electrical cabinet door hanging open with exposed high-voltage cables. Action?',
              'hintAr': 'الابتعاد فوراً والاتصال بطوارئ الشركة السعودية للكهرباء (933)',
              'hintEn': 'Keep clear immediately and report to Saudi Electricity emergency 933',
              'safeTextAr': 'الابتعاد مسافة 5 أمتار والاتصال الفوري بطوارئ الكهرباء (933) لإبلاغهم بالكبينة',
              'safeTextEn': 'Maintain 5m safe distance and call SEC emergency 933 immediately to report open cabinet',
              'safeExpAr': 'تصرف مسؤول؛ البلاغ السريع يضمن إرسال فرق الصيانة لإغلاق الباب قبل تعرض أحد للصعق.',
              'safeExpEn': 'Responsible response; fast reporting dispatches repair crews before public contact occurs.',
              'safeOutAr': 'بلغت طوارئ الكهرباء للمحطة 2.',
              'safeOutEn': 'Reported open cabinet to SEC for Station 2.',
              'unsafeTextAr': 'محاولة إغلاق باب الكبينة بيدك المباشرة أو دفع الأسلاك بالداخل',
              'unsafeTextEn': 'Try closing heavy metal cabinet door with bare hands pushing loose wires in',
              'unsafeExpAr': 'خطأ مهلك؛ ملامسة الباب أو الأسلاك المكشوفة يسبب قوساً كهربائياً قاتلاً.',
              'unsafeExpEn': 'Fatal mistake; touching cabinet body or exposed conductors triggers catastrophic arc flash.',
              'unsafeOutAr': 'حدث شرر قوس بالكبينة.',
              'unsafeOutEn': 'Triggered cabinet arc flash.',
            },
            {
              'sitAr': 'انبعاث طنين عالي ودخان أسود من محول الكهرباء بالحي (Transformer). كيف تحمي المتواجدين؟',
              'sitEn': 'Loud humming noise and black smoke spewing from neighborhood pole transformer. Action?',
              'hintAr': 'تحذير المارة ومنع الوقوف تحت المحول أو إيقاف السيارات أسفله',
              'hintEn': 'Warn pedestrians away and prevent parking cars directly underneath failing transformer',
              'safeTextAr': 'تحذير المشاة بالشارع ومنع إيقاف السيارات تحت المحول تحسباً لانفجاره',
              'safeTextEn': 'Warn passersby away and clear parked cars underneath in case transformer explodes',
              'safeExpAr': 'تأمين ممتاز؛ انفجار المحولات يفرغ زيتاً مغلياً وشرراً نائراً في قطر واسع.',
              'safeExpEn': 'Great safety measure; failing transformers spray burning dielectric oil and shrapnel over a wide radius.',
              'safeOutAr': 'أمنت منطقة المحول للمحطة 3.',
              'safeOutEn': 'Secured transformer safety zone for Station 3.',
              'unsafeTextAr': 'الوقوف أسفل المحول مباشرة والتحديق في الدخان المتصاعد',
              'unsafeTextEn': 'Stand directly underneath smoking transformer staring up at sparking wires',
              'unsafeExpAr': 'خطأ؛ تساقط الزيت المغلي والشظايا يسبب إصابات بالغة بالعين والوجه.',
              'unsafeExpEn': 'Error; falling superheated transformer oil causes severe facial and eye burn injuries.',
              'unsafeOutAr': 'تعرضت لقطرات الزيت المغلي.',
              'unsafeOutEn': 'Struck by falling burning oil droplets.',
            },
            {
              'sitAr': 'توقف سيارتك بالقرب من كبينة كهرباء مغمورة بماء السيول بالحي. كيف تتصرف؟',
              'sitEn': 'Car parked next to neighborhood electrical cabinet submerged in rain floodwater. Action?',
              'hintAr': 'عدم الخوض بالماء المحيط بالكبينة نهائياً واستدعاء الدفاع المدني (998)',
              'hintEn': 'NEVER step into water around flooded power cabinet; call 998/933',
              'safeTextAr': 'عدم المشي بالماء المحيط بالكبينة نهائياً والاتصال بـ 911 أو 933 لعزل التيار',
              'safeTextEn': 'Do NOT enter flooded water near cabinet; call 911/933 to isolate neighborhood power grid',
              'safeExpAr': 'حذر حكيم؛ الماء المغمور بالكبينة يصبح مشحوناً بتيار كهربائي قاتل.',
              'safeExpEn': 'Wise caution; floodwater submerging power cabinets becomes lethally charged with voltage.',
              'safeOutAr': 'تجنبت خوض الماء المشحون للمحطة 4.',
              'safeOutEn': 'Avoided charged floodwater for Station 4.',
              'unsafeTextAr': 'الخوض بالماء حافي القدمين لسحب السيارة المجاورة للكبينة',
              'unsafeTextEn': 'Wade barefoot into floodwater to drive car parked next to flooded cabinet',
              'unsafeExpAr': 'خطأ قاتل؛ الخوض بالماء المشحون يسبب الصعق الفوري قبل الوصول للسيارة.',
              'unsafeExpEn': 'Fatal error; stepping into electrified water causes instant lethal grounding shock.',
              'unsafeOutAr': 'صعق مائي بالكبينة.',
              'unsafeOutEn': 'Cabinet flood electrocution.',
            },
            {
              'sitAr': 'وصول فرق طوارئ الكهرباء للتعامل مع كبينة الحي. كيف تسهل عمل الفنيين؟',
              'sitEn': 'SEC emergency repair crew arrives at neighborhood cabinet. How to facilitate work?',
              'hintAr': 'إخلاء المسار لمركبات الصيانة والابتعاد عن نطاق العمل الفني',
              'hintEn': 'Clear access path for SEC repair utility trucks and remain clear of work area',
              'safeTextAr': 'إفساح الطريق لسيارات الصيانة والالتزام بالوقوف خلف الشريط التحذيري الأصفر',
              'safeTextEn': 'Clear access for utility trucks and remain standing behind yellow caution tape perimeter',
              'safeExpAr': 'تعاون محترف؛ ترك مساحة للفنيين يسرع إصلاح العطل وحماية الحي.',
              'safeExpEn': 'Pro cooperation; keeping distance allows technicians to work safely and restore power fast.',
              'safeOutAr': 'سهلت عمل الصيانة للمحطة 5.',
              'safeOutEn': 'Facilitated repair work for Station 5.',
              'unsafeTextAr': 'التجمهر حول الكبينة وإعاقة حركة الفنيين أثناء الفحص الفني',
              'unsafeTextEn': 'Crowd closely around open electrical cabinet interrupting technical team',
              'unsafeExpAr': 'خطأ؛ التجمهر يعرض المتواجدين لخطر القوس الكهربائي المفاجئ أثناء الاختبار.',
              'unsafeExpEn': 'Error; crowding around open live cabinets exposes onlookers to arc flash during testing.',
              'unsafeOutAr': 'تعرضت لخطر التجمهر.',
              'unsafeOutEn': 'Onlooker arc flash risk.',
            },
            {
              'sitAr': 'إتمام إغلاق وإصلاح كبينة الكهرباء وإعادة التيار للحي. ما التوجيه الدائم؟',
              'sitEn': 'Cabinet repaired, locked, and power restored to neighborhood. Permanent rule?',
              'hintAr': 'توعية أفراد الأسرة بعدم تسلق أو العبث بكبائن ومحولات الكهرباء مطلقاً',
              'hintEn': 'Educate family and children never to climb or tamper with outdoor electrical cabinets',
              'safeTextAr': 'توعية الأطفال والأسرة بعدم الاقتراب أو التسلق على كبائن ومحولات الكهرباء بالحي',
              'safeTextEn': 'Educate children and family members strictly never to lean, climb, or touch outdoor electric boxes',
              'safeExpAr': 'إتمام كامل؛ التوعية الحضرية تضمن بيئة آمنة وتمنع الحوادث الكهربائية بالمرور.',
              'safeExpEn': 'Complete resolution; public safety awareness prevents tragic electrocutions in high-density areas.',
              'safeOutAr': 'أكملت محطات طوارئ كبائن ومحولات الكهرباء بنجاح!',
              'safeOutEn': 'Successfully completed electrical substation & cabinet safety scenario!',
              'unsafeTextAr': 'السماح للأطفال باللعب والتسلق فوق كبينة الكهرباء الخارجية',
              'unsafeTextEn': 'Allow children to use low neighborhood electric cabinet as a play jungle gym',
              'unsafeExpAr': 'خطأ خطير؛ التسلق على كبائن الكهرباء يسبب حوادث صعق وسقوط مميتة.',
              'unsafeExpEn': 'Dangerous mistake; climbing electrical cabinets risks high-voltage shock and severe falls.',
              'unsafeOutAr': 'مخاطرة بتسلق الأطفال.',
              'unsafeOutEn': 'Child cabinet climbing risk persisted.',
            },
          ],
        ),
      ];
}
