import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosFire {
  static List<Scenario> get list => [
        // 1. Fire Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_1',
          categoryId: 'fire',
          titleAr: 'حريق المطبخ ومقلاة الزيت المشتعلة',
          titleEn: 'Kitchen Oil Fire Response',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حرائق الزيت والغاز والإخلاء الآمن.',
          descriptionEn: 'Interactive 5-station scenario for kitchen oil fires and safe smoke evacuation.',
          difficulty: 'متوسط',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'تصاعد دخان ورائحة غاز داخل المطبخ. ما أول تصرف بحذر؟',
              'sitEn': 'Smoke and gas smell detected in kitchen. Immediate step?',
              'hintAr': 'إغلاق صمام الغاز وتجنب إشعال أو إطفاء أي مفتاح كهربائي',
              'hintEn': 'Shut gas valve and avoid touching electrical switches',
              'safeTextAr': 'إغلاق صمام الغاز الرئيسي وتجنب تشغيل مفاتيح الإضاءة أو الشفاط',
              'safeTextEn': 'Close main gas valve and avoid toggling light switches or electric hood',
              'safeExpAr': 'تصرف ممتاز؛ منع التشرر الكهربائي يقي من حدوث انفجار غازي.',
              'safeExpEn': 'Excellent action; preventing electrical spark avoids gas explosion.',
              'safeOutAr': 'أمّنت مصدر الغاز وتوجهت للمحطة 2.',
              'safeOutEn': 'Secured gas source, proceeding to Station 2.',
              'unsafeTextAr': 'تشغيل الشفاط الكهربائي بأقصى سرعة لشفط الدخان والغاز',
              'unsafeTextEn': 'Turn electric hood fan to max speed to pull smoke and gas',
              'unsafeExpAr': 'خطأ جسيم؛ المحرك الكهربائي يولد شرارة صغيرة قد تفجر الغاز المتسرب.',
              'unsafeExpEn': 'Severe error; electrical fan motor sparks can ignite trapped gas.',
              'unsafeOutAr': 'تسببت في شرارة خطر بالمطبخ.',
              'unsafeOutEn': 'Caused high ignition risk in kitchen.',
            },
            {
              'sitAr': 'اشتعلت مقلاة الزيت فوق الفرن. كيف تخمد النار بأمان؟',
              'sitEn': 'Cooking oil pan catches fire. How to safely smother flames?',
              'hintAr': 'غطِ المقلاة بغطاء معدني أو بطانية حريق، ولا تسكب الماء مطلقاً',
              'hintEn': 'Cover pan with metal lid or fire blanket; NEVER pour water on hot oil fire',
              'safeTextAr': 'تغطية المقلاة بغطاء معدني أو بطانية حريق وفصل مصدر الحرارة',
              'safeTextEn': 'Cover pan with metal lid or fire blanket and turn off stove element',
              'safeExpAr': 'حكمة عالية؛ خنق الأكسجين يخمد حريق الزيت فوراً.',
              'safeExpEn': 'Wise action; cutting off oxygen smothers oil fire instantly.',
              'safeOutAr': 'أخمدت حريق المقلاة وانتقلت للمحطة 3.',
              'safeOutEn': 'Smothered pan fire, advancing to Station 3.',
              'unsafeTextAr': 'سكب كوب ماء بارد مباشرة فوق الزيت المشتعل',
              'unsafeTextEn': 'Pour a cup of cold water directly over burning grease',
              'unsafeExpAr': 'خطأ كارثي؛ الماء يتبخر فوراً وينشر رذاذ الزيت المشتعل بالسقف.',
              'unsafeExpEn': 'Catastrophic error; water flash-evaporates exploding burning oil everywhere.',
              'unsafeOutAr': 'انتشرت النيران في المطبخ.',
              'unsafeOutEn': 'Flames exploded across kitchen space.',
            },
            {
              'sitAr': 'امتلأت الممرات بالدخان الخانق. كيف تتحرك نحو المخرج؟',
              'sitEn': 'Hallways filling with thick smoke. How to move toward exit?',
              'hintAr': 'الانخفاض أرضاً والتنفس بمحاذاة الأرض حيث الهواء النقي',
              'hintEn': 'Crawl low under smoke layer where fresh air remains',
              'safeTextAr': 'الانخفاض أرضاً والحبو تحت مستوى الدخان مع وضع قماش رطب على الأنف',
              'safeTextEn': 'Crawl low under smoke line placing damp cloth over nose and mouth',
              'safeExpAr': 'ممتاز؛ الهواء النقي يتجمع بالأسفل بينما يرتفع الدخان السام للأعلى.',
              'safeExpEn': 'Excellent; breathable air settles low while toxic smoke rises up.',
              'safeOutAr': 'تجنبت الاختناق ووصلت للمحطة 4.',
              'safeOutEn': 'Avoided suffocation, reaching Station 4.',
              'unsafeTextAr': 'الركض واقفا بأقصى سرعة واستنشاق الهواء بعمق',
              'unsafeTextEn': 'Run fully upright taking deep breaths to move faster',
              'unsafeExpAr': 'خطأ خطير؛ استنشاق غاز أول أكسيد الكربون العالي يسبب الإغماء السريع.',
              'unsafeExpEn': 'Dangerous error; breathing upper hot carbon monoxide causes swift collapse.',
              'unsafeOutAr': 'تعرضت للاختناق بالدخان.',
              'unsafeOutEn': 'Suffered severe smoke inhalation.',
            },
            {
              'sitAr': 'استخدام طفاية البودرة الجافة لإخماد ألسنة اللهب المتبقية. ما ترتيب PASS؟',
              'sitEn': 'Operating dry powder extinguisher on residual fire. Correct PASS rule?',
              'hintAr': 'سحب الدبوس، التوجيه للقاعدة، الضغط على المقبض، والتكنيس يميناً ويساراً',
              'hintEn': 'Pull pin, Aim at base, Squeeze trigger, Sweep side-to-side',
              'safeTextAr': 'سحب أمان الطفاية، التوجيه لقاعدة النار، الضغط، والتكنيس يميناً ويساراً',
              'safeTextEn': 'Pull safety pin, aim nozzle at fire base, squeeze handle, sweep side-to-side',
              'safeExpAr': 'إتقان تام؛ توجيه البودرة لقاعدة اللهب يقطع التفاعل الكيميائي كلياً.',
              'safeExpEn': 'Perfect mastery; aiming at fuel base disrupts combustion chemical chain.',
              'safeOutAr': 'سيطرت على اللهب وتم تجهيز المحطة 5.',
              'safeOutEn': 'Controlled residual fire, proceeding to Station 5.',
              'unsafeTextAr': 'توجيه قذف الطفاية لأعلى قمة ألسنة الدخان من مسافة بعيدة',
              'unsafeTextEn': 'Aim extinguisher nozzle high into top smoke flames from far away',
              'unsafeExpAr': 'خطأ؛ الرش في القمة يفرغ البودرة دون الوصول لمصدر الوقود الاشتعالي.',
              'unsafeExpEn': 'Error; spraying flame tips wastes powder without extinguishing fuel source.',
              'unsafeOutAr': 'نفذت البودرة واستمرت النار.',
              'unsafeOutEn': 'Extinguisher depleted without suppressing core.',
            },
            {
              'sitAr': 'الخروج من المنزل إلى منطقة التجمع الخارجية. ما الخطوة النهائية؟',
              'sitEn': 'Evacuated safely outside building. Final essential protocol?',
              'hintAr': 'الاتصال بالدفاع المدني (998/911)، وإحصاء الأسرة دون العودة للمبنى',
              'hintEn': 'Call Civil Defense 998/911, account for family members, do NOT re-enter',
              'safeTextAr': 'الاتصال بالدفاع المدني (998 أو 911)، التأكد من سلامة الجميع، وعدم العودة نهائياً',
              'safeTextEn': 'Call Saudi Civil Defense 998/911, account for all members, never re-enter',
              'safeExpAr': 'إتمام مثالي؛ تأمين نقطة التجمع وإبلاغ الطوارئ يضمن سلامة الجميع.',
              'safeExpEn': 'Flawless execution; securing assembly area and notifying 998 completes safety.',
              'safeOutAr': 'أكملت محطات إخلاء وإطفاء الحريق بنجاح!',
              'safeOutEn': 'Successfully cleared all 5 fire response stations!',
              'unsafeTextAr': 'العودة داخل المبنى المشتعل لإحضار الوثائق والأغراض الثمينة',
              'unsafeTextEn': 'Re-enter burning building to retrieve valuable documents and belongings',
              'unsafeExpAr': 'خطأ مهلك؛ العودة المبنى توقعك في مصيدة الدخان والانهيارات.',
              'unsafeExpEn': 'Fatal mistake; re-entering trapped victims in flashovers and structural collapse.',
              'unsafeOutAr': 'عرضت حياتك للخطر المحقق.',
              'unsafeOutEn': 'Endangered life by re-entering toxic zone.',
            },
          ],
        ),

        // 2. Fire Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_2',
          categoryId: 'fire',
          titleAr: 'حريق شاحن الجوال بغرفة النوم ليلاً',
          titleEn: 'Phone Charger Bedroom Fire',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع اشتعال شواحن البطاريات واحتواء حريق المفروشات.',
          descriptionEn: 'Interactive 5-station scenario to contain lithium charger fires on bed.',
          difficulty: 'سهل',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'استيقظت على شرر ودخان متصاعد من شاحن الجوال فوق السرير. ما أول تصرف؟',
              'sitEn': 'Woke up to sparks and smoke from phone charger on bed. First step?',
              'hintAr': 'سحب الفيش الرئيسي للكهرباء فوراً دون لمس السلك الساخن بيديك',
              'hintEn': 'Unplug main wall socket immediately without touching hot melted wire',
              'safeTextAr': 'سحب الفيش من مقبس الجدار فوراً بقطعة قماش جافة لقطع التيار',
              'safeTextEn': 'Unplug charger from wall outlet immediately using dry cloth',
              'safeExpAr': 'تصرف ممتاز؛ قطع التيار يوقف التغذية الكهربائية ويمنع الماس.',
              'safeExpEn': 'Excellent action; disconnecting power stops ongoing short circuit heating.',
              'safeOutAr': 'فصلت الكهرباء وانتقلت للمحطة 2.',
              'safeOutEn': 'Power cut, advancing to Station 2.',
              'unsafeTextAr': 'سحب السلك المشتعل بيديك العاريتين ومحاولة نفخه بالفم',
              'unsafeTextEn': 'Grab melting wire barehanded trying to blow out fire with breath',
              'unsafeExpAr': 'خطأ؛ السلك الساخن يسبب حروقاً باليد والنفخ يزيد اشتعال الأكسجين.',
              'unsafeExpEn': 'Error; melted wires burn hands and blowing provides oxygen to flames.',
              'unsafeOutAr': 'تعرضت يدك للحرق.',
              'unsafeOutEn': 'Burned hands on hot plastic.',
            },
            {
              'sitAr': 'انتقلت الجمرة إلى بطانية السرير وبدأت بالاتساع. كيف تخمدها؟',
              'sitEn': 'Fire spreads to bed blanket expanding fast. How to smother it?',
              'hintAr': 'استخدام طفاية حريق أو بطانية رطبة ثقيلة لخنق النار كلياً',
              'hintEn': 'Use fire extinguisher or heavy wet blanket to smother flames completely',
              'safeTextAr': 'تغطية المفروشات بطفاية البودرة أو بطانية رطبة ثقيلة لخنق النار',
              'safeTextEn': 'Cover burning bedding with heavy damp blanket or extinguisher powder',
              'safeExpAr': 'إجراء صحيح؛ قطع الهواء عن الأنسجة المشتعلة يوقف انتشار النار.',
              'safeExpEn': 'Correct step; smothering starves flames of required combustion oxygen.',
              'safeOutAr': 'سيطرت على حريق السرير للمحطة 3.',
              'safeOutEn': 'Smothered bed fire for Station 3.',
              'unsafeTextAr': 'مروحة بطانية أخرى فوق النار لتهوية الغرفة',
              'unsafeTextEn': 'Wave another dry blanket over fire to clear smoke',
              'unsafeExpAr': 'خطأ؛ التلويح بالبطانية يزيد تيار الهواء ويؤجج النار.',
              'unsafeExpEn': 'Error; fanning bedding fuels fire with surge of fresh air.',
              'unsafeOutAr': 'تأججت النار بالسرير.',
              'unsafeOutEn': 'Flames surged aggressively.',
            },
            {
              'sitAr': 'إخلاء أفراد الأسرة من الغرف المجاورة. ما أفضل طريقة لتنبيههم؟',
              'sitEn': 'Evacuating family members from nearby bedrooms. Best alarm method?',
              'hintAr': 'المناداة بصوت مرتفع "حريق" وإغلاق باب الغرفة المشتعلة لمنع انتشار الدخان',
              'hintEn': 'Shout "Fire" loudly and close burning room door behind you to contain smoke',
              'safeTextAr': 'الصرخة بالمناداة لإيقاظ الجميع وإغلاق باب الغرفة المشتعلة خلفك',
              'safeTextEn': 'Shout loudly to wake everyone and close room door behind to trap smoke',
              'safeExpAr': 'حكمة عالية؛ إغلاق باب الغرفة يعزل الحريق لمدة تزيد عن 15 دقيقة.',
              'safeExpEn': 'Wise tactic; closing interior door isolates fire and smoke for 15+ mins.',
              'safeOutAr': 'عزلت الغرفة وأيقظت الأسرة للمحطة 4.',
              'safeOutEn': 'Contained fire room, advancing to Station 4.',
              'unsafeTextAr': 'ترك باب الغرفة مفتوحاً بالكامل والهمس بصوت منخفض',
              'unsafeTextEn': 'Leave room door wide open while whispering quietly',
              'unsafeExpAr': 'خطأ؛ ترك الباب مفتوحاً يسمح للدخان بالتدفق لجميع غرف النوم.',
              'unsafeExpEn': 'Error; open doors allow toxic smoke to flood all sleeping quarters.',
              'unsafeOutAr': 'انتشر الدخان بالممر الرئيسي.',
              'unsafeOutEn': 'Smoke flooded sleeping corridor.',
            },
            {
              'sitAr': 'التوجه نحو مخرج المنزل والدخان يتصاعد. كيف تحمي مجرى التنفس؟',
              'sitEn': 'Moving toward front door as smoke rises. How to cover airway?',
              'hintAr': 'بل قماش بالماء ووضعه على الأنف والفم وتخفيض مستوى المشي',
              'hintEn': 'Dampen cloth with water over nose/mouth and stoop down low',
              'safeTextAr': 'ترطيب قماش بالماء ووضعه على الأنف والفم والانخفاض أثناء المشي',
              'safeTextEn': 'Cover nose and mouth with wet cloth while stooping down low',
              'safeExpAr': 'حماية ممتازة؛ القماش الرطب يفلتر رماد الكربون ويبرد الهواء المستنشق.',
              'safeExpEn': 'Great protection; damp fabric filters soot particles and cools inhaled air.',
              'safeOutAr': 'وصلت لباب المنزل للمحطة 5.',
              'safeOutEn': 'Reached exit door safely for Station 5.',
              'unsafeTextAr': 'التنفس السريع من الفم دون أي غطاء',
              'unsafeTextEn': 'Pant rapidly through open mouth with no filter',
              'unsafeExpAr': 'خطأ؛ استنشاق السخام الجاف يسبب كوي القصبة الهوائية والاختناق.',
              'unsafeExpEn': 'Error; inhaling dry hot soot causes airway burns and asphyxiation.',
              'unsafeOutAr': 'تعرضت للسعال الحاد والاختناق.',
              'unsafeOutEn': 'Suffered severe coughing fit.',
            },
            {
              'sitAr': 'الخروج للشارع والاتصال بـ (998 للدفاع المدني). ما البيانات المطلوبة؟',
              'sitEn': 'Outside on street calling 998 Civil Defense. What details to state?',
              'hintAr': 'تحديد المدينة، الحي، رقم الشارع، نوع الحريق، وحالة المحتجزين',
              'hintEn': 'Specify city, district, street name, fire type, and trapped person status',
              'safeTextAr': 'إعطاء العنوان بدقة، وذكر أن الحريق بسبب شاحن مع التأكيد على خروج جميع الأسرة',
              'safeTextEn': 'Give exact street address, mention charger origin, confirm all family evacuated',
              'safeExpAr': 'بلاغ نموذجي؛ يساعد فرق الإطفاء على الوصول الفوري وتوجيه معدات التهوية.',
              'safeExpEn': 'Model dispatch call; enables firefighters to reach location swiftly with fan gear.',
              'safeOutAr': 'أكملت محطات حريق الشاحن بنجاح!',
              'safeOutEn': 'Successfully completed charger fire scenario!',
              'unsafeTextAr': 'الاتصال والارتباك دون إعطاء اسم الحي أو رقم المنزل',
              'unsafeTextEn': 'Panic on phone call without giving neighborhood or house number',
              'unsafeExpAr': 'خطأ؛ عدم إعطاء العنوان يؤخر وصول آليات الإطفاء.',
              'unsafeExpEn': 'Error; missing location info delays fire engine arrival.',
              'unsafeOutAr': 'تأخرت آليات الدفاع المدني.',
              'unsafeOutEn': 'Civil defense arrival delayed.',
            },
          ],
        ),

        // 3. Fire Scenario 3
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_3',
          categoryId: 'fire',
          titleAr: 'ماس كهربائي بالقاطع الرئيسي بالشقة',
          titleEn: 'Main Breaker Electrical Spark Fire',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حرائق اللوحات الكهربائية الرئيسية.',
          descriptionEn: 'Interactive 5-station scenario for electrical breaker board fire management.',
          difficulty: 'صعب',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'انبعث شرر ورائحة بلاستيك محترق من لوحة المفاتيح الرئيسية. ما تصرفك؟',
              'sitEn': 'Sparks and burning plastic smell emitting from main breaker panel. Action?',
              'hintAr': 'فصل القاطع الخارجي الرئيسي إن أمكن وتجنب رش أي مياه إطلاقاً',
              'hintEn': 'Shut external main supply breaker if accessible; NEVER spray water',
              'safeTextAr': 'فصل القاطع الخارجي الرئيسي للشقة باستخدام عازل مطاطي',
              'safeTextEn': 'Disconnect external main apartment supply breaker using insulated tool',
              'safeExpAr': 'إجراء ممتاز؛ قطع المصدر الرئيسي يوقف التغذية الكهربائية للشرر.',
              'safeExpEn': 'Excellent action; isolating external breaker stops high voltage arcing.',
              'safeOutAr': 'قطعت التغذية الرئيسية للمحطة 2.',
              'safeOutEn': 'Main supply isolated for Station 2.',
              'unsafeTextAr': 'رش سطل ماء على اللوحة الكهربائية لإطفاء الشرر',
              'unsafeTextEn': 'Throw a bucket of water over electrical panel to extinguish sparks',
              'unsafeExpAr': 'خطأ كارثي؛ الماء موصل للكهرباء ويسبب صعقاً خطيراً وانفجار القاطع.',
              'unsafeExpEn': 'Catastrophic mistake; water conducts high voltage triggering massive explosion.',
              'unsafeOutAr': 'حدث انفجار باللوحة الكهربائية.',
              'unsafeOutEn': 'Electrical panel exploded from water shock.',
            },
            {
              'sitAr': 'اشتعلت النيران بالأسلاك البلاستيكية باللوحة. أي طفاية حريق تستخدم؟',
              'sitEn': 'Plastic wire insulation catches fire. Which extinguisher class?',
              'hintAr': 'استخدام طفاية ثاني أكسيد الكربون CO2 أو البودرة الجافة المخصصة للكهرباء',
              'hintEn': 'Use CO2 carbon dioxide or dry chemical powder extinguisher safe for electrics',
              'safeTextAr': 'استخدام طفاية ثاني أكسيد الكربون (CO2) أو البودرة الجافة (Class C)',
              'safeTextEn': 'Use CO2 gas extinguisher or Class C dry powder suitable for electrical fires',
              'safeExpAr': 'اختيار محترف؛ غاز CO2 غاز غير موصل ولا يترك رواسب تالفة بالأسلاك.',
              'safeExpEn': 'Professional choice; CO2 is non-conductive and leaves zero corrosive residue.',
              'safeOutAr': 'أخمدت حريق الأسلاك للمحطة 3.',
              'safeOutEn': 'Smothered wire fire for Station 3.',
              'unsafeTextAr': 'استخدام طفاية الرغوة الفوم المائية (Foam Extinguisher)',
              'unsafeTextEn': 'Use liquid water foam fire extinguisher',
              'unsafeExpAr': 'خطأ؛ طفايات الرغوة المائية موصلة للتيار الكهربائي وتسبب الصعق.',
              'unsafeExpEn': 'Error; water foam carries electric current creating shock hazard.',
              'unsafeOutAr': 'تعرضت لخطر الصعق بالرغوة.',
              'unsafeOutEn': 'Foam conducted high voltage current.',
            },
            {
              'sitAr': 'انتشار دخان البلاستيك السام بالممر. كيف تؤمن خروج الأطفال؟',
              'sitEn': 'Toxic burning PVC smoke fills corridor. How to guide children?',
              'hintAr': 'توجيه الأطفال للحبو على الأيدي والركبتين وتغطية الوجه بقماش رطب',
              'hintEn': 'Guide kids to crawl on hands and knees with wet towels over face',
              'safeTextAr': 'توجيه الأطفال للحبو على الأيدي والركبتين وتغطية أفواههم بمناشف رطبة',
              'safeTextEn': 'Guide children to crawl low on hands and knees covering mouth with wet towels',
              'safeExpAr': 'حماية ممتازة؛ غازات البلاستيك المحترق سريعة السمية وحبو الأطفال يحميهم.',
              'safeExpEn': 'Superb protection; burning PVC fumes are highly toxic; low crawling shields lungs.',
              'safeOutAr': 'أمّنت خروج الأطفال للمحطة 4.',
              'safeOutEn': 'Guided kids out safely for Station 4.',
              'unsafeTextAr': 'جعل الأطفال يركضون وهم مرفوعي الرأس ويصرخون',
              'unsafeTextEn': 'Have kids run fully upright screaming loudly',
              'unsafeExpAr': 'خطأ؛ الصراخ يزيد استنشاق غاز الهيدروجين كلورايد السام.',
              'unsafeExpEn': 'Error; screaming increases deep inhalation of toxic PVC gases.',
              'unsafeOutAr': 'استنشق الأطفال غازات سامة.',
              'unsafeOutEn': 'Children inhaled toxic plastic smoke.',
            },
            {
              'sitAr': 'التوجه لباب الشقة الرئيسي. ماذا تفعل قبل فتح الباب للخارج؟',
              'sitEn': 'Reaching front exit door. What to test before opening door knob?',
              'hintAr': 'لمس ظهر المقبض أو الباب بظهر اليد للتأكد من عدم وجود نار بالخارج',
              'hintEn': 'Touch door knob with back of hand to feel for trapped hallway heat',
              'safeTextAr': 'فحص حرارة الباب والمقبض بظهر اليد قبل فتح الباب',
              'safeTextEn': 'Check door and knob temperature with back of hand before opening',
              'safeExpAr': 'اختبار أمني ذكي؛ فحص الحرارة يمنع اندفاع ألسنة اللهب المفاجئة (Backdraft).',
              'safeExpEn': 'Smart check; testing door heat prevents sudden backdraft explosion.',
              'safeOutAr': 'تأكدت من أمان المخرج للمحطة 5.',
              'safeOutEn': 'Verified exit safety for Station 5.',
              'unsafeTextAr': 'فتح الباب بقوة ودفعة سريعة دون فحص حرارته',
              'unsafeTextEn': 'Fling door open abruptly without checking temperature',
              'unsafeExpAr': 'خطأ؛ الفتح المفاجئ قد يزود الحريق الخارجي بدفعة أكسجين مفجرة.',
              'unsafeExpEn': 'Error; sudden door opening feeds external fire causing explosive flashover.',
              'unsafeOutAr': 'اندفعت النار للداخل.',
              'unsafeOutEn': 'Flashover flames surged inward.',
            },
            {
              'sitAr': 'التجمع الخارجي وإبلاغ طوارئ الكهرباء (933) والدفاع المدني (998).',
              'sitEn': 'Outside reporting to SEC Emergency 933 & Civil Defense 998.',
              'hintAr': 'الإبلاغ عن حريق اللوحة الكهربائية لقطع التيار الخارجي من المحول الرئيسي',
              'hintEn': 'Report electrical panel fire to isolate transformer power feed outside building',
              'safeTextAr': 'البلاغ عن ماس القاطع الرئيسي لشركة الكهرباء (933) والدفاع المدني (998)',
              'safeTextEn': 'Call SEC 933 and Civil Defense 998 to isolate neighborhood transformer feed',
              'safeExpAr': 'إتمام ممتاز؛ قطع التيار من المحول الحيوي يؤمن المبنى بالكامل.',
              'safeExpEn': 'Complete action; transformer grid isolation ensures total building safety.',
              'safeOutAr': 'أكملت محطات ماس القاطع الرئيسي بنجاح!',
              'safeOutEn': 'Successfully completed breaker fire scenario!',
              'unsafeTextAr': 'مغادرة المكان دون إبلاغ شركة الكهرباء بالحادث',
              'unsafeTextEn': 'Leave scene without informing SEC emergency teams',
              'unsafeExpAr': 'خطأ؛ استمرار التيار الخارجي قد يجدد اشتعال الكابلات بالشارع.',
              'unsafeExpEn': 'Error; ongoing grid power can reignite external street cables.',
              'unsafeOutAr': 'استمر الخطر بالشبكة الخارجية.',
              'unsafeOutEn': 'Grid short circuit hazard persisted.',
            },
          ],
        ),

        // 4. Fire Scenario 4
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_4',
          categoryId: 'fire',
          titleAr: 'حريق قبو المبنى وتصاعد الدخان للممرات',
          titleEn: 'Basement Parking Fire & Smoke Spill',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انبعاثات الدخان في قبوات المباني والهروب الآمن.',
          descriptionEn: 'Interactive 5-station scenario for basement smoke buildup evacuation.',
          difficulty: 'صعب',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'انطلقت أجهزة الإنذار وانبعث دخان أسود كثيف من فتحة المصعد والقبو. ما الحركة؟',
              'sitEn': 'Alarms sound and dense black smoke rises from basement elevator shaft. Action?',
              'hintAr': 'التوجه لدرج الطوارئ الجانبي وحظر استخدام المصاعد الكهربائية نهائياً',
              'hintEn': 'Head to side emergency exit stairwell; NEVER use elevators',
              'safeTextAr': 'التوجه لسلالم الطوارئ الجانبية وحظر ركوب المصاعد إطلاقاً',
              'safeTextEn': 'Head immediately to side fire escape stairs strictly avoiding elevators',
              'safeExpAr': 'إجراء حيوي؛ المصاعد تتوقف فجأة بالدور المشتعل أو تنقطع عنها الكهرباء.',
              'safeExpEn': 'Vital step; elevators can stall or open directly onto fire floor.',
              'safeOutAr': 'دخلت بيت الدرج للمحطة 2.',
              'safeOutEn': 'Entered fire stairwell for Station 2.',
              'unsafeTextAr': 'الضغط على زر المصعد للنزول للقبو لأخذ السيارة',
              'unsafeTextEn': 'Press elevator call button to ride down into basement to get car',
              'unsafeExpAr': 'خطأ مهلك؛ دخول القبو المشتعل يضعك في وسط فرن الغازات السامة.',
              'unsafeExpEn': 'Fatal mistake; riding into burning basement traps you in toxic smoke chamber.',
              'unsafeOutAr': 'احتجزت بالمصعد بالدور السفلي.',
              'unsafeOutEn': 'Stalled in basement elevator.',
            },
            {
              'sitAr': 'دخول الدخان لبيت الدرج الرئيسي. كيف تعبر المسار بأمان؟',
              'sitEn': 'Smoke seeping into main stairwell. How to navigate descent?',
              'hintAr': 'إغلاق الأبواب المضادة للحريق خلفك والنزول بمحاذاة جدار الدرج',
              'hintEn': 'Close fire doors behind you and descend hugging stairwell wall',
              'safeTextAr': 'إغلاق باب الدرج خلفك والنزول بمحاذاة جدار السلم مع خفض الرأس',
              'safeTextEn': 'Close fire door behind and descend while hugging wall with head lowered',
              'safeExpAr': 'تصرف ممتاز؛ إغلاق الباب يمنع تدفق الدخان الساخن لسلالم النجاة.',
              'safeExpEn': 'Excellent move; self-closing fire doors seal smoke out of stairwell.',
              'safeOutAr': 'نزلت بأمان للدور الأرضي للمحطة 3.',
              'safeOutEn': 'Reached ground floor safely for Station 3.',
              'unsafeTextAr': 'ترك باب الدرج مفتوحاً والركض لزيادة السرعة',
              'unsafeTextEn': 'Propping fire door open running fast downstairs',
              'unsafeExpAr': 'خطأ؛ ترك الباب مفتوحاً يحول بيت الدرج لمدخنة نارية.',
              'unsafeExpEn': 'Error; propping doors open turns stairwell into a chimney for fire.',
              'unsafeOutAr': 'امتلأ بيت الدرج بالدخان.',
              'unsafeOutEn': 'Stairwell filled with chimney smoke.',
            },
            {
              'sitAr': 'تعثر أحد الجيران في بيت الدرج المظلم. كيف تساعده؟',
              'sitEn': 'Neighbor trips in dark filled stairwell. How to aid them?',
              'hintAr': 'مساعدته على النهوض فوراً وتوجيه كشاف الجوال نحو عتبات الدرج',
              'hintEn': 'Help them up immediately pointing mobile flashlight onto stair steps',
              'safeTextAr': 'إسناد الجار وتوجيه إضاءة الجوال نحو عتبات الدرج لتفادي السقوط',
              'safeTextEn': 'Support neighbor and light stair treads using mobile phone torch',
              'safeExpAr': 'إغاثة رائدة؛ الإضاءة تمنع التعثر والتدافع لجميع النازلين بالدرج.',
              'safeExpEn': 'Great aid; lighting steps prevents mass tripping and injuries in darkness.',
              'safeOutAr': 'أنقذت الجار وتوجهتما للمحطة 4.',
              'safeOutEn': 'Aided neighbor safely for Station 4.',
              'unsafeTextAr': 'تجاوزه والقفز فوقه للوصول للمخرج أسرع',
              'unsafeTextEn': 'Leap over fallen neighbor to reach exit first',
              'unsafeExpAr': 'خطأ؛ القفز في الظلام يسبب سقوطك وسقوط آخرين.',
              'unsafeExpEn': 'Error; leaping in dark stairs causes secondary falls and severe injuries.',
              'unsafeOutAr': 'تعثرت وسقطت على الدرج.',
              'unsafeOutEn': 'Fell down dark staircase.',
            },
            {
              'sitAr': 'الوصول لبوابة المبنى الرئيسية. كيف تتأكد من خروج الجميع؟',
              'sitEn': 'Reaching main building lobby exit. How to verify headcount?',
              'hintAr': 'التوجه لنقطة التجمع الخارجية وإبلاغ مشرف السلامة بأسماء السكّان',
              'hintEn': 'Proceed to outdoor assembly point and inform safety officer of occupants',
              'safeTextAr': 'التوجه المباشر لنقطة التجمع الخارجية ومراجعة القائمة مع حارس المبنى',
              'safeTextEn': 'Proceed directly to assembly point auditing list with building warden',
              'safeExpAr': 'تنسيق محترف؛ حصر الغائبين يوجه رجال الدفاع المدني لأماكن الاحتجاز فوراً.',
              'safeExpEn': 'Pro coordination; clear headcount directs firefighters straight to trapped units.',
              'safeOutAr': 'حصّرت الأسماء وتوجهت للمحطة 5.',
              'safeOutEn': 'Completed headcount for Station 5.',
              'unsafeTextAr': 'الوقوف أمام بوابة المبنى وتعطيل حركة رجال الإطفاء',
              'unsafeTextEn': 'Block main entrance lobby taking photo videos',
              'unsafeExpAr': 'خطأ؛ التجمهر أمام البوابة يعيق دخول فرق الإنقاذ بحقائب الإكسجين.',
              'unsafeExpEn': 'Error; crowding entrance obstructs firefighters carrying heavy oxygen gear.',
              'unsafeOutAr': 'أعقت دخول فرق الإنقاذ.',
              'unsafeOutEn': 'Obstructed firefighter access.',
            },
            {
              'sitAr': 'وصول فرق الدفاع المدني (998). كيف تقدم البلاغ الميداني؟',
              'sitEn': 'Civil Defense fire chief arrives (998). Field brief details?',
              'hintAr': 'إبلاغ الضابط بمكان الحريق بالقبو وجود سيارات غاز ومواقع الشقق المحتجزة',
              'hintEn': 'Inform captain of basement fire location, LPG vehicles, and trapped units',
              'safeTextAr': 'إبلاغ القائد الميداني بأن الحريق بالقبو وموقع كابلات الكهرباء ورقم الشقق المتبقية',
              'safeTextEn': 'Brief field officer on basement source, power line shafts, and trapped apartment numbers',
              'safeExpAr': 'بلاغ ميداني ذهبي؛ يوفر وقتاً ثميناً لفرق الاقتحام والإنقاذ.',
              'safeExpEn': 'Golden field report; saves critical minutes for search and rescue assault teams.',
              'safeOutAr': 'أكملت محطات حريق الققب والإخلاء بنجاح!',
              'safeOutEn': 'Successfully completed basement fire scenario!',
              'unsafeTextAr': 'مغادرة الموقع دون إعطاء أي معلومات لقائد الفرق',
              'unsafeTextEn': 'Leave scene without speaking to arriving rescue commander',
              'unsafeExpAr': 'خطأ؛ عدم الإبلاغ قد يجعل الفرق تبحث في الأدوار الخاطئة.',
              'unsafeExpEn': 'Error; failing to report leaves firefighters searching wrong floors.',
              'unsafeOutAr': 'تأخرت عمليات الاقتحام.',
              'unsafeOutEn': 'Rescue operation delayed.',
            },
          ],
        ),

        // 5. Fire Scenario 5
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_5',
          categoryId: 'fire',
          titleAr: 'اشتعال ملابس أثناء الطهي بالمطبخ',
          titleEn: 'Clothing Fire Incident in Kitchen',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع اشتعال الملابس وتطبيق قاعدة "توقف، اسقط، ودحرج".',
          descriptionEn: 'Interactive 5-station scenario for clothing fires: Stop, Drop & Roll.',
          difficulty: 'سهل',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'لامس أكمام الثوب أو العباءة نار موقد الغاز واشتعلت حافة الملابس. ما أول حركة؟',
              'sitEn': 'Sleeve catches flame from gas burner. Immediate response?',
              'hintAr': 'التوقف فوراً وعدم الجري؛ تطبيق قاعدة Stop, Drop & Roll',
              'hintEn': 'STOP immediately; do NOT run! Apply Stop, Drop & Roll',
              'safeTextAr': 'التوقف الفوري عن الحركة وتجنب الجري إطلاقاً',
              'safeTextEn': 'STOP moving immediately and strictly refrain from running',
              'safeExpAr': 'استجابة ذهبية؛ الجري يزيد تيار الأكسجين ويعمل كمروحة تشعل الثوب كلياً.',
              'safeExpEn': 'Golden response; running feeds oxygen to fabric burning whole garment rapidly.',
              'safeOutAr': 'توقفت عن الجري للمحطة 2.',
              'safeOutEn': 'Stopped running for Station 2.',
              'unsafeTextAr': 'الركض والهروله نحو الصالة المفتوحة لطلب النجدة',
              'unsafeTextEn': 'Run fast toward living room screaming for help',
              'unsafeExpAr': 'خطأ قاتل؛ الجري يجعل ألسنة اللهب تلتف وتصل لوجه المصاب وشعره.',
              'unsafeExpEn': 'Fatal mistake; running fans flames upward wrapping around face and hair.',
              'unsafeOutAr': 'امتدت النار لأعلى الثوب.',
              'unsafeOutEn': 'Flames enveloped upper body.',
            },
            {
              'sitAr': 'ما الخطوة الثانية لإخماد نار الملابس على الجسد؟',
              'sitEn': 'Second step to extinguish burning clothes on body?',
              'hintAr': 'السقوط على الأرض وتغطية الوجه بالكفين لحماية العينين والجهاز التنفسي',
              'hintEn': 'DROP to ground covering face with hands to protect eyes and airway',
              'safeTextAr': 'السقوط فوراً على الأرض وتغطية الوجه بالكفين لحماية العينين',
              'safeTextEn': 'DROP to ground covering face with hands to shield eyes and lungs',
              'safeExpAr': 'تصرف ممتاز؛ السقوط يمنع صعود ألسنة اللهب باتجاه الوجه والقصبة الهوائية.',
              'safeExpEn': 'Excellent move; dropping prevents flames from ascending into facial airway.',
              'safeOutAr': 'سقطت أرضاً وحميت الوجه للمحطة 3.',
              'safeOutEn': 'Dropped low protecting face for Station 3.',
              'unsafeTextAr': 'البقاء واقفاً وحك القماش باليدين العاريتين',
              'unsafeTextEn': 'Stand upright beating flames with bare hands',
              'unsafeExpAr': 'خطأ؛ الضرب باليدين يحرق الكفين ولا يخمد النار.',
              'unsafeExpEn': 'Error; slapping with hands causes hand burns without smothering fire.',
              'unsafeOutAr': 'تعرضت الكفوف للحرق.',
              'unsafeOutEn': 'Burned palms on fire.',
            },
            {
              'sitAr': 'كيف تقوم بكتم الأكسجين عن الملابس المشتعلة على الأرض؟',
              'sitEn': 'How to smother oxygen from burning clothes while on ground?',
              'hintAr': 'الدحرج والتمرغ ذهاباً وإيابا على الأرض حتى انطفاء النار كلياً (ROLL)',
              'hintEn': 'ROLL back and forth over ground until flames are fully smothered',
              'safeTextAr': 'التمرغ والدحرجة ذهاباً وإياداً على السجاد أو الأرض حتى انطفاء اللهب',
              'safeTextEn': 'ROLL back and forth continuously pressing fire against floor until out',
              'safeExpAr': 'إخماد تام؛ الدحرجة تضغط القماش المشتعل بالأرض وتخنق اللهب كلياً.',
              'safeExpEn': 'Complete extinguishing; rolling presses burning cloth to floor cutting oxygen.',
              'safeOutAr': 'أخمدت النار بالدحرجة للمحطة 4.',
              'safeOutEn': 'Extinguished clothing fire for Station 4.',
              'unsafeTextAr': 'الاستلقاء ساكناً دون دحرجة',
              'unsafeTextEn': 'Lie completely motionlessly without rolling',
              'unsafeExpAr': 'خطأ؛ السكون دون دحرجة يترك الأجزاء العلوية مشتعلة.',
              'unsafeExpEn': 'Error; lying still leaves exposed top sides of garment burning.',
              'unsafeOutAr': 'استمر القماش بالاشتعال.',
              'unsafeOutEn': 'Fabric continued burning.',
            },
            {
              'sitAr': 'انطفأت النار بالكامل ولكن القماش الملتصق بالجلد ساخن. كيف تسعفه؟',
              'sitEn': 'Fire extinguished but hot fabric sticking to skin. First aid?',
              'hintAr': 'سكب ماء فاتر/بارد خفيف وتجنب نزع القماش الملتصق بالجلد بالقوة',
              'hintEn': 'Cool with cool running water; do NOT rip off stuck fabric forcibly',
              'safeTextAr': 'سكب ماء بارد جاري لمدة 10-15 دقيقة وتجنب نزع القماش الملتصق بالجلد',
              'safeTextEn': 'Pour cool running water for 10-15 mins; NEVER pull off stuck burned fabric',
              'safeExpAr': 'إسعاف سليم؛ ماء التبريد يوقف كوي الأنسجة ونزع القماش بالقوة يسلخ الجلد.',
              'safeExpEn': 'Correct first aid; cool water stops tissue cooking; ripping fabric tears raw skin.',
              'safeOutAr': 'برّدت الحرق بأمان للمحطة 5.',
              'safeOutEn': 'Cooled burn safely for Station 5.',
              'unsafeTextAr': 'شد ونزع القماش الملتصق بالحرق بقوة وإغاطتها بالزبدة',
              'unsafeTextEn': 'Rip stuck cloth off burn forcibly and coat in butter',
              'unsafeExpAr': 'خطأ كوارثي؛ نزع القماش الملتصق يسبب نزيفاً وتهتكاً شديداً للأدمة.',
              'unsafeExpEn': 'Catastrophic error; yanking stuck fabric tears dermis causing severe bleeding.',
              'unsafeOutAr': 'تهتك الجلد وتسبب بنزيف.',
              'unsafeOutEn': 'Torn skin and severe bleeding.',
            },
            {
              'sitAr': 'نقل المصاب وتغطية الحروق. ما الخطوة النهائية؟',
              'sitEn': 'Transporting victim and dressing burn. Final protocol?',
              'hintAr': 'تغطية الحرق بشاش معقم جاف والاتصال بالهلال الأحمر (997)',
              'hintEn': 'Cover burn with clean dry sterile sheet and call Red Crescent 997',
              'safeTextAr': 'تغطية موضع الحرق بشاش معقم جاف والاتصال الفوري بـ (997 الهلال الأحمر)',
              'safeTextEn': 'Cover burn area with sterile dry sheet and call Saudi Red Crescent 997',
              'safeExpAr': 'إتمام ممتاز؛ نقل المصاب بسيارات الإسعاف يضمن المحاليل وتسكين الألم.',
              'safeExpEn': 'Complete execution; ambulance transport ensures sterile care and pain IV.',
              'safeOutAr': 'أكملت محطات إخماد حريق الملابس بنجاح!',
              'safeOutEn': 'Successfully completed clothing fire scenario!',
              'unsafeTextAr': 'وضع ثلج مباشر أو معجون أسنان فوق الحرق قبل الذهاب بسيارة خاصة',
              'unsafeTextEn': 'Apply direct ice or toothpaste then drive private car',
              'unsafeExpAr': 'خطأ؛ الثلج المباشر يسبب موت الخلايا المعالجة بالتجميد.',
              'unsafeExpEn': 'Error; direct ice causes frostbite tissue necrosis on raw burns.',
              'unsafeOutAr': 'تلف الخلايا بسبب الثلج.',
              'unsafeOutEn': 'Tissue necrosis from ice.',
            },
          ],
        ),

        // 6. Fire Scenario 6
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_6',
          categoryId: 'fire',
          titleAr: 'حريق محرك السيارة في مواقف القبو',
          titleEn: 'Car Engine Fire in Basement Parking',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع اشتعال محركات السيارات والمواقف المغلقة.',
          descriptionEn: 'Interactive 5-station scenario for car engine bay fires in garages.',
          difficulty: 'متوسط',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'تصاعد دخان وشرر من كابوت محرك السيارة بالمواقف. ما أول إجراء؟',
              'sitEn': 'Smoke and sparks billow from car hood in parking. Immediate action?',
              'hintAr': 'إيقاف المحرك، سحب السويتش، وإخراج جميع الركاب من السيارة فوراً',
              'hintEn': 'Turn off ignition key and evacuate all passengers immediately',
              'safeTextAr': 'إيقاف المحرك، سحب المفتاح، وإخلاء جميع الركاب خارج المركبة',
              'safeTextEn': 'Turn off engine ignition, remove key, and evacuate passengers instantly',
              'safeExpAr': 'إجراء ممتاز؛ إيقاف السويتش يقطع مضخة البنزين والدائرة الكهربائية.',
              'safeExpEn': 'Excellent step; switching ignition off stops electric fuel pump pressure.',
              'safeOutAr': 'قطعت الوقود والكهرباء للمحطة 2.',
              'safeOutEn': 'Stopped fuel pump for Station 2.',
              'unsafeTextAr': 'فتح الكابوت بالكامل بيديك العاريتين لمعاينة النار',
              'unsafeTextEn': 'Fling hood open completely barehanded to look at flames',
              'unsafeExpAr': 'خطأ خطير؛ فتح الكابوت يعطي النار دفعة أكسجين تتسبب في اندفاع اللهب لوجهك.',
              'unsafeExpEn': 'Dangerous error; opening hood fully supplies oxygen causing fire burst to face.',
              'unsafeOutAr': 'اندفعت النار باتجاه الوجه.',
              'unsafeOutEn': 'Flames burst into face.',
            },
            {
              'sitAr': 'أحضرت طفاية الحريق الخاصة بالسيارة. كيف تفتح غطاء المحرك بحذر؟',
              'sitEn': 'Fetched car fire extinguisher. How to crack open hood safely?',
              'hintAr': 'فتح الغطاء فتحة ضيقة جداً ورش البودرة عبر الفتحة دون رفعه كلياً',
              'hintEn': 'Pop hood latch slightly and spray powder through small gap without lifting fully',
              'safeTextAr': 'فتح القفل الداخلي للغطاء فتحة صغيرة ورش طفاية البودرة عبر الفتحة',
              'safeTextEn': 'Pop hood latch slightly open and spray powder extinguisher through the gap',
              'safeExpAr': 'تكتيك محترف؛ الرش عبر الفتحة يخنق الحريق دون إدخال تيار أكسجين خارجي.',
              'safeExpEn': 'Pro tactic; spraying through small gap smothers fire without introducing oxygen blow.',
              'safeOutAr': 'رششت البودرة داخل الكابوت للمحطة 3.',
              'safeOutEn': 'Sprayed powder into engine bay for Station 3.',
              'unsafeTextAr': 'رفع الكابوت زاوية 90 درجة بالكامل وترك الطفاية',
              'unsafeTextEn': 'Lift hood up 90 degrees fully leaving extinguisher on ground',
              'unsafeExpAr': 'خطأ؛ فتح الغطاء بالكامل يوسع الحريق ويحررق المحرك كلياً.',
              'unsafeExpEn': 'Error; full hood opening engulfs engine bay in uncontrollable flames.',
              'unsafeOutAr': 'اتسع حريق المحرك.',
              'unsafeOutEn': 'Engine bay fully engulfed.',
            },
            {
              'sitAr': 'تصاعد الدخان بالمواقف المغلقة بالقبو. كيف تحمي نفسك أثناء الرش؟',
              'sitEn': 'Smoke expanding in enclosed basement garage. Position during spraying?',
              'hintAr': 'الوقوف مع اتجاه الريح/التهوية والرش من مسافة 2-3 أمتار',
              'hintEn': 'Stand upwind from draft spraying from 2-3 meters safe distance',
              'safeTextAr': 'الوقوف في اتجاه تيار الهواء النقي والرش على بعد 2-3 أمتار من المحرك',
              'safeTextEn': 'Position yourself upwind spraying from safe 2-3 meter distance',
              'safeExpAr': 'موقع آمن؛ الوقوف عكس التيار يمنع ارتداد البودرة والدخان على عينيك.',
              'safeExpEn': 'Safe position; upwind stance prevents powder blowing back into eyes.',
              'safeOutAr': 'رششت بأمان للمحطة 4.',
              'safeOutEn': 'Sprayed safely for Station 4.',
              'unsafeTextAr': 'الوقوف ملاصقاً للمحرك واستنشاق غازات البنزين',
              'unsafeTextEn': 'Stand right up against engine inhaling gasoline fumes',
              'unsafeExpAr': 'خطأ؛ القرب الشديد يعرضك لانفجار خرطوم البنزين المضغوط.',
              'unsafeExpEn': 'Error; standing too close risks face burns from rupturing fuel lines.',
              'unsafeOutAr': 'تعرضت لأبخرة البنزين.',
              'unsafeOutEn': 'Inhaled burning petrol fumes.',
            },
            {
              'sitAr': 'إذا استمر حريق المحرك ولم تتوقف النار. ما قرارك السريع؟',
              'sitEn': 'If engine fire persists despite extinguisher. Immediate decision?',
              'hintAr': 'التراجع الفوري، إخلاء القبو، وتفعيل زر إنذار الحريق بالمرآب',
              'hintEn': 'Retreat immediately, evacuate basement, pull wall fire alarm',
              'safeTextAr': 'الانسحاب الفوري، سحب مقبض إنذار الحريق بالجدار، والصعود خارج القبو',
              'safeTextEn': 'Retreat immediately, pull wall fire manual call point, evacuate upstairs',
              'safeExpAr': 'حكمة عالية؛ سلامة الأرواح أولاً عند تعذر إخماد حريق الوقود.',
              'safeExpEn': 'Wise decision; life safety overrides property when fuel fires expand.',
              'safeOutAr': 'فعّلت الإنذار وخرجت للمحطة 5.',
              'safeOutEn': 'Pulled alarm and evacuated for Station 5.',
              'unsafeTextAr': 'البقاء بالقبو وتفريغ طفايات متعددة دون نفع',
              'unsafeTextEn': 'Stay in basement inhaling smoke trying multiple empty canisters',
              'unsafeExpAr': 'خطأ؛ البقاء في القبو المظلم يسبب الاختناق واحتجازك وسط السيارات.',
              'unsafeExpEn': 'Error; remaining in basement leads to rapid asphyxiation.',
              'unsafeOutAr': 'تعرضت للاختناق بالقبو.',
              'unsafeOutEn': 'Trapped in smoke filled basement.',
            },
            {
              'sitAr': 'وصول الدفاع المدني (998). كيف توجه فرق الإطفاء لقبو السيارات؟',
              'sitEn': 'Civil Defense arrive (998). How to direct fire crew to basement car?',
              'hintAr': 'تحديد موقع السيارة الدقيق بالقبو ووجود خزانات بنزين ممتلئة',
              'hintEn': 'Inform crew of exact basement pillar location and fuel tanks nearby',
              'safeTextAr': 'إبلاغ فرقة الإطفاء بموقع السيارة عند العمود المحدد بالقبو وبداية انتشاره',
              'safeTextEn': 'Direct crew to exact pillar code in basement and nearby fuel hazards',
              'safeExpAr': 'بلاغ موجه؛ يتيح لرجال الإطفاء دخول القبو بخراطيم الضغط العالي مباشرة.',
              'safeExpEn': 'Targeted dispatch; allows firefighters to enter with high-pressure hoses.',
              'safeOutAr': 'أكملت محطات حريق محرك السيارة بنجاح!',
              'safeOutEn': 'Successfully completed car fire scenario!',
              'unsafeTextAr': 'مغادرة المواقف دون انتظار فرق الإطفاء',
              'unsafeTextEn': 'Walk away from garage without waiting for fire engines',
              'unsafeExpAr': 'خطأ؛ غياب التوجيه يطيل بحث الفرقة عن مصدر الدخان.',
              'unsafeExpEn': 'Error; lack of direction wastes time finding fire origin.',
              'unsafeOutAr': 'تأخر إطفاء السيارة.',
              'unsafeOutEn': 'Extinguishment delayed.',
            },
          ],
        ),

        // 7. Fire Scenario 7
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_7',
          categoryId: 'fire',
          titleAr: 'حريق مكيف السبلت بالغرفة',
          titleEn: 'Split AC Unit Fire in Living Room',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع اشتعال مكيفات الهواء والماس الكهربائي الداخلي.',
          descriptionEn: 'Interactive 5-station scenario for split AC unit fires.',
          difficulty: 'سهل',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'صدور صوت طقطقة وتساقط بلاستيك مشتعل من مكيف السبلت. ما أول حركة؟',
              'sitEn': 'Crackling sound and flaming plastic dripping from split AC. Immediate step?',
              'hintAr': 'فصل مفتاح التكييف الجداري (Circuit Switch) فوراً لقطع التيار',
              'hintEn': 'Shut off AC wall safety switch immediately to isolate electric current',
              'safeTextAr': 'فصل قاطع التكييف الجداري أو القاطع الرئيسي فوراً لقطع التغذية',
              'safeTextEn': 'Flip AC wall isolator switch or main breaker off immediately',
              'safeExpAr': 'تصرف ممتاز؛ قطع الكهرباء يوقف انصهار الملفات الداخلية للمكيف.',
              'safeExpEn': 'Excellent action; isolating power stops internal coils from melting further.',
              'safeOutAr': 'قطعت الكهرباء عن المكيف للمحطة 2.',
              'safeOutEn': 'Isolated AC power for Station 2.',
              'unsafeTextAr': 'سكب كاس ماء فوق المكيف من الأسفل',
              'unsafeTextEn': 'Throw water upward into dripping AC unit',
              'unsafeExpAr': 'خطأ؛ رش الماء على جهاز كهربائي متصل بالكهرباء يسبب الصعق.',
              'unsafeExpEn': 'Error; throwing water onto live electrical apparatus causes fatal shock.',
              'unsafeOutAr': 'تعرضت للصعق بالماء.',
              'unsafeOutEn': 'Electric shock from water stream.',
            },
            {
              'sitAr': 'تساقط قطر بلاستيك مشتعل على الستائر والسجاد. كيف تمنع انتشار الحريق؟',
              'sitEn': 'Burning plastic drops onto curtains and carpet. How to prevent spread?',
              'hintAr': 'إبعاد الستائر والأثاث وتغطية الجمر بطفاية بودرة أو بطانية رطبة',
              'hintEn': 'Move furniture away and smother embers with fire blanket or CO2',
              'safeTextAr': 'سحب الأثاث والستائر بعيداً وتغطية نقطة التساقط ببطانية حريق',
              'safeTextEn': 'Pull curtains/furniture away and smother falling hot plastic with fire blanket',
              'safeExpAr': 'حكمة عالية؛ إبعاد المواد القابلة للاشتعال يمنع تكون حريق شامل (Flashover).',
              'safeExpEn': 'Wise tactic; clearing combustibles prevents room flashover.',
              'safeOutAr': 'عزلت المفروشات للمحطة 3.',
              'safeOutEn': 'Isolated combustibles for Station 3.',
              'unsafeTextAr': 'ترك الستائر مكانها ومحاولة إطفاء المكيف بقطعة قماش جافة',
              'unsafeTextEn': 'Leave curtains in place trying to hit AC with dry towel',
              'unsafeExpAr': 'خطأ؛ ضرب المكيف بقماش جاف ينشر الجمر على السجاد.',
              'unsafeExpEn': 'Error; swatting hot plastic with dry towels spreads embers across room.',
              'unsafeOutAr': 'اشتعلت الستائر والسجاد.',
              'unsafeOutEn': 'Curtains caught fire.',
            },
            {
              'sitAr': 'استخدام طفاية ثاني أكسيد الكربون (CO2) لإخماد المكيف. كيف توجه القذف؟',
              'sitEn': 'Using CO2 extinguisher on AC unit. How to direct discharge?',
              'hintAr': 'الإمساك بالمقبض المخصص (لتجنب حروق الصقيع) والرش باتجاه فتحات المكيف',
              'hintEn': 'Hold nozzle handle to prevent freeze burns and spray into AC louvers',
              'safeTextAr': 'الإمساك بالمقبض العازل ورش غاز CO2 نحو فتحات تهوية المكيف',
              'safeTextEn': 'Hold insulated nozzle grip and discharge CO2 gas into AC air louvers',
              'safeExpAr': 'إجراء صحيح؛ غاز CO2 يتدفق داخل المكيف دون إتلاف المكونات الإكترونية.',
              'safeExpEn': 'Correct step; CO2 displaces oxygen inside AC casing without damaging circuits.',
              'safeOutAr': 'أخمدت حريق المكيف للمحطة 4.',
              'safeOutEn': 'Smothered AC fire for Station 4.',
              'unsafeTextAr': 'الإمساك بأنبوب CO2 المعدني بيدك العارية أثناء الرش',
              'unsafeTextEn': 'Grasp bare metal horn of CO2 canister barehanded while spraying',
              'unsafeExpAr': 'خطأ؛ أنبوب CO2 يصبح شديد البرودة ويسبب حروق صقيع باليد (Frostbite).',
              'unsafeExpEn': 'Error; CO2 horn drops to sub-zero temperatures causing severe skin frostbite.',
              'unsafeOutAr': 'تعرضت يدك لحرق صقيع.',
              'unsafeOutEn': 'Suffered frostbite on hand.',
            },
            {
              'sitAr': 'انتشار رائحة العازل المحترق والغرفة ممتلئة بالغازات. كيف تهوي المكان؟',
              'sitEn': 'AC insulation smell remains with trapped smoke. How to ventilate?',
              'hintAr': 'فتح النوافذ الشارعية الخارجية فقط مع إغلاق الأبواب الداخلية للشقة',
              'hintEn': 'Open exterior windows only while keeping internal room door shut',
              'safeTextAr': 'فتح النوافذ الخارجية للغرفة مع إغلاق الباب الداخلي لمنع تسرب الرائحة للشقة',
              'safeTextEn': 'Open exterior room windows while keeping interior door shut to contain odor',
              'safeExpAr': 'تهوية ذكية؛ تضمن طرد الدخان للخارج دون تلويث بقية الغرف.',
              'safeExpEn': 'Smart ventilation; expels fumes outside without contaminating rest of home.',
              'safeOutAr': 'هويت الغرفة للمحطة 5.',
              'safeOutEn': 'Ventilated room for Station 5.',
              'unsafeTextAr': 'فتح جميع أبواب الشقة الداخلية وتوفير تيار هوائي صاعد',
              'unsafeTextEn': 'Open all apartment interior doors pushing smoke to bedrooms',
              'unsafeExpAr': 'خطأ؛ فتح الأبواب الداخلية ينشر غاز الفريون المحترق بجميع الشقة.',
              'unsafeExpEn': 'Error; opening interior doors spreads burnt freon gas into all living areas.',
              'unsafeOutAr': 'انتشرت الغازات بكافة الشقة.',
              'unsafeOutEn': 'Burnt freon gas spread across home.',
            },
            {
              'sitAr': 'فحص المكيف واستدعاء فني التكييف المعتمَد. ما الخطوة النهائية؟',
              'sitEn': 'Inspecting unit and calling HVAC certified technician. Final step?',
              'hintAr': 'إبقاء القاطع الكهربائي مفصولاً واستبدال التوصيلات التالفة',
              'hintEn': 'Keep breaker off until certified technician replaces melted wires',
              'safeTextAr': 'إبقاء القاطع مفصولاً واستدعاء فني تكييف معتمد لإصلاح الظفيرة الكهربائية',
              'safeTextEn': 'Keep breaker locked off and call certified HVAC technician to repair wiring',
              'safeExpAr': 'إتمام ممتاز؛ الفحص الفني يمنع تكرار الماس الكهربائي عند التشغيل.',
              'safeExpEn': 'Complete execution; professional overhaul prevents re-ignition upon power turn-on.',
              'safeOutAr': 'أكملت محطات حريق مكيف السبلت بنجاح!',
              'safeOutEn': 'Successfully completed AC fire scenario!',
              'unsafeTextAr': 'إعادة رفع القاطع وتشغيل المكيف مجدداً فوراً',
              'unsafeTextEn': 'Flip breaker back on and restart AC immediately',
              'unsafeExpAr': 'خطأ؛ إعادة تشغيل المكيف التالف تسبب حريقاً أكبر بالأسلاك الداخلية.',
              'unsafeExpEn': 'Error; restarting damaged AC causes severe short circuit and immediate fire.',
              'unsafeOutAr': 'تجدد الماس بالمكيف.',
              'unsafeOutEn': 'AC short-circuited again.',
            },
          ],
        ),

        // 8. Fire Scenario 8
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_8',
          categoryId: 'fire',
          titleAr: 'حريق دفاية الزيت والكهرباء بالشتاء',
          titleEn: 'Electric Space Heater Winter Fire',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع مخاطر وأخطاء وسائل التدفئة الكهربائية.',
          descriptionEn: 'Interactive 5-station scenario for electric heater winter fires.',
          difficulty: 'متوسط',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'انقلبت الدفاية الكهربائية على السجاد واشتعلت حافة المفروشات. ما الإجراء الأولي؟',
              'sitEn': 'Electric heater tipped over onto rug igniting carpet edge. First action?',
              'hintAr': 'سحب فيش الدفاية فوراً وعدم الإمساك بجسم الدفاية الساخن',
              'hintEn': 'Unplug heater plug instantly; do NOT touch scorching metal grid barehanded',
              'safeTextAr': 'سحب الفيش الكهربائي فوراً من المقبس وتجنب لمس شبك الدفاية الساخن',
              'safeTextEn': 'Unplug heater from wall immediately avoiding hot metal element grid',
              'safeExpAr': 'تصرف ممتاز؛ قطع الكهرباء يوقف انبعاث الحرارة العالية فوراً.',
              'safeExpEn': 'Excellent step; unplugging halts continuous radiant heat generation.',
              'safeOutAr': 'فصلت فيش الدفاية للمحطة 2.',
              'safeOutEn': 'Unplugged space heater for Station 2.',
              'unsafeTextAr': 'رفع الدفاية بيديك العاريتين ومحاولة تعديلها وهي موصولة بالكهرباء',
              'unsafeTextEn': 'Grab hot tipped heater barehanded trying to stand it up while plugged in',
              'unsafeExpAr': 'خطأ؛ شبك الدفاية المشتعل يسبب حروقاً عميقة باليدين.',
              'unsafeExpEn': 'Error; glowing heater grill causes severe third-degree hand burns.',
              'unsafeOutAr': 'تعرضت يدك للحرق.',
              'unsafeOutEn': 'Severe hand burns on hot grill.',
            },
            {
              'sitAr': 'بداية اشتعال بسجاد الغرفة الصوفي. كيف تخمد النار المتكونة؟',
              'sitEn': 'Wool rug starting to burn and smoke. How to extinguish rug fire?',
              'hintAr': 'استخدام طفاية البودرة الجافة أو بطانية حريق لخنق النار بالكامل',
              'hintEn': 'Use dry powder extinguisher or fire blanket to smother carpet fire',
              'safeTextAr': 'استخدام طفاية البودرة الجافة أو تغطية السجاد ببطانية حريق ثقيلة',
              'safeTextEn': 'Use dry powder fire extinguisher or cover burning rug with heavy fire blanket',
              'safeExpAr': 'إجراء صحيح؛ خنق السجاد المشتعل يوقف تمدد الجمر للأثاث.',
              'safeExpEn': 'Correct step; smothering carpet embers stops spread to lounge sofas.',
              'safeOutAr': 'أخمدت حريق السجاد للمحطة 3.',
              'safeOutEn': 'Smothered rug fire for Station 3.',
              'unsafeTextAr': 'سكب البنزين أو الكحول للمساعدة على تنظيف السجاد',
              'unsafeTextEn': 'Pour cleaning alcohol over rug to dissolve melted plastic',
              'unsafeExpAr': 'خطأ كارثي؛ الكحول مادة سريعة الاشتعال تسبب انفجاراً نارياً.',
              'unsafeExpEn': 'Catastrophic error; rubbing alcohol is flammable liquid causing fireball explosion.',
              'unsafeOutAr': 'حدث انفجار ناري.',
              'unsafeOutEn': 'Alcohol fireball explosion.',
            },
            {
              'sitAr': 'تأثر التوصيلة الكهربائية التي كانت تزود الدفاية بالكهرباء. كيف تؤمنها؟',
              'sitEn': 'Extension cord used for heater melted and blackened. How to secure?',
              'hintAr': 'عدم استخدام التوصيل الإضافية نهائياً للدفيات وحظر ربط دفاية بتوصيلة ضعيفة',
              'hintEn': 'Never use light extension cords for space heaters; plug directly to wall',
              'safeTextAr': 'فصل التوصيلة الذائبة والتخلص منها نهائياً مع التعهد بالوصل المباشر بالجدار',
              'safeTextEn': 'Discard melted extension cord completely and vow to plug heaters directly to wall',
              'safeExpAr': 'توعية وقائية؛ الدفايات تستهلك أحمالاً عالية تفوق طاقة التوصيلات العادية (2000W+).',
              'safeExpEn': 'Prevention rule; space heaters draw high wattage (2000W+) melting extension cords.',
              'safeOutAr': 'تخلصت من التوصيلة التالفة للمحطة 4.',
              'safeOutEn': 'Discarded damaged cord for Station 4.',
              'unsafeTextAr': 'لف شريط لاصق فوق السلك الذائب وإعادة استخدامه',
              'unsafeTextEn': 'Wrap electrical tape over melted cord and reuse it',
              'unsafeExpAr': 'خطأ؛ الشريط اللاصق لا يتحمل حرارة الأحمال العالية وسيذوب مجدداً.',
              'unsafeExpEn': 'Error; vinyl tape melts under high current loads causing secondary fires.',
              'unsafeOutAr': 'ذابت التوصيلة مجدداً.',
              'unsafeOutEn': 'Extension cord melted again.',
            },
            {
              'sitAr': 'وجود أطفال في الصالة أثناء حادث الدفاية. ما نصيحة السلامة للأطفال؟',
              'sitEn': 'Children present in room during heater fire. Safe distance rule?',
              'hintAr': 'إبعاد الأطفال مسافة 1 متر على الأقل عن أي وسيلة تدفئة',
              'hintEn': 'Enforce 1-meter 3-foot safe zone around space heaters for children',
              'safeTextAr': 'تخصيص منطقة أمان لا تقل عن متر واحد حول الدفايات ومنع الأطفال من الاقتراب',
              'safeTextEn': 'Enforce a minimum 1-meter (3ft) safe perimeter zone around heaters for kids',
              'safeExpAr': 'قاعدة سلامة عالمية؛ تمنع انسكاب أو انقلاب الدفايات وتجنب حروق التلامس.',
              'safeExpEn': 'Global safety rule; prevents accidental tipping and child contact burns.',
              'safeOutAr': 'أمّنت منطقة الأطفال للمحطة 5.',
              'safeOutEn': 'Secured safe zone for Station 5.',
              'unsafeTextAr': 'وضع الدفاية ملاصقة تماماً لسرير الطفل لتدفئته بسرعة',
              'unsafeTextEn': 'Place electric heater right against child bed for fast warmth',
              'unsafeExpAr': 'خطأ؛ ملاصقة الدفاية للمفارش والأسرة سبب رئيسي لحرائق المنازل بالشتاء.',
              'unsafeExpEn': 'Error; placing heaters close to bed sheets is a leading cause of winter fires.',
              'unsafeOutAr': 'عرضت السرير لخطر الاشتعال.',
              'unsafeOutEn': 'Exposed bed sheets to ignition.',
            },
            {
              'sitAr': 'تأمين الغرفة بالكامل ومراجعة كواشف الحريق. ما الخطوة النهائية؟',
              'sitEn': 'Securing room completely and auditing smoke detectors. Final step?',
              'hintAr': 'فحص وتجربة زر كاشف الدخان بالمنزل وتغيير بطاريته',
              'hintEn': 'Test home smoke detector alarm button and replace battery annually',
              'safeTextAr': 'فحص كاشف الدخان بالصالة واختبار جاهزيته والتأكد من انطفاء جميع الجمرات',
              'safeTextEn': 'Test living room smoke detector button and verify all carpet embers are cold',
              'safeExpAr': 'إتمام كامل؛ كواشف الدخان تضمن التنبيه المبكر وتمنع حرائق النوم الصامتة.',
              'safeExpEn': 'Complete resolution; working smoke alarms prevent silent sleeping fire tragedies.',
              'safeOutAr': 'أكملت محطات حريق الدفاية بنجاح!',
              'safeOutEn': 'Successfully completed heater fire scenario!',
              'unsafeTextAr': 'إعادة تشغيل الدفاية التالفة قبل فحص الأسلاك',
              'unsafeTextEn': 'Restart damaged heater without inspecting wiring',
              'unsafeExpAr': 'خطأ؛ تشغيل الدفاية المتضررة يسبب حريقاً أكبر.',
              'unsafeExpEn': 'Error; running damaged space heater triggers catastrophic electrical fires.',
              'unsafeOutAr': 'تجدد حريق الدفاية.',
              'unsafeOutEn': 'Heater fire reignited.',
            },
          ],
        ),

        // 9. Fire Scenario 9
        ScenarioBuilder.build5StationScenario(
          id: 'sc_fire_9',
          categoryId: 'fire',
          titleAr: 'اشتعال الفحم والبخور بمفروشات المجلس',
          titleEn: 'Charcoal & Incense Burner Council Fire',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع سقوط المبخرة واشتعال الجمر بالمجالس.',
          descriptionEn: 'Interactive 5-station scenario for charcoal and incense burner fires.',
          difficulty: 'سهل',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          stations: [
            {
              'sitAr': 'سقطت مبخرة الفحم المشتعلة على موكيت المجلس وتناثر الجمر. ما الحركة؟',
              'sitEn': 'Lit charcoal incense burner tips over scattering red hot coals on carpet. Action?',
              'hintAr': 'عزل الجمر فوراً باستخدام ملقط معدني وسكب القليل من الماء عليه',
              'hintEn': 'Isolate coals immediately using metal tongs and douse with water',
              'safeTextAr': 'جمع الجمر المتناثر فوراً بملقط معدني وسكب كوب ماء مباشر على كل جمرة',
              'safeTextEn': 'Gather scattered coals using metal tongs and pour water over each ember',
              'safeExpAr': 'تصرف ممتاز؛ الماء يطفئ جمر الفحم فوراً ويدمر حرارته الكامنة.',
              'safeExpEn': 'Excellent response; water instantly extinguishes coal core heat.',
              'safeOutAr': 'أخمدت الجمر المتناثر للمحطة 2.',
              'safeOutEn': 'Extinguished scattered coals for Station 2.',
              'unsafeTextAr': 'دهس الجمر المشتعل بأقدام حافية لإطفائه',
              'unsafeTextEn': 'Stomp bareheaded/barefooted directly onto burning red hot coals',
              'unsafeExpAr': 'خطأ؛ حرارة الفحم تزيد عن 400 مئوية وتسبب ذوبان الجلد وحروقاً بالغة.',
              'unsafeExpEn': 'Error; charcoal burns over 400°C causing deep severe foot skin burns.',
              'unsafeOutAr': 'تعرضت القدم للحرق.',
              'unsafeOutEn': 'Severe foot burns.',
            },
            {
              'sitAr': 'انبعث دخان ورائحة احتراق الصوف من الموكيت. كيف تؤمن الأنسجة السفلية؟',
              'sitEn': 'Burnt wool smell and smoke rising from carpet. How to treat deep fibers?',
              'hintAr': 'صُب الماء على موضع الحرق وفحص الإسفنج السفلي للتأكد من عدم وجود جمرة خفية',
              'hintEn': 'Pour water over scorched spot and lift carpet edge to check subfloor padding',
              'safeTextAr': 'سكب الماء الوفير على موضع الحرق ورفع طرف الموكيت للتأكد من عدم وجود جمر تحته',
              'safeTextEn': 'Pour ample water on scorched area and lift carpet edge to inspect padding underneath',
              'safeExpAr': 'إجراء احترافي؛ الفحم قد ينفذ لإسفنج الموكيت ويبقى يشتعل ببطء طوال الليل.',
              'safeExpEn': 'Pro move; hot embers melt into carpet underlayment smoldering silently for hours.',
              'safeOutAr': 'تأكدت من سلامة الإسفنج للمحطة 3.',
              'safeOutEn': 'Inspected subfloor padding for Station 3.',
              'unsafeTextAr': 'مسح الموكيت بقماش جاف وترك الإسفنج السفلي يشتعل',
              'unsafeTextEn': 'Wipe carpet surface with dry rag leaving underlayment smoldering',
              'unsafeExpAr': 'خطأ؛ الجمرة الخفية بالإسفنج تتوسع وتسبب حريقاً بعد عدة ساعات أثناء النوم.',
              'unsafeExpEn': 'Error; hidden smoldering padding reignites hours later during sleep.',
              'unsafeOutAr': 'توسعت الجمرة بالداخل.',
              'unsafeOutEn': 'Smoldering fire spread under carpet.',
            },
            {
              'sitAr': 'تراكم غاز أول أكسيد الكربون الخانق من الفحم بالمجلس المغلق. كيف تهوي القاعة؟',
              'sitEn': 'Toxic carbon monoxide gas accumulating in closed council room. Ventilation?',
              'hintAr': 'فتح جميع النوافذ والأبواب فوراً وتطوير تيار هوائي لطرد الغازات الشفافة السامة',
              'hintEn': 'Open all windows and doors to create cross breeze expelling odorless CO gas',
              'safeTextAr': 'فتح كافة نوافذ وأبواب المجلس لتجديد الهواء وطرد غاز أول أكسيد الكربون',
              'safeTextEn': 'Open all windows and doors to establish cross ventilation flushing out toxic CO gas',
              'safeExpAr': 'تهوية حاسمة؛ أول أكسيد الكربون غاز عديم اللون والرائحة يسبب الوفاة الصامتة.',
              'safeExpEn': 'Vital step; carbon monoxide is invisible odorless toxic gas causing silent death.',
              'safeOutAr': 'جددت هواء المجلس للمحطة 4.',
              'safeOutEn': 'Flushed out CO gas for Station 4.',
              'unsafeTextAr': 'إغلاق النوافذ وتشغيل التكييف بدون تهوية خارجية',
              'unsafeTextEn': 'Close windows and turn AC to recirculate internal air',
              'unsafeExpAr': 'خطأ؛ التكييف يعيد تدوير غاز أول أكسيد الكربون الخانق دون طرده.',
              'unsafeExpEn': 'Error; split AC recirculates toxic CO gas continuously trapped inside room.',
              'unsafeOutAr': 'تراكم الغاز السام بالمجلس.',
              'unsafeOutEn': 'CO gas accumulated dangerously.',
            },
            {
              'sitAr': 'اختيار المبخرة الآمنة لمنع تكرار الحادث. ما معيار السلامة للمبخرة؟',
              'sitEn': 'Selecting safe incense burner to prevent recurrence. Safety standard?',
              'hintAr': 'استخدام مبخرة ذات قاعدة ثقيلة متزنة أو مبخرة إلكترونية ذات حماية تلقائية',
              'hintEn': 'Use heavy wide-base burner or electronic incense burner with auto shutdown',
              'safeTextAr': 'استخدام مبخرة ذات قاعدة عريضة ثقيلة غير قابلة للانقلاب أو مبخرة كهربائية آمنة',
              'safeTextEn': 'Use wide heavy-base tip-proof burners or certified safe electric incense devices',
              'safeExpAr': 'وقاية ذكية؛ المباهر الثقيلة والكهربائية تمنع تناثر الجمر عند الاصطدام.',
              'safeExpEn': 'Smart safety; heavy base and electric burners eliminate open ember spill risks.',
              'safeOutAr': 'اخترت مبخرة آمنة للمحطة 5.',
              'safeOutEn': 'Selected safe burner for Station 5.',
              'unsafeTextAr': 'وضع المبخرة الخفيفة العالية فوق الحافة المتحركة للكنب',
              'unsafeTextEn': 'Balance lightweight tall incense burner on armrest of sofa',
              'unsafeExpAr': 'خطأ؛ وضع المبخرة على أطراف الكنب يسبب سقوطها عند تحرك أي شخص.',
              'unsafeExpEn': 'Error; balancing burners on sofa armrests leads to immediate tipping spills.',
              'unsafeOutAr': 'عرضت المجلس لسقوط المبخرة.',
              'unsafeOutEn': 'High risk of burner tipping.',
            },
            {
              'sitAr': 'التخلص الآمن من بقايا فحم المبخرة بعد انتهائها. كيف تتخلص منه؟',
              'sitEn': 'Safe disposal of used charcoal ash after event. Proper procedure?',
              'hintAr': 'نقع الفحم بالماء بالكامل قبل إلقائه بسلة المهملات',
              'hintEn': 'Soak charcoal ash completely in water before throwing in trash bin',
              'safeTextAr': 'غمر الفحم المستخدم بالماء بالكامل للتأكد من تبريده قبل رميه بسلة المهملات',
              'safeTextEn': 'Submerge spent charcoal completely in a bowl of water before bin disposal',
              'safeExpAr': 'إتمام تام؛ رمي الفحم دون نقعه بالماء هو السبب الأول لحرائق حاويات النفايات.',
              'safeExpEn': 'Complete resolution; dumping un-doused charcoal is top cause of trash can fires.',
              'safeOutAr': 'أكملت محطات سلامة الفحم والمبخرة بنجاح!',
              'safeOutEn': 'Successfully completed charcoal fire scenario!',
              'unsafeTextAr': 'رمي الفحم الساخن مباشرة في سلة المهملات البلاستيكية',
              'unsafeTextEn': 'Dump warm dry charcoal directly into plastic waste basket',
              'unsafeExpAr': 'خطأ؛ رمي الفحم الساخن بسلة المهملات يشعل النفايات البلاستيكية بسرعة.',
              'unsafeExpEn': 'Error; dry warm coals melt plastic bins causing violent trash canister fires.',
              'unsafeOutAr': 'اشتعلت سلة المهملات.',
              'unsafeOutEn': 'Trash bin ignited into flames.',
            },
          ],
        ),
      ];
}
