import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosEvacuation {
  static List<Scenario> get list => [
        // 1. Evacuation Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_1',
          categoryId: 'evacuation',
          titleAr: 'إخلاء التدافع في المنشآت والمباني',
          titleEn: 'Facility Evacuation & Crowd Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع الإخلاء الطارئ وتجنب مخاطر التدافع.',
          descriptionEn: 'Interactive 5-station scenario for emergency exit evacuation and crowd movement.',
          difficulty: 'متوسط',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'انطلقت أجهزة إنذار الحريق بالبرج التجاري. ما أول خطوة تسلكها؟',
              'sitEn': 'Commercial tower fire alarm sounds loudly. Initial action?',
              'hintAr': 'ترك الأغراض الثقيلة والتوجيه فوراً نحو اللوحات الإرشادية الخضراء لمخارج الطوارئ',
              'hintEn': 'Leave non-essential heavy bags and follow illuminated green emergency exit signs',
              'safeTextAr': 'ترك الحقائب والأشياء غير الضرورية والتوجيه فوراً نحو مخارج الطوارئ',
              'safeTextEn': 'Leave heavy personal items and head immediately toward marked emergency exits',
              'safeExpAr': 'سرعة استجابة؛ إخلاء الأغراض يمنع التعثر ويضمن الخروج السريع.',
              'safeExpEn': 'Quick response; abandoning bulky belongings prevents tripping and speeds exit.',
              'safeOutAr': 'توجهت لمسار الطوارئ للمحطة 2.',
              'safeOutEn': 'Headed into emergency exit path for Station 2.',
              'unsafeTextAr': 'الجمع والتنقيب عن الأغراض الشخصية والهدايا قبل مغادرة المكتب',
              'unsafeTextEn': 'Search office drawers to gather personal items before leaving building',
              'unsafeExpAr': 'خطأ؛ إضاعة الوقت في حزم الأغراض يعرضك لمحاصرة الدخان والنيران.',
              'unsafeExpEn': 'Error; wasting valuable evacuation seconds risks getting trapped in fire floor.',
              'unsafeOutAr': 'تأخرت في بدء الإخلاء.',
              'unsafeOutEn': 'Delayed initial evacuation start.',
            },
            {
              'sitAr': 'اختيار الطريق للنزول من الدور الـ 10. أي الوسيلتين تختار؟',
              'sitEn': 'Selecting descent route from 10th floor. Elevator vs Stairs?',
              'hintAr': 'استخدام سلالم الطوارئ المحصنة حتماً؛ يمنع منعاً باتاً استخدام المصاعد الكهربائية',
              'hintEn': 'Strictly use fire escape stairwell; NEVER use elevators during alarms',
              'safeTextAr': 'استخدام درج بيت السلامة وإغلاق الأبواب المضادة للحريق خلفك',
              'safeTextEn': 'Use fire exit stairwell closing smoke barrier doors behind you',
              'safeExpAr': 'اختيار حتمي؛ المصاعد تتوقف فجأة وتتحول لمصيدة خانقة عند انقطاع الكهرباء.',
              'safeExpEn': 'Vital choice; elevators stall and trap occupants when power cuts or shafts smoke.',
              'safeOutAr': 'نزلت عبر بيت الدرج الآمن للمحطة 3.',
              'safeOutEn': 'Descended via fire stairs for Station 3.',
              'unsafeTextAr': 'انتظار ودخول المصعد الكهربائي للنزول بسرعة أكبر',
              'unsafeTextEn': 'Wait for elevator to ride down quickly to ground floor',
              'unsafeExpAr': 'خطأ قاتل؛ قد يتوقف المصعد بالدور المشتعل أو تنقطع الكهرباء ويتحول لفرن.',
              'unsafeExpEn': 'Fatal mistake; elevators can open on fire floors or lose power trapping all.',
              'unsafeOutAr': 'تعطل المصعد بك بالدور المتوسط.',
              'unsafeOutEn': 'Elevator stalled mid-shaft.',
            },
            {
              'sitAr': 'حدوث تدافع وازدحام شديد عند البوابة الرئيسية. كيف تحمي نفسك من السقوط؟',
              'sitEn': 'Crowd surge near ground exit. How to protect body chest & balance?',
              'hintAr': 'وضع المرفقين والساعدين أمام الصدر كدرع حماية للقفص الصدري، والحركة مع اتجاه الكتلة',
              'hintEn': 'Fold arms across chest to protect lungs; move fluidly with crowd flow without stopping',
              'safeTextAr': 'ثني الذراعين أمام الصدر لحماية الرئتين والانسياب مع اتجاه الكتلة دون توقف',
              'safeTextEn': 'Cross arms over chest to shield ribcage, moving fluidly with crowd flow',
              'safeExpAr': 'تقنية حماية التدافع؛ درع الذراعين يحمي القفص الصدري من الضغط الخانق.',
              'safeExpEn': 'Crowd safety technique; arm box protects chest cavity from crushing pressure.',
              'safeOutAr': 'حافظت على توازنك ونفسك للمحطة 4.',
              'safeOutEn': 'Preserved balance and breathing for Station 4.',
              'unsafeTextAr': 'الوقوف عكس التدافع والدفع بقوة شديدة للخلف',
              'unsafeTextEn': 'Stand firm resisting crowd pushing forcefully backward',
              'unsafeExpAr': 'خطأ؛ مقاومة زحم التدافع تسبب التعثر والسقوط تحت أقدام الحشود.',
              'unsafeExpEn': 'Error; fighting crowd momentum risks losing balance and getting trampled.',
              'unsafeOutAr': 'تعرضت للسقوط تحت الأقدام.',
              'unsafeOutEn': 'Risked falling into crowd surge.',
            },
            {
              'sitAr': 'سقط شخص مجاور لك وسط التدافع. كيف تساعده بأمان بسرعة؟',
              'sitEn': 'Person trips and falls beside you in moving crowd. Safe quick aid?',
              'hintAr': 'رفعه بسرعة بقوة مع مساعدة شخص آخر، أو مساعدته لاتخاذ وضعية الجنين لحماية الرأس',
              'hintEn': 'Pull up immediately with team help or advise fetal position if unmovable',
              'safeTextAr': 'سحبه بسرعة خاطفة من ذراعيه بمساعدة شخص آخر لإعطائه التوازن فوراً',
              'safeTextEn': 'Quickly haul person up by arms with secondary help to restore footing',
              'safeExpAr': 'إنقاذ إنساني احترافي؛ رفع الساقط يمنع دهسه ويحمي تدفق الإخلاء.',
              'safeExpEn': 'Heroic crowd rescue; pulling fallen person prevents catastrophic trampling.',
              'safeOutAr': 'أنقذت الساقط وتوجهتما للمحطة 5.',
              'safeOutEn': 'Rescued fallen person, advancing to Station 5.',
              'unsafeTextAr': 'الدهس فوقه ومواصلة الجري دون الاكتراث له',
              'unsafeTextEn': 'Step directly over fallen person running forward',
              'unsafeExpAr': 'سلوك خطير؛ يؤدي للإصابات البليغة للطرفين وتعثر المزيد من الناس.',
              'unsafeExpEn': 'Hazardous behavior; causes severe injury and multi-person trip hazards.',
              'unsafeOutAr': 'تسببت في تعثر آخرين.',
              'unsafeOutEn': 'Caused secondary trip pileup.',
            },
            {
              'sitAr': 'الوصول لنقطة التجمع الخارجي (Assembly Point). ما الخطوة النهائية؟',
              'sitEn': 'Reached outdoor designated assembly area. Final step?',
              'hintAr': 'التجمع بالنقطة المحددة وتسجيل الاسم لدى مسؤول الإخلاء وعدم العودة إطلاقاً',
              'hintEn': 'Report to safety warden at assembly point for headcount; do NOT re-enter',
              'safeTextAr': 'الوقوف في نقطة التجمع المحددة، إبلاغ مشرف السلامة بأسماء المتواجدين، والانتظار',
              'safeTextEn': 'Stand at designated assembly point, check in with safety warden, wait',
              'safeExpAr': 'إتمام كامل؛ حصر المباني والتسجيل يمنع دخول رجال الدفاع المدني بالخطأ للبحث عنك.',
              'safeExpEn': 'Complete safety protocol; headcounts prevent firefighters from risking lives needlessly.',
              'safeOutAr': 'أكملت محطات الإخلاء وسلامة المنشآت بنجاح!',
              'safeOutEn': 'Successfully cleared all 5 evacuation safety stations!',
              'unsafeTextAr': 'مغادرة منطقة التجمع والعودة داخل المنشأة لأخذ سيارتك من المواقف',
              'unsafeTextEn': 'Leave assembly group re-entering basement parking to retrieve car',
              'unsafeExpAr': 'خطأ جسيم؛ قبو مواقف السيارات يمتلئ بالغازات السامة بسرعة.',
              'unsafeExpEn': 'Severe mistake; basement parkings collect toxic smoke and gases rapidly.',
              'unsafeOutAr': 'عرضت حياتك للخطر في المواقف.',
              'unsafeOutEn': 'Exposed self to basement smoke hazards.',
            },
          ],
        ),

        // Scenarios 2 to 9 for EVACUATION...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_2',
          categoryId: 'evacuation',
          titleAr: 'إنذار حريق بالمدرسة وإخلاء الطلاب',
          titleEn: 'School Fire Alarm & Student Evacuation',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتنظيم إخلاء المدارس والفصول التعليمية بسلام.',
          descriptionEn: 'Interactive 5-station scenario for school fire drill evacuation.',
          difficulty: 'سهل',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'انطلقت جرس إنذار الحريق بمبنى الفصل الدراسي. ما أول حركة من المعلم والطلاب؟',
              'sitEn': 'Fire alarm rings in school building. Immediate teacher & student action?',
              'hintAr': 'التوقف عن الدروس والوقوف بالترتيب بحط واحد وإغلاق باب الفصل',
              'hintEn': 'Stop class immediately, line up in single file, and close classroom door',
              'safeTextAr': 'التوقف عن الدراسة فوراً، الوقوف بنظام صف أحادي، وإغلاق باب الفصل خلفكم',
              'safeTextEn': 'Stop class instantly, line up in single file, and close classroom door behind',
              'safeExpAr': 'تصرف ممتاز؛ الوقوف بنظام يمنع التدافع وإغلاق الباب يعزل الدخان ببيت السلم.',
              'safeExpEn': 'Excellent step; single file prevents hallway stampedes & closing door isolates fire.',
              'safeOutAr': 'اصطفت المجموعة بنظام للمحطة 2.',
              'safeOutEn': 'Lined up in single file for Station 2.',
              'unsafeTextAr': 'الاندفاع الفوضوي الجماعي نحو الباب الرئيسي بالصرخ',
              'unsafeTextEn': 'Stampede frantically out the door screaming and pushing',
              'unsafeExpAr': 'خطأ؛ الاندفاع الفوضوي يسبب تعثر الطلاب واحتجازهم عند الباب.',
              'unsafeExpEn': 'Error; chaotic rush trips students clogging door exit frame.',
              'unsafeOutAr': 'انسد باب الفصل.',
              'unsafeOutEn': 'Classroom door jammed with students.',
            },
            {
              'sitAr': 'السير بممرات المدرسة نحو سلالم الطوارئ. كيف تتحرك الصفوف؟',
              'sitEn': 'Walking down hallways to emergency stairs. How should lines move?',
              'hintAr': 'المشي بسرعة وبنظام بدون ركض وحمل كشوفات الحضور من المعلم',
              'hintEn': 'Walk fast without running, keeping single file line with attendance roster',
              'safeTextAr': 'المشي السريع بنظام مع محاذاة الجدار وتجنب الركض أو التجاوز',
              'safeTextEn': 'Walk briskly in orderly line hugging wall, strictly avoiding running or passing',
              'safeExpAr': 'إجراء سليم؛ المشي السريع المنتظم أسرع وأمن بـ 3 مرات من الركض العشوائي.',
              'safeExpEn': 'Correct method; orderly brisk walking clears hallways 3x faster than chaotic running.',
              'safeOutAr': 'نزلت الصفوف عبر بيت الدرج للمحطة 3.',
              'safeOutEn': 'Descended stairs safely for Station 3.',
              'unsafeTextAr': 'الركض القفزي والاندفاع فوق عتبات الدرج',
              'unsafeTextEn': 'Leap and sprint down stair steps 3 at a time',
              'unsafeExpAr': 'خطأ؛ القفز على الدرج يسبب سقوط الطالب وتراكم الإصابات.',
              'unsafeExpEn': 'Error; jumping steps causes falls resulting in a stair pileup.',
              'unsafeOutAr': 'سقط طالب على الدرج.',
              'unsafeOutEn': 'Student fell on staircase.',
            },
            {
              'sitAr': 'وجود دخان خفيف في الدور الأرضي قبل المخرج. كيف تعبر الفصول؟',
              'sitEn': 'Light smoke in ground corridor before courtyard exit. How to pass?',
              'hintAr': 'تغطية الفم بمناديل رطبة والانخفاض قليلاً أثناء المشي',
              'hintEn': 'Cover mouth with damp tissues and stoop slightly while moving',
              'safeTextAr': 'توزيع مناشف أو مناديل رطبة وانخفاض مستوى قامة المشي',
              'safeTextEn': 'Distribute damp tissues covering mouth & stoop slightly while maintaining line',
              'safeExpAr': 'حماية تنفسية ممتازة؛ التغطية تمنع استنشاق جزيئات الكربون.',
              'safeExpEn': 'Great protection; damp tissue filtering shields young lungs from soot.',
              'safeOutAr': 'عبرت الفصول بسلام للمحطة 4.',
              'safeOutEn': 'Passed smoke zone safely for Station 4.',
              'unsafeTextAr': 'الوقوف بوسط الدخان والاستنشاق بدون غطاء',
              'unsafeTextEn': 'Stop mid-smoke corridor to cough without covering mouth',
              'unsafeExpAr': 'خطأ؛ الوقوف بوسط الدخان يسبب ذعر الطلاب واستنشاق السخام.',
              'unsafeExpEn': 'Error; stopping in smoke causes student panic and soot inhalation.',
              'unsafeOutAr': 'استنشق الطلاب الدخان.',
              'unsafeOutEn': 'Students inhaled smoke.',
            },
            {
              'sitAr': 'الوصول لملعب المدرسة (نقطة التجمع الخارجية). ماذا يفعل المعلم؟',
              'sitEn': 'Reaching school yard (outdoor assembly area). What does teacher do?',
              'hintAr': 'مناداة كشف الحضور والغياب (Roll Call) وحصر الطلاب المفقودين',
              'hintEn': 'Take attendance roll call immediately & account for any missing student',
              'safeTextAr': 'مناداة أسماء الطلاب بكشف الحضور وحصر أي طالب مفقود فوراً لفرق الدفاع المدني',
              'safeTextEn': 'Conduct immediate attendance roll call, reporting any missing student to CD captain',
              'safeExpAr': 'تنسيق محترف؛ حصر كشوفات المدارس يضمن عدم ترك أي طفل داخل المبنى.',
              'safeExpEn': 'Pro coordination; school roll calls verify zero child is left behind in building.',
              'safeOutAr': 'حصّرت الأسماء وتأكدت من الجميع للمحطة 5.',
              'safeOutEn': 'Completed student roll call for Station 5.',
              'unsafeTextAr': 'ترك الطلاب يتفرقون بالشارع دون أخذ الحضور',
              'unsafeTextEn': 'Allow students to scatter into street without conducting attendance check',
              'unsafeExpAr': 'خطأ؛ تفرق الطلاب يمنع التأكد من خروج الجميع من المبنى.',
              'unsafeExpEn': 'Error; scattering prevents verifying if all children escaped safely.',
              'unsafeOutAr': 'تفرق الطلاب بالخارج.',
              'unsafeOutEn': 'Students scattered into street.',
            },
            {
              'sitAr': 'وصول الدفاع المدني (998) والاطمئنان على سلامة المدرسة. ما المعيار الوقائي؟',
              'sitEn': 'Civil Defense clear building safety. School emergency drill protocol?',
              'hintAr': 'إجراء تدريب إخلاء فرضي (Fire Drill) كل فصل دراسي لجميع الطلاب',
              'hintEn': 'Execute mandatory fire drill training every school term for all students',
              'safeTextAr': 'تنفيذ فرضية إخلاء وهمية (Fire Drill) مرتين كل عام لترسيخ الوعي السلوكي',
              'safeTextEn': 'Schedule termly mandatory emergency fire drills to build instinctual student response',
              'safeExpAr': 'إتمام كامل؛ الفرضيات المنتظمة المدرسية تبني سرعة استجابة هادئة دون هلع.',
              'safeExpEn': 'Complete resolution; regular school fire drills build calm instinctual evacuation speed.',
              'safeOutAr': 'أكملت محطات إخلاء المدرسة بنجاح!',
              'safeOutEn': 'Successfully completed school fire drill scenario!',
              'unsafeTextAr': 'إلغاء خطط الإخلاء وعدم تدريب الطلاب طوال العام',
              'unsafeTextEn': 'Cancel all evacuation drills to save classroom time',
              'unsafeExpAr': 'خطأ؛ غياب التدريب يتسبب في الهلع والتدافع بالحوادث الحقيقية.',
              'unsafeExpEn': 'Error; lack of drill practice leads to severe panic stampedes during real fires.',
              'unsafeOutAr': 'غاب الوعي الإخلائي.',
              'unsafeOutEn': 'Lack of evacuation practice.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_3',
          categoryId: 'evacuation',
          titleAr: 'تدافع في مجمع تجاري أو فعالية كبرى',
          titleEn: 'Shopping Mall & Mega Event Crowd Surge',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع التدافع بالأسواق والفعاليات الجماهيرية.',
          descriptionEn: 'Interactive 5-station scenario for mall and event crowd surge safety.',
          difficulty: 'متوسط',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'حدث اندفاع مفاجئ وتدافع بساحة المول التجاري نحو المخارج. ما أول حركة؟',
              'sitEn': 'Sudden crowd surge hits shopping mall main atrium rushing exits. Action?',
              'hintAr': 'الابتعاد عن البوابات المزدحمة والتنقل نحو المخارج الجانبية الفرعية',
              'hintEn': 'Avoid main bottleneck exit gates; move sideways toward secondary service exits',
              'safeTextAr': 'الانحراف قطرياً نحو الأطراف والتوجيه لمخارج الخدمات الجانبية غير المزدحمة',
              'safeTextEn': 'Move diagonally toward room perimeters heading for secondary service exit doors',
              'safeExpAr': 'تصرف ممتاز؛ البوابات الرئيسية تصبح نقطة اختناق قاتلة (Bottleneck).',
              'safeExpEn': 'Excellent step; main gates become deadly choke bottlenecks during mass surges.',
              'safeOutAr': 'انحرفت لمخرج الخدمات للمحطة 2.',
              'safeOutEn': 'Steered to service exit for Station 2.',
              'unsafeTextAr': 'الاندفاع بوسط الكتلة الجماهيرية نحو البوابة الرئيسية المغلقة',
              'unsafeTextEn': 'Rush right into center of crowd crush toward main locked glass doors',
              'unsafeExpAr': 'خطأ؛ الاندفاع في المركز يضعك تحت ضغط زحم مئات الأجساد.',
              'unsafeExpEn': 'Error; rushing central bottleneck exposes body to crush pressures over 4000N.',
              'unsafeOutAr': 'تعرضت لضغط التدافع.',
              'unsafeOutEn': 'Trapped in central crowd crush.',
            },
            {
              'sitAr': 'ارتفاع ضغط التدافع وحصارك بين الحشود. كيف تحمي قفصك الصدري؟',
              'sitEn': 'Crowd pressure intensifies trapping you. How to shield chest cavity?',
              'hintAr': 'صنع درع باليدين وقبض المرفقين أمام الصدر لترك مساحة للتنفس',
              'hintEn': 'Create a defensive arm box by folding arms across chest to maintain breathing space',
              'safeTextAr': 'ثني المرفقين وعقد اليدين أمام الصدر بقوة لصنع مربع حماية فضائي للتنفس',
              'safeTextEn': 'Form an arm box by holding wrists across chest creating a 10cm space to expand lungs',
              'safeExpAr': 'تكتيك حماية الرئة؛ مربع الذراعين يمنع انقشاط القفص الصدري بسبب انضغاط الأجساد.',
              'safeExpEn': 'Lung protection box; arm shield prevents asphyxiation from mass thoracic compression.',
              'safeOutAr': 'حميت القفص الصدري بمربع الذراعين للمحطة 3.',
              'safeOutEn': 'Protected chest cavity for Station 3.',
              'unsafeTextAr': 'إنزال الذراعين بجانب الجسد والاستسلام لضغط الأجساد',
              'unsafeTextEn': 'Drop arms down by your sides allowing crowd to compress ribs',
              'unsafeExpAr': 'خطأ؛ إنزال الذراعين يسبب انحصار الرئتين ومنع شهيق الأكسجين.',
              'unsafeExpEn': 'Error; dropping arms pins ribs preventing chest expansion causing compressive asphyxia.',
              'unsafeOutAr': 'تعرضت لانحصار الرئتين.',
              'unsafeOutEn': 'Compressive chest asphyxia.',
            },
            {
              'sitAr': 'حافظت على التوازن والتحرك. كيف تسير قدميك لمنع التعثر والسقوط؟',
              'sitEn': 'Maintaining footing in crowd. How to move feet to avoid tripping?',
              'hintAr': 'المشي كخطوات الملاكم (Boxer Stance) بقدم متقدمة وأخرى متأخرة وثني الركبتين',
              'hintEn': 'Adopt a stable stance with feet staggered like a boxer, knees slightly bent',
              'safeTextAr': 'اتخاذ وضعية الثبات بقدم متقدمة وأخرى متأخرة والانسياب مع اتجاه الحركة',
              'safeTextEn': 'Adopt staggered stance with one foot forward, knees bent, moving fluidly with flow',
              'safeExpAr': 'توازن حركي رائع؛ قدم الملاكم توزع الثبات وتمنع اختلال التوازن عند الدفع.',
              'safeExpEn': 'Great footing physics; staggered stance absorbs forward/rear pushes without fall.',
              'safeOutAr': 'حافظت على التوازن للمحطة 4.',
              'safeOutEn': 'Maintained staggered balance for Station 4.',
              'unsafeTextAr': 'المشي برجل واحدة أو الصمود والتوقف التام في وجه التيار',
              'unsafeTextEn': 'Lock knees straight and try to stand completely immobile against crowd flow',
              'unsafeExpAr': 'خطأ؛ الوقوف المتصلب يسبب التعثر والسقوط تحت الأقدام.',
              'unsafeExpEn': 'Error; rigid locking causes loss of balance when pushed leading to fall under foot.',
              'unsafeOutAr': 'اختل توازن القدمين.',
              'unsafeOutEn': 'Staggered balance lost.',
            },
            {
              'sitAr': 'الوصول لباب مخرج الخدمات الجانبي وتواجد منظمي الأمن. ما الخطوة؟',
              'sitEn': 'Reaching side service exit door with security guards present. Action?',
              'hintAr': 'العبور بانتظام وعدم التوقف عند فتحة الباب لمنع تكدس من خلفك',
              'hintEn': 'Exit smoothly without stopping at doorway threshold to keep line moving',
              'safeTextAr': 'العبور السريع عبر الباب والابتعاد مسافة 20 متراً فوراً لمنع تكدس القادمين',
              'safeTextEn': 'Pass through exit door quickly and walk 20 meters away immediately to keep threshold clear',
              'safeExpAr': 'إجراء انسيابي ممتازة؛ الابتعاد عن عتبة الباب يفتح المجال للناجين خلفك.',
              'safeExpEn': 'Excellent flow management; clearing doorway threshold prevents rear pileups.',
              'safeOutAr': 'خرجت وأبتعدت عن الباب للمحطة 5.',
              'safeOutEn': 'Cleared exit threshold for Station 5.',
              'unsafeTextAr': 'التوقف فور الخروج من الباب لالتقاط أنفاسك بفتحة المخرج',
              'unsafeTextEn': 'Stop right at exit door threshold to rest and catch breath',
              'unsafeExpAr': 'خطأ؛ التوقف بالعتبة يسبب تراكم وتدافع القادمين من الخلف.',
              'unsafeExpEn': 'Error; stopping at doorway causes immediate pileup of rushing people behind.',
              'unsafeOutAr': 'حدث تكدس بعتبة الباب.',
              'unsafeOutEn': 'Doorway threshold pileup.',
            },
            {
              'sitAr': 'الوصول للشاحات الخارجية وسلامتك. ما المعيار الوقائي بالفعاليات الجماهيرية؟',
              'sitEn': 'Safely outdoors. Personal & event crowd safety standard?',
              'hintAr': 'تحديد نقاط الخروج للطوارئ فور دخول أي مكان مزدحم وتجنب الاختناقات',
              'hintEn': 'Locate emergency exit routes immediately upon entering any crowded venue',
              'safeTextAr': 'تحديد موقع مخرجين للطوارئ فور دخول أي مجمع أو فعالية والابتعاد عن البوابات الضيقة',
              'safeTextEn': 'Locate 2 emergency exit signs upon entering any venue and identify low-density exits',
              'safeExpAr': 'إتمام كامل؛ المسح البصري المسبق للمخارج يضمن نجاة خاطفة في الأزمات.',
              'safeExpEn': 'Complete resolution; pre-mapping venue exit routes guarantees swift self-evacuation.',
              'safeOutAr': 'أكملت محطات سلامة التدافع بنجاح!',
              'safeOutEn': 'Successfully completed mall crowd surge scenario!',
              'unsafeTextAr': 'دخول الأماكن المزدحمة دون معرفة مواقع مخارج الطوارئ',
              'unsafeTextEn': 'Enter dense mega-crowds without noting emergency exit locations',
              'unsafeExpAr': 'خطأ؛ غياب معرفة المخارج يجعلك تتبع التدافع العشوائي.',
              'unsafeExpEn': 'Error; lacking exit awareness forces following dangerous blind crowd surges.',
              'unsafeOutAr': 'غياب معرفة مخارج الطوارئ.',
              'unsafeOutEn': 'Lacked exit route awareness.',
            },
          ],
        ),

        // Scenarios 4 to 9 for EVACUATION...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_4',
          categoryId: 'evacuation',
          titleAr: 'احتجاز بالازدحام في بوابة الاستاد',
          titleEn: 'Stadium Gate Crowd Crush Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انحصار البوابات بالاستادات الرياضية.',
          descriptionEn: 'Interactive 5-station scenario for stadium gate crowd crush emergencies.',
          difficulty: 'صعب',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'عند الخروج من مباراة بالاستاد حدث توقف مفاجئ وازدحام خنق عند بوابات الدوار. ما الحركة؟',
              'sitEn': 'Sudden crowd freeze and choke crush at stadium turnstile exit gates. Action?',
              'hintAr': 'التحرك مع التيار المائل وتجنب الضغط على حواجز الحديد الصلبة',
              'hintEn': 'Move diagonally with flow; avoid getting pressed against fixed steel turnstile fences',
              'safeTextAr': 'التحرك الجانبي القطري للابتعاد عن الحواجز الحديدية والمضي نحو المساحات الفسيحة',
              'safeTextEn': 'Move diagonally sideways to clear fixed steel fencing toward open concourse space',
              'safeExpAr': 'تصرف ممتاز؛ الحواجز الحديدية الثابتة تسبب إصابات انحصار خطيرة.',
              'safeExpEn': 'Excellent response; fixed steel fences cause fatal crush injuries when pinned.',
              'safeOutAr': 'ابعدت عن الحواجز الصلبة للمحطة 2.',
              'safeOutEn': 'Steered clear of fixed steel barriers for Station 2.',
              'unsafeTextAr': 'الدفع المباشر للأمام نحو الدوارات المغلقة',
              'unsafeTextEn': 'Push forcefully straight ahead into turnstile steel bars',
              'unsafeExpAr': 'خطأ؛ الدفع نحو الحواجز المغلقة يحصر جسمك بين الأجساد والحديد.',
              'unsafeExpEn': 'Error; pushing toward locked turnstiles pins body against unyielding steel.',
              'unsafeOutAr': 'انحصرت بالحديد.',
              'unsafeOutEn': 'Pinned against steel turnstiles.',
            },
            {
              'sitAr': 'فقدت إحدى فردتي الحذاء وسط الزحام الشديد. هل تنحني لإحضارها؟',
              'sitEn': 'Lost a shoe in dense stadium crowd. Should you bend down to pick it up?',
              'hintAr': 'حظر الانحناء أو الجثو للأرض نهائياً ومواصلة السير بقدم واحدة',
              'hintEn': 'STRICTLY never bend down to pick up dropped items in moving crowds',
              'safeTextAr': 'مواصلة السير بانتظام وحظر الانحناء نهائياً لإحضار الحذاء الساقط',
              'safeTextEn': 'Keep moving upright continuously; STRICTLY never bend down to retrieve dropped shoe',
              'safeExpAr': 'قاعدة نجاة حاسمة؛ الانحناء في التدافع يسبب سقوطك فوراً تحت أقدام الجمهور.',
              'safeExpEn': 'Critical survival rule; bending down in a crowd crush guarantees getting knocked over.',
              'safeOutAr': 'واصلت المشي منتصباً للمحطة 3.',
              'safeOutEn': 'Kept moving upright for Station 3.',
              'unsafeTextAr': 'الانحناء للأرض للبحث عن الحذاء والتقاطه من بين الأقدام',
              'unsafeTextEn': 'Bend down between moving crowd legs to search for lost shoe',
              'unsafeExpAr': 'خطأ قاتل؛ الانحناء يجعلك تفقد توازنك وتسقط ليتم دهسك.',
              'unsafeExpEn': 'Fatal error; stooping down causes instant loss of balance and fatal trampling.',
              'unsafeOutAr': 'سقطت تحت الأقدام.',
              'unsafeOutEn': 'Knocked down under feet.',
            },
            {
              'sitAr': 'توقف الحركة تماماً وشعرت بضيق تنفس شديد. كيف تنظم تنفسك؟',
              'sitEn': 'Crowd gridlocked solid; feeling severe tightness. How to control breathing?',
              'hintAr': 'أخذ أنفاس قصيرة بطيئة وإبقاء الذراعين مرفوعتين كدرع حماية',
              'hintEn': 'Take controlled shallow breaths; keep arms locked across chest',
              'safeTextAr': 'أخذ أنفاس هادئة منتظمة وإبقاء الذراعين متقاطعتين فوق الصدر لتوفير مجال للرئة',
              'safeTextEn': 'Take controlled calm sips of air, keeping arms locked across chest cavity',
              'safeExpAr': 'تكتيك هادئ؛ التحكم بالتنفس يمنع نوبات الهلع والاستهلاك السريع للأكسجين.',
              'safeExpEn': 'Calm tactic; controlled breathing prevents hyperventilation panic and saves oxygen.',
              'safeOutAr': 'حافظت على التنفس بالدرع للمحطة 4.',
              'safeOutEn': 'Controlled breathing with arm box for Station 4.',
              'unsafeTextAr': 'الشهيق الشديد بالصراخ والبكاء بعالي الصوت',
              'unsafeTextEn': 'Scream loudly while gasping frantically for air',
              'unsafeExpAr': 'خطأ؛ الصراخ يفرغ أكسجين الرئة ويعجل بالاختناق.',
              'unsafeExpEn': 'Error; screaming rapidly depletes lung oxygen accelerating unconsciousness.',
              'unsafeOutAr': 'نفذ أكسجين الرئة.',
              'unsafeOutEn': 'Depleted lung oxygen.',
            },
            {
              'sitAr': 'فتحت أجهزة الأمن بوابة الطوارئ الجانبية العريضة. كيف تنتقل للمخرج؟',
              'sitEn': 'Security opens wide side emergency gate. How to move to newly opened exit?',
              'hintAr': 'الانسياب الهادئ مع موجة الجمهور المتجهة نحو فتحة البوابة',
              'hintEn': 'Move fluidly with wave momentum toward new open gate without fighting flow',
              'safeTextAr': 'الانسياب التكتيكي مع اتجاه الموجة البشرية المنسابة نحو البوابة المفتوحة',
              'safeTextEn': 'Flow fluidly with wave momentum toward newly opened gate avoiding sudden stops',
              'safeExpAr': 'تحرك انسيابي سليم؛ التحرك مع الموجة يحافظ على توازنك حتى نقطة الأمان.',
              'safeExpEn': 'Fluid motion; drifting with crowd wave maintains balance until passing gate.',
              'safeOutAr': 'عبِرت عبر البوابة المفتوحة للمحطة 5.',
              'safeOutEn': 'Passed through emergency gate for Station 5.',
              'unsafeTextAr': 'محاولة قطع الطريق عكس الموجة للجري منفصلاً',
              'unsafeTextEn': 'Try cutting perpendicularly against crowd wave to run separately',
              'unsafeExpAr': 'خطأ؛ قطع موجة التدافع يسبب الاصطدام والسقوط.',
              'unsafeExpEn': 'Error; fighting crowd wave perpendicular forces causes instant loss of footing.',
              'unsafeOutAr': 'اصطدمت بموجة التدافع.',
              'unsafeOutEn': 'Collided with crowd wave.',
            },
            {
              'sitAr': 'الخروج خارج أسوار الاستاد وسلامتك. ما معيار السلامة بتنظيم الاستادات؟',
              'sitEn': 'Outside stadium perimeter safe. Stadium architectural safety standard?',
              'hintAr': 'فتح جميع البوابات الكبيرة تلقائياً عند انتهاء الفعالية وتوفير بوابات دوارة ذكية',
              'hintEn': 'Mandate wide-opening emergency gates & clear concourses post-match',
              'safeTextAr': 'التأكد من فتح جميع البوابات الكبرى وإلغاء اختناقات التفتيش عند الخروج الجماهيري',
              'safeTextEn': 'Ensure all perimeter exit gates are fully opened post-event eliminating bottlenecks',
              'safeExpAr': 'إتمام كامل؛ فتح البوابات الكبرى يشتت الضغط الجماهيري وتضمن الإخلاء الآمن.',
              'safeExpEn': 'Complete resolution; opening wide gates disperses crowd density preventing crush.',
              'safeOutAr': 'أكملت محطات سلامة بوابات الاستاد بنجاح!',
              'safeOutEn': 'Successfully completed stadium gate crush scenario!',
              'unsafeTextAr': 'إغلاق البوابات الكبرى وتفويج الجماهير عبر دوار واحد ضيق',
              'unsafeTextEn': 'Funnel 50,000 fans through a single narrow turnstile gate',
              'unsafeExpAr': 'خطأ؛ حصر الجماهير في منفذ ضيق السبب الرئيسي لحوادث الاستادات.',
              'unsafeExpEn': 'Error; funneled exit bottlenecks are the leading cause of stadium crowd crush disasters.',
              'unsafeOutAr': 'تسبب الضيق بتدافع.',
              'unsafeOutEn': 'Bottleneck crush hazard persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_5',
          categoryId: 'evacuation',
          titleAr: 'انقطاع الكهرباء في قطار أو نفق',
          titleEn: 'Subway/Train Tunnel Blackout Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انقطاع الكهرباء والاحتجاز داخل الأنفاق والقطارات.',
          descriptionEn: 'Interactive 5-station scenario for train and subway tunnel blackouts.',
          difficulty: 'متوسط',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'توقف القطار فجأة داخل النفق وانقطعت الإضاءة والتكييف والتصقت الحشود. ما أول خطوة؟',
              'sitEn': 'Train halts suddenly in dark tunnel; AC & lights cut off. First action?',
              'hintAr': 'التزام الهدوء بالقطار، تشغيل كشاف الجوال، والاستماع لتعليمات السائق',
              'hintEn': 'Stay calm inside car, switch on phone LED light, listen to driver intercom',
              'safeTextAr': 'الهدوء التام، تشغيل كشاف الجوال، والاستماع لبيانات السائق عبر سماعات الطوارئ',
              'safeTextEn': 'Stay calm, switch on mobile phone LED torch, and listen to PA system announcements',
              'safeExpAr': 'تصرف ممتاز؛ الهدوء يمنع الهلع الجماعي واستهلاك الأكسجين داخل العربة المغلقة.',
              'safeExpEn': 'Excellent step; staying calm prevents mass panic and conserves oxygen in car.',
              'safeOutAr': 'شغّلت الكشاف واستمعت للتعليمات للمحطة 2.',
              'safeOutEn': 'Turned torch on & listened to PA for Station 2.',
              'unsafeTextAr': 'الصراخ وكسر نوافذ القطار فجأة بين السكك الحديدية',
              'unsafeTextEn': 'Scream hysterically & shatter train windows trying to jump out onto tracks',
              'unsafeExpAr': 'خطأ؛ القفز العشوائي على السكك الكهربائية ينطوي على خطورة الصعق والموت.',
              'unsafeExpEn': 'Error; jumping onto third-rail electrified tracks risks instant high-voltage electrocution.',
              'unsafeOutAr': 'تعرضت لخطر السكة الكهربائية.',
              'unsafeOutEn': 'Electrified track hazard.',
            },
            {
              'sitAr': 'أعلن السائق بدء عملية الإخلاء عبر المخرج الأمامي للقطار. كيف تتحرك الركاب؟',
              'sitEn': 'Driver announces controlled evacuation via front train door. How to move?',
              'hintAr': 'المشي بنظام صف واحد نحو باب الطوارئ الأمامي ومساعدة الأطفال وكبار السن',
              'hintEn': 'Walk single file toward front emergency door aiding children and elderly',
              'safeTextAr': 'التحرك بنظام صف واحد نحو باب الطوارئ الأمامي مع إعطاء الأولوية للأطفال والنساء',
              'safeTextEn': 'Move in single file toward designated front exit door giving priority to kids & elderly',
              'safeExpAr': 'إجراء إخلاء سليم؛ الصف الأحادي يمنع الانحصار بممرات العربات الضيقة.',
              'safeExpEn': 'Correct evacuation rule; single file aisle progression prevents aisle blockages.',
              'safeOutAr': 'تحركت الصفوف للبوابة الأمامية للمحطة 3.',
              'safeOutEn': 'Advanced single file for Station 3.',
              'unsafeTextAr': 'التدافع والقفز فوق المقاعد للوصول للأمام أسرع',
              'unsafeTextEn': 'Climb & jump over seats pushing others to reach front first',
              'unsafeExpAr': 'خطأ؛ القفز فوق المقاعد يسبب سقوط الركاب وتراكم الإصابات بالظلام.',
              'unsafeExpEn': 'Error; climbing over seats in dark causes falls & injuries in train aisle.',
              'unsafeOutAr': 'سقط ركاب بالممر.',
              'unsafeOutEn': 'Passengers fell in aisle.',
            },
            {
              'sitAr': 'النزول لسمك النفق المظلم. كيف تسير على ممشى الطوارئ بجانب السكة؟',
              'sitEn': 'Stepping down into dark tunnel walkway. How to walk on side catwalk safely?',
              'hintAr': 'المشي على رصيف الطوارئ المرتفع وتجنب لمس القضبان الكهربائية السفلية',
              'hintEn': 'Walk on elevated side catwalk; strictly avoid touching lower electrified rails',
              'safeTextAr': 'المشي على ممشى الطوارئ الجانبي المرتفع والإمساك بحبل السلامة الجداري',
              'safeTextEn': 'Step onto elevated side emergency catwalk holding wall guide rope continuously',
              'safeExpAr': 'مسار آمن؛ ممشى الطوارئ الجانبي يعزلك عن خطر السكك وتيار القضيب الثالث.',
              'safeExpEn': 'Safe path; side catwalk keeps passengers elevated away from high-voltage 3rd rails.',
              'safeOutAr': 'سرت على الممشى الجانبي للمحطة 4.',
              'safeOutEn': 'Walked side catwalk for Station 4.',
              'unsafeTextAr': 'السير وسط السكة الحديدية بين الحجارة والقضبان السفلية',
              'unsafeTextEn': 'Walk down center of track bed stepping over lower metal rails',
              'unsafeExpAr': 'خطأ؛ السير على السكة ينطوي على خطورة الصعق والتعثر بالحجارة.',
              'unsafeExpEn': 'Error; walking track bed risks 750V electrocution and tripping on ballast stones.',
              'unsafeOutAr': 'تعرضت لخطر السكة.',
              'unsafeOutEn': 'Exposed to track hazards.',
            },
            {
              'sitAr': 'الوصول لرصيف المحطة المجاورة عبر سلم النفق. ما التوجيه النهائي؟',
              'sitEn': 'Reaching next station platform via exit stairs. Final guidance?',
              'hintAr': 'الصعود لرصيف المحطة وتسجيل السلامة لدى فريق أمن المترو',
              'hintEn': 'Ascend platform stairs & report to metro station staff for headcount',
              'safeTextAr': 'الصعود لرصيف المحطة المضاء والتوجه نحو مخرج الشارع مع إبلاغ فريق أمن المترو',
              'safeTextEn': 'Ascend to lit station platform & proceed toward street exit checking in with station staff',
              'safeExpAr': 'إتمام رائع؛ الخروج لرصيف المحطة ينهي الإخلاء بالنفق المظلم بنجاح.',
              'safeExpEn': 'Great resolution; platform exit completes tunnel evacuation cleanly & safely.',
              'safeOutAr': 'وصلت لرصيف المحطة للمحطة 5.',
              'safeOutEn': 'Reached station platform for Station 5.',
              'unsafeTextAr': 'العودة لداخل النفق المظلم للبحث عن حقيبة نُسيت بالعربة',
              'unsafeTextEn': 'Turn back into dark tunnel to search for lost handbag left in car',
              'unsafeExpAr': 'خطأ؛ العودة للنفق تعرضك للضياع والصعق عند إعادة التيار.',
              'unsafeExpEn': 'Error; re-entering dark tunnel risks getting hit when power test restores.',
              'unsafeOutAr': 'عرضت نفسك لخطر النفق.',
              'unsafeOutEn': 'Re-entered hazardous tunnel.',
            },
            {
              'sitAr': 'الخروج للشارع وتوفر وسائل النقل البديلة. ما المعيار الوقائي للأنفاق؟',
              'sitEn': 'Out on street; alternative transport provided. Tunnel safety standard?',
              'hintAr': 'تأمين إضاءة طوارئ تلقائية (UPS) ومسارات إخلائية مضاءة بالأنفاق',
              'hintEn': 'Ensure automatic UPS emergency lighting & photo-luminescent tunnel signs',
              'safeTextAr': 'تزويد جميع أنفاق القطارات بإضاءة طوارئ مساندة (UPS) ومسارات فوسفورية موجهة',
              'safeTextEn': 'Equip all subway tunnels with automatic UPS emergency lighting and photoluminescent signs',
              'safeExpAr': 'إتمام كامل؛ الإضاءة الفوسفورية تضمن الرؤية وإرشاد النازلين حتى في انقطاع الكهرباء.',
              'safeExpEn': 'Complete resolution; photoluminescent signage guides evacuees even during total grid collapse.',
              'safeOutAr': 'أكملت محطات إخلاء نفق القطار بنجاح!',
              'safeOutEn': 'Successfully completed train blackout scenario!',
              'unsafeTextAr': 'إهمال صيانة بطاريات الطوارئ بأنفاق القطارات',
              'unsafeTextEn': 'Neglect emergency battery backup maintenance in rail tunnels',
              'unsafeExpAr': 'خطأ؛ غياب إضاءة الطوارئ يحول النفق لظلام دامس يسبب الهلع.',
              'unsafeExpEn': 'Error; unmaintained backup lighting leaves tunnels pitch black causing mass panic.',
              'unsafeOutAr': 'ظلام دامس بالنفق.',
              'unsafeOutEn': 'Pitch black tunnel hazard persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_6',
          categoryId: 'evacuation',
          titleAr: 'تسرب كيميائي بمصنع أو مختبر',
          titleEn: 'Chemical Spill & Hazardous Gas Evacuation',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تسرب المواد الكيميائية الخطرة بالمناطق المغلقة.',
          descriptionEn: 'Interactive 5-station scenario for chemical spill & toxic gas leaks.',
          difficulty: 'صعب',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'انكسرت حاوية مادة كيميائية وانبعثت غازات لاذعة للمشر بالمختبر/المصنع. ما أول حركة؟',
              'sitEn': 'Chemical container shatters releasing acrid toxic vapor in lab/factory. First action?',
              'hintAr': 'حبس التنفس، التراجع فوراً عكس اتجاه تيار الهواء، وسحب مقبض إنذار المواد الخطرة',
              'hintEn': 'Hold breath, retreat upwind immediately, & pull chemical emergency alarm',
              'safeTextAr': 'حبس التنفس، الانسحاب فوراً عكس اتجاه تيار الهواء (Upwind)، وتفعيل إنذار الإخلاء',
              'safeTextEn': 'Hold breath, evacuate immediately UPWIND of spill, & trigger chemical hazmat alarm',
              'safeExpAr': 'تصرف ممتاز؛ التحرك عكس التيار يمنع استنشاق الأبخرة الحمضية/القلوية الكاوية.',
              'safeExpEn': 'Excellent step; moving upwind prevents breathing caustic acid/solvent vapors.',
              'safeOutAr': 'انسحبت عكس تيار الغاز للمحطة 2.',
              'safeOutEn': 'Retreated upwind for Station 2.',
              'unsafeTextAr': 'الانحناء والمشي مع اتجاه الغاز لمعاينة السائل المنسكب',
              'unsafeTextEn': 'Bend down downwind to sniff and inspect spilled liquid',
              'unsafeExpAr': 'خطأ قاتل؛ استنشاق أبخرة الكيماويات يسبب حرق القصبة الهوائية والإغماء.',
              'unsafeExpEn': 'Fatal error; sniffing chemical vapors burns lungs causing immediate collapse.',
              'unsafeOutAr': 'استنشقت الأبخرة الكاوية.',
              'unsafeOutEn': 'Inhaled toxic chemical gas.',
            },
            {
              'sitAr': 'تأثرت عينيك أو جلدك برذاذ المادة الكيميائية أثناء الانسحاب. كيف تسعف عينيك؟',
              'sitEn': 'Chemical splash hits eyes/skin during retreat. Emergency eye wash protocol?',
              'hintAr': 'غسل العينين فوراً بمحطة غسيل العيون (Eye Wash) لمدة 15 دقيقة بماء جاري',
              'hintEn': 'Flush eyes immediately at emergency eyewash station for 15 full minutes with water',
              'safeTextAr': 'التوجه لمحطة غسيل العيون الطارئة وغسل العينين بالماء الجاري المتصل لمدة 15 دقيقة',
              'safeTextEn': 'Flush eyes continuously at emergency eyewash station with running water for 15 mins',
              'safeExpAr': 'إجراء طبي حرج؛ الغسيل المتصل بالماء يغسل المادة الكيميائية ويمنع فقدان البصر.',
              'safeExpEn': 'Critical medical protocol; 15-minute continuous water flush stops chemical ocular burns.',
              'safeOutAr': 'غسلت العينين 15 دقيقة للمحطة 3.',
              'safeOutEn': 'Flushed eyes at eyewash station for Station 3.',
              'unsafeTextAr': 'فرك العينين بشدة بقماش جاف',
              'unsafeTextEn': 'Rub eyes vigorously with dry shop towel',
              'unsafeExpAr': 'خطأ؛ فرك العينين ينشر المادة الكيميائية داخل القرنية ويسبب العمى.',
              'unsafeExpEn': 'Error; rubbing eyes embeds chemical deeper into cornea causing permanent blindness.',
              'unsafeOutAr': 'تضررت القرنية بالفرك.',
              'unsafeOutEn': 'Cornea damaged by rubbing.',
            },
            {
              'sitAr': 'الخروج خارج المنشأة إلى المنطقة الآمنة. أين تقف بالنسبة لاتجاه الريح؟',
              'sitEn': 'Evacuated outside facility. Assembly position relative to wind direction?',
              'hintAr': 'الوقوف في اتجاه عكس الريح (Upwind) وعلى مسافة مرتفعة آمنة',
              'hintEn': 'Assemble UPWIND & uphill from chemical release point',
              'safeTextAr': 'التجمع في نقطة الإخلاء المحددة الواقعة في اتجاه عكس الريح (Upwind) وفي مكان مرتفع',
              'safeTextEn': 'Assemble at designated hazmat point positioned UPWIND and UPHILL from leak',
              'safeExpAr': 'تأمين أمني رائع؛ الغازات الكيميائية تتجه مع الريح وتنزل للمناطق المنخفضة.',
              'safeExpEn': 'Great safety step; toxic hazmat plumes travel downwind & settle in low-lying hollows.',
              'safeOutAr': 'وقفت في موقع عكس الريح للمحطة 4.',
              'safeOutEn': 'Assembled upwind for Station 4.',
              'unsafeTextAr': 'الوقوف مع اتجاه الريح (Downwind) في الحفر المنخفضة',
              'unsafeTextEn': 'Stand downwind in low-lying parking ditch near exhaust vents',
              'unsafeExpAr': 'خطأ؛ الوقوف مع الريح يضعك مباشرة في سحابة الغازات المنتشرة.',
              'unsafeExpEn': 'Error; assembling downwind puts group directly in path of toxic chemical plume.',
              'unsafeOutAr': 'تعرضت لسحابة الغازات.',
              'unsafeOutEn': 'Exposed to downwind toxic plume.',
            },
            {
              'sitAr': 'وصول فرقة المواد الخطرة بالدفاع المدني (Hazmat 998). ما البيانات المطلوبة؟',
              'sitEn': 'Civil Defense Hazmat team arrives (998). What chemical safety data to provide?',
              'hintAr': 'تزويد الضابط بصحيفة بيانات سلامة المادة (MSDS) واسم المركب الكيميائي',
              'hintEn': 'Hand field captain Material Safety Data Sheet (MSDS) & exact chemical name',
              'safeTextAr': 'تزويد قائد فرقة المواد الخطرة بصحيفة بيانات أمان المادة (MSDS) وموقع التسرب',
              'safeTextEn': 'Hand Hazmat captain the Material Safety Data Sheet (MSDS) & exact chemical CAS number',
              'safeExpAr': 'تسليم نموذجي؛ صحيفة MSDS تحدد الترياق ولبس الحماية الخاص بالطوارئ (Level A/B).',
              'safeExpEn': 'Model reporting; MSDS sheet tells Hazmat crew exact suit level (A/B) & neutralizing agent.',
              'safeOutAr': 'سلمت صحيفة MSDS للمحطة 5.',
              'safeOutEn': 'Handed MSDS sheet to Hazmat for Station 5.',
              'unsafeTextAr': 'عدم إبلاغ الفرق برمز المادة ومحاولة التكتم على اسمها',
              'unsafeTextEn': 'Hide chemical identity from Hazmat captain to avoid inspection fine',
              'unsafeExpAr': 'خطأ؛ إخفاء اسم المادة يعرض فرق الإنقاذ للتسمم والارتشاح.',
              'unsafeExpEn': 'Error; concealing chemical name endangers Hazmat responders without proper suits.',
              'unsafeOutAr': 'تأخرت عملية التطهير.',
              'unsafeOutEn': 'Hazmat containment delayed.',
            },
            {
              'sitAr': 'تطهير المنشأة وتأمين الموقع. ما المعيار الوقائي المستدام للكيماويات؟',
              'sitEn': 'Facility decontaminated. Sustainable chemical safety & storage standard?',
              'hintAr': 'تخزين الكيماويات بحاويات مزدوجة معتمدة وتوفير معدات الحماية (PPE)',
              'hintEn': 'Store chemicals in secondary containment bunds & mandate PPE gear',
              'safeTextAr': 'حفظ الكيماويات بحاويات مزدوجة معتمدة وتوفير أجهزة تنفس ومحطات غسيل العيون',
              'safeTextEn': 'Enforce secondary bund containment for all chemicals & mandate eye-wash/PPE stations',
              'safeExpAr': 'إتمام كامل؛ الحاويات المزدوجة ومحطات الغسيل تمنع الكوارث الكيميائية كلياً.',
              'safeExpEn': 'Complete resolution; secondary containment bunds trap 100% of primary leaks.',
              'safeOutAr': 'أكملت محطات نجاة التسرب الكيميائي بنجاح!',
              'safeOutEn': 'Successfully completed chemical spill scenario!',
              'unsafeTextAr': 'تخزين الكيماويات في عبوات زجاجية غير مخصصة بأسقف مكشوفة',
              'unsafeTextEn': 'Store concentrated acids in unlabelled glass jars on high open shelves',
              'unsafeExpAr': 'خطأ؛ الحفظ العشوائي يسبب كسر العبوات وتجدد الكوارث الكيميائية.',
              'unsafeExpEn': 'Error; improper glass storage leads to shelf falls and repeated toxic chemical spills.',
              'unsafeOutAr': 'تجدد خطر التسرب الكيميائي.',
              'unsafeOutEn': 'Chemical spill hazard persisted.',
            },
          ],
        ),

        // Scenarios 7 to 9 for EVACUATION...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_7',
          categoryId: 'evacuation',
          titleAr: 'خروج طارئ من مستشفى أثناء حريق',
          titleEn: 'Hospital Ward Emergency Fire Evacuation',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتنفيذ بروتوكول إخلاء المستشفيات ورعاية المرضى.',
          descriptionEn: 'Interactive 5-station scenario for hospital fire evacuation (RACE protocol).',
          difficulty: 'صعب',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'انطلقت أجهزة الإنذار بجناح التمريض بالمستشفى (Code Red). ما أول خطوة طبق بروتوكول RACE؟',
              'sitEn': 'Code Red fire alarm triggers in hospital ward. First step of RACE protocol?',
              'hintAr': 'الخطوة R (Rescue): إنقاذ المرضى في الخطر المباشر أولاً لنقطة آمنة',
              'hintEn': 'Step R (Rescue): Rescue & move patients in immediate fire danger first',
              'safeTextAr': 'تطبيق R (Rescue): إنقاذ ونقل المرضى المتواجدين في غرف الخطر المباشر فوراً',
              'safeTextEn': 'Execute R (Rescue): Instantly rescue patients in immediate room fire danger',
              'safeExpAr': 'تصرف ممتاز؛ بروتوكول RACE يبدأ دائماً بإنقاذ الأرواح المعرضة للخطر المباشر.',
              'safeExpEn': 'Excellent first step; RACE protocol prioritizes immediate patient life rescue first.',
              'safeOutAr': 'أنقذت المرضى بالغرفة للمحطة 2.',
              'safeOutEn': 'Rescued patients in immediate fire room for Station 2.',
              'unsafeTextAr': 'ترك المرضى بغرفهم المشتعلة والركض للخارج منفصلاً',
              'unsafeTextEn': 'Abandon patients in burning room running outside alone',
              'unsafeExpAr': 'خطأ؛ إهمال المرضى العاجزين ينافي بروتوكولات السلامة الطبية.',
              'unsafeExpEn': 'Error; abandoning bedridden patients violates fundamental medical safety codes.',
              'unsafeOutAr': 'تعرض المرضى لخطر الحريق.',
              'unsafeOutEn': 'Patients exposed to direct fire danger.',
            },
            {
              'sitAr': 'الخطوة الثانية في بروتوكول RACE (Alarm & Contain). كيف تعزل جناح الحريق؟',
              'sitEn': 'Second step in RACE protocol (Alarm & Contain). How to isolate fire ward?',
              'hintAr': 'تفعيل الإنذار وإغلاق جميع أبواب غرف المرضى والأبواب المقاومة للحريق (Contain)',
              'hintEn': 'Pull alarm, close all patient room doors & fire barrier doors (Contain)',
              'safeTextAr': 'إغلاق جميع أبواب غرف المرضى وأبواب حواجز الدخان الجدارية لعزل النيران (Contain)',
              'safeTextEn': 'Close all patient room doors and automated smoke barrier doors to contain smoke/fire',
              'safeExpAr': 'إجراء عزل رائع؛ إغلاق أبواب المستشفى يعزل الدخان ويمنع انتشاره بالأجنحة.',
              'safeExpEn': 'Great containment move; fire doors in hospitals hold smoke/fire back for 1-2 hours.',
              'safeOutAr': 'عزلت جناح الحريق للمحطة 3.',
              'safeOutEn': 'Contained fire ward doors for Station 3.',
              'unsafeTextAr': 'فتح جميع أبواب الغرف وشبكات التهوية',
              'unsafeTextEn': 'Propping all patient room doors open to vent smoke into hallway',
              'unsafeExpAr': 'خطأ؛ فتح أبواب الغرف يدفع الدخان السام لممرات إخلاء المرضى.',
              'unsafeExpEn': 'Error; open doors allow smoke to flood hospital corridor evacuation routes.',
              'unsafeOutAr': 'امتلأت الممرات بالدخان.',
              'unsafeOutEn': 'Corridors flooded with smoke.',
            },
            {
              'sitAr': 'نقل المرضى المقعدين وغير القادرين على المشي. ما وسيلة النقل الأفقية الآمنة؟',
              'sitEn': 'Evacuating bedridden patients horizontally. Safe horizontal transfer method?',
              'hintAr': 'النقل الأفقي (Horizontal Evacuation) للمنطقة المجاورة خلف أبواب الحريق باستخدام أغطية الأسرة',
              'hintEn': 'Perform Horizontal Evacuation to adjacent zone past fire doors using bed sheets/wheelchairs',
              'safeTextAr': 'إخلاء المرضى أفقياً (Horizontal Evacuation) للمنطقة المجاورة خلف أبواب الدخان باستخدام الكراسي',
              'safeTextEn': 'Evacuate patients horizontally past heavy smoke barrier doors into adjacent safe zone',
              'safeExpAr': 'تكتيك مستشفيات معتمد؛ الإخلاء الأفقي ينقل المرضى لمنطقة آمنة بالدور نفسه دون الحاجة للدرج.',
              'safeExpEn': 'Certified hospital tactic; horizontal evacuation moves beds past fire doors on same floor.',
              'safeOutAr': 'نقلت المرضى أفقياً للمحطة 4.',
              'safeOutEn': 'Transferred patients horizontally for Station 4.',
              'unsafeTextAr': 'محاولة حمل أسرة المرضى الثقيلة عبر الدرج الضيق',
              'unsafeTextEn': 'Try carrying heavy motorized hospital beds down narrow emergency stairs',
              'unsafeExpAr': 'خطأ؛ حمل الأسرة الكهربائية بالدرج ينسد بيت الدرج ويتسبب بسقوطها.',
              'unsafeExpEn': 'Error; carrying 200kg electric beds down stairwells blocks exit stairs completely.',
              'unsafeOutAr': 'انسد بيت الدرج بالأسرة.',
              'unsafeOutEn': 'Stairwell blocked by heavy bed.',
            },
            {
              'sitAr': 'فصل أنظمة الأكسجين المركزي (O2 Shutoff) بالجناح المشتعل. كيف تؤمن الأكسجين؟',
              'sitEn': 'Medical gas zone valve shutoff (O2 Zone Valve). How to secure oxygen lines?',
              'hintAr': 'إغلاق صمام الأكسجين الموحد للجناح المشتعل لمنع تغذية النار بالأكسجين',
              'hintEn': 'Shut zone valve box for medical O2 to prevent feeding fire with pure oxygen',
              'safeTextAr': 'إغلاق صمام الأكسجين الطبي الرئيسي للجناح المشتعل (Zone Valve Box) بحذر',
              'safeTextEn': 'Shut medical oxygen zone valve box for the fire sector to cut off pressurized O2 feed',
              'safeExpAr': 'تأمين حيوي؛ الأكسجين المضغوط يسبب انفجاراً وتسارعاً هائلاً لشعلة النار.',
              'safeExpEn': 'Vital safety protocol; medical O2 under pressure causes explosive flash fires if ruptured.',
              'safeOutAr': 'أغلقت صمام الأكسجين للمحطة 5.',
              'safeOutEn': 'Shut medical oxygen zone valve for Station 5.',
              'unsafeTextAr': 'ترك صمامات الأكسجين مفتوحة تتدفق بالغرف المشتعلة',
              'unsafeTextEn': 'Leave medical oxygen zone valves wide open in fire area',
              'unsafeExpAr': 'خطأ؛ تدفق الأكسجين النقي يحول الحريق البسيط لانفجار ناري عارم.',
              'unsafeExpEn': 'Error; flowing pure oxygen turns minor room fire into an uncontrollable blast.',
              'unsafeOutAr': 'انفجرت النار بالأكسجين.',
              'unsafeOutEn': 'Oxygen-fed flash fire explosion.',
            },
            {
              'sitAr': 'وصول الدفاع المدني (998) وتأمين المستشفى. ما المعيار الوقائي لمنشآت الرعاية؟',
              'sitEn': 'Civil Defense clear hospital building. Healthcare facility safety standard?',
              'hintAr': 'تدريب الكادر الطبي على بروتوكول RACE وصيانة رشاشات المياه التلقائية (Sprinklers)',
              'hintEn': 'Train medical staff on RACE/PASS protocols & maintain automatic fire sprinklers',
              'safeTextAr': 'التدريب الدوري لجميع الكوادر على خطة RACE وصيانة شبكة الرشاشات التلقائية',
              'safeTextEn': 'Mandate RACE protocol staff drills & quarterly inspection of automatic fire sprinkler systems',
              'safeExpAr': 'إتمام كامل؛ رشاشات المياه التلقائية وبروتوكول RACE يضمنان سلامة المرضى 100%.',
              'safeExpEn': 'Complete resolution; automatic sprinklers & RACE training protect non-ambulatory patients.',
              'safeOutAr': 'أكملت محطات إخلاء المستشفى بنجاح!',
              'safeOutEn': 'Successfully completed hospital fire evacuation scenario!',
              'unsafeTextAr': 'إهمال صيانة رشاشات المياه وإغلاق صمامات التغذية',
              'unsafeTextEn': 'Shut off main water supply to hospital automatic fire sprinkler system',
              'unsafeExpAr': 'خطأ؛ تعطيل الرشاشات التلقائية يحرم المستشفى من خط الدفاع الأول.',
              'unsafeExpEn': 'Error; shutting off sprinkler mains deprives healthcare facilities of core fire defense.',
              'unsafeOutAr': 'تعطلت رشاشات الحريق.',
              'unsafeOutEn': 'Fire sprinkler system disabled.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_8',
          categoryId: 'evacuation',
          titleAr: 'زلزال خفيف أو هزات أرضية بالمبنى',
          titleEn: 'Earthquake & Tremor Safety Protocol',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتطبيق بروتوكول النجاة أثناء الهزات الأرضية (Drop, Cover, Hold On).',
          descriptionEn: 'Interactive 5-station scenario for earthquake response: Drop, Cover, Hold On.',
          difficulty: 'متوسط',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'اهتز المبنى فجأة وبدأت الأغراض بالاهتزاز والسقوط (هزة أرضية). ما أول حركة؟',
              'sitEn': 'Building shakes violently; items falling off shelves (earthquake). First step?',
              'hintAr': 'تطبيق قاعدة (Drop, Cover, Hold On) الانخفاض، الاحتماء تحت طاولة صلبة، والتمسك بها',
              'hintEn': 'Execute DROP, COVER, HOLD ON under sturdy desk; do NOT run outside during shaking',
              'safeTextAr': 'الانخفاض فوراً أرضاً، الاحتماء تحت طاولة صلبة، والتمسك بأرجلها (Drop, Cover, Hold On)',
              'safeTextEn': 'DROP to hands and knees, COVER head/neck under sturdy table, HOLD ON to table legs',
              'safeExpAr': 'استجابة عالمية ذهبية؛ الاحتماء تحت الطاولة يحميك من تساقط الأسقف والزجاج.',
              'safeExpEn': 'Universal golden safety rule; taking cover under sturdy desks protects head from falling debris.',
              'safeOutAr': 'احتميت تحت الطاولة للمحطة 2.',
              'safeOutEn': 'Protected under sturdy desk for Station 2.',
              'unsafeTextAr': 'الركض نحو الخارج والقفز عبر النوافذ أثناء اهتزاز الأرض',
              'unsafeTextEn': 'Run frantically outdoors while floor is violently shaking',
              'unsafeExpAr': 'خطأ قاتل؛ الركض أثناء الهزة يسبب اختلال التوازن والسقوط تحت الأنقاض.',
              'unsafeExpEn': 'Fatal error; running during seismic shaking causes falls & exposes you to falling facades.',
              'unsafeOutAr': 'سقطت أثناء الركض.',
              'unsafeOutEn': 'Knocked down while running.',
            },
            {
              'sitAr': 'توقفت الهزة الأرضية الرئيسية وحل الهدوء المؤقت. ما خطوة الإخلاء التالية؟',
              'sitEn': 'Main earthquake shaking stops. What is the immediate post-shake step?',
              'hintAr': 'الخروج بحذر عبر سلالم الطوارئ وتجنب استخدام المصاعد نهائياً',
              'hintEn': 'Evacuate carefully using emergency stairs; avoid elevators completely',
              'safeTextAr': 'الخروج بحذر وحماية الرأس باليدين واستخدام سلالم الطوارئ فقط دون المصاعد',
              'safeTextEn': 'Evacuate building carefully shielding head with arms, using stairwells strictly NO elevators',
              'safeExpAr': 'إجراء سليم؛ الهزات الارتدادية (Aftershocks) قد تقطع الكهرباء وتعطل المصاعد.',
              'safeExpEn': 'Correct evacuation step; seismic aftershocks disrupt electrical grid stalling elevators.',
              'safeOutAr': 'نزلت عبر الدرج بحذر للمحطة 3.',
              'safeOutEn': 'Evacuated via stairs for Station 3.',
              'unsafeTextAr': 'ركوب المصعد للنزول بسرعة قبل الهزة الارتدادية',
              'unsafeTextEn': 'Jump into elevator to ride down quickly before aftershock hits',
              'unsafeExpAr': 'خطأ؛ الهزات الارتدادية تعطل المصاعد وتحتجز الركاب داخل الشافت.',
              'unsafeExpEn': 'Error; aftershocks jam elevator guide rails trapping occupants between floors.',
              'unsafeOutAr': 'تعطل المصعد بك.',
              'unsafeOutEn': 'Elevator jammed during aftershock.',
            },
            {
              'sitAr': 'أثناء النزول بالشارع تساقطت زجاج المباني المجاورة. أين تقف في المنطقة المفتوحة؟',
              'sitEn': 'Stepping outside onto street; glass/facades falling from tall buildings. Safe area?',
              'hintAr': 'الابتعاد عن جدران المباني والأشجار وأعمدة الكهرباء والتجمع بالساحات المفتوحة',
              'hintEn': 'Move away from building facades, power lines, & trees into open field/plaza',
              'safeTextAr': 'الابتعاد عن واجهات المباني وأعمدة الكهرباء والتجمع في ساحة مفتوحة واسعة',
              'safeTextEn': 'Move away from building exterior walls & utility poles, assembling in open field or park',
              'safeExpAr': 'تأمين ممتاز؛ 80% من إصابات الزلازل الخفيفة تنتج عن تساقط الزجاج والواجهات بالشارع.',
              'safeExpEn': 'Great safety step; 80% of outdoor earthquake injuries occur from falling glass & brick facades.',
              'safeOutAr': 'وقفت بالساحة المفتوحة للمحطة 4.',
              'safeOutEn': 'Assembled in open plaza for Station 4.',
              'unsafeTextAr': 'الوقوف ملاصقاً لجدران المبنى العالي تحت النوافذ',
              'unsafeTextEn': 'Stand right against exterior wall under glass windows',
              'unsafeExpAr': 'خطأ؛ الوقوف تحت الواجهات يعرضك لدهس الزجاج المتساقط بالهزات الارتدادية.',
              'unsafeExpEn': 'Error; standing near exterior walls exposes body to falling glass and masonry rain.',
              'unsafeOutAr': 'تعرضت للزجاج المتساقط.',
              'unsafeOutEn': 'Struck by falling glass rain.',
            },
            {
              'sitAr': 'حدوث هزة ارتدادية (Aftershock) أثناء تواجدك بالساحة المفتوحة. ما التصرف؟',
              'sitEn': 'Aftershock hits while you are in open outdoor plaza. How to react?',
              'hintAr': 'الانخفاض أرضاً والثبات في المكان المفتوح لحين توقف الاهتزاز',
              'hintEn': 'Drop to ground in open space & hold position until shaking stops',
              'safeTextAr': 'الانخفاض على الأيدي والركبتين بالأرض المفتوحة والثبات حتى توقف الاهتزاز',
              'safeTextEn': 'Drop to hands & knees in open clear space, holding position until aftershock stops',
              'safeExpAr': 'تكتيك ثابت؛ الانخفاض يمنع اختلال التوازن والسقوط على الأرض.',
              'safeExpEn': 'Stable tactic; dropping to ground prevents being thrown off feet during ground acceleration.',
              'safeOutAr': 'ثبّت نفسك بالساحة للمحطة 5.',
              'safeOutEn': 'Held position outdoors for Station 5.',
              'unsafeTextAr': 'الركض والعودة داخل المبنى المتصدع',
              'unsafeTextEn': 'Run back inside cracked damaged building',
              'unsafeExpAr': 'خطأ؛ العودة للمباني المتصدعة أثناء الهزات الارتدادية يسبب الاحتجاز عند الانهيار.',
              'unsafeExpEn': 'Error; entering earthquake-damaged structures during aftershocks risks building collapse.',
              'unsafeOutAr': 'تعرضت لخطر تصدع المبنى.',
              'unsafeOutEn': 'Damaged building collapse risk.',
            },
            {
              'sitAr': 'انتهاء الهزات وسلامة الجميع. ما الفحص الوقائي للمنزل قبل إعادة الدخول؟',
              'sitEn': 'Shaking ends; all safe. Structural & utility home safety check before re-entry?',
              'hintAr': 'فحص تسرب الغاز، سلامة التوصيلات، وعدم وجود تصدعات هيكلية بالحران',
              'hintEn': 'Inspect for gas leaks, electrical shorts, & severe structural wall cracks',
              'safeTextAr': 'فحص محبس الغاز والتأكد من عدم وجود تسرب غازي أو تصدعات مائلة بالجدران الحاملة',
              'safeTextEn': 'Inspect main gas valves for leaks, check electric breakers, & verify zero load-bearing wall cracks',
              'safeExpAr': 'إتمام كامل؛ الفحص الوقائي يمنع الحرائق الناتجة عن تسرب الغاز بعد الزلازل.',
              'safeExpEn': 'Complete resolution; utility inspection prevents secondary post-earthquake gas fires.',
              'safeOutAr': 'أكملت محطات الوقاية من الهزات بنجاح!',
              'safeOutEn': 'Successfully completed earthquake safety scenario!',
              'unsafeTextAr': 'إشعال ولاعة داخل الشقة فور العودة دون فحص الغاز',
              'unsafeTextEn': 'Strike a match/lighter inside home immediately upon re-entering',
              'unsafeExpAr': 'خطأ؛ تسرب الغاز الناتج عن انكسار الأنابيب قد ينفجر عند إشعال أي لهب.',
              'unsafeExpEn': 'Error; broken interior gas lines ignite instantly if open flames are struck.',
              'unsafeOutAr': 'تسببت في انفجار غاز.',
              'unsafeOutEn': 'Post-earthquake gas explosion.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_evacuation_9',
          categoryId: 'evacuation',
          titleAr: 'سقوط منصة أو جدار في تجمع جماهيري',
          titleEn: 'Stage Collapse & Mass Gathering Evacuation',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انهيار المنصات الجماهيرية والإخلاء الفوري.',
          descriptionEn: 'Interactive 5-station scenario for structural stage collapses at outdoor events.',
          difficulty: 'صعب',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
          stations: [
            {
              'sitAr': 'أثناء مهرجان جماهيري انهار جزء من المنصة وتسبب في هلع وتدافع الجمهور. ما أول حركة؟',
              'sitEn': 'Event stage structure collapses causing mass panic and crowd surge. Action?',
              'hintAr': 'الابتعاد الفوري عن منطقة أنقاض المنصة والتنقل نحو المساحات المكشوفة',
              'hintEn': 'Move away from collapsed stage rubble immediately toward open spaces',
              'safeTextAr': 'الابتعاد الفوري عن منطقة الأنقاض والأسلاك المقطوعة والتوجيه للمساحة المكشوفة',
              'safeTextEn': 'Evacuate immediately away from stage rubble & fallen electric cables toward open space',
              'safeExpAr': 'تصرف ممتاز؛ الابتعاد يجنبك خطر تساقط بقية السقالات المعدنية والشرر الكهربائي.',
              'safeExpEn': 'Excellent step; moving away avoids secondary scaffold collapses and live wire shocks.',
              'safeOutAr': 'ابتعدت عن الأنقاض للمحطة 2.',
              'safeOutEn': 'Evacuated clear of collapse zone for Station 2.',
              'unsafeTextAr': 'الاقتراب والوقوف أسفل السقالات المعدنية المترنحة',
              'unsafeTextEn': 'Stand directly under leaning damaged metal scaffolding to film video',
              'unsafeExpAr': 'خطأ؛ السقالات المترنحة قد تسقط وتسبب إصابات سحق قاتلة.',
              'unsafeExpEn': 'Error; leaning structural scaffolds can trigger secondary crushing collapses.',
              'unsafeOutAr': 'تعرضت لخطر السقالات.',
              'unsafeOutEn': 'Secondary scaffold collapse risk.',
            },
            {
              'sitAr': 'سقوط كابلات إضاءة المسرح المكهربة قرب الأرض. كيف تتفادى الصعق؟',
              'sitEn': 'Live stage lighting cables drop near ground. How to avoid electrocution?',
              'hintAr': 'عدم ملامسة المياه أو الكابلات والمشي بخطوات صغيرة متقاربة (Shuffle Step)',
              'hintEn': 'Do NOT touch metallic debris/water; shuffle feet together away from ground current',
              'safeTextAr': 'تجنب ملامسة الهياكل المعدنية والمشي بسحب القدمين المتقاربتين (Hop/Shuffle Step)',
              'safeTextEn': 'Avoid touching metal fences & shuffle feet together along ground away from live wire',
              'safeExpAr': 'تكتيك نجاة كهربائي؛ مشية الشفل تمنع وجود فرق جهد بين القدمين بالشرائح المكهربة.',
              'safeExpEn': 'Electric safety tactic; shuffling feet eliminates step potential voltage difference on wet ground.',
              'safeOutAr': 'تجنبت الجهد الكهربائي للمحطة 3.',
              'safeOutEn': 'Shuffled away from step potential for Station 3.',
              'unsafeTextAr': 'أخذ خطى واسعة وجري فوق الكابلات الملقاة بالماء',
              'unsafeTextEn': 'Take long running strides over wet ground near fallen power lines',
              'unsafeExpAr': 'خطأ؛ الخطوات الواسعة تخلق فرق جهد (Step Potential) يسبب الصعق بالجسد.',
              'unsafeExpEn': 'Error; wide strides create dangerous voltage gradient between feet causing electrocution.',
              'unsafeOutAr': 'تعرضت لفرق الجهد الصاعق.',
              'unsafeOutEn': 'Electrocuted by step potential gradient.',
            },
            {
              'sitAr': 'وجود مصابين محتجزين تحت قطع الخشب الخفيفة بالمنصة. كيف تساعدهم؟',
              'sitEn': 'Trapped victims under lightweight wooden stage debris. Safe aid action?',
              'hintAr': 'رفع الألواح الخفيفة بحذر وتجنب تحريك القطع المعدنية الهيكلية الثقيلة',
              'hintEn': 'Lift light wooden boards carefully; do NOT disturb heavy structural steel beams',
              'safeTextAr': 'رفع الألواح الخفيفة بحذر كفريق وتخليص المصابين دون مساس بالأعمدة الحديدية الثقيلة',
              'safeTextEn': 'Team-lift light wooden debris safely freeing trapped victims without shifting structural steel',
              'safeExpAr': 'إجراء إنقاذ محترف؛ رفع الأجزاء الخفيفة ينقذ الأرواح دون التسبب في تحريك الهيكل.',
              'safeExpEn': 'Pro rescue move; clearing light debris frees victims without triggering main beam shifts.',
              'safeOutAr': 'حررت المصابين للمحطة 4.',
              'safeOutEn': 'Freed trapped victims safely for Station 4.',
              'unsafeTextAr': 'سحب الأعمدة الحديدية الرئيسية المحملة بوزن المنصة',
              'unsafeTextEn': 'Yank heavy load-bearing steel support beams by hand',
              'unsafeExpAr': 'خطأ؛ سحب الأعمدة الحاملة يسبب انهيار كامل أجزاء المسرح المتبقية.',
              'unsafeExpEn': 'Error; pulling load-bearing steel beams triggers total structural failure.',
              'unsafeOutAr': 'تسببت بانهيار كلي.',
              'unsafeOutEn': 'Total structural collapse triggered.',
            },
            {
              'sitAr': 'الاتصال بالدفاع المدني (998) والهلال الأحمر (997). التفاصيل الميدانية؟',
              'sitEn': 'Calling Civil Defense (998) & Red Crescent (997). Field report data?',
              'hintAr': 'إعطاء موقع الفعالية، نوع الانهيار، عدد المصابين، ومسار وصول السيارات',
              'hintEn': 'State event location, collapse type, estimated casualties, & clear access route',
              'safeTextAr': 'تحديد موقع الفعالية، وإبلاغ 998 بانهيار منصة ووجود مصابين وتأمين مسار لدخول السيارات',
              'safeTextEn': 'Report event address to 998/997 specifying stage collapse, casualties, & cleared access lane',
              'safeExpAr': 'بلاغ موجه؛ فتح مسار لدخول سيارات الإسعاف يضمن الوصول السريع للموقع.',
              'safeExpEn': 'Targeted dispatch call; securing entry access lane allows heavy rescue rigs fast entry.',
              'safeOutAr': 'أبلغت 998 و997 للمحطة 5.',
              'safeOutEn': 'Reported clear route to 998/997 for Station 5.',
              'unsafeTextAr': 'تعطيل مدخل الفعالية بسف سيارات الجمهور',
              'unsafeTextEn': 'Park private cars blocking main event access gate',
              'unsafeExpAr': 'خطأ؛ إغلاق مدخل الفعالية بالسيارات يمنع دخول آليات الدفاع المدني.',
              'unsafeExpEn': 'Error; blocking main gate prevents heavy Civil Defense rescue trucks from entering.',
              'unsafeOutAr': 'انسدت بوابة الدخول.',
              'unsafeOutEn': 'Emergency gate blocked.',
            },
            {
              'sitAr': 'تثبيت الأنقاض ونقل المصابين. ما المعيار الوقائي في المنصات المؤقتة؟',
              'sitEn': 'Debris stabilized; victims cared for. Temporary stage safety standard?',
              'hintAr': 'اشتراط فحص الهيئة السعودية للمهندسين واعتماد الأوزان والمصادقة الأيمنية',
              'hintEn': 'Mandate structural engineering certification & load capacity limits for all stages',
              'safeTextAr': 'اشتراط شهادة سلامة إنشائية معتمدة واختبار الأحمال قبل تشغيل أي منصة جماهيرية',
              'safeTextEn': 'Mandate certified structural engineering inspections & load limit safety testing for all stages',
              'safeExpAr': 'إتمام كامل؛ الفحص الإنشائي المسبق يضمن تحمّل المنصات للرياح والاهتزاز الجماهيري.',
              'safeExpEn': 'Complete resolution; mandatory engineering structural checks prevent stage collapses 100%.',
              'safeOutAr': 'أكملت محطات نجاة انهيار المنصات بنجاح!',
              'safeOutEn': 'Successfully completed stage collapse scenario!',
              'unsafeTextAr': 'بناء منصات خشبية عشوائية دون دراسة أحمال أو تراخيص سلامة',
              'unsafeTextEn': 'Erect un-certified temporary wooden stages without engineering review',
              'unsafeExpAr': 'خطأ؛ البناء العشوائي يسبب انهيار المنصات عند تجمهر الجماهير عليها.',
              'unsafeExpEn': 'Error; un-certified stage construction leads to tragic structural collapses.',
              'unsafeOutAr': 'ظلت المنصات العشوائية خطيرة.',
              'unsafeOutEn': 'Uncertified stage hazard persisted.',
            },
          ],
        ),
      ];
}
