import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosCyber {
  static List<Scenario> get list => [
        // 1. Cyber Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_1',
          categoryId: 'cyber_safety',
          titleAr: 'رسائل الاحتيال البنكي والهندسة الاجتماعية (Phishing)',
          titleEn: 'SMS Phishing & Bank Fraud Social Engineering',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لكشف الروابط المشبوهة، حماية OTP، والبلاغ عبر 330330.',
          descriptionEn: 'Interactive 5-station scenario to detect phishing SMS, protect OTP, and report via 330330.',
          difficulty: 'متوسط',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'وصلتك رسالة نصية SMS تزعم إيقاف بطاقتك البنكية وتطلب النقر على رابط لتحديث البيانات. ما الإجراء؟',
              'sitEn': 'Received SMS claiming bank card suspended with link to update info. Immediate action?',
              'hintAr': 'تجاهل الرابط فوراً وعدم النقر عليه نهائياً، فالبنوك لا تطلب التحديث بروابط نصية',
              'hintEn': 'Ignore link completely; Saudi banks NEVER request personal info updates via SMS links',
              'safeTextAr': 'تجاهل الرابط وعدم النقر عليه، والتحقق عبر تطبيق البنك الرسمي أو الهاتف المصرفي المباشر',
              'safeTextEn': 'Ignore link and verify directly via official bank mobile app or official customer care phone line',
              'safeExpAr': 'تصرف أساسي؛ البنوك السعودية لا ترسل روابط لتحديث الحسابات عبر الرسائل النصية.',
              'safeExpEn': 'Primary defense; Saudi banks strictly never issue SMS web links for account verification.',
              'safeOutAr': 'تجاهلت الرابط المشبوه للمحطة 2.',
              'safeOutEn': 'Ignored suspicious SMS link for Station 2.',
              'unsafeTextAr': 'النقر فوراً على الرابط وتعبئة بيانات البطاقة والرمز السري',
              'unsafeTextEn': 'Click link immediately and fill in credit card number and PIN code',
              'unsafeExpAr': 'خطأ جسيم؛ الروابط المزيفة تسرق بيانات البطاقة وتفرغ الحساب البنكي.',
              'unsafeExpEn': 'Severe error; phishing sites steal full card credentials and drain bank funds.',
              'unsafeOutAr': 'سرقت بيانات البطاقة.',
              'unsafeOutEn': 'Card credentials stolen.',
            },
            {
              'sitAr': 'وردك اتصال هاتفي يدعي أنه موظف البنك ويطلب رمز التحقق (OTP) المرسل لجوالك لتأمين الحساب. ما ردك؟',
              'sitEn': 'Call from fake bank agent asking for your OTP code to secure account. Response?',
              'hintAr': 'حظر مشاركة رمز OTP مع أي شخص نهائياً وإغلاق المكالمة فوراً',
              'hintEn': 'STRICTLY NEVER share OTP codes with anyone; hang up call immediately',
              'safeTextAr': 'رفض مشاركة رمز OTP نهائياً، إغلاق المكالمة، والإبلاغ عن الرقم المشبوه',
              'safeTextEn': 'Refuse sharing OTP code, hang up immediately, and block the caller number',
              'safeExpAr': 'قاعدة أمان حاسمة؛ رمز OTP هو مفتاح دخول حسابك وموظف البنك لا يطلبه منك أبداً.',
              'safeExpEn': 'Critical security rule; OTP is your primary security key—bank staff will NEVER ask for it.',
              'safeOutAr': 'رفضت مشاركة OTP للمحطة 3.',
              'safeOutEn': 'Refused OTP disclosure for Station 3.',
              'unsafeTextAr': 'إملاء رمز OTP للمتصل لتحديث الحساب بسرعة',
              'unsafeTextEn': 'Read out OTP passcode aloud to caller to update account quickly',
              'unsafeExpAr': 'خطأ قاتل؛ إعطاء رمز OTP يتيح للمحتال إتمام عملية سحب الأموال فوراً.',
              'unsafeExpEn': 'Fatal mistake; sharing OTP authorizes fraudulent live money transfer instantly.',
              'unsafeOutAr': 'سُحبت الأموال من الحساب.',
              'unsafeOutEn': 'Funds fraudulently transferred.',
            },
            {
              'sitAr': 'كيف تقوم بالإبلاغ عن رسالة الاحتيال النصية في المملكة العربية السعودية؟',
              'sitEn': 'How to report phishing SMS in Kingdom of Saudi Arabia?',
              'hintAr': 'إعادة توجيه الرسالة النصية إلى الرقم المجاني الموحد 330330',
              'hintEn': 'Forward the spam SMS message to the national anti-phishing number 330330',
              'safeTextAr': 'إعادة توجيه نص الرسالة الاحتيالية مع رقم المحتال إلى الخدمة الوطنية (330330)',
              'safeTextEn': 'Forward phishing SMS message with caller number to Saudi short code 330330',
              'safeExpAr': 'إبلاغ احترافي؛ خدمة 330330 تتيح هيئة الاتصالات وتقنية المعلومات حظر رقم المحتال بالكامل.',
              'safeExpEn': 'Pro reporting; CST service 330330 blocks fraud caller numbers across national telecom networks.',
              'safeOutAr': 'أرسلت البلاغ لـ 330330 للمحطة 4.',
              'safeOutEn': 'Reported spam SMS to 330330 for Station 4.',
              'unsafeTextAr': 'مسح الرسالة دون الإبلاغ عنها أو إعادة توجيهها للأصدقاء',
              'unsafeTextEn': 'Delete SMS silently or forward to friends asking if it is real',
              'unsafeExpAr': 'خطأ؛ السكوت يتيح للمحتال استهداف ضحايا آخرين وإعادة الرسائل.',
              'unsafeExpEn': 'Error; failing to report allows scammers to continue targetting other victims.',
              'unsafeOutAr': 'استمر المحتال باستهداف الآخرين.',
              'unsafeOutEn': 'Scammer targeted more victims.',
            },
            {
              'sitAr': 'اكتشاف خصم مالي مشبوه من حسابه البنكي بالخطأ. ما الإجراء الفوري لإيقاف البطاقة؟',
              'sitEn': 'Noticing unauthorized debit on bank account. Immediate action to freeze card?',
              'hintAr': 'إيقاف البطاقة فوراً عبر تطبيق البنك البنكي أو الاتصال بالهاتف المصرفي',
              'hintEn': 'Freeze card instantly using bank app or official customer hotline',
              'safeTextAr': 'دخول تطبيق البنك وإيقاف البطاقة فوراً (Block Card) وإبلاغ عمليات البنك',
              'safeTextEn': 'Log into official bank app, instantly freeze/block card, and report fraud transaction',
              'safeExpAr': 'استجابة سريعة؛ حظر البطاقة يوقف المسح المالي الإضافي وتثبت مطالبة استرداد المبلغ.',
              'safeExpEn': 'Quick response; locking card halts further unauthorized transactions enabling chargeback dispute.',
              'safeOutAr': 'حظرت البطاقة البنكية للمحطة 5.',
              'safeOutEn': 'Blocked compromised card for Station 5.',
              'unsafeTextAr': 'الانتظار حتى الغد ورؤية هل ستتكرر السحوبات أم لا',
              'unsafeTextEn': 'Wait until tomorrow to see if more money gets deducted',
              'unsafeExpAr': 'خطأ؛ الانتظار يتيح للمخترق سحب كامل رصيد الحساب المتبقي.',
              'unsafeExpEn': 'Error; waiting gives fraudsters time to drain total remaining credit limits.',
              'unsafeOutAr': 'تكررت السحوبات المالية.',
              'unsafeOutEn': 'Further unauthorized debits occurred.',
            },
            {
              'sitAr': 'تأمين الحساب البنكي وتحديث بيانات الأمان. ما التوجيه الوقائي المعتمد؟',
              'sitEn': 'Securing banking access post-incident. Approved permanent security protocol?',
              'hintAr': 'تفعيل المصادقة الثنائية البيومترية وعدم حفظ كلمات السر بالمستعرضات العامة',
              'hintEn': 'Enable biometric 2FA logins & avoid saving banking passwords on web browsers',
              'safeTextAr': 'تفعيل الدخول البيومتري (بصمة الوجه/الإصبع) وتغيير كلمة المرور وتحديث تطبيق البنك',
              'safeTextEn': 'Enable biometric FaceID 2FA, update banking password, and use only official app',
              'safeExpAr': 'إتمام كامل؛ المصادقة البيومترية تمنع 99% من محاولات الدخول الخارجي.',
              'safeExpEn': 'Complete resolution; biometric 2FA effectively blocks 99% of unauthorized remote login attempts.',
              'safeOutAr': 'أكملت محطات الوقاية من الاحتيال البنكي بنجاح!',
              'safeOutEn': 'Successfully completed phishing & bank fraud safety scenario!',
              'unsafeTextAr': 'استخدام كلمة مرور سهلة مثل (123456) وكتابتها على ورقة بجانب الجهاز',
              'unsafeTextEn': 'Use weak password like "123456" and write it on note attached to device',
              'unsafeExpAr': 'خطأ؛ كلمات السر الضعيفة سهلة التخمين عبر الهجمات الآلية.',
              'unsafeExpEn': 'Error; weak passwords are brute-forced easily by automated hacking tools.',
              'unsafeOutAr': 'ضعف حماية كلمة المرور.',
              'unsafeOutEn': 'Weak password vulnerability persisted.',
            },
          ],
        ),

        // 2. Cyber Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_2',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين حسابات الواتساب والتليجرام من الاختراق',
          titleEn: 'WhatsApp & Messaging App Hijacking Prevention',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتفعيل التحقق بخطوتين وتأمين حسابات التواصل الاجتماعية.',
          descriptionEn: 'Interactive 5-station scenario to enable 2FA and prevent messaging app account takeover.',
          difficulty: 'سهل',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'ورود رسالة نصية تحتوي على رمز تفعيل الواتساب، يليها اتصل من صديق يطلب الرمز فجأة. ما الإجراء؟',
              'sitEn': 'Received SMS with WhatsApp verification code, then friend calls asking for it. Action?',
              'hintAr': 'رفض إعطاء رمز التفعيل نهائياً حتى لو كان الطلب من صديق مقرب',
              'hintEn': 'Refuse giving verification code; friend\'s account is likely hacked',
              'safeTextAr': 'رفض إعطاء رمز التفعيل والتواصل مع الصديق عبر اتصال مباشر للتحقق من اختراق حسابه',
              'safeTextEn': 'Refuse code disclosure, and call friend directly via phone call verifying if their account was stolen',
              'safeExpAr': 'تصرف ذكي؛ المخترقون يستخدمون حسابات الأصدقاء المخترقة للاستيلاء على حسابات جديدة.',
              'safeExpEn': 'Smart action; hackers use stolen friend accounts to socially engineer new contacts.',
              'safeOutAr': 'رفضت إعطاء رمز تفعيل الواتساب للمحطة 2.',
              'safeOutEn': 'Refused WhatsApp activation code for Station 2.',
              'unsafeTextAr': 'إرسال الرمز للصديق فوراً لمساعدته في تفعيل حسابه',
              'unsafeTextEn': 'Send code to friend instantly believing they need help unlocking account',
              'unsafeExpAr': 'خطأ جسيم؛ إرسال الرمز ينقل ملكية حساب الواتساب الخاص بك للمخترق فوراً.',
              'unsafeExpEn': 'Severe error; sending code transfers your WhatsApp account ownership to hacker instantly.',
              'unsafeOutAr': 'اخُترق حساب الواتساب.',
              'unsafeOutEn': 'WhatsApp account hijacked.',
            },
            {
              'sitAr': 'تفعيل ميزة التحقق بخطوتين (Two-Step Verification) بالواتساب. كيف تضبط الميزة؟',
              'sitEn': 'Enabling Two-Step Verification in WhatsApp settings. Correct setup?',
              'hintAr': 'الدخول للإعدادات > الحساب > التحقق بخطوتين وإدخال رمز PIN مكون من 6 أرقام مع بريد إلكتروني',
              'hintEn': 'Go to Settings > Account > Two-Step Verification, enter 6-digit PIN and recovery email',
              'safeTextAr': 'تفعيل التحقق بخطوتين، إنشاء رمز PIN مكون من 6 أرقام وربط بريد إلكتروني رسمي للاسترداد',
              'safeTextEn': 'Enable 2FA, set a secret 6-digit PIN, and link a recovery email address',
              'safeExpAr': 'إجراء أمان حاسم؛ رمز PIN يمنع أي شخص من تفعيل حسابك حتى لو امتلك شريحة SIM.',
              'safeExpEn': 'Critical step; 6-digit PIN prevents unauthorized activation even if SIM card is cloned.',
              'safeOutAr': 'فعلت التحقق بخطوتين للمحطة 3.',
              'safeOutEn': 'Enabled 2-Step Verification for Station 3.',
              'unsafeTextAr': 'إهمال تفعيل التحقق بخطوتين والاعتماد فقط على رمز الرسالة النصية',
              'unsafeTextEn': 'Ignore 2FA activation relying purely on standard SMS activation codes',
              'unsafeExpAr': 'خطأ؛ غياب 2FA يسهل سرقة الحساب عند اعتراض الرسائل النصية.',
              'unsafeExpEn': 'Error; lacking 2FA makes account vulnerable to SIM swapping and SMS interception.',
              'unsafeOutAr': 'غياب حماية 2FA.',
              'unsafeOutEn': 'Lacked 2FA protection.',
            },
            {
              'sitAr': 'فحص الأجهزة المرتبطة (Linked Devices) بالواتساب لتأكد من عدم وجود متجسس. كيف تفحص الحساب؟',
              'sitEn': 'Checking Linked Devices in WhatsApp to detect unauthorized web sessions. How to audit?',
              'hintAr': 'الدخول لقائمة "الأجهزة المرتبطة" وتسجيل الخروج من أي متصفح أو جهاز غير معروف',
              'hintEn': 'Go to "Linked Devices" menu and log out of all unrecognized browsers or sessions',
              'safeTextAr': 'مراجعة قائمة الأجهزة المرتبطة دورياً وضغط "تسجيل الخروج من كافة الأجهزة"',
              'safeTextEn': 'Audit Linked Devices section regularly and tap "Log out from all devices" if unknown sessions exist',
              'safeExpAr': 'فحص ممتاز؛ يقطع جلسات WhatsApp Web التي قد يكون المخترق فتحها عبر مسح Qr Code.',
              'safeExpEn': 'Great audit; revokes unauthorized WhatsApp Web browser sessions paired via QR code scanning.',
              'safeOutAr': 'أنهيت الجلسات المشبوهة للمحطة 4.',
              'safeOutEn': 'Revoked unrecognized linked sessions for Station 4.',
              'unsafeTextAr': 'ترك الجلسات القديمة المرتبطة بمتصفحات المقاهي العامة مفتوحة',
              'unsafeTextEn': 'Leave old sessions active on public internet café browsers',
              'unsafeExpAr': 'خطأ؛ الجلسات المفتوحة تتيح للآخرين قراءة رسائلك وصورك الخاصة.',
              'unsafeExpEn': 'Error; active open sessions allow unauthorized users to read private messages and media.',
              'unsafeOutAr': 'تسريب محادثات الحساب.',
              'unsafeOutEn': 'Private chat leak risk.',
            },
            {
              'sitAr': 'تعرض الحساب للاختناق الفعلي وسرقته. كيف تسترد حساب الواتساب بسرعة؟',
              'sitEn': 'Account hijacked. How to rapidly recover stolen WhatsApp account?',
              'hintAr': 'إعادة إعادة تحميل الواتساب وإدخال رقم جوالك وطلب رمز تفعيل جديد لإخراج المخترق',
              'hintEn': 'Reinstall WhatsApp, enter phone number, request new SMS code to log hacker out',
              'safeTextAr': 'إعادة تسجيل الدخول برقم جوالك، إدخال الرمز الجديد لإخراج المخترق فوراً وإبلاغ الدعم الفني',
              'safeTextEn': 'Re-register WhatsApp with phone number, enter fresh SMS code forcing hacker lockout, contact support',
              'safeExpAr': 'استرداد ناجح؛ تسجيل الدخول من جهازك الأصلي يلغي جلسة المخترق تلقائياً.',
              'safeExpEn': 'Successful recovery; registering phone number forces immediate session termination on hacker device.',
              'safeOutAr': 'استرددت حساب الواتساب للمحطة 5.',
              'safeOutEn': 'Recovered hijacked WhatsApp account for Station 5.',
              'unsafeTextAr': 'الاستسلام وإنشاء حساب برقم جديد دون محاولة استرداد القديم',
              'unsafeTextEn': 'Give up and buy a new SIM card without attempting account recovery',
              'unsafeExpAr': 'خطأ؛ ترك الحساب المنسحب يتيح للمخترق احتيال أصدقائك بلسانك.',
              'unsafeExpEn': 'Error; leaving compromised account active enables hacker to scam contacts using your identity.',
              'unsafeOutAr': 'احتيال الأصدقاء باسمك.',
              'unsafeOutEn': 'Hacker scammed friends in your name.',
            },
            {
              'sitAr': 'استعادة الحساب بالكامل وحمايته. ما التوجيه الأمني المستدام للتطبيقات؟',
              'sitEn': 'Account fully recovered and locked down. Sustainable messaging safety protocol?',
              'hintAr': 'تغليف جميع تطبيقات المراسلة بحماية البصمة البيومترية وعدم النقر على برامج التجسس',
              'hintEn': 'Enable App Lock with Biometrics on all messaging apps & avoid unofficial WhatsApp mods',
              'safeTextAr': 'تفعيل قفل التطبيق بالبصمة (App Lock) وتجنب استخدام نسخ الواتساب المعدلة غير الرسمية (Plus/Gold)',
              'safeTextEn': 'Enable app-level biometric lock and strictly avoid using modified third-party WhatsApp APKs (Plus/Gold)',
              'safeExpAr': 'إتمام كامل؛ تجنب النسخ المعدلة يمنع وجود أبواب خلفية (Backdoors) للتجسس.',
              'safeExpEn': 'Complete resolution; avoiding unofficial modded apps prevents malicious spyware backdoors.',
              'safeOutAr': 'أكملت محطات تأمين الواتساب والتليجرام بنجاح!',
              'safeOutEn': 'Successfully completed WhatsApp & messenger security scenario!',
              'unsafeTextAr': 'تحميل برامج واتساب معدلة (WhatsApp Gold) من روابط مجهولة',
              'unsafeTextEn': 'Download unofficial modified WhatsApp Gold APKs from untrusted web forums',
              'unsafeExpAr': 'خطأ؛ التطبيقات المعدلة تشتمل على برمجيات تجسس تسرق الرسائل وتخترق الجوال.',
              'unsafeExpEn': 'Error; modified APKs harbor embedded trojans spying on messages and contacts.',
              'unsafeOutAr': 'مخاطرة ببرمجيات التجسس.',
              'unsafeOutEn': 'Spyware trojan risk persisted.',
            },
          ],
        ),

        // Scenarios 3 to 9 for CYBER...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_3',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين كاميرات المراقبة المنزلية والشبكات',
          titleEn: 'Smart Home IoT Camera & Wi-Fi Security',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتغيير كلمة مرور الراوتر وتأمين الكاميرات الذكية.',
          descriptionEn: 'Interactive 5-station scenario for securing home Wi-Fi routers and IoT IP cameras.',
          difficulty: 'متوسط',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'تركيب كاميرات مراقبة منزلية (IP Cameras) جديدة بالمنزل. ما أول خطوة أمان حاسمة؟',
              'sitEn': 'Installing new smart home IP security cameras. Mandatory first security step?',
              'hintAr': 'تغيير كلمة المرور الافتراضية (admin/admin) فوراً بكلمة سر معقدة',
              'hintEn': 'Immediately change factory default admin password (admin/admin) to a strong unique passkey',
              'safeTextAr': 'تغيير اسم المستخدم وكلمة المرور الافتراضية للجهاز (Default Password) إلى كلمة مرور معقدة',
              'safeTextEn': 'Change default manufacturer admin login credentials immediately to a strong unique passphrase',
              'safeExpAr': 'تصرف أساسي؛ كلمات السر الافتراضية مكشوفة في محركات البحث وتتيح اختراق الكاميرا عالمياً.',
              'safeExpEn': 'Primary rule; default factory passwords are publicly indexed enabling automated global camera hijacking.',
              'safeOutAr': 'غيرت كلمة المرور الافتراضية للمحطة 2.',
              'safeOutEn': 'Changed default camera password for Station 2.',
              'unsafeTextAr': 'ترك كلمة المرور الافتراضية المصنعية كما هي دون تغيير',
              'unsafeTextEn': 'Keep factory default password "admin/12345" unchanged for convenience',
              'unsafeExpAr': 'خطأ جسيم؛ ترك الحساب المصنعي يتيح للمخترقين بث فيديو الكاميرا بالإنترنت.',
              'unsafeExpEn': 'Severe error; leaving default login active allows search bots to stream your home video online.',
              'unsafeOutAr': 'اختراق بث الكاميرات.',
              'unsafeOutEn': 'Camera live stream breached.',
            },
            {
              'sitAr': 'تأمين شبكة الواي فاي المنزلية (Wi-Fi Router). ما تشفير الأمان الأقوى الموصى به؟',
              'sitEn': 'Securing home Wi-Fi router network. Recommended strong encryption standard?',
              'hintAr': 'استخدام تشفير WPA3 أو WPA2-AES وتعطيل خاصية WPS القابلة للاختراق',
              'hintEn': 'Use WPA3 or WPA2-AES encryption and DISABLE vulnerable WPS push-button feature',
              'safeTextAr': 'اختيار تشفير WPA3/WPA2-Personal مع تعطيل ميزة WPS الضئيلة بالأمان بالراوتر',
              'safeTextEn': 'Select WPA3 or WPA2-AES Wi-Fi encryption standard and disable vulnerable WPS feature in router settings',
              'safeExpAr': 'إجراء ممتاز؛ تشفير WPA3 يمنع هجمات التخمين وتفكيك حزم البيانات اللاسلكية.',
              'safeExpEn': 'Excellent choice; WPA3/WPA2-AES encryption protects wireless data packets from offline dictionary attacks.',
              'safeOutAr': 'أمنت تشفير الراوتر وتعطيل WPS للمحطة 3.',
              'safeOutEn': 'Secured WPA3 & disabled WPS for Station 3.',
              'unsafeTextAr': 'استخدام تشفير WEP القديم وتفعيل ميزة WPS دائمًا',
              'unsafeTextEn': 'Use outdated WEP encryption and keep WPS button permanently enabled',
              'unsafeExpAr': 'خطأ؛ تشفير WEP يسهل كسر كلمته في دقائق عبر برامج الهاتف.',
              'unsafeExpEn': 'Error; legacy WEP encryption and active WPS are cracked within minutes using mobile apps.',
              'unsafeOutAr': 'سهولة اختراق الواي فاي.',
              'unsafeOutEn': 'Easy Wi-Fi network breach.',
            },
            {
              'sitAr': 'عزل أجهزة الكاميرات والـ IoT عن شبكة الأسرة الرئيسية. كيف تضبط شبكة الضيوف (Guest Network)؟',
              'sitEn': 'Isolating IoT cameras from main family computers. How to use Guest Network?',
              'hintAr': 'إنشاء شبكة ضيوف منفصلة لكاميرات المنزل لحماية أجهزة الكمبيوتر والجوالات',
              'hintEn': 'Create a separate isolated Guest Wi-Fi Network specifically for smart IoT devices',
              'safeTextAr': 'توصيل جميع كاميرات وأجهزة المنزل الذكية بشبكة ضيوف (Guest Network) منعدمة الاتصال بالأجهزة الرئيسية',
              'safeTextEn': 'Connect all IP cameras and smart IoT devices to an isolated Guest Wi-Fi Network VLAN',
              'safeExpAr': 'تكتيك احترافي؛ عزل الكاميرات يضمن عدم قدرة المخترق على الانتقال لحواسيب الأسرة.',
              'safeExpEn': 'Pro security architecture; IoT isolation prevents lateral network movement to family laptops if camera breached.',
              'safeOutAr': 'عزلت الكاميرات بشركة الضيوف للمحطة 4.',
              'safeOutEn': 'Isolated IoT devices on Guest Network for Station 4.',
              'unsafeTextAr': 'ربط جميع الكاميرات والكمبيوترات وأجهزة البنك بشركة واحدة مفتوحة',
              'unsafeTextEn': 'Connect all cameras, personal laptops, and banking phones to same flat network',
              'unsafeExpAr': 'خطأ؛ اختراق كاميرا واحدة يتيح للمخترق الوصول لبيانات الكمبيوتر المالي.',
              'unsafeExpEn': 'Error; breaching a single weak IoT camera grants access to rest of internal network.',
              'unsafeOutAr': 'انتقال الاختراق للكمبيوتر.',
              'unsafeOutEn': 'Lateral breach to family PC.',
            },
            {
              'sitAr': 'تحديث البرامج الثابتة (Firmware Update) للكاميرات والراوتر. ما أهمية ذلك؟',
              'sitEn': 'Updating camera and router Firmware. Why is this critical?',
              'hintAr': 'التحديث الدوري يغلق الثغرات الأمنية (Vulnerabilities) المعروضة للعلن',
              'hintEn': 'Regular firmware updates patch zero-day security vulnerabilities and exploits',
              'safeTextAr': 'تفعيل التحديث التلقائي للبرامج الثابتة (Firmware) للكاميرات والراوتر لترقيع الثغرات',
              'safeTextEn': 'Enable auto-updates or check monthly for camera and router Firmware patches to fix vulnerabilities',
              'safeExpAr': 'تأمين حاسم؛ التحديثات تسد الثغرات الأمنية التي يكتشفها الخبراء لمنع الاستغلال.',
              'safeExpEn': 'Critical step; firmware patches seal known exploits blocking automated botnet malware infection.',
              'safeOutAr': 'حدثت البرامج الثابتة للمحطة 5.',
              'safeOutEn': 'Applied firmware updates for Station 5.',
              'unsafeTextAr': 'إهمال التحديثات لمدة سنوات والعمل على إصدار قديم',
              'unsafeTextEn': 'Ignore firmware update prompts running 5-year-old factory code',
              'unsafeExpAr': 'خطأ؛ الأجهزة القديمة غير المحدثة تتحول لمنصات استهداف ضخمة.',
              'unsafeExpEn': 'Error; unpatched devices get recruited into malicious Mirai botnets automatically.',
              'unsafeOutAr': 'استغلال الثغرات القديمة.',
              'unsafeOutEn': 'Unpatched exploit vulnerability.',
            },
            {
              'sitAr': 'تأمين مشاهدة الكاميرات عبر الجوال من الخارج. ما الوسيلة الأكثر أماناً؟',
              'sitEn': 'Securing remote camera viewing from outside home. Safest connection method?',
              'hintAr': 'استخدام تطبيق معتمد يوفر التشفير من الطرفين وتفعيل 2FA لحساب الكاميرا',
              'hintEn': 'Use vendor app with end-to-end encryption & enable 2FA on camera cloud account',
              'safeTextAr': 'استخدام تطبيق الشركة المعتمد مع تفعيل المصادقة الثنائية (2FA) وتجنب فتح البورتات (Port Forwarding)',
              'safeTextEn': 'Use official camera app with 2FA enabled on cloud account; avoid raw router Port Forwarding',
              'safeExpAr': 'إتمام كامل؛ المصادقة الثنائية تمنع أي شخص من مشاهدة البث الحي للكاميرات حتى لو عرف الرقم.',
              'safeExpEn': 'Complete resolution; 2FA on cloud accounts prevents unauthorized live view even if login leaked.',
              'safeOutAr': 'أكملت محطات تأمين كاميرات المراقبة بنجاح!',
              'safeOutEn': 'Successfully completed smart camera & Wi-Fi security scenario!',
              'unsafeTextAr': 'فتح بورت مباشر بالراوتر (Port Forwarding 80) دون تشفير',
              'unsafeTextEn': 'Open unencrypted raw Port Forwarding (Port 80/8080) directly on router',
              'unsafeExpAr': 'خطأ؛ فتح البورتات ينشر الكاميرات علانية في محركات البحث.',
              'unsafeExpEn': 'Error; raw port forwarding exposes camera video streams directly to public internet crawlers.',
              'unsafeOutAr': 'انكشاف البث المباشر للعلن.',
              'unsafeOutEn': 'Public camera stream exposure risk.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_4',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين المعاملات والبطاقات البنكية الرقمية',
          titleEn: 'Digital Banking & Online Shopping Card Protection',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لاستخدام البطاقات الرقمية المؤقتة وتجنب متاجر الشراء المزيفة.',
          descriptionEn: 'Interactive 5-station scenario for virtual cards & safe online shopping.',
          difficulty: 'متوسط',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'الشراء من موقع تسوق إلكتروني جديد وغير معروف. ما نوع البطاقات الأفضل للاستخدام؟',
              'sitEn': 'Shopping online from a new unfamiliar e-commerce site. Best card type to use?',
              'hintAr': 'استخدام بطاقة مسبقة الدفع أو بطاقة رقمية مؤقتة (Virtual Card) مخصصة للشراء',
              'hintEn': 'Use a prepaid card or temporary disposable Virtual Card with set spending limits',
              'safeTextAr': 'استخدام بطاقة مسبقة الدفع (Prepaid) أو بطاقة رقمية مؤقتة بمبلغ مخصص للشراء فقط',
              'safeTextEn': 'Use a virtual disposable card or dedicated prepaid card funded ONLY with the exact purchase amount',
              'safeExpAr': 'تصرف آمن؛ البطاقة الرقمية تعزل حسابك البنكي الرئيسي وتمنع أي سحوبات غير مصرح بها.',
              'safeExpEn': 'Safe action; virtual prepaid cards isolate primary bank balance preventing recurring unauthorized charges.',
              'safeOutAr': 'استخدمت بطاقة رقمية مؤقتة للمحطة 2.',
              'safeOutEn': 'Used virtual card for Station 2.',
              'unsafeTextAr': 'إدخال بيانات بطاقة الراتب الحساب الرئيسي (Mada/Credit) المباشرة',
              'unsafeTextEn': 'Enter primary salary debit card (Mada) CVV details directly into unknown site',
              'unsafeExpAr': 'خطأ جسيم؛ تسريب بيانات بطاقة الحساب الرئيسي يتيح للموقع سحب كامل الرصيد.',
              'unsafeExpEn': 'Severe error; exposing primary debit card credentials risks total account balance draining.',
              'unsafeOutAr': 'مخاطرة ببطاقة الراتب.',
              'unsafeOutEn': 'Primary debit card credentials compromised.',
            },
            {
              'sitAr': 'فحص أمان موقع التسوق قبل إدخال بيانات الشراء. ما الرمز والشرط الواجب توفره؟',
              'sitEn': 'Auditing online store security before payment. Mandatory browser indicator & protocol?',
              'hintAr': 'وجود رمز القفل المغلق (https://) في بداية عنوان الموقع والتأكد من اسم النطاق',
              'hintEn': 'Check for secure padlock icon and https:// protocol prefix with exact official domain spelling',
              'safeTextAr': 'التأكد من وجود بروتوكول التشافير (https://) ورمز القفل وتدقيق حروف نطاق الموقع (Domain)',
              'safeTextEn': 'Verify presence of secure https:// prefix, locked padlock icon, and inspect domain spelling accuracy',
              'safeExpAr': 'فحص ممتاز؛ Https تشفر بياناتك أثناء انتقالها لمنع التجسس الإلكتروني.',
              'safeExpEn': 'Great check; HTTPS encrypts card details during transmission blocking man-in-the-middle sniffing.',
              'safeOutAr': 'تأكّدت من تشفير HTTPS للمحطة 3.',
              'safeOutEn': 'Verified HTTPS padlock for Station 3.',
              'unsafeTextAr': 'الشراء من موقع ينتهي بـ (http://) بدون قفل وبأسعار رخيصة غير منطقية',
              'unsafeTextEn': 'Shop on unencrypted http:// site lured by unrealistically cheap prices',
              'unsafeExpAr': 'خطأ؛ المواقع غير المشفرة تنقل بيانات البطاقة بنص مكشوف وتسهل السرقة.',
              'unsafeExpEn': 'Error; HTTP sites transmit credit card numbers in cleartext accessible to network attackers.',
              'unsafeOutAr': 'تسريب بيانات البطاقة بالنص.',
              'unsafeOutEn': 'Cleartext card data leak.',
            },
            {
              'sitAr': 'إتمام الشراء عبر شبكات الواي فاي العامة في المقاهي والمطارات. ما مدى أمان العملية؟',
              'sitEn': 'Completing online shopping payment while connected to public coffee shop Wi-Fi. Security assessment?',
              'hintAr': 'حظر الشراء عبر الواي فاي العام، أو استخدام شبكة البيانات الجوالة (4G/5G) / VPN',
              'hintEn': 'NEVER make financial transactions on open public Wi-Fi; use mobile cellular data (4G/5G)',
              'safeTextAr': 'فصل الواي فاي العام والتحول لاستخدام بيانات الجوال الشخصية (4G/5G) أو تشغيل VPN موثوق',
              'safeTextEn': 'Disconnect from public Wi-Fi and switch to personal cellular data (4G/5G) or secure VPN before paying',
              'safeExpAr': 'إجراء حكيم؛ شبكات الواي فاي العامة سهلة الاعتراض والتجسس (Man-in-the-Middle).',
              'safeExpEn': 'Wise step; open public Wi-Fi networks allow attackers to intercept financial traffic.',
              'safeOutAr': 'حولت لشريحة البيانات للمحطة 4.',
              'safeOutEn': 'Switched to cellular 5G data for Station 4.',
              'unsafeTextAr': 'إدخال أرقام الرمز السري والبطاقة أثناء التواجد على شبكة واي فاي مفتوحة',
              'unsafeTextEn': 'Enter credit card details and OTP while connected to unsecured open public hotspot',
              'unsafeExpAr': 'خطأ؛ شبكات المقاهي المفتوحة تتيح للمترصدين التقاط بياناتك المالية بسهولة.',
              'unsafeExpEn': 'Error; unsecured Wi-Fi hotspots invite malicious packet sniffing of sensitive payment data.',
              'unsafeOutAr': 'اعتراض الشبكة المفتوحة.',
              'unsafeOutEn': 'Public Wi-Fi packet sniffing risk.',
            },
            {
              'sitAr': 'استلام إشعار سداد عبر خاصية 3D Secure (رمز التحقق البنكي). ما الواجب قراءته قبل الموافقة؟',
              'sitEn': 'Receiving 3D Secure bank SMS approval code. What must you double-check before entering?',
              'hintAr': 'قراءة اسم المتاجر والمبلغ المالي المكتوب بنص رسالة الـ OTP بالتفصيل',
              'hintEn': 'Read merchant name and exact debit currency/amount inside OTP text message body',
              'safeTextAr': 'قراءة نص الرسالة وتدقيق اسم التاجر وقيمة المبلغ قبل إدخال رمز 3D Secure',
              'safeTextEn': 'Read full SMS text carefully, verifying merchant identity and exact currency amount before entering 3DS code',
              'safeExpAr': 'تدقيق احترافي؛ الرسالة تفصح عن التاجر الحقيقي وتمنع الموافقة على مبالغ مضاعفة.',
              'safeExpEn': 'Pro verification; 3DS SMS discloses actual merchant name and total charge stopping hidden overbilling.',
              'safeOutAr': 'دققت بيانات 3DS للمحطة 5.',
              'safeOutEn': 'Verified 3DS SMS transaction details for Station 5.',
              'unsafeTextAr': 'إدخال رمز التحقق فوراً دون قراءة اسم المتجر أو المبلغ',
              'unsafeTextEn': 'Enter 3DS approval code blindly without reading merchant name or currency amount',
              'unsafeExpAr': 'خطأ؛ قد تفاجأ بخصم بالدولار أو العملات الأجنبية بقيمة أعلى بكثير.',
              'unsafeExpEn': 'Error; blind authorization risks processing high foreign currency charges by rogue merchants.',
              'unsafeOutAr': 'سحب مبلغ مضاعف.',
              'unsafeOutEn': 'Excessive currency charge authorized.',
            },
            {
              'sitAr': 'تفعيل ميزات الأمان الدائمة بالبطاقة البنكية. ما الإعداد الذكي المستدام؟',
              'sitEn': 'Setting permanent card security controls in mobile bank app. Sustainable setup?',
              'hintAr': 'تحديد حد الشراء اليومي للبطاقة وتفعيل تنبيهات الرسائل النصية الفورية',
              'hintEn': 'Set daily e-commerce spending limits & enable instant SMS transaction notifications',
              'safeTextAr': 'تحديد حد يومي للشراء عبر الإنترنت، وتفعيل إشعارات السحب الفورية لكافة المعاملات',
              'safeTextEn': 'Set custom daily online transaction limits in bank app and enable instant push/SMS purchase alerts',
              'safeExpAr': 'إتمام كامل؛ الحد اليومي والإشعارات الفورية تضمن رصد أي سحب غير عادي في نفس الدقيقة.',
              'safeExpEn': 'Complete resolution; lower e-commerce limits and instant push alerts stop runaway fraudulent charges.',
              'safeOutAr': 'أكملت محطات تأمين المعاملات والبطاقات البنكية بنجاح!',
              'safeOutEn': 'Successfully completed digital card protection scenario!',
              'unsafeTextAr': 'ترك حد الشراء مفتوحاً برصيد البطاقة كاملاً وتعطيل إشعارات الرسائل',
              'unsafeTextEn': 'Leave daily e-commerce limit uncapped to total balance and turn off SMS alerts',
              'unsafeExpAr': 'خطأ؛ تعطيل الإشعارات يمنع رصد العمليات المشبوهة إلا بعد فوات الأوان.',
              'unsafeExpEn': 'Error; disabling alerts delays discovering fraudulent charges until account is empty.',
              'unsafeOutAr': 'غياب إشعارات السحب.',
              'unsafeOutEn': 'Disabled purchase notification risk.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_5',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين البريد الإلكتروني والحسابات الشخصية',
          titleEn: 'Email Account Security & Password Manager Protocol',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتأمين Gmail وOutlook باستخدام مدير كلمات المرور و2FA.',
          descriptionEn: 'Interactive 5-station scenario for securing primary email & password managers.',
          difficulty: 'متوسط',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'تأمين الحساب الرئيسي للبريد الإلكتروني (Gmail/Outlook). ما أهمية البريد الإلكتروني؟',
              'sitEn': 'Securing primary personal email account (Gmail/Outlook). Why is primary email critical?',
              'hintAr': 'البريد هو المفتاح لجميع حساباتك، فاختراقه يتيح استرداد وتغيير كلمات سر البنوك والتطبيقات',
              'hintEn': 'Primary email is the master key; compromise enables password resets across all linked services',
              'safeTextAr': 'تأمين البريد الإلكتروني بأقوى كلمة مرور وتفعيل المصادقة الثنائية (2FA) فوراً',
              'safeTextEn': 'Secure primary email with an exclusive strong passphrase and mandatory hardware/app 2FA',
              'safeExpAr': 'تصرف حاسم؛ البريد هو مركز التحكم، وتأمينه يحمي جميع خدماتك الإلكترونية المرتبطة.',
              'safeExpEn': 'Critical choice; primary email controls all password reset tokens—securing it protects entire identity.',
              'safeOutAr': 'أمنت البريد الإلكتروني الرئيسي للمحطة 2.',
              'safeOutEn': 'Secured main email account for Station 2.',
              'unsafeTextAr': 'استخدام كلمة مرور مكررة وموحدة للبريد ولجميع مواقع التواصل',
              'unsafeTextEn': 'Reuse same exact password across primary email, shopping sites, and social media',
              'unsafeExpAr': 'خطأ جسيم؛ تسريب كلمة السر بموقع واحد يفتح جميع حساباتك وبريدك للمخترق.',
              'unsafeExpEn': 'Severe error; password reuse means a single breach leaks master key to all online accounts.',
              'unsafeOutAr': 'تكرار كلمات المرور.',
              'unsafeOutEn': 'Password reuse vulnerability.',
            },
            {
              'sitAr': 'استخدام مدير كلمات المرور (Password Manager). ما فائدته الأمنية؟',
              'sitEn': 'Using a Password Manager app (1Password / Bitwarden). Security advantage?',
              'hintAr': 'توليد كلمات سر فريدة ومعقدة لكل موقع وتخزينها بتشفير عالي دون الحاجة لحفظها',
              'hintEn': 'Generates unique complex passwords per site storing them encrypted; you memorize only 1 Master key',
              'safeTextAr': 'استخدام برنامج مدير كلمات مرور موثوق لتوليد وحفظ كلمات سر معقدة ومستقلة لكل موقع',
              'safeTextEn': 'Adopt a trusted password manager (e.g., Bitwarden) to generate and vault unique 16+ char passwords',
              'safeExpAr': 'إجراء ممتاز؛ مدير كلمات المرور يلغي تكرار كلمات السر ويحمي من المواقع المزيفة.',
              'safeExpEn': 'Great implementation; password managers eliminate reuse and resist phishing by auto-filling ONLY on real sites.',
              'safeOutAr': 'اعتمدت مدير كلمات المرور للمحطة 3.',
              'safeOutEn': 'Adopted password manager vault for Station 3.',
              'unsafeTextAr': 'كتابة كلمات المرور في مذكرة الجوال العادية أو على ورقة مكشوفة',
              'unsafeTextEn': 'Write down all banking & email passwords in unencrypted plain phone notes',
              'unsafeExpAr': 'خطأ؛ الملاحظات غير المشفرة تكون هدفا سهلاً للتطبيقات الخبيثة والسرقة الفيزيائية.',
              'unsafeExpEn': 'Error; plain unencrypted notes are easily scraped by malicious apps or physical snoopers.',
              'unsafeOutAr': 'كشف الملاحظات غير المشفرة.',
              'unsafeOutEn': 'Unencrypted notes data leak.',
            },
            {
              'sitAr': 'وصول رسالة تنبيه أمنية تزعم دخول شخص لحسابك من بلد آخر مع رابط تسجيل دخول. ما الحركة؟',
              'sitEn': 'Receiving email alert claiming login attempt from another country with verification link. Action?',
              'hintAr': 'عدم النقر على الرابط المرفق بالرسالة، والدخول المباشر لموقع البريد من المتصفح',
              'hintEn': 'Do NOT click email link; open browser independently and check official security activity page',
              'safeTextAr': 'فتح المتصفح بشكل مستقل والتأكد من قائمة "نشاط الأمان" داخل إعدادات الحساب الرسمية',
              'safeTextEn': 'Ignore link in email; open fresh browser tab, navigate directly to official provider security dashboard',
              'safeExpAr': 'تحقق آمن؛ الرسائل التنبيهية المزيفة هي أشهر أساليب الاصطياد الهيكلي (Spear Phishing).',
              'safeExpEn': 'Safe verification; fake security alert emails are a leading spear-phishing vector to steal credentials.',
              'safeOutAr': 'تحققت عبر التطبيق الرسمي للمحطة 4.',
              'safeOutEn': 'Checked via official security panel for Station 4.',
              'unsafeTextAr': 'النقر فوراً على رابط الرسالة وإدخال اسم المستخدم وكلمة السر',
              'unsafeTextEn': 'Click link inside email immediately and log in on page that pops up',
              'unsafeExpAr': 'خطأ؛ الصفحات المزيفة تسرق كلمة السر فور كتابتك لها بالحقول.',
              'unsafeExpEn': 'Error; fraudulent phishing page captures credentials instantly as you type them.',
              'unsafeOutAr': 'انكشاف كلمة السر بالصفحة المزيفة.',
              'unsafeOutEn': 'Phishing page credential theft.',
            },
            {
              'sitAr': 'استخدام تطبيق المصادقة (Authenticator App). لماذا هو أفضل من رسائل SMS؟',
              'sitEn': 'Using Authenticator Apps (Google/Microsoft Authenticator) vs SMS 2FA. Why is app 2FA better?',
              'hintAr': 'تطبيق المصادقة يولد رموزاً بالهاتف دون الحاجة للشبكة وهو محمي من هجمات شريحة SIM',
              'hintEn': 'Authenticator apps generate offline time-based codes (TOTP) immune to SIM-swapping hacks',
              'safeTextAr': 'اعتماد تطبيق المصادقة (Authenticator App) لتوليد رموز 2FA بدلاً من الرسائل النصية SMS',
              'safeTextEn': 'Configure time-based Authenticator app (TOTP) for 2FA instead of vulnerable SMS text messages',
              'safeExpAr': 'تأمين محترف؛ تطبيق المصادقة يعمل بدون شبكة ويحمي حسابك من هجمات استبدال الشرائح (SIM Swap).',
              'safeExpEn': 'Pro security step; TOTP apps generate local offline codes immune to cellular SIM swapping hijacks.',
              'safeOutAr': 'فعلت تطبيق Authenticator للمحطة 5.',
              'safeOutEn': 'Configured Authenticator app 2FA for Station 5.',
              'unsafeTextAr': 'تعطيل المصادقة الثنائية كلياً لتوفير الوقت أثناء الدخول',
              'unsafeTextEn': 'Turn off 2FA completely to save time when signing into email',
              'unsafeExpAr': 'خطأ؛ غياب المصادقة يجعل حسابك مكشوفاً فور تسرب كلمة السر.',
              'unsafeExpEn': 'Error; disabling 2FA leaves account completely exposed if password leaks anywhere.',
              'unsafeOutAr': 'غياب حماية المصادقة.',
              'unsafeOutEn': 'Disabled 2FA vulnerability.',
            },
            {
              'sitAr': 'حفظ رموز الاسترداد الاحتياطية (Backup Recovery Codes). ما الطريقة الآمنة لتخزينها؟',
              'sitEn': 'Saving offline 2FA Backup Recovery Codes. Safe storage method?',
              'hintAr': 'طباعة الرموز الاحتياطية وحفظها في خزنة آمنة مغلقة بالمنزل',
              'hintEn': 'Print emergency recovery codes and store paper copy in a secure home lockbox',
              'safeTextAr': 'طباعة رموز الاسترداد على ورقة وحفظها بمكان آمن مغلق، أو تشفيرها بمدير كلمات المرور',
              'safeTextEn': 'Print single-use 2FA recovery codes on paper storing in physical home safe or encrypted vault',
              'safeExpAr': 'إتمام كامل؛ الرموز الاحتياطية تضمن استعادة حسابك حتى لو ضاع هاتفك أو تغير رقمك.',
              'safeExpEn': 'Complete resolution; offline recovery codes guarantee emergency account rescue if phone is lost or damaged.',
              'safeOutAr': 'أكملت محطات تأمين البريد والحسابات الشخصية بنجاح!',
              'safeOutEn': 'Successfully completed email & account security scenario!',
              'unsafeTextAr': 'حفظ الرموز في لقطة شاشة (Screenshot) وتخزينها بالاستوديو العام',
              'unsafeTextEn': 'Take screenshot of recovery codes saving it in public photo gallery',
              'unsafeExpAr': 'خطأ؛ الصور بالاستوديو قد ترفع للخدمات السحابية وتتكشف للتطبيقات.',
              'unsafeExpEn': 'Error; unencrypted gallery screenshots sync to cloud apps exposing master recovery keys.',
              'unsafeOutAr': 'مخاطرة بصور الاستوديو.',
              'unsafeOutEn': 'Photo gallery recovery key leak.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_6',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين الأجهزة الذكية والألعاب من برمجيات الفدية (Ransomware)',
          titleEn: 'Ransomware & Malware Prevention on Devices & Gaming',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجنب الروابط المشبوهة للألعاب والفرار من تشفير الفدية.',
          descriptionEn: 'Interactive 5-station scenario for preventing ransomware & game mod malware.',
          difficulty: 'صعب',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'رغبة في تحميل لعبة أو تطبيق مدفوع مجاناً عبر رابط خارجي منسق في المنتديات. ما التقييم؟',
              'sitEn': 'Desire to download paid game or app for free via external forum link. Risk assessment?',
              'hintAr': 'حظر تحميل البرامج المقرصنة والـ Cracks، فهي المصدر الأول لبرمجيات الفدية (Ransomware)',
              'hintEn': 'NEVER download pirated software or cracks; primary vector for destructive Ransomware',
              'safeTextAr': 'التحميل حصرياً من المتاجر الرسمية (App Store / Google Play / Steam) وتجنب المقرصن',
              'safeTextEn': 'Download apps strictly from official curated app stores (App Store, Google Play, Steam)',
              'safeExpAr': 'تصرف آمن؛ البرامج المقرصنة تحتوي ملفات ضارة تشفر حاسوبك وتطالب بفدية مالية.',
              'safeExpEn': 'Safe action; cracked software carries embedded trojans that encrypt local files demanding ransom.',
              'safeOutAr': 'تجنبت البرامج المقرصنة للمحطة 2.',
              'safeOutEn': 'Avoided pirated crack files for Station 2.',
              'unsafeTextAr': 'تحميل ملف (Setup.exe) مجهول وتعطيل برنامج الحماية لتشغيله',
              'unsafeTextEn': 'Download unknown Setup.exe file and disable Antivirus to force execution',
              'unsafeExpAr': 'خطأ قاتل؛ تعطيل برنامج الحماية يتيح للفيروس تشفير جميع صورك وملفاتك.',
              'unsafeExpEn': 'Fatal error; disabling Antivirus allows ransomware to execute unhindered encrypting all drive data.',
              'unsafeOutAr': 'تشفير ملفات الحاسوب.',
              'unsafeOutEn': 'Drive files encrypted by ransomware.',
            },
            {
              'sitAr': 'أهمية النسخ الاحتياطي (Backup) للملفات والصور. ما هي قاعدة (3-2-1) للنسخ؟',
              'sitEn': 'Importance of data Backups. What is the standard 3-2-1 Backup rule?',
              'hintAr': 'حفظ 3 نسخ من البيانات، على نوعين مختلفين من وسائط التخزين، ونسخة واحدة خارج الموقع (Cloud)',
              'hintEn': 'Keep 3 copies of data, on 2 different media types, with 1 offsite encrypted cloud backup',
              'safeTextAr': 'تطبيق قاعدة (3-2-1): 3 نسخ من البيانات، 2 وسائط مختلفة (قرص خارجي + سحابة)، 1 خارج الموقع',
              'safeTextEn': 'Implement 3-2-1 backup rule: 3 total copies, 2 different media types (external drive + cloud), 1 offsite',
              'safeExpAr': 'تأمين بياني ممتاز؛ وجود النسخ الاحتياطية يضمن استعادة ملفاتك فوراً دون دفع أي فدية.',
              'safeExpEn': 'Great data defense; isolated backups guarantee 100% full file recovery without paying extortion ransoms.',
              'safeOutAr': 'طبقت قاعدة النسخ الاحتياطي 3-2-1 للمحطة 3.',
              'safeOutEn': 'Implemented 3-2-1 backup strategy for Station 3.',
              'unsafeTextAr': 'الاعتماد على القرص الصلب الداخلي نفسه دون أي نسخ إضافي',
              'unsafeTextEn': 'Rely solely on local internal C: drive with zero secondary backup copies',
              'unsafeExpAr': 'خطأ؛ تلف القرص أو تشفيره بالفدية يفقدك جميع ذكرياتك وملفاتك للأبد.',
              'unsafeExpEn': 'Error; drive failure or ransomware encryption permanently destroys all unbacked photos and work.',
              'unsafeOutAr': 'فقدان كلي للملفات.',
              'unsafeOutEn': 'Total unrecoverable file loss.',
            },
            {
              'sitAr': 'ظهور رسالة شاشة حمراء تدعي تشفير الملفات وتطلب تحويل بيتكوين لفك التشفير. ما الإجراء؟',
              'sitEn': 'Red ransom splash screen appears claiming files encrypted, demanding Bitcoin. Action?',
              'hintAr': 'فصل جهاز الكمبيوتر عن شبكة النت فوراً، وعدم دفع الفدية نهائياً',
              'hintEn': 'Isolate machine from network instantly; strictly NEVER pay extortion ransom',
              'safeTextAr': 'فصل سلك النت والواي فاي فوراً لمنع انتشار الفيروس لشبكة المنزل، وعدم دفع الفدية',
              'safeTextEn': 'Disconnect network cable/Wi-Fi immediately to isolate infection, refuse paying ransom, contact IT',
              'safeExpAr': 'استجابة سريعة؛ فصل النت يمنع الفيروس من تشفير باقي أجهزة الأسرة المربوطة بالشبكة.',
              'safeExpEn': 'Rapid containment; isolating network stops ransomware worm from spreading laterally to home devices.',
              'safeOutAr': 'عزلت الجهاز عن الشبكة للمحطة 4.',
              'safeOutEn': 'Isolated infected PC from network for Station 4.',
              'unsafeTextAr': 'تحويل المبالغ المطلوبة بالبيتكوين فوراً للمخترقين على أمل فك التشفير',
              'unsafeTextEn': 'Pay Bitcoin ransom immediately hoping hackers send decryption key',
              'unsafeExpAr': 'خطأ؛ دفع الفدية لا يضمن فك الملفات ويدعم الجريمة الإلكترونية.',
              'unsafeExpEn': 'Error; paying extortionists rarely yields decryption keys and funds international cybercrime.',
              'unsafeOutAr': 'خسارة الأموال دون فك التشفير.',
              'unsafeOutEn': 'Lost money without getting files back.',
            },
            {
              'sitAr': 'استخدام برامج الحماية من الفيروسات (Antivirus / EDR). ما الخيار الأفضل بالجهاز؟',
              'sitEn': 'Using Antivirus / Endpoint protection software. Recommended configuration?',
              'hintAr': 'إبقاء برنامج Windows Defender نشطاً وتفعيل ميزة الحماية الفورية والتحديث المستمر',
              'hintEn': 'Keep Windows Defender / anti-malware active with real-time cloud protection turned ON',
              'safeTextAr': 'تفعيل ميزة الحماية الفورية (Real-Time Protection) والحماية من الفدية في برامج الأمان',
              'safeTextEn': 'Maintain active Real-Time Protection & Ransomware Shield features in Windows Defender or premium AV',
              'safeExpAr': 'تأمين دائم؛ الحماية الفورية تفحص الملفات المحملة بالسلوك (Heuristics) قبل تشغيلها.',
              'safeExpEn': 'Continuous security; real-time heuristic scanning blocks malicious behavior before payload executes.',
              'safeOutAr': 'فعلت الحماية الفورية للمحطة 5.',
              'safeOutEn': 'Enabled real-time antivirus protection for Station 5.',
              'unsafeTextAr': 'إيقاف تشغيل برنامج الحماية بدعوى أنه يقلل سرعة الألعاب',
              'unsafeTextEn': 'Permanently disable Antivirus software claiming it slows down gaming FPS',
              'unsafeExpAr': 'خطأ؛ إيقاف برنامج الحماية يترك حاسوبك مكشوفاً لجميع البرمجيات الخبيثة.',
              'unsafeExpEn': 'Error; turning off security shields exposes system to instant drive-by downloads and rootkits.',
              'unsafeOutAr': 'تعطيل الحماية.',
              'unsafeOutEn': 'Disabled security shields risk.',
            },
            {
              'sitAr': 'الفحص والتعافي الكامل للحاسوب. ما التوجيه الوقائي المعتمد؟',
              'sitEn': 'System cleanup and recovery post-incident. Approved permanent security standard?',
              'hintAr': 'فرمتة الجهاز بالكامل وإعادة تثبيت النظام من مصدر رسمي واستعادة النسخة السحابية',
              'hintEn': 'Wipe drive, clean install OS from official media, restore files from clean offline backup',
              'safeTextAr': 'تهيئة الجهاز (Format)، إعادة تثبيت النظام من فلاش رسمي، واستعادة الملفات من النسخة السحابية',
              'safeTextEn': 'Perform clean OS reinstall from official USB installation media, then restore data from clean cloud backup',
              'safeExpAr': 'إتمام كامل؛ الفرمتة الكاملة هي الوسيلة الوحيدة لضمان اقتلاع جذور الفايروس والتجسس.',
              'safeExpEn': 'Complete resolution; full disk wipe guarantees complete eradication of persistent rootkit malware.',
              'safeOutAr': 'أكملت محطات الوقاية من برمجيات الفدية بنجاح!',
              'safeOutEn': 'Successfully completed ransomware prevention scenario!',
              'unsafeTextAr': 'مواصلة استخدام الجهاز المصاب بعد مسح ملف واحد فقط',
              'unsafeTextEn': 'Continue using infected computer after running a single quick scan',
              'unsafeExpAr': 'خطأ؛ برمجيات الفدية تترك أبواباً خلفية (Backdoors) تعيد الاختراق.',
              'unsafeExpEn': 'Error; advanced malware leaves persistent hidden backdoors reinfecting system later.',
              'unsafeOutAr': 'تجدد الخطر الباب الخلفي.',
              'unsafeOutEn': 'Persistent backdoor reinfection risk.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_7',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين المعاملات الحكومية والهوية الرقمية (نفاذ / أبشر)',
          titleEn: 'Digital Identity & Nafath / Absher Portal Security',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتأمين تطبيق نفاذ، حماية الهوية الرقمية، وتجنب الاحتيال.',
          descriptionEn: 'Interactive 5-station scenario for securing Saudi Nafath digital identity & Absher.',
          difficulty: 'متوسط',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'وردك طلب موافقة وتأكيد عبر تطبيق "نفاذ" (Nafath) برقم محدد دون أن تجري أي معاملة. ما الإجراء؟',
              'sitEn': 'Unsolicited Nafath authentication prompt with a number pops up without you making a request. Action?',
              'hintAr': 'رفض الطلب فوراً وعدم اختيار الرقم، فالطلب محاولة سرقة لهويتك الرقمية',
              'hintEn': 'REJECT prompt immediately; never tap matching number unless YOU initiated transaction',
              'safeTextAr': 'رفض الطلب فوراً وعدم اختيار الرقم المجهول، وتغيير كلمة مرور أبشر فوراً',
              'safeTextEn': 'Reject authentication prompt immediately, do NOT select matching number, and change Absher password',
              'safeExpAr': 'تصرف أساسي؛ طلبات نفاذ المفاجئة تعني أن هناك شخصاً يحاول الدخول باسمك لهيئة رسمية.',
              'safeExpEn': 'Primary rule; unexpected Nafath prompts indicate an attacker attempting to impersonate your identity.',
              'safeOutAr': 'رفضت طلب نفاذ المشبوه للمحطة 2.',
              'safeOutEn': 'Rejected suspicious Nafath prompt for Station 2.',
              'unsafeTextAr': 'ضغط الرقم الظاهر بالشاشة للموافقة بسرعة والتخلص من التنبيه',
              'unsafeTextEn': 'Tap matching number displayed on phone to approve request and clear notification',
              'unsafeExpAr': 'خطأ جسيم؛ اختيار الرقم يمنح المخترق صلاحية كاملة باسم هويتك الرقمية.',
              'unsafeExpEn': 'Severe error; approving prompt grants fraudster full authorized legal control of your identity.',
              'unsafeOutAr': 'اختراق الهوية الوطنية الرقمية.',
              'unsafeOutEn': 'Digital national ID compromised.',
            },
            {
              'sitAr': 'تأمين حساب أبشر (Absher). ما أهمية عدم مشاركة كلمة السر أو كلمة المرور مع أحد؟',
              'sitEn': 'Securing Absher portal account. Why is sharing credentials strictly prohibited?',
              'hintAr': 'حساب أبشر يمثل هويتك الرسمية، ومشاركة البيانات تتيح إصدار وكالات ونقل ملكيات',
              'hintEn': 'Absher is your legal digital self; credentials authorize POAs, vehicle transfers, and visas',
              'safeTextAr': 'الحفاظ على سرية كلمة سر أبشر نهائياً وعدم إعطائها لمكاتب الخدمات العامة',
              'safeTextEn': 'Keep Absher credentials strictly confidential; NEVER share login info with public service offices',
              'safeExpAr': 'إجراء حاسم؛ إعطاء بيانات أبشر لمكاتب الخدمات يتيح لهم إجراء معاملات باسمك القانوني.',
              'safeExpEn': 'Critical step; sharing Absher login with service kiosks allows unauthorized legal transactions in your name.',
              'safeOutAr': 'حفظت سرية بيانات أبشر للمحطة 3.',
              'safeOutEn': 'Maintained Absher credentials confidentiality for Station 3.',
              'unsafeTextAr': 'إعطاء اسم المستخدم وكلمة السر لمكتب خدمات عامة لإنجاز معاملة',
              'unsafeTextEn': 'Give Absher username and password to a street public services shop to complete a form',
              'unsafeExpAr': 'خطأ؛ تسليم الحساب للغير يخل بالمسؤولية القانونية ويعرضك للمسائلة.',
              'unsafeExpEn': 'Error; delegating master credentials to third parties breaches legal identity responsibility.',
              'unsafeOutAr': 'استغلال الحساب القانوني.',
              'unsafeOutEn': 'Legal identity misuse risk.',
            },
            {
              'sitAr': 'تلقي رسالة تدعي وجود مخالفة مرورية أو بلاغ قضائي مع رابط سداد نصي. كيف تتحقق؟',
              'sitEn': 'SMS alleging traffic fine or judicial summons with payment link. How to verify safely?',
              'hintAr': 'الدخول المباشر لمنصة أبشر أو إيفاء (Efaa.sa) أو ناجز دون استخدام رابط الرسالة',
              'hintEn': 'Check directly on official platforms (Absher, Efaa.sa, Najiz.sa); NEVER use SMS link',
              'safeTextAr': 'الدخول المستقل لمنصة أبشر أو المنصة الوطنية للمخالفات (Efaa.sa) للتحقق من وجود المخالفة',
              'safeTextEn': 'Log into Absher app or official National Violations Platform (Efaa.sa) directly to verify claim',
              'safeExpAr': 'فحص ممتاز؛ المنصات الحكومية الرسمية توضح جميع الاستحقاقات المالية بدقة وتأمين.',
              'safeExpEn': 'Great check; official government portals list legitimate pending fines securely without fake links.',
              'safeOutAr': 'تحققت عبر منصة إيفاء الرسمية للمحطة 4.',
              'safeOutEn': 'Verified via official Efaa.sa portal for Station 4.',
              'unsafeTextAr': 'السداد السريع عبر الرابط المرفق بالرسالة النصية القادمة من رقم مجهول',
              'unsafeTextEn': 'Pay fine immediately through link provided in SMS sent from mobile number',
              'unsafeExpAr': 'خطأ؛ الروابط النصية للمخالفات المزيفة تستغل أسماء الجهات الحكومية لسرقة بطاقتك.',
              'unsafeExpEn': 'Error; fake traffic fine SMS links mimic official gateways to steal credit card data.',
              'unsafeOutAr': 'سرقة البطاقة برابط المخالفة المزيف.',
              'unsafeOutEn': 'Card stolen via fake fine link.',
            },
            {
              'sitAr': 'ربط رقم الجوال المسجل في أبشر. ما أهمية ملكية رقم الجوال باسمك الرسمي؟',
              'sitEn': 'Linking phone number in Absher. Why must registered mobile number be in your official ID name?',
              'hintAr': 'أن يكون رقم الجوال موثقاً بهويتك الوطنية لدى شركات الاتصالات لتلقي رسائل التحقق',
              'hintEn': 'Registered phone number MUST be officially ID-verified under your name at telecom providers',
              'safeTextAr': 'التأكد من أن رقم الجوال المسجل بأبشر ونفاذ موثق باسم هويتك الوطنية عبر تطبيق السجل التجاري/CST',
              'safeTextEn': 'Ensure registered mobile number in Absher is officially verified under your ID with telecom provider',
              'safeExpAr': 'تأمين رسمي؛ ملكية الرقم تضمن عدم فقدان الوصول لرسائل التحقق الحكومية عند نقل الرقم.',
              'safeExpEn': 'Official security; verified number ownership prevents losing access to mandatory 2FA codes.',
              'safeOutAr': 'تأكدت من توثيق رقم الجوال للمحطة 5.',
              'safeOutEn': 'Verified official phone number ownership for Station 5.',
              'unsafeTextAr': 'استخدام رقم جوال مسجل باسم شخص آخر أو عمالة سائبة',
              'unsafeTextEn': 'Use a SIM card registered under someone else\'s ID for government accounts',
              'unsafeExpAr': 'خطأ؛ قد يفقد الطرف الآخر الرقم أو يوقفه فيتوقف وصولك لجميع المعاملات الرسمية.',
              'unsafeExpEn': 'Error; original SIM owner can cancel or port number revoking your government access.',
              'unsafeOutAr': 'فقدان الوصول للخدمات الحكومية.',
              'unsafeOutEn': 'Lost access to government portals.',
            },
            {
              'sitAr': 'تأمين تطبيق نفاذ بالهاتف المحمول. ما الإعداد البايومتري الواجب تفعيله؟',
              'sitEn': 'Securing Mobile Nafath App. Mandatory biometric security setting?',
              'hintAr': 'تفعيل الدخول ببصمة الوجه/الإصبع وتطبيق قفل الشاشة المحكم للجوال',
              'hintEn': 'Enable FaceID/Fingerprint biometric app lock and secure main phone screen lock',
              'safeTextAr': 'تفعيل الدخول ببصمة الوجه (FaceID) داخل تطبيق نفاذ، وتأمين قفل شاشة الجوال برمز PIN قوي',
              'safeTextEn': 'Enable biometric authentication inside Nafath app and set a strong master phone lock screen PIN',
              'safeExpAr': 'إتمام كامل؛ قفل البصمة يمنع أي شخص يمسك جوالك من فتح تطبيق نفاذ وتأكيد الطلبات.',
              'safeExpEn': 'Complete resolution; biometric lock prevents physical phone snoopers from accessing active identity apps.',
              'safeOutAr': 'أكملت محطات تأمين المعاملات الحكومية والهوية الرقمية بنجاح!',
              'safeOutEn': 'Successfully completed digital identity & Nafath security scenario!',
              'unsafeTextAr': 'إلغاء قفل شاشة الجوال وترك تطبيق نفاذ مفتوحاً دون بصمة',
              'unsafeTextEn': 'Disable phone screen lock leaving Nafath app open without passcode',
              'unsafeExpAr': 'خطأ؛ فقدان الجوال يتيح لسارقه الدخول لجميع المنصات الحكومية.',
              'unsafeExpEn': 'Error; losing unlocked phone grants thief full immediate access to all national portals.',
              'unsafeOutAr': 'مخاطرة بضياع الجوال غير المقفل.',
              'unsafeOutEn': 'Unlocked phone loss risk persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_8',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين شبكات الواي فاي العامة والـ VPN',
          titleEn: 'Public Open Wi-Fi Security & VPN Usage Protocol',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجنب شبكات الواي فاي المزيفة بالمطارات واستخدام الـ VPN.',
          descriptionEn: 'Interactive 5-station scenario for public hotspot risks & VPN protection.',
          difficulty: 'سهل',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'التواجد بالمطار وملاحظة شبكة واي فاي مفتوحة بدون كلمة سر باسم (Free_Airport_WiFi). ما الإجراء؟',
              'sitEn': 'At airport noticing open unencrypted Wi-Fi named "Free_Airport_WiFi". Immediate step?',
              'hintAr': 'التأكد من اسم الشبكة الرسمية مع موظفي المطار أو استخدام شبكة الجوال 5G',
              'hintEn': 'Verify official network name with airport staff or use personal 5G cellular hotspot',
              'safeTextAr': 'تجنب الاتصال التلقائي بالشبكات المفتوحة، واستخدام بيانات الجوال 5G أو تشغيل VPN موثوق',
              'safeTextEn': 'Avoid auto-connecting to open Wi-Fi; use personal 5G data or turn ON trusted VPN before connecting',
              'safeExpAr': 'تصرف أساسي؛ الشبكات المفتوحة قد تكون شباك هجوم مزيفة (Evil Twin Attack) يزرعها المخترق.',
              'safeExpEn': 'Primary rule; open hotspots are often rogue "Evil Twin" honeypots deployed to trap victims.',
              'safeOutAr': 'تجنبت الاتصال بالواي فاي المفتوح للمحطة 2.',
              'safeOutEn': 'Avoided untrusted open Wi-Fi for Station 2.',
              'unsafeTextAr': 'الاتصال بالشبكة فوراً وتصفح حسابات البنك والتواصل',
              'unsafeTextEn': 'Connect to open Wi-Fi instantly and log into banking and social accounts',
              'unsafeExpAr': 'خطأ جسيم؛ شبكات Evil Twin تسجل جميع كلماتها المرورية المكتوبة من خلالها.',
              'unsafeExpEn': 'Severe error; rogue Wi-Fi access points capture all plaintext traffic and credentials entered.',
              'unsafeOutAr': 'تجسس على بيانات الاتصال.',
              'unsafeOutEn': 'Rogue Wi-Fi credential sniffing.',
            },
            {
              'sitAr': 'استخدام شبكة VPN عند اضطرارك للاتصال بالواي فاي العام. ما وظيفته الأمنية؟',
              'sitEn': 'Using a trusted Virtual Private Network (VPN) on public Wi-Fi. How does VPN protect you?',
              'hintAr': 'الـ VPN ينشئ نفقاً مشفراً (Encrypted Tunnel) يعزل بياناتك عن المتجسسين بالشبكة',
              'hintEn': 'VPN creates an Encrypted Tunnel shielding all data traffic from local network eavesdroppers',
              'safeTextAr': 'تشغيل تطبيق VPN معتمد لإنشاء نفق مشفر بين جهازك والخادم الخارجي لحماية بياناتك',
              'safeTextEn': 'Activate a reputable paid VPN service creating an end-to-end encrypted tunnel over public Wi-Fi',
              'safeExpAr': 'إجراء أمان ممتاز؛ التشفير عبر الـ VPN يجعل بياناتك عبارة عن رموز مبهمة لا يمكن فكها.',
              'safeExpEn': 'Great security; VPN encryption converts all network packets into unreadable ciphertext to snoopers.',
              'safeOutAr': 'شغّلت النفق المشفّر للـ VPN للمحطة 3.',
              'safeOutEn': 'Activated encrypted VPN tunnel for Station 3.',
              'unsafeTextAr': 'تحميل VPN مجاني مجهول يعرض إعلانات كثيفة ويطلب صلاحيات واسعة',
              'unsafeTextEn': 'Download a sketchy free VPN app with excessive ads requesting full device permissions',
              'unsafeExpAr': 'خطأ؛ التطبيقات المجانية المجهولة تبيع بيانات تصفحك للشركات الإعلانية.',
              'unsafeExpEn': 'Error; untrusted free VPN providers often log and monetize your private browsing data.',
              'unsafeOutAr': 'بيع البيانات للشركات الإعلانية.',
              'unsafeOutEn': 'Free VPN data harvesting risk.',
            },
            {
              'sitAr': 'تعطيل ميزة "الاتصال التلقائي بالشبكات المفتوحة" (Auto-Join) بالجوال. ما أهمية ذلك؟',
              'sitEn': 'Disabling "Auto-Join Open Networks" in phone Wi-Fi settings. Why is this critical?',
              'hintAr': 'منع الجوال من الاتصال بالشبكات غير الآمنة تلقائياً أثناء السير بالأماكن العامة',
              'hintEn': 'Prevents smartphone from automatically broadcasting and connecting to untrusted open hotspots',
              'safeTextAr': 'تعطيل خيار (Auto-Join / الاتصال التلقائي) للشبكات المفتوحة في إعدادات الواي فاي بالجوال',
              'safeTextEn': 'Disable "Auto-Join Open Networks" and "Ask to Join" in mobile Wi-Fi settings dashboard',
              'safeExpAr': 'فحص ذكي؛ يمنع هجمات انتحال اسم الشبكة حيث يتصل الجوال تلقائياً بأي شبكة تحمل نفش الاسم القديم.',
              'safeExpEn': 'Smart audit; disables automatic probing which rogue APs exploit to mimic previously saved network SSIDs.',
              'safeOutAr': 'عطلت الاتصال التلقائي للمحطة 4.',
              'safeOutEn': 'Disabled Wi-Fi Auto-Join for Station 4.',
              'unsafeTextAr': 'ترك خيار الاتصال التلقائي مفعلاً لجميع الشبكات العامة',
              'unsafeTextEn': 'Leave Auto-Connect enabled for all public hotspots continuously',
              'unsafeExpAr': 'خطأ؛ يتصل جوالك بالشبكات الخبيثة دون علمك أثناء مشيك بالمجمعات.',
              'unsafeExpEn': 'Error; phone connects silently to malicious hotspots as you walk through public venues.',
              'unsafeOutAr': 'اتصال تلقائي بشبكة خبيثة.',
              'unsafeOutEn': 'Silent rogue hotspot connection.',
            },
            {
              'sitAr': 'مشاركة نقطة الاتصال الشخصية (Personal Hotspot) من جوالك لأجهزتك الأخرى. كيف تؤمنها؟',
              'sitEn': 'Sharing Personal Hotspot from your phone to your laptop. How to secure it?',
              'hintAr': 'وضع كلمة مرور قوية لنقطة الاتصال وتغيير الاسم الافتراضي للجوال',
              'hintEn': 'Set a complex WPA2/WPA3 password and change default broadcast device name',
              'safeTextAr': 'تثبيت كلمة مرور معقدة لنقطة الاتصال الشخصية وتفعيل التشفير وتغيير اسم الجوال الظاهر',
              'safeTextEn': 'Set a strong WPA3 passphrase for Personal Hotspot and change default broadcast SSID name',
              'safeExpAr': 'تأمين محترف؛ يمنع المتواجدين بالقرب منك من استغلال باقتك الجوالة أو التجسس على الأجهزة المربوطة.',
              'safeExpEn': 'Pro security; strong hotspot passkeys stop nearby snoopers from piggybacking on your mobile data.',
              'safeOutAr': 'أمنت نقطة الاتصال الشخصية للمحطة 5.',
              'safeOutEn': 'Secured Personal Hotspot password for Station 5.',
              'unsafeTextAr': 'ترك نقطة الاتصال بدون كلمة سر (Open Hotspot) ليتصل بها الجميع',
              'unsafeTextEn': 'Leave Personal Hotspot unencrypted without password so anyone can join',
              'unsafeExpAr': 'خطأ؛ تسمح للآخرين باستهلاك باقتك والتجسس على حركة البيانات.',
              'unsafeExpEn': 'Error; open hotspots drain your data quota and expose connected laptop traffic to strangers.',
              'unsafeOutAr': 'استغلال باقة البيانات.',
              'unsafeOutEn': 'Hotspot data piggybacking risk.',
            },
            {
              'sitAr': 'إتمام جولة الأمان اللاسلكي. ما التوجيه الوقائي النهائي لشبكات الأماكن العامة؟',
              'sitEn': 'Wrapping up wireless security. Permanent rule for public network hygiene?',
              'hintAr': 'إغلاق مفتاح الواي فاي والبلوتوث كلياً عند الخروج بالشارع أو الأماكن العامة',
              'hintEn': 'Turn OFF Wi-Fi and Bluetooth toggles completely when out in public spaces',
              'safeTextAr': 'إطفاء مفاتيح Wi-Fi و Bluetooth بالجوال كلياً عند التواجد بالخارج وعدم الحاجة إليها',
              'safeTextEn': 'Toggle OFF Wi-Fi and Bluetooth switches completely when traveling in public areas when not in use',
              'safeExpAr': 'إتمام كامل؛ إغلاق الـ Wi-Fi يمنع الجوال من إرسال إشارات التتبع الحركي (Probe Requests).',
              'safeExpEn': 'Complete resolution; disabling Wi-Fi stops device from continuously broadcasting tracking probe requests.',
              'safeOutAr': 'أكملت محطات تأمين شبكات الواي فاي العامة بنجاح!',
              'safeOutEn': 'Successfully completed public Wi-Fi & VPN safety scenario!',
              'unsafeTextAr': 'ترك الواي فاي والبلوتوث يعملان طوال اليوم بالأسواق والمطارات',
              'unsafeTextEn': 'Leave Wi-Fi and Bluetooth toggled ON all day while walking through malls',
              'unsafeExpAr': 'خطأ؛ إبقاء المفاتيح مفعّلة يتيح لأجهزة التتبع رصد موقعك الحركي بالمنطقة.',
              'unsafeExpEn': 'Error; active Wi-Fi/BT continuously broadcasts unique MAC addresses allowing physical tracking.',
              'unsafeOutAr': 'مخاطرة بالتعقب الحركي.',
              'unsafeOutEn': 'Location tracking probe risk persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_cyber_9',
          categoryId: 'cyber_safety',
          titleAr: 'تأمين المعاملات والعملات الرقمية (Crypto & Wallet Safety)',
          titleEn: 'Cryptocurrency Wallet & Web3 Cyber Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لحماية المحافظ الرقمية، عبارة الاسترداد، وتجنب العقود الخبيثة.',
          descriptionEn: 'Interactive 5-station scenario for crypto wallet security & Seed Phrase protection.',
          difficulty: 'صعب',
          icon: 'security',
          colorHex: 0xFF6366F1,
          stations: [
            {
              'sitAr': 'إنشاء محفظة رقمية جديدة للعملات (MetaMask / Trust Wallet). كيف تحفظ عبارة الاسترداد (Seed Phrase)؟',
              'sitEn': 'Setting up new Web3 crypto wallet. How to store the 12/24-word Seed Phrase?',
              'hintAr': 'كتابة الأرقام والكلمات على ورقة جافة وحفظها بمكان آمن مغلق، وعدم حفظها إلكترونياً',
              'hintEn': 'Write 12-word seed phrase on paper/metal offline; NEVER store in screenshots or text files',
              'safeTextAr': 'كتابة الكلمات الـ 12 بخط اليد على ورقة وحفظها في خزنة آمنة وحظر تصويرها أو حفظها بالنت',
              'safeTextEn': 'Write the 12/24 words on physical paper or engraved metal plate, storing offline in a safe; NEVER type online',
              'safeExpAr': 'تصرف أساسي؛ عبارة الاسترداد هي مفتاح المحفظة، وحفظها أوفلاين يمنع سرقة أصولك الرقمية.',
              'safeExpEn': 'Primary rule; seed phrase is master private key—keeping it 100% offline prevents remote wallet draining.',
              'safeOutAr': 'حفظت عبارة الاسترداد ورقية أوفلاين للمحطة 2.',
              'safeOutEn': 'Stored Seed Phrase offline for Station 2.',
              'unsafeTextAr': 'التقاط صورة لقطة شاشة للكلمات وحفظها في الملاحظات أو إرسالها بالواتساب',
              'unsafeTextEn': 'Take screenshot of seed phrase saving to cloud photos or emailing it to yourself',
              'unsafeExpAr': 'خطأ قاتل؛ حفظ الكلمات إلكترونياً يتيح لتطبيقات التجسس سرقة المحفظة وتفريغها.',
              'unsafeExpEn': 'Fatal error; electronic seed storage allows cloud breaches and malware to drain all crypto assets instantly.',
              'unsafeOutAr': 'سرقة محتويات المحفظة الرقمية.',
              'unsafeOutEn': 'Crypto wallet balance drained.',
            },
            {
              'sitAr': 'طلب موقع إلكتروني أو مشروع دروب (AirDrop) إدخال عبارة الاسترداد لاستلام مكافأة. ما الإجراء؟',
              'sitEn': 'AirDrop website asking to type in your Seed Phrase to claim free token reward. Action?',
              'hintAr': 'رفض الطلب فوراً، فالمشاريع الحقيقية لا تطلب عبارة الاسترداد الخاصة بك إطلاقاً',
              'hintEn': 'Refuse immediately; LEGITIMATE Web3 dApps NEVER ask for your Seed Phrase',
              'safeTextAr': 'إغلاق الموقع فوراً، عدم إدخال أي كلمات، فحظر أي موقع يطلب الكلمات مفتاح الأمان',
              'safeTextEn': 'Close website immediately; strictly NEVER enter seed phrase into any website prompt or form',
              'safeExpAr': 'إجراء حاسم؛ طلب عبارة الاسترداد هو احتيال مؤكد 100% لتفريغ رصيد المحفظة.',
              'safeExpEn': 'Critical step; any site prompting for seed phrase input is a 100% fraudulent wallet-draining scam.',
              'safeOutAr': 'أغلقت الموقع الاحتيالي للمحطة 3.',
              'safeOutEn': 'Closed fraudulent AirDrop site for Station 3.',
              'unsafeTextAr': 'كتابة الكلمات الـ 12 في خانات الموقع لاستلام الهدية المجانية',
              'unsafeTextEn': 'Type 12 seed words into website form to claim promised free crypto reward',
              'unsafeExpAr': 'خطأ؛ إدخال الكلمات يتيح للسكربت سحب جميع العملات بالثانية التالية.',
              'unsafeExpEn': 'Error; submitting seed phrase gives scam script full control transferring all assets immediately.',
              'unsafeOutAr': 'انتقلت الأصول للمحتال.',
              'unsafeOutEn': 'Assets transferred to scammer.',
            },
            {
              'sitAr': 'استخدام المحفظة الصلبة الفشارية (Hardware Cold Wallet like Ledger / Trezor). ما ميزتها؟',
              'sitEn': 'Using a Hardware Cold Wallet (Ledger/Trezor). What is its core security advantage?',
              'hintAr': 'المحفظة الباردة تعزل المفاتيح الخاصة أوفلاين تماماً وتتطلب ضغط زر فيزيائي للتأكيد',
              'hintEn': 'Hardware wallet isolates private keys offline; requires physical button press to sign transactions',
              'safeTextAr': 'اعتماد محفظة باردة (Hardware Wallet) توفر توقيع المعاملات بزر فيزيائي دون كشف المفاتيح',
              'safeTextEn': 'Adopt a hardware cold wallet (Ledger/Trezor) keeping private keys isolated offline with physical button verification',
              'safeExpAr': 'تأمين ممتاز؛ المحفظة الباردة تمنع الفيروسات بالكمبيوتر من التوقيع بالنيابة عنك.',
              'safeExpEn': 'Great protection; cold wallets isolate private keys so computer malware cannot sign transfers without physical button press.',
              'safeOutAr': 'اعتمدت المحفظة الباردة للمحطة 4.',
              'safeOutEn': 'Adopted Hardware Cold Wallet for Station 4.',
              'unsafeTextAr': 'الاعتماد الكلي على محافيظ المتصفح الساخنة (Hot Wallets) بمبالغ كبرى',
              'unsafeTextEn': 'Store life savings on browser extension hot wallets connected 24/7 to internet',
              'unsafeExpAr': 'خطأ؛ المحافظ الساخنة بالمتصفح تكون عرضة لثغرات المتصفح وسكربتات الخبث.',
              'unsafeExpEn': 'Error; hot browser wallets remain vulnerable to zero-day browser exploits and malicious extensions.',
              'unsafeOutAr': 'مخاطرة بالمحافظ الساخنة.',
              'unsafeOutEn': 'Hot browser wallet vulnerability.',
            },
            {
              'sitAr': 'فحص تصاريح العقود الذكية (Token Approvals / Revoke). كيف تلغي التصاريح القديمة؟',
              'sitEn': 'Auditing Web3 Token Approvals (Revoke.cash). How to revoke risky smart contract permissions?',
              'hintAr': 'استخدام موقع Revoke.cash لإلغاء تصاريح الوصول غير المحدودة للتطبيقات القديمة',
              'hintEn': 'Use Revoke.cash to audit and cancel unlimited token spending approvals given to old dApps',
              'safeTextAr': 'مراجعة التصاريح دورياً عبر موقع (Revoke.cash) وإلغاء تصاريح السحب غير المحدود (Unlimited Allowance)',
              'safeTextEn': 'Audit active approvals regularly on Revoke.cash and revoke unlimited spending allowances given to dApps',
              'safeExpAr': 'فحص محترف؛ إلغاء التصاريح يمنع العقود المخترقة مستقبلاً من سحب عملاتك.',
              'safeExpEn': 'Pro security habit; revoking allowances stops compromised smart contracts from draining tokens later.',
              'safeOutAr': 'ألغيت التصاريح غير المحدودة للمحطة 5.',
              'safeOutEn': 'Revoked unlimited token allowances for Station 5.',
              'unsafeTextAr': 'إعطاء تصريح سحب مفتوح (Unlimited Approval) لأي موقع جديد دون فحص',
              'unsafeTextEn': 'Grant unlimited spending approvals to newly launched unverified dApp contracts',
              'unsafeExpAr': 'خطأ؛ التصريح المفتوح يتيح للعقد سحب عملاتك في أي وقت حتى بعد سنين.',
              'unsafeExpEn': 'Error; unlimited approval grants smart contract permanent power to drain wallet tokens anytime.',
              'unsafeOutAr': 'تصريح مفتوح خطير.',
              'unsafeOutEn': 'Unlimited spending allowance risk.',
            },
            {
              'sitAr': 'إتمام إعدادات السلامة الرقمية للعملات. ما المعيار الوقائي الأهم للتداول؟',
              'sitEn': 'Completing Web3 safety suite setup. Final mandatory security guideline for digital assets?',
              'hintAr': 'فصل محفظة التداول اليومية عن محفظة الادخار الرئيسية الباردة',
              'hintEn': 'Separate daily burner wallet for dApp interactions from main long-term storage wallet',
              'safeTextAr': 'استخدام محفظة مؤقتة (Burner Wallet) للتفاعل مع المواقع الجديدة وعزل أصول الادخار بالمحفظة الباردة',
              'safeTextEn': 'Maintain a separate low-balance "burner wallet" for testing new dApps, keeping main savings isolated',
              'safeExpAr': 'إتمام كامل؛ عزل المحافظ يضمن عدم خسارة سوى الرصيد الضئيل بالمحفظة المؤقتة عند الخطأ.',
              'safeExpEn': 'Complete resolution; wallet compartmentalization limits total risk exposure to small burner balance if a dApp is malicious.',
              'safeOutAr': 'أكملت محطات تأمين المعاملات والعملات الرقمية بنجاح!',
              'safeOutEn': 'Successfully completed crypto wallet & Web3 safety scenario!',
              'unsafeTextAr': 'ربط محفظة الادخار الرئيسية بكل موقع أو لعبة جديدة تجدها بالإنترنت',
              'unsafeTextEn': 'Connect main long-term savings wallet to every new Web3 game or NFT mint site',
              'unsafeExpAr': 'خطأ؛ تعريض محفظة الادخار لمواقع جديدة يزيد احتمال الوقوع بفخ العقود الخبيثة.',
              'unsafeExpEn': 'Error; connecting primary savings wallet directly to untested Web3 dApps risks total asset loss.',
              'unsafeOutAr': 'مخاطرة بربط محفظة الادخار.',
              'unsafeOutEn': 'Main savings wallet exposure risk persisted.',
            },
          ],
        ),
      ];
}
