import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosHome {
  static List<Scenario> get list => [
        // 1. Home Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_1',
          categoryId: 'home',
          titleAr: 'تسرب الغاز وحرائق المنزل',
          titleEn: 'Household Gas Leak & Home Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تسرب الغاز، حرائق المنزل، وحماية الأسرة.',
          descriptionEn: 'Interactive 5-station scenario for gas leak containment and home safety.',
          difficulty: 'متوسط',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'عند عودتك للمنزل اشتممت رائحة غاز قوية جداً. ما تصرفك الأولي؟',
              'sitEn': 'Entering home, strong gas smell fills air. Initial response?',
              'hintAr': 'فتح الأبواب والنوافذ فوراً للتهوية وتجنب تشغيل أو إطفاء أي قاطع أو جرس كهربائي',
              'hintEn': 'Open windows/doors for cross-ventilation; NEVER flip electric light switches',
              'safeTextAr': 'فتح جميع النوافذ والأبواب للتهوية الفورية وعدم لمس أي قاطع كهربائي',
              'safeTextEn': 'Open all windows and doors for ventilation without touching light switches',
              'safeExpAr': 'وعي ممتاز؛ منع الشرر الكهربائي وتجديد الهواء يشتت تركيز الغاز الخطر.',
              'safeExpEn': 'Excellent awareness; avoiding sparks and ventilating clears explosive gas buildup.',
              'safeOutAr': 'شتت تركيز الغاز وانتقلت للمحطة 2.',
              'safeOutEn': 'Dissipated gas concentration for Station 2.',
              'unsafeTextAr': 'تشغيل أضواء المطبخ والشفاط لمعاينة مصدر الغاز',
              'unsafeTextEn': 'Turn on kitchen lights and exhaust hood to inspect gas leak',
              'unsafeExpAr': 'خطأ جسيم؛ تلامس المفتاح الكهربائي يولد شرارة ميكرونية تسبب انفجار الغاز.',
              'unsafeExpEn': 'Severe error; electrical arc inside wall switch detonates gas cloud.',
              'unsafeOutAr': 'تسببت في شرارة خطر بالمنزل.',
              'unsafeOutEn': 'Triggered immediate indoor explosion risk.',
            },
            {
              'sitAr': 'التوجه لمصدر التسرب في صمام الأسطوانة أو المحبس. كيف تؤمنه؟',
              'sitEn': 'Approaching leak source at cylinder valve or main pipe. Secure action?',
              'hintAr': 'إغلاق صمام محبس الغاز باتجاه عقارب الساعة بقوة وحبسه تماماً',
              'hintEn': 'Shut gas valve knob tightly clockwise to isolate gas flow',
              'safeTextAr': 'إغلاق المحبس الرئيسي أو صمام الأسطوانة باتجاه عقارب الساعة تماماً',
              'safeTextEn': 'Turn main valve or cylinder knob fully clockwise to shut off supply',
              'safeExpAr': 'إجراء حازم؛ قطع الإمداد يوقف استمرار تدفق الغاز للمطبخ.',
              'safeExpEn': 'Firm action; cutting supply halts continuous gas accumulation.',
              'safeOutAr': 'أغلقت مصدر الغاز للمحطة 3.',
              'safeOutEn': 'Isolated gas source for Station 3.',
              'unsafeTextAr': 'ترك الصمام مفتوحاً وضرب خرطوم الغاز بأداة حادة',
              'unsafeTextEn': 'Leave valve open and strike gas rubber hose with knife',
              'unsafeExpAr': 'خطأ؛ تمزيق الخرطوم يزيد التسرب ويضاعف الخطر.',
              'unsafeExpEn': 'Error; damaging gas hose amplifies leaks rapidly.',
              'unsafeOutAr': 'زاد معدل تسرب الغاز.',
              'unsafeOutEn': 'Accelerated gas leak rate.',
            },
            {
              'sitAr': 'فحص تسرب التوصيلات المطاطية بعد التهوية. ما الطريقة الآمنة للفحص؟',
              'sitEn': 'Checking rubber hose connections after airing out. Safe test method?',
              'hintAr': 'استخدام الرغوة الصابونية على التوصيلات؛ ظهور فقاعات يدل على موقع التسرب',
              'hintEn': 'Apply soapy water bubble solution to hose joints; bubbles indicate leak',
              'safeTextAr': 'دهن التوصيلات والخرطوم برغوة الماء والصابون ومراقبة تكون الفقاعات',
              'safeTextEn': 'Apply soapy water foam to joints and observe expanding bubbles',
              'safeExpAr': 'طريقة عالمية معتمدة؛ رغوة الصابون تكشف أدق الثقوب دون خطر اشتعال.',
              'safeExpEn': 'Certified safety method; soapy bubbles pinpoint micro-leaks without fire hazards.',
              'safeOutAr': 'حددت موقع التسرب بنجاح للمحطة 4.',
              'safeOutEn': 'Located leak accurately for Station 4.',
              'unsafeTextAr': 'تقريب شمعة أو عود ثقاب مشتعل لمعرفة مكان خروج الغاز',
              'unsafeTextEn': 'Hold open lit candle or matchstick near hose to test leak',
              'unsafeExpAr': 'خطأ قاتل؛ تقريب النار من تسرب الغاز يسبب اشتعالاً وانفجاراً حظياً.',
              'unsafeExpEn': 'Fatal mistake; bringing open flame to gas leak detonates vapor instantly.',
              'unsafeOutAr': 'تسببت في اشتعال غاز فوري.',
              'unsafeOutEn': 'Triggered immediate flash fire.',
            },
            {
              'sitAr': 'تعريض أحد أفراد الأسرة لدوار خفيف بسبب استنشاق الغاز. كيف تسعفه؟',
              'sitEn': 'Family member experiencing dizziness from gas inhalation. First aid act?',
              'hintAr': 'نقله فوراً للهواء الطلق خارج الشقة، ومساعدته على الاسترخاء والتنفس',
              'hintEn': 'Escort person to fresh outdoor air outside apartment, supporting deep breaths',
              'safeTextAr': 'مساعدة المصاب على الخروج للشرفة أو خارج الشقة للاستنشاق من الهواء النقيل',
              'safeTextEn': 'Guide victim out to balcony or hallway to breathe fresh outdoor air',
              'safeExpAr': 'إسعاف صحيح؛ الأكسجين النقيل يطرد غاز البوتان والميثان من الرئتين والدم.',
              'safeExpEn': 'Correct first aid; fresh oxygen clears inhaled butane/methane from bloodstream.',
              'safeOutAr': 'استعاد المصاب وعيه للمحطة 5.',
              'safeOutEn': 'Victim recovered fresh breathing for Station 5.',
              'unsafeTextAr': 'إجلاس المصاب داخل المطبخ المغلق وإعطائه طعاماً ثقيلاً',
              'unsafeTextEn': 'Sit victim inside closed kitchen feeding heavy meal',
              'unsafeExpAr': 'خطأ؛ البقاء في البيئة الملوثة يعمق حالات التسمم والاختناق.',
              'unsafeExpEn': 'Error; remaining in gas-filled space deepens hypoxia poisoning.',
              'unsafeOutAr': 'زاد دوار المصاب.',
              'unsafeOutEn': 'Hypoxia symptoms worsened.',
            },
            {
              'sitAr': 'صيانة التوصيلات واستبدال منظم الغاز (Regulator). ما معيار الأمان التام؟',
              'sitEn': 'Station 5: Maintenance and gas regulator replacement. Total home safety standard?',
              'hintAr': 'تركيب منظم غاز جديد ذو صمام أمان معتمد وتغيير الخرطوم كل سنتين',
              'hintEn': 'Install SASO certified auto-shutoff regulator and replace rubber hose every 2 years',
              'safeTextAr': 'تركيب منظم غاز ذكي معتمد بمواصفات SASO وفحص كاشف الغاز المنزلي',
              'safeTextEn': 'Install certified SASO safety regulator and check home gas detector alarm',
              'safeExpAr': 'وقاية مستدامة؛ المنظمات المعتمدة وكواشف الغاز تضمن سلامة المنزل طوال العام.',
              'safeExpEn': 'Sustainable protection; certified regulators and detectors secure home safety.',
              'safeOutAr': 'أكملت محطات سلامة المنزل والغاز بنجاح!',
              'safeOutEn': 'Successfully completed all 5 home gas safety stations!',
              'unsafeTextAr': 'ربط الخرطوم التالف بشريد لاصق ورقي دون استبداله',
              'unsafeTextEn': 'Wrap cracked old hose with paper tape without replacing component',
              'unsafeExpAr': 'خطأ خطير؛ الشريط الورقي لا يتحمل ضغط الغاز وسينفجر مجدداً.',
              'unsafeExpEn': 'Dangerous error; paper tape cannot withstand gas pressure leading to leaks.',
              'unsafeOutAr': 'ظلت الثغرة قائمة بالمنزل.',
              'unsafeOutEn': 'Hazardous gas leak remained unaddressed.',
            },
          ],
        ),

        // Scenarios 2 to 9 for HOME...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_2',
          categoryId: 'home',
          titleAr: 'تسمم طفل بمواد المنظفات المنزلية',
          titleEn: 'Child Household Chemical Ingestion Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع ابتلاع الأطفال للمنظفات أو الكيماويات.',
          descriptionEn: 'Interactive 5-station scenario for household detergent ingestion.',
          difficulty: 'صعب',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'شاهدت الطفل يحمل عبوة مبيض/منظف مفتوحة ويبكي مع وجود رغوة على فمه. ما أول حركة؟',
              'sitEn': 'Child found holding open bleach bottle crying with chemical foam around mouth. Action?',
              'hintAr': 'سحب عبوة المنظف فوراً ومسح الفم وتنظيف بقايا المادة بالماء',
              'hintEn': 'Take chemical bottle away immediately and wipe foam off lips',
              'safeTextAr': 'إبعاد عبوة المنظف فوراً، ومسح رغوة الفم بقماش رطب وتنظيف البصر',
              'safeTextEn': 'Remove chemical container immediately and wipe chemical foam off child lips',
              'safeExpAr': 'تصرف ممتاز؛ إبعاد المادة يمنع ابتلاع جرعات إضافية من المنظفات.',
              'safeExpEn': 'Excellent step; removing container prevents child from swallowing more toxic chemical.',
              'safeOutAr': 'أبعدت المنظف ونظفت الفم للمحطة 2.',
              'safeOutEn': 'Removed detergent and cleaned mouth for Station 2.',
              'unsafeTextAr': 'إرغام الطفل على التقيؤ فوراً بوضع الأصابع بالحلق',
              'unsafeTextEn': 'Force child to vomit immediately by sticking fingers down throat',
              'unsafeExpAr': 'خطأ خطير؛ إرغام التقيؤ في حالات المنظفات الكاوية يسبب كوي المريء مرتين.',
              'unsafeExpEn': 'Dangerous error; forcing vomiting of caustic cleaners re-burns esophagus during ascent.',
              'unsafeOutAr': 'تعرض المريء لكوي ثانٍ.',
              'unsafeOutEn': 'Esophagus re-burned by caustic acid.',
            },
            {
              'sitAr': 'الطفل واعي ومجاري التنفس مفتوحة. ما السائل الذي يعطى لتخفيف المادة الكاوية؟',
              'sitEn': 'Child conscious with open airway. What fluid to dilute ingested chemical?',
              'hintAr': 'إعطاء رشفات صغيرة من الماء أو الحليب لتخفيف تركيز المادة دون التقيؤ',
              'hintEn': 'Give small sips of plain water or milk to dilute chemical concentration',
              'safeTextAr': 'إعطاء الطفل رشفات صغيرة هادئة من الماء النقيل أو الحليب لتخفيف المادة الكاوية',
              'safeTextEn': 'Offer small calm sips of plain water or milk to dilute chemical strength in stomach',
              'safeExpAr': 'إجراء إسعافي سليم؛ التخفيف المائي يقلل التأثير الكاوي على جدار المعدة والمريء.',
              'safeExpEn': 'Correct first aid; water dilution lowers chemical acidity/alkalinity impact.',
              'safeOutAr': 'خففت المادة الكاوية للمحطة 3.',
              'safeOutEn': 'Diluted chemical with sips for Station 3.',
              'unsafeTextAr': 'إعطاء الطفل عصيراً حامضياً (ليمون/خل) لمعادلة المنظف',
              'unsafeTextEn': 'Feed child citrus lemon juice or vinegar to neutralize alkaline cleaner',
              'unsafeExpAr': 'خطأ؛ إعطاء أحماض قوية يسبب تفاعلاً حرارياً خطيراً داخل المعدة.',
              'unsafeExpEn': 'Error; mixing acids & bases in stomach causes dangerous exothermic heat reaction.',
              'unsafeOutAr': 'حدث تفاعل حراري بالمعدة.',
              'unsafeOutEn': 'Exothermic heat reaction in stomach.',
            },
            {
              'sitAr': 'الاتصال بمركز معلومات التسمم (937 وزارة الصحة) أو الهلال الأحمر (997). التفاصيل؟',
              'sitEn': 'Calling MOH Poison Control Center (937) or 997. Information required?',
              'hintAr': 'قراءة المكونات المكتوبة على عبوة المنظف وعمر الطفل والجرعة التقديرية',
              'hintEn': 'Read active ingredient label on chemical bottle, child age, and estimated intake',
              'safeTextAr': 'الاتصال بـ 937 وقراءة المكونات النشطة من العبوة للطييب وتحديد العمر والكمية',
              'safeTextEn': 'Call MOH 937 reading chemical ingredients off bottle label, stating child age & intake',
              'safeExpAr': 'بلاغ نموذجية؛ مركز التسمم 937 يوجه الترياق المضاد (Antidote) الخاص بكل مادة.',
              'safeExpEn': 'Model reporting; 937 poison specialists direct exact chemical antidote treatment.',
              'safeOutAr': 'أبلغت مركز التسمم 937 للمحطة 4.',
              'safeOutEn': 'Reported to 937 Poison Control for Station 4.',
              'unsafeTextAr': 'رمي عبوة المنظف بالقمامة والذهاب دون المعاينة',
              'unsafeTextEn': 'Throw chemical bottle in trash and head to hospital empty-handed',
              'unsafeExpAr': 'خطأ؛ رمي العبوة يحرم الأطباء من معرفة المركب الكيميائي الدقيق للتسمم.',
              'unsafeExpEn': 'Error; discarding bottle deprives ER doctors of exact chemical identification.',
              'unsafeOutAr': 'صعُب تشخيص المركب الكيميائي.',
              'unsafeOutEn': 'ER doctors lacked chemical ID.',
            },
            {
              'sitAr': 'نقل الطفل لطوارئ المستشفى. ما الشيء المهم إحضاره مع الطفل للطوارئ؟',
              'sitEn': 'Transporting child to ER. What vital item must accompany child to hospital?',
              'hintAr': 'إحضار عبوة المنظف نفسها المعنية بالحالة ليقرأها أطباء الطوارئ',
              'hintEn': 'Bring the exact chemical bottle with child to ER for toxicology review',
              'safeTextAr': 'إحضار عبوة المنظف الأصلية معكم لطوارئ المستشفى ليعاينها طبيب السموم',
              'safeTextEn': 'Bring original chemical bottle directly to ER toxicology department for review',
              'safeExpAr': 'تكتيك أنقذ حياة؛ إحضار العبوة يتيح بدء غسيل المعدة والترياق دون تأخير.',
              'safeExpEn': 'Lifesaving tactic; showing container enables instant antidote administration.',
              'safeOutAr': 'سلمت العبوة للأطباء للمحطة 5.',
              'safeOutEn': 'Handed container to ER docs for Station 5.',
              'unsafeTextAr': 'ترك العبوة في المنزل والاعتماد على الوصف الفهمي',
              'unsafeTextEn': 'Leave bottle at home relying on vague verbal description',
              'unsafeExpAr': 'خطأ؛ الوصف الشفهي المكتوب قد يتشابه بين المواد الحمضية والقلوية.',
              'unsafeExpEn': 'Error; vague verbal description delays specific toxicological antidote setup.',
              'unsafeOutAr': 'تأخر العلاج النوعي.',
              'unsafeOutEn': 'Toxicology antidote delayed.',
            },
            {
              'sitAr': 'علاج الطفل وسلامته. ما المعيار الوقائي المنزلي الدائم لحماية الأطفال؟',
              'sitEn': 'Child treated and healthy. Permanent home chemical safety standard?',
              'hintAr': 'حفظ جميع المنظفات والكيماويات في خزائن مرتفعة ومقفولة بقفل أمان للأطفال',
              'hintEn': 'Store all cleaners/chemicals in high cabinets locked with child-safety latches',
              'safeTextAr': 'تخزين المنظفات بالخزائن العلوية المرتفعة وتأمينها بأقفال أمان خاصة بالأطفال',
              'safeTextEn': 'Store all household cleaners in high wall cabinets secured with child safety locks',
              'safeExpAr': 'إتمام كامل؛ القفل العالي يمنع وصول الأطفال للمواد الخطرة بنسبة 100%.',
              'safeExpEn': 'Complete resolution; high locked cabinets completely eliminate child chemical access.',
              'safeOutAr': 'أكملت محطات علاج تسمم المنظفات بنجاح!',
              'safeOutEn': 'Successfully completed child chemical poisoning scenario!',
              'unsafeTextAr': 'حفظ المنظفات في قارورات المياه الغازية والعصير تحت المغسلة',
              'unsafeTextEn': 'Store bulk drain cleaner inside plastic water/juice bottles under sink',
              'unsafeExpAr': 'خطأ؛ حفظ الكيماويات في قارورات العصير يغري الأطفال بابتلاعها كشراب.',
              'unsafeExpEn': 'Error; storing toxic cleaners in beverage bottles tricks children into drinking them.',
              'unsafeOutAr': 'تسببت في إغراء الطفل بالشراب.',
              'unsafeOutEn': 'Re-exposed child to poison hazard.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_3',
          categoryId: 'home',
          titleAr: 'انسداد مجرى التنفس بالغصة لدى طفل',
          titleEn: 'Child Airway Choking Emergency (Heimlich)',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لإسعاف الغصة واختناق مجرى التنفس عند الأطفال.',
          descriptionEn: 'Interactive 5-station scenario for child choking and Heimlich maneuver.',
          difficulty: 'صعب',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'أثناء تناول الطعام ابتلع طفل قطعة لعبة صلبة واختنق صوته مع تحول وجهه للأزرق. ما الحركة؟',
              'sitEn': 'Child swallows toy object turning blue & unable to breathe/cough. Action?',
              'hintAr': 'التقييم السريع: إن كان لا يسعل ولا يتنفس يجب البدء فوراً بضربات الظهر والدفع',
              'hintEn': 'Quick check: if silent and blue, immediately start back blows & abdominal thrusts',
              'safeTextAr': 'التقييم السريع؛ تأكيد انسداد مجرى التنفس والمناداة على شخص للاتصال بـ (997)',
              'safeTextEn': 'Perform quick check; confirm total airway blockage & yell for helper to dial 997',
              'safeExpAr': 'استجابة ذهبية؛ التمييز بين السعال الجزئي والانسداد الكلي يحدد نوع الإسعاف.',
              'safeExpEn': 'Golden step; differentiating partial coughing from complete blockage dictates maneuver.',
              'safeOutAr': 'أكدت الانسداد وطلبت الإسعاف للمحطة 2.',
              'safeOutEn': 'Confirmed blockage & called 997 for Station 2.',
              'unsafeTextAr': 'إدخال أصابعك بالكامل داخل حلق الطفل بشكل عشوائي',
              'unsafeTextEn': 'Blindly jam your fingers deep into child throat searching for object',
              'unsafeExpAr': 'خطأ قاتل؛ الضغط العشوائي بالأصابع يدفع الجسم الغريب لعمق القصبة الهوائية.',
              'unsafeExpEn': 'Fatal error; blind finger sweeps push choking hazard deeper down trachea.',
              'unsafeOutAr': 'دفعت الجسم الغريب للداخل.',
              'unsafeOutEn': 'Pushed choking hazard deeper.',
            },
            {
              'sitAr': 'كيف تبدأ بضربات الظهر (Back Blows) لإخراج الجسم الخانق للطفل فوق سنة؟',
              'sitEn': 'How to perform back blows for choking child over 1 year old?',
              'hintAr': 'إمالة الطفل للأمام وجهه لأسفل وإعطاء 5 ضربات بين لوحي الكتف بكف اليد',
              'hintEn': 'Incline child forward face down and give 5 firm back blows between shoulder blades',
              'safeTextAr': 'إمالة جذر جسم الطفل للأمام وإعطاء 5 ضربات بين لوحي الكتف بكعب الكف',
              'safeTextEn': 'Lean child forward supporting chest and deliver 5 firm back blows between shoulder blades',
              'safeExpAr': 'تكتيك ممتاز؛ الجاذبية مع الضربات تساعد على زحزحة الجسم الغريب للخارج.',
              'safeExpEn': 'Great tactic; gravity combined with back blows dislodges foreign body.',
              'safeOutAr': 'أعطيت 5 ضربات ظهر للمحطة 3.',
              'safeOutEn': 'Delivered 5 back blows for Station 3.',
              'unsafeTextAr': 'ضرب الطفل وهو مستلقٍ على ظهره مستقيماً',
              'unsafeTextEn': 'Slap child back while child lies flat on back',
              'unsafeExpAr': 'خطأ؛ الضرب أثناء الاستلقاء على الظهر لا يستفيد من الجاذبية لإخراج الجسم.',
              'unsafeExpEn': 'Error; slapping while lying flat fails to use gravity to dislodge blockage.',
              'unsafeOutAr': 'لم يتزحزح الجسم الغريب.',
              'unsafeOutEn': 'Blockage un-moved.',
            },
            {
              'sitAr': 'إذا لم يخرج الجسم بضربات الظهر. كيف تطبق ضغطات البطن (Heimlich Maneuver)؟',
              'sitEn': 'If back blows fail. How to perform abdominal thrusts (Heimlich)?',
              'hintAr': 'الوقوف خلف الطفل، وضع قبضة اليد فوق السرة، والضغط للداخل ولأعلى 5 مرات',
              'hintEn': 'Stand behind child, place fist above navel, and press inward & upward 5 times',
              'safeTextAr': 'الوقوف خلف الطفل، وضع قبضة يدك بين السرة وصدره، والضغط للداخل ولأعلى 5 مرات',
              'safeTextEn': 'Stand behind child, position fist above navel below ribs, press inward and upward 5 times',
              'safeExpAr': 'مانورة هاالمليك الذهبية؛ ترفع ضغط الرئتين فجأة لطرد الجسم الغريب كالقذيفة.',
              'safeExpEn': 'Golden Heimlich maneuver; forces air up from lungs to pop out foreign object.',
              'safeOutAr': 'خرجت القطعة واستعاد التنفس للمحطة 4.',
              'safeOutEn': 'Object expelled; airway clear for Station 4.',
              'unsafeTextAr': 'الضغط على قفص الصدر السفلي بقوة شديدة يكسر أضلاعه',
              'unsafeTextEn': 'Squeeze lower ribcage violently with both arms',
              'unsafeExpAr': 'خطأ؛ الضغط العنيف على الأضلاع يسبب كسر القفص الصدري وتمزق الكبد.',
              'unsafeExpEn': 'Error; violent ribcage squeezing fractures ribs and risks liver laceration.',
              'unsafeOutAr': 'تسببت بكسر بالأضلاع.',
              'unsafeOutEn': 'Ribs fractured.',
            },
            {
              'sitAr': 'خرجت لعبة البلاستيك وبدأ الطفل بالسعال والتنفس. كيف تؤمن وضعيته بعد النجاة؟',
              'sitEn': 'Toy object pops out; child coughs and breathes. How to position post-choking?',
              'hintAr': 'إجلاس الطفل بهدوء وطمأنته ومراقبة تنفسه حتى وصول الإسعاف',
              'hintEn': 'Sit child upright comfortably, reassure them, monitor breathing until 997 arrives',
              'safeTextAr': 'إجلاس الطفل بوضعية مريحة وطمأنته ومتابعة انتظام تنفسه ولون شفتيه',
              'safeTextEn': 'Sit child upright in comfortable position, soothe them, and monitor lips color and breath',
              'safeExpAr': 'عناية بعد الإسعاف ممتازة؛ الاطمئنان يمنع الصدمة والهلع لدى الطفل.',
              'safeExpEn': 'Great post-event care; calming victim prevents panic hyperventilation.',
              'safeOutAr': 'طمأنت الطفل للمحطة 5.',
              'safeOutEn': 'Soothed child for Station 5.',
              'unsafeTextAr': 'إعطاء الطفل كاس ماء بارد يبلعه فجأة فور خروج القطعة',
              'unsafeTextEn': 'Force child to gulp down large glass of ice water immediately',
              'unsafeExpAr': 'خطأ؛ بلع الماء فجأة بعد الغصة يسبب التشرق والشرقة مجدداً.',
              'unsafeExpEn': 'Error; forcing immediate water gulping triggers secondary aspiration coughing.',
              'unsafeOutAr': 'تشرق الطفل بالماء.',
              'unsafeOutEn': 'Child choked on water.',
            },
            {
              'sitAr': 'وصول فرقة الهلال الأحمر (997). ما الفحص الطبي المطلوب للطفل؟',
              'sitEn': '997 Paramedics arrive. What medical exam is required post-Heimlich?',
              'hintAr': 'فحص القصبة الهوائية والصدر لتأكيد عدم وجود بقايا ولصيانة البطن',
              'hintEn': 'Examine lungs & trachea to confirm zero residual debris & check abdominal organs',
              'safeTextAr': 'إخضاع الطفل للفحص الطبي لدى المسعف للتحقق من سلامة الحلق والأعضاء الداخلية',
              'safeTextEn': 'Have 997 paramedics perform chest stethoscopy and abdominal palpation check',
              'safeExpAr': 'إتمام كامل؛ الفحص الطبي يؤكد عدم وجود أجزاء متبقية وعدم تضرر الكبد بالضغطات.',
              'safeExpEn': 'Complete resolution; medical triage rules out internal organ injury or residual choking.',
              'safeOutAr': 'أكملت محطات إسعاف الغصة بنجاح!',
              'safeOutEn': 'Successfully completed child choking scenario!',
              'unsafeTextAr': 'رفض الفحص الطبي ومغادرة الإسعاف فور خروج القطعة',
              'unsafeTextEn': 'Refuse paramedic evaluation sending ambulance away immediately',
              'unsafeExpAr': 'خطأ؛ قد تكون مناورة هاالمليك تسببت برضوض بطنية تستوجب التقييم.',
              'unsafeExpEn': 'Error; Heimlich abdominal thrusts require professional organ injury screening.',
              'unsafeOutAr': 'إغفال الفحص الطبي.',
              'unsafeOutEn': 'Skipped vital organ check.',
            },
          ],
        ),

        // Scenarios 4 to 9 for HOME...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_4',
          categoryId: 'home',
          titleAr: 'سقوط طفل من نافذة أو درابزين',
          titleEn: 'Child Window/Balcony Fall Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حوادث سقوط الأطفال وتثبيت الإصابات.',
          descriptionEn: 'Interactive 5-station scenario for child falls from height.',
          difficulty: 'صعب',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'سقط طفل من نافذة الدور الأول واستقر على عشب الحوش وهو يبكي. ما أول حركة؟',
              'sitEn': 'Child falls from 1st floor window landing on yard grass crying. Action?',
              'hintAr': 'عدم تحريك أو حمل الطفل إطلاقاً وتثبيت رأسه بالوضعية التي سقط عليها',
              'hintEn': 'Do NOT lift or carry child; manually stabilize head & neck in found position',
              'safeTextAr': 'التثبيت اليدوي لرأس ورقبة الطفل ومنع أي شخص من رفعه أو تحريكه',
              'safeTextEn': 'Manually hold child head & neck inline; strictly prohibit anyone from lifting child',
              'safeExpAr': 'تصرف أنقذ حياة؛ السقوط من ارتفاع يرجح كسور العمود الفقري وتحريكه يسبب الشلل.',
              'safeExpEn': 'Lifesaving response; fall from height implies spinal trauma; moving victim risks paralysis.',
              'safeOutAr': 'ثبّت رأس الطفل ومنعت تحريكه للمحطة 2.',
              'safeOutEn': 'Stabilized child spine for Station 2.',
              'unsafeTextAr': 'حمـل الطفل فوراً وضمه بكتفيك والركض به لداخل المنزل',
              'unsafeTextEn': 'Scoop child up in arms immediately running inside home',
              'unsafeExpAr': 'خطأ قاتل؛ حمل الطفل المصاب بالسقوط يقطع الحبل الشوكي المكسور.',
              'unsafeExpEn': 'Fatal mistake; scooping up a fall victim severs damaged spinal nerves.',
              'unsafeOutAr': 'تسببت بمضاعفات كسر الرقبة.',
              'unsafeOutEn': 'Severed spinal nerve.',
            },
            {
              'sitAr': 'الاتصال الفوري بالطوارئ الموحدة (997 الهلال الأحمر / 911). التفاصيل؟',
              'sitEn': 'Calling emergency dispatch (997 Red Crescent / 911). Details to relay?',
              'hintAr': 'تحديد ارتفاع السقوط، عمر الطفل، درجة الوعي، وأماكن النزيف',
              'hintEn': 'Specify fall height, child age, consciousness level, and visible trauma',
              'safeTextAr': 'إعطاء العنوان، وذكر أن السقوط من ارتفاع دور كامل مع تحديد عمر الطفل ووعيه',
              'safeTextEn': 'Give exact location, report fall height (1st floor), child age, & responsiveness to 997',
              'safeExpAr': 'بلاغ شمولية؛ الارتفاع يحدد درجة استجابة سيارة إسعاف عناية الإصابات (Trauma Rig).',
              'safeExpEn': 'Comprehensive dispatch; fall height triggers priority advanced trauma response team.',
              'safeOutAr': 'أبلغت 997 بالإصابة للمحطة 3.',
              'safeOutEn': 'Reported trauma details for Station 3.',
              'unsafeTextAr': 'البكاء بالهاتف وإغلاق الخط دون إعطاء عنوان المنزل',
              'unsafeTextEn': 'Cry frantically into phone hanging up without giving address',
              'unsafeExpAr': 'خطأ؛ عدم تحديد العنوان يمنع وصول طاقم الإسعاف.',
              'unsafeExpEn': 'Error; missing address leaves ambulance crew unable to locate house.',
              'unsafeOutAr': 'تأخر وصول الإسعاف.',
              'unsafeOutEn': 'Ambulance dispatch delayed.',
            },
            {
              'sitAr': 'فحص علامات الوعي واستجابة عينين الطفل أثناء الانتظار. كيف تفحص الحيوية؟',
              'sitEn': 'Checking child responsiveness & pupils while waiting. How to check vitals?',
              'hintAr': 'التحدث بكلمات مهدئة للطفل وفحص التنفس دون لمس الظهر أو الرقبة',
              'hintEn': 'Talk softly to child, monitor chest breathing; do NOT touch spine',
              'safeTextAr': 'التحدث بكلمات مهدئة للطفل ومراقبة انتظام حركة الصدر والتنفس دون تحريك الجسد',
              'safeTextEn': 'Speak in soothing tones to child, monitor chest rise/fall without moving body',
              'safeExpAr': 'إجراء إسعافي سليم؛ التهدئة تخفض التسارع النبضي وتثبيت الرأس يحمي الأعصاب.',
              'safeExpEn': 'Correct first aid; calming reduces trauma shock while neck stabilization protects spinal cord.',
              'safeOutAr': 'طمأنت الطفل وفحصت التنفس للمحطة 4.',
              'safeOutEn': 'Soothed child and checked breathing for Station 4.',
              'unsafeTextAr': 'إجلاس الطفل بالقوة وجعله يقف على قدميه لاختبار الكسور',
              'unsafeTextEn': 'Force child to stand up and walk to test for broken legs',
              'unsafeExpAr': 'خطأ؛ إرغام الطفل على الوقوف يسبب إزاحة كسور الحوض والفخذ.',
              'unsafeExpEn': 'Error; forcing a fall victim to stand displaces pelvic/femur fractures violently.',
              'unsafeOutAr': 'تسببت بإزاحة الكسر.',
              'unsafeOutEn': 'Displaced femur fracture.',
            },
            {
              'sitAr': 'وصول فرقة الهلال الأحمر (997) واستخدام اللوح الخشبي الشوكي (Spine Board). الإجراء؟',
              'sitEn': '997 Paramedics arrive using full spinal backboard. Paramedic assistance?',
              'hintAr': 'مساعدة المسعفين بتثبيت الرأس أثناء نقل الطفل ككتلة واحدة (Log Roll)',
              'hintEn': 'Assist paramedics by keeping head inline while log-rolling child onto board',
              'safeTextAr': 'مساعدة المسعف بتثبيت الرأس المحاذي أثناء نقل الطفل ككتلة واحدة فوق اللوح الشوكي',
              'safeTextEn': 'Maintain head inline manual grip while paramedics log-roll child onto spinal board',
              'safeExpAr': 'تكتيك إنقاذ احترافي؛ نقل المصاب ككتلة واحدة (Log Roll) يضمن عدم انثناء العمود الفقري.',
              'safeExpEn': 'Pro trauma technique; log-rolling onto spinal board prevents any vertebral flexion.',
              'safeOutAr': 'تم نقل الطفل للسطح الشوكي للمحطة 5.',
              'safeOutEn': 'Log-rolled safely onto backboard for Station 5.',
              'unsafeTextAr': 'الاستعجال ونقل الطفل بداخل سيارة خاصة قبل تثبيته بالرقبة الخشبية',
              'unsafeTextEn': 'Rush to put child in private sedan backseat before spine board arrives',
              'unsafeExpAr': 'خطأ؛ نقل مصابي السقوط بالسيارات العادية يسبب الشلل بالمسار.',
              'unsafeExpEn': 'Error; transporting spinal trauma victims in regular cars causes permanent paralysis.',
              'unsafeOutAr': 'عرضت الطفل لخطر الشلل.',
              'unsafeOutEn': 'High risk of permanent paralysis.',
            },
            {
              'sitAr': 'نقل الطفل لمركز الإصابات بالمستشفى. ما التجهيز الوقائي بالمنزل لمنع السقوط؟',
              'sitEn': 'Child safely in ER. Home window & balcony preventive safety standard?',
              'hintAr': 'تركيب شبك حماية صلب وحزام أمان على جميع النوافذ والدرابزين',
              'hintEn': 'Install certified steel window safety guards & raise balcony railing heights',
              'safeTextAr': 'تركيب شبك حماية حديدي وقفل أمان على جميع نوافذ وشرفات المنزل العلوية',
              'safeTextEn': 'Install heavy-duty steel window guards and child-proof safety locks on all upper windows',
              'safeExpAr': 'إتمام كامل؛ شبك النوافذ والأقفال تمنع سقوط الأطفال وتوفر الأمان التام.',
              'safeExpEn': 'Complete resolution; certified window guards 100% prevent child fall tragedies.',
              'safeOutAr': 'أكملت محطات الوقاية من سقوط الأطفال بنجاح!',
              'safeOutEn': 'Successfully completed child window fall scenario!',
              'unsafeTextAr': 'الاعتماد على شبك الناموس القماشي الضعيف لحماية النوافذ',
              'unsafeTextEn': 'Rely on flimsy mesh insect screens to stop children falling out',
              'unsafeExpAr': 'خطأ؛ شبك الناموس القماشي يمتزق فور اتكاء وزن الطفل عليه.',
              'unsafeExpEn': 'Error; mesh insect screens give way instantly when a child leans against them.',
              'unsafeOutAr': 'تمزق الشبك القماشي.',
              'unsafeOutEn': 'Insect screen gave way.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_5',
          categoryId: 'home',
          titleAr: 'جروح قطعية عميقة بالزجاج بالمنزل',
          titleEn: 'Severe Glass Cut & Bleeding Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع الجروح القطعية العميقة والنزيف الشرياني.',
          descriptionEn: 'Interactive 5-station scenario for deep glass cuts and severe bleeding.',
          difficulty: 'متوسط',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'انكسر باب زجاجي وتسبب في جرح قطعي عميق في ساعد اليد مع تدفق دم احمر نافوري. ما الحركة؟',
              'sitEn': 'Glass door breaks causing deep forearm laceration with spurting blood. Action?',
              'hintAr': 'الضغط المباشر والقوي على مكان الجرح بقماش معقم ورفع الساعد لأعلى',
              'hintEn': 'Apply immediate firm direct pressure with clean cloth and elevate arm above heart',
              'safeTextAr': 'الضغط المباشر والقوي بشاش معقم أو قماش نظيف على الجرح ورفع الساعد فوق مستوى القلب',
              'safeTextEn': 'Apply immediate firm direct pressure using clean cloth and elevate arm above heart level',
              'safeExpAr': 'إجراء إسعافي ذهبي؛ الضغط المباشر مع الرفع يقلل تدفق الدم الشرياني فوراً.',
              'safeExpEn': 'Golden first aid rule; direct pressure combined with elevation stops arterial spurt.',
              'safeOutAr': 'ضغطت الجرح ورفعت الساعد للمحطة 2.',
              'safeOutEn': 'Compressed cut and elevated arm for Station 2.',
              'unsafeTextAr': 'سكب العطر أو البودرة الشعبية داخل الجرح القطعي المفتوح',
              'unsafeTextEn': 'Pour perfume or coffee grounds deep inside open arterial wound',
              'unsafeExpAr': 'خطأ؛ سكب العطر والبودرة يلوث الجرح ويمنع التئام الأوعية.',
              'unsafeExpEn': 'Error; coffee grounds and perfume introduce severe infection & prevent vascular repair.',
              'unsafeOutAr': 'تلوث الجرح المفتوح.',
              'unsafeOutEn': 'Wound heavily contaminated.',
            },
            {
              'sitAr': 'الدم ينفذ عبر القماش الأول بكثرة. ماذا تفعل بالضماد المبتل بالدم؟',
              'sitEn': 'Blood soaks completely through first cloth. What to do with soaked dressing?',
              'hintAr': 'إضافة ضماد جديد فوق الضماد الأول دون إزالة القماش السابَق لتفادي نزع التجلط',
              'hintEn': 'Add second cloth ON TOP of first; do NOT remove blood-soaked original layer',
              'safeTextAr': 'إضافة طبقة قماش جديدة فوق الضماد الأولي ومواصلة الضغط دون إزالة الطبقة الأولى',
              'safeTextEn': 'Place additional sterile pads ON TOP of soaked original dressing continuing pressure',
              'safeExpAr': 'تكتيك إسعافي معتمد؛ إزالة القماش الأول تخلع خثرة الدم المتكونة وتجدد النزيف.',
              'safeExpEn': 'Certified first aid tactic; yanking off first pad strips forming clot reigniting bleeding.',
              'safeOutAr': 'ضفت ضماداً ثانياً للمحطة 3.',
              'safeOutEn': 'Added second pad on top for Station 3.',
              'unsafeTextAr': 'نزع القماش الأول المبتل بالدم والبحث عن قطن جاف',
              'unsafeTextEn': 'Peel soaked first cloth off wound completely searching for cotton balls',
              'unsafeExpAr': 'خطأ؛ نزع القماش يزيل الخثرة ويسبب اندفاع النزيف مجدداً.',
              'unsafeExpEn': 'Error; peeling off soaked pad tears newly formed blood clot restarting hemorrhage.',
              'unsafeOutAr': 'اندفع النزيف مجدداً.',
              'unsafeOutEn': 'Arterial bleeding reignited.',
            },
            {
              'sitAr': 'وجود قطعة زجاج صغيرة مغروسة داخل الجرح المفتوح. كيف تتعامل مع الزجاج المغروس؟',
              'sitEn': 'Small glass shard embedded deep inside open wound. How to manage embedded glass?',
              'hintAr': 'عدم قلع الزجاج المغروس نهائياً والضغط على جانبي الزجاج لتثبيته',
              'hintEn': 'Do NOT pull out embedded glass; pressure on wound EDGES around glass',
              'safeTextAr': 'عدم سحب أو قلع قطعة الزجاج المغروسة، والضغط على حوافي الجرح الجانبية حول الزجاج',
              'safeTextEn': 'Do NOT pull out embedded glass shard; apply pressure around gash edges stabilizing glass',
              'safeExpAr': 'حكمة عالية؛ الزجاج المغروس يعمل كشبه سدادة للشريان وسحبه يسبب نزيفاً قاتلاً.',
              'safeExpEn': 'Wise rule; embedded glass acts as a plug for severed vessels; pulling it causes massive bleed.',
              'safeOutAr': 'ثبّت الزجاج المغروس للمحطة 4.',
              'safeOutEn': 'Stabilized embedded glass for Station 4.',
              'unsafeTextAr': 'قلع وسحب قطعة الزجاج بقوة بأصابعك',
              'unsafeTextEn': 'Yank embedded glass shard out forcefully barehanded',
              'unsafeExpAr': 'خطأ؛ سحب الزجاج يقطع الشرايين والأعصاب المجاورة أثناء الخروج.',
              'unsafeExpEn': 'Error; pulling embedded glass slashes adjacent nerves & arteries on the way out.',
              'unsafeOutAr': 'قطع الأوتار والأعصاب.',
              'unsafeOutEn': 'Severed adjacent tendons & nerves.',
            },
            {
              'sitAr': 'الاتصال بالهلال الأحمر (997) أو التوجه لغرفة الطوارئ. ما البلاغ؟',
              'sitEn': 'Calling 997 Red Crescent or heading to ER. Information needed?',
              'hintAr': 'تحديد موقع الجرح، حجم النزيف، وجود زجاج مغروس، وحالة النبض',
              'hintEn': 'Specify gash location, bleeding volume, embedded object, & peripheral pulse',
              'safeTextAr': 'إعطاء اسم الشارع، وتأكيد وجود جرح قطعي شرياني عميق بالساعد مع تثبيت الزجاج',
              'safeTextEn': 'Report location to 997 stating severe deep glass laceration with arterial bleeding',
              'safeExpAr': 'بلاغ موجه؛ يوجه المسعفين لإحضار حقيبة الخياطة والأربطة الشريانية (Tourniquet).',
              'safeExpEn': 'Targeted report; directs paramedics to bring vascular tourniquet & trauma dressings.',
              'safeOutAr': 'أبلغت 997 بالإصابة للمحطة 5.',
              'safeOutEn': 'Reported details to 997 for Station 5.',
              'unsafeTextAr': 'القيادة بالسيارة بكتف واحد والنزيف ينزف بكثرة',
              'unsafeTextEn': 'Drive fast to hospital with one hand while gash bleeds profusely',
              'unsafeExpAr': 'خطأ؛ القيادة أثناء النزيف الشديد قد تسبب فقدان الوعي وحادث سيارة.',
              'unsafeExpEn': 'Error; driving while bleeding heavily causes hypovolemic shock loss of consciousness.',
              'unsafeOutAr': 'تعرضت للإغماء أثناء القيادة.',
              'unsafeOutEn': 'Passed out behind wheel.',
            },
            {
              'sitAr': 'وصول المسعفين وخياطة الجرح بالطوارئ. ما المعيار الوقائي للزجاج بالمنزل؟',
              'sitEn': 'Sutured in ER; wound dressed. Home glass safety preventive standard?',
              'hintAr': 'تركيب أفلام السلامة العازلة للزجاج (Safety Window Film) أو الزجاج المعالج (Tempered)',
              'hintEn': 'Apply safety film on glass doors or replace with Tempered Safety Glass',
              'safeTextAr': 'تركيب أفلام الحماية المقاومة للكسر على الأبواب والنوافذ الزجاجية أو استبدالها بزجاج Tempered',
              'safeTextEn': 'Apply shatter-resistant safety film to indoor glass doors or upgrade to Tempered Glass',
              'safeExpAr': 'إتمام كامل؛ زجاج Tempered يتفتت لقطع صغيرة غير حادة عند الكسر ويمنع الجروح القاتلة.',
              'safeExpEn': 'Complete resolution; Tempered glass breaks into dull harmless granules avoiding deep gashes.',
              'safeOutAr': 'أكملت محطات إسعاف الجروح الزجاجية بنجاح!',
              'safeOutEn': 'Successfully completed glass cut emergency scenario!',
              'unsafeTextAr': 'ترك زجاج الأبواب الخفيف العادي بدون أي أفلام عازلة للسلامة',
              'unsafeTextEn': 'Keep thin single-pane untempered glass doors unshielded',
              'unsafeExpAr': 'خطأ؛ الزجاج العادي ينكسر لشفرات حادة كاطراف السكاكين عند اصطدام الأطفال.',
              'unsafeExpEn': 'Error; plain plate glass shatters into lethal razor-sharp daggers upon impact.',
              'unsafeOutAr': 'ظلت الأبواب الزجاجية خطيرة.',
              'unsafeOutEn': 'Untempered glass remained hazard.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_6',
          categoryId: 'home',
          titleAr: 'احتجاز طفل داخل غرفة مغلقة',
          titleEn: 'Child Locked inside Room Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انقلاق أبواب الغرف واحتجاز الأطفال.',
          descriptionEn: 'Interactive 5-station scenario for children locked inside rooms.',
          difficulty: 'سهل',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'انغلق باب الغرفة على طفل صغير بطريق الخطأ ولم يستطع فتح المقبض من الداخل وبدأ بالبكاء. ما أول خطوة؟',
              'sitEn': 'Room door accidentally locks with toddler trapped inside crying. First action?',
              'hintAr': 'التحدث بصوت مهدئ عبر الباب ومنع الطفل من الهلع أو الاقتراب من النوافذ',
              'hintEn': 'Talk calmly through door to soothe child preventing panic/window access',
              'safeTextAr': 'التحدث بكلمات مهدئة بصوت واثق عبر الباب لطمأنة الطفل وتوجيهه للابتعاد عن الباب',
              'safeTextEn': 'Speak calmly through door soothing child and instructing them to sit safely away from door',
              'safeExpAr': 'تصرف ممتاز؛ التهدئة تمنع طفل المفزوع من تسلق النوافذ أو محاولة القفز.',
              'safeExpEn': 'Excellent step; calming child stops panic climbing onto balconies or high windows.',
              'safeOutAr': 'طمأنت الطفل عبر الباب للمحطة 2.',
              'safeOutEn': 'Soothed child through door for Station 2.',
              'unsafeTextAr': 'الصراخ بالخارج وضرب الباب بقوة شديدة تفرع الطفل',
              'unsafeTextEn': 'Scream hysterically pounding on door violently terrifying child',
              'unsafeExpAr': 'خطأ؛ الصراخ يسبب هلعاً حاداً للطفل ودفعه للتسلق والتعثر.',
              'unsafeExpEn': 'Error; screaming terrifies toddler inducing frantic panic and dangerous climbing.',
              'unsafeOutAr': 'فزع الطفل بالداخل.',
              'unsafeOutEn': 'Child panicked inside.',
            },
            {
              'sitAr': 'محاولة فتح مقبض الباب بالدبوس أو مفتاح الطوارئ الخارجي. كيف تفتحه؟',
              'sitEn': 'Attempting to open lock via emergency pin/hole on outer knob. How to unlock?',
              'hintAr': 'إدخال مفك صغير أو دبوس بالفتحة الصغيرة بمركز المقبض الخارجي والضغط للداخل',
              'hintEn': 'Insert small screwdriver or emergency pin into outer knob hole and push',
              'safeTextAr': 'إدخال مفك صغير أو دبوس بالفتحة المخصصة بالطوارئ بمركز المقبض الخارجي والضغط',
              'safeTextEn': 'Insert small flathead screwdriver or pin into outer knob release hole and press/turn',
              'safeExpAr': 'تكتيك مفصلات الباب؛ معظم مقابض الأبواب المنزلية تحوي فتحة فتح طوارئ خارجية.',
              'safeExpEn': 'Door hardware design; standard interior privacy knobs feature outer pin release holes.',
              'safeOutAr': 'فتحت قفل المقبض للمحطة 3.',
              'safeOutEn': 'Released door lock pin for Station 3.',
              'unsafeTextAr': 'كسر الباب بركلة قوية فجأة نحو الداخل',
              'unsafeTextEn': 'Kick door inward violently with full force without checking behind it',
              'unsafeExpAr': 'خطأ؛ ركل الباب قد يصدم الطفل إذا كان واقفاً خلف الباب المباشر.',
              'unsafeExpEn': 'Error; kicking door inward strikes child directly if standing behind door leaf.',
              'unsafeOutAr': 'صدم الباب المكسور الطفل.',
              'unsafeOutEn': 'Door struck child behind it.',
            },
            {
              'sitAr': 'إذا تعذر فتح المقبض بالدبوس وكان الباب خشبياً. كيف تكسر الإطار بأمان؟',
              'sitEn': 'If pin fails & door is solid wood. How to pry/force frame safely?',
              'hintAr': 'استخدام العتلة أو المفك بين إطار الباب والمفتاح قرب القفل دون ركل',
              'hintEn': 'Use crowbar/large screwdriver at latch bolt level to pry frame clear',
              'safeTextAr': 'وضع عتلة أو مفك عريض بين إطار الجدار ومكال اللسان للضغط بحذر وإبعاد اللسان',
              'safeTextEn': 'Insert pry bar or flat screwdriver between door jamb and bolt latch level to pry open',
              'safeExpAr': 'إجراء احترافي؛ الضغط بين اللسان والإطار يفتح القفل فوراً دون إيذاء من بالداخل.',
              'safeExpEn': 'Pro method; prying jamb at latch bolt level pops lock without inward door impact.',
              'safeOutAr': 'فتحت اللسان بالعتلة للمحطة 4.',
              'safeOutEn': 'Pried latch bolt safely for Station 4.',
              'unsafeTextAr': 'استخدام منشار كهربائي لقطع الخشب والدخان يملأ الشقة',
              'unsafeTextEn': 'Use power saw to cut wood door generating heavy friction smoke',
              'unsafeExpAr': 'خطأ؛ المنشار الكهربائي يخيف الطفل وينشر غباراً خشبياً خانقاً الغرفة.',
              'unsafeExpEn': 'Error; power saws terrify child and generate toxic sawdust smoke in closed room.',
              'unsafeOutAr': 'امتلأت الغرفة بغبار الخشب.',
              'unsafeOutEn': 'Room filled with sawdust smoke.',
            },
            {
              'sitAr': 'الاتصال بالدفاع المدني (998) عند تعذر الفتح. كيف تبلغ الطوارئ؟',
              'sitEn': 'Calling Civil Defense (998) if door unopenable. Emergency report details?',
              'hintAr': 'تحديد عنوان المنزل، عمر الطفل المحتجز، ووجود مخاطر كالنوافذ المفتوحة',
              'hintEn': 'State house location, child age, and active hazards like open windows',
              'safeTextAr': 'إعطاء العنوان، وذكر عمر الطفل المحتجز والتأكيد على وجود شرفة أو نوافذ بالغرفة',
              'safeTextEn': 'Report exact address, child age (toddler), & state active room hazards (balcony/windows) to 998',
              'safeExpAr': 'بلاغ عالي الأولوية؛ وجود النوافذ يحرك فرقة فراد النجدة والمقصوصات السريعة.',
              'safeExpEn': 'High-priority dispatch; open window hazards elevate Civil Defense response speed.',
              'safeOutAr': 'أبلغت 998 للنجدة للمحطة 5.',
              'safeOutEn': 'Reported to 998 for Station 5.',
              'unsafeTextAr': 'الانتظار لعدة ساعات حتى عودة النجار دون إبلاغ الطوارئ',
              'unsafeTextEn': 'Wait 4 hours for carpenter to arrive without calling emergency services',
              'unsafeExpAr': 'خطأ؛ الانتظار الطويل يسبب جفاف وهلع شديد للطفل المحتجز.',
              'unsafeExpEn': 'Error; multi-hour confinement causes severe dehydration and psychological trauma.',
              'unsafeOutAr': 'تعرض الطفل للجفاف والهلع.',
              'unsafeOutEn': 'Child dehydrated and traumatized.',
            },
            {
              'sitAr': 'إنقاذ الطفل ودخول الغرفة. ما الإجراء الوقائي الدائم لجميع أبواب المنزل؟',
              'sitEn': 'Child rescued. Permanent home interior door safety standard?',
              'hintAr': 'إزالة الأقفال الداخلية لأبواب غرف الأطفال أو تركيب أغطية مقابض أمان',
              'hintEn': 'Remove interior locking push-buttons or install pinch-guards & safety knobs',
              'safeTextAr': 'إلغاء الأقفال الداخلية لغرف الأطفال أو تركيب مصدات مطاطية يمنع انغلاق الباب',
              'safeTextEn': 'Disable interior lock pins on kids rooms or install anti-slam door pinch guards',
              'safeExpAr': 'إتمام كامل؛ مصدات الأبواب تمنع انغلاق الباب على أصابع الأطفال أو احتجازهم كلياً.',
              'safeExpEn': 'Complete resolution; door pinch guards prevent both child lock-ins and finger crush injuries.',
              'safeOutAr': 'أكملت محطات إخلاء الطفل المحتجز بنجاح!',
              'safeOutEn': 'Successfully completed child locked-in scenario!',
              'unsafeTextAr': 'ترك المقابض ذات الأقفال المعقدة كما هي بجميع الغرف',
              'unsafeTextEn': 'Leave complex keyless lock pins on all child bedroom doors',
              'unsafeExpAr': 'خطأ؛ ترك الأقفال يجدد احتجاز الأطفال بالغرف مستقبلاً.',
              'unsafeExpEn': 'Error; leaving push-pin locks guarantees future accidental child lock-ins.',
              'unsafeOutAr': 'تجدد الخطر بالأبواب.',
              'unsafeOutEn': 'Lock-in hazard persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_7',
          categoryId: 'home',
          titleAr: 'انسكاب سائل ساخن وحروق الجلد',
          titleEn: 'Scalding Hot Liquid Burn Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انسكاب الماء المغلي والحروق الحرارية.',
          descriptionEn: 'Interactive 5-station scenario for scalding liquid burn first aid.',
          difficulty: 'سهل',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'انسكب كوب شاي/ماء مغلي على ساعد اليد والفخذ وسرخ المصاب. ما أول خطوة؟',
              'sitEn': 'Hot boiling tea/water spills over arm & thigh. First step?',
              'hintAr': 'تبريد الحرق فوراً بماء الصنبور الفاتر الجاري لمدة 10-20 دقيقة',
              'hintEn': 'Cool burn immediately with cool running tap water for 10-20 minutes',
              'safeTextAr': 'وضع موضع الحرق تحت ماء الصنبور الفاتر الجاري فوراً لمدة 10 إلى 20 دقيقة',
              'safeTextEn': 'Place burned area under cool running tap water immediately for 10-20 full minutes',
              'safeExpAr': 'تصرف إسعافي ذهبي؛ ماء التبريد الجاري يمتص الحرارة المخزونة بالأنسجة فوراً.',
              'safeExpEn': 'Golden first aid rule; cool running water dissipates trapped thermal energy from skin.',
              'safeOutAr': 'برّدت الحرق بماء الصنبور للمحطة 2.',
              'safeOutEn': 'Cooled burn under tap for Station 2.',
              'unsafeTextAr': 'وضع الثلج المباشر أو معجون الأسنان فوق الحرق الساخن',
              'unsafeTextEn': 'Apply direct ice blocks or toothpaste over fresh hot scalding burn',
              'unsafeExpAr': 'خطأ؛ الثلج المباشر يسبب تلف الخلايا ومعجون الأسنان يحبس الحرارة ويلوث الحرق.',
              'unsafeExpEn': 'Error; direct ice causes frostbite tissue necrosis; toothpaste traps heat.',
              'unsafeOutAr': 'تلف الجلد بالثلج.',
              'unsafeOutEn': 'Frostbite tissue damage from ice.',
            },
            {
              'sitAr': 'الملابس مبللة بالسائل المغلي فوق الجلد المحترق. كيف تنزع الملابس؟',
              'sitEn': 'Clothes soaked in boiling liquid on burned skin. How to remove clothing?',
              'hintAr': 'نزع الملابس غير الملتصقة بحذر وقص الملابس حول الأجزاء الملتصقة',
              'hintEn': 'Remove loose un-stuck clothes gently; cut around fabric stuck to burn',
              'safeTextAr': 'خلع الملابس غير الملتصقة بحذر، وقص القماش حول الأنسجة الملتصقة بالحرق دون شد',
              'safeTextEn': 'Remove un-stuck clothing carefully; use scissors to cut around fabric stuck to skin',
              'safeExpAr': 'إجراء سليم؛ قص الملابس يمنع سلخ الجلد الملتصق بالسائل المغلي.',
              'safeExpEn': 'Correct method; cutting fabric around burn prevents tearing raw scalded dermis.',
              'safeOutAr': 'قصصت الملابس الملتصقة للمحطة 3.',
              'safeOutEn': 'Cut stuck clothing safely for Station 3.',
              'unsafeTextAr': 'شد ونزع الملابس الملتصقة بقوة شديدة عن الجلد',
              'unsafeTextEn': 'Yank stuck scalded shirt off skin forcefully',
              'unsafeExpAr': 'خطأ؛ شد الملابس الملتصقة يسلخ طبقة الجلد السطحية وتسبب نزيفاً مؤلماً.',
              'unsafeExpEn': 'Error; yanking stuck fabric rips off top layer of scalded skin causing bleeding.',
              'unsafeOutAr': 'انسلخ الجلد.',
              'unsafeOutEn': 'Torn scalded skin.',
            },
            {
              'sitAr': 'تغطية الحرق بعد التبريد المائي. أي ضماد تستخدم على حروق السوائل؟',
              'sitEn': 'Dressing burn post-cooling. Which bandage/wrap to apply?',
              'hintAr': 'تغطية الحرق بضماد معقم جاف أو بلاستيك تغليف الأطعمة الشفاف النظيف',
              'hintEn': 'Cover burn loosely with dry sterile gauze or clean plastic food wrap',
              'safeTextAr': 'تغطية الحرق بلطف بشاش معقم جاف أو بضماد ناعم غير ملتصق دون ضغط',
              'safeTextEn': 'Cover burn loosely with clean non-stick sterile gauze or plastic wrap without pressure',
              'safeExpAr': 'تغليف ممتاز؛ البلاستيك الشفاف أو الضماد المعقم يحمي الأعصاب المكشوفة من التلوث والارتجاف.',
              'safeExpEn': 'Great dressing; sterile wrap shields exposed nerve endings from air currents & bacteria.',
              'safeOutAr': 'غطيت الحرق بشاش معقم للمحطة 4.',
              'safeOutEn': 'Dressed burn with sterile gauze for Station 4.',
              'unsafeTextAr': 'وضع مراهم شعبية كالزبدة أو الطحين أو البيض فوق الحرق',
              'unsafeTextEn': 'Smear butter, flour, or raw eggs over open scalded burn',
              'unsafeExpAr': 'خطأ؛ المواد الشعبية تنقل البكتيريا وتسبب تلوثاً صديدياً شديداً.',
              'unsafeExpEn': 'Error; home remedies like flour/eggs introduce bacteria causing severe infection.',
              'unsafeOutAr': 'تلوث الحرق صديدياً.',
              'unsafeOutEn': 'Severe burn infection.',
            },
            {
              'sitAr': 'الحرق يشمل مساحة كبيرة تفوق كف اليد (حروق الدرجة الثانية). أين تنقل المصاب؟',
              'sitEn': 'Burn covers large area bigger than palm (2nd degree). Transport destination?',
              'hintAr': 'التوجه لمركز الطوارئ أو الاتصال بـ (997) للحروق واسعة المساحة',
              'hintEn': 'Head to ER or dial 997 Red Crescent for burns larger than palm size',
              'safeTextAr': 'الاتصال بـ (997 الهلال الأحمر) أو التوجه الفوري لمركز طوارئ المستشفى',
              'safeTextEn': 'Dial 997 Red Crescent or proceed immediately to nearest hospital emergency room',
              'safeExpAr': 'تقييم طبي حرج؛ الحروق الكبيرة تسبب فقدان سوائل الجسم وصدمة حروق (Burn Shock).',
              'safeExpEn': 'Critical triage; large burns cause severe plasma fluid loss requiring IV resuscitation.',
              'safeOutAr': 'نقلت المصاب للطوارئ للمحطة 5.',
              'safeOutEn': 'Transported to ER for Station 5.',
              'unsafeTextAr': 'البقاء بالمنزل والتغاضي عن الحرق واسع المساحة',
              'unsafeTextEn': 'Stay home for days ignoring large blistering burn covering arm & thigh',
              'unsafeExpAr': 'خطأ؛ إهمال الحروق الواسعة يسبب جفاف حاداً وتلوثاً مهدداً للحياة.',
              'unsafeExpEn': 'Error; ignoring extensive burns causes life-threatening dehydration and sepsis.',
              'unsafeOutAr': 'تعرض المصاب لتلوث وسوائل.',
              'unsafeOutEn': 'Suffered burn sepsis.',
            },
            {
              'sitAr': 'علاج الحرق واستقرار الحالة. ما الوقاية المنزلية بالمطبخ لمنع انسكاب السوائل؟',
              'sitEn': 'Burn treated in ER. Kitchen preventive rule for hot liquids?',
              'hintAr': 'توجيه مقابض أواني الطبخ للداخل وإبعاد غلايات الماء عن حوافي الطاولات',
              'hintEn': 'Turn pot handles inward toward back of stove & keep kettles off counter edges',
              'safeTextAr': 'توجيه مقابض القدر والمقلاة نحو الداخل وحفظ غلاية الماء بعيداً عن أطراف الطاولات',
              'safeTextEn': 'Always turn pot handles inward toward stove back and keep electric kettles off counter edges',
              'safeExpAr': 'إتمام كامل؛ توجيه المقابض للداخل يمنع سحب الأواني أو اصطدام الأطفال بها بنسبة 100%.',
              'safeExpEn': 'Complete resolution; turning pot handles inward eliminates 100% of accidental spills.',
              'safeOutAr': 'أكملت محطات علاج حروق السوائل بنجاح!',
              'safeOutEn': 'Successfully completed hot liquid burn scenario!',
              'unsafeTextAr': 'ترك مقابض الأواني بارزة للخارج بسلك الغلاية المتدلي',
              'unsafeTextEn': 'Leave pot handles sticking out over stove edge with dangling kettle cords',
              'unsafeExpAr': 'خطأ؛ المقابض البارزة والأسلاك المتدلية السبب الأول لحروق الأطفال.',
              'unsafeExpEn': 'Error; protruding pot handles and dangling cords are #1 cause of pediatric scalding.',
              'unsafeOutAr': 'ظلت المقابض خطيرة.',
              'unsafeOutEn': 'Protruding handles remained hazard.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_8',
          categoryId: 'home',
          titleAr: 'انبعاث أول أكسيد الكربون من الفحم',
          titleEn: 'Carbon Monoxide Poisoning from Indoor Coal',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع التسمم الشفاف بغاز أول أكسيد الكربون.',
          descriptionEn: 'Interactive 5-station scenario for indoor carbon monoxide poisoning.',
          difficulty: 'صعب',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'استيقظت بشعور بثقل في الرأس ودوار شديد مع وجود منقل فحم مشتعل بالغرفة المغلقة. ما الحركة؟',
              'sitEn': 'Woke up with severe headache & dizziness; burning coal braziers inside closed room. Action?',
              'hintAr': 'الخروج الفوري للهواء الطلق وتنبيه جميع النائمين ومغادرة الغرفة',
              'hintEn': 'Evacuate to fresh outdoor air immediately and wake all sleeping family members',
              'safeTextAr': 'الخروج الفوري للهواء الطلق وإيقاظ جميع النائمين ونقلهم خارج الغرفة',
              'safeTextEn': 'Evacuate to fresh outdoor air immediately, waking and assisting all sleeping family members',
              'safeExpAr': 'إجراء أنقذ حياة؛ غاز أول أكسيد الكربون غاز قاتل يسبب النوم الدائم والوفاة.',
              'safeExpEn': 'Lifesaving response; CO is an invisible killer gas causing silent suffocation during sleep.',
              'safeOutAr': 'خرجت للهواء النقيل للمحطة 2.',
              'safeOutEn': 'Evacuated to fresh air for Station 2.',
              'unsafeTextAr': 'العودة للنوم ومحاولة تجاهل الصداع والدوار',
              'unsafeTextEn': 'Go back to sleep trying to ignore headache and dizziness',
              'unsafeExpAr': 'خطأ قاتل؛ العودة للنوم تسبب فقدان الوعي والوفاة باختناق أول أكسيد الكربون.',
              'unsafeExpEn': 'Fatal mistake; going back to sleep leads to coma and fatal carbon monoxide asphyxiation.',
              'unsafeOutAr': 'تعرضت للغيبوبة الخانقة.',
              'unsafeOutEn': 'Fatal CO asphyxiation coma.',
            },
            {
              'sitAr': 'تهوية الغرفة بأمان وتخليص المكان من الغاز. كيف تفتح المكان؟',
              'sitEn': 'Ventilating room safely to clear trapped CO gas. How to air out?',
              'hintAr': 'فتح جميع النوافذ والأبواب وإخراج منقل الفحم المشتعل للخارج',
              'hintEn': 'Open all doors and windows wide and carefully remove coal brazier outside',
              'safeTextAr': 'فتح كافة الأبواب والنوافذ بالكامل وإخراج منقل الفحم للهواء الطلق بحذر',
              'safeTextEn': 'Open all doors and windows completely to flush room and move coal brazier outdoors',
              'safeExpAr': 'تكتيك ممتاز؛ التهوية الشاملة تطرد غاز CO الثقيل وتستبدله بالأكسجين.',
              'safeExpEn': 'Great tactic; cross-ventilation flushes out dense odorless carbon monoxide gas.',
              'safeOutAr': 'هويت الغرفة وطردت الفحم للمحطة 3.',
              'safeOutEn': 'Flushed room and removed coal for Station 3.',
              'unsafeTextAr': 'إبقاء النوافذ مغلقة وتشغيل التكييف فقط',
              'unsafeTextEn': 'Keep windows closed and run split AC unit only',
              'unsafeExpAr': 'خطأ؛ التكييف يعيد تدوير الغاز القاتل داخل الغرفة دون طرده للخارج.',
              'unsafeExpEn': 'Error; split AC recirculates indoor air without introducing fresh outdoor oxygen.',
              'unsafeOutAr': 'استمر الغاز القاتل.',
              'unsafeOutEn': 'Toxic CO gas remained trapped.',
            },
            {
              'sitAr': 'أحد أفراد الأسرة غائب عن الوعي ويتنفس ببطء. كيف تسعفه حتى وصول الإسعاف؟',
              'sitEn': 'Family member unconscious but breathing slowly. First aid stance?',
              'hintAr': 'وضعه في وضعية الإفاقة الجانبية وتزويده بالهواء النقي والاتصال بـ (997)',
              'hintEn': 'Place in lateral recovery position in fresh air & call Red Crescent 997',
              'safeTextAr': 'تمديد المصاب بالهواء الطلق في وضعية الإفاقة الجانبية والاتصال بـ (997 الهلال الأحمر)',
              'safeTextEn': 'Lie unconscious member outdoors in lateral recovery position & dial 997 Red Crescent',
              'safeExpAr': 'وضعية ذهبية؛ تمنع انسداد مجرى التنفس وتضمن استمرار دخول الأكسجين للرئتين.',
              'safeExpEn': 'Golden position; maintains clear airway preventing tongue block while 997 responds.',
              'safeOutAr': 'أمّنت وضعية الإفاقة وأبلغت 997 للمحطة 4.',
              'safeOutEn': 'Secured recovery stance and called 997 for Station 4.',
              'unsafeTextAr': 'إجلاس المصاب الغائب عن الوعي مستقيماً وسكب ماء بداخل فمه',
              'unsafeTextEn': 'Sit unconscious person upright and pour water down their mouth',
              'unsafeExpAr': 'خطأ؛ سكب الماء لغير الواعي يدخل السائل للقصبة الهوائية ويسبب الغرق.',
              'unsafeExpEn': 'Error; pouring water into unconscious mouth causes pulmonary aspiration drowning.',
              'unsafeOutAr': 'دخل الماء للرئتين.',
              'unsafeOutEn': 'Water entered lungs.',
            },
            {
              'sitAr': 'وصول فرقة الهلال الأحمر (997). ما العلاج الطبي التخصصي لمسمومي CO؟',
              'sitEn': '997 Paramedics arrive. What is specialized medical treatment for CO poisoning?',
              'hintAr': 'إعطاء أكسجين نقي بنسبة 100% عبر قناع الأكسجين غير المرتد (Non-Rebreather Mask)',
              'hintEn': 'Administer 100% high-flow oxygen via Non-Rebreather Mask (NRB)',
              'safeTextAr': 'تزويد المصاب بأكسجين نقي بنسبة 100% عبر قناع الإسعاف لطرد أول أكسيد الكربون من الدم',
              'safeTextEn': 'Administer 100% high-flow oxygen via Non-Rebreather Mask to flush CO off hemoglobin',
              'safeExpAr': 'علاج طبي تخصصي؛ الأكسجين النقي 100% يقلل عمر غاز CO بالدم من 5 ساعات لـ 80 دقيقة.',
              'safeExpEn': 'Specialized medical treatment; 100% oxygen drops CO blood half-life from 5 hours to 80 mins.',
              'safeOutAr': 'أعطي الأكسجين النقي 100% للمحطة 5.',
              'safeOutEn': 'Administered 100% high-flow oxygen for Station 5.',
              'unsafeTextAr': 'رفض الأكسجين والاعتماد على التنفس العادي',
              'unsafeTextEn': 'Refuse oxygen therapy relying on room air breathing',
              'unsafeExpAr': 'خطأ؛ هواء الغرفة العادي يستغرق ساعات طويلة لطرد التسمم من الهيموجلوبين.',
              'unsafeExpEn': 'Error; ambient air takes over 5 hours to clear bound CO causing permanent brain damage.',
              'unsafeOutAr': 'بطء طرد التسمم.',
              'unsafeOutEn': 'Delayed CO blood clearance.',
            },
            {
              'sitAr': 'تعافي المصابين والتوعية الوقائية الشتوية. ما المعيار الوقائي للفحم بالمنزل؟',
              'sitEn': 'Victims recovered. Winter indoor heating & coal safety standard?',
              'hintAr': 'حظر إشعال الفحم أو الحطب داخل الأماكن المغلقة وتثبيت كاشف CO',
              'hintEn': 'STRICTLY prohibit burning coal indoors and install home Carbon Monoxide detector',
              'safeTextAr': 'حظر إشعال الفحم بالحجرات المغلقة كلياً وتركيب كاشف غاز أول أكسيد الكربون (CO Alarm)',
              'safeTextEn': 'STRICTLY forbid indoor coal braziers and install certified Carbon Monoxide (CO) alarms',
              'safeExpAr': 'إتمام كامل؛ كاشف CO ينطلق بصوت حاد فور انبعاث الغاز ويمنع حوادث الاختناق.',
              'safeExpEn': 'Complete resolution; CO detectors sound loud alarm upon gas trace, 100% preventing tragedies.',
              'safeOutAr': 'أكملت محطات الوقاية من أول أكسيد الكربون بنجاح!',
              'safeOutEn': 'Successfully completed carbon monoxide poisoning scenario!',
              'unsafeTextAr': 'إشعال الفحم بالصالة وإغلاق جميع الأبواب بالشتاء',
              'unsafeTextEn': 'Burn open coal brazier in living room keeping all doors sealed in winter',
              'unsafeExpAr': 'خطأ؛ إشعال الفحم بالبيوت المغلقة السبب الأول لوفيات الشتاء الصامتة.',
              'unsafeExpEn': 'Error; burning charcoal in sealed rooms is #1 cause of silent winter death tragedies.',
              'unsafeOutAr': 'استمر خطر الاختناق الصامت.',
              'unsafeOutEn': 'Silent asphyxiation hazard persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_home_9',
          categoryId: 'home',
          titleAr: 'انزلاق وسقوط كبار السن بالدورة',
          titleEn: 'Elderly Bathroom Slip & Fall Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انزلاق كبار السن بالحمامات وتأمين السلامة.',
          descriptionEn: 'Interactive 5-station scenario for elderly bathroom slip and fall safety.',
          difficulty: 'متوسط',
          icon: 'home',
          colorHex: 0xFF43A047,
          stations: [
            {
              'sitAr': 'سمعت صوت سقوط واكتشفت انزلاق جدك على بلاط دورة المياه المبلل. ما أول خطوة؟',
              'sitEn': 'Loud thud heard; grandfather slipped on wet bathroom floor. Immediate action?',
              'hintAr': 'فصل المياه والطلب منه عدم الحركة وفحص موضع ألم مفصل الورك',
              'hintEn': 'Turn off water, instruct elder not to move, and check for hip fracture pain',
              'safeTextAr': 'الدخول بحذر على البلاط الزلق، طلب عدم الحركة، وفحص موضع الألم ومفصل الورك',
              'safeTextEn': 'Tread carefully on wet tile, instruct elder to stay still, and check for severe hip pain',
              'safeExpAr': 'تصرف ممتاز؛ كبار السن أكثر عرضة لكسور مفصل الفخذ (Hip Fracture) ومرفوعيتهم تزيد التمزق.',
              'safeExpEn': 'Excellent step; elderly are prone to hip fractures; moving them worsens bone displacement.',
              'safeOutAr': 'فحصت الألم وحميت الجسد للمحطة 2.',
              'safeOutEn': 'Assessed hip pain and stabilized for Station 2.',
              'unsafeTextAr': 'سحب كبير السن بقوة من ذراعيه وإجبارة على الوقوف فوراً',
              'unsafeTextEn': 'Forcefully yank elder up by arms compelling them to stand on feet',
              'unsafeExpAr': 'خطأ؛ إرغام كبير السن على الوقوف عند وجود كسر بالفخذ يسبب نزيفاً داخلياً.',
              'unsafeExpEn': 'Error; forcing an elder with hip fracture to stand displaces bone causing severe bleeding.',
              'unsafeOutAr': 'تسببت بإزاحة كسر الفخذ.',
              'unsafeOutEn': 'Displaced hip fracture.',
            },
            {
              'sitAr': 'كبير السن يشتكي من ألم شديد بمفصل الفخذ وعدم القدرة على تحريك الساق. الإجراء؟',
              'sitEn': 'Elderly victim complains of intense hip joint pain unable to rotate leg. Protocol?',
              'hintAr': 'تثبيت الساقين معاً بوضع وسادة بين الركبتين وتدفئة الجسد',
              'hintEn': 'Stabilize legs inline placing a soft pillow between knees and cover with blanket',
              'safeTextAr': 'تثبيت الساقين بهدوء بوضع وسادة بين الركبتين وتغطية كبير السن ببطانية دافئة',
              'safeTextEn': 'Gentle stabilization of legs placing soft cushion between knees & cover elder with warm blanket',
              'safeExpAr': 'تثبيت إسعافي ممتاز؛ الوسادة بين الركبتين تثبت مفصل الفخذ وتخفف الألم.',
              'safeExpEn': 'Great first aid; cushion between knees stabilizes hip joint reducing acute pain.',
              'safeOutAr': 'ثبّت الفخذ بالوسادة للمحطة 3.',
              'safeOutEn': 'Stabilized hip with cushion for Station 3.',
              'unsafeTextAr': 'ثني وركض الساق المصابة بقوة لمعاينة الحركة',
              'unsafeTextEn': 'Bend and twist injured leg forcefully to check joint mobility',
              'unsafeExpAr': 'خطأ؛ ثني الساق المكسورة يسبب تمزق الشريان الفخذي الرئيسي.',
              'unsafeExpEn': 'Error; twisting broken hip leg risks severing main femoral artery.',
              'unsafeOutAr': 'تمزق الشريان الفخذي.',
              'unsafeOutEn': 'Femoral artery damaged.',
            },
            {
              'sitAr': 'الاتصال بالهلال الأحمر (997). ماذا تبلغ عن حادث سقوط كبير السن؟',
              'sitEn': 'Calling Saudi Red Crescent 997. What details to dispatch for elderly fall?',
              'hintAr': 'تحديد العمر، اشتباه كسر الفخذ، حالة الوعي، وعنوان المنزل',
              'hintEn': 'Report age, suspected hip fracture, consciousness level, and exact home address',
              'safeTextAr': 'إعطاء العنوان بدقة، وتأكيد وقوع حادث انزلاق لكبير السن مع اشتباه كسر الفخذ',
              'safeTextEn': 'Report exact address, hit details, elder age, and suspected hip fracture to 997 operator',
              'safeExpAr': 'بلاغ موجه؛ يتيح للمسعفين إحضار النقالة المفصلية (Scoop Stretcher) المخصصة للكسور.',
              'safeExpEn': 'Targeted report; enables 997 crew to bring orthopedic Scoop Stretcher for safe lifting.',
              'safeOutAr': 'أبلغت 997 للمحطة 4.',
              'safeOutEn': 'Reported details to 997 for Station 4.',
              'unsafeTextAr': 'نقل كبير السن بالمقعد الخلفي لسيارة خاصة دون نقالة إسعاف',
              'unsafeTextEn': 'Haul elder into private sedan backseat driving to clinic without ambulance',
              'unsafeExpAr': 'خطأ؛ نقل كسر الفخذ بسيارة عادية يضاعف الآلام ويسبب مضاعفات وشرخاً.',
              'unsafeExpEn': 'Error; transporting hip fracture in regular car doubles pain and worsens bone displacement.',
              'unsafeOutAr': 'تفاقم ألم الكسر.',
              'unsafeOutEn': 'Hip fracture complicated.',
            },
            {
              'sitAr': 'وصول المسعفين ونقل كبير السن بالنقالة المخصصة. ما الفحص الطبي بالطوارئ؟',
              'sitEn': '997 Paramedics transfer elder with Scoop Stretcher. Hospital ER evaluation?',
              'hintAr': 'عمل أشعة سريعة (X-Ray) لمفصل الفخذ وفحص الهيموجلوبين والضغط',
              'hintEn': 'Perform pelvic X-ray, check hemoglobin levels, and evaluate blood pressure',
              'safeTextAr': 'إخضاع كبير السن لأشعة X-Ray للحوض وفحص ضغط الدم لتقييم صدمة الأوردة',
              'safeTextEn': 'Hospital X-ray evaluation of pelvis/hip, monitor blood pressure and hemoglobin levels',
              'safeExpAr': 'إتمام ممتاز؛ الأشعة تحدد نوع الكسر وتوجه الجراح لعملية التثبيت المسماري.',
              'safeExpEn': 'Complete medical steps; X-ray guides orthopedic surgeon for hip pin stabilization.',
              'safeOutAr': 'أجريت الأشعة والتقييم للمحطة 5.',
              'safeOutEn': 'Completed X-ray and triage for Station 5.',
              'unsafeTextAr': 'إعادة كبير السن للمنزل دون عمل أشعة سريعة',
              'unsafeTextEn': 'Take elder home immediately without getting pelvic X-ray',
              'unsafeExpAr': 'خطأ؛ كسور الفخذ الدقيقة لا تظهر بالعين وتستوجب الأشعة التشخيصية.',
              'unsafeExpEn': 'Error; hairline hip fractures are invisible externally requiring diagnostic X-ray.',
              'unsafeOutAr': 'إغفال كسر الفخذ.',
              'unsafeOutEn': 'Missed diagnosis of hip fracture.',
            },
            {
              'sitAr': 'تعافي كبير السن وعودته للمنزل. ما التعديلات الوقائية بدورة المياه لمنع السقوط؟',
              'sitEn': 'Elderly recovered and home. Bathroom fall prevention modification standard?',
              'hintAr': 'تركيب مقابض جدارية (Grab Bars)، دهان بلاستيكي مانع للانزلاق، وإضاءة ليلية',
              'hintEn': 'Install wall grab bars, anti-slip floor mats/coatings, and night LED sensor lights',
              'safeTextAr': 'تركيب مقابض جدارية ثقيلة (Grab Bars)، مفرش مطاطي مانع للانزلاق، وإضاءة مستشعر ليلية',
              'safeTextEn': 'Install heavy-duty wall grab bars, non-slip rubber floor matting, and motion night lights',
              'safeExpAr': 'إتمام كامل؛ المقابض والمفارش المطاطية تمنع 98% من حوادث انزلاق كبار السن بالحمامات.',
              'safeExpEn': 'Complete resolution; wall grab bars & non-slip mats eliminate 98% of bathroom fall risks.',
              'safeOutAr': 'أكملت محطات الوقاية من انزلاق كبار السن بنجاح!',
              'safeOutEn': 'Successfully completed elderly bathroom fall scenario!',
              'unsafeTextAr': 'ترك بلاء الدورة أملساً ومبلولاً بدون أي مقابض جدارية',
              'unsafeTextEn': 'Leave glossy smooth tiles wet with zero wall grab bars or mats',
              'unsafeExpAr': 'خطأ؛ ترك البلاط الناعم المبلل يضمن تكرار انزلاق كبار السن.',
              'unsafeExpEn': 'Error; glossy wet tiles guarantee repeated severe bathroom falls for elderly.',
              'unsafeOutAr': 'تجدد خطر الانزلاق.',
              'unsafeOutEn': 'Bathroom slip hazard persisted.',
            },
          ],
        ),
      ];
}
