import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosDesert {
  static List<Scenario> get list => [
        // 1. Desert Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_1',
          categoryId: 'desert_safety',
          titleAr: 'الانغراز بالرمال النفوذة بالصحراء',
          titleEn: 'Desert Sand Trap & Stuck Vehicle Recovery',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتخليص المركبة المنغرزة بالرمال وتجنب ضربات الشمس.',
          descriptionEn: 'Interactive 5-station scenario for recovering a sand-stuck vehicle safely.',
          difficulty: 'متوسط',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'انغرزت إطارات سيارة الدفع الرباعي بالرمال النفوذة أثناء الكشتة بالصحراء. ما أول تصرف؟',
              'sitEn': '4WD vehicle tires get stuck in deep soft sand during desert trip. First action?',
              'hintAr': 'التوقف الفوري عن ضغط دواسة البنزين لتجنب إحفار السيارة بالرمال',
              'hintEn': 'Stop pressing gas pedal immediately to prevent digging wheels deeper',
              'safeTextAr': 'التوقف الفوري عن ضغط دواسة البنزين لتفادي حفر الرمال ودوران الإطارات الفارغ',
              'safeTextEn': 'Stop accelerating immediately to prevent tires from spinning and digging deeper pits',
              'safeExpAr': 'تصرف أساسي؛ إيقاف التسارع يمنع دفن جسم السيارة والسلسلة السفلى بالرمال.',
              'safeExpEn': 'Primary rule; stopping acceleration prevents chassis and differential from bottoming out.',
              'safeOutAr': 'أوقفت التسارع للمحطة 2.',
              'safeOutEn': 'Stopped wheel spin for Station 2.',
              'unsafeTextAr': 'الضغط بأقصى قوة على دواسة البنزين لزيادة سرعة الإطارات',
              'unsafeTextEn': 'Floor the gas pedal to spin wheels at max RPM trying to break out',
              'unsafeExpAr': 'خطأ جسيم؛ الدوران السريع يحفر خنادق تحت الإطارات ويعلق المحور السري.',
              'unsafeExpEn': 'Severe error; high RPM tire spin digs deep trenches burying differential under sand.',
              'unsafeOutAr': 'انغرز المحور بالرمال.',
              'unsafeOutEn': 'Differential bottomed out in sand.',
            },
            {
              'sitAr': 'تخفيف ضغط هواء الإطارات (التنسيم). ما المستوى الموصى به للقيادة بالرمال؟',
              'sitEn': 'Airing down tire pressure (Tire Deflation). Recommended PSI level for soft sand?',
              'hintAr': 'تنسيم الإطارات لدرجة 12-15 PSI لتوسيع رقعة ملامسة الكفر بالرمال',
              'hintEn': 'Deflate tires down to 12-15 PSI to widen tire footprint on soft dunes',
              'safeTextAr': 'تنسيم ضغط الإطارات Ar إلى 12-15 PSI لزيادة مساحة الالتصاق وتوسيع الأثر',
              'safeTextEn': 'Deflate all 4 tires down to 12-15 PSI expanding rubber contact patch over sand surface',
              'safeExpAr': 'تنسيم ممتاز؛ توسيع رقعة الكفر يجعل السيارة تطفو فوق الرمال بدل الحفر.',
              'safeExpEn': 'Great technique; widening tire footprint floats rubber on sand crust preventing sinkage.',
              'safeOutAr': 'نسّمت الإطارات للمحطة 3.',
              'safeOutEn': 'Aired down tires to 15 PSI for Station 3.',
              'unsafeTextAr': 'ترك الإطارات على ضغطها المرتفع (35 PSI) للشارع',
              'unsafeTextEn': 'Leave tires at high highway pressure 35 PSI attempting recovery',
              'unsafeExpAr': 'خطأ؛ الضغط المرتفع يجعل الكفر كالمطرقة الحادة يغوص بالرمال.',
              'unsafeExpEn': 'Error; hard high-pressure tires slice through sand like thin blades sinking instantly.',
              'unsafeOutAr': 'غاصت الإطارات الصلبة.',
              'unsafeOutEn': 'Hard tires sank into dune.',
            },
            {
              'sitAr': 'إزالة الرمال من أمام وخلف الإطارات. كيف تمهد مسار الخروج؟',
              'sitEn': 'Clearing sand behind and in front of tires. How to clear exit ramp?',
              'hintAr': 'استخدام المجرفة لإزالة السواتر الرملية وحفر مسار انحداري ملائم',
              'hintEn': 'Use shovel to dig out sand ramps in front of all 4 tires',
              'safeTextAr': 'استخدام مجرفة الصحراء لإزالة السواتر الرملية وتفريغ ما تحت جسم السيارة',
              'safeTextEn': 'Use desert shovel to dig smooth ramps ahead of tires and clear underbody sand frame',
              'safeExpAr': 'إعداد سليم؛ تمهيد المسار يقلل المقاومة أمام حركة الإطارات عند الدوران.',
              'safeExpEn': 'Proper preparation; clearing sand ramps reduces rolling resistance for smooth momentum.',
              'safeOutAr': 'مهّدت مسار الإطارات للمحطة 4.',
              'safeOutEn': 'Dug out sand ramps for Station 4.',
              'unsafeTextAr': 'محاولة الخروج دون رفع الرمال المتراكمة أمام الكفرات',
              'unsafeTextEn': 'Attempt driving out without removing sand mounds built up against wheels',
              'unsafeExpAr': 'خطأ؛ السواتر الرملية تعمل كحواجز صد تمنع اندفاع المركبة للأمام.',
              'unsafeExpEn': 'Error; sand mounds block tire rotation creating high resistance barricades.',
              'unsafeOutAr': 'اصطدمت بالسواتر الرملية.',
              'unsafeOutEn': 'Blocked by sand barricades.',
            },
            {
              'sitAr': 'استخدام ألواح التغريس (MaxTrax Recovery Boards). كيف تثبت الألواح؟',
              'sitEn': 'Using sand recovery traction tracks (MaxTrax). Correct board placement?',
              'hintAr': 'دفع الألواح بزاوية مائلة تحت أسفل منحنى الإطارات مباشرة',
              'hintEn': 'Wedge recovery tracks tightly under lead edge of tires at an angle',
              'safeTextAr': 'غرس ألواح التغريس مائلة تحت واجهة الإطارات مباشرة لضمان التشبث المعشّق',
              'safeTextEn': 'Wedge traction tracks firmly under front edge of drive tires engaging tread teeth',
              'safeExpAr': 'استخدام محترف؛ أسنان الألواح تمنح الإطار تماسكاً فورياً للارتفاع والخروج.',
              'safeExpEn': 'Pro use; track teeth grip tire tread elevating vehicle out of sand depression.',
              'safeOutAr': 'وضعت ألواح التراك بالمسار للمحطة 5.',
              'safeOutEn': 'Positioned traction tracks for Station 5.',
              'unsafeTextAr': 'رمي الألواح بعيداً عن الكفر بمسافة نصف متر على الرمال السائبة',
              'unsafeTextEn': 'Throw recovery tracks on sand half a meter away from tires',
              'unsafeExpAr': 'خطأ؛ وضع الألواح بعيداً يمنع الكفر من الوصول لأسنان التماسك.',
              'unsafeExpEn': 'Error; placing tracks away from tire edge prevents tread from gripping board teeth.',
              'unsafeOutAr': 'دوران فارغ دون تماسك.',
              'unsafeOutEn': 'Wheel spun without gripping track.',
            },
            {
              'sitAr': 'الخروج بسلامة من التغريسة. ما التوجيه القيادي بعد تخليص السيارة؟',
              'sitEn': 'Successfully cleared sand trap. Post-recovery driving protocol?',
              'hintAr': 'مواصلة السير بانسياق هادئ حتى الوصول لأرض صلبة وعدم التوقف المفاجئ بالرمال',
              'hintEn': 'Keep smooth momentum until reaching firm ground; avoid braking hard on soft sand',
              'safeTextAr': 'مواصلة السير بانسياق تدريجي حتى الوصول لأرض صلبة (حصى/قشرة) ثم نفخ الإطارات',
              'safeTextEn': 'Maintain steady momentum driving to hardpack ground before stopping to re-inflate tires',
              'safeExpAr': 'إتمام كامل؛ المواصلة تمنع الانغراز الثاني والتوقف على أرض صلبة يؤمن إعادة النفخ.',
              'safeExpEn': 'Complete resolution; continuous momentum prevents secondary sinkage until reaching firm ground.',
              'safeOutAr': 'أكملت محطات تخليص التغريسة بنجاح!',
              'safeOutEn': 'Successfully completed sand recovery scenario!',
              'unsafeTextAr': 'التوقف الفوري المفاجئ بالرمال الناعمة فور الخروج من الألواح',
              'unsafeTextEn': 'Slam brakes to a full stop on soft sand right after clearing tracks',
              'unsafeExpAr': 'خطأ؛ الفرملة المفاجئة بالرمال الناعمة تسبب انغراز السيارة مجدداً.',
              'unsafeExpEn': 'Error; sudden braking on soft sand digs tires right back into a secondary sand trap.',
              'unsafeOutAr': 'تغريس ثاني مفاجئ.',
              'unsafeOutEn': 'Secondary sand trap stuck.',
            },
          ],
        ),

        // 2. Desert Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_2',
          categoryId: 'desert_safety',
          titleAr: 'الضياع بالصحراء والنجاة العطش',
          titleEn: 'Lost in Desert & Thirst Survival Protocol',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تعطل السيارة وسط الصحراء وحفظ المياه.',
          descriptionEn: 'Interactive 5-station scenario for vehicle stranded deep in desert & survival.',
          difficulty: 'صعب',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'تعطلت السيارة تماماً بعمق نفود الصحراء وانقطعت تغطية الجوال. ما القرار الذهبي الأول؟',
              'sitEn': 'Car completely breaks down deep in desert dunes; zero phone signal. Golden survival rule?',
              'hintAr': 'البقاء بجانب السيارة وعدم المغادرة مشياً على الأقدام إطلاقاً',
              'hintEn': 'STAY WITH THE VEHICLE; never wander off walking into empty open desert',
              'safeTextAr': 'البقاء بظل السيارة وعدم مغادرتها مشياً، فالسيارة أسهل للرصد الجوي والإنقاذ',
              'safeTextEn': 'Stay beside vehicle in shade; STRICTLY never wander off on foot into barren desert',
              'safeExpAr': 'قاعدة نجاة حاسمة؛ السيارة هدف ضخم يسهل على طائرات وفرق الجمعيات (كعون وغوث) رصده.',
              'safeExpEn': 'Crucial survival rule; vehicle is a massive target easily spotted by air and ground search teams.',
              'safeOutAr': 'بقيت بجانب المركبة للمحطة 2.',
              'safeOutEn': 'Stayed with vehicle for Station 2.',
              'unsafeTextAr': 'ترك السيارة والمشي في الهجير نحو أفق الصحراء المجهول',
              'unsafeTextEn': 'Abandon vehicle and start walking under scorching sun toward open horizon',
              'unsafeExpAr': 'خطأ قاتل؛ المشي بالحر القاهل يسبب الجفاف والضربة الشمسية القاتلة في ساعات.',
              'unsafeExpEn': 'Fatal error; walking under peak desert heat causes fatal heatstroke and dehydration in hours.',
              'unsafeOutAr': 'تعرضت للجفاف أثناء المشي.',
              'unsafeOutEn': 'Dehydrated while walking.',
            },
            {
              'sitAr': 'كيف ترتب استهلاك كمية المياه القليلة المتبقية معك لحفظ حياتك؟',
              'sitEn': 'Managing scarce remaining water supply. How to ration water wisely?',
              'hintAr': 'الشرب بجرعات صغيرة عند العطش الشديد وتجنب الحركة تحت الشمس لتقليل العرق',
              'hintEn': 'Sip water slowly when necessary; minimize body sweating by resting in shade',
              'safeTextAr': 'ترشيد المياه بأخذ رشفات صغيرة، والتزام الراحة التامة بالظل لمنع التعرق',
              'safeTextEn': 'Ration water taking small slow sips, resting completely in shade to stop sweat fluid loss',
              'safeExpAr': 'ترشيد ممتاز؛ تقليل الحركة يوفر لترات المياه الناتجة عن التعرق والزفير.',
              'safeExpEn': 'Smart rationing; minimizing physical activity conserves vital internal body moisture.',
              'safeOutAr': 'نسّقت استهلاك المياه للمحطة 3.',
              'safeOutEn': 'Rationed water supply for Station 3.',
              'unsafeTextAr': 'شرب كامل كمية المياه دفعة واحدة أو شرب مياه الإسرديتد الملوثة',
              'unsafeTextEn': 'Gulp down all remaining water bottles at once in panic',
              'unsafeExpAr': 'خطأ؛ شرب كميات كبيرة دفعة واحدة يسرع التعرق وتصريف المياه من الكلى.',
              'unsafeExpEn': 'Error; gulping water induces rapid sweating and fast kidney filtration flushing fluids out.',
              'unsafeOutAr': 'نفذت المياه بالكامل.',
              'unsafeOutEn': 'Water supply exhausted quickly.',
            },
            {
              'sitAr': 'صنع إشارة استغاثة بصرية لرصد طائرات البحث. كيف تعكس ضوء الشمس؟',
              'sitEn': 'Creating visual distress signal for search aircraft. How to signal searchers?',
              'hintAr': 'استخدام مرآة السيارة لعكس ضوء الشمس وإشعال دخان بإطار احتياطي بالنهار',
              'hintEn': 'Use car side mirror to flash sunlight or burn a spare tire creating thick black smoke',
              'safeTextAr': 'عكس أشعة الشمس بمرآة الجانب، وإشعال نار بالإطار الاحتياطي بالنهار لإحداث دخان أسود كثيف',
              'safeTextEn': 'Flash sunlight using side mirror, and burn a spare tire during daytime creating high black smoke column',
              'safeExpAr': 'إشارة دولية؛ عمود الدخان الأسود من الإطار يرى على بعد 20 كيلومتراً بالصحراء.',
              'safeExpEn': 'Global signal; burning rubber spare tire generates a black smoke column visible from 20 km away.',
              'safeOutAr': 'أطلقت إشارات الاستغاثة للمحطة 4.',
              'safeOutEn': 'Generated smoke and mirror signal for Station 4.',
              'unsafeTextAr': 'التلويح بيد صغيرة بالهواء دون أي أدوات عاكسة بالنهار',
              'unsafeTextEn': 'Wave bare hand in air without using reflective mirrors or smoke',
              'unsafeExpAr': 'خطأ؛ حركة اليد لا ترى إطلاقاً من الارتفاعات العالية لطائرات البحث.',
              'unsafeExpEn': 'Error; bare hand waving is completely invisible to search aircraft at normal altitude.',
              'unsafeOutAr': 'تعذر رصد الإشارة.',
              'unsafeOutEn': 'Signal missed by searchers.',
            },
            {
              'sitAr': 'الحماية من البرد القارس أو الحرارة العالية ليلاً ونهاراً بالصحراء. ما الملابس المناسبة؟',
              'sitEn': 'Protecting body from extreme heat by day and freezing cold by night in desert. Attire rule?',
              'hintAr': 'إبقاء الملابس كاملة ومغطاة لوقاية الجلد من حروق الشمس والبرد',
              'hintEn': 'Keep clothes ON to shield skin from sun evaporation by day and cold by night',
              'safeTextAr': 'إبقاء الشماغ والملابس كاملة لحماية الجلد من التبخر الشمسي والتدفئة ليلاً',
              'safeTextEn': 'Keep light long clothes and head cover ON shielding skin from UV rays and night chill',
              'safeExpAr': 'حماية حرارية؛ غطاء الملابس يقلل تبخر العرق وينظم درجة حرارة الجسد.',
              'safeExpEn': 'Thermal protection; covering skin lowers sweat evaporation rate and shields from sunburn.',
              'safeOutAr': 'حافظت على تغطية الجسم للمحطة 5.',
              'safeOutEn': 'Maintained full body cover for Station 5.',
              'unsafeTextAr': 'نزع جميع الملابس بالنهار للامتعاض من الحرارة',
              'unsafeTextEn': 'Strip off clothes during hot day to cool down bare skin',
              'unsafeExpAr': 'خطأ؛ تعري الجلد للشمس يضاعف التبخر المائي ويصيب بحروق جلدية خطيرة.',
              'unsafeExpEn': 'Error; exposing bare skin to sun accelerates sweat evaporation and causes severe solar burns.',
              'unsafeOutAr': 'حروق جلدية وتبخر مائي.',
              'unsafeOutEn': 'Severe sunburn & rapid fluid loss.',
            },
            {
              'sitAr': 'وصول فرق البحث والإنقاذ (جمعية عون/غوث أو الدفاع المدني). ما التوجيه الوقائي المسبق للكشتات؟',
              'sitEn': 'Search & Rescue teams (Ewn/Ghowth/CD) locate you. Mandatory pre-trip safety protocol?',
              'hintAr': 'إبلاغ الأهل بالمسار الدقيق وحمل جهاز الاتصال الفضائي (Thuraya / Garmin InReach)',
              'hintEn': 'Inform family of exact desert destination & carry satellite tracker (Garmin/Thuraya)',
              'safeTextAr': 'إبلاغ الأسرة بخط السير المتوقع وحمل جهاز تتبع فضائي (Garmin InReach / ثريا) بالطوارئ',
              'safeTextEn': 'Notify family of exact desert coordinates/route and carry a satellite messenger tracker',
              'safeExpAr': 'إتمام كامل؛ إبلاغ المسار مسبقاً يضمن تحريك فرق الإنقاذ لموقعك خلال ساعات معدودة.',
              'safeExpEn': 'Complete resolution; sharing trip itinerary ensures rescue teams deploy straight to your grid.',
              'safeOutAr': 'أكملت محطات النجاة بالصحراء بنجاح!',
              'safeOutEn': 'Successfully completed desert lost survival scenario!',
              'unsafeTextAr': 'الانطلاق للصحراء المجهولة دون إبلاغ أي شخص بموقع وجهتك',
              'unsafeTextEn': 'Drive into deep desert without informing anyone of your destination route',
              'unsafeExpAr': 'خطأ؛ غياب البلاغ المسبق يؤخر بدء عمليات البحث لعدة أيام.',
              'unsafeExpEn': 'Error; lack of trip itinerary delays search initiation for critical days.',
              'unsafeOutAr': 'تأخر عمليات البحث.',
              'unsafeOutEn': 'Search operation delayed.',
            },
          ],
        ),

        // Scenarios 3 to 9 for DESERT...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_3',
          categoryId: 'desert_safety',
          titleAr: 'مداهمة السيول المنقولة بالأودية الصحراوية',
          titleEn: 'Desert Wadi Flash Flood Surge Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للنجاة من السيول الفجائية ببطون الأودية أثناء الكشتة.',
          descriptionEn: 'Interactive 5-station scenario for surviving desert wadi flash floods.',
          difficulty: 'صعب',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'التخييم ونصب الخيمة في بطن الوادي الصحراوي صيفاً أو شتاءً. ما تقييم السلامة؟',
              'sitEn': 'Setting up campsite & tent directly in low desert wadi riverbed. Safety evaluation?',
              'hintAr': 'حظر التخييم في مجاري الأودية نهائياً ونصب الخيام على الحزوم والجسور المرتفعة',
              'hintEn': 'STRICTLY never camp in low wadi beds; set camp on high elevated ridges',
              'safeTextAr': 'إبعاد موقع التخييم عن مجرى الوادي ونصب الخيام فوق التلال والحزوم المرتفعة',
              'safeTextEn': 'Camp strictly on high elevated desert ridges well clear of dry wadi floodplains',
              'safeExpAr': 'تقييم حكيم؛ السيول المنقولة تأتي من أمطار بعيدة وتدهم مجرى الوادي فجأة دون سحب محلية.',
              'safeExpEn': 'Wise choice; flash floods travel fast from distant rain mountains surprising dry wadis.',
              'safeOutAr': 'اخترت موقعاً مرتفعاً للمحطة 2.',
              'safeOutEn': 'Selected elevated campsite for Station 2.',
              'unsafeTextAr': 'نصب الخيمة في أسفل بطن الوادي تحت الأشجار الكبيرة',
              'unsafeTextEn': 'Pitch tent directly in deep center wadi channel under big trees',
              'unsafeExpAr': 'خطأ قاتل؛ مجرى الوادي يصبح نهراً جارفاً في دقائق معدودة.',
              'unsafeExpEn': 'Fatal error; low wadi channels transform into raging rivers within minutes during sudden rain.',
              'unsafeOutAr': 'مخاطرة ببطن الوادي.',
              'unsafeOutEn': 'Low wadi channel flood hazard.',
            },
            {
              'sitAr': 'سماع هديد وصوت جريف السيل المنقول قادماً من أعلى الوادي بالليل. ما أول حركة؟',
              'sitEn': 'Hearing roaring sound of incoming flash flood upstream at night. Immediate action?',
              'hintAr': 'ترك الخيام والأغراض فوراً والصعود للأماكن العالية المرتفعة على الأقدام',
              'hintEn': 'Abandon tents and equipment immediately; scramble on foot up nearest high hill',
              'safeTextAr': 'ترك الخيمة والمتاع فوراً والهروب صعوداً بالأقدام نحو أقرب جبل أو حزم مرتفع',
              'safeTextEn': 'Abandon campsite belongings instantly, climbing up nearest rocky hill on foot',
              'safeExpAr': 'استجابة نجاة؛ سيل الوادي المنقول يجرف الخيام والسيارات بسعة جارفة.',
              'safeExpEn': 'Survival response; wadi flash surges sweep tents and heavy vehicles effortlessly.',
              'safeOutAr': 'صعدت للجبل المرتفع للمحطة 3.',
              'safeOutEn': 'Scrambled up high hill for Station 3.',
              'unsafeTextAr': 'محاولة جمع الفرش والأدوات وتثبيت أوتاد الخيمة بقوة',
              'unsafeTextEn': 'Try gathering camping gear and hammering tent stakes deeper',
              'unsafeExpAr': 'خطأ؛ إضاعة الثواني في جمع المتاع تجعلك في وسط جرف السيل.',
              'unsafeExpEn': 'Error; wasting seconds packing gear traps campers in high-velocity water wall.',
              'unsafeOutAr': 'انحصرت بجرف السيل.',
              'unsafeOutEn': 'Trapped in incoming flash surge.',
            },
            {
              'sitAr': 'احتجاز السيارات في بطن الوادي واجتراف المياه لها. هل تعود للسيارة لجلب الهاتف؟',
              'sitEn': 'Vehicles being swept by rising wadi waters. Should you run back to car for phone?',
              'hintAr': 'حظر العودة للمركبة المحاصرة بالسيل نهائياً فسرعة المياه تصرع الإنسان',
              'hintEn': 'STRICTLY never return to vehicle stuck in moving floodwater',
              'safeTextAr': 'البقاء بالمنطقة المرتفعة الآمنة وعدم الاقتراب من السيل أو المركبة الجارفة',
              'safeTextEn': 'Remain on high ground, strictly avoiding running back into raging torrent for car items',
              'safeExpAr': 'قاعدة سلامة؛ سرعة السيل بعمق 20 سم كفيلة بإسقاط الإنسان وجرفه لعمق الوادي.',
              'safeExpEn': 'Safety rule; 20 cm of fast-moving wadi water easily knocks down an adult.',
              'safeOutAr': 'بقيت بالقمة المرتفعة للمحطة 4.',
              'safeOutEn': 'Remained on safe high ground for Station 4.',
              'unsafeTextAr': 'النزول لمجرى الوادي السريع ومحاولة تسلق باب السيارة',
              'unsafeTextEn': 'Wade into fast torrent trying to climb open car door',
              'unsafeExpAr': 'خطأ؛ انجراف السيارة والانقلاب المائي يهرس أي شخص يحاول الاقتراب.',
              'unsafeExpEn': 'Error; tumbling submerged vehicles crush anyone attempting close recovery.',
              'unsafeOutAr': 'انزلقت بالسيل.',
              'unsafeOutEn': 'Swept into raging wadi torrent.',
            },
            {
              'sitAr': 'توفير الإضاءة والإشارات لفرق إنقاذ الدفاع المدني بالليل (998/911). كيف تدلهم عليك؟',
              'sitEn': 'Providing night signals for Civil Defense rescue helicopters (998/911). How to indicate location?',
              'hintAr': 'تشغيل كشافات الجوال اليدوية وإشعال نار صغيرة بالقمة المرتفعة',
              'hintEn': 'Flash torches continuously and light small safe campfire on high ridge top',
              'safeTextAr': 'إشعال شعلة نار صفيرة فوق قمة الجبل وتلويح كشافات اليد بانتظام في الهواء',
              'safeTextEn': 'Light small campfire on high rocky ledge and wave LED torches rhythmically toward sky',
              'safeExpAr': 'تأمين إشارة ممتاز؛ النقطة المضيئة المرتفعة تعزل موقعك عن ظلام الوادي.',
              'safeExpEn': 'Great signaling; elevated light beacons guide night-vision search crews directly to safety hill.',
              'safeOutAr': 'أظهرت الإشارات الليلي للمحطة 5.',
              'safeOutEn': 'Showed night signals for Station 5.',
              'unsafeTextAr': 'النزول للأسفل بجانب السيل وصنع كشافات بالماء',
              'unsafeTextEn': 'Climb back down to water edge flashing torch into rushing brown mud',
              'unsafeExpAr': 'خطأ؛ الاقتراب من حافة الوادي المنهارة قد يسبب انهيار الجرف تحت قدميك.',
              'unsafeExpEn': 'Error; standing on collapsing muddy wadi banks risks sudden soil collapse into river.',
              'unsafeOutAr': 'انهار جرف الوادي.',
              'unsafeOutEn': 'Wadi bank collapsed underfoot.',
            },
            {
              'sitAr': 'اجتلاء السيل ووصول فرق الدفاع المدني. ما الدرس الوقائي الدائم للكشتات؟',
              'sitEn': 'Flood subsides and Civil Defense clears team. Permanent wadi safety lesson?',
              'hintAr': 'متابعة تنبيهات المركز الوطني للأرصاد عدم التخييم بالأودية مطلقاً',
              'hintEn': 'Check National Center for Meteorology warnings & NEVER camp in wadis',
              'safeTextAr': 'متابعة إنذارات الأرصاد الجوية (NCM) والالتزام بحظر التخييم ببطون الأودية دائماً',
              'safeTextEn': 'Monitor NCM weather alerts continuously and strictly enforce zero-camping policy in dry wadi beds',
              'safeExpAr': 'إتمام كامل؛ الوعي بمجاري الأودية والإنذار المبكر يضمن كشتة آمنة.',
              'safeExpEn': 'Complete resolution; wadi awareness and NCM weather apps ensure 100% safe desert trips.',
              'safeOutAr': 'أكملت محطات سلامة سيول الأودية بنجاح!',
              'safeOutEn': 'Successfully completed desert wadi flood scenario!',
              'unsafeTextAr': 'تجاهل تحذيرات الأرصاد الحمراء ومواصلة التخييم في الأودية',
              'unsafeTextEn': 'Ignore red weather alerts and continue camping in wadi channels',
              'unsafeExpAr': 'خطأ؛ التحذيرات المبكرة تمنع التواجد في مناطق الخطر.',
              'unsafeExpEn': 'Error; ignoring red weather alerts invites catastrophic flash flood traps.',
              'unsafeOutAr': 'تكرار مخاطر سيول الأودية.',
              'unsafeOutEn': 'Recurrent wadi flood risk.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_4',
          categoryId: 'desert_safety',
          titleAr: 'لدغات العقارب والأفاعي الصحراوية',
          titleEn: 'Scorpion & Viper Snake Bite First Aid in Desert',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع لدغات العقارب والأفاعي بالصحراء.',
          descriptionEn: 'Interactive 5-station scenario for desert scorpion & snake bite first aid.',
          difficulty: 'متوسط',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'تعرض زميل للكشتة للدغة عقرب أو أفعى صحراوية في القدم بالليل. ما الإجراء الأول؟',
              'sitEn': 'Desert camper bitten by scorpion or viper in foot at night. Immediate action?',
              'hintAr': 'تهدئة المصاب تماماً ومنعه من الحركة لمنع انتشار السم بالدم',
              'hintEn': 'Keep patient calm & completely still to slow venom spread through bloodstream',
              'safeTextAr': 'طمأنة المصاب وإجلائه في مكان مستقر ومنعه من الحركة أو الجري فوراً',
              'safeTextEn': 'Calm patient down, lay them resting flat, strictly forbidding any walking or running',
              'safeExpAr': 'تصرف أساسي؛ الهدوء وخفض ضربات القلب يبطئ حركة السم بالشبكة اللمفاوية.',
              'safeExpEn': 'Primary rule; staying calm keeps heart rate low slowing lymphatic venom distribution.',
              'safeOutAr': 'هدّأت المصاب وثبّت حركته للمحطة 2.',
              'safeOutEn': 'Calmed patient & immobilized foot for Station 2.',
              'unsafeTextAr': 'الطلب من المصاب الجري والركض لتنشيط الدورة الدموية',
              'unsafeTextEn': 'Instruct victim to run rapidly around camp to "flush out" blood',
              'unsafeExpAr': 'خطأ قاتل؛ الركض يسرع ضربات القلب وينشر السم بالدماغ والقلب خلال دقائق.',
              'unsafeExpEn': 'Fatal error; running spikes heart rate circulating envenomation rapidly to vital organs.',
              'unsafeOutAr': 'انتشر السم بالدورة الدموية.',
              'unsafeOutEn': 'Rapid systemic venom spread.',
            },
            {
              'sitAr': 'كيف تتصرف مع مكان اللدغة بالساق؟ هل تشق الجلد بمشرط وتشفط السم بملئ الفم؟',
              'sitEn': 'Managing bite site on leg. Should you cut skin with blade & suck venom by mouth?',
              'hintAr': 'حظر شق الجلد أو مص السم بالفم، وغسل مكان اللدغة بالماء والصابون وتثبيتها',
              'hintEn': 'STRICTLY never cut skin or suck venom by mouth; wash wound with soap and water',
              'safeTextAr': 'غسل مكان اللدغة بالماء والصابون وتثبيت الطرف المصاب أسفل مستوى القلب',
              'safeTextEn': 'Wash bite site with soap and water, keeping limb immobilized at or below heart level',
              'safeExpAr': 'إجراء طبي سليم؛ الشق والشفط يزيد تلوث الجرح وينقل السم للمنقذ.',
              'safeExpEn': 'Correct medical step; cutting/sucking causes secondary infection and envenomates rescuer.',
              'safeOutAr': 'غسلت مكان اللدغة للمحطة 3.',
              'safeOutEn': 'Washed bite site cleanly for Station 3.',
              'unsafeTextAr': 'شق مكان اللدغة بمشرط ومص السم بالفم وتبصه على الأرض',
              'unsafeTextEn': 'Cut open bite marks with razor blade and suck venom directly by mouth',
              'unsafeExpAr': 'خطأ؛ مص السم بالفم ينقل السم لتقرحات لثة المسعف ويقطع أعصاب المصاب.',
              'unsafeExpEn': 'Error; mouth sucking exposes rescuer to venom via gums and severs patient nerves.',
              'unsafeOutAr': 'تسمم المسعف وقطع الأنسجة.',
              'unsafeOutEn': 'Rescuer envenomation & tissue damage.',
            },
            {
              'sitAr': 'ربط الطرف المصاب باللدغة. هل تستخدم رباطاً ضاغطاً شديداً أو عاصبة؟',
              'sitEn': 'Bandaging bitten limb. Should you apply a tight arterial tourniquet?',
              'hintAr': 'تجنب الربط الشديد الضاغط واستخدام رباط مرن خفيف يسمح بمرور الإصبع',
              'hintEn': 'Avoid tight tourniquets; apply firm elastic crepe bandage allowing finger space',
              'safeTextAr': 'لف رباط ضاغط مرن بخفة فوق مكان اللدغة بحيث يمكن إدخال إصبع تحته بسهولة',
              'safeTextEn': 'Wrap flexible crepe bandage firmly around limb allowing one finger to slide easily underneath',
              'safeExpAr': 'تكتيك ممتاز؛ الربط المرن يبطئ التدفق اللمفاوي دون قطع الدورة الدموية الشريانية.',
              'safeExpEn': 'Great technique; elastic pressure retards lymphatic flow without cutting arterial supply.',
              'safeOutAr': 'لففت الرباط المرن للمحطة 4.',
              'safeOutEn': 'Wrapped elastic bandage safely for Station 4.',
              'unsafeTextAr': 'ربط سلك معدني ضيق بقوة فوق اللدغة حتى يتحول لون الساق للأسود',
              'unsafeTextEn': 'Tie thin metal wire tightly above bite until leg turns blue/black',
              'unsafeExpAr': 'خطأ؛ قطع شريان الدم التام يسبب موتاً موضعياً للأنسجة واضطرار البتر.',
              'unsafeExpEn': 'Error; total arterial blockage causes localized tissue necrosis leading to amputation.',
              'unsafeOutAr': 'موت موضعي للأنسجة.',
              'unsafeOutEn': 'Localized ischemic necrosis.',
            },
            {
              'sitAr': 'توثيق شكل العقرب أو الأفعى لنقل الوصف للطبيب بالمستشفى. كيف تفعل ذلك بأمان؟',
              'sitEn': 'Identifying scorpion/snake type for hospital. How to document safely?',
              'hintAr': 'التقاط صورة سريعة بالجوال من مسافة آمنة دون محاولة الإمساك بها',
              'hintEn': 'Take quick phone photo from safe distance; NEVER try to catch or handle snake',
              'safeTextAr': 'التقاط صورة بالجوال للعقرب/الأفعى من مسافة آمنة لمساعدة الطبيب بتحديد الترياق (Antivenom)',
              'safeTextEn': 'Snap a quick mobile photo of reptile from safe distance to help doctors match Antivenom',
              'safeExpAr': 'إجراء ذكي؛ الصورة تسهم في اختيار المصل الخاص دون تعريض أحد للدغة ثانية.',
              'safeExpEn': 'Smart action; photo helps ER physicians identify species for specific antivenom matching.',
              'safeOutAr': 'التقطت صورة آمنة للمحطة 5.',
              'safeOutEn': 'Took safe photo for Station 5.',
              'unsafeTextAr': 'اللحاق بالأفعى ومحاولة قطع رأسها باليد للإمساك بها',
              'unsafeTextEn': 'Chasing snake and grabbing it barehanded to bring dead body to ER',
              'unsafeExpAr': 'خطأ؛ محاولة الإمساك بالأفعى تسبب لدغة ثانية للمنقذ.',
              'unsafeExpEn': 'Error; handling live or freshly killed vipers frequently results in secondary bites.',
              'unsafeOutAr': 'تعرضت للدغة ثانية.',
              'unsafeOutEn': 'Secondary bite on rescuer.',
            },
            {
              'sitAr': 'نقل المصاب لطوارئ المستشفى (997/937). ما التوجيه الوقائي المسبق للكشتات؟',
              'sitEn': 'Transporting victim to ER via 997. Permanent desert footwear and safety rule?',
              'hintAr': 'ارتداء أحذية برية مرتفعة الساق وفحص الفراش والأحذية قبل ارتدائها بالصحراء',
              'hintEn': 'Wear high ankle desert boots; inspect shoes and bedding before use',
              'safeTextAr': 'نقل المصاب لـ 997، والالتزام بارتداء جزم برية مرتفعة ونفض الأحذية قبل لبسها بالصحراء',
              'safeTextEn': 'Rush to ER via 997, and strictly mandate high ankle boots and inspecting boots before putting feet in',
              'safeExpAr': 'إتمام كامل؛ فحص الأحذية واستخدام الكشاف بالليل يمنع 90% من لدغات البر.',
              'safeExpEn': 'Complete resolution; boot inspections and torch use at night prevent 90% of desert bites.',
              'safeOutAr': 'أكملت محطات إسعاف اللدغات الصحراوية بنجاح!',
              'safeOutEn': 'Successfully completed scorpion/snake bite scenario!',
              'unsafeTextAr': 'المشي حافي القدمين حول الخيمة ليلاً بالظلام',
              'unsafeTextEn': 'Walk barefoot around campsite in dark pitch night',
              'unsafeExpAr': 'خطأ؛ المشي حافياً بالليل يجعلك هدفا سهلاً للدغات العقارب الخفية.',
              'unsafeExpEn': 'Error; walking barefoot at night invites hidden scorpions and vipers to strike feet.',
              'unsafeOutAr': 'مخاطرة بالمشي حافياً.',
              'unsafeOutEn': 'Barefoot night walking risk.',
            },
          ],
        ),

        // Scenarios 5 to 9 for DESERT...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_5',
          categoryId: 'desert_safety',
          titleAr: 'تجهيزات الملاحة والسلامة بالرحلات البرية',
          titleEn: 'Desert Navigation & GPS Equipment Preparation',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتعلم الملاحة الصحراوية، الـ GPS، وبوصلة القبلة.',
          descriptionEn: 'Interactive 5-station scenario for desert GPS navigation & compass safety.',
          difficulty: 'سهل',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'التخطيط لرحلة برية في عمق الربع الخالي أو النفود. ما أهم تطبيق للملاحة بدون إنترنت؟',
              'sitEn': 'Planning trip deep into Rub al Khali or Nafud desert. Best offline GPS navigation app?',
              'hintAr': 'تحميل الخرائط الصحراوية غير المتصلة (OsmAnd / Maps.me) وتطبيقات الإحداثيات (GEO)',
              'hintEn': 'Download offline desert maps (OsmAnd / Maps.me) and offline GPS coordinate trackers',
              'safeTextAr': 'تحميل خرائط الصحراء غير المتصلة بالشبكة (Offline Maps) وحفظ نقاط العودة الإحداثية',
              'safeTextEn': 'Download offline satellite desert maps and save waypoints for return coordinates on phone',
              'safeExpAr': 'تخطيط ممتاز؛ الخرائط المحملة تعمل عبر أقمار الـ GPS دون الحاجة لأبراج الجوال.',
              'safeExpEn': 'Great planning; offline satellite maps rely purely on GPS chips independent of cell towers.',
              'safeOutAr': 'حمّلت الخرائط الميدانية للمحطة 2.',
              'safeOutEn': 'Downloaded offline maps for Station 2.',
              'unsafeTextAr': 'الاعتماد الكلي على خرائط البث المباشر (Google Maps) أثناء السير بالصحراء',
              'unsafeTextEn': 'Rely entirely on online streaming Google Maps while driving in remote desert',
              'unsafeExpAr': 'خطأ؛ انقطاع تغطية أبراج الجوال يفرغ الخرائط ويتركك بصفحة بيضاء.',
              'unsafeExpEn': 'Error; losing cell coverage clears map display leaving you with a blank screen.',
              'unsafeOutAr': 'اختفت الخريطة عند انقطاع الابراج.',
              'unsafeOutEn': 'Map blanked upon losing cell signal.',
            },
            {
              'sitAr': 'تجهيز جهاز الملاحة الفضائي اليدوي (Garmin GPS). ما الإجراء قبل الانطلاق؟',
              'sitEn': 'Preparing handheld Garmin GPS unit. Mandatory step before setting out?',
              'hintAr': 'معايرة البوصلة وتخزين موقع نقطة الانطلاق (Home Waypoint) وبطاريات إضافية',
              'hintEn': 'Calibrate compass, mark Home/Start waypoint, carry extra AA lithium batteries',
              'safeTextAr': 'تخزين نقطة الانطلاق (Start Point) وتوفير طقم بطاريات إضافية مع معايرة البوصلة',
              'safeTextEn': 'Mark starting campsite waypoint (Home) on GPS and pack spare AA batteries with compass calibration',
              'safeExpAr': 'تجهيز ذكي؛ نقطة العودة المحفوظة تتيح للجهاز رسم مسار تتبع عكسي (TrackBack) دقيق.',
              'safeExpEn': 'Smart prep; saved start waypoint enables automated TrackBack route navigation back to camp.',
              'safeOutAr': 'حفظت نقطة الانطلاق للمحطة 3.',
              'safeOutEn': 'Saved start waypoint for Station 3.',
              'unsafeTextAr': 'تشغيل الجهاز دون تسجيل نقطة البداية ودون بطاريات احتياطية',
              'unsafeTextEn': 'Turn on GPS without marking home waypoint or packing spare batteries',
              'unsafeExpAr': 'خطأ؛ نفاد البطارية أو عدم وجود نقطة مرجعية يعطل فائدة الملاحة.',
              'unsafeExpEn': 'Error; dead batteries or missing home waypoint renders GPS unit useless when lost.',
              'unsafeOutAr': 'نفذت البطارية دون نقطة رجوع.',
              'unsafeOutEn': 'Batteries died without home waypoint.',
            },
            {
              'sitAr': 'فقدان جهاز الـ GPS وتوقف الجوال. كيف تستدل على الاتجاهات بالبوصلة والنجوم ليلاً؟',
              'sitEn': 'Lost GPS and dead phone. How to find North using compass & North Star (Polaris)?',
              'hintAr': 'الاستدلال بنجم الجدي (Polaris) بدب الأكبر تحديد اتجاه الشمال الدائم',
              'hintEn': 'Locate North Star (Polaris) using Big Dipper pointer stars to fix TRUE NORTH',
              'safeTextAr': 'التعرف على نجم الجدي (Polaris) عبر الامتداد البصري لكوكبة الدب الأكبر لتحديد الشمال',
              'safeTextEn': 'Identify North Star (Polaris) by extending visual line from Big Dipper pointer stars to fix True North',
              'safeExpAr': 'معرفة صحراوية أصيلة؛ نجم الجدي يقع ثابت فوق القطب الشمالي الجغرافي دائماً.',
              'safeExpEn': 'Authentic desert skill; North Star remains fixed above geographic North Pole orientation.',
              'safeOutAr': 'حدّدت اتجاه الشمال بنجم الجدي للمحطة 4.',
              'safeOutEn': 'Fixed True North using Polaris for Station 4.',
              'unsafeTextAr': 'المشي العشوائي ليلاً دون الاستدلال بالنجوم أو البوصلة',
              'unsafeTextEn': 'Walk randomly at night without using stars or magnetic compass',
              'unsafeExpAr': 'خطأ؛ المشي العشوائي يدورك في حلقات مغلقة (Circular Wandering).',
              'unsafeExpEn': 'Error; random walking without directional anchors causes human body to walk in circles.',
              'unsafeOutAr': 'الدوران في حلقات مغلقة.',
              'unsafeOutEn': 'Wandered in circular loop.',
            },
            {
              'sitAr': 'توفير جهاز جهاز الاتصال باللاسلكي (VHF / UHF) بين سيارات الكشتة. ما القناة المعتمدة للطوارئ؟',
              'sitEn': 'Using two-way UHF/VHF radio between desert convoy cars. Emergency channel usage?',
              'hintAr': 'ضبط قنوات التواصل وتخصيص قناة نداء موحدة للطوارئ بين الفريق',
              'hintEn': 'Set agreed team frequency & keep battery saved for emergency distress calls',
              'safeTextAr': 'تثبيت قناة اللاسلكي الموحدة للفريق وإجراء فحص إشارة قبل الابتعاد عن القافلة',
              'safeTextEn': 'Agree on dedicated VHF convoy frequency and perform radio range test before splitting up',
              'safeExpAr': 'تواصل فعّال؛ الأجهزة اللاسلكية تغطي مسافات 15 كم وتضمن ترابط القافلة.',
              'safeExpEn': 'Effective comms; VHF radios cover 15 km ranges keeping desert convoy members connected.',
              'safeOutAr': 'اختبرت الاتصال اللاسلكي للمحطة 5.',
              'safeOutEn': 'Tested VHF radio comms for Station 5.',
              'unsafeTextAr': 'إيقاف جهاز اللاسلكي أو تغيير القناة دون علم باقي القافلة',
              'unsafeTextEn': 'Turn off radio or switch frequencies without notifying convoy leader',
              'unsafeExpAr': 'خطأ؛ تغيير القناة يعزلك عن أفراد القافلة في حال الانغراز.',
              'unsafeExpEn': 'Error; changing channels isolates vehicle from convoy rescue calls during sand traps.',
              'unsafeOutAr': 'انقطع الاتصال بالقافلة.',
              'unsafeOutEn': 'Lost radio contact with convoy.',
            },
            {
              'sitAr': 'العودة بسلامة من الرحلة البرية. ما المعيار الدائم لسلامة الملاحة؟',
              'sitEn': 'Returned safely from desert expedition. Permanent navigation preparedness rule?',
              'hintAr': 'دمج الوسائل الحديثة (GPS) مع البوصلة التقليدية والخرائط الورقية',
              'hintEn': 'Combine modern satellite GPS with traditional magnetic compass & paper maps',
              'safeTextAr': 'احتواء سيارة البر دائماً على بوصلة مغناطيسية، خريطة ورقية، وجهاز ملاحة الكتروني',
              'safeTextEn': 'Equip desert vehicle with redundant magnetic compass, paper map, and electronic GPS',
              'safeExpAr': 'إتمام كامل؛ توفير البدائل اليدوية يضمن النجاة عند تعطل الإلكترونيات.',
              'safeExpEn': 'Complete resolution; analog paper maps and magnetic compasses guarantee navigation if electronics fail.',
              'safeOutAr': 'أكملت محطات الملاحة والسلامة البرية بنجاح!',
              'safeOutEn': 'Successfully completed desert navigation safety scenario!',
              'unsafeTextAr': 'الاعتماد على الذاكرة الشخصية فقط في الصحراء دون أي خرائط',
              'unsafeTextEn': 'Rely solely on personal memory of landmarks without maps or compass',
              'unsafeExpAr': 'خطأ؛ تغير الكثبان الرملية والعواصف يمحو المعالم وتسبب التوهان.',
              'unsafeExpEn': 'Error; shifting sand dunes and dust storms erase landmarks confusing human memory.',
              'unsafeOutAr': 'تلاشي المعالم والتوهان.',
              'unsafeOutEn': 'Erased landmarks & disorientation.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_6',
          categoryId: 'desert_safety',
          titleAr: 'طوارئ العواصف الرملية وحجب الرؤية (العجاج)',
          titleEn: 'Severe Desert Dust Storm (Ajaj) & Zero Visibility Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع العواصف الرملية الجدارية أثناء القيادة والتخييم.',
          descriptionEn: 'Interactive 5-station scenario for managing severe desert dust storms.',
          difficulty: 'متوسط',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'ملاحظة جدار غباري أسود/أحمر (عاصفة رملية) يتقدم نحو سيارتك بالطريق البري. ما الإجراء الفوري؟',
              'sitEn': 'Massive wall of dust (sandstorm) approaching vehicle on desert highway. Immediate action?',
              'hintAr': 'الخروج التام عن الشارع الرئيسي وإيقاف السيارة بمكان آمن بعيداً عن الطريق',
              'hintEn': 'Pull completely off paved highway onto safe shoulder area away from traffic',
              'safeTextAr': 'الخروج التام عن أسفلت الطريق الرئيسي إلى جانب مرتفع آمن وإيقاف السيارة',
              'safeTextEn': 'Pull completely off paved travel lanes onto safe right shoulder stopping vehicle clear of traffic',
              'safeExpAr': 'تصرف آمن؛ انعدام الرؤية المباغت بالطريق السريع يسبب تصادمات مروعة بين السيارات.',
              'safeExpEn': 'Safe action; zero visibility on highways causes catastrophic multi-car pileup chain collisions.',
              'safeOutAr': 'خرجت عن الشارع للمحطة 2.',
              'safeOutEn': 'Pulled completely off road for Station 2.',
              'unsafeTextAr': 'التوقف المفاجئ في وسط مسار الشارع السريع وتدفق السيارات خلفك',
              'unsafeTextEn': 'Slam brakes to a complete stop right in middle of active travel lane',
              'unsafeExpAr': 'خطأ قاتل؛ التوقف بالمسار يجعلك هدفاً مستهدفاً لدهس الشاحنات القادمة خلفك.',
              'unsafeExpEn': 'Fatal error; stopping in active lane causes high-speed rear-end crashes from trailing trucks.',
              'unsafeOutAr': 'تصادم خلفي بالشاحنة.',
              'unsafeOutEn': 'Rear-end highway crash.',
            },
            {
              'sitAr': 'إيقاف السيارة بالجانب الآمن أثناء العاصفة. كيف تتصرف بالإضاءة والمكابح؟',
              'sitEn': 'Vehicle stopped safely off road during dust storm. Lights & brake pedal safety rule?',
              'hintAr': 'إطفاء الإضاءة العادية ومكابح القدم وتشغيل فلاش الطوارئ (Hazard Lights)',
              'hintEn': 'Turn off main driving headlights & foot brake; turn ON hazard emergency flashers',
              'safeTextAr': 'إيقاف محرك السيارة، تشغيل إشارات التحذير الرباعية (الرباعي)، ورفع القدم عن دواسة الفرملة',
              'safeTextEn': 'Turn off driving lights, engage parking brake, take foot off brake pedal, and turn ON hazard flashers',
              'safeExpAr': 'قاعدة ذهبية؛ رؤية أضواء الفرملة الحمراء تجعل السيارات الخلفية تظن أنك تسير وتتبعك لتصطدم بك.',
              'safeExpEn': 'Golden rule; red brake lights trick trailing drivers into following you off-road crashing into your car.',
              'safeOutAr': 'شغّلت إشارات الطوارئ للمحطة 3.',
              'safeOutEn': 'Engaged hazard flashers for Station 3.',
              'unsafeTextAr': 'إبقاء ضغط القدم على دواسة الفرملة لإنارة الأنوار الحمراء الخلفية',
              'unsafeTextEn': 'Keep foot pressed hard on brake pedal keeping brake lights continuously illuminated',
              'unsafeExpAr': 'خطأ؛ الأنوار الحمراء المشتعلة تضلل السيارات القادمة خلفك بالدخول فيك.',
              'unsafeExpEn': 'Error; constant red brake lights blind and guide trailing cars straight into your stopped trunk.',
              'unsafeOutAr': 'تضليل السيارات الخلفية.',
              'unsafeOutEn': 'Misled trailing highway traffic.',
            },
            {
              'sitAr': 'ضبط تكييف ونوافذ السيارة أثناء اجتياح الغبار الكثيف. ما الإعداد الصحيح للتكييف؟',
              'sitEn': 'Setting vehicle AC and windows during dense dust storm. Correct AC mode?',
              'hintAr': 'إغلاق النوافذ بالكامل وتشغيل التدوير الداخلي للهواء (Recirculation Mode)',
              'hintEn': 'Close all windows completely & switch AC to internal Recirculation Mode',
              'safeTextAr': 'إغلاق جميع النوافذ بإحكام وتشغيل التدوير الداخلي للتكييف لمنع دخول الغبار',
              'safeTextEn': 'Close all windows tightly and switch AC system to internal air recirculation mode',
              'safeExpAr': 'تأمين تنفسي؛ التدوير الداخلي يمنع سحب الأتربة الناعمة لكابينة الركاب وفلتر المحرك.',
              'safeExpEn': 'Respiratory defense; internal recirculation blocks micro-dust from choking cabin occupants.',
              'safeOutAr': 'شغّلت التدوير الداخلي للمحطة 4.',
              'safeOutEn': 'Set AC to internal recirculation for Station 4.',
              'unsafeTextAr': 'فتح النوافذ جزئياً أو ترك التكييف يشفط الهواء الخارجي',
              'unsafeTextEn': 'Leave windows cracked open or AC pulling fresh external air',
              'unsafeExpAr': 'خطأ؛ شفط الهواء الخارجي يملأ السيارة بالغبار ويسبب الاختناق.',
              'unsafeExpEn': 'Error; external intake fills cabin with suffocating dust choking passengers and clogging AC.',
              'unsafeOutAr': 'امتلأت الكابينة بالغبار.',
              'unsafeOutEn': 'Cabin filled with dust.',
            },
            {
              'sitAr': 'التواجد بالخيمة أثناء انقضاض العاصفة الرملية بالصحراء. كيف تثبت الخيمة؟',
              'sitEn': 'Inside tent when sandstorm hits campsite. How to secure tent structure?',
              'hintAr': 'ربط الأطناب الإضافية بمربط صخري وإغلاق فتحات التهوية من اتجاه الرياح',
              'hintEn': 'Anchor extra guy lines to heavy rocks; zip up windward mesh vents completely',
              'safeTextAr': 'ربط حبال الخيمة بأحجار ثقيلة وإغلاق جميع نوافذ الخيمة المواجهة لاتجاه الرياح',
              'safeTextEn': 'Anchor guy lines around heavy boulders and tightly zip all windward mesh flaps',
              'safeExpAr': 'تثبيت ممتاز؛ الثقل الصخري يمنع اقتلاع أوتاد الخيمة تحت هبات الرياح العاتية.',
              'safeExpEn': 'Great anchoring; rock weights prevent guy stakes from ripping out under high wind gusts.',
              'safeOutAr': 'ثبّت الخيمة بالحجارة للمحطة 5.',
              'safeOutEn': 'Anchored tent with boulders for Station 5.',
              'unsafeTextAr': 'ترك نوافذ الخيمة مفتوحة للهواء دون تثبيت الحبال',
              'unsafeTextEn': 'Leave tent flaps open for breeze without anchoring extra lines',
              'unsafeExpAr': 'خطأ؛ دخول الرياح داخل الخيمة يرفع السقف كالمظلة ويقتلع الخيمة بالكامل.',
              'unsafeExpEn': 'Error; wind entering tent traps air under canopy blowing structure away into dunes.',
              'unsafeOutAr': 'اقتلعت الرياح الخيمة.',
              'unsafeOutEn': 'Tent blown away by storm gusts.',
            },
            {
              'sitAr': 'انقضاء العاصفة الرملية واستعادة الرؤية. ما الفحص الميكانيكي الواجب للسيارة؟',
              'sitEn': 'Dust storm passes and visibility recovers. Mandatory vehicle mechanical check?',
              'hintAr': 'فحص ونفض فلتر هواء المحرك (Air Filter) من الرمل قبل مواصلة القيادة',
              'hintEn': 'Inspect & knock sand out of engine air filter before resuming highway speeds',
              'safeTextAr': 'فتح الكبوت ونفض الأتربة والرمال عن فلتر هواء المحرك لضمان عدم انسداد المحرك',
              'safeTextEn': 'Open hood and tap out accumulated sand from engine air filter before resuming journey',
              'safeExpAr': 'إتمام كامل؛ تنظيف الفلتر يمنع اختناق المحرك وارتفاع حرارته أثناء السير.',
              'safeExpEn': 'Complete resolution; cleaning air filter restores oxygen flow stopping engine overheating and power loss.',
              'safeOutAr': 'أكملت محطات طوارئ العواصف الرملية بنجاح!',
              'safeOutEn': 'Successfully completed dust storm safety scenario!',
              'unsafeTextAr': 'مواصلة السير بسرعة عالية بفلتر هواء مكتوم بالرمال',
              'unsafeTextEn': 'Drive off at high speed with air filter completely choked with sand',
              'unsafeExpAr': 'خطأ؛ الفلتر المكتوم يسبب ارتفاع حرارة المحرك وتوقف السيارة.',
              'unsafeExpEn': 'Error; choked air filter causes fuel mixture imbalance and severe engine thermal breakdown.',
              'unsafeOutAr': 'سخونة واختناق المحرك.',
              'unsafeOutEn': 'Engine choked & overheated.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_7',
          categoryId: 'desert_safety',
          titleAr: 'سلامة شبات الضوء والحطب بالصحراء',
          titleEn: 'Campfire & Carbon Monoxide Safety in Desert',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لإشعال شبات النار بسلامة وتجنب الاختناق بالخيمة.',
          descriptionEn: 'Interactive 5-station scenario for campfire safety & carbon monoxide prevention.',
          difficulty: 'سهل',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'إشعال شبة النار بالليل أثناء الكشتة. ما الموقع الآمن لبؤرة النار؟',
              'sitEn': 'Lighting campfire at night during desert trip. Safe fire pit location?',
              'hintAr': 'إبعاد النار مسافة 5 أمتار على الأقل عن الخيام والسيارات وعكس اتجاه الرياح',
              'hintEn': 'Keep campfire at least 5 meters away downwind from tents and vehicles',
              'safeTextAr': 'حفر بؤرة النار على مسافة 5 أمتار عن الخيام والسيارات وفي اتجاه أسفل الريح',
              'safeTextEn': 'Dig campfire pit at least 5 meters downwind clear of tents, dry brush, and vehicles',
              'safeExpAr': 'تصرف أساسي؛ إبعاد النار يمنع وصول شرر الحطب الملتد إلى قماش الخيمة.',
              'safeExpEn': 'Primary rule; distance prevents floating embers from igniting synthetic tent fabrics.',
              'safeOutAr': 'أعدَدت بؤرة النار بمسافة آمنة للمحطة 2.',
              'safeOutEn': 'Prepared fire pit at safe distance for Station 2.',
              'unsafeTextAr': 'إشعال النار ملاصقة تماماً لباب الخيمة لزيادة التدفئة',
              'unsafeTextEn': 'Light campfire directly adjacent to tent entrance for extra warmth',
              'unsafeExpAr': 'خطأ جسيم؛ الشرر المتطاير يثقب قماش الخيمة ويشعل الحريق بجميع المتواجدين.',
              'unsafeExpEn': 'Severe error; flying sparks ignite flammable tent walls trapping occupants.',
              'unsafeOutAr': 'اشتعل باب الخيمة بالشرر.',
              'unsafeOutEn': 'Sparks ignited tent wall.',
            },
            {
              'sitAr': 'هل يجوز إدخال المنقل أو وجار الحطب الجمر المشتعل داخل الخيمة المغلقة للنوم؟',
              'sitEn': 'Should you bring glowing charcoal/fire pit INSIDE a sealed tent overnight for sleeping?',
              'hintAr': 'حظر إدخال الجمر أو الحطب المشتعل داخل الخيام المعتِمة مطلقاً لتجنب الاختناق',
              'hintEn': 'STRICTLY FORBIDDEN to bring burning charcoal/wood inside enclosed tents (CO toxicity)',
              'safeTextAr': 'إطفاء النار أو إبقائها بالخارج، وحظر إدخال الجمر داخل الخيمة المغلقة نهائياً',
              'safeTextEn': 'Extinguish or leave coals outside; STRICTLY forbid bringing burning embers inside closed tent',
              'safeExpAr': 'قاعدة نجاة حتمية؛ الجمر ينبعث منه غاز أول أكسيد الكربون (CO) السام الذي يقتل صامتاً أثناء النوم.',
              'safeExpEn': 'Vital survival rule; burning coals emit odorless Carbon Monoxide (CO) gas causing silent death during sleep.',
              'safeOutAr': 'بقيت الجمر بالخارج للمحطة 3.',
              'safeOutEn': 'Kept embers outside tent for Station 3.',
              'unsafeTextAr': 'سحب المنقل المشتعل بالجمر إلى داخل الخيمة وإغلاق السحاب',
              'unsafeTextEn': 'Pull glowing charcoal basin inside tent and zip door closed for warm sleep',
              'unsafeExpAr': 'خطأ قاتل؛ غاز أول أكسيد الكربون يحل محل الأكسجين بالدم ويسبب الاختناق الصامت.',
              'unsafeExpEn': 'Fatal error; CO gas replaces oxygen in hemoglobin causing undetected asphyxiation death.',
              'unsafeOutAr': 'اختناق صامت بالغاز.',
              'unsafeOutEn': 'Silent carbon monoxide poisoning.',
            },
            {
              'sitAr': 'إشعال النار باستخدام البنزين أو الوقود السريع. ما تقييم السلامة؟',
              'sitEn': 'Using gasoline or accelerants to ignite campfire wood. Safety evaluation?',
              'hintAr': 'حظر سكب البنزين على النار أو الحطب، واستخدام المكعبات الشمعية الآمنة',
              'hintEn': 'NEVER pour gasoline on campfire; use safe paraffin fire-lighter cubes',
              'safeTextAr': 'استخدام مكعبات إشعال النار الشمعية الآمنة وتجنب سكب البنزين نهائياً',
              'safeTextEn': 'Use wax/paraffin fire-starter cubes strictly avoiding gasoline or liquid accelerants',
              'safeExpAr': 'اختيار آمن؛ البنزين يتبخر فوراً ويصنع غيمة أبخرة انفجارية بوجه من يشعل النار.',
              'safeExpEn': 'Safe choice; gasoline vaporizes instantly forming an explosive vapor cloud flashing back at user.',
              'safeOutAr': 'استخدمت المكعبات الآمنة للمحطة 4.',
              'safeOutEn': 'Used wax starter cubes for Station 4.',
              'unsafeTextAr': 'سكب البنزين مباشرة من الجالون فوق الحطب ثم إلقاء الكبريت',
              'unsafeTextEn': 'Pour gasoline directly from plastic jug onto logs and toss match',
              'unsafeExpAr': 'خطأ؛ الارتداد اللهبي يتبع بخار البنزين لينفجر جالون الوقود بيدك.',
              'unsafeExpEn': 'Error; flame flashes back up fuel stream exploding gasoline jug in user\'s hand.',
              'unsafeOutAr': 'انفجر جالون البنزين.',
              'unsafeOutEn': 'Gasoline jug exploded.',
            },
            {
              'sitAr': 'التعامل مع الرياح المفاجئة التي تنشر الشرر حول الأعشاب الجافة بالصحراء. كيف تحمي الموقع؟',
              'sitEn': 'Sudden wind blowing sparks toward dry desert brush. How to protect area?',
              'hintAr': 'إحاطة النار بحجارة دائرية وتوفير سطل رمل أو ماء بجانب الشبة',
              'hintEn': 'Enclose fire with stone ring & keep bucket of sand/water nearby',
              'safeTextAr': 'تطويق بؤرة النار بحجارة دائرية مرتفعة وتوفير سطل رمل/ماء بجانب المنقل',
              'safeTextEn': 'Build a raised circular stone ring around fire pit and keep a bucket of sand/water ready',
              'safeExpAr': 'تطويق ممتاز؛ الحجارة تحجب الرياح والسطل يطفئ أي شرارة قبل انتشار الحريق.',
              'safeExpEn': 'Great enclosure; stone ring acts as windbreak while sand bucket instantly smothers stray sparks.',
              'safeOutAr': 'طوّقت النار بالحجارة للمحطة 5.',
              'safeOutEn': 'Enclosed fire with stone ring for Station 5.',
              'unsafeTextAr': 'إشعال النار على الرمال المكشوفة بين الأعشاب الجافة اليابسة',
              'unsafeTextEn': 'Light fire on open sand directly surrounded by dry brush weeds',
              'unsafeExpAr': 'خطأ؛ تطاير الشرر على الأعشاب الجافة يسبب حرائق برية سريعة الانتشار.',
              'unsafeExpEn': 'Error; airborne sparks landing on dry brush start uncontrollable wildfire blazes.',
              'unsafeOutAr': 'اشتعلت الأعشاب الجافة.',
              'unsafeOutEn': 'Dry brush ignited.',
            },
            {
              'sitAr': 'الاستعداد للمغادرة أو النوم. كيف تطفئ النار والجمر بشكل كامل وآمن؟',
              'sitEn': 'Preparing to sleep or break camp. How to completely & safely extinguish campfire?',
              'hintAr': 'دفن الجمر بالرمال وكسر حرارتها بالماء للتأكد من انطفائها كلياً',
              'hintEn': 'Douse embers with water and bury thoroughly with sand until cool',
              'safeTextAr': 'سكب الماء الوفير فوق الجمر، تقليبه، ثم دفنه بالرمال والتأكد من برودته التامة',
              'safeTextEn': 'Douse embers thoroughly with water, stir ash, and bury with sand until cold to touch',
              'safeExpAr': 'إتمام كامل؛ التفريغ والمحاصرة تضمن عدم إعادة اشتعال الجمر بفعل رياح الفجر.',
              'safeExpEn': 'Complete resolution; dousing and burying prevent morning winds from rekindling hidden hot embers.',
              'safeOutAr': 'أكملت محطات سلامة شبات النار بنجاح!',
              'safeOutEn': 'Successfully completed campfire safety scenario!',
              'unsafeTextAr': 'ترك الجمر مشتعلاً ومكشوفاً للرياح عند المغادرة',
              'unsafeTextEn': 'Walk away leaving glowing coals exposed to morning wind',
              'unsafeExpAr': 'خطأ؛ هبوب الرياح ينقل الجمر المشتعل للمخيمات والسيارات المجاورة.',
              'unsafeExpEn': 'Error; morning wind gusts blow hot embers onto neighboring tents and dry foliage.',
              'unsafeOutAr': 'انتقال الجمر بالرياح.',
              'unsafeOutEn': 'Embers rekindled by wind.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_8',
          categoryId: 'desert_safety',
          titleAr: 'طوارئ انقلاب وسقوط سيارات الدفع الرباعي بالكثبان',
          titleEn: '4WD Vehicle Dune Rollover & Steep Incline Safety',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لقيادة الكثبان المائلة (التطعيس) وتجنب الانقلاب.',
          descriptionEn: 'Interactive 5-station scenario for 4WD dune driving & rollover prevention.',
          difficulty: 'صعب',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'صعود طعس رملي شديد الانحدار بالسيارة وتوقف اندفاع السيارة قرب القمة. ما الإجراء القيادي الصحيح؟',
              'sitEn': 'Ascending steep sand dune; vehicle loses momentum near crest. Correct driving maneuver?',
              'hintAr': 'الرجوع للخلف بشكل مستقيم تماماً بنفس مسار الصعود وتجنب تدوير المقود جانباً',
              'hintEn': 'Reverse STRAIGHT back down the incline in reverse gear; NEVER turn wheel sideways',
              'safeTextAr': 'تعشيق الـ R والرجوع للخلف باستقامة تامة دون تدوير عجلة القيادة يميناً أو يساراً',
              'safeTextEn': 'Shift into Reverse and back straight down hill in fall-line without turning steering wheel sideways',
              'safeExpAr': 'مناورة احترافية؛ الرجوع المستقيم يحافظ على مركز ثقل السيارة ويمنع انقلابها الجانبي.',
              'safeExpEn': 'Pro maneuver; reversing straight along fall-line maintains low center of gravity preventing side rollover.',
              'safeOutAr': 'رجعت للخلف باستقامة للمحطة 2.',
              'safeOutEn': 'Reversed straight down fall-line for Station 2.',
              'unsafeTextAr': 'تدوير عجلة القيادة بأقصى قوة والانعطاف الجانبي على زاوية الميلان',
              'unsafeTextEn': 'Turn steering wheel hard to side trying to U-turn on steep slope face',
              'unsafeExpAr': 'خطأ قاتل؛ الانعطاف الجانبي بالمنحدر يقلب السيارة دحرجياً لأسفل الطعس.',
              'unsafeExpEn': 'Fatal error; turning sideways on a steep incline triggers catastrophic multi-roll side rollover.',
              'unsafeOutAr': 'انقلاب جانبي للسيارة.',
              'unsafeOutEn': 'Side rollover down dune face.',
            },
            {
              'sitAr': 'ربط أحزمة الأمان لجميع ركاب سيارة الدفع الرباعي أثناء التطعيس بالرمال. ما أهميته الحرج؟',
              'sitEn': 'Fastening seatbelts for all 4WD occupants during dune driving. Critical necessity?',
              'hintAr': 'إلزام جميع الركاب بربط حزام الأمان يمنع القذف الخارجي عند الانقلاب المفاجئ',
              'hintEn': 'Mandate seatbelts for all passengers; prevents ejection during unexpected dune tumbles',
              'safeTextAr': 'إلزام جميع الركاب بالمركبة بربط أحزمة الأمان قبل بدء صعود ونزول الكثبان',
              'safeTextEn': 'Enforce mandatory seatbelt buckling for all front and rear occupants before tackling sand dunes',
              'safeExpAr': 'تأمين حياة؛ الحزام يبقيك داخل الهيكل المحمي ويمنع قذفك خارج السيارة أثناء الانقلاب.',
              'safeExpEn': 'Life saving; seatbelts retain occupants inside roll cage envelope preventing fatal vehicle ejection.',
              'safeOutAr': 'أمنت أحزمة الركاب للمحطة 3.',
              'safeOutEn': 'Secured all passenger seatbelts for Station 3.',
              'unsafeTextAr': 'فك أحزمة الأمان بحجة سهولة الحركة والقفز داخل الكابينة',
              'unsafeTextEn': 'Unbuckle seatbelts claiming it allows better posture and movement',
              'unsafeExpAr': 'خطأ؛ القذف الخارجي أثناء انقلاب السيارة هو السبب الأول للوفيات بالتطعيس.',
              'unsafeExpEn': 'Error; occupant ejection during rollover is the leading cause of fatality in off-road crashes.',
              'unsafeOutAr': 'مخاطرة بالقذف الخارجي.',
              'unsafeOutEn': 'Occupant ejection risk.',
            },
            {
              'sitAr': 'توقف السيارة مائلة بدرجة حادة على جرف الطعس وخطر الانقلاب قائم. كيف يترجل الركاب؟',
              'sitEn': 'Vehicle resting at dangerous angle on dune crest risking rollover. How to exit safely?',
              'hintAr': 'الترجل بحذر شديد من الجهة المرتفعة (أعلى المنحدر) وتجنب فتح الأبواب السفلية',
              'hintEn': 'Exit carefully from UP-SLOPE high side doors ONLY; do NOT open low-side doors',
              'safeTextAr': 'الترجل ببطء شديد من الأبواب المرتفعة (الجهة العليا للمنحدر) لتجنب اختلال التوازن',
              'safeTextEn': 'Exit vehicle carefully from up-slope (high side) doors only, keeping body weight on high side',
              'safeExpAr': 'إخلاء ذكي؛ الخروج من الجهة العليا يحافظ على ثقل السيارة وتمنع ميلانها للأسفل.',
              'safeExpEn': 'Smart evacuation; high-side exit prevents disturbing vehicle center of gravity toward roll vector.',
              'safeOutAr': 'ترجّلت من الأبواب العليا للمحطة 4.',
              'safeOutEn': 'Exited safely from up-slope doors for Station 4.',
              'unsafeTextAr': 'فتح الأبواب السفلية والنزول تحت جهة ميلان السيارة',
              'unsafeTextEn': 'Open low-side doors and step out right beneath tilting lower car frame',
              'unsafeExpAr': 'خطأ؛ نزول الركاب من الأسفل يرجح كفة الوزن وتقلب السيارة فوقهم.',
              'unsafeExpEn': 'Error; stepping out low side shifts weight causing vehicle to roll over crushing exiting passengers.',
              'unsafeOutAr': 'انقلبت السيارة للأسفل.',
              'unsafeOutEn': 'Car rolled onto lower side.',
            },
            {
              'sitAr': 'تثبيت السيارة المائلة بواسطة سيارة إنقاذ أخرى وسلسلة سحب (Snatch Strap). كيف تثبت حبل السحب؟',
              'sitEn': 'Securing tilted vehicle using recovery strap (Kinetic Rope). How to attach tow line?',
              'hintAr': 'تثبيت الحبل بنقاط السحب المعتمدة بالهيكل الصلب (Tow Points) وتجنب الصدام',
              'hintEn': 'Attach kinetic strap strictly to rated chassis recovery points; NEVER to bumpers',
              'safeTextAr': 'ربط حبل السحب بنقاط السحب المعتمدة الملحومة بشاسيه السيارة المباشر',
              'safeTextEn': 'Attach kinetic recovery strap using rated shackles strictly to chassis-mounted recovery points',
              'safeExpAr': 'تثبيت معتمد؛ نقاط الشاسيه تتحمل قوة الشد العالية دون انكسار الخطاف.',
              'safeExpEn': 'Rated attachment; heavy chassis tow points withstand high kinetic snatch forces without snapping.',
              'safeOutAr': 'ربطت الحبل بنقاط الشاسيه للمحطة 5.',
              'safeOutEn': 'Attached strap to rated tow points for Station 5.',
              'unsafeTextAr': 'ربط حبل السحب بعمود الصدام التجاري أو حول محور الإطار',
              'unsafeTextEn': 'Hook recovery rope onto plastic bumper shell or around steering axle tie-rod',
              'unsafeExpAr': 'خطأ قاتل؛ اقتلاع الصدام أو الخطاف يتحول إلى قذيفة معدنية طائرة بقوة الشد.',
              'unsafeExpEn': 'Fatal mistake; yanking unrated bumper hooks converts shackle into a lethal metal shrapnel missile.',
              'unsafeOutAr': 'انكسر الخطاف بقوة الشد.',
              'unsafeOutEn': 'Shackle snapped into projectile.',
            },
            {
              'sitAr': 'تخليص السيارة وسحبها برفق للأسفل. ما التوجيه الدائم لقيادة الكثبان البرية؟',
              'sitEn': 'Vehicle safely recovered. Permanent safety protocol for off-road dune driving?',
              'hintAr': 'عدم القيادة المنفردة بالصحراء وتوفير راية السلامة المرتفعة (Safety Flag Pole)',
              'hintEn': 'Never drive solo in dunes; equip high-visibility dune safety flag pole',
              'safeTextAr': 'عدم الخروج للتطعيس كسيارة واحدة منفردة وتثبيت الراية الفسفورية المرتفعة (Safety Flag)',
              'safeTextEn': 'Never tackle dunes alone (minimum 2 vehicles) and mount a high-visibility whip safety flag',
              'safeExpAr': 'إتمام كامل؛ راية السلامة تتيح للسيارات الأخرى رؤيتك خلف قمم الكثبان لتجنب الاصطدام Head-on.',
              'safeExpEn': 'Complete resolution; high safety whip flag alerts oncoming dune drivers over blind crests.',
              'safeOutAr': 'أكملت محطات سلامة قيادة الكثبان بنجاح!',
              'safeOutEn': 'Successfully completed 4WD dune driving scenario!',
              'unsafeTextAr': 'التطعيس المنفرد بالليل بدون راية وبسيارة واحدة فقط',
              'unsafeTextEn': 'Go solo dune bashing at night without safety flag or secondary recovery vehicle',
              'unsafeExpAr': 'خطأ؛ التطعيس المنفرد يعرضك للانحصار والاصطدام دون وجود من يسعفك.',
              'unsafeExpEn': 'Error; solo dune driving invites catastrophic accidents with no support vehicle to assist.',
              'unsafeOutAr': 'مخاطرة التطعيس المنفرد.',
              'unsafeOutEn': 'Solo dune bashing risk persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_desert_9',
          categoryId: 'desert_safety',
          titleAr: 'طوارئ انقطاع الوقود وتعطل المحرك في الفياض',
          titleEn: 'Desert Out of Fuel & Engine Breakdown Emergency',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع نفاد البنزين وتعطل السيارة بالفياض والبر.',
          descriptionEn: 'Interactive 5-station scenario for fuel depletion & breakdown deep in desert.',
          difficulty: 'متوسط',
          icon: 'landscape',
          colorHex: 0xFFD97706,
          stations: [
            {
              'sitAr': 'أضاءت لمبة البنزين البرتقالية وسط الصحراء البعيدة عن المحطات. ما أول إجراء لترشيد الوقود؟',
              'sitEn': 'Low fuel indicator lights up deep in desert far from gas stations. First fuel saving action?',
              'hintAr': 'إيقاف التكييف والقيادة بسرعة منتظمة دون تسارع مفاجئ (60-80 كم/س)',
              'hintEn': 'Turn off AC compressor and maintain steady smooth speed (60-80 km/h)',
              'safeTextAr': 'إيقاف تشغيل التكييف والقيادة بضغط دواسة منتظم بين 60-80 كم/س للوصول لأقرب طريق',
              'safeTextEn': 'Turn off AC compressor, close windows partially, and drive smoothly at 60-80 km/h toward road',
              'safeExpAr': 'تصرف ذكي؛ إيقاف التكييف يوفر 15% من استهلاك الوقود ويطيل مسافة السير.',
              'safeExpEn': 'Smart response; switching off AC cuts engine load saving up to 15% remaining fuel.',
              'safeOutAr': 'رشّدت استهلاك البنزين للمحطة 2.',
              'safeOutEn': 'Economized fuel consumption for Station 2.',
              'unsafeTextAr': 'زيادة السرعة لأقصى طاقة للوصول بسرعة قبل انطفاء المحرك',
              'unsafeTextEn': 'Floor gas pedal running at 140 km/h hoping to reach gas station faster',
              'unsafeExpAr': 'خطأ؛ السرعة العالية تضاعف استهلاك الوقود وتفرغ التانكي سريعا.',
              'unsafeExpEn': 'Error; high speed drastically increases fuel burn rate emptying tank twice as fast.',
              'unsafeOutAr': 'فرغ التانكي سريعاً.',
              'unsafeOutEn': 'Fuel tank depleted prematurely.',
            },
            {
              'sitAr': 'انطفأ المحرك تماماً ونفد الوقود. كيف توقف السيارة وتؤمن موقعها بالصحراء؟',
              'sitEn': 'Engine dies completely out of fuel. How to stop and secure position in desert?',
              'hintAr': 'التوقف بمرتفع آمن بعيداً عن مجرى الأودية ومسارات الكثبان',
              'hintEn': 'Coast vehicle to a stop on safe flat high ground away from wadi beds & dune drops',
              'safeTextAr': 'استغلال اندفاع السيارة للتوقف على أرض مستوية مرتفعة بعيداً عن الكثبان المعتمة',
              'safeTextEn': 'Coast momentum to park vehicle on flat elevated ground clearly visible from surrounding area',
              'safeExpAr': 'توقف ممتاز؛ التوقف بموقع بارز وسهل الرؤية يحميك من اصطدام السيارات وتدفق السيول.',
              'safeExpEn': 'Great parking; high flat ground provides maximum visibility for searchers and avoids flood basins.',
              'safeOutAr': 'أوقفت السيارة بموقع آمن للمحطة 3.',
              'safeOutEn': 'Parked on high flat ground for Station 3.',
              'unsafeTextAr': 'ترك السيارة تنحدر وتتوقف بأسفل منحدر حاد بين الكثبان',
              'unsafeTextEn': 'Let car roll down into a blind depression between deep dunes',
              'unsafeExpAr': 'خطأ؛ التوقف بالمنخفضات يحجب المركبة عن فرق البحث وطائرات الإنقاذ.',
              'unsafeExpEn': 'Error; parking in deep sand depressions hides vehicle from ground and aerial search teams.',
              'unsafeOutAr': 'اختفت السيارة بالمنخفض.',
              'unsafeOutEn': 'Vehicle hidden in sand bowl.',
            },
            {
              'sitAr': 'الاتصال بالطوارئ أو جمعيات الإنقاذ التطوعية (كجمعية عون 0500114480 أو غوث). كيف تحدد إحداثياتك؟',
              'sitEn': 'Calling emergency or volunteer desert rescue (Ewn/Ghowth). How to share exact location?',
              'hintAr': 'قراءة واستخراج الإحداثيات الجغرافية (Coordinates) من تطبيق الجوال أو الـ GPS',
              'hintEn': 'Extract and share exact GPS Coordinates (Degrees Minutes Seconds or Decimal)',
              'safeTextAr': 'استخراج الإحداثيات الجغرافية (GPS Coordinates) من الجوال وإرسالها نصياً لفرق الإنقاذ',
              'safeTextEn': 'Extract exact GPS coordinates (Latitude & Longitude) from phone compass/map app and SMS to rescue dispatch',
              'safeExpAr': 'إجراء حاسم؛ الإحداثيات الدقيقة تتيح لفرق الإنقاذ التوجه المباشر لموقعك دون تشتت.',
              'safeExpEn': 'Critical step; precise coordinates allow rescue teams to navigate straight to your vehicle grid.',
              'safeOutAr': 'أرسلت الإحداثيات الدقيقة للمحطة 4.',
              'safeOutEn': 'Sent exact GPS coordinates for Station 4.',
              'unsafeTextAr': 'إعطاء وصف شفوي مبهم مثل: "أنا بجانب شجرة كبيرة بجوار كليب رملي"',
              'unsafeTextEn': 'Give vague verbal description like: "I am near a big tree beside a sand hill"',
              'unsafeExpAr': 'خطأ؛ الوصف العشوائي لا يفيد في صحراء شاسعة تحتوي آلاف الأشجار والتلال.',
              'unsafeExpEn': 'Error; vague descriptions are useless in vast deserts with thousands of identical trees & hills.',
              'unsafeOutAr': 'تعذر تحديد الموقع بالوصف.',
              'unsafeOutEn': 'Vague description led to search delay.',
            },
            {
              'sitAr': 'انتظار وصول فرق الإنقاذ بالنهار في ظل درجات حرارة مرتفعة. كيف تحمي جسدك؟',
              'sitEn': 'Awaiting rescue team arrival during hot desert day. How to manage thermal safety?',
              'hintAr': 'الجلوس داخل السيارة مع فتح الأبواب المعاكسة للشمس للتظليل وتوفير الهواء',
              'hintEn': 'Rest inside car shade with cross-ventilation or under a fabric tarp; avoid ground heat',
              'safeTextAr': 'الاستظلال بظل السيارة وتوفير تهوية جانبية مع رفع المفارش عن الرمال الحارة',
              'safeTextEn': 'Sit in shaded shadow of vehicle using fabric tarp for extra shade, resting above hot ground',
              'safeExpAr': 'تظليل ذكي؛ حرارة الرمال المباشرة تصل لـ 60°C والاستظلال يمنع ضربات الشمس.',
              'safeExpEn': 'Smart shade; direct desert sand reaches 60°C, staying elevated in shade prevents thermal shock.',
              'safeOutAr': 'استظللت بأمان للمحطة 5.',
              'safeOutEn': 'Rested safely in vehicle shade for Station 5.',
              'unsafeTextAr': 'الاستلقاء المباشر على الرمال الساخنة تحت أشعة الشمس العمودية',
              'unsafeTextEn': 'Lie down directly on scorching bare sand under direct noon sunlight',
              'unsafeExpAr': 'خطأ؛ التلامس المباشر مع الرمال الحارة يسبب حروق جلدية وارتفاع سريع للحرارة.',
              'unsafeExpEn': 'Error; direct contact with 60°C sand causes skin contact burns and rapid heatstroke.',
              'unsafeOutAr': 'ارتفعت حرارة الجسد.',
              'unsafeOutEn': 'Rapid body overheating.',
            },
            {
              'sitAr': 'وصول فريق الإغاثة وتزويد السيارة بالوقود. ما التجهيز الوقائي الدائم للرحلات القادمة؟',
              'sitEn': 'Rescue team arrives supplying fuel. Permanent desert trip prep standard?',
              'hintAr': 'حمل جالون بنزين إضافي مخصص للصحراء (Jerrican) والتزود بالوقود قبل دخول البر',
              'hintEn': 'Carry extra certified metal fuel jerrycan & fill main tank before entering desert',
              'safeTextAr': 'التزود التام بالوقود من آخر محطة وحمل جالون بنزين معدني محكم (Jerrycan) مخصص للبر',
              'safeTextEn': 'Fill main fuel tank completely at last highway station and carry a certified metal spare fuel jerrycan',
              'safeExpAr': 'إتمام كامل؛ التزود المسبق بالوقود والجالون الإضافي يلغي مخاطر الانقطاع بالبر.',
              'safeExpEn': 'Complete resolution; full tank and spare metal jerrycan ensure ample fuel reserve for desert trips.',
              'safeOutAr': 'أكملت محطات طوارئ انقطاع الوقود بالصحراء بنجاح!',
              'safeOutEn': 'Successfully completed desert out of fuel scenario!',
              'unsafeTextAr': 'الدخول للصحراء بتانكي بنزين نصف فارغ دون جالون احتياطي',
              'unsafeTextEn': 'Enter deep desert trails with half-empty fuel tank and zero backup jerrycan',
              'unsafeExpAr': 'خطأ؛ قيادة الكثبان تستهلك ضعفي البنزين مقارنة بالشارع المسفلت.',
              'unsafeExpEn': 'Error; off-road sand driving consumes double the fuel rate of smooth highway driving.',
              'unsafeOutAr': 'تكرار مخاطر انقطاع الوقود.',
              'unsafeOutEn': 'Recurrent fuel depletion risk.',
            },
          ],
        ),
      ];
}
