import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosHeat {
  static List<Scenario> get list => [
        // 1. Heat Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_1',
          categoryId: 'heat',
          titleAr: 'الإجهاد الحراري وضربات الشمس صيفاً',
          titleEn: 'Heatstroke & Extreme Summer Heat',
          descriptionAr: 'محاكاة تفاعلية من 5 محطات للتعامل مع ضربات الشمس في أجواء الصيف القاسية.',
          descriptionEn: 'Interactive 5-station scenario for managing sunstroke and heat exhaustion.',
          difficulty: 'سهل',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'سقط زميل في الموقع مغشياً عليه تحت أشعة الشمس المباشرة. ما الإجراء الأولي؟',
              'sitEn': 'Co-worker collapses under direct scorching summer sun. Initial action?',
              'hintAr': 'نقل المصاب فوراً إلى مكان مظلل، بارد، ومكيف لتخفيف درجة الحرارة المحيطة',
              'hintEn': 'Move victim immediately into shaded, cool, air-conditioned environment',
              'safeTextAr': 'نقل المصاب فوراً إلى منطقة مظللة ومكيفة وتخفيف الملابس الثقيلة',
              'safeTextEn': 'Move victim to shaded air-conditioned spot and loosen heavy clothing',
              'safeExpAr': 'تصرف ممتاز؛ إبعاد المصاب عن مصدر الحرارة يوقف ارتفاع حرارة الدماغ.',
              'safeExpEn': 'Excellent action; removing source heat prevents further thermal neurological damage.',
              'safeOutAr': 'نقلت المصاب للظل وتوجهت للمحطة 2.',
              'safeOutEn': 'Moved victim into shade, moving to Station 2.',
              'unsafeTextAr': 'تركه في مكانه تحت الشمس وسكب الماء المغلي لتنشيطه',
              'unsafeTextEn': 'Leave victim on hot ground pouring warm water over face',
              'unsafeExpAr': 'خطأ جسيم؛ بقاء المصاب تحت الشمس يرفع الحرارة لمدى خطير قاتل.',
              'unsafeExpEn': 'Severe error; leaving victim under sun pushes core temp to fatal levels.',
              'unsafeOutAr': 'تدهورت حالة المصاب.',
              'unsafeOutEn': 'Victim core temp reached critical point.',
            },
            {
              'sitAr': 'حرارة مصاب ضربة الشمس ارتفعت لـ 40 درجة مئوية. كيف تبرد جسمه؟',
              'sitEn': 'Sunstroke victim core temp spike at 40°C. How to rapidly cool body?',
              'hintAr': 'وضع كمادات ماء فاتر أو بارد على الرقبة، الإبطين، والمغبن حيث الشرايين الكبرى',
              'hintEn': 'Apply cool damp cloths to neck, armpits, and groin where main blood vessels pass',
              'safeTextAr': 'وضع كمادات ماء بارد على الرقبة، أسفل الإبطين، والمغبن لتبريد الشرايين',
              'safeTextEn': 'Apply cold damp packs to neck, armpits, and groin to cool major arteries',
              'safeExpAr': 'تقنية إسعافية متقدمة؛ تبريد الشرايين الرئيسة يخفض حرارة الجسم الداخلية بسرعة.',
              'safeExpEn': 'Advanced paramedic technique; cooling major vessels drops internal core temp fast.',
              'safeOutAr': 'بدأت حرارة المصاب بالانخفاض للمحطة 3.',
              'safeOutEn': 'Core body temp began lowering for Station 3.',
              'unsafeTextAr': 'غمر المصاب فجأة في حوض ثلج شديد البرودة',
              'unsafeTextEn': 'Submerge victim suddenly in ice bath full of ice blocks',
              'unsafeExpAr': 'خطأ؛ التبريد الثلجي المفاجئ يسبب انقباض الأوعية الدموية وصدمة قلبية.',
              'unsafeExpEn': 'Error; extreme ice immersion causes sudden vascular constriction and shock.',
              'unsafeOutAr': 'تسبب الانقباض المفاجئ بإجهاد الوعائي.',
              'unsafeOutEn': 'Caused vascular constriction shock.',
            },
            {
              'sitAr': 'المصاب واعي ويتحدث بصعوبة. ما السوائل المناسبة لإعادة الترطيب؟',
              'sitEn': 'Victim conscious but complaining of severe thirst. Correct fluid?',
              'hintAr': 'إعطاء رشفات صغيرة متقطعة من الماء البارد أو محاليل الأملاح التعويضية',
              'hintEn': 'Offer small frequent sips of cool water or oral rehydration salts solution',
              'safeTextAr': 'إعطاء رشفات هادئة من الماء المعتدل أو محلول الجفاف الفموي (Electrolytes)',
              'safeTextEn': 'Provide gentle sips of moderate water or electrolyte ORS solution',
              'safeExpAr': 'ممتاز؛ السوائل المتوازنة تعوض أملاح الصوديوم والبوتاسيوم المفقودة بالتعرق.',
              'safeExpEn': 'Excellent; balanced fluids replenish lost sodium and potassium minerals.',
              'safeOutAr': 'استعاد المصاب توازنه المائي للمحطة 4.',
              'safeOutEn': 'Rehydrated victim minerals safely for Station 4.',
              'unsafeTextAr': 'إرغامه على شرب كميات هائلة من المشروبات الغازية أو القهوة الساخنة',
              'unsafeTextEn': 'Force victim to gulp large quantities of caffeinated sodas or hot coffee',
              'unsafeExpAr': 'خطأ؛ الكافيين والمشروبات السكرية تزيد الجفاف وتدر البول.',
              'unsafeExpEn': 'Error; caffeine and sugary sodas accelerate fluid loss through diuresis.',
              'unsafeOutAr': 'زاد معدل الجفاف لدى المصاب.',
              'unsafeOutEn': 'Dehydration worsened from caffeine.',
            },
            {
              'sitAr': 'شعر المصاب بغثيان ورغبة بالتقيؤ. ما الوضعية الإسعافية الآمنة؟',
              'sitEn': 'Victim feels nauseous with vomiting risk. Safe recovery position?',
              'hintAr': 'وضعية الإفاقة الجانبية لمنع انسداد مجرى التنفس بالسائل القيئي',
              'hintEn': 'Place in lateral recovery position to keep airway open and clear of vomit',
              'safeTextAr': 'تمديد المصاب على جانبه (وضعية الإفاقة الجانبية) وحماية رأسه',
              'safeTextEn': 'Lie victim on their side in lateral recovery position supporting head',
              'safeExpAr': 'وضعية ذهبية؛ يضمن مجرى تنفس مفتوح ويمنع الغرق بالسائل المعوي.',
              'safeExpEn': 'Golden positioning; maintains clear airway preventing aspiration choking.',
              'safeOutAr': 'أمّنت التنفس ونظافة المجرى للمحطة 5.',
              'safeOutEn': 'Secured open airway for Station 5.',
              'unsafeTextAr': 'جعل المصاب يستلقي مستقيماً على ظهره مع رفع رأسه لأعلى',
              'unsafeTextEn': 'Lay victim flat on their back pushing head straight backward',
              'unsafeExpAr': 'خطأ؛ الاستلقاء على الظهر مع الغثيان يؤدي لانسداد القصبة الهوائية.',
              'unsafeExpEn': 'Error; supine lying during vomiting causes airway block and asphyxiation.',
              'unsafeOutAr': 'انسدد مجرى التنفس جزئياً.',
              'unsafeOutEn': 'Risked tongue and fluid choking.',
            },
            {
              'sitAr': 'وصول فرقة الهلال الأحمر السعودي (997). كيف تسلم الحالة؟',
              'sitEn': 'Saudi Red Crescent 997 paramedics arrive. How to report handoff?',
              'hintAr': 'تزويد المسعف بتفاصيل وقت التعرض، الإجراءات المتبعة، ونسبة الوعي',
              'hintEn': 'Hand over report detailing sun exposure duration, cooling steps, and consciousness',
              'safeTextAr': 'تزويد المسعفين بتقرير سريع عن درجة الحرارة، مدة الشمس، والخطوات التبريدية التي قمت بها',
              'safeTextEn': 'Provide paramedics brief report of sun duration, peak temp, and cooling done',
              'safeExpAr': 'تسليم احترافي؛ يساعد الفريق الطبي على مواصلة المحاليل المستهدفة بنجاح.',
              'safeExpEn': 'Professional handoff; empowers paramedics to streamline IV fluid therapy.',
              'safeOutAr': 'أكملت محطات التعامل مع ضربة الشمس بنجاح!',
              'safeOutEn': 'Completed all 5 heatstroke rescue stations successfully!',
              'unsafeTextAr': 'الانسحاب فوراً دون التحدث للمسعفين أو إبلاغهم بأسماء الأدوية',
              'unsafeTextEn': 'Walk away immediately without relaying symptoms or care provided',
              'unsafeExpAr': 'تفويت معلومات؛ إغفال التقرير يؤخر التشخيص الطبي الدقيق.',
              'unsafeExpEn': 'Missing info; failing to report delays vital medical emergency response.',
              'unsafeOutAr': 'تأخر التقييم الطبي الدقيق.',
              'unsafeOutEn': 'Paramedic triage delayed.',
            },
          ],
        ),

        // 2. Heat Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_2',
          categoryId: 'heat',
          titleAr: 'نسيان طفل داخل مركبة مغلقة صيفاً',
          titleEn: 'Child Trapped in Hot Sealed Car',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع احتجاز الأطفال في السيارات المغلقة بالحرارة.',
          descriptionEn: 'Interactive 5-station scenario for children trapped in hot cars.',
          difficulty: 'صعب',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'لاحظت وجود طفل محتجز داخل سيارة مغلقة تحت شمس الصيف الحارقة والطفل يصب عرقاً. ما التصرف؟',
              'sitEn': 'Spotted child trapped inside locked car under blistering sun sweating heavily. Action?',
              'hintAr': 'البحث عن صاحب السيارة فوراً أو كسر الزجاج البعيد عن الطفل إن كان غائباً عن الوعي',
              'hintEn': 'Search for driver or break far window safely if child shows heat distress',
              'safeTextAr': 'التقييم السريع؛ إن كان الطفل متأثراً بالحرارة يتم كسر نافذة جانبية بعيدة عن الطفل فوراً',
              'safeTextEn': 'Quick triage: if child shows heat distress, immediately break side window furthest from child',
              'safeExpAr': 'تصرف إنقاذ حياة؛ حرارة السيارة المغلقة ترتفع لـ 60 مئوية خلال 10 دقائق.',
              'safeExpEn': 'Lifesaving action; cabin temps inside locked cars reach 60°C in just 10 mins.',
              'safeOutAr': 'كسرت النافذة بعيداً عن الطفل للمحطة 2.',
              'safeOutEn': 'Broke far window safely for Station 2.',
              'unsafeTextAr': 'الانتظار لمدة ساعة في الظل بحثاً عن السائق دون اتخاذ أي إجراء',
              'unsafeTextEn': 'Wait an hour in shade hoping driver returns without taking action',
              'unsafeExpAr': 'خطأ قاتل؛ الانتظار يؤدي لإصابة الطفل بفشل أعضاء وفقدان الحياة.',
              'unsafeExpEn': 'Fatal mistake; waiting causes pediatric heat stroke and multiple organ failure.',
              'unsafeOutAr': 'تعرض الطفل لغيبوبة حرارية.',
              'unsafeOutEn': 'Child fell into thermal coma.',
            },
            {
              'sitAr': 'فتح باب السيارة وإخراج الطفل من الكابينة المشتعلة. أين تنقله؟',
              'sitEn': 'Opened door extracting child from scorching cabin. Where to transfer?',
              'hintAr': 'نقل الطفل فوراً لمكان مكيف بارد أو ظل واحة وتخفيف ملابسه',
              'hintEn': 'Move child immediately to cool air-conditioned space and remove hot clothing',
              'safeTextAr': 'نقل الطفل فوراً لمحل مكيف أو مكان مظلل وتخفيف ملابسه الساخنة',
              'safeTextEn': 'Carry child into cool AC shop or shade immediately stripping hot clothes',
              'safeExpAr': 'إجراء ممتاز؛ خفض الحرارة المحيطة يوقف تدهور الجفاف والتلف الدماغي.',
              'safeExpEn': 'Excellent step; dropping ambient temp halts rapid brain overheating.',
              'safeOutAr': 'نقلت الطفل للظل والتكييف للمحطة 3.',
              'safeOutEn': 'Moved child to AC for Station 3.',
              'unsafeTextAr': 'إجلاس الطفل على الإسفلت الساخن أمام الشارع',
              'unsafeTextEn': 'Sit child down directly on hot asphalt road pavement',
              'unsafeExpAr': 'خطأ؛ الإسفلت الساخن يرسل حرارة إشعاعية تزيد حروق الجلد.',
              'unsafeExpEn': 'Error; hot asphalt radiates 70°C surface heat worsening skin burns.',
              'unsafeOutAr': 'تأثر الطفل بحرارة الإسفلت.',
              'unsafeOutEn': 'Exposed to asphalt heat.',
            },
            {
              'sitAr': 'الطفل واعي لكنه يبكي بشدة وجلده أحمر جاف. كيف تبدأ بالتبريد الإسعافي؟',
              'sitEn': 'Child conscious but crying with red dry skin. How to begin cooling?',
              'hintAr': 'رش ماء فاتر أو مسح الجسم بفوطة رطبة وتجنب مياه الثلج المفاجئة',
              'hintEn': 'Dampen skin with lukewarm wet towel; avoid sudden ice cold water shock',
              'safeTextAr': 'مسح جسم ورأس الطفل بقطعة قماش رطبة بماء فاتر وإعطائه رشفات ماء هادئة',
              'safeTextEn': 'Wipe child skin and head gently with lukewarm wet cloth giving small sips of water',
              'safeExpAr': 'تبريد متدرج سليم؛ التبريد الفاتر يمنع الارتجاف الشديد الذي يرفع الحرارة الداخلية.',
              'safeExpEn': 'Correct gradual cooling; lukewarm water prevents shivering which raises core temp.',
              'safeOutAr': 'بدأت التبريد التدريجي للمحطة 4.',
              'safeOutEn': 'Started gradual cooling for Station 4.',
              'unsafeTextAr': 'سكب سطل ماء مثلج فوق رأس الطفل دفعة واحدة',
              'unsafeTextEn': 'Douse child head with bucket of ice cold water all at once',
              'unsafeExpAr': 'خطأ؛ الصدمة الثلجية تسبب تقلص الشرايين وانخفاض ضربات القلب.',
              'unsafeExpEn': 'Error; ice shock induces severe bradycardia and vascular collapse.',
              'unsafeOutAr': 'تعرض الطفل لصدمة ثلجية.',
              'unsafeOutEn': 'Child suffered ice shock.',
            },
            {
              'sitAr': 'الاتصال بالهلال الأحمر (997) وأمن الطرق/الشرطة (999/911). ماذا تبلغ؟',
              'sitEn': 'Calling Red Crescent 997 & Police 911. What info to dispatch?',
              'hintAr': 'تحديد موقع السيارة، حالة وعي الطفل، والوقت المستغرق بالحرارة',
              'hintEn': 'Specify vehicle location, child consciousness level, and heat duration',
              'safeTextAr': 'الاتصال بـ 997 و911 وإعطاء موقع السيارة، حالة وعي الطفل، ونوع السيارة',
              'safeTextEn': 'Call 997 and 911 relaying car location, plate/make, and child responsiveness',
              'safeExpAr': 'بلاغ مزدوج ممتاز؛ الإسعاف يتولى الطفل والشرطة تفتح تحقيقاً لمعرفة الوالدين.',
              'safeExpEn': 'Dual report; 997 provides pediatric care while 911 investigates parent negligence.',
              'safeOutAr': 'أبلغت الإسعاف والشرطة للمحطة 5.',
              'safeOutEn': 'Reported to 997 and 911 for Station 5.',
              'unsafeTextAr': 'مغادرة الموقع وترك الطفل مع عمال الشارع دون بلاغ رسمي',
              'unsafeTextEn': 'Leave scene abandoning child with street workers without filing report',
              'unsafeExpAr': 'خطأ؛ ترك الطفل دون تسليم رسمي للشرطة والإسعاف يعرض حياته للخطر.',
              'unsafeExpEn': 'Error; abandoning rescued child without official handoff is unsafe.',
              'unsafeOutAr': 'ترك الطفل بدون رعاية رسمية.',
              'unsafeOutEn': 'Abandoned child without police handoff.',
            },
            {
              'sitAr': 'وصول سيارة الإسعاف 997 وتسليم الطفل للمسعفين. ما التوعية الوقائية لعدم التكرار؟',
              'sitEn': '997 Ambulance arrives taking over child. Preventive awareness rule?',
              'hintAr': 'وضع الحقيبة أو الجوال بالمرتبة الخلفية دائماً لتذكر التأكد من الخلو',
              'hintEn': 'Always place bag/phone on rear seat to force checking back seat before locking',
              'safeTextAr': 'نشر قاعدة "افحص المرتبة الخلفية" ووضع الهاتف أو الحقيبة بالخلف دائماً لعدم النسيان',
              'safeTextEn': 'Promote "Look Before You Lock" habit by keeping vital items in back seat',
              'safeExpAr': 'إتمام ناجح؛ عادة وضع الأغراض بالخلف تمنع مأساة النسيان صيفاً كلياً.',
              'safeExpEn': 'Successful completion; keeping items in back seat completely prevents hot car memory gaps.',
              'safeOutAr': 'أكملت محطات إنقاذ طفل السيارة بنجاح!',
              'safeOutEn': 'Successfully completed hot car child rescue!',
              'unsafeTextAr': 'الاعتماد على التظليل المظلم فقط وتجاهل حرارة السيارة',
              'unsafeTextEn': 'Rely solely on window tinting thinking tint stops heat buildup',
              'unsafeExpAr': 'خطأ؛ التظليل لا يمنع ارتفاع حرارة السيارة المغلقة إطلاقاً.',
              'unsafeExpEn': 'Error; window tinting does NOT stop deadly thermal greenhouse heat inside locked cars.',
              'unsafeOutAr': 'استمر خطر التظليل المضلل.',
              'unsafeOutEn': 'Tinting myth created unsafe habit.',
            },
          ],
        ),

        // 3. Heat Scenario 3
        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_3',
          categoryId: 'heat',
          titleAr: 'انفجار شاحن متنقل أو عبوة عطر داخل السيارة',
          titleEn: 'Powerbank or Perfume Explosion in Hot Car',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انفجار المواد المضغوطة والليثيوم في حرارة الصيف.',
          descriptionEn: 'Interactive 5-station scenario for lithium battery explosions in parked cars.',
          difficulty: 'متوسط',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'عند الاقتراب من سيارتك المتوقفة بالشمس لاحظت انبعاث دخان من الكابينة وسماع صوت انفجار. ما الحركة؟',
              'sitEn': 'Approaching car parked in sun, smoke billowing from cabin with loud pop sound. Action?',
              'hintAr': 'فتح الأبواب بحذر وعدم استنشاق الغازات السامة الممتلئة بالكابينة',
              'hintEn': 'Open doors cautiously; do NOT inhale toxic battery gases filling cabin',
              'safeTextAr': 'فتح الأبواب بحذر والوقوف عكس اتجاه الريح لتهوية الغازات السامة',
              'safeTextEn': 'Open car doors cautiously standing upwind to allow toxic fumes to clear',
              'safeExpAr': 'تصرف ممتاز؛ غازات انفجار بطاريات الليثيوم مسممة ومخرشة للرئتين.',
              'safeExpEn': 'Excellent step; exploding lithium ion battery fumes are highly toxic and caustic.',
              'safeOutAr': 'فتحت الأبواب بحذر للمحطة 2.',
              'safeOutEn': 'Opened doors upwind for Station 2.',
              'unsafeTextAr': 'الدخول وركوب السيارة فوراً واستنشاق الدخان الأبيض',
              'unsafeTextEn': 'Sit inside car immediately taking deep breaths of white battery smoke',
              'unsafeExpAr': 'خطأ؛ استنشاق حمض الليثيوم يسبب التسمم الحاد وكوي القصبة الهوائية.',
              'unsafeExpEn': 'Error; inhaling hydrofluoric acid from lithium battery fires burns respiratory tract.',
              'unsafeOutAr': 'استنشقت غازات الليثيوم.',
              'unsafeOutEn': 'Inhaled toxic lithium gas.',
            },
            {
              'sitAr': 'رأيت الشاحن المتنقل المشتعل فوق المقعد يتصاعد منه اللهب. كيف تخمده؟',
              'sitEn': 'Flashing lithium powerbank on seat bursting into flame. How to extinguish?',
              'hintAr': 'استخدام طفاية البودرة أو ثاني أكسيد الكربون وتجنب لمس البطارية بيديك',
              'hintEn': 'Use dry powder or CO2 extinguisher; NEVER touch swelling battery barehanded',
              'safeTextAr': 'رش طفاية البودرة الجافة الخاصة بالسيارة على المقعد المشتعل من مسافة أمان',
              'safeTextEn': 'Discharge car dry powder extinguisher onto burning seat from safe distance',
              'safeExpAr': 'إجراء صحيح؛ البودرة تخمد الحريق الأولي وتمنع امتداده لجميع المقاعد.',
              'safeExpEn': 'Correct step; powder extinguishes seat fabric preventing full cabin burn.',
              'safeOutAr': 'أخمدت حريق المقعد للمحطة 3.',
              'safeOutEn': 'Extinguished seat fire for Station 3.',
              'unsafeTextAr': 'الإمساك بالبطارية المنتفخة المشتعلة بيدك ورمايتها للخارج',
              'unsafeTextEn': 'Grab burning swollen lithium battery barehanded to throw out window',
              'unsafeExpAr': 'خطأ؛ البطارية المشتعلة تنفجر بين يديك وتتسبب في بتر أو حروق كيميائية.',
              'unsafeExpEn': 'Error; burning lithium cells explode violently in hand causing severe chemical blast.',
              'unsafeOutAr': 'انفجرت البطارية بيدك.',
              'unsafeOutEn': 'Battery exploded in hand.',
            },
            {
              'sitAr': 'تضررت المقاعد وانبعث شرر للحرارة الداخلي. كيف تضمن انطفاء الجمر؟',
              'sitEn': 'Seat foam scorched with lingering heat. How to verify full cooling?',
              'hintAr': 'فصل بطارية السيارة وسكب كمية ماء على بقايا المقعد الساخن',
              'hintEn': 'Disconnect main car battery and douse scorched seat foam with water',
              'safeTextAr': 'فصل بطارية السيارة وسكب الماء على الجمر المتبقي بإسفنج المقعد للتأكد من تبريده',
              'safeTextEn': 'Disconnect car battery negative terminal and douse seat foam thoroughly with water',
              'safeExpAr': 'تكتيك ممتاز؛ إسفنج المقاعد يحتفظ بالجمر الحراري وقد يجدد الحريق.',
              'safeExpEn': 'Great tactic; seat foam retains deep thermal embers that reignite later.',
              'safeOutAr': 'برّدت المقعد تماماً للمحطة 4.',
              'safeOutEn': 'Cooled seat foam completely for Station 4.',
              'unsafeTextAr': 'إغلاق أبواب السيارة فوراً ومغادرتها والجمر يشتعل',
              'unsafeTextEn': 'Slam car doors shut leaving hot seat foam smoldering inside',
              'unsafeExpAr': 'خطأ؛ إغلاق السيارة المغلقة مع وجود جمر يعيد اشتعال المركبة بالكامل.',
              'unsafeExpEn': 'Error; sealing smoldering interior traps heat reigniting entire vehicle.',
              'unsafeOutAr': 'تجدد حريق السيارة.',
              'unsafeOutEn': 'Vehicle fire reignited.',
            },
            {
              'sitAr': 'فحص وتصفية الأغراض الخطرة المتبقية بالسيارة صيفاً. ما الأغراض الخطر إبقاؤها؟',
              'sitEn': 'Inspecting car for remaining high-risk summer items. What to remove?',
              'hintAr': 'إزالة جميع الشواحن المتنقلة، العطور، الولاعات، والعبوات المضغوطة صيفاً',
              'hintEn': 'Remove all powerbanks, perfumes, lighters, and aerosol cans in summer',
              'safeTextAr': 'إزالة الشواحن، العطور، الولاعات، وأجهزة التابلت من المركبة مطلقاً أثناء الصيف',
              'safeTextEn': 'Remove all powerbanks, perfumes, lighters, and tablets from vehicle in summer',
              'safeExpAr': 'وقاية استباقية؛ الحرارة العالية تزيد الضغط الداخلي للعبوات وتسبب انفجارها.',
              'safeExpEn': 'Proactive prevention; cabin heat expands internal pressure causing catastrophic bursts.',
              'safeOutAr': 'أزلت المواد الخطرة للمحطة 5.',
              'safeOutEn': 'Removed all hazards for Station 5.',
              'unsafeTextAr': 'ترك الولاعات والعطور تحت الزجاج الأمامي المباشر للشمس',
              'unsafeTextEn': 'Leave disposable gas lighters and perfumes on dashboard directly under sun',
              'unsafeExpAr': 'خطأ؛ ترك الولاعات على الطبلون يحولها لقنابل موقوتة بالشمس.',
              'unsafeExpEn': 'Error; dashboard lighters act as ticking bombs under direct sun glass focus.',
              'unsafeOutAr': 'عرضت الطبلون لخطورة الانفجار.',
              'unsafeOutEn': 'Dashboard explosion hazard.',
            },
            {
              'sitAr': 'إصلاح التلفيات وتأمين المركبة. ما الدرس والتوعية النهائية؟',
              'sitEn': 'Repairing damage and securing car. Final educational takeaway?',
              'hintAr': 'عدم ترك أي بطارية ليثيوم في السيارة واستخدام مظلة الشماسية الزجاجية',
              'hintEn': 'Never store lithium batteries in cars and always install windshield sunshade',
              'safeTextAr': 'استخدام مظلة الشماسية العاكسة دائماً وعدم ترك أي بطاريات بالسيارة إطلاقاً',
              'safeTextEn': 'Always deploy reflective windshield sunshade and strictly never leave batteries inside',
              'safeExpAr': 'إتمام كامل؛ الشماسية تخفض حرارة الكابينة بـ 20 درجة مئوية وتسهم بالحماية.',
              'safeExpEn': 'Complete resolution; reflective sunshades drop interior temps by 20°C protecting cabin.',
              'safeOutAr': 'أكملت محطات الوقاية من انفجار الشاحن بنجاح!',
              'safeOutEn': 'Successfully completed hot car powerbank scenario!',
              'unsafeTextAr': 'الاعتماد على ركن السيارة بالشمس بدون مظلة شماسية',
              'unsafeTextEn': 'Park in open sun without using windshield sunshades continuously',
              'unsafeExpAr': 'خطأ؛ ترك السيارة بدون شماسية يسرّع تلف الطبلون والتوصيلات.',
              'unsafeExpEn': 'Error; unshielded sun exposure warps dashboard and cooks internal electronics.',
              'unsafeOutAr': 'تأثر الطبلون بالحرارة.',
              'unsafeOutEn': 'Dashboard warped by heat.',
            },
          ],
        ),

        // Scenarios 4 to 9 for HEAT...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_4',
          categoryId: 'heat',
          titleAr: 'حروق الشمس الشديدة أثناء العمل المكشوف',
          titleEn: 'Severe Sunburns & Field Work Hazards',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حروق الشمس والوقاية أثناء العمل الخارجي.',
          descriptionEn: 'Interactive 5-station scenario for outdoor worker sunburns and heat safety.',
          difficulty: 'سهل',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'أثناء عملك بالموقع المكشوف ظهر احمرار شديد وآلام على جلد الظهر والكتفين. ما أول إجراء؟',
              'sitEn': 'Severe redness and pain appears on back/shoulders during field work. Immediate step?',
              'hintAr': 'التوقف فوراً عن العمل تحت الشمس والانتقال إلى الظل البارد',
              'hintEn': 'Stop working under sun immediately and retreat into cool shade',
              'safeTextAr': 'التوقف الفوري عن العمل وتغطية الجلد والانتقال لمنطقة مظللة مكيفة',
              'safeTextEn': 'Stop work immediately, cover skin, and move to cool shaded/AC area',
              'safeExpAr': 'تصرف ممتاز؛ التوقف السريع يمنع عمق حروق الأشعة فوق البنفسجية (UV).',
              'safeExpEn': 'Excellent step; stopping sun exposure halts deeper UV radiation dermal burns.',
              'safeOutAr': 'انتقلت للظل للمحطة 2.',
              'safeOutEn': 'Retreated to shade for Station 2.',
              'unsafeTextAr': 'مواصلة العمل تحت الشمس دون أي غطاء لحين انتهاء الدوام',
              'unsafeTextEn': 'Continue hard manual labor under direct sun until shift ends',
              'unsafeExpAr': 'خطأ؛ مواصلة التعرض تحول الحرق من الدرجة الأولى إلى حروق فقاعية مؤلمة.',
              'unsafeExpEn': 'Error; continued exposure converts 1st degree sunburn into severe 2nd degree blisters.',
              'unsafeOutAr': 'تفاقمت حروق الجلد.',
              'unsafeOutEn': 'Sunburn escalated to blistering stage.',
            },
            {
              'sitAr': 'ظهرت فقاقيع مائية (Blisters) على الكتفين المحترقة. كيف تعتني بالحرق؟',
              'sitEn': 'Water blisters appearing on sunburned shoulders. First aid treatment?',
              'hintAr': 'وضع كمادات ماء بارد وتجنب ثقب أو فتح الفقاقيع المائية',
              'hintEn': 'Apply cool damp compresses; do NOT pop or puncture skin blisters',
              'safeTextAr': 'وضع كمادات ماء بارد خفيف وتجنب فقع أو ثقب الفقاقيع الجلدية المائية',
              'safeTextEn': 'Apply cool damp water compresses gently; strictly avoid popping skin blisters',
              'safeExpAr': 'إجراء سليم؛ الفقاقيع المائية حماية طبيعية تفرزها الأنسجة وتنقيبها يسبب التلوث.',
              'safeExpEn': 'Correct first aid; intact blisters act as sterile natural skin bandages against infection.',
              'safeOutAr': 'عالجت الحرق بالماء الفاتر للمحطة 3.',
              'safeOutEn': 'Cooled sunburn safely for Station 3.',
              'unsafeTextAr': 'ثقب الفقاقيع بإبرة وحكها بقوة',
              'unsafeTextEn': 'Puncture blisters with pin and rub skin vigorously',
              'unsafeExpAr': 'خطأ؛ ثقب الفقاقيع يفتح باباً للبكتيريا وتلوث الجلد العميق.',
              'unsafeExpEn': 'Error; popping blisters destroys protective layer allowing bacterial skin sepsis.',
              'unsafeOutAr': 'تلوث حرق الجلد.',
              'unsafeOutEn': 'Sunburn became infected.',
            },
            {
              'sitAr': 'شعور بحرارة وجفاف داخلي شديد. ما المراهم والسوائل المناسبة؟',
              'sitEn': 'Feeling intense skin tightness and dehydration. Suitable gels & fluids?',
              'hintAr': 'دهن جيل الألوفيرا (Aloe Vera) وتناول كميات وفيرة من المياه',
              'hintEn': 'Apply pure Aloe Vera gel and drink ample hydration fluids',
              'safeTextAr': 'دهن جيل الألوفيرا المبرد المرطب وشرب كميات وفيرة من الماء لتعويض الجفاف',
              'safeTextEn': 'Apply cooling Aloe Vera gel and drink large amounts of water for hydration',
              'safeExpAr': 'اختيار رائع؛ الألوفيرا تهدئ الالتهاب والماء يعوض الترطيب المفقود من الجلد.',
              'safeExpEn': 'Great choice; Aloe Vera reduces inflammation and hydration speeds dermal repair.',
              'safeOutAr': 'رطبت الجلد والجسم للمحطة 4.',
              'safeOutEn': 'Applied Aloe Vera for Station 4.',
              'unsafeTextAr': 'دهن الحروق بالزيوت الثقيلة أو الفازلين الزيتي فوق الجلد المشتعل',
              'unsafeTextEn': 'Slather heavy petroleum jelly or cooking oil over burning hot skin',
              'unsafeExpAr': 'خطأ؛ الزيوت الثقيلة تحبس الحرارة داخل الجلد وتزيد الألم والالتهاب.',
              'unsafeExpEn': 'Error; heavy oils trap thermal heat inside skin intensifying inflammation pain.',
              'unsafeOutAr': 'احتبست الحرارة داخل الجلد.',
              'unsafeOutEn': 'Heat trapped in skin by oil.',
            },
            {
              'sitAr': 'التهيؤ للعودة للعمل الميداني باليوم التالي. كيف تحمي نفسك وقائياً؟',
              'sitEn': 'Preparing for field work next day. How to protect skin preventively?',
              'hintAr': 'ارتداء قبعات عريضة، قمصان طويلة الأكمام، وواقي شمس (SPF 50+)',
              'hintEn': 'Wear wide-brim hat, long-sleeve UV shirts, and broad spectrum SPF 50+ sunscreen',
              'safeTextAr': 'ارتداء ملابس قطنية طويلة الأكمام، قبعة عريضة، ووضع واقي شمس (SPF 50+)',
              'safeTextEn': 'Wear long-sleeve UV cotton clothing, broad-brim hat, and apply SPF 50+ sunscreen',
              'safeExpAr': 'حماية متكاملة؛ الملابس الواقية والواقي الشمسي يعكسان 98% من أشعة الصيف.',
              'safeExpEn': 'Complete defense; UV apparel and SPF 50+ shield against 98% of harmful solar rays.',
              'safeOutAr': 'ارتديت الملابس الواقية للمحطة 5.',
              'safeOutEn': 'Equipped sun protection gear for Station 5.',
              'unsafeTextAr': 'العمل بقمصان قصيرة بدون واقي شمس بالظهيرة',
              'unsafeTextEn': 'Work sleeveless with zero sunblock during peak 12 PM noon hours',
              'unsafeExpAr': 'خطأ؛ التعرض المكشوف صيفاً يزيد خطر سرطانات الجلد وتلف الخلايا.',
              'unsafeExpEn': 'Error; unshielded noon sun causes severe cellular DNA damage and skin cancer risks.',
              'unsafeOutAr': 'عرضت الجلد لتلف الأشعة.',
              'unsafeOutEn': 'Exposed skin to severe UV damage.',
            },
            {
              'sitAr': 'تنظيم أوقات العمل الميداني بالأنظمة الرسمية. ما معيار السلامة المهنية؟',
              'sitEn': 'Organizing outdoor work shifts under Saudi labor laws. Midday rule?',
              'hintAr': 'الالتزام بحظر العمل تحت الشمس المباشرة من 12 ظهراً إلى 3 عصراً صيفاً',
              'hintEn': 'Comply with Saudi Ministry of Labor outdoor work ban (12 PM to 3 PM)',
              'safeTextAr': 'الالتزام التام بحظر العمل تحت أشعة الشمس المباشرة من 12 ظهراً حتى 3 عصراً',
              'safeTextEn': 'Strictly adhere to official Saudi Labor Ministry sun work ban (12 PM to 3 PM)',
              'safeExpAr': 'إتمام كامل؛ حظر العمل أوقات الذروة يحمي ملايين العمال سنوياً من ضربات الشمس.',
              'safeExpEn': 'Complete resolution; peak sun work bans safeguard workers from fatal heatstroke.',
              'safeOutAr': 'أكملت محطات الوقاية من حروق الشمس بنجاح!',
              'safeOutEn': 'Successfully completed sunburn safety scenario!',
              'unsafeTextAr': 'مواصلة العمل في ساعات الذروة 1 ظهراً بدون توقف',
              'unsafeTextEn': 'Force continuous labor during peak 1 PM sun hours without rest breaks',
              'unsafeExpAr': 'خطأ؛ مخالفة أنظمة السلامة تعرض العمال لمخاطر الإجهاد الحراري والوفاة.',
              'unsafeExpEn': 'Error; violating work ban regulations risks fatal heat collapse.',
              'unsafeOutAr': 'مخالفة أنظمة حظر العمل.',
              'unsafeOutEn': 'Violated midday sun work ban.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_5',
          categoryId: 'heat',
          titleAr: 'تعطل التكييف بالمنزل أثناء موجة الحر',
          titleEn: 'Home AC Failure During Severe Heatwave',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تعطل التكييف وحماية الأسرة وكبار السن.',
          descriptionEn: 'Interactive 5-station scenario for home AC failure during heatwaves.',
          difficulty: 'متوسط',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'توقف التكييف المركزي بالمنزل أثناء موجة حر تتجاوز 48 مئوية. ما التصرف؟',
              'sitEn': 'Central AC fails at home during 48°C extreme summer heatwave. Action?',
              'hintAr': 'إغلاق الستائر والنوافذ المشمسة وتجميع الأسرة بالغرفة الأكثر برودة',
              'hintEn': 'Close sun-facing blinds/curtains and gather family in coolest insulated room',
              'safeTextAr': 'إغلاق الستائر والنوافذ المقابلة للشمس وتجميع الأسرة بأبرد غرفة بالمنزل',
              'safeTextEn': 'Close all sun-facing curtains/blinds and gather family in coolest ground room',
              'safeExpAr': 'تصرف ممتاز؛ إغلاق الستائر يمنع دخول الإشعاع الحراري للكابينة المنزلية.',
              'safeExpEn': 'Excellent step; closing shades blocks radiant solar heat gain inside home.',
              'safeOutAr': 'جمعت الأسرة بالغرفة الأبرد للمحطة 2.',
              'safeOutEn': 'Gathered family in cool room for Station 2.',
              'unsafeTextAr': 'فتح جميع النوافذ الخارجية بالظهيرة لتوفير هواء',
              'unsafeTextEn': 'Open all exterior windows wide at 1 PM aiming for a breeze',
              'unsafeExpAr': 'خطأ؛ فتح النوافذ بالظهيرة يدخل الهواء الخارجي اللاهب (48C+) للمنزل.',
              'unsafeExpEn': 'Error; opening windows at noon floods interior with scorching 48°C outdoor heat.',
              'unsafeOutAr': 'ارتفعت حرارة المنزل.',
              'unsafeOutEn': 'Flooded home with scorching heat.',
            },
            {
              'sitAr': 'ارتفاع حرارة الغرفة وبداية شعور كبار السن بالإنهاك. كيف تبرد البيئة؟',
              'sitEn': 'Room temp rising; elderly family feeling exhausted. How to cool environment?',
              'hintAr': 'تشغيل المراوح مع وضع أوعية ماء بارد/ثلج أمام تيار المروحة',
              'hintEn': 'Run electric fans placing bowls of ice water directly in front of airflow',
              'safeTextAr': 'تشغيل المراوح مع وضع أوعية ماء بارد وثبت ثلج أمام تيار الهواء لتبريده',
              'safeTextEn': 'Operate fans placing large bowls of ice water directly in front of fan blades',
              'safeExpAr': 'تكتيك تبريد مبتكر؛ التبخير الثلجي يخفض درجة حرارة تيار الهواء بـ 5 درجات.',
              'safeExpEn': 'Innovative cooling tactic; ice evaporation drops fan airflow temp by 5°C.',
              'safeOutAr': 'برّدت تيار الهواء للمحطة 3.',
              'safeOutEn': 'Cooled airflow with ice for Station 3.',
              'unsafeTextAr': 'جعل كبار السن يرتدون أغطية وملابس ثقيلة',
              'unsafeTextEn': 'Cover elderly members with thick heavy blankets',
              'unsafeExpAr': 'خطأ؛ الأغطية الثقيلة تحبس حرارة الجسم وتسبب ضربة شمس داخلية.',
              'unsafeExpEn': 'Error; heavy blankets trap core body heat causing indoor heatstroke.',
              'unsafeOutAr': 'احتبست حرارة الجسم.',
              'unsafeOutEn': 'Trapped core body heat.',
            },
            {
              'sitAr': 'تأمين المياه والترطيب لجميع أفراد الأسرة. ما النظام الغذائي المفضل صيفاً؟',
              'sitEn': 'Ensuring family hydration during AC outage. Preferred summer diet & drinks?',
              'hintAr': 'شرب الماء باستمرار وتناول الفواكه الغنية بالماء كالرقي (البطيخ) والخيار',
              'hintEn': 'Drink water continuously; eat water-rich fruits like watermelon & cucumber',
              'safeTextAr': 'تقديم الماء البارد المعتدل باستمرار وتناول البطيخ والخيار لترطيب الجسم',
              'safeTextEn': 'Serve cool water continuously and offer watermelon and cucumbers for hydration',
              'safeExpAr': 'ترطيب رائع؛ الفواكه الطبيعية تزود الجسم بالماء والأملاح الحيوية بشكل متوازن.',
              'safeExpEn': 'Great hydration; natural fruits provide water and essential minerals seamlessly.',
              'safeOutAr': 'أمّنت الترطيب الغذائي للمحطة 4.',
              'safeOutEn': 'Hydrated family with fruits & water for Station 4.',
              'unsafeTextAr': 'تقديم وجبات دسمة ثقيلة ومشروبات كافيين ساخنة',
              'unsafeTextEn': 'Serve heavy greasy fried meals and hot caffeinated tea',
              'unsafeExpAr': 'خطأ؛ الهضم الثقيل يزيد حرارة التمثيل الغذائي والكافيين يدر البول.',
              'unsafeExpEn': 'Error; heavy digestion increases internal metabolic heat; caffeine dehydrates.',
              'unsafeOutAr': 'ارتفعت حرارة التمثيل الغذائي.',
              'unsafeOutEn': 'Metabolic heat increased.',
            },
            {
              'sitAr': 'استمرار عطل التكييف وشدة الحرارة. ما الخيار البديل الآمن؟',
              'sitEn': 'AC repair delayed; heatwave continues. Safe temporary relocation?',
              'hintAr': 'الانتقال المؤقت لبيت أقارب مكيف أو فندق لحين إصلاح التكييف',
              'hintEn': 'Temporarily relocate family to air-conditioned relative home or hotel',
              'safeTextAr': 'الانتقال المؤقت بالأسرة لبيت أقارب مكيف أو شقة مفروشة لحين انتهاء الصيانة',
              'safeTextEn': 'Temporarily relocate family to a well-air-conditioned relative house or hotel',
              'safeExpAr': 'قرار حكيم؛ حماية كبار السن والأطفال من الحرارة الشديدة حظر التهاون به.',
              'safeExpEn': 'Wise decision; protecting vulnerable family from extreme heat is top priority.',
              'safeOutAr': 'انتقلت لمأوى مكيف للمحطة 5.',
              'safeOutEn': 'Relocated to AC environment for Station 5.',
              'unsafeTextAr': 'البقاء بالمنزل المشتعل والتصابر رغم هبوط ضغط كبار السن',
              'unsafeTextEn': 'Stay in 45°C house ignoring elderly fainting symptoms',
              'unsafeExpAr': 'خطأ؛ المكابرة بالحرارة الشديدة تسبب الفشل الكلوي والوفاة.',
              'unsafeExpEn': 'Error; toughing out extreme heat leads to acute kidney failure and heat stroke.',
              'unsafeOutAr': 'تعرض كبار السن للخطر.',
              'unsafeOutEn': 'Exposed elderly to renal stroke risk.',
            },
            {
              'sitAr': 'إصلاح التكييف واختباره. ما الصيانة الوقائية السنوية؟',
              'sitEn': 'AC repaired; home cooled. Annual preventive maintenance standard?',
              'hintAr': 'غسل الفلاتر وشحن الفريون وفحص المحركات قبل حلول فصل الصيف',
              'hintEn': 'Wash air filters, inspect freon levels, and service AC motors before summer',
              'safeTextAr': 'إجراء صيانة شمولية للتكييف وغسل الفلاتر قبل بداية الصيف كل عام',
              'safeTextEn': 'Schedule comprehensive AC maintenance and filter washing every spring before heat hits',
              'safeExpAr': 'إتمام كامل؛ الصيانة الاستباقية تضمن عمل التكييف بكفاءة في أشد أيام الصيف.',
              'safeExpEn': 'Complete resolution; proactive spring tuning ensures AC reliability during heatwaves.',
              'safeOutAr': 'أكملت محطات تعطل التكييف بنجاح!',
              'safeOutEn': 'Successfully completed home AC failure scenario!',
              'unsafeTextAr': 'إهمال غسيل الفلاتر والصيانة حتى يتوقف التكييف فجأة',
              'unsafeTextEn': 'Neglect AC cleaning until unit breaks down completely',
              'unsafeExpAr': 'خطأ؛ انسداد الفلاتر بالغياب يسبب احتراق المكبس (Compressor).',
              'unsafeExpEn': 'Error; clogged filters overheat compressor causing complete system breakdown.',
              'unsafeOutAr': 'احترق مكبس التكييف.',
              'unsafeOutEn': 'AC compressor burned out.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_6',
          categoryId: 'heat',
          titleAr: 'الجفاف الحاد وهبوط الضغط بالحرارة',
          titleEn: 'Severe Dehydration & Heat Hypotension',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع هبوط الضغط والجفاف الناتج عن الحرارة.',
          descriptionEn: 'Interactive 5-station scenario for heat dehydration hypotension.',
          difficulty: 'متوسط',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'شعر شخص بدوار حاد وضبابية رؤية مع جفاف لسانه بعد مشي صيفي. ما أول حركة؟',
              'sitEn': 'Person feels dizzy with blurred vision and dry tongue after summer walk. Action?',
              'hintAr': 'إجلاس الشخص فوراً بالظل ورفع قدميه لأعلى لتنشيط الدورة الدموية',
              'hintEn': 'Sit/lay person down in shade immediately elevating legs to boost brain blood flow',
              'safeTextAr': 'إجلاس المصاب بالظل وتمديده مع رفع قدميه على وسادة لتغذية الدماغ بالدم',
              'safeTextEn': 'Lie person down in shade elevating their legs on a cushion to restore brain blood flow',
              'safeExpAr': 'تصرف إسعافي ممتاز؛ رفع الساقين يعيد الدم للقلب والدماغ ويمنع الإغماء.',
              'safeExpEn': 'Excellent paramedic step; elevating legs pools venous blood back to brain stopping syncope.',
              'safeOutAr': 'رفعت الساقين وأمّنت الوعي للمحطة 2.',
              'safeOutEn': 'Elevated legs restoring brain flow for Station 2.',
              'unsafeTextAr': 'إرغام المصاب على مواصلة المشي والوقوف واقفا',
              'unsafeTextEn': 'Force dizzy person to keep walking upright in sun',
              'unsafeExpAr': 'خطأ؛ إبقاء المصاب واقفاً يسبب هبوطاً حاداً بالضغط وسقوطاً مفاجئاً.',
              'unsafeExpEn': 'Error; keeping dizzy person upright causes sudden orthostatic collapse and head trauma.',
              'unsafeOutAr': 'سقط المصاب مغشياً عليه.',
              'unsafeOutEn': 'Victim collapsed violently.',
            },
            {
              'sitAr': 'قياس نبض المصاب وجد أنه سريع وضعيف مع جفاف بالجلد. ما نوع السائل المطلوبة؟',
              'sitEn': 'Victim pulse rapid/weak with dry inelastic skin. Correct rehydration fluid?',
              'hintAr': 'محلول معالجة الجفاف الفموي (ORS) أو ماء مضاف له قليل من الملح والسكر',
              'hintEn': 'Oral Rehydration Salts (ORS) or water with small pinch of salt/sugar',
              'safeTextAr': 'إعطاء محلول معالجة الجفاف (ORS) أو ماء مع قليل من ملح الطعام والسكر',
              'safeTextEn': 'Provide Oral Rehydration Solution (ORS) or water mixed with small pinch of salt',
              'safeExpAr': 'إعادة ترطيب علمية؛ الأملاح تلزم امتصاص الماء داخل الخلايا والأوعية.',
              'safeExpEn': 'Scientific rehydration; electrolyte sodium enables cellular water absorption.',
              'safeOutAr': 'أعطيت محلول الجفاف للمحطة 3.',
              'safeOutEn': 'Administered ORS solution for Station 3.',
              'unsafeTextAr': 'إعطاء المصاب ماء مقطراً خالصاً بدون أي أملاح بكميات ضخمة',
              'unsafeTextEn': 'Gulp large volumes of pure distilled zero-mineral water',
              'unsafeExpAr': 'خطأ؛ شرب كميات ضخمة من الماء الخالي من الأملاح يسبب هبوط الصوديوم (Hyponatremia).',
              'unsafeExpEn': 'Error; massive plain water ingestion dilutes blood sodium causing fatal hyponatremia.',
              'unsafeOutAr': 'تسبب بضعف الصوديوم.',
              'unsafeOutEn': 'Triggered blood hyponatremia.',
            },
            {
              'sitAr': 'شعر المصاب بتقلصات عضلية مؤلمة في الساقين (Heat Cramps). كيف تسعف الشد العضلي؟',
              'sitEn': 'Victim suffers painful leg muscle heat cramps. First aid for heat cramps?',
              'hintAr': 'عمل تمديد هادئ ومساج خفيف للعضلة وتجنب الدلك العنيف',
              'hintEn': 'Perform gentle stretch and mild massage; avoid forceful jerking',
              'safeTextAr': 'بسط وتمديد عضلة الساق بهدوء مع مساج خفيف وتغطيتها بقماش دافئ',
              'safeTextEn': 'Gently stretch cramped calf muscle and massage lightly while staying hydrated',
              'safeExpAr': 'إسعاف سليم؛ البسط الهدوء يرخي الألياف العضلية المنقبضة بسبب نقص الصوديوم.',
              'safeExpEn': 'Correct first aid; gentle stretch releases cramped muscle fibers starved of sodium.',
              'safeOutAr': 'أرحت الشد العضلي للمحطة 4.',
              'safeOutEn': 'Relieved heat cramps for Station 4.',
              'unsafeTextAr': 'شد القدم بقوة وعنف عكس الاتجاه',
              'unsafeTextEn': 'Yank foot backward with violent force',
              'unsafeExpAr': 'خطأ؛ الشد العنيف قد يسبب تمزق الألياف العضلية المنقبضة.',
              'unsafeExpEn': 'Error; violent stretching tears contracted muscle fibers causing internal bleeding.',
              'unsafeOutAr': 'تمزقت الألياف العضلية.',
              'unsafeOutEn': 'Torn muscle fibers.',
            },
            {
              'sitAr': 'استمرار هبوط الضغط وقياسه (80/50). متى تطلب الهلال الأحمر (997)؟',
              'sitEn': 'Blood pressure remains low (80/50) with confusion. Call 997 trigger?',
              'hintAr': 'الاتصال بـ 997 فوراً عند استمرار هبوط الضغط أو التشوّش الذهني',
              'hintEn': 'Dial 997 Red Crescent immediately if low BP or mental confusion persists',
              'safeTextAr': 'الاتصال الفوري بـ (997 الهلال الأحمر) لنقل المصاب وتزويده بالمحاليل الوريدية (IV)',
              'safeTextEn': 'Dial 997 Red Crescent immediately for emergency IV saline fluid administration',
              'safeExpAr': 'استجابة طبية حاسمة؛ المحاليل الوريدية تعيد حجم الدم والضغط للحد الطبيعي.',
              'safeExpEn': 'Crucial medical response; IV saline rapidly restores intravascular volume & BP.',
              'safeOutAr': 'طلب الإسعاف للمحطة 5.',
              'safeOutEn': 'Called 997 IV team for Station 5.',
              'unsafeTextAr': 'إعطاء المصاب حبوب منشطة أو قهوة مركزة دون استشارة',
              'unsafeTextEn': 'Administer caffeine pills or heavy energy drinks without medical check',
              'unsafeExpAr': 'خطأ؛ المنشطات تزيد إجهاد القلب المصاب بالجفاف.',
              'unsafeExpEn': 'Error; stimulants strain dehydrated heart triggering cardiac arrhythmias.',
              'unsafeOutAr': 'أجهدت عضلة القلب.',
              'unsafeOutEn': 'Strained heart muscle.',
            },
            {
              'sitAr': 'وصول المسعفين وإعطاء المحاليل وسلامة الحالة. ما النصيحة الوقائية؟',
              'sitEn': 'Paramedics stabilize condition with IV. Daily summer fluid rule?',
              'hintAr': 'شرب 2-3 لتر ماء يومياً وعدم انتظار الشعور بالعطش لشرب الماء',
              'hintEn': 'Drink 2-3L water daily; do NOT wait until feeling thirsty to drink',
              'safeTextAr': 'شرب 2.5 لتر ماء يومياً كحد أدنى صيفاً دون انتظار الشعور بالعطش',
              'safeTextEn': 'Drink at least 2.5-3 liters of fluids daily in summer without waiting for thirst sensation',
              'safeExpAr': 'إتمام كامل؛ العطش مؤشر متأخر للجفاف وشرب الماء المستمر يقي تماماً.',
              'safeExpEn': 'Complete resolution; thirst is a delayed dehydration indicator; proactive sips prevent it.',
              'safeOutAr': 'أكملت محطات علاج الجفاف بنجاح!',
              'safeOutEn': 'Successfully completed heat dehydration scenario!',
              'unsafeTextAr': 'الاعتماد على شرب المشروبات السكرية فقط',
              'unsafeTextEn': 'Drink only high-sugar sodas and energy drinks in summer',
              'unsafeExpAr': 'خطأ؛ المشروبات السكرية لا تعوض الجفاف وتدر البول.',
              'unsafeExpEn': 'Error; high-sugar drinks worsen dehydration via osmotic diuresis.',
              'unsafeOutAr': 'استمر خطر الجفاف السكري.',
              'unsafeOutEn': 'Dehydration risk persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_7',
          categoryId: 'heat',
          titleAr: 'ارتياح الحرارة وإجهاد المشاة بالفعاليات',
          titleEn: 'Heat Fatigue During Outdoor Mass Events',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع الإجهاد الحراري في التجمعات والفعاليات.',
          descriptionEn: 'Interactive 5-station scenario for crowd heat exhaustion at mass events.',
          difficulty: 'سهل',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'أثناء حضور فعالية خارجية بالنهار سقط شخص مجاور بالزحام من الحرارة. ما أول خطوة؟',
              'sitEn': 'Person collapses from heat in outdoor crowd event at noon. First step?',
              'hintAr': 'مساعدة الشخص للخروج من الازدحام ونقله لخيام التبريد الطبية',
              'hintEn': 'Help person exit crowd matrix moving to nearest event medical cooling tent',
              'safeTextAr': 'حمل المصاب بمساعدة آخرين والخروج من الزحام لنقطة الرعاية الطبية المكيفة',
              'safeTextEn': 'Assist person out of crowd mass to nearest air-conditioned event medical tent',
              'safeExpAr': 'تصرف ممتاز؛ الخروج من التجمع المزدحم يمنع احتباس الحرارة الجماعي.',
              'safeExpEn': 'Excellent step; escaping body-to-body crowd density lowers ambient heat.',
              'safeOutAr': 'خرجت من الزحام للمحطة 2.',
              'safeOutEn': 'Exited crowd for Station 2.',
              'unsafeTextAr': 'ترك المصاب ملقى وسط أقدام الجماهير المزدحمة',
              'unsafeTextEn': 'Leave victim lying on ground amidst moving crowd feet',
              'unsafeExpAr': 'خطأ؛ ترك المصاب بالزحام يعرضه للدهس واحتباس الهواء.',
              'unsafeExpEn': 'Error; leaving fallen victim risks trampling and suffocating crowd heat.',
              'unsafeOutAr': 'تعرض المصاب للتدافع.',
              'unsafeOutEn': 'Risked trampling in crowd.',
            },
            {
              'sitAr': 'وصول المصاب لمركز التبريد الإسعافي بالفعالية. كيف تبرد الحرارة؟',
              'sitEn': 'Arrived at event medical cooling station. How to cool body quickly?',
              'hintAr': 'استخدام رذاذ المهرجانات والتبريد بالمراوح المائية ورش الجسم',
              'hintEn': 'Use water misting fans and wet sponge baths over head & body',
              'safeTextAr': 'توجيه مراوح الرذاذ المائي ونزع القبعات والسترات الثقيلة عن المصاب',
              'safeTextEn': 'Position water misting fans over victim removing hats and heavy jackets',
              'safeExpAr': 'تبريد فعال؛ الرذاذ المائي المتبخر يخفض حرارة الجلد بسرعة فائقة.',
              'safeExpEn': 'Effective cooling; evaporative misting rapidly reduces skin surface heat.',
              'safeOutAr': 'برّدت المصاب بالرذاذ للمحطة 3.',
              'safeOutEn': 'Cooled with misting fans for Station 3.',
              'unsafeTextAr': 'تغطية المصاب ببطانية ثقيلة لتغطية جسده',
              'unsafeTextEn': 'Cover overheated victim with wool blankets',
              'unsafeExpAr': 'خطأ؛ البطانيات تحبس الحرارة وتمنع تبخر الرذاذ.',
              'unsafeExpEn': 'Error; blankets trap trapped heat preventing skin evaporation.',
              'unsafeOutAr': 'ارتفعت حرارة الجسد.',
              'unsafeOutEn': 'Trapped internal body heat.',
            },
            {
              'sitAr': 'المصاب يشتكي من صداع حاد وعطش شديد. ما الإسعاف المائي؟',
              'sitEn': 'Victim complains of severe headache & extreme thirst. Water response?',
              'hintAr': 'تزويده بعبوة ماء مبردة وإعطائها على دفعات هادئة متقطعة',
              'hintEn': 'Provide chilled water bottle giving gentle sips every minute',
              'safeTextAr': 'إعطاء المصاب عبوة ماء مبردة وجعله يشرب رشفات منتظمة هادئة',
              'safeTextEn': 'Provide chilled water bottle encouraging slow steady sips every few moments',
              'safeExpAr': 'إسعاف سليم؛ الشرب التدريجي يمنع الغثيان ويعيد توازن الترطيب.',
              'safeExpEn': 'Correct first aid; gradual sips prevent vomiting and restore hydration smoothly.',
              'safeOutAr': 'أرويت المصاب للمحطة 4.',
              'safeOutEn': 'Hydrated victim steadily for Station 4.',
              'unsafeTextAr': 'إرغامه على بلع قالب ثلج كامل دفعة واحدة',
              'unsafeTextEn': 'Force victim to swallow whole ice blocks rapidly',
              'unsafeExpAr': 'خطأ؛ بلع الثلج المباشر يسبب تقلص المريء والغصة.',
              'unsafeExpEn': 'Error; swallowing whole ice blocks risks choking and esophageal spasms.',
              'unsafeOutAr': 'تعرض للغصة بالثلج.',
              'unsafeOutEn': 'Choked on ice block.',
            },
            {
              'sitAr': 'الوقاية في الفعاليات القادمة بالنهار. ما المستلزمات الشخصية الواجب حملها؟',
              'sitEn': 'Preventive readiness for future daytime outdoor events. Essential items?',
              'hintAr': 'حمل مظلة شمسية يدوية، عبوة ماء، وارتداء مظلات الرأس والواقي',
              'hintEn': 'Carry personal UV sun umbrella, water bottle, and wear broad hat',
              'safeTextAr': 'حمل مظلة شمسية يدوية، عبوة ماء شخصية، وارتداء قبعة ونظارة شمسية',
              'safeTextEn': 'Carry personal UV sun umbrella, refillable water bottle, and wear wide hat',
              'safeExpAr': 'جاهزية شخصية ممتازة؛ المظلة اليدوية تكسر 90% من الأشعة المباشرة.',
              'safeExpEn': 'Great personal prep; handheld sun umbrella blocks 90% of direct solar heat.',
              'safeOutAr': 'تجهزت للمحطة 5.',
              'safeOutEn': 'Equipped sun umbrella for Station 5.',
              'unsafeTextAr': 'حضور الفعاليات بالنهار بدون أي مظلة أو عبوة ماء',
              'unsafeTextEn': 'Attend noon outdoor festival with zero sunshade or water',
              'unsafeExpAr': 'خطأ؛ الحضور المكشوف بالحرارة يضمن حدوث الإجهاد الحراري.',
              'unsafeExpEn': 'Error; attending unshielded noon outdoor events guarantees heat exhaustion.',
              'unsafeOutAr': 'تعرض للإجهاد الحراري مجدداً.',
              'unsafeOutEn': 'Re-exposed to event heat stroke.',
            },
            {
              'sitAr': 'تأمين سلامة كبار السن بالفعالية. ما الخيار الأفضل لحضورهم؟',
              'sitEn': 'Securing elderly family at outdoor events. Best attendance plan?',
              'hintAr': 'اختيار أوقات المساء أو الممرات المغطاة المكيفة لحضور كبار السن',
              'hintEn': 'Choose evening hours or air-conditioned shaded VIP zones for elderly',
              'safeTextAr': 'جدولة حضور كبار السن في أوقات المساء أو توفير مسارات مظللة ومكيفة',
              'safeTextEn': 'Schedule elderly family visits during cooler evening hours or shaded VIP zones',
              'safeExpAr': 'إتمام ناجح؛ اختيار الأوقات الباردة يحمي كبار السن من مخاطر الشمس.',
              'safeExpEn': 'Successful completion; choosing cool evening hours keeps elderly safe.',
              'safeOutAr': 'أكملت محطات سلامة الفعاليات بنجاح!',
              'safeOutEn': 'Successfully completed event heat safety scenario!',
              'unsafeTextAr': 'إصطحاب كبار السن بالظهيرة 1 ظهراً وتكليفهم بالمشي الطويل',
              'unsafeTextEn': 'Force elderly family to walk long distances in 1 PM noon sun',
              'unsafeExpAr': 'خطأ؛ مشي كبار السن بالظهر يسبب الهبوط الحاد والصدمة الحرارية.',
              'unsafeExpEn': 'Error; pushing elderly to walk in noon heat causes rapid cardiovascular shock.',
              'unsafeOutAr': 'عرض كبار السن للصدمة الحرارية.',
              'unsafeOutEn': 'Exposed elderly to severe heat shock.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_8',
          categoryId: 'heat',
          titleAr: 'احتراق إطار المركبة بالخط السريع صيفاً',
          titleEn: 'Highway Tire Blowout in Summer Heat',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انصلاح وانفجار الإطارات في الحرارة.',
          descriptionEn: 'Interactive 5-station scenario for summer highway tire blowouts.',
          difficulty: 'صعب',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'أثناء القيادة بسعرعة 110 كم/س صيفاً انفجر الإطار الخلفي فجأة. ما أول تصرف؟',
              'sitEn': 'Rear tire blows out at 110 km/h in summer heat. Immediate action?',
              'hintAr': 'الإمساك بالمقود بقوة وتجنب الضغط الفجائي على الفرامل إطلاقاً',
              'hintEn': 'Grip steering wheel firmly with both hands; do NOT slam brakes',
              'safeTextAr': 'الإمساك بمقود السيارة بقوة بجلتا اليدين ورفع القدم عن دواسة البنزين تدريجياً',
              'safeTextEn': 'Grip steering wheel firmly with both hands and ease off accelerator pedal slowly',
              'safeExpAr': 'استجابة ذهبية؛ الفرملة المفاجئة عند انفجار الإطار تسبب الانقلاب الفوري.',
              'safeExpEn': 'Golden response; slamming brakes during tire blowout triggers immediate rollover.',
              'safeOutAr': 'حافظت على توازن السيارة للمحطة 2.',
              'safeOutEn': 'Maintained vehicle control for Station 2.',
              'unsafeTextAr': 'الضغط بقوة وحرارة على دواسة الفرامل (Slam Brakes)',
              'unsafeTextEn': 'Slam brakes as hard as possible immediately',
              'unsafeExpAr': 'خطأ قاتل؛ الفرملة القاسية عند الانفجار تجعل الجنط يحتك بالإسفلت وينقلب.',
              'unsafeExpEn': 'Fatal mistake; sudden hard braking catches bare metal rim spinning car into flip.',
              'unsafeOutAr': 'انقلبت السيارة بالخط السريع.',
              'unsafeOutEn': 'Car flipped on highway.',
            },
            {
              'sitAr': 'تراجعت السرعة لـ 40 كم/س. كيف توقف السيارة بمكان آمن صيفاً؟',
              'sitEn': 'Speed drops to 40 km/h. How to stop car safely on hot highway?',
              'hintAr': 'الانحراف التدريجي نحو الكتف الأيمن وتفعيل أضواء التحذير الرباعية',
              'hintEn': 'Steer gradually onto far right shoulder activating hazard lights',
              'safeTextAr': 'الانحراف التدريجي الهادئ نحو الأكتاف الترابية الأيمن وتفعيل الفلاشر',
              'safeTextEn': 'Steer smoothly onto far right dirt shoulder and turn on hazard emergency flashers',
              'safeExpAr': 'تصرف سليم؛ التوقف بعيداً عن حارة السير يمنع اصطدام السيارات القادمة.',
              'safeExpEn': 'Correct move; pulling completely off active lanes avoids rear-end collisions.',
              'safeOutAr': 'أوقفت السيارة بالأكتاف للمحطة 3.',
              'safeOutEn': 'Parked on right shoulder for Station 3.',
              'unsafeTextAr': 'التوقف المفاجئ وسط المسار الأيسر السريع',
              'unsafeTextEn': 'Stop dead in middle of fast left lane',
              'unsafeExpAr': 'خطأ؛ التوقف بالمسار السريع يسبب اصطدام الشاحنات والسيارات بمركبتك.',
              'unsafeExpEn': 'Error; stopping in fast lane triggers catastrophic multi-car high speed crashes.',
              'unsafeOutAr': 'تعرضت لاصطدام خلفي.',
              'unsafeOutEn': 'Rear-ended by fast traffic.',
            },
            {
              'sitAr': 'الترجل لتغيير الإطار تحت شمس الظهيرة الحارقة. كيف تحمي نفسك مرورياً وحرارياً؟',
              'sitEn': 'Getting out to change tire under 45°C noon sun. Safety protocol?',
              'hintAr': 'وضع مثلث السلامة على 100م وارتداء سترة السلامة ومشروب ماء',
              'hintEn': 'Set warning triangle 100m back, wear safety vest, stay hydrated',
              'safeTextAr': 'وضع مثلث السلامة على مسافة 100 متر وارتداء سترة عاكسة وشرب الماء أثناء التغيير',
              'safeTextEn': 'Place warning triangle 100 meters behind and wear reflective vest while changing tire',
              'safeExpAr': 'تأمين ممتاز؛ المثلث ينبه الشاحنات والماء يقي من ضربة الشمس أثناء الفك.',
              'safeExpEn': 'Great protection; triangle warns fast trucks and hydration prevents heatstroke.',
              'safeOutAr': 'أمّنت الموقع وغيرت الإطار للمحطة 4.',
              'safeOutEn': 'Set triangle & changed tire for Station 4.',
              'unsafeTextAr': 'العمل والظهر موجه نحو حركة السيارات بدون مثلث سلامة',
              'unsafeTextEn': 'Work with back turned to oncoming traffic without warning triangle',
              'unsafeExpAr': 'خطأ؛ العمل بدون مثلث يعرضك للدهس الفوري من السيارات السريعة.',
              'unsafeExpEn': 'Error; working on shoulder without warning triangle risks pedestrian fatality.',
              'unsafeOutAr': 'تعرضت لخطر الدهس.',
              'unsafeOutEn': 'High risk of pedestrian strike.',
            },
            {
              'sitAr': 'فحص سبب الانفجار وتبين أنه بسبب انخفاض/ارتفاع ضغط الهواء وتآكل الإطار صيفاً. المعيار؟',
              'sitEn': 'Inspecting blowout cause: over/under inflation & worn tread in heat. Standard?',
              'hintAr': 'فحص تاريخ الإطار، معيار التماسك (Traction A)، وضغط الهواء الموصى به',
              'hintEn': 'Check tire manufacture date, Traction A rating, and recommended PSI',
              'safeTextAr': 'الالتزام بإطارات ذات تصنيف حراري (Temperature A) وضبط الضغط المعياري (PSI)',
              'safeTextEn': 'Ensure tires have Temperature A rating and maintain recommended cold PSI pressure',
              'safeExpAr': 'معيار أمني ممتاز؛ إطارات Temperature A مصممة لتحمل حرارة الإسفلت العالية (70C+).',
              'safeExpEn': 'Excellent safety standard; Temp A rated tires withstand 70°C+ summer asphalt.',
              'safeOutAr': 'فحصت معايير الإطار للمحطة 5.',
              'safeOutEn': 'Verified Temp A tire specs for Station 5.',
              'unsafeTextAr': 'شراء إطارات مستعملة قديمة (منتهية الصنع) صيفاً',
              'unsafeTextEn': 'Buy expired 5-year-old used tires to save money in summer',
              'unsafeExpAr': 'خطأ؛ الإطارات القديمة المنتهية تتفتت بالحرارة وتنفجر فوراً.',
              'unsafeExpEn': 'Error; expired rubber degrades internally disintegrating instantly under heat.',
              'unsafeOutAr': 'عرضت السيارة لانفجار مجدد.',
              'unsafeOutEn': 'Installed unsafe expired tire.',
            },
            {
              'sitAr': 'الاستمرار بالرحلة بسلامة. ما الفحص الدوري للإطارات بالشتاء والصيف؟',
              'sitEn': 'Resuming journey safely. Routine tire safety check rule?',
              'hintAr': 'فحص ضغط الإطارات أسبوعياً وهو بارد وفحص عمق النقشة وتاريخ الصنع',
              'hintEn': 'Check cold tire pressure weekly and audit tread depth & manufacture date',
              'safeTextAr': 'فحص ضغط الإطارات أسبوعياً صباحاً وتغيير الإطار كل 40,000 كم أو سنتين',
              'safeTextEn': 'Check tire PSI cold every week and replace tires every 40,000 km or 2 years',
              'safeExpAr': 'إتمام كامل؛ الفحص الدوري المنتظم يمنع 95% من حوادث انفجار الإطارات صيفاً.',
              'safeExpEn': 'Complete resolution; weekly cold PSI checks prevent 95% of summer blowouts.',
              'safeOutAr': 'أكملت محطات نجاة انفجار الإطار بنجاح!',
              'safeOutEn': 'Successfully completed tire blowout scenario!',
              'unsafeTextAr': 'إهمال ضغط الإطارات حتى ينخفض لـ 15 PSI بالخط السريع',
              'unsafeTextEn': 'Neglect tire pressure driving on 15 PSI underinflated tires at 120 km/h',
              'unsafeExpAr': 'خطأ؛ القيادة بإطار منخفض الضغط تبني حرارة احتكاك مدمرة تفجر الإطار.',
              'unsafeExpEn': 'Error; driving underinflated tires flexes sidewalls building catastrophic heat blowouts.',
              'unsafeOutAr': 'تجدد خطر انفجار الإطار.',
              'unsafeOutEn': 'Sidewall heat built up dangerously.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_heat_9',
          categoryId: 'heat',
          titleAr: 'ضربة حرارية لكبار السن بالمنزل',
          titleEn: 'Indoor Heatstroke in Elderly Family Members',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لإنقاذ كبار السن من ضربات الشمس والإجهاد الحراري المغلق.',
          descriptionEn: 'Interactive 5-station scenario for indoor heatstroke in elderly.',
          difficulty: 'صعب',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          stations: [
            {
              'sitAr': 'وجدة جدك بالمنزل يشتكي من ارتباك ذكري وزغللة بالعينين وجلده ساخن جاف بدون عرق. ما هذا؟',
              'sitEn': 'Found grandfather at home confused, hot dry skin with zero sweat. Diagnosis & action?',
              'hintAr': 'هذه حالة ضربة شمس داخلية (Classic Heatstroke)؛ الاتصال بـ 997 والتبريد الفوري',
              'hintEn': 'Classic indoor heatstroke! Call Red Crescent 997 immediately & start cooling',
              'safeTextAr': 'الاتصال الفوري بـ (997 الإسعاف) والبدء بنقله للغرفة المكيفة وتبريد الجسد',
              'safeTextEn': 'Call 997 Red Crescent immediately and move elder to cool AC room starting cooling',
              'safeExpAr': 'تشخيص وتصرف ذهبي؛ غياب العرق مع حرارة الجلد علامة ضربة شمس حرجة.',
              'safeExpEn': 'Golden response; hot dry skin with zero sweat indicates medical emergency heatstroke.',
              'safeOutAr': 'أبلغت 997 ونقلته للتكييف للمحطة 2.',
              'safeOutEn': 'Called 997 and moved to AC for Station 2.',
              'unsafeTextAr': 'إعطاؤه مسكنات بندول وإجلاسه بالحرارة بانتظار استيقاظه',
              'unsafeTextEn': 'Give oral painkiller pills leaving him sitting in warm uncooled room',
              'unsafeExpAr': 'خطأ قاتل؛ المسكنات لا تخفض حرارة ضربة الشمس وتضيع الوقت الفعلي للإسعاف.',
              'unsafeExpEn': 'Fatal mistake; antipyretic pills fail to lower heatstroke core temps wasting time.',
              'unsafeOutAr': 'تدهورت درجة الحرارة الداخلية.',
              'unsafeOutEn': 'Core temp escalated dangerously.',
            },
            {
              'sitAr': 'كيف تبرد جسم كبير السن المصاب بضربة الشمس بأمان دون صدمة؟',
              'sitEn': 'How to cool elderly heatstroke victim safely without shock?',
              'hintAr': 'رش ماء فاتر وتوجيه مروحة عليه لتبخير الماء وتبريد الجلد',
              'hintEn': 'Spray lukewarm water over skin and direct fan to create evaporative cooling',
              'safeTextAr': 'رش جسم كبار السن بماء فاتر وتوجيه مروحة هادئة لتبخير الماء وتخفيض الحرارة',
              'safeTextEn': 'Spray skin with lukewarm water and use gentle fan to evaporate moisture',
              'safeExpAr': 'أفضل طريقة علمية؛ التبريد التبخيري (Evaporative Cooling) هو الخيار الطبي الأكثر أماناً.',
              'safeExpEn': 'Top medical method; evaporative misting & fanning is the safest paramedic cooling tactic.',
              'safeOutAr': 'بدأت التبريد التبخيري للمحطة 3.',
              'safeOutEn': 'Started evaporative cooling for Station 3.',
              'unsafeTextAr': 'وضع الثلج المباشر فوق صدر الرأس لكبير السن',
              'unsafeTextEn': 'Apply direct ice packs over chest and head of elderly person',
              'unsafeExpAr': 'خطأ؛ الثلج المباشر يسبب انقباض الشرايين وصدمة قلبية لكبار السن.',
              'unsafeExpEn': 'Error; direct ice application triggers severe vasoconstriction and cardiac arrest.',
              'unsafeOutAr': 'تعرض المصاب لانقباض شرياني.',
              'unsafeOutEn': 'Vascular shock from direct ice.',
            },
            {
              'sitAr': 'كبير السن شبه مغمى عليه وغير قادر على البلع. هل تسقيه ماء؟',
              'sitEn': 'Elderly victim semi-conscious unable to swallow properly. Offer water?',
              'hintAr': 'حظر إعطاء أي سوائل فموية للشخص شبه المغمى عليه لمنع الغرق الرئوي',
              'hintEn': 'NEVER give oral fluids to semi-conscious person; risks aspiration drowning',
              'safeTextAr': 'حظر إعطاء السوائل الفموية كلياً وتعديل الوضعية للجانب لحماية مجرى التنفس',
              'safeTextEn': 'Refrain from giving any oral fluids; position elder on side in recovery stance',
              'safeExpAr': 'قاعدة طبية صارمة؛ سكب السوائل الفموية لمن لا يبلع يدخل الماء للرئتين مباشرة.',
              'safeExpEn': 'Strict medical rule; pouring liquids down semi-conscious throat floods lungs (aspiration).',
              'safeOutAr': 'حميت مجرى التنفس للمحطة 4.',
              'safeOutEn': 'Protected airway for Station 4.',
              'unsafeTextAr': 'سكب الماء بالقوة داخل فم كبير السن شبه المغمى عليه',
              'unsafeTextEn': 'Force water down semi-conscious elder throat to hydrate him',
              'unsafeExpAr': 'خطأ كوارثي؛ سكب الماء يسبب انسداد القصبة الهوائية وتوقف التنفس.',
              'unsafeExpEn': 'Catastrophic error; forcing water down un-reflexive throat drowns lungs.',
              'unsafeOutAr': 'دخل الماء للرئتين.',
              'unsafeOutEn': 'Aspiration fluid flooded lungs.',
            },
            {
              'sitAr': 'وصول فرقة الهلال الأحمر (997). كيف توضح التاريخ الطبي لكبير السن؟',
              'sitEn': 'Saudi Red Crescent 997 paramedics arrive. How to present medical history?',
              'hintAr': 'تزويد المسعف بأدوية الضغط/السكري المسجلة وحرارة الجسم المستهدفة',
              'hintEn': 'Provide paramedics with list of chronic medications (BP/Diabetes) & temperature',
              'safeTextAr': 'تزويد طاقم الإسعاف بقائمة أدوية الضغط والسكري وتفاصيل وقت بداية الحرارة',
              'safeTextEn': 'Hand paramedics list of chronic medications (BP/Diabetes) & onset time details',
              'safeExpAr': 'تسليم نموذجي؛ معلومات الأدوية تساعد الطبيب على اختيار المحاليل المناسبة.',
              'safeExpEn': 'Model handoff; chronic med list enables paramedics to tailor IV fluid therapy.',
              'safeOutAr': 'سلمت التقرير الطبي للمحطة 5.',
              'safeOutEn': 'Handed medical history to 997 for Station 5.',
              'unsafeTextAr': 'إخفاء الأدوية والمغادرة دون الحديث للمسعف',
              'unsafeTextEn': 'Hide medication bottles and stay quiet during paramedic exam',
              'unsafeExpAr': 'خطأ؛ إخفاء تاريخ الأدوية قد يتسبب في إعطاء محاليل متعارضة.',
              'unsafeExpEn': 'Error; concealing medical history risks contra-indicated emergency drug interaction.',
              'unsafeOutAr': 'تأخر التقييم الطبي الدقيق.',
              'unsafeOutEn': 'Delayed precise IV therapy.',
            },
            {
              'sitAr': 'نقل كبير السن للمستشفى واستقرار حالته. ما الإجراء المنزلي الوقائي صيفاً؟',
              'sitEn': 'Grandfather hospitalized and stabilized. Home preventive protocol?',
              'hintAr': 'توفير التكييف المستمر 24/7 بغرفة كبار السن ومتابعة شرب الماء',
              'hintEn': 'Ensure 24/7 climate-controlled room for elderly and monitor daily water sips',
              'safeTextAr': 'تأمين التكييف المستمر المعتدل ومتابعة شرب 2 لتر ماء يومياً لكبار السن',
              'safeTextEn': 'Ensure 24/7 continuous AC climate control and actively prompt 2L daily water sips',
              'safeExpAr': 'إتمام ناجح؛ كبار السن يفقدون الشعور بالعطش وتنبيههم المستمر أنقذ حياتهم.',
              'safeExpEn': 'Successful completion; elderly lose natural thirst sensation; active prompting saves lives.',
              'safeOutAr': 'أكملت محطات حماية كبار السن من الحرارة بنجاح!',
              'safeOutEn': 'Successfully completed indoor elderly heatstroke scenario!',
              'unsafeTextAr': 'إطفاء التكييف ليلاً بالصيف لتوفير الكهرباء',
              'unsafeTextEn': 'Turn off AC in elderly bedroom at night to save electricity in summer',
              'unsafeExpAr': 'خطأ؛ إطفاء التكييف صيفاً يرفع حرارة الغرفة ليلاً ويجدد ضربة الشمس.',
              'unsafeExpEn': 'Error; shutting AC at night in summer traps heat causing nocturnal heatstroke.',
              'unsafeOutAr': 'تجدد خطر الحرارة ليلاً.',
              'unsafeOutEn': 'Nocturnal heatstroke risk.',
            },
          ],
        ),
      ];
}
