import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosEmergencyKit {
  static List<Scenario> get list => [
        // 1. Emergency Kit Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_1',
          categoryId: 'emergency_kit',
          titleAr: 'تجهيز حقيبة الطوارئ الأسرية 72 ساعة',
          titleEn: 'Family 72-Hour Emergency Survival Kit',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجهيز حزمة البقاء والإمدادات الحيوية للأزمات.',
          descriptionEn: 'Interactive 5-station scenario for assembling a 72-hour family emergency kit.',
          difficulty: 'سهل',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'تجهيز كميات المياه الحيوية للحقيبة الأسرية. ما المقدار الأسبوعي/اليومي للشخص؟',
              'sitEn': 'Calculating essential water supply for emergency kit. Required volume per person per day?',
              'hintAr': 'توفير 3 لترات من الماء النقي لكل شخص يومياً (للشرب والنظافة)',
              'hintEn': 'Store 3 liters of clean drinkable water per person per day for at least 3 days',
              'safeTextAr': 'تخزين 3 لترات من الماء الصالح للشرب لكل فرد من الأسرة يومياً لمدة 3 أيام متتالية',
              'safeTextEn': 'Store 3 liters of potable bottled water per family member per day for 72 hours',
              'safeExpAr': 'حساب دقيق؛ 3 لترات تضمن ترطيب الجسم وتجنب الجفاف الخطير أثناء انقطاع الإمدادات.',
              'safeExpEn': 'Accurate calculation; 3L per person daily prevents severe dehydration during grid outage.',
              'safeOutAr': 'حسبت كميات المياه للمحطة 2.',
              'safeOutEn': 'Calculated water ration for Station 2.',
              'unsafeTextAr': 'تخزين علبة ماء واحدة صغيرة (250 مل) لكل فرد في الحقيبة',
              'unsafeTextEn': 'Pack a single 250ml small water bottle per person for 3 days',
              'unsafeExpAr': 'خطأ؛ 250 مل لا تكفي للبقاء سوى لعدة ساعات وتسبب الجفاف السريع.',
              'unsafeExpEn': 'Error; 250ml is dangerously insufficient leading to heat stress and dehydration.',
              'unsafeOutAr': 'نقص حاد بالمياه.',
              'unsafeOutEn': 'Critical water shortage.',
            },
            {
              'sitAr': 'اختيار نوعية الأغذية لحقيبة الإمدادات الطارئة. ما المواصفات الأفضل للأطعمة؟',
              'sitEn': 'Selecting food types for survival kit. Best food characteristics?',
              'hintAr': 'أطعمة المعلبات غير القابلة للتلف، التمور، المكسرات، وحبوب الطاقة سهلة الفتح',
              'hintEn': 'Non-perishable canned foods, Saudi dates, energy bars with pull-ring pop-tops',
              'safeTextAr': 'أطعمة معلبة طويلة الأجل، تمور جافة، زبدة الفول السوداني، وحبوب طاقة عالية السعرات',
              'safeTextEn': 'Pack long-shelf-life canned food, dry dates, peanut butter, and high-calorie energy bars',
              'safeExpAr': 'اختيار ذكي؛ الأطعمة الجافة والمعلبة توفر الطاقة دون الحاجة لطهي أو ثلاجة.',
              'safeExpEn': 'Smart choice; non-perishable ready-to-eat foods provide calories without cooking or power.',
              'safeOutAr': 'اخترت الأغذية المحفوظة للمحطة 3.',
              'safeOutEn': 'Packed non-perishable foods for Station 3.',
              'unsafeTextAr': 'تعبئة مطبوخات طازجة ولحوم نية تحتاج للثلاجة',
              'unsafeTextEn': 'Pack fresh cooked meals and raw meats requiring refrigeration',
              'unsafeExpAr': 'خطأ؛ الأغذية الطازجة تفسد بسرعة وتسبب تسمماً غذائياً أثناء الأزمات.',
              'unsafeExpEn': 'Error; fresh food spoils within hours causing food poisoning in emergency situations.',
              'unsafeOutAr': 'تلف الطعام بالحقيبة.',
              'unsafeOutEn': 'Food spoiled in kit.',
            },
            {
              'sitAr': 'تجهيز المستلزمات الطبية والدوائية الخاصة بالحقيبة. ما الواجب توفره للأسرة؟',
              'sitEn': 'Assembling medical and pharmaceutical essentials in kit. What must be included?',
              'hintAr': 'حقيبة إسعافات أولية، مطهرات، ضمادات، وأدوية الأمراض المزمنة لمدة أسبوع',
              'hintEn': 'First aid supplies, antiseptics, bandages, plus 7-day supply of personal prescription meds',
              'safeTextAr': 'حقيبة إسعافات أولية متكاملة وأدوية الأمراض المزمنة (كالضغط والسكر) لمدة 7 أيام',
              'safeTextEn': 'Include standard first aid kit plus a 7-day backup reserve of personal prescription medications',
              'safeExpAr': 'تأمين طبي ممتاز؛ توفر أدوية الوصفات الطبية يحمي أفراد الأسرة من الانتكاسات.',
              'safeExpEn': 'Great medical prep; backup prescription meds prevent chronic health breakdowns.',
              'safeOutAr': 'أمنت الإمدادات الطبية للمحطة 4.',
              'safeOutEn': 'Secured medical supplies for Station 4.',
              'unsafeTextAr': 'الاكتفاء بشرائط لاصق جروح جافة دون أدوية الوصفات',
              'unsafeTextEn': 'Pack only basic adhesive band-aids ignoring prescription medications',
              'unsafeExpAr': 'خطأ؛ غياب أدوية الضغط والسكر يهدد حياة المريض عند احتجاز الطرق.',
              'unsafeExpEn': 'Error; missing daily chronic meds risks severe medical emergencies during isolation.',
              'unsafeOutAr': 'نقص أدوية الوصفات.',
              'unsafeOutEn': 'Missing prescription meds.',
            },
            {
              'sitAr': 'اختيار أدوات الإضاءة والتواصل لحقيبة الطوارئ. ما المعدات الأجدر للتضمين؟',
              'sitEn': 'Selecting lighting & communication tools. Essential equipment?',
              'hintAr': 'كشاف LED يدوي، راديو يعمل بالبطاريات/اليد، وبنك طاقة (Power Bank) مشحون',
              'hintEn': 'LED flashlight, hand-crank/battery radio, and charged high-capacity power bank',
              'safeTextAr': 'كشاف LED عالي الإضاءة، راديو طوارئ، وبنك طاقة مشحون مع بطاريات إضافية',
              'safeTextEn': 'Pack high-lumen LED flashlight, battery/crank emergency radio, and charged power bank',
              'safeExpAr': 'تجهيز تواصل رائع؛ الراديو يدعم تلقي توجيهات الدفاع المدني فور انقطاع الاتصالات.',
              'safeExpEn': 'Great comms choice; emergency radio receives official Civil Defense updates when cellular networks down.',
              'safeOutAr': 'أمنت أجهزة التواصل للإضاءة للمحطة 5.',
              'safeOutEn': 'Secured lights and comms for Station 5.',
              'unsafeTextAr': 'الاعتماد الكلي على كشاف الجوال دون بطاريات خارجية',
              'unsafeTextEn': 'Rely solely on mobile phone torch without carrying external batteries or power bank',
              'unsafeExpAr': 'خطأ؛ بطارية الجوال تنفد خلال ساعات قليلة وتتركك بالظلام.',
              'unsafeExpEn': 'Error; mobile phone batteries drain fast leaving you without light or emergency comms.',
              'unsafeOutAr': 'نفذت بطارية الهاتف.',
              'unsafeOutEn': 'Phone battery depleted quickly.',
            },
            {
              'sitAr': 'مكان حفظ حقيبة الطوارئ الأسرية 72 ساعة وتحديثها. ما الموقع والدورية المثالية؟',
              'sitEn': 'Storing and updating family 72-hour survival kit. Location & audit cycle?',
              'hintAr': 'حفظ الحقيبة بمكان سهل الوصول قرب مخرج المنزل وتفقد الصلاحيات كل 6 أشهر',
              'hintEn': 'Store in accessible spot near home exit gate; inspect expiry dates every 6 months',
              'safeTextAr': 'وضع الحقيبة عند مدخل المنزل الرئيسي وتفقد صلاحيات الأطعمة والأدوية كل 6 أشهر',
              'safeTextEn': 'Place kit near main exit door and inspect food/medication expiration dates every 6 months',
              'safeExpAr': 'إتمام كامل؛ الموقع عند البوابة يضمن سحب الحقيبة فوراً في حالات الإخلاء السريع.',
              'safeExpEn': 'Complete resolution; exit placement ensures immediate grab-and-go during emergency evacuation.',
              'safeOutAr': 'أكملت محطات تجهيز حقيبة الطوارئ بنجاح!',
              'safeOutEn': 'Successfully completed emergency kit preparation scenario!',
              'unsafeTextAr': 'تخزين الحقيبة تحت كراتين التخزين بأعماق المستودع العليوي',
              'unsafeTextEn': 'Bury emergency kit deep under storage boxes in roof attic',
              'unsafeExpAr': 'خطأ؛ التخزين البعيد يمنع الوصول للحقيبة عند الإخلاء الفوري.',
              'unsafeExpEn': 'Error; inaccessible storage prevents grabbing kit during rapid emergency evacuation.',
              'unsafeOutAr': 'تعذر الوصول للحقيبة.',
              'unsafeOutEn': 'Kit unreachable during emergency.',
            },
          ],
        ),

        // 2. Emergency Kit Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_2',
          categoryId: 'emergency_kit',
          titleAr: 'الإسعافات الأولية للنزيف والجروح القطعية',
          titleEn: 'First Aid for Severe Bleeding & Cuts',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للسيطرة على النزيف الحاد وتضميد الجروح بسلامة.',
          descriptionEn: 'Interactive 5-station scenario for controlling severe arterial bleeding & wound care.',
          difficulty: 'متوسط',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'إصابة شخص بجرح قطعي غائر في الساعد وينزف دماً أحمراً زاهياً بغزارة. ما الإجراء الأول؟',
              'sitEn': 'Deep forearm cut spewing bright red blood rapidly. Immediate first aid action?',
              'hintAr': 'الضغط المباشر على مكان الجرح باستخدام قماش نظيف أو ضمادة طبية معقمة',
              'hintEn': 'Apply firm direct pressure onto wound using clean cloth or sterile gauze pad',
              'safeTextAr': 'الضغط المباشر الثابت على مكان الجرح بضمادة معقمة أو قماش نظيف بدون رفعه',
              'safeTextEn': 'Apply continuous firm direct pressure over wound with sterile gauze or clean cloth',
              'safeExpAr': 'تصرف أساسي؛ الضغط المباشر هو خط الدفاع الأول لوقف النزيف وتجلط الدم.',
              'safeExpEn': 'Primary aid; direct pressure compresses severed vessels and promotes blood clotting.',
              'safeOutAr': 'ضغطت على النزيف للمحطة 2.',
              'safeOutEn': 'Applied direct pressure for Station 2.',
              'unsafeTextAr': 'غسل الجرح بالماء الجاري والمشاهدة دون تطبيق أي ضغط',
              'unsafeTextEn': 'Rinse wound with running tap water while standing by without applying pressure',
              'unsafeExpAr': 'خطأ جسيم؛ غسل النزيف الشديد يزيل التجلط الطبيعي ويزيد فقدان الدم.',
              'unsafeExpEn': 'Severe error; washing active heavy arterial bleeding washes away clots accelerating blood loss.',
              'unsafeOutAr': 'استمر تتدفق الدم.',
              'unsafeOutEn': 'Severe blood flow persisted.',
            },
            {
              'sitAr': 'تشبعت الضمادة الأولى بالدم بالكامل. هل تزيل الضمادة المبللة وتضع جديدة؟',
              'sitEn': 'First gauze pad becomes completely soaked with blood. Should you remove it?',
              'hintAr': 'حظر إزالة الضمادة المبللة بالدم، وإضافة ضمادة ثانية فوقها ومواصلة الضغط',
              'hintEn': 'NEVER remove blood-soaked pad; add secondary pad directly on top and continue pressure',
              'safeTextAr': 'إضافة ضمادة جديدة فوق الضمادة الأولى المبتلّة ومواصلة الضغط القوي بدون رفع الأولى',
              'safeTextEn': 'Place additional sterile pad directly on top of soaked pad maintaining firm pressure',
              'safeExpAr': 'إجراء طبي سليم؛ رفع الضمادة الأولى يمزق تخثر الخثرة النامية ويستأنف النزيف.',
              'safeExpEn': 'Correct medical step; removing initial pad tears forming blood clot resuming heavy bleed.',
              'safeOutAr': 'أضفت ضمادة جديدة للمحطة 3.',
              'safeOutEn': 'Added secondary pad for Station 3.',
              'unsafeTextAr': 'نزع الضمادة الأولى المبللة بقوة ورؤية الجرح مجدداً',
              'unsafeTextEn': 'Peel off blood-soaked initial pad to inspect wound depth',
              'unsafeExpAr': 'خطأ؛ نزع الضمادة يزيل التخثر المكون ويزيد النزيف خطورة.',
              'unsafeExpEn': 'Error; peeling off soaked pad destroys developing clot re-opening damaged artery.',
              'unsafeOutAr': 'نزف الجرح مجدداً.',
              'unsafeOutEn': 'Wound bled heavily again.',
            },
            {
              'sitAr': 'ال نزيف ما زال مستمراً بغزارة من الطرف السلفي. كيف تسعف المصاب بوضعية الجسم؟',
              'sitEn': 'Bleeding continues heavily from limb. How to position body to aid control?',
              'hintAr': 'رفع الطرف المصاب أعلى من مستوى القلب إذا لم توجد كسور',
              'hintEn': 'Elevate injured limb above heart level (if no bone fracture suspected)',
              'safeTextAr': 'رفع الساعد المصاب أعلى من مستوى القلب لتخفيف ضغط تدفق الدم على الجرح',
              'safeTextEn': 'Elevate bleeding arm above level of heart to reduce hydrostatic blood pressure',
              'safeExpAr': 'تكتيك إسعافي؛ رفع الطرف يقلل الضغط الشرياني ويساعد الضغط المباشر على التجلط.',
              'safeExpEn': 'Paramedic technique; elevation drops local arterial pressure aiding rapid clot formation.',
              'safeOutAr': 'رفعت الطرف المصاب للمحطة 4.',
              'safeOutEn': 'Elevated injured arm for Station 4.',
              'unsafeTextAr': 'ترك اليد المصابة متدلية للأسفل نحو الأرض',
              'unsafeTextEn': 'Let injured arm hang down toward floor',
              'unsafeExpAr': 'خطأ؛ تدلي الطرف يرفع الضغط الشرياني ويزيد سرعة النزيف.',
              'unsafeExpEn': 'Error; hanging limb increases gravitational blood flow accelerating hemorrhage.',
              'unsafeOutAr': 'ازداد تدفق النزيف.',
              'unsafeOutEn': 'Blood loss accelerated.',
            },
            {
              'sitAr': 'استمرار النزيف الكارثي النابض رغم الضغط والرفع. كيف تطبق عاصبة الشرايين (Tourniquet)؟',
              'sitEn': 'Life-threatening arterial pulse bleed persists. How to correctly apply a Tourniquet?',
              'hintAr': 'ربط العاصبة فوق الجرح بـ 5-7 سم (باتجاه القلب) وشدها حتى يتوقف النزيف وكتابة التوقيت',
              'hintEn': 'Apply tourniquet 5-7 cm above wound (towards heart), tighten until bleeding stops, mark time',
              'safeTextAr': 'تثبيت العاصبة أعلى الجرح بـ 5 سم، تدوير العصا حتى يتوقف النزيف، وتدوين وقت الربط على جبهة المصاب',
              'safeTextEn': 'Apply tourniquet 5cm above wound site, turn windlass tight until bleed stops, mark application time',
              'safeExpAr': 'إنقاذ حرج؛ استخدام العاصبة المعيارية يمنع الوفاة من الصدمة النزفية في دقائق.',
              'safeExpEn': 'Life-saving action; proper tourniquet placement stops arterial exsanguination in minutes.',
              'safeOutAr': 'طبقت العاصبة ودوّنت الوقت للمحطة 5.',
              'safeOutEn': 'Applied tourniquet and marked time for Station 5.',
              'unsafeTextAr': 'ربط سلك كهربائي ضيق مباشرة فوق صابونة الجرح دون تدوين الوقت',
              'unsafeTextEn': 'Tie thin electric wire tightly directly inside open wound without noting time',
              'unsafeExpAr': 'خطأ؛ الأسلاك النحاسية تقطع الجلد وتسبب تلفاً عصبياً ودائماً بالأنسجة.',
              'unsafeExpEn': 'Error; improvised thin wire cuts through muscle causing irreversible nerve damage.',
              'unsafeOutAr': 'تلف أنسجة وأعصاب.',
              'unsafeOutEn': 'Severe tissue & nerve laceration.',
            },
            {
              'sitAr': 'وصول فرقة الإسعاف (997) وتسليم المصاب. ما المعلومات الحيوية التي تبلغهم بها؟',
              'sitEn': 'Saudi Red Crescent paramedics 997 arrive. Critical info to convey to medical crew?',
              'hintAr': 'إبلاغهم بسبب الإصابة، وقت تركيب العاصبة بالدقيقة، ومقدار فقدان الدم الفعلي',
              'hintEn': 'Report cause of injury, exact tourniquet placement timestamp, estimated blood loss',
              'safeTextAr': 'إبلاغ المسعفين بسبب القطع، التوقيت الدقيق لتركيب العاصبة، والتغيرات بالوعي',
              'safeTextEn': 'Inform paramedics of mechanism of injury, exact tourniquet timestamp, and victim consciousness level',
              'safeExpAr': 'إتمام كامل؛ إبلاغ توقيت العاصبة يوجه أطباء الجراحة بالتعامل الآمن مع الطرف.',
              'safeExpEn': 'Complete resolution; exact tourniquet timestamp guides trauma surgeons in saving limb.',
              'safeOutAr': 'أكملت محطات الإسعاف الأولية للنزيف بنجاح!',
              'safeOutEn': 'Successfully completed severe bleeding first aid scenario!',
              'unsafeTextAr': 'إخفاء تركيب العاصبة وعدم ذكر التوقيت للمسعفين',
              'unsafeTextEn': 'Hide fact that tourniquet was applied and omit time information',
              'unsafeExpAr': 'خطأ؛ إخفاء توقيت العاصبة يعرض الطرف لمخاطر الغرغرينا والبتر.',
              'unsafeExpEn': 'Error; withholding tourniquet application duration risks permanent ischemic tissue necrosis.',
              'unsafeOutAr': 'مخاطرة بغرغرينا الطرف.',
              'unsafeOutEn': 'Ischemia risk persisted.',
            },
          ],
        ),

        // Scenarios 3 to 9 for EMERGENCY KIT...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_3',
          categoryId: 'emergency_kit',
          titleAr: 'التعامل مع الاختناق وإنقاذ الغصّة (مناورة هيمليك)',
          titleEn: 'Choking First Aid & Heimlich Maneuver',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لإنقاذ بالغ أو طفل يتعرض للغصّة والاختناق.',
          descriptionEn: 'Interactive 5-station scenario for adult and child choking emergency rescue.',
          difficulty: 'متوسط',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'شخص أثناء تناول الطعام يمسك برقبته بكفتا يديه ولا يستطيع الكلام أو السعال. ما تشخيص الحالة؟',
              'sitEn': 'Person holding neck with both hands, unable to speak, cough, or breathe. Diagnosis?',
              'hintAr': 'علامة الاختناق الكلية العالمية (Universal Choking Sign) تتطلب التدخل الفوري',
              'hintEn': 'Universal sign of complete choking requiring immediate Heimlich maneuver',
              'safeTextAr': 'التعرف على علامة الاختناق الكلي البدء بالإسعاف فوراً والاتصال بالإسعاف (997)',
              'safeTextEn': 'Recognize universal choking sign, initiate emergency Heimlich aid, call 997',
              'safeExpAr': 'تشخيص حاسم؛ عدم القدرة على السعال يعني انسداد مجرى الهواء كلياً باللقمة.',
              'safeExpEn': 'Critical diagnosis; inability to speak or cough confirms complete airway obstruction.',
              'safeOutAr': 'شخّصت الغصّة الكلية للمحطة 2.',
              'safeOutEn': 'Diagnosed full choking for Station 2.',
              'unsafeTextAr': 'إعطاء الشخص المصاب بالغصّة الكلية كوب ماء ليشربه',
              'unsafeTextEn': 'Offer victim a glass of water to drink while choking completely',
              'unsafeExpAr': 'خطأ قاتل؛ سكب الماء مع انسداد مجرى الهواء يدفع الجسم الغريب لعمق الرئة.',
              'unsafeExpEn': 'Fatal error; pouring water into fully blocked airway forces obstruction deeper into lungs.',
              'unsafeOutAr': 'انسدت الرئة بالمياه.',
              'unsafeOutEn': 'Water trapped behind obstruction.',
            },
            {
              'sitAr': 'تطبيق ضغطات الظهر (Back Blows) للمصاب البالغ. كيف توجه الضربات؟',
              'sitEn': 'Delivering back blows to conscious choking adult. Correct technique?',
              'hintAr': 'إمالة المصاب للأمام وسكب 5 ضربات بكعب اليد بين لوحي الكتف',
              'hintEn': 'Lean victim forward and give 5 firm blows with heel of hand between shoulder blades',
              'safeTextAr': 'إمالة المصاب للأمام وتوجيه 5 ضربات بكعب اليد بين لوحي الكتف بقوة',
              'safeTextEn': 'Lean victim forward and deliver 5 sharp back blows between shoulder blades using heel of hand',
              'safeExpAr': 'تقنية سليمة؛ إمالة الجسد والضربات تساعد الجاذبية والهواء على طرد الجسم الغريب.',
              'safeExpEn': 'Correct technique; forward angle combined with back shocks leverages gravity to dislodge object.',
              'safeOutAr': 'وجهت ضربات الظهر للمحطة 3.',
              'safeOutEn': 'Delivered 5 back blows for Station 3.',
              'unsafeTextAr': 'ضرب المصاب على ظهره وهو واقف بقامة منتصبة تماماً',
              'unsafeTextEn': 'Slap victim\'s upper back while standing completely upright',
              'unsafeExpAr': 'خطأ؛ الضرب القائم قد يسقط الجسم الغريب لأسفل القصيبات الهوائية.',
              'unsafeExpEn': 'Error; upright back slaps can settle foreign body deeper into lower trachea.',
              'unsafeOutAr': 'استقر جسم بالقصيبات.',
              'unsafeOutEn': 'Object slid lower in trachea.',
            },
            {
              'sitAr': 'لم يخرج الجسم الغريب بعد ضربات الظهر. كيف تطبق مناورة هيمليك (Abdominal Thrusts)؟',
              'sitEn': 'Object not dislodged. How to execute Abdominal Thrusts (Heimlich Maneuver)?',
              'hintAr': 'الوقوف خلف المصاب، وضع قبضة يدك فوق السرة، والضغط للداخل والأعلى 5 مرات',
              'hintEn': 'Stand behind, place fist above navel, perform 5 quick inward & upward thrusts',
              'safeTextAr': 'الوقوف خلف المصاب، وضع قبضة اليد فوق السرة وتحت القفص، والضغط للداخل وللأعلى',
              'safeTextEn': 'Stand behind victim, place fist thumb-side in above navel, apply 5 inward and upward thrusts',
              'safeExpAr': 'تطبيق احترافي؛ الضغط للأعلى ينشط الحجاب الحاجز لدفع هواء الرئة لطرد اللقمة.',
              'safeExpEn': 'Pro execution; inward/upward thrust forces diaphragm to expel trapped lung air pushing object out.',
              'safeOutAr': 'طبقت الضغطات البطنية للمحطة 4.',
              'safeOutEn': 'Applied abdominal thrusts for Station 4.',
              'unsafeTextAr': 'الضغط المباشر الشديد فوق عظمة الصدر أو الأضلاع السفلى',
              'unsafeTextEn': 'Press forcefully directly over sternum or lower rib cage bones',
              'unsafeExpAr': 'خطأ؛ الضغط على الأضلاع قد يكسر القفص الصدري دون ضغط الحجاب الحاجز.',
              'unsafeExpEn': 'Error; pressing directly on lower ribs risks fracturing bone without displacing diaphragm.',
              'unsafeOutAr': 'انكسرت الأضلاع.',
              'unsafeOutEn': 'Rib fracture risk.',
            },
            {
              'sitAr': 'فقد المصاب الوعي وسقط أرضاً أثناء إجراء المناورة. ما الإجراء الفوري الجديد؟',
              'sitEn': 'Choking victim loses consciousness and collapses. New immediate action?',
              'hintAr': 'تمديد المصاب على ظهره، البدء بالإنعاش القلبي الرئوي (CPR)، وتفقد الفم قبل إعطاء الأنفاس',
              'hintEn': 'Lay victim flat on back, begin CPR chest compressions, check mouth before rescue breaths',
              'safeTextAr': 'تمديد المصاب على ظهره، البدء بالضغطات الصدرية (CPR 30 ضغطة)، وتفقد الفم لرؤية جسم الغصّة',
              'safeTextEn': 'Lower victim onto back, initiate CPR (30 chest compressions), and inspect mouth for dislodged object',
              'safeExpAr': 'تحول إسعافي سليم؛ الضغطات الصدرية بالإنعاش تضغط الهواء أيضاً وتدعم الدورة الدموية.',
              'safeExpEn': 'Correct shift; chest compressions generate airway pressure while keeping blood oxygenated.',
              'safeOutAr': 'بدأت الإنعاش القلبي للمحطة 5.',
              'safeOutEn': 'Initiated CPR protocol for Station 5.',
              'unsafeTextAr': 'مواصلة سحب بطن المصاب وهو مستلقي فاقد الوعي',
              'unsafeTextEn': 'Keep pulling victim\'s abdomen while lying unconscious on floor',
              'unsafeExpAr': 'خطأ؛ المناورة البطنية لا تطبق على المصاب الفاقد للوعي على الأرض.',
              'unsafeExpEn': 'Error; abdominal thrusts are invalid on unconscious supine victims; CPR is required.',
              'unsafeOutAr': 'توقف الإنعاش الصدري.',
              'unsafeOutEn': 'CPR chest compressions delayed.',
            },
            {
              'sitAr': 'خروج اللقمة واستعادة التنفس والوعي بعد الإنعاش. ما التوجيه الطبي اللازم؟',
              'sitEn': 'Object expelled, victim regains breathing and consciousness. Mandatory medical step?',
              'hintAr': 'نقل المصاب للمستشفى لفحص الأعضاء الباطنية والقصبة الهوائية بواسطة الطبيب',
              'hintEn': 'Transport victim to hospital ER for medical evaluation of internal organs & trachea',
              'safeTextAr': 'نقل المصاب للمستشفى عبر الإسعاف (997) للتقييم الطبي والتأكد من سلامة الأحشاء الصدرية',
              'safeTextEn': 'Transport victim to ER via 997 ambulance for medical check of internal abdominal organs',
              'safeExpAr': 'إتمام كامل؛ الفحص الطبي يضمن عدم وجود تمزق بالحجاب الحاجز أو المريء بعد الضغطات.',
              'safeExpEn': 'Complete resolution; ER evaluation ensures no internal diaphragm or esophageal tears from thrusts.',
              'safeOutAr': 'أكملت محطات إسعاف الاختناق بنجاح!',
              'safeOutEn': 'Successfully completed choking first aid scenario!',
              'unsafeTextAr': 'سماح للمصاب بالمغادرة فوراً ومواصلة تناوله الطعام',
              'unsafeTextEn': 'Allow victim to walk away immediately and resume eating heavy steak',
              'unsafeExpAr': 'خطأ؛ قد توجد تورمات بالقصبة الهوائية تسبب انسداداً ثانوياً.',
              'unsafeExpEn': 'Error; airway trauma or tissue swelling can cause secondary airway compromise.',
              'unsafeOutAr': 'تورم القصبة الهوائية.',
              'unsafeOutEn': 'Airway swelling risk persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_4',
          categoryId: 'emergency_kit',
          titleAr: 'إسعاف الحروق المنزلية والدرجة الثانية',
          titleEn: 'First Aid for Household & 2nd Degree Burns',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع حروق الماء المغلي والحرارة بأسلوب علمي.',
          descriptionEn: 'Interactive 5-station scenario for thermal & scalding water burn first aid.',
          difficulty: 'سهل',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'انسكاب ماء مغلي على ذراع شخص وظهور احمرار وانتفاخ فقاقيع مائية (Blisters). ما أول خطوة؟',
              'sitEn': 'Scalding boiling water spilled on arm showing red skin and water blisters. First action?',
              'hintAr': 'تبريد الحرق بالماء الجاري الفاتر (وليس الثلج) لمدة 10 إلى 20 دقيقة فوراً',
              'hintEn': 'Cool burn area under cool running tap water (NOT ice) for 10 to 20 minutes',
              'safeTextAr': 'تبريد مكان الحرق فوراً تحت ماء صنبور جاري فاتر لمدة 15 دقيقة متواصلة',
              'safeTextEn': 'Cool affected area immediately under cool running tap water continuously for 15 minutes',
              'safeExpAr': 'خطوة ذهبية؛ التبريد المائي يوقف تعمق الحرارة بالأنسجة الحية ويخفف الألم.',
              'safeExpEn': 'Golden action; cool running water stops thermal energy from penetrating deeper dermal layers.',
              'safeOutAr': 'برّدت الحرق بالماء الجاري للمحطة 2.',
              'safeOutEn': 'Cooled burn under running water for Station 2.',
              'unsafeTextAr': 'ضع مكعبات ثلج مباشرة فوق الجلد المشتعل بالحرق',
              'unsafeTextEn': 'Apply ice cubes directly onto burned blistered skin',
              'unsafeExpAr': 'خطأ خطير؛ الثلج يسبب انقباض الأوعية وحرقة صدمة صقيع تدمّر الأنسجة.',
              'unsafeExpEn': 'Dangerous error; direct ice causes tissue frostbite damage atop the thermal burn.',
              'unsafeOutAr': 'تلف الأنسجة الصقيعي.',
              'unsafeOutEn': 'Frostbite tissue burn combo.',
            },
            {
              'sitAr': 'هل تقوم بثقب الفقاقيع المائية (Blisters) الممتلئة بالسائل فوق الحرق؟',
              'sitEn': 'Water-filled burn blisters forming on arm. Should you pop or puncture them?',
              'hintAr': 'حظر ثقب أو وكس الفقاقيع المائية لأنها غطاء طبيعي يمنع التلوث والبكتيريا',
              'hintEn': 'NEVER pop or puncture blisters; intact skin acts as a natural sterile protective barrier',
              'safeTextAr': 'ترك الفقاقيع المائية سليمة دون ثقبها وتغطيتها برفق لمنع التلوث البكتيري',
              'safeTextEn': 'Keep burn blisters intact without puncturing, covering gently to prevent bacterial entry',
              'safeExpAr': 'حكمة معملية؛ سائل الفقاقيع المعقم يسرع التئام الجلد وحمايته من التقيح.',
              'safeExpEn': 'Clinical rule; blister fluid is sterile protecting exposed dermis from severe infection.',
              'safeOutAr': 'حافظت على الفقاقيع للمحطة 3.',
              'safeOutEn': 'Preserved intact blisters for Station 3.',
              'unsafeTextAr': 'استخدام إبرة لثقب الفقاقيع وتفريغ السائل على الجلد',
              'unsafeTextEn': 'Use a sewing needle to pop blisters and squeeze out fluid',
              'unsafeExpAr': 'خطأ؛ ثقب الفقاقيع يزيل حماية الجلد ويفتح باب التهابات البكتيريا.',
              'unsafeExpEn': 'Error; popping blisters removes biological shield inviting severe bacterial infection.',
              'unsafeOutAr': 'التهاب الجرح وتلوثه.',
              'unsafeOutEn': 'Bacterial infection of burn.',
            },
            {
              'sitAr': 'نزع الملابس أو الخواتم الملتصقة بقرب مكان الحرق. كيف تتعامل معها؟',
              'sitEn': 'Clothing or rings near burned area. How to manage garments and jewelry?',
              'hintAr': 'نزع الخواتم والساعة فوراً قبل الانتفاخ، وقص الملابس حول الحرق دون شد الملتصق',
              'hintEn': 'Remove rings/watches immediately before swelling; cut clothes around burn without pulling stuck fabric',
              'safeTextAr': 'خلع الخواتم والساعات فوراً وقص الملابس المحيطة دون نزع الجزء الملتصق بالحرق',
              'safeTextEn': 'Remove rings/watches immediately and gently trim away loose clothing without pulling melted fabric',
              'safeExpAr': 'تصرف ذكي؛ تورم الجلد السريع يجعل الخواتم قطعاً خانقاً لأوردة الإصبع.',
              'safeExpEn': 'Smart action; rapid tissue swelling converts tight rings into ischemic tourniquets.',
              'safeOutAr': 'نزعت الخواتم والمجوهرات للمحطة 4.',
              'safeOutEn': 'Removed rings & jewelry for Station 4.',
              'unsafeTextAr': 'شد وجذب الملابس الملتصقة بقوة بعيداً عن الجلد المحترق',
              'unsafeTextEn': 'Forcefully yank stuck fabric off melted burned skin surface',
              'unsafeExpAr': 'خطأ؛ جذب القماش الملتصق ينسلخ معه طبقات الجلد الحي.',
              'unsafeExpEn': 'Error; yanking stuck fabric tears off live skin layers creating deep open wounds.',
              'unsafeOutAr': 'انسلاخ الجلد الحي.',
              'unsafeOutEn': 'Live skin layer avulsion.',
            },
            {
              'sitAr': 'وضع المواد على الحرق. ما المادة الطبية الصحيحة المقبولة للإسعاف؟',
              'sitEn': 'Applying topical substances on burn. Correct medical first aid substance?',
              'hintAr': 'وضع مرهم الحروق المعقم (مثل الميبو Bepanthen/MEBO) وتغطيتها بضمادة فازلين غير لاصقة',
              'hintEn': 'Apply medical burn ointment (MEBO) and cover with sterile non-adherent petrolatum dressing',
              'safeTextAr': 'وضع مرهم حروق معقم وتغطية المكان بضمادة معقمة غير لاصقة (Non-adherent Dressing)',
              'safeTextEn': 'Apply sterile burn ointment (MEBO) and wrap loosely with non-adherent sterile gauze',
              'safeExpAr': 'علاج سليم؛ ضمادات الفازلين تمنع التفرزات من الالتصاق والتمزق عند التغيير.',
              'safeExpEn': 'Proper care; non-stick dressings prevent newly forming tissue from sticking to bandage.',
              'safeOutAr': 'ضمدت الحرق بضمادة معقمة للمحطة 5.',
              'safeOutEn': 'Dressed burn with sterile gauze for Station 5.',
              'unsafeTextAr': 'وضع معجون الأسنان، معجون الطماطم، أو الزبدة فوق الحرق',
              'unsafeTextEn': 'Smear toothpaste, tomato paste, or butter directly onto open burn',
              'unsafeExpAr': 'خطأ شائع ومضر؛ معجون الأسنان يحبس الحرارة ويحتوي مواد كيميائية مخرشة.',
              'unsafeExpEn': 'Common harmful myth; toothpaste traps heat and introduces harsh irritating chemicals.',
              'unsafeOutAr': 'تخرّش وتلوث كيميائي.',
              'unsafeOutEn': 'Chemical irritation & infection.',
            },
            {
              'sitAr': 'تقييم مساحة الحرق وحاجة المستشفى. متى يتوجب الذهاب لطوارئ الإسعاف (997)؟',
              'sitEn': 'Evaluating burn surface area and hospital need. When to seek immediate ER (997)?',
              'hintAr': 'إذا كان الحرق بالوجه، اليدين، الأماكن الحساسة، أو تجاوز مساحة كف اليد',
              'hintEn': 'If burn covers face, hands, major joints, genitals, or exceeds size of victim\'s palm',
              'safeTextAr': 'التوجه للمستشفى فوراً إذا كان الحرق يشمل الوجه، اليدين، المفصل، أو تجاوز حجم كف اليد',
              'safeTextEn': 'Seek immediate ER care if burn involves face, hands, joints, genitals, or exceeds palm size',
              'safeExpAr': 'إتمام كامل؛ حروق المناطق الحساسة تتطلب رعاية تخصصية لضمان عدم حدوث تشوهات وتصلب.',
              'safeExpEn': 'Complete resolution; critical area burns require specialized burn unit care preventing joint contractures.',
              'safeOutAr': 'أكملت محطات إسعاف الحروق بنجاح!',
              'safeOutEn': 'Successfully completed burn first aid scenario!',
              'unsafeTextAr': 'إهمال حرق الوجه واليدين الكبار والاعتماد على العلاج المنزلي فقط',
              'unsafeTextEn': 'Ignore extensive facial/hand burns treating purely with home remedies',
              'unsafeExpAr': 'خطأ؛ حروق اليدين والوجه قد تسبب ندبات انكماشية تعيق الحركة.',
              'unsafeExpEn': 'Error; facial and hand burns carry high risks of severe scarring and functional contracture.',
              'unsafeOutAr': 'مخاطرة بتشوه الندبات.',
              'unsafeOutEn': 'Contracture scarring risk.',
            },
          ],
        ),

        // Scenarios 5 to 9 for EMERGENCY KIT...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_5',
          categoryId: 'emergency_kit',
          titleAr: 'إسعاف الكسور والتثبيت الميداني',
          titleEn: 'Bone Fracture First Aid & Splinting',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتثبيت الكسر وتجنب نقل المصاب الخاطئ.',
          descriptionEn: 'Interactive 5-station scenario for immobilizing fractures & safe splinting.',
          difficulty: 'متوسط',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'سقوط شخص من ارتفاع مع ألم شديد وتشوه بشكل الساق وعدم القدرة على المشي. ما التشخيص الأول؟',
              'sitEn': 'Person fell from height showing severe pain, leg deformity, and inability to bear weight. Diagnosis?',
              'hintAr': 'الاشتباه بكسر مغلق بالساق والتزام تثبيت المصاب في مكانه دون تحريك',
              'hintEn': 'Suspect closed leg bone fracture; keep patient stationary without moving limb',
              'safeTextAr': 'الاشتباه بكسر بالسمحاق العظمي، منع المصاب من السير، وطلب الإسعاف (997) فوراً',
              'safeTextEn': 'Suspect bone fracture, strictly stop victim from walking, and call 997 ambulance immediately',
              'safeExpAr': 'استجابة سليم؛ منع الحركة يمنع تحول الكسر المغلق إلى كسر مفتوح متمزق.',
              'safeExpEn': 'Correct initial step; preventing movement stops closed fracture from becoming open compound fracture.',
              'safeOutAr': 'ثبّت المصاب وطلبت الإسعاف للمحطة 2.',
              'safeOutEn': 'Immobilized patient & called 997 for Station 2.',
              'unsafeTextAr': 'طلب من المصاب الوقوف والمشي لمعرفة هل الساق مكسورة أم لا',
              'unsafeTextEn': 'Ask victim to stand up and try walking to test if bone is broken',
              'unsafeExpAr': 'خطأ قاتل؛ محاولة المشي على العظم المكسور تقطع الأوردة والأعصاب المجاورة.',
              'unsafeExpEn': 'Fatal error; bearing weight on fractured bone severs surrounding vessels and nerves.',
              'unsafeOutAr': 'مخاطرة بتمزيق الأنسجة.',
              'unsafeOutEn': 'Tissue & vessel laceration.',
            },
            {
              'sitAr': 'هل تحاول تعديل شكل العظم الملتوي أو رد الكسر إلى مكانه بيدك؟',
              'sitEn': 'Limb bone is visibly bent at unnatural angle. Should you attempt to realign/reset it?',
              'hintAr': 'حظر محاولة رد أو تعديل العظام المكسورة ميدانياً، وتثبيتها على وضعيتها فقط',
              'hintEn': 'STRICTLY never attempt to reduce/realign fractured bones; immobilize in position found',
              'safeTextAr': 'تثبيت الساق المكسورة على الوضعية التي وجدت عليها دون محاولة تعديل استقامتها',
              'safeTextEn': 'Immobilize leg in exact position found without attempting manual realignment',
              'safeExpAr': 'قاعدة طبية حاسمة؛ تعديل العظام يدوياً يسبب صدمة ألم حادة وتمزق شرياني.',
              'safeExpEn': 'Critical medical rule; manual bone reduction causes severe neurogenic shock and arterial cuts.',
              'safeOutAr': 'حافظت على وضعية الكسر للمحطة 3.',
              'safeOutEn': 'Maintained fracture posture for Station 3.',
              'unsafeTextAr': 'سحب القدم بقوة وتدوير الساق لتعديل شكلها الملتوي',
              'unsafeTextEn': 'Pull foot forcefully twisting leg back into straight line',
              'unsafeExpAr': 'خطأ؛ الجذب اليدوي يمزق العضلات وقد يقطع الشريان الفخذي/الظنبوبي.',
              'unsafeExpEn': 'Error; forceful yanking severs major tibial/femoral arteries causing internal bleeding.',
              'unsafeOutAr': 'تمزق الشريان.',
              'unsafeOutEn': 'Arterial laceration hazard.',
            },
            {
              'sitAr': 'تثبيت الكسر باستخدام جبيرة ميدانية (Splint). ما الشروط الصحيحة لتطبيق الجبيرة؟',
              'sitEn': 'Applying field splint to immobilize fracture. Correct splinting protocol?',
              'hintAr': 'تثبيت المفصلين (أعلى وأسفل الكسر) باستخدام لوح خشبي أو وسادة وربطها برفق',
              'hintEn': 'Immobilize joints ABOVE and BELOW fracture site using rigid board cushioned with cloth',
              'safeTextAr': 'استخدام لوحين عازلين وتثبيت المفصل الذي أعلى الكسر والمفصل الذي أسفله بحزم',
              'safeTextEn': 'Apply rigid splint boards immobilizing joints both ABOVE and BELOW the fracture site',
              'safeExpAr': 'تثبيت ممتاز؛ قفل المفصلين المحيطين يلغي أي حركة دورانية للقطعة المكسورة.',
              'safeExpEn': 'Great stabilization; locking adjacent joints eliminates rotational forces at fracture line.',
              'safeOutAr': 'طبقت الجبيرة المعيارية للمحطة 4.',
              'safeOutEn': 'Applied standard splint for Station 4.',
              'unsafeTextAr': 'ربط الجبيرة على منطقة الكسر فقط دون تثبيت المفاصل المجاورة',
              'unsafeTextEn': 'Bind splint solely over exact fracture point ignoring adjacent joints',
              'unsafeExpAr': 'خطأ؛ حركة المفاصل المجاورة تنقل الاهتزاز للكسر وتلغي فائدة الجبيرة.',
              'unsafeExpEn': 'Error; adjacent joint motion transfers severe movement to fracture line.',
              'unsafeOutAr': 'اهتزت قطعة الكسر.',
              'unsafeOutEn': 'Fracture site unstable.',
            },
            {
              'sitAr': 'التحقق من الدورة الدموية والأعصاب (PMS Check) بعد ربط الجبيرة. كيف تفحص القدم؟',
              'sitEn': 'Checking Circulation, Sensation, Movement (PMS check) post-splinting. How to inspect?',
              'hintAr': 'فحص نبض القدم، لون أصابع القدم، والقدرة على الحس والتحريك',
              'hintEn': 'Check pedal pulse, skin color/warmth of toes, and sensation/movement',
              'safeTextAr': 'ضغط أظافر أصابع القدم لرؤية عودة اللون الوردي، والتأكد من شعور المصاب باللمس',
              'safeTextEn': 'Pinch toe nails checking capillary refill (< 2 sec) and verify sensation/warmth in toes',
              'safeExpAr': 'فحص احترافي؛ التأكد من التروية يضمن عدم انقباض الدم بسبب شد رباط الجبيرة.',
              'safeExpEn': 'Pro check; capillary refill ensures splint bandages are not too tight cutting off circulation.',
              'safeOutAr': 'فحصت التروية الإشعاعية للمحطة 5.',
              'safeOutEn': 'Verified blood circulation for Station 5.',
              'unsafeTextAr': 'شد أربطة الجبيرة بأقصى قوة دون فحص لون الأصابع',
              'unsafeTextEn': 'Crank splint straps with maximum force without checking toe color',
              'unsafeExpAr': 'خطأ؛ الربط الشديد يقطع تيار الدم وينتج متلازمة الانقسام (Compartment Syndrome).',
              'unsafeExpEn': 'Error; overtightening blocks arterial supply risking irreversible compartment syndrome.',
              'unsafeOutAr': 'انقطع تيار الدم عن القدم.',
              'unsafeOutEn': 'Ischemic foot circulation.',
            },
            {
              'sitAr': 'انتظار سيارة الإسعاف 997. ما التوجيه النهائي للتعامل مع ألم الكسر؟',
              'sitEn': 'Awaiting 997 ambulance arrival. Final care guidance for fracture pain?',
              'hintAr': 'وضع كيس ثلج مغلف بقماش على منطقة الكسر وتغطية المصاب ببطانية لمنع الصدمة',
              'hintEn': 'Apply cloth-wrapped ice pack to fracture area and cover patient with blanket for shock',
              'safeTextAr': 'وضع كيس ثلج مغلف بقماش فوق الجبيرة لتخفيف الورم وتغطية المصاب ببطانية تدفئة',
              'safeTextEn': 'Apply wrapped ice pack over splint to reduce swelling and cover patient with thermal blanket',
              'safeExpAr': 'إتمام كامل؛ الثلج المغلف يقلل التورم والتدفئة تقي من صدمة الألم العصبي.',
              'safeExpEn': 'Complete resolution; cold pack minimizes internal swelling while thermal blanket combats neurogenic shock.',
              'safeOutAr': 'أكملت محطات إسعاف الكسور بنجاح!',
              'safeOutEn': 'Successfully completed bone fracture first aid scenario!',
              'unsafeTextAr': 'تدليك منطقة الكسر الملتوية بالزيوت الحارة بقوة',
              'unsafeTextEn': 'Vigorously rub hot oils directly onto swollen fractured limb',
              'unsafeExpAr': 'خطأ؛ التدليك يفاقم التورم ويزيد النزيف الداخلي حول العظم.',
              'unsafeExpEn': 'Error; vigorous massage amplifies internal hematoma and tissue bleeding.',
              'unsafeOutAr': 'تدافق النزيف الداخلي.',
              'unsafeOutEn': 'Internal hematoma worsened.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_6',
          categoryId: 'emergency_kit',
          titleAr: 'إسعاف حالات السكتة الدماغية (اختبار FAST)',
          titleEn: 'Stroke Emergency Recognition & FAST Protocol',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعرف الفوري على أعراض السكتة الدماغية وإنقاذ الحياة.',
          descriptionEn: 'Interactive 5-station scenario for recognizing stroke symptoms using FAST test.',
          difficulty: 'متوسط',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'شخص كبير بالسن يشعر فجأة بثقل في الوجنة وثعثعة باللسان. ما أول اختبار مسحي (FAST)؟',
              'sitEn': 'Elderly person suddenly experiences facial drooping and slurred speech. First FAST test step?',
              'hintAr': 'طلب من الشخص الابتسام لرؤية ميلان شق الوجه (F - Face Droop)',
              'hintEn': 'Ask person to smile; check if one side of face droops (F - Face)',
              'safeTextAr': 'طلب من الشخص الابتسام أو إبراز الأسنان وملاحظة انحراف شفة شق الوجه',
              'safeTextEn': 'Ask person to smile or show teeth; observe if one side of face droops unbalance',
              'safeExpAr': 'فحص مبكر؛ ارتخاء شق الوجه يشير لتأثر العصب الوجهي بسبب انسداد شريان الدماغ.',
              'safeExpEn': 'Early sign; facial droop indicates facial nerve ischemia from cerebral artery occlusion.',
              'safeOutAr': 'لاحظت ارتخاء الوجه للمحطة 2.',
              'safeOutEn': 'Noted facial drooping for Station 2.',
              'unsafeTextAr': 'إعطاء الشخص كوب قهوة ساخنة لتهدئة الأعصاب',
              'unsafeTextEn': 'Offer person a hot coffee cup to calm down nervous stress',
              'unsafeExpAr': 'خطأ؛ ضعف البلع أثناء السكتة يسبب دخول القهوة للقصبة الهوائية والاختناق.',
              'unsafeExpEn': 'Error; impaired swallowing during stroke causes fluid aspiration into lungs.',
              'unsafeOutAr': 'مخاطرة بشرق القهوة.',
              'unsafeOutEn': 'Aspiration choking risk.',
            },
            {
              'sitAr': 'فحص قوة الذراعين (A - Arm Weakness). كيف تطلب من المصاب رفع يديه؟',
              'sitEn': 'Testing arm strength (A - Arm Weakness). How to instruct victim?',
              'hintAr': 'طلب رفع كلتا الذراعين للأمام لمدة 10 ثوانٍ ورؤية انخفاض إحدى الذراعين تلقائياً',
              'hintEn': 'Ask person to raise both arms forward for 10 seconds; check if one arm drifts down',
              'safeTextAr': 'طلب رفع الذراعين معاً للأمام بعيون مغلقة وملاحظة هبوط إحداهما عاجزة',
              'safeTextEn': 'Ask victim to extend both arms forward with eyes closed, checking if one arm drifts downward',
              'safeExpAr': 'اختبار دقيق؛ هبوط الذراع يؤكد ضعف الإشارة العصبية المحركة بالحبل الشوكي.',
              'safeExpEn': 'Accurate test; arm drift confirms unilateral motor cortex ischemia.',
              'safeOutAr': 'رصدت هبوط الذراع للمحطة 3.',
              'safeOutEn': 'Observed arm drift for Station 3.',
              'unsafeTextAr': 'طلب من الشخص القيام بتمارين ضغط ومشي سريع',
              'unsafeTextEn': 'Ask victim to do push-ups or brisk walking to test vigor',
              'unsafeExpAr': 'خطأ؛ المجهود البدني يرفع الضغط الشرياني ويزيد نزيف الدماغ.',
              'unsafeExpEn': 'Error; physical exertion spikes blood pressure escalating brain ischemia or hemorrhage.',
              'unsafeOutAr': 'ارتفع ضغط الدم.',
              'unsafeOutEn': 'Spiked arterial blood pressure.',
            },
            {
              'sitAr': 'فحص الكلام والنطق (S - Speech Difficulty). كيف تختبر نطق العبارات؟',
              'sitEn': 'Testing speech clarity (S - Speech Difficulty). How to test phrasing?',
              'hintAr': 'طلب تكرار جملة بسيطة ورؤية ثقل اللسان وتلعثم الكلمات',
              'hintEn': 'Ask person to repeat a simple sentence; listen for slurred or jumbled words',
              'safeTextAr': 'طلب تكرار جملة بسيطة مثل: "الطقس مشمس اليوم" والاستماع لتعثر وتلعثم الحروف',
              'safeTextEn': 'Ask victim to repeat a simple phrase like "The sky is blue" listening for slurred pronunciation',
              'safeExpAr': 'تثبيت التشخيص؛ ثقل الكلام يعني تأثر مركز الكلام (Broca\'s Area) في الدماغ.',
              'safeExpEn': 'Diagnosis confirmed; speech slurring indicates Broca\'s area language center ischemia.',
              'safeOutAr': 'ثبت تعثر النطق للمحطة 4.',
              'safeOutEn': 'Confirmed speech slurring for Station 4.',
              'unsafeTextAr': 'تجاهل اللعثمة واعتبارها مجرد إرهاق طبيعي وسيتحسن بالنوم',
              'unsafeTextEn': 'Ignore slurred speech assuming it is simple tiredness that sleep will cure',
              'unsafeExpAr': 'خطأ قاتل؛ التأخر في علاج السكتة يسبب تلفاً دائمياً بالمخ.',
              'unsafeExpEn': 'Fatal error; delaying stroke care causes irreversible brain tissue infarction.',
              'unsafeOutAr': 'تأخر الوقت الذهبي.',
              'unsafeOutEn': 'Golden window time lost.',
            },
            {
              'sitAr': 'تحديد عنصر الوقت (T - Time to Call 997). ما الإجراء الطارئ الحاس في هذه اللحظة؟',
              'sitEn': 'Critical Time factor (T - Time to Call 997). Crucial action right now?',
              'hintAr': 'الاتصال بالإسعاف (997) فوراً وتدوين الوقت الدقيق لظهور أول أعراض',
              'hintEn': 'Call 997 ambulance immediately and record exact timestamp when symptoms first began',
              'safeTextAr': 'الاتصال بـ 997 فوراً وتدوين الوقت بالساعة والدقيقة لظهور الاعراض لنقلها لطبيب الطوارئ',
              'safeTextEn': 'Call 997 immediately and log exact time of onset to report to stroke neurologist',
              'safeExpAr': 'النافذة الذهبية؛ إعطاء مذيبات التجلط (tPA) يتطلب الوصول للمستشفى خلال 3 إلى 4.5 ساعات.',
              'safeExpEn': 'Golden window; tPA clot-dissolving therapy requires hospital arrival within 3 to 4.5 hours.',
              'safeOutAr': 'دعوت 997 ودوّنت الوقت للمحطة 5.',
              'safeOutEn': 'Called 997 and logged time for Station 5.',
              'unsafeTextAr': 'إعطاء المصاب حبة أسبرين دون معرفة هل السكتة نزلية أم انسدادية',
              'unsafeTextEn': 'Administer an aspirin tablet without knowing if stroke is ischemic or hemorrhagic',
              'unsafeExpAr': 'خطأ مهلك؛ إذا كانت السكتة نزفية فأن الأسبرين يسبب النزيف القاتل بالدماغ.',
              'unsafeExpEn': 'Fatal mistake; giving aspirin during hemorrhagic stroke worsens fatal brain bleeding.',
              'unsafeOutAr': 'مخاطرة بالنزيف الدماغي.',
              'unsafeOutEn': 'Intracranial hemorrhage risk.',
            },
            {
              'sitAr': 'وضع المصاب أثناء انتظار فرقة الهلال الأحمر (997). ما الوضعية الجسدية الآمنة؟',
              'sitEn': 'Positioning victim while waiting for Red Crescent paramedics. Safe posture?',
              'hintAr': 'تمديد المصاب مع رفع الرأس 30 درجة وإمالته جانباً عند التقيؤ',
              'hintEn': 'Lay victim down with head elevated 30 degrees; roll on side if vomiting',
              'safeTextAr': 'إسناد رقبته ورفع الرأس 30 درجة، وإمالة الجسد جانباً (وضعية الإفاقة) عند الغثيان',
              'safeTextEn': 'Lay victim comfortable with head elevated 30°, turning on side (recovery position) if vomiting occurs',
              'safeExpAr': 'إتمام كامل؛ رفع الرأس يخفف الضغط الدماغي ووضعية الجانب تمنع انسداد مجرى الهواء.',
              'safeExpEn': 'Complete resolution; 30° head elevation lowers intracranial pressure while side roll protects airway.',
              'safeOutAr': 'أكملت محطات إسعاف السكتة الدماغية بنجاح!',
              'safeOutEn': 'Successfully completed stroke FAST recognition scenario!',
              'unsafeTextAr': 'ترك المصاب مستلقياً مسطحاً على ظهره تماماً دون مراقبة مجرى التنفس',
              'unsafeTextEn': 'Lay victim flat on back completely horizontal without monitoring airway',
              'unsafeExpAr': 'خطأ؛ الاستلقاء المسطح يزيد الضغط الدماغي ويرفع خطر الاختناق.',
              'unsafeExpEn': 'Error; flat position elevates intracranial pressure and risks airway aspiration.',
              'unsafeOutAr': 'ارتفع الضغط الدماغي.',
              'unsafeOutEn': 'Elevated intracranial pressure risk.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_7',
          categoryId: 'emergency_kit',
          titleAr: 'إسعاف التسمم بالمنظفات والمواد الكيميائية',
          titleEn: 'First Aid for Household Chemical & Detergent Ingestion',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع شرب الفلاش، الكلور، والمنظفات بالمنزل.',
          descriptionEn: 'Interactive 5-station scenario for household bleach & acid poisoning first aid.',
          difficulty: 'صعب',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'طفل شرب كمية من منظف السيراميك الحامضي (الفلاش) أو الكلور بالخطأ. ما التصرف الفوري الأول؟',
              'sitEn': 'Child accidentally swallows acidic drain cleaner or household bleach. Immediate first step?',
              'hintAr': 'الاتصال بطوارئ الصحة (937) والإسعاف (997) وحظر إجبار الطفل على التقيؤ',
              'hintEn': 'Call MOH Poison Control 937 / ER 997 immediately; STRICTLY never induce vomiting',
              'safeTextAr': 'الاتصال بمركز سموم وزارة الصحة (937) وحظر إحداث تقيؤ للطفل نهائياً',
              'safeTextEn': 'Call MOH Poison Control center (937) & 997 instantly; STRICTLY forbid inducing vomiting',
              'safeExpAr': 'استجابة حاسمة؛ التقيؤ يمرر المادة الكاوية مرتين في المريء مما يمزق الأنسجة.',
              'safeExpEn': 'Critical action; inducing vomiting forces corrosive chemical back up burning esophagus twice.',
              'safeOutAr': 'اتصلت بمركز السموم للمحطة 2.',
              'safeOutEn': 'Called Poison Control 937 for Station 2.',
              'unsafeTextAr': 'إدخال الأصبع في حلق الطفل لإجباره على التقيؤ فوراً',
              'unsafeTextEn': 'Stick fingers down child\'s throat to force immediate vomiting',
              'unsafeExpAr': 'خطأ كوارثي؛ إعادة التقيؤ الحامضي تسبب ثقب المريء وانفجار القفص الصدري.',
              'unsafeExpEn': 'Catastrophic error; re-exposing esophagus to caustic acid causes chemical perforation.',
              'unsafeOutAr': 'انثقاب المريء.',
              'unsafeOutEn': 'Esophageal perforation hazard.',
            },
            {
              'sitAr': 'هل تعطي الطفل كربونات الصودا أو الخل لتحييد الحامض أو القلوي بالحروق الباطنية؟',
              'sitEn': 'Should you give vinegar or baking soda to "neutralize" acid/alkali chemical internally?',
              'hintAr': 'حظر إعطاء أي حمض أو قلوي مضاد لأن تفاعل التحييد يولد حرارة عالية جداً',
              'hintEn': 'NEVER give neutralizing agents; chemical reaction generates extreme exothermic heat inside',
              'safeTextAr': 'تجنب إعطاء أي أحماض أو قلويات مضادة والالتزام بتعليمات طبيب السموم بـ 937',
              'safeTextEn': 'Strictly avoid administering neutralizing liquids; follow exact MOH 937 medical instructions',
              'safeExpAr': 'تحذير طبي؛ تفاعل التحييد الكيميائي في المعدة يولد حرارة شديدة تشوي الأحشاء.',
              'safeExpEn': 'Medical warning; chemical neutralization inside stomach generates exothermic heat boiling tissues.',
              'safeOutAr': 'تجنبت المواد الكيميائية للمحطة 3.',
              'safeOutEn': 'Avoided chemical neutralizers for Station 3.',
              'unsafeTextAr': 'إسقاء الطفل الخل أو معادل حامضي مبني على التخمين',
              'unsafeTextEn': 'Force child to drink vinegar or home acid neutralizing concoction',
              'unsafeExpAr': 'خطأ؛ غازات وتفاعل الحرارة التحييدية يفجر قاع المعدة.',
              'unsafeExpEn': 'Error; exothermic reaction heat and gas pressure cause stomach rupture.',
              'unsafeOutAr': 'تفاعل حراري باطني.',
              'unsafeOutEn': 'Exothermic stomach burn.',
            },
            {
              'sitAr': 'تناثرت المادة الكيميائية الكاوية على فم الطفل وجلده وملابسه. كيف تطهر الجلد؟',
              'sitEn': 'Caustic chemical splashed onto child\'s mouth, skin, and shirt. How to decontaminate skin?',
              'hintAr': 'غسل الجلد والفم بالماء الفاتر الجاري بكميات وفيرة وقص الملابس الملوثة',
              'hintEn': 'Rinse mouth and skin with copious amounts of cool running water; remove contaminated clothes',
              'safeTextAr': 'غسل الشفتين والجلد بالماء الجاري لمدة 15 دقيقة ونزع الملابس الملوثة برفق',
              'safeTextEn': 'Flush skin and outer lips with cool running tap water for 15 minutes, cutting away soaked clothes',
              'safeExpAr': 'تطهير ممتاز؛ التخفيف بالماء الجاري يزيل المادة الكاوية ويوقف تآكل الجلد الخارجي.',
              'safeExpEn': 'Great decontamination; water flushing dilutes corrosive agents stopping cutaneous chemical burns.',
              'safeOutAr': 'طهرت الجلد بالماء للمحطة 4.',
              'safeOutEn': 'Decontaminated skin with water for Station 4.',
              'unsafeTextAr': 'فرك الجلد الملوث بالصابون والمناشف الجافة',
              'unsafeTextEn': 'Scrub chemical-soaked skin vigorously with bar soap and dry towel',
              'unsafeExpAr': 'خطأ؛ الفرك يدخل المادة الكاوية لمسام الجلد العميقة.',
              'unsafeExpEn': 'Error; dry rubbing drives chemical toxins deeper into damaged dermal layers.',
              'unsafeOutAr': 'عمق الحرق الكيميائي.',
              'unsafeOutEn': 'Chemical burn driven deeper.',
            },
            {
              'sitAr': 'الاحتفاظ بعبوة المادة الكيميائية المتسببة بالتسمم. ما أهمية ذلك؟',
              'sitEn': 'Retaining chemical product bottle/container. Why is this critical?',
              'hintAr': 'أخذ علبة المنظف الأصلية للمستشفى ليتعرف الأطباء على التركيب الكيميائي والمضاد',
              'hintEn': 'Bring original container to ER so physicians identify exact chemical breakdown and antidote',
              'safeTextAr': 'أخذ علبة المنظف الأصلية معكم للإسعاف لتمكين أطباء الطوارئ من معرفة المادة الفعالة',
              'safeTextEn': 'Bring original product bottle directly to ER so doctors inspect ingredient labels for antidote',
              'safeExpAr': 'إجراء حاسم؛ معرفة رقم المادة ومكوناتها يحدد غسيل المعدة والترياق المناسب.',
              'safeExpEn': 'Critical step; container label reveals active ingredient enabling targeted antidote therapy.',
              'safeOutAr': 'أخذت عبوة المنظف للمحطة 5.',
              'safeOutEn': 'Retained chemical bottle for Station 5.',
              'unsafeTextAr': 'رمي العلبة في النفايات قبل مغادرة المنزل للمستشفى',
              'unsafeTextEn': 'Throw chemical bottle into trash can before leaving for ER',
              'unsafeExpAr': 'خطأ؛ رمي العلبة يصعب على الأطباء معرفة ونوع التسمم الحامضي أو القلوي.',
              'unsafeExpEn': 'Error; discarding container delays medical team in identifying acid vs alkali poisoning.',
              'unsafeOutAr': 'جهل المادة بالمستشفى.',
              'unsafeOutEn': 'Unknown toxin delay.',
            },
            {
              'sitAr': 'وصول المستشفى وعلاج الطفل. ما الوقاية المنزلية المستدامة لمنع تكرار التسمم؟',
              'sitEn': 'Child treated safely at ER. Sustainable home prevention rule to stop chemical poisonings?',
              'hintAr': 'حفظ جميع المنظفات والمواد الكيميائية في خزائن مرتفعة ومقفولة بقفل سلامة',
              'hintEn': 'Store all household cleaners in high, locked cabinets with child-proof safety latches',
              'safeTextAr': 'حفظ جميع المنظفات والمواد الكيميائية في خزانات مرتفعة ومقفولة بأقفال أمان خاصة',
              'safeTextEn': 'Lock all household chemicals in high wall-mounted cabinets fitted with child safety latches',
              'safeExpAr': 'إتمام كامل؛ تخزين المواد المرتفع والمغلق يقضي على 99% من حوادث التسمم المنزلي.',
              'safeExpEn': 'Complete resolution; high locked storage eliminates 99% of accidental pediatric poisoning incidents.',
              'safeOutAr': 'أكملت محطات إسعاف التسمم الكيميائي بنجاح!',
              'safeOutEn': 'Successfully completed chemical poisoning first aid scenario!',
              'unsafeTextAr': 'إعادة تعبئة المطهرات والفلاش في قارورات المياه المعدنية وعصائر الأطفال',
              'unsafeTextEn': 'Decant toxic cleaners or drain chemicals into clear water or juice drinking bottles',
              'unsafeExpAr': 'خطأ قاتل؛ وضع المواد السامة بقوارير العصير يخدع الأطفال والكبار بشربها.',
              'unsafeExpEn': 'Fatal error; storing chemicals in beverage containers tricks kids into drinking lethal toxins.',
              'unsafeOutAr': 'مخاطرة بقوارير العصير السامة.',
              'unsafeOutEn': 'Decanting chemical risk persisted.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_8',
          categoryId: 'emergency_kit',
          titleAr: 'إسعاف ضربات وحروق العين الكيميائية',
          titleEn: 'Eye Injury & Chemical Splash First Aid',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لغسيل العين وإنقاذ البصر عند غمر الكيماويات.',
          descriptionEn: 'Interactive 5-station scenario for emergency eye flushing & splash first aid.',
          difficulty: 'صعب',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'تناثر سائل حمضي أو كلور مركز مباشرة داخل عين العامل أو الشخص. ما الإجراء الفوري الأول؟',
              'sitEn': 'Concentrated bleach or acid splashes directly into eye. Immediate first aid action?',
              'hintAr': 'غسل العين فوراً بماء صنبور جاري متواصل لمدة 15 إلى 20 دقيقة دون توقف',
              'hintEn': 'Flush eye immediately with continuous cool running tap water for 15 to 20 minutes',
              'safeTextAr': 'غسل العين المصابة فوراً تحت ماء صنبور جاري خفيف لمدة 20 دقيقة متواصلة مع فتح الجفون',
              'safeTextEn': 'Flush injured eye under continuous gentle stream of tap water for 20 full minutes holding eyelids open',
              'safeExpAr': 'استجابة ذهبية؛ الغسيل المستمر يقلل تركيز الكيماويات ويوقف تآكل القرنية.',
              'safeExpEn': 'Golden response; continuous water flushing dilutes chemical concentration stopping corneal burns.',
              'safeOutAr': 'بدأت غسيل العين للمحطة 2.',
              'safeOutEn': 'Initiated 20-min eye flush for Station 2.',
              'unsafeTextAr': 'دعك وفرك العين بقوة باليد والضغط على الجفن',
              'unsafeTextEn': 'Rub eye forcefully with hands pressing hard on closed eyelid',
              'unsafeExpAr': 'خطأ كارثي؛ فرك العين ينشر المادة الكاوية ويعزز خدش وتقرّح القرنية.',
              'unsafeExpEn': 'Catastrophic error; rubbing drives corrosive chemicals deeper into corneal tissue causing blindness.',
              'unsafeOutAr': 'تآكل وتقرّح القرنية.',
              'unsafeOutEn': 'Corneal chemical ulceration.',
            },
            {
              'sitAr': 'كيف تغسل العين دون نقل المادة الكيميائية للعين السليمة المجاورة؟',
              'sitEn': 'How to position head during eye flush to protect uninjured other eye?',
              'hintAr': 'إمالة الرأس نحو جهة العين المصابة لأسفل بحيث يتدفق الماء للخارج بعيداً عن العين الأخرى',
              'hintEn': 'Tilt head toward side of injured eye so water drains away from healthy eye',
              'safeTextAr': 'إمالة الرأس جانباً نحو جهة العين المصابة ليجري الماء للخارج دون المرور بالعين السليمة',
              'safeTextEn': 'Tilt head sideways down toward injured eye side ensuring runoff drains away from good eye',
              'safeExpAr': 'تكتيك وقائي رائع؛ إمالة الرأس تضمن عدم تلوث العين السليمة بالماء الكيميائي النازل.',
              'safeExpEn': 'Great prevention; tilting head downwards isolates runoff protecting opposite healthy eye.',
              'safeOutAr': 'وجهت سريان الماء للمحطة 3.',
              'safeOutEn': 'Directed water flow safely for Station 3.',
              'unsafeTextAr': 'مستلقياً على ظهرك وصب الماء بين العينين بالنصف',
              'unsafeTextEn': 'Lay flat on back pouring water directly over bridge of nose into both eyes',
              'unsafeExpAr': 'خطأ؛ صب الماء بالمنتصف ينقل الكيماويات من العين المصابة إلى العين السليمة.',
              'unsafeExpEn': 'Error; central pouring washes corrosive chemicals directly into unaffected eye.',
              'unsafeOutAr': 'انتقلت المادة الكيميائية للعين الأخرى.',
              'unsafeOutEn': 'Chemical contaminated good eye.',
            },
            {
              'sitAr': 'شخص يرتدي عدسات لاصقة أثناء تعرضه لتناثر المواد الكيميائية. متى تزيل العدسات؟',
              'sitEn': 'Victim wearing contact lenses during chemical splash. When to remove contact lenses?',
              'hintAr': 'محاولة إزالة العدسات أثناء غسيل الماء الجاري إذا لم تكن ملتصقة بالقرنية',
              'hintEn': 'Attempt to slide out lenses during continuous water flushing if not fused to cornea',
              'safeTextAr': 'مواصلة صب الماء الجاري ومحاولة نزع العدسة برفق أثناء الغسيل إذا انزلاقت تلقائياً',
              'safeTextEn': 'Continue water flushing while gently sliding out contact lens if loosened by water',
              'safeExpAr': 'تصرف احترافي؛ حصر الكيماويات تحت العدسة يضاعف التلف إذا لم تزال بالغسيل.',
              'safeExpEn': 'Pro step; chemical trapping behind contacts causes rapid deep tissue destruction if unremoved.',
              'safeOutAr': 'نزعت العدسة المعزولة للمحطة 4.',
              'safeOutEn': 'Removed trapped contact lens for Station 4.',
              'unsafeTextAr': 'نزع العدسة الالتصاقية بالقوة الجافة قبل البدء بغسيل الماء',
              'unsafeTextEn': 'Pinch and yank contact lens off dry eye before initiating water flush',
              'unsafeExpAr': 'خطأ؛ نزع العدسة الجافة قد ينسلخ معه غشاء القرنية الخارجي.',
              'unsafeExpEn': 'Error; yanking dry chemical-softened lens tears away delicate corneal epithelium.',
              'unsafeOutAr': 'تمزق غشاء القرنية.',
              'unsafeOutEn': 'Corneal epithelium torn.',
            },
            {
              'sitAr': 'انتهاء الـ 20 دقيقة غسيل بالماء. كيف تغطي العين المصابة لنقلها لطوارئ العيون؟',
              'sitEn': 'Completed 20-minute flushing. How to bandage eye for transport to ER?',
              'hintAr': 'تغطية العين بضمادة معقمة فضفاضة أو كوب بلاستيكي ناعم دون الضغط على الكرة',
              'hintEn': 'Cover eye loosely with sterile pad or paper cup without pressing on globe',
              'safeTextAr': 'تغطية العين برفق بضمادة معقمة فضفاضة أو تثبيت كوب ورقي لحمايتها من الضوء واللمس',
              'safeTextEn': 'Cover eye loosely with sterile pad or tape a paper cup over socket avoiding globe pressure',
              'safeExpAr': 'تأمين آمن؛ الكوب الورقي يحمي العين من أي ضغط أو احتكاك خارجي أثناء الطريق.',
              'safeExpEn': 'Safe protection; paper cup shield prevents accidental pressure on damaged globe during transit.',
              'safeOutAr': 'حميت العين بضمادة آمنة للمحطة 5.',
              'safeOutEn': 'Shielded eye for transport for Station 5.',
              'unsafeTextAr': 'ربط غطاء على العين بشريط ضاغط شديد وقوي',
              'unsafeTextEn': 'Bind eye socket tightly with heavy pressure elastic bandage',
              'unsafeExpAr': 'خطأ؛ الضغط على العين الكيميائية يزيد التلف الداخلي للكرة البصرية.',
              'unsafeExpEn': 'Error; applying pressure to chemically damaged eyeball causes intraocular damage.',
              'unsafeOutAr': 'انحصار الضغط الداخلي.',
              'unsafeOutEn': 'Intraocular pressure injury.',
            },
            {
              'sitAr': 'وصول طوارئ العيون بالمستشفى (997). ما المعيار الوقائي بالورش والمنازل؟',
              'sitEn': 'Rushed to ER eye clinic via 997. Permanent prevention protocol for homes and workshops?',
              'hintAr': 'ارتداء نظارات السلامة الواقية (Safety Goggles) دائماً عند التعامل مع المواد الكيميائية',
              'hintEn': 'Always wear splash-proof Safety Goggles when handling acids or drain cleaners',
              'safeTextAr': 'الالتزام بارتداء نظارات حماية العين البلاستيكية (Safety Goggles) عند التعامل مع المنظفات القوية',
              'safeTextEn': 'Mandate wearing enclosed splash-proof Safety Goggles whenever mixing or handling strong chemicals',
              'safeExpAr': 'إتمام كامل؛ نظارات الحماية تمنع 100% من حوادث تطاير المواد الكيميائية بالعين.',
              'safeExpEn': 'Complete resolution; splash goggles prevent 100% of accidental eye chemical splash injuries.',
              'safeOutAr': 'أكملت محطات إسعاف حروق العين بنجاح!',
              'safeOutEn': 'Successfully completed eye chemical splash first aid scenario!',
              'unsafeTextAr': 'سكب المنظفات القوية بدون ارتداء نظارات حماية العين',
              'unsafeTextEn': 'Pour concentrated drain acid directly while looking closely without goggles',
              'unsafeExpAr': 'خطأ؛ تناثر قطرة واحدة كفيل بإفقاد البصر جزئياً أو كلياً.',
              'unsafeExpEn': 'Error; a single splash droplet of drain acid can cause permanent blindness.',
              'unsafeOutAr': 'مخاطرة بالفقدان البصري.',
              'unsafeOutEn': 'Permanent visual loss risk.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_emergency_kit_9',
          categoryId: 'emergency_kit',
          titleAr: 'طوارئ الغرق والتنفس الصناعي بالمسابح',
          titleEn: 'Pool Drowning Rescue & Pediatric CPR Protocol',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لإنقاذ الغريق بالمسبح وتطبيق الإنعاش الرئوي.',
          descriptionEn: 'Interactive 5-station scenario for pool drowning rescue and CPR.',
          difficulty: 'صعب',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
          stations: [
            {
              'sitAr': 'رؤية طفل يصارع المياه ومستغرق في القاع بمسبح المنزل. ما الإجراء الأول؟',
              'sitEn': 'Child submerged at bottom of home swimming pool unresponsive. Immediate action?',
              'hintAr': 'إخراج الطفل فوراً من الماء بأمان والطلب من أحدهم الاتصال بالإسعاف (997)',
              'hintEn': 'Extract child immediately from water safely; direct bystander to call 997',
              'safeTextAr': 'سحب الطفل من قاع المسبح فوراً للبر الجاف، وإيعاز شخص للاتصال بالإسعاف 997',
              'safeTextEn': 'Extract child from pool instantly onto dry firm ground; command bystander to dial 997',
              'safeExpAr': 'استجابة سريعة؛ كل ثانية بالإنقاذ توفر خيارات نجاة الدماغ من نقص الأكسجين (Hypoxia).',
              'safeExpEn': 'Rapid response; every second saved halts progressive anoxic brain damage.',
              'safeOutAr': 'سحبت الغريق للبر للمحطة 2.',
              'safeOutEn': 'Extracted victim to dry land for Station 2.',
              'unsafeTextAr': 'البحث عن الهاتف والاتصال بالإسعاف والطفل ما زال بالقاع',
              'unsafeTextEn': 'Search for phone to call 997 while leaving child submerged at bottom',
              'unsafeExpAr': 'خطأ قاتل؛ ترك الغريق بالماء يكمل الاختناق والوفاة بالدماغ.',
              'unsafeExpEn': 'Fatal error; leaving drowning victim under water causes irreversible cardiac arrest.',
              'unsafeOutAr': 'توقف القلب تحت الماء.',
              'unsafeOutEn': 'Submerged cardiac arrest.',
            },
            {
              'sitAr': 'الطفل فاقد للوعي ولا يتنفس. ما الخطوة الأولى بالإنعاش القلبي الرئوي للغريق؟',
              'sitEn': 'Child unconscious and not breathing. First step in drowning CPR protocol?',
              'hintAr': 'إعطاء 5 أنفاس إنقاذية أولية (Rescue Breaths) قبل بدء الضغطات الصدرية',
              'hintEn': 'Give 5 initial Rescue Breaths FIRST in drowning cases to restore depleted oxygen',
              'safeTextAr': 'إعطاء 5 أنفاس إنقاذية متتالية في فم الغريق لتزويده بالأكسجين المفقود بالرئة',
              'safeTextEn': 'Deliver 5 initial rescue breaths immediately covering mouth/nose to inflate oxygen-starved lungs',
              'safeExpAr': 'بروتوكول حاسم؛ بروتوكول الغرق يبدأ بالأنفاس لأن سبب التوقف هو نقص الأكسجين.',
              'safeExpEn': 'Crucial protocol; drowning CPR starts with 5 rescue breaths because hypoxia is the primary cause.',
              'safeOutAr': 'أعطيت الأنفاس الإنقاذية للمحطة 3.',
              'safeOutEn': 'Delivered 5 rescue breaths for Station 3.',
              'unsafeTextAr': 'إضاعة الوقت بالضغط على البطن لتفريغ ماء المسبح',
              'unsafeTextEn': 'Waste time pressing forcefully on stomach trying to drain swallowed water',
              'unsafeExpAr': 'خطأ؛ محاولة تفريغ ماء البطن يسبب تقيؤ الطفل وانسداد الرئة بالكامل.',
              'unsafeExpEn': 'Error; gastric pumps induce vomiting leading to fatal airway aspiration during CPR.',
              'unsafeOutAr': 'انسداد الرئة بالاستفراغ.',
              'unsafeOutEn': 'Vomitus airway aspiration.',
            },
            {
              'sitAr': 'تطبيق الضغطات الصدرية (Chest Compressions) للطفل الغريق. ما المعدل والعمق؟',
              'sitEn': 'Applying chest compressions for drowning child. Rate and depth standard?',
              'hintAr': '30 ضغطة صدرية مقابل نفخين بمعدل 100-120 ضغطة بالدقيقة بعمق 4-5 سم',
              'hintEn': '30 compressions to 2 breaths at 100-120 bpm, depressing chest 4-5 cm deep',
              'safeTextAr': 'تطبيق 30 ضغطة صدرية في منتصف الصدر ثم نفخين إنقاذيين بمعدل 100-120 ضغطة بالدقيقة',
              'safeTextEn': 'Perform cycles of 30 chest compressions followed by 2 rescue breaths at 100-120 bpm rate',
              'safeExpAr': 'إنعاش معياري؛ معدل 30:2 يدعم تدوير الدم المحمل بالأكسجين للدماغ.',
              'safeExpEn': 'Standard CPR; 30:2 ratio pumps oxygenated blood continuously to vital organs.',
              'safeOutAr': 'واصلت الضغطات 30:2 للمحطة 4.',
              'safeOutEn': 'Maintained 30:2 CPR cycle for Station 4.',
              'unsafeTextAr': 'الضغط البطني السريع بطرق عشوائية دون نفخات',
              'unsafeTextEn': 'Press stomach randomly avoiding rescue breaths altogether',
              'unsafeExpAr': 'خطأ؛ الضغط البطني العشوائي لا يحيي الدورة الدموية ولا ينقذ الدماغ.',
              'unsafeExpEn': 'Error; stomach pressing provides zero cardiac output failing to oxygenate brain.',
              'unsafeOutAr': 'توقف تدوير الدم.',
              'unsafeOutEn': 'Zero cardiac output.',
            },
            {
              'sitAr': 'وصول جهاز الصدمات الكهربائية الخارجي (AED). كيف تستخدمه مع غريق مبتل؟',
              'sitEn': 'Automated External Defibrillator (AED) arrives. How to use AED safely on wet drowning victim?',
              'hintAr': 'تفيف صدر المصاب بسرعة بالمنشفة قبل إلقاء وسائد الصدمة الكهربائية',
              'hintEn': 'Wipe victim\'s chest dry immediately before applying AED pads',
              'safeTextAr': 'تجفيف صدر المصاب فوراً بمنشفة، ثم تثبيت وسادات AED وقراءة تخطيط القلب',
              'safeTextEn': 'Wipe child\'s bare chest dry with towel, then adhere AED pads following voice prompts',
              'safeExpAr': 'تأمين ممتازا؛ تجفيف الصدر يمنع تشتت الشحنة الكهربائية عبر ماء الجلد.',
              'safeExpEn': 'Great safety step; drying chest prevents AED electrical shock from dispersing across wet skin.',
              'safeOutAr': 'جففت الصدر وركبت AED للمحطة 5.',
              'safeOutEn': 'Dried chest & attached AED for Station 5.',
              'unsafeTextAr': 'إلصاق وسائد AED فوق الصدر المليء بالماء الغزير',
              'unsafeTextEn': 'Stick adhesive AED pads directly over dripping wet soaking chest',
              'unsafeExpAr': 'خطأ؛ ماء الصدر يسبب قوساً كهربائياً سطحياً يفشل الصدمة وتدفقها للقلب.',
              'unsafeExpEn': 'Error; surface water causes electrical arcing shorting shock away from heart.',
              'unsafeOutAr': 'فشلت صدمة القلب.',
              'unsafeOutEn': 'AED shock arced harmlessly.',
            },
            {
              'sitAr': 'عادت النبضات واستعاد الطفل التنفس التلقائي. ما التوجيه النهائي بمستشفى الطوارئ؟',
              'sitEn': 'Child regains pulse and spontaneous breathing. Final mandatory hospital guideline?',
              'hintAr': 'نقل الطفل فوراً للمستشفى للملاحظة 24 ساعة للوقاية من الغرق الثانوي (Secondary Drowning)',
              'hintEn': 'RUSH to hospital for 24h observation to monitor for lethal Secondary Drowning',
              'safeTextAr': 'نقل الطفل بـ 997 للمستشفى والملاحظة 24 ساعة للوقاية من مضاعفات الغرق الثانوي والوذمة الرئوية',
              'safeTextEn': 'Transport child to ER via 997 ambulance for mandatory 24-hour observation against Secondary Drowning',
              'safeExpAr': 'إتمام كامل؛ الغرق الثانوي قد يظهر بعد ساعات بسبب تراكم السوائل بالحويصلات الرئوية.',
              'safeExpEn': 'Complete resolution; Secondary Drowning can strike hours later as pulmonary edema sets in.',
              'safeOutAr': 'أكملت محطات إنعاش الغرق بالمسبح بنجاح!',
              'safeOutEn': 'Successfully completed drowning rescue & CPR scenario!',
              'unsafeTextAr': 'السماح للطفل بالنوم بالمنزل فور استعادة وعيه دون فحص المستشفى',
              'unsafeTextEn': 'Let child go to sleep at home immediately after coughing up water without ER check',
              'unsafeExpAr': 'خطأ قاتل؛ الغرق الثانوي قد يسبب الوفاة الصامتة أثناء النوم بعد ساعات.',
              'unsafeExpEn': 'Fatal error; secondary pulmonary edema causes silent hypoxia and death during sleep.',
              'unsafeOutAr': 'مخاطرة بالغرق الثانوي.',
              'unsafeOutEn': 'Secondary drowning risk persisted.',
            },
          ],
        ),
      ];
}
