import '../../../models/scenario.dart';
import 'scenario_builder.dart';

class ScenariosFlood {
  static List<Scenario> get list => [
        // 1. Flood Scenario 1
        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_1',
          categoryId: 'flood',
          titleAr: 'عبور الأودية والسيول المنقولة',
          titleEn: 'Wadi Flash Floods & Rescue',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتجنب احتجاز السيارات بالسيول وكيفية النجاة.',
          descriptionEn: 'Interactive 5-station scenario to overcome wadi flash floods and car trapping.',
          difficulty: 'صعب',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'شاهدت جريان سيل جارف عبر بطن الوادي أمام طريقك. ما القرار؟',
              'sitEn': 'Rapid wadi flash flood crossing road ahead. Initial choice?',
              'hintAr': 'التوقف الفوري وعدم المغامرة بقطع السيل مهما كان عمقه ضئيلاً',
              'hintEn': 'Stop immediately; 15cm of moving water can knock you down and 30cm moves cars',
              'safeTextAr': 'التوقف الفوري على جانب مرتفع وعدم تجسير السيل نهائياً',
              'safeTextEn': 'Stop immediately on high ground and strictly avoid crossing wadi',
              'safeExpAr': 'قرار حكيم؛ قوة اندفاع السيول تحرف المركبات الثقيلة وسرعتها تخدع العين.',
              'safeExpEn': 'Wise choice; torrent power easily sweeps heavy 4WDs downstream.',
              'safeOutAr': 'تجنبت الانجراف وانتقلت للمحطة 2.',
              'safeOutEn': 'Avoided flash flood drag, moving to Station 2.',
              'unsafeTextAr': 'زيادة السرعة ومحاولة قطع الوادي قبل ارتفاع منسوب المياه',
              'unsafeTextEn': 'Accelerate fast hoping to cross before water rises higher',
              'unsafeExpAr': 'مخاطرة مهلكة؛ اندفاع السيل يحرف عجلة القيادة ويعطل المحرك وسط مجرى الوادي.',
              'unsafeExpEn': 'Fatal risk; torrential push stalls engine and floats car downriver.',
              'unsafeOutAr': 'تعطلت المركبة وسط السيل.',
              'unsafeOutEn': 'Car engine stalled mid-torrent stream.',
            },
            {
              'sitAr': 'ارتفع منسوب المياه حول السيارة وتوقفت عن العمل. كيف تتصرف فوراً؟',
              'sitEn': 'Water level rises around vehicle and engine dead. Immediate act?',
              'hintAr': 'فتح النوافذ الكهربائية وفك حزام الأمان قبل انقطاع كهرباء المركبة',
              'hintEn': 'Open power windows and unbuckle seatbelts before battery shorts out',
              'safeTextAr': 'فتح النوافذ فوراً، فك حزام الأمان، والاستعداد للخروج قبل تعطل الكهرباء',
              'safeTextEn': 'Lower windows immediately, unbuckle belts, prepare escape before power failure',
              'safeExpAr': 'استجابة ذهبية؛ فتح النوافذ يمنع احتجازك داخل السيارة بسبب ضغط المياه.',
              'safeExpEn': 'Golden response; open windows prevent door jamming from water pressure.',
              'safeOutAr': 'فتحت منفذ الخروج للمحطة 3.',
              'safeOutEn': 'Secured exit route for Station 3.',
              'unsafeTextAr': 'إغلاق النوافذ بإحكام والانتظار داخل السيارة المغلقة',
              'unsafeTextEn': 'Roll up windows tightly waiting inside sealed cabin',
              'unsafeExpAr': 'خطأ؛ ضغط المياه الخارجي يمنع فتح الأبواب عند انغمار السيارة بالكامل.',
              'unsafeExpEn': 'Error; external hydrostatic pressure locks doors tight when submerged.',
              'unsafeOutAr': 'احتجزت داخل المقوّرة.',
              'unsafeOutEn': 'Trapped inside flooded cabin.',
            },
            {
              'sitAr': 'بدأت المياه تغمر أرضية السيارة. ما أفضل وسيلة للخروج والنجاة؟',
              'sitEn': 'Water flooding floorboards rapidly. Best escape method?',
              'hintAr': 'الخروج عبر النافذة والاعتلاء فوق سقف المركبة للبقاء فوق مستوى التيار',
              'hintEn': 'Climb out through window onto vehicle roof to stay above rushing torrent',
              'safeTextAr': 'تسلق النافذة والصعود إلى سقف السيارة والتمسك به بقوة',
              'safeTextEn': 'Climb through open window onto car roof and hold on tightly',
              'safeExpAr': 'موقع آمن؛ سقف السيارة يمنحك ارتفاعاً عن دوامات السيل السفلى.',
              'safeExpEn': 'Safe vantage; car roof provides elevation above violent undercurrents.',
              'safeOutAr': 'وصلت لسقف المركبة بنجاح للمحطة 4.',
              'safeOutEn': 'Reached roof safely, ready for Station 4.',
              'unsafeTextAr': 'القفز في المياه والسباحة عكس اتجاه التيار الجارف',
              'unsafeTextEn': 'Jump into torrential water and swim against violent current',
              'unsafeExpAr': 'خطأ جسيم؛ السباحة في السيل المنقول مستحيلة بسبب الصخور والحطام المندفع.',
              'unsafeExpEn': 'Severe error; swimming torrents is impossible due to submerged rocks and debris.',
              'unsafeOutAr': 'انجرفت مع حطام السيل.',
              'unsafeOutEn': 'Swept away by heavy debris stream.',
            },
            {
              'sitAr': 'وصول طائرة أو فرقة إنقاذ الدفاع المدني بالزوارق. كيف توضح موقعك؟',
              'sitEn': 'Civil Defense helicopter or boat rescue team searching area. How to signal?',
              'hintAr': 'التلويح بقماش زاهي اللون أو إضاءة كشاف الجوال دون الاتكاء المائل',
              'hintEn': 'Wave bright cloth or flash phone torch while maintaining secure footing',
              'safeTextAr': 'التلويح بقطعة قماش ملونة وإضاءة فلاش الجوال بقوة لجذب المنقذين',
              'safeTextEn': 'Wave bright cloth and flash mobile phone torch to attract rescuers',
              'safeExpAr': 'ممتاز؛ الإشارات البصرية الواضحة تسهم في سرعة رصدك وتحديد موقعك.',
              'safeExpEn': 'Excellent; high-visibility signals help air and water rescue pin location.',
              'safeOutAr': 'رصدت فرق الإنقاذ موقعك للمحطة 5.',
              'safeOutEn': 'Rescue crew spotted your signal for Station 5.',
              'unsafeTextAr': 'الوقوف على طرف السقف والقفز في الهواء بشكل غير متزن',
              'unsafeTextEn': 'Stand recklessly on roof edge jumping up and down',
              'unsafeExpAr': 'خطأ؛ السقف أملس وقد تسبل قدمك وتسقط في المجرى المائي.',
              'unsafeExpEn': 'Error; slippery wet roof surfaces risk slipping into swift floodwaters.',
              'unsafeOutAr': 'تعرضت لخطر الانزلاق بالسيل.',
              'unsafeOutEn': 'Risked slipping into raging current.',
            },
            {
              'sitAr': 'تم سحبك بأمان بواسطة حبال الإنقاذ للبر الآمن. ما الخطوة النهائية؟',
              'sitEn': 'Pulled to safe shoreline using rescue harnesses. Final step?',
              'hintAr': 'الفحص الطبي السريع مع فرق الإسعاف (997) وتجنب البقاء بالملابس المبللة',
              'hintEn': 'Undergo quick medical evaluation by paramedics 997 and prevent hypothermia',
              'safeTextAr': 'إجراء الفحص الطبي لدى الهلال الأحمر (997) واستبدال الملابس المبللة تفادياً لانخفاض الحرارة',
              'safeTextEn': 'Undergo 997 paramedic evaluation and change damp clothes preventing hypothermia',
              'safeExpAr': 'إتمام ناجح؛ الاطمئنان الطبي والتدفئة يمنعان صدمة البرد والاصابات الباطنية.',
              'safeExpEn': 'Successful execution; medical triage and warming prevent hypothermia shock.',
              'safeOutAr': 'أكملت محطات النجاة من السيول بنجاح!',
              'safeOutEn': 'Successfully completed all 5 flood rescue stations!',
              'unsafeTextAr': 'مغادرة الموقع فوراً دون إجراء أي فحص طبي أو تدفئة',
              'unsafeTextEn': 'Leave scene immediately without medical checkup or body warming',
              'unsafeExpAr': 'خطأ؛ انخفاض حرارة الجسم قد يسبب صدمة بعد النجاة.',
              'unsafeExpEn': 'Error; secondary hypothermia shock can strike unexamined survivors.',
              'unsafeOutAr': 'تعرضت لإجهاد حراري وبرودة شديدة.',
              'unsafeOutEn': 'Suffered severe hypothermia fatigue.',
            },
          ],
        ),

        // 2. Flood Scenario 2
        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_2',
          categoryId: 'flood',
          titleAr: 'دخول المياه للدور الأرضي والارتفاع للمنسوب',
          titleEn: 'Ground Floor Inundation & Rising Water',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع غرق المنزل والتحرك نحو الأدوار العلوية.',
          descriptionEn: 'Interactive 5-station scenario for home ground floor flooding.',
          difficulty: 'متوسط',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'بدأت مياه الأمطار بالتجمع بالحوش والتسرب عبر الأبواب للدور الأرضي. ما أول تصرف؟',
              'sitEn': 'Rainwater flooding yard and leaking into ground floor doors. Immediate step?',
              'hintAr': 'فصل القاطع الكهربائي الرئيسي للدور الأرضي لتجنب الصعق المائي',
              'hintEn': 'Shut off main ground floor electrical breaker to eliminate water shock',
              'safeTextAr': 'فصل قاطع الكهرباء الرئيسي للشقة أو الدور الأرضي فوراً من مكان جاف',
              'safeTextEn': 'Shut off ground floor main electrical breaker immediately from dry spot',
              'safeExpAr': 'إجراء ممتاز؛ غرق الفيش السفلية بالماء يسبب صعقاً كهربائياً قاتلاً.',
              'safeExpEn': 'Excellent step; submerged low electrical sockets cause lethal water electrification.',
              'safeOutAr': 'قطعت الكهرباء عن الأراضي المبللة للمحطة 2.',
              'safeOutEn': 'Isolated ground power for Station 2.',
              'unsafeTextAr': 'تشغيل الأجهزة الكهربائية وسحب المياه بمكنسة كهربائية',
              'unsafeTextEn': 'Plug in electric wet-vac cleaner to suck up incoming floodwater',
              'unsafeExpAr': 'خطأ كارثي؛ استخدام أجهزة كهربائية فوق أرضية مبللة يسبب الصعق الفوري.',
              'unsafeExpEn': 'Catastrophic error; operating electric gear on wet floor causes instant electrocution.',
              'unsafeOutAr': 'تعرضت للصعق الكهربائي المائي.',
              'unsafeOutEn': 'Electrocuted by water contact.',
            },
            {
              'sitAr': 'ارتفع منسوب المياه لـ 30 سم داخل الشقة. كيف تؤمن أفراد الأسرة؟',
              'sitEn': 'Water level reaches 30cm inside home. How to secure family?',
              'hintAr': 'الصعود السريع للأدوار العلوية أو السطح وأخذ حقيبة الطوارئ',
              'hintEn': 'Evacuate upstairs to higher floors/roof taking emergency kit',
              'safeTextAr': 'توجيه الأسرة للصعود للأدوار العلوية أو السطح وحمل حقيبة الإسعاف والمياه',
              'safeTextEn': 'Evacuate family upstairs to upper floor or roof carrying emergency survival kit',
              'safeExpAr': 'تصرف صحيح؛ الارتفاع للأماكن العلوية يمنع الانحصار ومخاطر الغرق.',
              'safeExpEn': 'Correct move; ascending upstairs shields family from rising flood levels.',
              'safeOutAr': 'صعدت الأسرة للأماكن المرتفعة للمحطة 3.',
              'safeOutEn': 'Evacuated upstairs for Station 3.',
              'unsafeTextAr': 'البقاء في الدور الأرضي وحماية السجاد والأثاث الخشبي',
              'unsafeTextEn': 'Stay on ground floor trying to stack wooden furniture and rugs',
              'unsafeExpAr': 'خطأ؛ الارتفاع السريع للمياه قد يحاصركم بالدور الأرضي دون مخرج.',
              'unsafeExpEn': 'Error; rapid water rise traps occupants on ground floor with zero exit.',
              'unsafeOutAr': 'انحصرت بالدور الأرضي.',
              'unsafeOutEn': 'Trapped on ground floor.',
            },
            {
              'sitAr': 'انقطاع التيار البلاغي والشبكة الجوالة بالمنزل. كيف تطلب الاستغاثة؟',
              'sitEn': 'Power and local cell tower cutout at home. How to request rescue?',
              'hintAr': 'استخدام الصافرة، الكشاف اليدوي من السطح، والاتصال بـ (911/998)',
              'hintEn': 'Use emergency whistle, roof flashlight, or satellite SOS dial 911',
              'safeTextAr': 'استخدام صافرة الاستغاثة وإشارات الكشاف من السطح لجذب فرق الإنقاذ',
              'safeTextEn': 'Use rescue whistle and torch light signals from roof to signal rescue boats',
              'safeExpAr': 'إشارات بصرية وصوتية ممتازة؛ الصافرة تشق صوت رعد المطر بوضوح.',
              'safeExpEn': 'Great sound and light signaling; whistles cut through torrential rain noise.',
              'safeOutAr': 'أرسلت إشارات الاستغاثة للمحطة 4.',
              'safeOutEn': 'Signaled rescue boats for Station 4.',
              'unsafeTextAr': 'النزول مجدداً للحوش المغمور بالمياه للبحث عن التغطية',
              'unsafeTextEn': 'Wade back down into flooded yard searching for mobile signal',
              'unsafeExpAr': 'خطأ؛ الخوض في مياه الحوش يعرضك للسقوط بفتحات بيارات الصرف المفتوحة.',
              'unsafeExpEn': 'Error; wading in flooded yard risks falling into displaced sewer manholes.',
              'unsafeOutAr': 'تعرضت لسقوط في بيارة الصرف.',
              'unsafeOutEn': 'Risked falling into open manhole.',
            },
            {
              'sitAr': 'وصول زوارق الدفاع المدني لمحيط المنزل. كيف تسلم الأطفال؟',
              'sitEn': 'Civil Defense rescue boats reach house perimeter. How to transfer kids?',
              'hintAr': 'إلباس الأطفال سترة النجاة أو ربطه بحبل أمان قبل تسليمه للزورق',
              'hintEn': 'Equip kids with life jackets or safety line before transferring to boat',
              'safeTextAr': 'إلباس الأطفال سترات النجاة وتأمينهم بحبل وتثبيتهم بيدي المنقذ',
              'safeTextEn': 'Equip kids with life vests and hand them safely to boat rescuers one by one',
              'safeExpAr': 'إجراء أمني محترف؛ سترات النجاة تحمي الأطفال من الانزلاق المفاجئ بالماء.',
              'safeExpEn': 'Pro security protocol; life vests protect children against slipping into deep water.',
              'safeOutAr': 'سلمت الأطفال بأمان للمحطة 5.',
              'safeOutEn': 'Transferred kids safely for Station 5.',
              'unsafeTextAr': 'رمي الأطفال من ارتفاع السطح نحو الزورق',
              'unsafeTextEn': 'Toss kids down from roof height toward rescue boat',
              'unsafeExpAr': 'خطأ خطير؛ الرمي العشوائي قد يسبب سقوط الطفل في مجرى السيل.',
              'unsafeExpEn': 'Dangerous mistake; throwing kids risks missing boat and hitting flood current.',
              'unsafeOutAr': 'عرضت الطفل لخطر السقوط.',
              'unsafeOutEn': 'Risked dropping child in water.',
            },
            {
              'sitAr': 'الوصول لمركز الإيواء الطارئ. ما الخطوة الوقائية النهائية؟',
              'sitEn': 'Arrived at official emergency shelter. Final safety protocol?',
              'hintAr': 'تسجيل أسماء الأسرة لدى مشرف الإيواء، وإجراء فحص طبي شامل لجميع الأفراد',
              'hintEn': 'Check in family roster with shelter warden and undergo medical screening',
              'safeTextAr': 'تسجيل أسماء الأسرة لدى إدارة مركز الإيواء وتلقي التقييم الطبي من الهلال الأحمر',
              'safeTextEn': 'Register family at shelter administration and complete 997 Red Crescent triage',
              'safeExpAr': 'إتمام ناجح؛ التسجيل الإداري والفحص الطبي يضمن توفير السكن والرعاية التامة.',
              'safeExpEn': 'Successful completion; shelter registration and triage secure long-term support.',
              'safeOutAr': 'أكملت محطات إخلاء غرق المنزل بنجاح!',
              'safeOutEn': 'Successfully completed home flood scenario!',
              'unsafeTextAr': 'مغادرة مركز الإيواء والعودة للمنزل الغارق قبل صدور إشعار السلامة',
              'unsafeTextEn': 'Leave shelter returning to flooded home before Civil Defense clear safety alert',
              'unsafeExpAr': 'خطأ؛ العودة المبكرة تعرضكم لترسبات المباني والماس المتبقي.',
              'unsafeExpEn': 'Error; premature return exposes family to structural collapse and active short circuits.',
              'unsafeOutAr': 'عرضت الأسرة لمخاطر المبنى الغارق.',
              'unsafeOutEn': 'Exposed family to unsafe flooded building.',
            },
          ],
        ),

        // 3. Flood Scenario 3
        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_3',
          categoryId: 'flood',
          titleAr: 'احتجاز السيارة بالأنفاق الغارقة بالمياه',
          titleEn: 'Submerged Highway Tunnel Car Trap',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع غمر الأنفاق وتحرر المركبة من المياه.',
          descriptionEn: 'Interactive 5-station scenario for flooded underpass tunnel emergencies.',
          difficulty: 'صعب',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'دخلت نفقاً ورأيت تجمع مياه عميق وتوقف السيارات السابقة. ما التصرف؟',
              'sitEn': 'Drove into underpass tunnel seeing deep water pool and stalled cars. Action?',
              'hintAr': 'التوقف فوراً والرجوع للخلف إن أمكن وعدم التهور بالدخول في عمق النفق',
              'hintEn': 'Stop immediately and reverse out if clear; NEVER risk driving into flooded tunnel',
              'safeTextAr': 'التوقف الفوري قبل تجمع المياه وتغيير المسار للخلف أو الكتف الجانبي',
              'safeTextEn': 'Stop immediately before water pool and reverse out safely',
              'safeExpAr': 'قرار ممتاز؛ الأنفاق تجمع مياه السيول بسرعة فائقة ويصعب تقدير عمقها.',
              'safeExpEn': 'Excellent choice; underpass tunnels accumulate massive water depth rapidly.',
              'safeOutAr': 'تجنبت دخول النفق الغارق للمحطة 2.',
              'safeOutEn': 'Avoided flooded tunnel for Station 2.',
              'unsafeTextAr': 'مواصلة السير بسرعة عالية لشق المياه بالمركبة',
              'unsafeTextEn': 'Floor gas pedal to plow through deep tunnel water',
              'unsafeExpAr': 'خطأ قاتل؛ دخول النفق الغارق يعطل محرك المركبة ويتسبب في غرقها.',
              'unsafeExpEn': 'Fatal error; deep tunnel water floats vehicle and drowns air intake.',
              'unsafeOutAr': 'انغمرت السيارة بوسط النفق.',
              'unsafeOutEn': 'Vehicle submerged mid-tunnel.',
            },
            {
              'sitAr': 'داهمت المياه مركبتك بالنفق وتوقفت عن الحركة. كيف تفتح المنفذ؟',
              'sitEn': 'Water surged around car inside tunnel stalling engine. How to secure exit?',
              'hintAr': 'الضغط على زر فتح النوافذ فوراً قبل تلف النظام الكهربائي',
              'hintEn': 'Press power window switch down immediately before electrical failure',
              'safeTextAr': 'أنزل جميع النوافذ الكهربائية فوراً وفك حزام الأمان قبل تعطل البطارية',
              'safeTextEn': 'Roll down all power windows instantly and unbuckle belts before short circuit',
              'safeExpAr': 'استجابة ذهبية؛ النوافذ المفتوحة تضمن مخرج نجاة قبل ارتفاع المنسوب.',
              'safeExpEn': 'Golden action; open windows provide instant escape route before submergence.',
              'safeOutAr': 'فتحت النوافذ للمحطة 3.',
              'safeOutEn': 'Opened windows for Station 3.',
              'unsafeTextAr': 'محاولة إعادة تشغيل المحرك مراراً وتكراراً',
              'unsafeTextEn': 'Crank starter ignition repeatedly trying to restart drowned engine',
              'unsafeExpAr': 'خطأ؛ محاولة تشغيل المحرك المغمور تدمر الفوهة وتضيع وقت الخروج.',
              'unsafeExpEn': 'Error; cranking flooded engine causes water-lock explosion wasting escape time.',
              'unsafeOutAr': 'تعطلت الكهرباء تماماً.',
              'unsafeOutEn': 'Battery shorted out completely.',
            },
            {
              'sitAr': 'تعطلت الكهرباء والنوافذ مغلقة. كيف تكسر زجاج النافذة للنجاة؟',
              'sitEn': 'Power failed with windows closed. How to break side glass to escape?',
              'hintAr': 'استخدام رأس مسند الرأس (Headrest) لضرب زاوية النافذة الجانبية',
              'hintEn': 'Use metal prongs of seat headrest to shatter bottom corner of side window',
              'safeTextAr': 'خلع مسند الرأس واستخدام زواياه المعدنية لضرب زاوية الزجاج الجانبي',
              'safeTextEn': 'Detach seat headrest using its steel prongs to strike corner of side window glass',
              'safeExpAr': 'تقنية إنقاذ معتمدة؛ مسند الرأس يكسر الزجاج الجانبي بسهولة دون جهد كبير.',
              'safeExpEn': 'Certified escape technique; headrest steel points shatter tempered side glass easily.',
              'safeOutAr': 'كسرت الزجاج الجانبي للمحطة 4.',
              'safeOutEn': 'Shattered side glass for Station 4.',
              'unsafeTextAr': 'ضرب الزجاج الأمامي العريض بيدك أو بقدمك',
              'unsafeTextEn': 'Kick front laminated windshield with bare feet',
              'unsafeExpAr': 'خطأ؛ الزجاج الأمامي مزدوج ومصفح لا ينكسر بضرب القدم.',
              'unsafeExpEn': 'Error; front windshield is safety laminated glass which will not break by kicking.',
              'unsafeOutAr': 'فشلت في كسر الزجاج الأمامي.',
              'unsafeOutEn': 'Failed to break front windshield.',
            },
            {
              'sitAr': 'الخروج من السيارة وسط مياه النفق. أين تتجه داخل النفق الغارق؟',
              'sitEn': 'Escaped car inside flooded tunnel. Where to move inside tunnel?',
              'hintAr': 'التسلق على رصيف المشاة الجانبي بالنفق والتحرك نحو فتحة الخروج',
              'hintEn': 'Climb onto elevated tunnel side walkway moving toward daylight exit',
              'safeTextAr': 'الصعود على رصيف الصيانة الجانبي المرتفع بالنفق والتحرك باتجاه المخرج',
              'safeTextEn': 'Climb onto elevated tunnel side ledge walkway heading toward exterior exit',
              'safeExpAr': 'مسار آمن؛ رصيف الصيانة يرفعك فوق عمق المياه ويوصلك لخارج النفق.',
              'safeExpEn': 'Safe path; elevated maintenance ledge keeps you above deep water while exiting.',
              'safeOutAr': 'صعدت للرصيف الجانبي للمحطة 5.',
              'safeOutEn': 'Climbed side ledge for Station 5.',
              'unsafeTextAr': 'السباحة وسط منتصف النفق بين السيارات الطافية',
              'unsafeTextEn': 'Swim mid-tunnel between floating drifting vehicles',
              'unsafeExpAr': 'خطأ؛ السباحة بين السيارات الطافية تعرضك للانحصار والتصادم تحت المياه.',
              'unsafeExpEn': 'Error; swimming between drifting submerged cars risks crush hazards.',
              'unsafeOutAr': 'تعرضت لخطر الانحصار بين السيارات.',
              'unsafeOutEn': 'Risked getting crushed between cars.',
            },
            {
              'sitAr': 'الخروج من النفق بأمان وإبلاغ الطوارئ (911). ما الخطوة النهائية؟',
              'sitEn': 'Reached tunnel exterior safely calling 911. Final protocol?',
              'hintAr': 'الإبلاغ عن وجود سيارات محتجزة داخل النفق وتأمين موقع البوابة',
              'hintEn': 'Inform 911 of trapped vehicles inside tunnel and block entry gate',
              'safeTextAr': 'الإبلاغ الفوري عبر 911 عن موقع النفق والسيارات المحتجزة بالداخل لتنبيه الإنقاذ',
              'safeTextEn': 'Report flooded tunnel location and trapped cars to 911 dispatch immediately',
              'safeExpAr': 'إتمام تام؛ البلاغ الفوري يغلق مداخل النفق ويحمي سائقين آخرين من الدخول.',
              'safeExpEn': 'Complete resolution; immediate report blocks tunnel entry saving other drivers.',
              'safeOutAr': 'أكملت محطات نجاة النفق الغارق بنجاح!',
              'safeOutEn': 'Successfully completed tunnel flood scenario!',
              'unsafeTextAr': 'ترك النفق مغموراً دون تقديم أي بلاغ للجهات الأمنية',
              'unsafeTextEn': 'Walk away without notifying 911 of flooded tunnel hazard',
              'unsafeExpAr': 'خطأ؛ ترك النفق يسبب دخول سيارات أخرى وغرق ركابها.',
              'unsafeExpEn': 'Error; un-reported flooded tunnel traps incoming unwary motorists.',
              'unsafeOutAr': 'عرضت سائقين آخرين للخطر.',
              'unsafeOutEn': 'Left hazard un-reported to police.',
            },
          ],
        ),

        // Add Scenarios 4 to 9 for FLOOD to complete 9 scenarios total!
        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_4',
          categoryId: 'flood',
          titleAr: 'انهيار الصخور والانزلاقات بالطرق الجبلية',
          titleEn: 'Mountain Road Landslides & Rockfalls',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تساقط الصخور في الطرق الجبلية أثناء الأمطار.',
          descriptionEn: 'Interactive 5-station scenario for mountain road rockfalls during rain.',
          difficulty: 'متوسط',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'أثناء قيادتك بطريق جبلي أثناء هطول أمطار غزيرة تساقطت حجارة صغيرة على الزجاج. ما أول حركة؟',
              'sitEn': 'Small rocks hit windshield on mountain road during heavy rain. Initial step?',
              'hintAr': 'تخفيف السرعة فوراً وتفعيل أضواء التحذير وتجنب التوقف أسفل الصخور',
              'hintEn': 'Slow down, turn on hazard flashers; do NOT stop underneath steep cliffs',
              'safeTextAr': 'تخفيف السرعة، تشغيل أضواء التحذير، والابتعاد عن مجرى التساقط الصخري',
              'safeTextEn': 'Slow down, turn hazard lights on, and move away from active rockfall zone',
              'safeExpAr': 'إجراء حكيم؛ تساقط الحجارة الصغرى ينبئ بانهيار صخري أكبر كلياً.',
              'safeExpEn': 'Wise step; minor rockfall precedes major mountain slope collapse.',
              'safeOutAr': 'ابتعدت عن الجرف للمحطة 2.',
              'safeOutEn': 'Moved away from cliff for Station 2.',
              'unsafeTextAr': 'التوقف التام تحت الجرف الجبلي لمعاينة القمة',
              'unsafeTextEn': 'Stop car completely under steep cliff to look up at mountain peak',
              'unsafeExpAr': 'خطأ قاتل؛ التوقف أسفل الجرف يجعلك هدفاً مباشراً للصخور الهاوية.',
              'unsafeExpEn': 'Fatal error; stopping directly under cliffs exposes car to falling boulders.',
              'unsafeOutAr': 'تعرضت لخطر تساقط الصخور.',
              'unsafeOutEn': 'Exposed car to rockfall impact.',
            },
            {
              'sitAr': 'انهارت صخرة كبيرة أمامك وغلقت الطريق. كيف تؤمن مركبتك؟',
              'sitEn': 'Large boulder collapses ahead blocking road. How to secure vehicle?',
              'hintAr': 'التوقف على مسافة أمان والرجوع للخلف إن كان المسار خلفك خالياً',
              'hintEn': 'Stop at safe distance and reverse back if path behind is clear',
              'safeTextAr': 'التوقف على مسافة أمان والرجوع للخلف بهدوء بعيداً عن منطقة الانزلاق',
              'safeTextEn': 'Stop at safe distance and carefully reverse away from landslide area',
              'safeExpAr': 'تكتيك ممتاز؛ التراجع يمنحك مسافة حماية من انزلاقات الصخور المتتابعة.',
              'safeExpEn': 'Great tactic; reversing provides buffer zone against secondary rock slides.',
              'safeOutAr': 'تراجعت لموقع آمن للمحطة 3.',
              'safeOutEn': 'Reversed to safe spot for Station 3.',
              'unsafeTextAr': 'الترجل من السيارة والمشي بجانب الصخرة المنهارة',
              'unsafeTextEn': 'Get out of car walking right next to collapsed boulder',
              'unsafeExpAr': 'خطأ؛ المنحدر الجبلي غير مستقر وقد تتدحرج صخور أخرى.',
              'unsafeExpEn': 'Error; unstable mountain slope may shed secondary heavy boulders.',
              'unsafeOutAr': 'تعرضت لخطر تساقط مجدد.',
              'unsafeOutEn': 'Exposed to secondary slides.',
            },
            {
              'sitAr': 'احتجاز الطريق الجبلي من الأمام والخلف بالصخور. كيف تتواصل مع أمن الطرق (996/911)؟',
              'sitEn': 'Trapped on mountain pass blocked both front and rear. How to call 996/911?',
              'hintAr': 'إعطاء اسم العقبة/الطريق الجبلي ورقم العمود أو الكيلومتر الدقيق',
              'hintEn': 'Provide mountain pass name, route number, and exact kilometer marker',
              'safeTextAr': 'الاتصال بـ (996 أمن الطرق) وإعطاء اسم العقبة ورقم الكيلومتر والوضعية',
              'safeTextEn': 'Call 996 Special Highway Forces giving pass name and exact KM marker',
              'safeExpAr': 'بلاغ موجه؛ يتيح توجيه جرافات الطرق وآليات الإنقاذ للموقع فوراً.',
              'safeExpEn': 'Targeted report; directs road bulldozers and rescue equipment swiftly.',
              'safeOutAr': 'أبلغت أمن الطرق للمحطة 4.',
              'safeOutEn': 'Reported location to 996 for Station 4.',
              'unsafeTextAr': 'تسلق الصخور المنهارة بالأقدام للوصول للطرف الآخر',
              'unsafeTextEn': 'Climb over loose rockfall pile on foot to reach other side',
              'unsafeExpAr': 'خطأ؛ الصخور المنهارة حادة وغير ثابتة وقد تنزلق تحت قدميك.',
              'unsafeExpEn': 'Error; loose rock rubble is unstable and can shift causing falls into ravine.',
              'unsafeOutAr': 'تعرضت للانزلاق بالصخور.',
              'unsafeOutEn': 'Slipped on loose rocks.',
            },
            {
              'sitAr': 'استمرار الأمطار وتدفق المياه عبر العقبة. كيف تحمي نفسك داخل المركبة؟',
              'sitEn': 'Rain continues with water cascading down pass. How to stay safe in car?',
              'hintAr': 'البقاء داخل المركبة مع ربط حزام الأمان وتشعيل الإضاءة والتحذير',
              'hintEn': 'Stay inside vehicle with seatbelts fastened and emergency flashers on',
              'safeTextAr': 'البقاء داخل المركبة المحصنة مع إبقاء أضواء التحذير مشتعلة وحزام الأمان مربوطاً',
              'safeTextEn': 'Remain inside cabin with seatbelts fastened and hazard lights flashing',
              'safeExpAr': 'حماية ممتازة؛ هيكل السيارة يحميك من الحصى المتناثر والمياه السطحية.',
              'safeExpEn': 'Great protection; steel car frame shields occupants from loose gravel impacts.',
              'safeOutAr': 'انتظرت بأمان للمحطة 5.',
              'safeOutEn': 'Waited safely for Station 5.',
              'unsafeTextAr': 'الخروج والجلوس على صخرة مكشوفة بالهواء الطلق',
              'unsafeTextEn': 'Exit car sitting on exposed rock in open torrential rain',
              'unsafeExpAr': 'خطأ؛ الخروج يتعرضك للصواعق والإنهاك البردي والصخور المتطايرة.',
              'unsafeExpEn': 'Error; exiting exposes body to lightning, hypothermia, and stray rock hits.',
              'unsafeOutAr': 'تعرضت للبرد والصخور.',
              'unsafeOutEn': 'Exposed to elements and gravel.',
            },
            {
              'sitAr': 'وصول جرافات أمن الطرق والدفاع المدني وتم فتح المسار. ما الخطوة النهائية؟',
              'sitEn': 'Highway safety bulldozers clear path. Final safety protocol?',
              'hintAr': 'متابعة السير ببطء خلف آليات الطرق وتجنب التجاوز حتى النزول من العقبة',
              'hintEn': 'Drive slowly behind safety escort avoiding overtaking until down mountain',
              'safeTextAr': 'متابعة السير ببطء وحذر خلف آليات أمن الطرق حتى الوصول للسهل الآمن',
              'safeTextEn': 'Follow highway patrol escort slowly until safely off mountain pass',
              'safeExpAr': 'إتمام ناجح؛ القيادة الحذرة خلف المسح تضمن سلامة الإطارات والسيارة.',
              'safeExpEn': 'Successful completion; cautious driving behind clearers prevents tire punctures.',
              'safeOutAr': 'أكملت محطات نجاة الطرق الجبلية بنجاح!',
              'safeOutEn': 'Successfully completed mountain landslide scenario!',
              'unsafeTextAr': 'التجاوز السريع بتهور فوق الحجارة المتبقية بالخط',
              'unsafeTextEn': 'Overtake clearers recklessly driving fast over remaining sharp rock debris',
              'unsafeExpAr': 'خطأ؛ الصخور الحادة تقطع الإطارات وتسبب انحراف السيارة.',
              'unsafeExpEn': 'Error; sharp rock shards slash tires causing vehicle rollover.',
              'unsafeOutAr': 'تمزقت الإطارات.',
              'unsafeOutEn': 'Tires slashed by sharp rocks.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_5',
          categoryId: 'flood',
          titleAr: 'انقطاع الكهرباء وتجمع المياه بالحوش',
          titleEn: 'Power Outage & Yard Water Accumulation',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع انقطاع الكهرباء وتراكم المياه بالمنزل.',
          descriptionEn: 'Interactive 5-station scenario for flooded yard power outages.',
          difficulty: 'سهل',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'تجمعت مياه الأمطار بكثافة بالحوش وانقطعت الكهرباء بالشقة ليلاً. ما أول خطوة؟',
              'sitEn': 'Rainwater floods yard and blackout hits home at night. First step?',
              'hintAr': 'استخدام كشاف يدوي LED وتجنب إشعال الشموع قرب التوصيلات المبتلة',
              'hintEn': 'Use LED flashlight; avoid lighting wax candles near wet sockets',
              'safeTextAr': 'استخدام كشاف يدوي آمن (LED) وفحص مصدر انقطاع الكهرباء بحذر',
              'safeTextEn': 'Use safe LED flashlight to inspect power outage origin carefully',
              'safeExpAr': 'تصرف ممتاز؛ الكشافات الجافة تمنع أخطار الحرائق والتماس الكهربائي.',
              'safeExpEn': 'Excellent response; LED lights eliminate fire and wet electrical hazards.',
              'safeOutAr': 'أضاءت المسار بالكشاف للمحطة 2.',
              'safeOutEn': 'Lit path with LED torch for Station 2.',
              'unsafeTextAr': 'إشعال شمعة مكشوفة والمشي بها قرب غطاء البيارة والمياه',
              'unsafeTextEn': 'Light open candle walking near flooded yard manholes',
              'unsafeExpAr': 'خطأ؛ الشموع المكشوفة قد تشتعل بغاز الميثان المتصاعد من البيارات.',
              'unsafeExpEn': 'Error; open flames can ignite methane gas venting from flooded septic tanks.',
              'unsafeOutAr': 'عرضت المكان لخطر اشتعال الميثان.',
              'unsafeOutEn': 'Methane gas ignition hazard.',
            },
            {
              'sitAr': 'ملاحظة شرر كهربائي من مضخة المياه بالحوش (الغطاس). كيف تؤمنها؟',
              'sitEn': 'Sparks noticed from yard water submersible pump. How to secure?',
              'hintAr': 'فصل قاطع مضخة المياه فوراً من اللوحة الرئيسية الجافة',
              'hintEn': 'Shut off water pump circuit breaker immediately from main panel',
              'safeTextAr': 'فصل قاطع مضخة المياه الخاص بها فوراً من لوحة المفاتيح الداخلية',
              'safeTextEn': 'Flip water pump dedicated breaker switch off from indoor panel',
              'safeExpAr': 'إجراء أمني حازم؛ فصل مضخة الغطاس يمنع تكهرب مياه الحوش بالكامل.',
              'safeExpEn': 'Firm safety step; isolating submersible pump prevents electrifying yard flood.',
              'safeOutAr': 'فصلت قاطع المضخة للمحطة 3.',
              'safeOutEn': 'Isolated pump breaker for Station 3.',
              'unsafeTextAr': 'الخوض في مياه الحوش بقدين حافيتين لسحب فيش المضخة',
              'unsafeTextEn': 'Wade bare-footed through flooded yard to pull pump plug',
              'unsafeExpAr': 'خطأ قاتل؛ الخوض في مياه تكهربت بالمضخة يسبب الصعق الفوري.',
              'unsafeExpEn': 'Fatal error; stepping into electrified yard water causes instant electrocution.',
              'unsafeOutAr': 'تعرضت لصعق مائي.',
              'unsafeOutEn': 'Electrocuted in yard water.',
            },
            {
              'sitAr': 'انسداد فتحات تصريف المياه بالحوش بأوراق الأشجار. كيف تنظفها بأمان؟',
              'sitEn': 'Yard drain grates clogged with tree leaves. How to clear safely?',
              'hintAr': 'ارتداء جزمة مطاطية عازلة واستخدام مكنسة خشبية لإزاحة الأوراق',
              'hintEn': 'Wear rubber boots and use wooden broom handle to push leaves away',
              'safeTextAr': 'ارتداء حذاء مطاطي مرتفع واستخدام مكنسة خشبية لإزاحة الأوراق عن الفتحة',
              'safeTextEn': 'Wear tall rubber boots and use wooden broom handle to clear leaves off grate',
              'safeExpAr': 'تكتيك ممتاز؛ الأدوات الخشبية والمطاطية تعزل أي شحنة متبقية بماء الحوش.',
              'safeExpEn': 'Great tactic; rubber boots and wooden handles insulate against stray charges.',
              'safeOutAr': 'نظفت الفتحة وسالت المياه للمحطة 4.',
              'safeOutEn': 'Cleared drain safely for Station 4.',
              'unsafeTextAr': 'إدخال يدك العارية داخل فتحة التصريف المظلمة',
              'unsafeTextEn': 'Stick bare hand deep into dark submerged drain hole',
              'unsafeExpAr': 'خطأ؛ إدخال اليد قد يعرضك للعض من زواحف ملتقطة أو جروح حادة.',
              'unsafeExpEn': 'Error; bare hand insertion risks venomous bites from washed-in reptiles.',
              'unsafeOutAr': 'تعرضت لجرح باليد.',
              'unsafeOutEn': 'Hand injury in drain.',
            },
            {
              'sitAr': 'انخفاض مستوى المياه بالحوش وتراجع المطر. كيف تعيد التيار الكهربائي؟',
              'sitEn': 'Yard water recedes and rain stops. How to safely restore power?',
              'hintAr': 'التأكد من جفاف القواطع والتوصيلات الخارجية قبل رفع القاطع',
              'hintEn': 'Verify outdoor sockets are completely dry before resetting breaker',
              'safeTextAr': 'فحص جفاف التوصيلات الخارجية واستدعاء كهربائي إن لزم قبل رفع القاطع',
              'safeTextEn': 'Inspect outdoor sockets for complete dryness before resetting main breaker',
              'safeExpAr': 'حكمة عالية؛ رفع القاطع مع وجود رطوبة بالفيش يجدد التماس والحريق.',
              'safeExpEn': 'Wise step; resetting breaker while sockets remain damp causes short circuits.',
              'safeOutAr': 'تأكدت من الجفاف للمحطة 5.',
              'safeOutEn': 'Verified dryness for Station 5.',
              'unsafeTextAr': 'رفع القاطع مباشرة والماء لا يزال يقطر على المقابس',
              'unsafeTextEn': 'Flip breaker back on immediately while water drips on sockets',
              'unsafeExpAr': 'خطأ؛ رفع القاطع على المقابس المبللة يسبب انفجار لوحة المفاتيح.',
              'unsafeExpEn': 'Error; resetting live power onto dripping sockets blows panel board.',
              'unsafeOutAr': 'حدث ماس باللوحة.',
              'unsafeOutEn': 'Panel short-circuited.',
            },
            {
              'sitAr': 'عودة الكهرباء وسلامة المنزل. ما الإجراء الوقائي للمرات القادمة؟',
              'sitEn': 'Power restored and home safe. Long-term preventive measure?',
              'hintAr': 'تركيب قاطع حماية تسريب الأرضي (ELCB / GFCI) للتوصيلات الخارجية',
              'hintEn': 'Install Ground Fault Circuit Interrupter (GFCI/ELCB) for all outdoor outlets',
              'safeTextAr': 'تركيب قواطع حماية تسريب الأرضي (GFCI) لجميع الفيش والمضخات الخارجية',
              'safeTextEn': 'Install certified GFCI/ELCB safety breakers for all outdoor pumps and plugs',
              'safeExpAr': 'إتمام كامل؛ قواطع GFCI تفصل الكهرباء في أجزاء من الثانية عند ملامسة الماء.',
              'safeExpEn': 'Complete resolution; GFCI breakers trip in milliseconds upon water contact.',
              'safeOutAr': 'أكملت محطات سلامة كهرباء الحوش بنجاح!',
              'safeOutEn': 'Successfully completed yard flood scenario!',
              'unsafeTextAr': 'ترك المقابس الخارجية مكشوفة بدون أغطية حماية من المطر',
              'unsafeTextEn': 'Leave outdoor electrical sockets exposed without waterproof covers',
              'unsafeExpAr': 'خطأ؛ عدم وجود أغطية حماية يجدد الخطر مع أول زخة مطر.',
              'unsafeExpEn': 'Error; uncovered outdoor plugs guarantee short circuits during next rain.',
              'unsafeOutAr': 'ظلت المقابس عرضة للمطر.',
              'unsafeOutEn': 'Plugs left vulnerable to rain.',
            },
          ],
        ),

        // Scenarios 6 to 9 for FLOOD...
        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_6',
          categoryId: 'flood',
          titleAr: 'نجاة وانقاذ شخص جرفه السيل بالحبال',
          titleEn: 'Rope Rescue of Torrent Swept Person',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لإنقاذ شخص يصارع جريان السيل واستخدام الحبال.',
          descriptionEn: 'Interactive 5-station scenario for rope rescue of flood victims.',
          difficulty: 'صعب',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'شاهدت شخصاً يجرفه السيل ويحاول التمسك بغصن شجرة ثابته. ما أول حركة؟',
              'sitEn': 'Person swept by flood clinging to tree branch. Immediate action?',
              'hintAr': 'الاتصال بالطوارئ (911/998) وإحضار حبل إنقاذ أو طوق طفو',
              'hintEn': 'Call 911/998 immediately; throw rope or floating tube from safe bank',
              'safeTextAr': 'الاتصال الفوري بـ (911/998) والبحث عن حبل إنقاذ أو طوق طفو قوي',
              'safeTextEn': 'Call 911/998 instantly and locate strong rescue rope or flotation ring',
              'safeExpAr': 'تصرف ممتاز؛ البلاغ الفوري يوجه فرق الغوص والإنقاذ المائي.',
              'safeExpEn': 'Excellent step; early call dispatches trained water rescue divers.',
              'safeOutAr': 'أبلغت الطوارئ وأحضرت الحبل للمحطة 2.',
              'safeOutEn': 'Called 911 and secured rope for Station 2.',
              'unsafeTextAr': 'القفز في السيل الجارف بالملابس العادية لسباحة نحو المصاب',
              'unsafeTextEn': 'Jump directly into violent floodwater to swim out to victim',
              'unsafeExpAr': 'خطأ قاتل؛ السباحة في السيل الجارف تسبب انجرافك وغرقك مع المصاب.',
              'unsafeExpEn': 'Fatal mistake; jumping into torrent sweeps helper away creating 2 victims.',
              'unsafeOutAr': 'انجرفت مع السيل.',
              'unsafeOutEn': 'Swept away by torrent.',
            },
            {
              'sitAr': 'كيف تثبت نفسك على الضفة الصلبة قبل رمي الحبل للمصاب؟',
              'sitEn': 'How to anchor yourself on safe shoreline before throwing rope?',
              'hintAr': 'ربط طرف الحبل بشجرة كبيرة أو سيارة متوقفة وقوفاً تاماً',
              'hintEn': 'Anchor rope end to a sturdy tree or heavy parked car frame',
              'safeTextAr': 'ربط طرف الحبل بشجرة ضخمة أو هيكل سيارة ثقيلة متوقفة كمركاز أمان',
              'safeTextEn': 'Anchor end of rope securely to large tree trunk or heavy parked truck frame',
              'safeExpAr': 'تكتيك احترافي؛ التثبيت يمنع سحبك لداخل السيل عند إمساك المصاب بالحبل.',
              'safeExpEn': 'Pro tactic; strong anchor prevents helper from getting dragged into river.',
              'safeOutAr': 'ثبّت الحبل كمركاز للمحطة 3.',
              'safeOutEn': 'Anchored rope safely for Station 3.',
              'unsafeTextAr': 'الإمساك بالحبل بيديك العاريتين وأنت واقف على طين أملس',
              'unsafeTextEn': 'Hold rope with bare hands standing on slippery mud edge',
              'unsafeExpAr': 'خطأ؛ اندفاع جرف المصاب مع الحبل يسحبك فوراً لطين السيل.',
              'unsafeExpEn': 'Error; victim pull force will instantly drag helper off mud bank.',
              'unsafeOutAr': 'انزلقت في مجرى السيل.',
              'unsafeOutEn': 'Slipped into water.',
            },
            {
              'sitAr': 'كيف ترمي الحبل للمصاب المحتجز بالشجرة بأعلى كفاءة؟',
              'sitEn': 'How to throw rope efficiently to victim trapped on tree?',
              'hintAr': 'رمي الحبل متجاوزاً جسد المصاب بقليل (Upstream) ليمسكه مع جريان الماء',
              'hintEn': 'Throw rope slightly upstream across victim body so current carries it into hands',
              'safeTextAr': 'رمي الحبل فوق اتجاه التيار بقليل (Upstream) ليصل ليد المصاب مع الماء',
              'safeTextEn': 'Cast rope slightly upstream of victim so water current pushes line into hands',
              'safeExpAr': 'رمية هندسية رائعة؛ جريان المياه يدفع حبل الإنقاذ لحضن المصاب تلقائياً.',
              'safeExpEn': 'Great casting physics; current carries rope line right into victim grasp.',
              'safeOutAr': 'أمسك المصاب بالحبل للمحطة 4.',
              'safeOutEn': 'Victim caught rope for Station 4.',
              'unsafeTextAr': 'رمي الحبل خلف اتجاه السيل بعيداً عن متناول يد المصاب',
              'unsafeTextEn': 'Throw rope far downstream behind victim back',
              'unsafeExpAr': 'خطأ؛ رمي الحبل خلف الاتجاه يجعله يبتعد فوراً مع جريان التيار.',
              'unsafeExpEn': 'Error; throwing downstream floats rope away from victim reach.',
              'unsafeOutAr': 'ابتعد الحبل عن المصاب.',
              'unsafeOutEn': 'Rope floated out of reach.',
            },
            {
              'sitAr': 'أمسك المصاب بالحبل. كيف توجهه لسحبه نحو الضفة بأمان؟',
              'sitEn': 'Victim gripped rope. How to guide them as you pull to shore?',
              'hintAr': 'توجيهه للاستلقاء على ظهره ورجليه للأمام لحماية رأسه من الصخور',
              'hintEn': 'Instruct victim to float on back with feet pointed downstream protecting head',
              'safeTextAr': 'الصرخ للمصاب بالاستلقاء على ظهره وتوجيه قدميه للأمام لسحبه ببطء',
              'safeTextEn': 'Instruct victim to float on back with feet pointing downstream while pulling in',
              'safeExpAr': 'وضعية إنقاذ مائي عالمية؛ القدمان المرفوعتان تصدان الصخور وتمنعان صدم الرأس.',
              'safeExpEn': 'Universal water rescue posture; feet-first back float deflects rocks protecting head.',
              'safeOutAr': 'سحبت المصاب للضفة للمحطة 5.',
              'safeOutEn': 'Pulled victim to bank for Station 5.',
              'unsafeTextAr': 'سحب المصاب وهو يسبح على بطنه وجهه لأسفل الماء',
              'unsafeTextEn': 'Yank victim violently face down in water',
              'unsafeExpAr': 'خطأ؛ السحب ووجه المصاب بالماء يسببت الغرق وابتلاع كميات مياه ضخمة.',
              'unsafeExpEn': 'Error; pulling face-down victim causes water ingestion and asphyxiation.',
              'unsafeOutAr': 'ابتلع المصاب مياه السيل.',
              'unsafeOutEn': 'Victim ingested torrent water.',
            },
            {
              'sitAr': 'وصول المصاب للشاطئ بأمان وتواجد فرقة الهلال الأحمر (997). ما الخطوة النهائية؟',
              'sitEn': 'Victim reaches shore safe; 997 paramedics present. Final step?',
              'hintAr': 'تسليم المصاب للمسعفين لفحص الرئتين من الغرق الثانوي (Secondary Drowning)',
              'hintEn': 'Hand victim to paramedics to check for secondary drowning and hypothermia',
              'safeTextAr': 'تسليم المصاب فوراً لطاقم الإسعاف لفحص الأكسجين وتجنب الغرق الثانوي',
              'safeTextEn': 'Hand victim over to 997 paramedics for oxygen status and secondary drowning check',
              'safeExpAr': 'إتمام ناجح؛ الغرق الثانوي قد يظهر بعد ساعات من النجاة إذا دخلت مياه للرئتين.',
              'safeExpEn': 'Successful completion; secondary drowning can strike hours later if water entered lungs.',
              'safeOutAr': 'أكملت محطات إنقاذ الغريق بالحبال بنجاح!',
              'safeOutEn': 'Successfully completed rope rescue scenario!',
              'unsafeTextAr': 'السماح للمصاب بالمغادرة لمنازله فوراً دون فحص طبي',
              'unsafeTextEn': 'Allow victim to walk home immediately without medical exam',
              'unsafeExpAr': 'خطأ؛ إغفال الفحص ينطوي على خطورة الغرق الثانوي والسوائل الرئوية.',
              'unsafeExpEn': 'Error; skipping medical check risks fatal delayed pulmonary edema.',
              'unsafeOutAr': 'تعرض المصاب لمضاعفات رئوية.',
              'unsafeOutEn': 'Victim suffered lung complications.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_7',
          categoryId: 'flood',
          titleAr: 'محاصرة السيول لكشتة برية في الوادي',
          titleEn: 'Wadi Torrent Trap During Desert Camping',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات لتخليص مخيم بري محاصر بالسيول المفاجئة.',
          descriptionEn: 'Interactive 5-station scenario for flooded campsite emergencies.',
          difficulty: 'متوسط',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'أثناء الكشتة بالوادي انبعث صوت هدير مرتفع من أعلى المجرى. ما أول حركة؟',
              'sitEn': 'Roaring sound heard upstream while camping in wadi. Immediate step?',
              'hintAr': 'ترك الخيام والأغراض والصعود الفوري لقمة الجبل أو الضفة المرتفعة',
              'hintEn': 'Abandon tents/gear immediately and scramble up high rocky ridge',
              'safeTextAr': 'ترك الخيام والأمتعة فوراً والصعود الجماعي لأعلى ضفة صخرية مرتفعة',
              'safeTextEn': 'Abandon tents and equipment instantly scrambling up nearest high rocky ridge',
              'safeExpAr': 'استجابة حاسمة؛ هدير السيل المنقول يعني وصول مياه جارفة خلال ثوانٍ.',
              'safeExpEn': 'Decisive action; roaring sound signals flash flood wave arriving in seconds.',
              'safeOutAr': 'صعدت للضفة المرتفعة للمحطة 2.',
              'safeOutEn': 'Scrambled up high ridge for Station 2.',
              'unsafeTextAr': 'بدء فك الخيمة وتفكيك أدوات الشواء وحزم العزبة',
              'unsafeTextEn': 'Start dismantling tents and packing up camp stoves slowly',
              'unsafeExpAr': 'خطأ قاتل؛ إضاعة الوقت في حزم التجهيزات يعرضك لمداهمة موجة السيل.',
              'unsafeExpEn': 'Fatal error; wasting time packing camp gear gets you swept by flood surge.',
              'unsafeOutAr': 'داهم السيل المخيم.',
              'unsafeOutEn': 'Flood wave engulfed campsite.',
            },
            {
              'sitAr': 'وصلت مياه السيل واجتاحت موقع الخيام وجرفت السيارات المحذية. كيف تؤمن المجموعة؟',
              'sitEn': 'Flood wave hits campsite sweeping cars. How to keep group safe on ridge?',
              'hintAr': 'التجمع في نقطة صلبة بعيدة عن أطراف الجرف الترابي المنزلق',
              'hintEn': 'Gather group on solid rock point away from eroding dirt cliff edges',
              'safeTextAr': 'إبعاد الجميع عن أطراف الجرف الترابي والتجمع فوق صخرة صلبة متماسكة',
              'safeTextEn': 'Move group back from eroding dirt edges onto solid bedrock formation',
              'safeExpAr': 'تكتيك ممتاز؛ مياه السيل تآكل أطراف الجرف الترابي وتسبب انهيارها.',
              'safeExpEn': 'Great safety step; torrential floodwaters undercut and collapse dirt banks.',
              'safeOutAr': 'تجمعت المجموعة على الصخرة للمحطة 3.',
              'safeOutEn': 'Gathered on solid rock for Station 3.',
              'unsafeTextAr': 'الوقوف على حافة الطين المنهارة لالتقاط مقاطع فيديو',
              'unsafeTextEn': 'Stand right on crumbling mud cliff edge filming videos',
              'unsafeExpAr': 'خطأ؛ حافة الجرف الترابي تنهدم فجأة تحت الأقدام.',
              'unsafeExpEn': 'Error; dirt cliff edges collapse suddenly plunging bystanders into torrent.',
              'unsafeOutAr': 'انهارت الحافة الترابية.',
              'unsafeOutEn': 'Cliff edge collapsed.',
            },
            {
              'sitAr': 'انقطاع الاتصال وقدم الليل والمجموعة محاصرة فوق الهضبة. كيف تشعل إشارة استغاثة؟',
              'sitEn': 'Night falls; group trapped on ridge with no cell service. Signal method?',
              'hintAr': 'إشعال نار استغاثة ثلاثية في مكان مرتفع وآمن أو استخدام كشافات الجوال',
              'hintEn': 'Light 3 signal fires on high rock or flash mobile torches in SOS rhythm',
              'safeTextAr': 'استخدام الكشافات وإشعال نار استغاثة على أرض صخرية جافة لجذب فرق البحث',
              'safeTextEn': 'Flash LED torches and light a safe elevated signal fire to mark position',
              'safeExpAr': 'إشارات استغاثة معتمدة؛ النار والكشافات بالليل تسهم في رصدك بالطائرات.',
              'safeExpEn': 'Standard wilderness SOS; fire and torch flashes are easily spotted by rescue aircraft.',
              'safeOutAr': 'أرسلت إشارات الاستغاثة للمحطة 4.',
              'safeOutEn': 'Signaled position for Station 4.',
              'unsafeTextAr': 'النزول في الظلام وحشو المياه للبحث عن الطريق',
              'unsafeTextEn': 'Climb down into dark floodwaters attempting to walk home',
              'unsafeExpAr': 'خطأ؛ النزول في السيل ليلاً انتحار محقق بسبب الحفر والعوائق.',
              'unsafeExpEn': 'Error; entering dark floodwaters at night is fatal due to hidden drop-offs.',
              'unsafeOutAr': 'تعرضت للسقوط بالمياه.',
              'unsafeOutEn': 'Fell into dark rushing water.',
            },
            {
              'sitAr': 'وصول طائرات الأمن وإنجاد الدفاع المدني (911). كيف تسهل عملية الإنزال؟',
              'sitEn': 'Civil Defense helicopter arrives overhead (911). How to aid winch descent?',
              'hintAr': 'إخلاء مساحة مسطحة من الحجارة السائبة والجلوس هادئين أثناء هبوط المنقذ',
              'hintEn': 'Clear flat landing spot of loose debris and sit calmly as paramedic winches down',
              'safeTextAr': 'إخلاء مساحة صخرية من الحجارة السائبة والجلوس بهدوء لتأمين إنزال المنقذ',
              'safeTextEn': 'Clear loose stones from flat rock and sit calmly as rescue swimmer winches down',
              'safeExpAr': 'تنسيق جوي رائع؛ هواء مروحة الطائرة قد يطير الحجارة والخيام الخفيفة.',
              'safeExpEn': 'Great air coordination; rotor wash blows loose gravel and debris violently.',
              'safeOutAr': 'هبط المنقذ للمحطة 5.',
              'safeOutEn': 'Rescuer winched down for Station 5.',
              'unsafeTextAr': 'الوقوف والركض نحو حبل الطائرة قبل وصول المنقذ',
              'unsafeTextEn': 'Run recklessly toward helicopter cable before rescuer touches ground',
              'unsafeExpAr': 'خطأ؛ الاندفاع نحو حبل الطائرة يسبب اختلال توازن الكيبل والوقوع.',
              'unsafeExpEn': 'Error; grabbing cable prematurely sways winch line risking fall from height.',
              'unsafeOutAr': 'اختل توازن حبل الإنزال.',
              'unsafeOutEn': 'Winch cable swayed dangerously.',
            },
            {
              'sitAr': 'تم إخلاء جميع أفراد الكشتة بالطائرة لنقطة الأمان. ما الخطوة النهائية؟',
              'sitEn': 'All campers airlifted safely to staging area. Final safety step?',
              'hintAr': 'مراجعة كشوفات الأسماء والإبلاغ عن سلامة الجميع وتلقي الرعاية الطبية',
              'hintEn': 'Complete roster headcount and undergo Red Crescent medical screening',
              'safeTextAr': 'إجراء التقييم الطبي الشامل وإبلاغ الأهل بسلامة جميع أفراد رحلة الكشتة',
              'safeTextEn': 'Undergo complete 997 paramedic exam and inform family of complete rescue',
              'safeExpAr': 'إتمام ناجح؛ التثبت الطبي والإبلاغ ينهي عمليات البحث والإنقاذ الميدانية.',
              'safeExpEn': 'Successful resolution; medical check and notification closes search operation.',
              'safeOutAr': 'أكملت محطات إخلاء الكشتة بنجاح!',
              'safeOutEn': 'Successfully completed campsite flood scenario!',
              'unsafeTextAr': 'الانصراف الفوري دون إبلاغ غرفة العمليات بسلامة المحاصرين',
              'unsafeTextEn': 'Depart area immediately without confirming complete headcount to command',
              'unsafeExpAr': 'خطأ؛ عدم الإبلاغ قد يجعل الفرق تستمر بالبحث عن أسماء مفقودة وهمية.',
              'unsafeExpEn': 'Error; missing headcount forces search teams to risk lives looking for phantom missing.',
              'unsafeOutAr': 'استمر البحث الميداني بالخطأ.',
              'unsafeOutEn': 'Search continued needlessly.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_8',
          categoryId: 'flood',
          titleAr: 'انسداد فتحات الصرف بالسطح وتسرب السقف',
          titleEn: 'Rooftop Drain Blockage & Ceiling Leak',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع تجمع مياه الأمطار بالسطح وتأمين الأسقف.',
          descriptionEn: 'Interactive 5-station scenario for rooftop drainage and ceiling water leaks.',
          difficulty: 'سهل',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'انسدت فتحات صرف المطر بالسطح وتحول السطح لبحيرة مياه بدأت بالتسرب للشقة. ما أول حركة؟',
              'sitEn': 'Rooftop drains clog creating deep pool leaking into top floor ceiling. Action?',
              'hintAr': 'فصل قاطع الكهرباء العلوي للشقة قبل الصعود لتنظيف فتحة السطح',
              'hintEn': 'Shut top floor main electric breaker before going up to clear roof drains',
              'safeTextAr': 'فصل قاطع الكهرباء للشقة العلوية فوراً لمنع التماس مع مياه السقف المتسربة',
              'safeTextEn': 'Shut top floor apartment electrical breaker instantly to prevent ceiling leaks shorts',
              'safeExpAr': 'تصرف ممتاز؛ مياه السقف المتسربة للمصابيح تسبب ماساً كهربائياً خطيراً.',
              'safeExpEn': 'Excellent response; water leaking through light fixtures causes severe short circuits.',
              'safeOutAr': 'فصلت الكهرباء عن السقف للمحطة 2.',
              'safeOutEn': 'Isolated top floor electrics for Station 2.',
              'unsafeTextAr': 'لمس المفاتيح الكهربائية تحت السقف الذي ينقط ماء',
              'unsafeTextEn': 'Toggle light switches directly underneath dripping ceiling leak',
              'unsafeExpAr': 'خطأ؛ لمس مفاتيح الإضاءة مع تسرب الماء يسبب الصعق المباشر.',
              'unsafeExpEn': 'Error; touching light switches under active water leaks causes electrocution.',
              'unsafeOutAr': 'تعرضت للصعق الكهربائي.',
              'unsafeOutEn': 'Electrocuted by wet switch.',
            },
            {
              'sitAr': 'الصعود للسطح لتسليك المزراب الصافي. كيف تتحرك بحذر على السطح المبلل؟',
              'sitEn': 'Going up to roof to unclog drain pipe. How to tread safely on wet roof?',
              'hintAr': 'ارتداء حذاء مانع للانزلاق والتنقل بحذر بعيداً عن حواف السطح المنخفضة',
              'hintEn': 'Wear anti-slip rubber shoes and tread carefully away from low parapets',
              'safeTextAr': 'ارتداء حذاء مطاطي مانع للانزلاق والتنقل بحذر نحو فتحة المزراب',
              'safeTextEn': 'Wear anti-slip rubber boots and tread carefully toward clogged drain outlet',
              'safeExpAr': 'تكتيك أمان سليم؛ بلاط السطح المبلل يصبح شديد الانزلاق كالجلبد.',
              'safeExpEn': 'Correct safety tactic; wet roof tiles become extremely slippery.',
              'safeOutAr': 'وصلت لفتحة المزراب للمحطة 3.',
              'safeOutEn': 'Reached drain outlet safely for Station 3.',
              'unsafeTextAr': 'الركض حافياً على بلاط السطح الزلق',
              'unsafeTextEn': 'Run barefoot across wet slippery roof tiles',
              'unsafeExpAr': 'خطأ؛ الركض حافياً يسبب الانزلاق والسقوط من أعلى السطح.',
              'unsafeExpEn': 'Error; running barefoot on wet tiles causes severe slips and falls off roof edge.',
              'unsafeOutAr': 'انزلقت على بلاط السطح.',
              'unsafeOutEn': 'Slipped on wet roof tiles.',
            },
            {
              'sitAr': 'وجدة فتحة الصرف مسدودة بالأكياس والقمامة. كيف تسلكها؟',
              'sitEn': 'Drain grate blocked with plastic bags and debris. How to unclog?',
              'hintAr': 'إزاحة العائق بعصا أو جرافة يدوية ودفع الأكياس للخارج',
              'hintEn': 'Clear debris using wooden stick or hand trowel; pull plastic bags out',
              'safeTextAr': 'استخدام أداة يدوية لإزاحة العوالق والأكياس عن المزراب حتى تنحدر المياه',
              'safeTextEn': 'Use hand tool to pull away plastic bags and debris letting water flow down drain',
              'safeExpAr': 'تسليك رائع؛ فتح المزراب يفرغ البحيرة المتراكمة ويوقف الضغط على السقف.',
              'safeExpEn': 'Great clearing; opening drain empties ponded water stopping ceiling load.',
              'safeOutAr': 'انحدرت المياه بالمزراب للمحطة 4.',
              'safeOutEn': 'Drain opened; water flowed for Station 4.',
              'unsafeTextAr': 'دفع الأكياس والقمامة لداخل أنبوب الصرف بقوة',
              'unsafeTextEn': 'Shove plastic bags deep into downspout pipe',
              'unsafeExpAr': 'خطأ؛ دفع الأكياس للداخل يسبب انسداداً كاملاً داخل الأنابيب الجدارية.',
              'unsafeExpEn': 'Error; pushing trash inside downspouts blocks internal pipes completely.',
              'unsafeOutAr': 'انسد الأنبوب الداخلي.',
              'unsafeOutEn': 'Internal downspout pipe blocked.',
            },
            {
              'sitAr': 'نزول المياه للشقة وتأثر الديكور والجبس. كيف تحمي الغرفة تحت التسرب؟',
              'sitEn': 'Water leaked into apartment damaging drywall. How to shield room?',
              'hintAr': 'وضع أوعية واسعة تحت نقاط التسرب ونقل الأثاث والأجهزة بعيداً',
              'hintEn': 'Place buckets beneath drip points and move electronics/furniture away',
              'safeTextAr': 'وضع أواني وأوعية بلاستيكية تحت نقاط النقط ونقل الأجهزة الكهربائية بعيداً',
              'safeTextEn': 'Position plastic buckets under active drip spots and move electronics away',
              'safeExpAr': 'حماية ممتازة؛ تجميع المياه يمنع اتلاف السجاد والأرضيات الخشبية.',
              'safeExpEn': 'Superb protection; collecting drips prevents ruining flooring and furniture.',
              'safeOutAr': 'حميت الأثاث والأجهزة للمحطة 5.',
              'safeOutEn': 'Shielded electronics for Station 5.',
              'unsafeTextAr': 'ترك الأجهزة الكهربائية تحت السقف الذي ينقط ماء',
              'unsafeTextEn': 'Leave TVs and computers directly under ceiling water drips',
              'unsafeExpAr': 'خطأ؛ نزول الماء داخل الأجهزة يسبب تلفها الكلي وتجدد الماس.',
              'unsafeExpEn': 'Error; water entering electronics destroys components causing short circuits.',
              'unsafeOutAr': 'تلف التلفزيون والأجهزة.',
              'unsafeOutEn': 'TV and electronics destroyed.',
            },
            {
              'sitAr': 'توقف المطر وجفاف السطح. ما الإجراء الوقائي الدائم؟',
              'sitEn': 'Rain stops and roof dries out. Permanent preventive action?',
              'hintAr': 'تنظيف فتحات الصرف دورياً قبل موسم الأمطار وتطبيق عزل مائي (صوف/عازل بولي يوريثان)',
              'hintEn': 'Clean roof drains regularly before rain season and apply waterproof coating',
              'safeTextAr': 'تنظيف مزاريب السطح دورياً وتطبيق طبقة عازل مائي معتمد على بلاط السطح',
              'safeTextEn': 'Clean roof drains regularly before winter and apply certified waterproof sealant',
              'safeExpAr': 'إتمام تام؛ العزل المائي والصيانة الدورية تضمن حماية المبنى طوال العام.',
              'safeExpEn': 'Complete resolution; waterproofing coating and maintenance prevent leaks permanently.',
              'safeOutAr': 'أكملت محطات سلامة صرف السطح بنجاح!',
              'safeOutEn': 'Successfully completed roof leak scenario!',
              'unsafeTextAr': 'إهمال السطح وترك المزاريب دون شبك حماية من الأشجار',
              'unsafeTextEn': 'Neglect roof maintenance leaving drains without protective mesh screens',
              'unsafeExpAr': 'خطأ؛ عدم وجود شبك حماية يجدد انسداد الصرف مع أول عاصفة.',
              'unsafeExpEn': 'Error; missing drain mesh guarantees immediate clogging during next storm.',
              'unsafeOutAr': 'تجدد انسداد السطح.',
              'unsafeOutEn': 'Roof drain clogged again next rain.',
            },
          ],
        ),

        ScenarioBuilder.build5StationScenario(
          id: 'sc_flood_9',
          categoryId: 'flood',
          titleAr: 'خروج ذباب وشرر الكهرباء مع مياه الأمطار',
          titleEn: 'Rainwater Flooding Outdoor Electrical Junction Box',
          descriptionAr: 'سيناريو تفاعلي من 5 محطات للتعامل مع غرق العدادات والقواطع الخارجية.',
          descriptionEn: 'Interactive 5-station scenario for outdoor meter box water flooding.',
          difficulty: 'صعب',
          icon: 'water',
          colorHex: 0xFF0288D1,
          stations: [
            {
              'sitAr': 'غمرت مياه الأمطار صندوق العداد الكهربائي الخارجي وانبعث منه صوت شرر ورائحة. ما التصرف؟',
              'sitEn': 'Rainwater floods outdoor electric meter box sparking with crackling sound. Action?',
              'hintAr': 'الابتعاد الفوري عن صندوق العداد وعدم لمس السور الخارجي للمنزل',
              'hintEn': 'Keep clear of meter box immediately; do NOT touch metal yard perimeter fence',
              'safeTextAr': 'الابتعاد الفوري مسافة 5 أمتار على الأقل وتنبيه المارة بعدم الاقتراب من السور',
              'safeTextEn': 'Keep at least 5 meters away immediately and warn passersby away from fence',
              'safeExpAr': 'تصرف ممتاز؛ العداد المغمور قد يكهرب السور الحديدي الخارجي بالكامل.',
              'safeExpEn': 'Excellent safety step; flooded live meter boxes electrify metal boundary fences.',
              'safeOutAr': 'ابتعدت وحذرت المارة للمحطة 2.',
              'safeOutEn': 'Kept clear and warned others for Station 2.',
              'unsafeTextAr': 'الاقتراب وفتح باب العداد بيديك بلمس المفصلات المعدنية',
              'unsafeTextEn': 'Approach meter box barehanded opening metal door to check sparks',
              'unsafeExpAr': 'خطأ قاتل؛ لمس العداد المدموج بالمياه يسبب الصعق بالتيار الجهد العالي.',
              'unsafeExpEn': 'Fatal error; touching flooded high-voltage meter box causes instant electrocution.',
              'unsafeOutAr': 'تعرضت لصعق الجهد العالي.',
              'unsafeOutEn': 'High-voltage electrocution.',
            },
            {
              'sitAr': 'الاتصال السريع بالطوارئ الرسمية. أي رقم تطلب لهذه الحالة؟',
              'sitEn': 'Calling official emergency services. Which number to dial for electric meter fire?',
              'hintAr': 'الاتصال بطوارئ الكهرباء (933) والدفاع المدني (998/911)',
              'hintEn': 'Dial SEC Emergency (933) and Saudi Civil Defense (998/911)',
              'safeTextAr': 'الاتصال بطوارئ الكهرباء (933) والدفاع المدني (998) وإعطاء رقم الحساب/الموقع',
              'safeTextEn': 'Dial SEC Emergency 933 and Civil Defense 998 providing meter number and address',
              'safeExpAr': 'بلاغ موجه؛ طوارئ 933 تملك صلاحية فصل الكابل الرئيسي من المحول الخارجي.',
              'safeExpEn': 'Targeted report; 933 emergency crews isolate main high-voltage street transformers.',
              'safeOutAr': 'أبلغت 933 و998 للمحطة 3.',
              'safeOutEn': 'Reported to 933 & 998 for Station 3.',
              'unsafeTextAr': 'محاولة رش العداد بطفاية ماء منزلية',
              'unsafeTextEn': 'Try spraying electric meter box with garden water hose',
              'unsafeExpAr': 'خطأ كوارثي؛ رش الماء على الجهد العالي يسبب انفجاراً وتكهرب خط الماء.',
              'unsafeExpEn': 'Catastrophic error; spraying water onto high voltage arc creates fatal electrical shock.',
              'unsafeOutAr': 'حدث انفجار كهربائي.',
              'unsafeOutEn': 'High voltage short circuit explosion.',
            },
            {
              'sitAr': 'تراكم مياه الأمطار حول السور وتدفقها نحو الشارع. كيف تمنع وصول الناس لمحيط الخطر؟',
              'sitEn': 'Rainwater pooling around fence flowing onto sidewalk. How to block access?',
              'hintAr': 'وضع شريط تحذيري أو أواني وشواخص لمنع مرور الأطفال والمارة',
              'hintEn': 'Set up warning markers or chairs to block pedestrian path near electrified water',
              'safeTextAr': 'وضع حواجز وشواخص مؤقتة لمنع مشاة الشارع والأطفال من الخوض في المياه',
              'safeTextEn': 'Set up temporary chairs/warning markers to block pedestrians from walking in water',
              'safeExpAr': 'إجراء وقائي رائع؛ يمنع صعق المارة بالماء المكهرب حتى وصول الفرق.',
              'safeExpEn': 'Great safety barrier; prevents public electrocution in electrified puddles.',
              'safeOutAr': 'وضعت حواحز الأمان للمحطة 4.',
              'safeOutEn': 'Set up safety boundary for Station 4.',
              'unsafeTextAr': 'ترك المكان ومغادرته دون وضع أي شواخص تحذيرية',
              'unsafeTextEn': 'Walk away leaving electrified water puddle completely open',
              'unsafeExpAr': 'خطأ؛ ترك الماء المكهرب يعرض الأطفال والمارة للخطر الصعق.',
              'unsafeExpEn': 'Error; leaving electrified puddle open risks drowning/electrocution of kids.',
              'unsafeOutAr': 'تعرض طفل لخطر الماء المكهرب.',
              'unsafeOutEn': 'Pedestrian exposed to electrified water.',
            },
            {
              'sitAr': 'وصول فرقة صيانة شركة الكهرباء (933). كيف تسلمهم الموقع؟',
              'sitEn': 'SEC emergency technician crew arrives (933). How to report handoff?',
              'hintAr': 'إبلاغ الفني بصوت الشرر ومسار تدفق المياه وحالة العداد الخارجي',
              'hintEn': 'Inform technician of arc sounds, water flow path, and meter box status',
              'safeTextAr': 'توجيه فني الكهرباء لمكان العداد وإبلاغه بمسار تسرب مياه المطر داخل الصندوق',
              'safeTextEn': 'Guide SEC technician to meter box explaining water ingress point and arc noise',
              'safeExpAr': 'تسليم احترافي؛ يساعد الفني على قطع التيار من الكابينة الرئيسية فوراً.',
              'safeExpEn': 'Pro handoff; empowers SEC tech to isolate street junction feed safely.',
              'safeOutAr': 'سلمت الموقع للفني للمحطة 5.',
              'safeOutEn': 'Handed off site to tech for Station 5.',
              'unsafeTextAr': 'الاندفاع والتدخل في عمل الفني ومحاولة فتح العداد معه',
              'unsafeTextEn': 'Interfere with technician work trying to touch meter panel',
              'unsafeExpAr': 'خطأ؛ الفني يرتدي قفازات عازلة 10,000 فولت واللمس يعرضك للخطر.',
              'unsafeExpEn': 'Error; technicians wear 10,000V rated safety gear; unequipped touch is fatal.',
              'unsafeOutAr': 'تدخلت بالعمل الفني.',
              'unsafeOutEn': 'Interfered with high voltage repair.',
            },
            {
              'sitAr': 'تم فصل الكهرباء واستبدال العداد وإغلاقه بإحكام. ما المعيار الوقائي الدائم؟',
              'sitEn': 'Power isolated, meter replaced with IP65 waterproof seal. Final step?',
              'hintAr': 'التأكد من تركيب غطاء عازل مقاوم للمياه (IP65) ورفع العداد فوق مستوى السيول',
              'hintEn': 'Ensure IP65 waterproof rated meter enclosure and elevate box above flood line',
              'safeTextAr': 'التأكد من إغلاق العداد بغطاء عازل للأمطار (IP65) وتأمين إحكام الإغلاق',
              'safeTextEn': 'Ensure meter box is fitted with certified IP65 waterproof enclosure door',
              'safeExpAr': 'إتمام تام؛ أغطية IP65 تمنع دخول مياه الأمطار والسيول للوصلات الداخلية.',
              'safeExpEn': 'Complete resolution; IP65 rated enclosures block rain and flood ingress permanently.',
              'safeOutAr': 'أكملت محطات سلامة العداد الخارجي بنجاح!',
              'safeOutEn': 'Successfully completed meter box flood scenario!',
              'unsafeTextAr': 'ترك العداد بدون غطاء حماية مفصلي',
              'unsafeTextEn': 'Leave meter box door unlatched without rain seal gasket',
              'unsafeExpAr': 'خطأ؛ ترك العداد دون غطاء يجدد خروج الشرر مع المطر القادم.',
              'unsafeExpEn': 'Error; unsealed meter boxes spark and short circuit during next rainfall.',
              'unsafeOutAr': 'تجدد الخطر مع المطر.',
              'unsafeOutEn': 'Meter sparked again next rainstorm.',
            },
          ],
        ),
      ];
}
