import sys

code = """
        // ---------------- HOME (4 to 9) ----------------
        Scenario(
          id: 'sc_home_4',
          categoryId: 'home',
          titleAr: 'انتشار رائحة الغاز بالمطبخ عند الاستيقاظ فجراً',
          titleEn: 'Kitchen Gas Leak Discovered at Dawn',
          descriptionAr: 'استيقظت فجراً على رائحة غاز نفاذة تنتشر في الصالة والمطبخ.',
          descriptionEn: 'Waking up at dawn to strong LPG gas smell filling kitchen and living room.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'home',
          colorHex: 0xFF43A047,
          steps: [
            ScenarioStep(
              id: 'step_hm4_1',
              scenarioId: 'sc_home_4',
              stepOrder: 1,
              situationAr: 'رائحة الغاز قوية جداً والمطبخ مغلق. ما أول حركة تقوم بها فوراً؟',
              situationEn: 'Gas smell is intense inside house. What is your immediate first action?',
              visualTheme: 'home',
              hintAr: 'إغلاق صمام الغاز وفتح النوافذ دون إشعال أي مفتاح كهربائي',
              hintEn: 'Shut gas valve and open windows without flipping electric switches',
              options: [
                ScenarioOption(
                  id: 'opt_hm4_1_a',
                  stepId: 'step_hm4_1',
                  textAr: 'إغلاق محبس الأسطوانة الرئيسي فوراً، وفتح جميع النوافذ والأبواب للتهوية دون لمس الإضاءة',
                  textEn: 'Shut main cylinder valve immediately, open all windows for ventilation without touching light switches',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الصحيح؛ إغلاق مصدر الغاز والتهوية الطبيعية يمنع الانفجار، وحظر الإضاءة يمنع الشرر.',
                  explanationEn: 'Correct procedure; closing valve and natural venting clears gas safely without electric spark risk.',
                  consequenceAr: 'تبدد الغاز المتسرب وسلِم المنزل من خطر الاشتعال.',
                  consequenceEn: 'Leaked gas dissipated safely avoiding explosion hazard.',
                ),
                ScenarioOption(
                  id: 'opt_hm4_1_b',
                  stepId: 'step_hm4_1',
                  textAr: 'تشغيل مروحة الشفط والإضاءة لرؤية مصدر التسرب',
                  textEn: 'Turn on exhaust fan and kitchen light to locate leak source',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الشرر الكهربائي الصادر من المفتاح يسبب انفجار غازي لحظي بالمطبخ.',
                  explanationEn: 'Dangerous; electric arc spark from switch causes instant explosive gas ignition.',
                  consequenceAr: 'حدثت شرارة كهربائية وانفجار غازي بالمطبخ.',
                  consequenceEn: 'Electric spark ignited gas causing kitchen explosion.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_home_5',
          categoryId: 'home',
          titleAr: 'انسداد مصارف الأسقف وارتفاع منسوب المياه بالداخل',
          titleEn: 'Roof Drain Clogging & Indoor Ceiling Leakage',
          descriptionAr: 'خلال عاصفة مطرية، انسدت مصارف السطح وبدأت المياه تتسرب وتتقاطر بغزارة من أسقف الصالة فوق التوصيلات.',
          descriptionEn: 'Heavy rain clogs roof drains causing heavy water dripping through ceiling near electric fixtures.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'home',
          colorHex: 0xFF43A047,
          steps: [
            ScenarioStep(
              id: 'step_hm5_1',
              scenarioId: 'sc_home_5',
              stepOrder: 1,
              situationAr: 'المياه تنزل من السقف وتقترب من ثريا الإضاءة والأجهزة. ما التصرف الأول الوقائي؟',
              situationEn: 'Water dripping through ceiling fixtures near chandelier and TV. What is first protective action?',
              visualTheme: 'home',
              hintAr: 'افصل قاطع الكهرباء الرئيسي للحي/المنزل لحماية الأرواح',
              hintEn: 'Disengage main circuit breaker to eliminate electrocution risk',
              options: [
                ScenarioOption(
                  id: 'opt_hm5_1_a',
                  stepId: 'step_hm5_1',
                  textAr: 'فصل قاطع الكهرباء الرئيسي للمنزل فوراً، ونقل الأجهزة الكهربائية وتثبيت أوعية لجمع المياه',
                  textEn: 'Disengage main home circuit breaker immediately, move electrical items and set buckets under drips',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء آمن؛ عزل التيار يمنع الماس والتكهرب الناتج عن اختلاط الماء بأسلاك السقف.',
                  explanationEn: 'Safe procedure; cutting power prevents short circuits and electrocution from ceiling water.',
                  consequenceAr: 'تم تفادي الماس الكهربائي وحماية أفراد الأسرة.',
                  consequenceEn: 'Prevented short circuit hazard and protected family members.',
                ),
                ScenarioOption(
                  id: 'opt_hm5_1_b',
                  stepId: 'step_hm5_1',
                  textAr: 'مسح المياه المتساقطة بمنشفة مع إبقاء الإضاءة والتلفاز يعملان',
                  textEn: 'Mop floor water with towel while leaving lights and TV running',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ تسرب المياه للثريا مع وجود التيار يؤدي لتماس وصعق كهربائي للمتواجدين.',
                  explanationEn: 'Hazardous; water penetrating live ceiling fixtures causes shock and short-circuit fires.',
                  consequenceAr: 'حدث شرر وتماس كهربائي بالثريا.',
                  consequenceEn: 'Electrical short occurred in ceiling light fixture.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_home_6',
          categoryId: 'home',
          titleAr: 'سقوط مادة منظفة كيميائية حارقة على عين فرد من العائلة',
          titleEn: 'Chemical Cleaning Agent Splashed in Family Member Eye',
          descriptionAr: 'أثناء تنظيف المطبخ، انسكبت مادة منظفة قوية (فلاش/مذيب رغوي) وتناثرت في عين أحد أفراد الأسرة.',
          descriptionEn: 'Harsh chemical drain/tile cleaner splashes directly into family member eye during cleaning.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'home',
          colorHex: 0xFF43A047,
          steps: [
            ScenarioStep(
              id: 'step_hm6_1',
              scenarioId: 'sc_home_6',
              stepOrder: 1,
              situationAr: 'المصاب يصرخ من شدة حرق العين. ما الإسعاف الأولي الفوري لمنع تلف القرنية؟',
              situationEn: 'Victim screaming from intense eye burn. What is immediate first aid to save cornea?',
              visualTheme: 'home',
              hintAr: 'اغسل العين فوراً بماء صنبور جاري متواصل لمدة 15 دقيقة',
              hintEn: 'Flush eye immediately under continuous running tap water for 15 minutes',
              options: [
                ScenarioOption(
                  id: 'opt_hm6_1_a',
                  stepId: 'step_hm6_1',
                  textAr: 'غسل العين فوراً بماء صنبور جاري متواصل ونظيف لمدة لا تقل عن 15 دقيقة، والتوجه فوراً لمركز الطوارئ',
                  textEn: 'Flush eye continuously under clean running tap water for at least 15 minutes, then seek ER emergency care',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إسعاف ممتاز؛ الغسل المستمر بالماء الجاري يزيل المادة الكيميائية ويقلل حروق القرنية.',
                  explanationEn: 'Excellent first aid; continuous water flushing dilutes chemical agent protecting cornea.',
                  consequenceAr: 'تم تخفيف تركيز المادة وحماية قرنية العين من التلف.',
                  consequenceEn: 'Chemical diluted effectively preserving corneal tissue.',
                ),
                ScenarioOption(
                  id: 'opt_hm6_1_b',
                  stepId: 'step_hm6_1',
                  textAr: 'دعك العين بقوة باستخدام منديل جاف ووضع قطرة عادية دون غسل',
                  textEn: 'Rub eye vigorously with dry tissue and apply ordinary eyedrops without rinsing',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ دعك العين ينشر المادة الكيميائية داخل أنسجة العين ويضاعف تلف القرنية.',
                  explanationEn: 'Dangerous; rubbing drives corrosive chemicals deeper into corneal layers.',
                  consequenceAr: 'تفاقم الحروق وزاد التلف بالأنسجة.',
                  consequenceEn: 'Corrosive burn worsened due to mechanical rubbing.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_home_7',
          categoryId: 'home',
          titleAr: 'انكسار لوح زجاجي كبير بالصالة بفعل رياح العاصفة',
          titleEn: 'Large Window Glass Shatters from Storm Winds',
          descriptionAr: 'ضربت عاصفة رياح شديدة المنزل وتسببت بانكسار نافذة زجاجية ضخمة بالصالة وتطاير الشظايا.',
          descriptionEn: 'Severe gale force winds shatter a large living room window throwing glass fragments indoors.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'home',
          colorHex: 0xFF43A047,
          steps: [
            ScenarioStep(
              id: 'step_hm7_1',
              scenarioId: 'sc_home_7',
              stepOrder: 1,
              situationAr: 'الزجاج متناثر بالصالة والرياح تدخل بقوة. كيف تحمي العائلة من الإصابات والقطع؟',
              situationEn: 'Shattered glass scattered on floor with raging wind entering room. How to protect family?',
              visualTheme: 'home',
              hintAr: 'انقل الجميع لغرفة داخلية دون نوافذ وإغلاق الباب',
              hintEn: 'Move everyone to an interior room without windows and shut door',
              options: [
                ScenarioOption(
                  id: 'opt_hm7_1_a',
                  stepId: 'step_hm7_1',
                  textAr: 'نقل جميع أفراد العائلة فوراً لغرفة داخلية محمية (كالممر أو المطبخ الداخلي) وإغلاق الأبواب',
                  textEn: 'Evacuate all family members immediately to an interior windowless room and close doors',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ الابتعاد عن النوافذ المكسورة أثناء العواصف يمنع الإصابة بشظايا الزجاج التطايرة.',
                  explanationEn: 'Safe procedure; taking shelter in interior spaces protects occupants from flying glass shards.',
                  consequenceAr: 'تمت حماية الجميع من القطوع والشظايا المتطايرة.',
                  consequenceEn: 'Family safely sheltered away from flying glass debris.',
                ),
                ScenarioOption(
                  id: 'opt_hm7_1_b',
                  stepId: 'step_hm7_1',
                  textAr: 'الوقوف أمام النافذة المكسورة ومحاولة تثبيت كرتون مقوى بيدك أثناء الرياح',
                  textEn: 'Stand right at shattered window trying to hold cardboard against raging wind',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ ضغط الرياح وشظايا الزجاج الحادة قد تسبب جروحاً قطعية شريانية خطيرة.',
                  explanationEn: 'Dangerous; high wind pressure and razor sharp glass edges cause severe lacerations.',
                  consequenceAr: 'تطايرت شظايا زجاجية وتسببت بجروح قطعية.',
                  consequenceEn: 'Flying glass fragments caused hand and face cuts.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_home_8',
          categoryId: 'home',
          titleAr: 'سقوط طفل في مسبح المنزل وغرقه',
          titleEn: 'Child Accidental Fall into Home Swimming Pool',
          descriptionAr: 'غفل العائلة لحظات وسقط طفل في مسبح المنزل وشوهد يستقر في القاع دون حركة.',
          descriptionEn: 'Toddler wanders off into backyard and falls into home swimming pool, sinking to bottom.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'home',
          colorHex: 0xFF43A047,
          steps: [
            ScenarioStep(
              id: 'step_hm8_1',
              scenarioId: 'sc_home_8',
              stepOrder: 1,
              situationAr: 'سحبت الطفل من المسبح وهو لا يتنفس وفاقد للوعي. ما الإجراء الفوري للإسعاف؟',
              situationEn: 'Child pulled from pool non-breathing and unconscious. What is immediate first aid?',
              visualTheme: 'home',
              hintAr: 'ابدأ بالإنعاش القلبي الرئوي (CPR) فوراً بـ 5 أنفاس إنقاذ متبوعة بالضغطات الصدرية',
              hintEn: 'Start CPR immediately with 5 rescue breaths followed by 30 chest compressions; call 997',
              options: [
                ScenarioOption(
                  id: 'opt_hm8_1_a',
                  stepId: 'step_hm8_1',
                  textAr: 'الاتصال بـ 997 فوراً والبدء بإعطاء 5 أنفاس إنقاذ ثم البدء بالضغطات الصدرية (CPR) المتواصلة',
                  textEn: 'Call 997 immediately, give 5 rescue breaths then perform continuous CPR chest compressions',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء منقذ للحياة؛ الإنعاش القلبي الرئوي السريع بالأنفاس يوفر الأكسجين للدماغ ويحمي الحياة.',
                  explanationEn: 'Life-saving action; immediate CPR rescue breathing delivers vital oxygen to brain.',
                  consequenceAr: 'استعاد الطفل التهوئة واستجاب للإنعاش حتى وصول الهلال الأحمر.',
                  consequenceEn: 'Child responded to CPR rescue breathing until paramedics arrived.',
                ),
                ScenarioOption(
                  id: 'opt_hm8_1_b',
                  stepId: 'step_hm8_1',
                  textAr: 'قلب الطفل رأساً على عقب وضغط بطنه لإخراج الماء دون البدء بالأنفاس',
                  textEn: 'Hold child upside down by ankles and squeeze stomach to drain water without CPR',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر وإضاعة للوقت؛ هز وقلب الطفل لا يخرج ماء الرئة ويؤخر الإنعاش الأكسجيني الفعلي.',
                  explanationEn: 'Dangerous myth; holding upside down does not drain lungs and delays vital CPR breathing.',
                  consequenceAr: 'ضاعت دقائق ثمينة دون توفير الأكسجين للرئتين.',
                  consequenceEn: 'Critical minutes wasted without oxygenating brain.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_home_9',
          categoryId: 'home',
          titleAr: 'غصة واختناق طفل بسبب بلع لعبة صغيرة',
          titleEn: 'Choking Toddler Airway Blocked by Small Toy Part',
          descriptionAr: 'أثناء اللعب بالصالة، ابتلع طفل قطعة لعبة صغيرة وبدأ باليسعال الحاد ثم انقطع صوته وازرقّ وجهه.',
          descriptionEn: 'Toddler swallows small toy part, coughs violently then loses voice with turning blue skin.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'home',
          colorHex: 0xFF43A047,
          steps: [
            ScenarioStep(
              id: 'step_hm9_1',
              scenarioId: 'sc_home_9',
              stepOrder: 1,
              situationAr: 'الطفل لا يستطيع التنفس أو الكلام ولونه يتغير. ما هي مناورة هيمليخ الصحيحة للأطفال؟',
              situationEn: 'Child cannot breathe or speak and turns blue. What is the correct choking first aid?',
              visualTheme: 'home',
              hintAr: 'للطفل فوق السنة: ضربات ظهرية ودفعات بطنية (مناورة هيمليخ)',
              hintEn: 'Apply Heimlich maneuver abdominal thrusts and back blows until object clears',
              options: [
                ScenarioOption(
                  id: 'opt_hm9_1_a',
                  stepId: 'step_hm9_1',
                  textAr: 'الوقوف خلف الطفل والقيام بدفعات بطنية سريعة للداخل والأعلى (هيمليخ) حتى خروج القطعة',
                  textEn: 'Stand behind child and deliver inward-upward abdominal thrusts (Heimlich) until object dislodges',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إسعاف ممتاز؛ مناورة هيمليخ تضغط الهواء المتبقي بالرئة لطرد الجسم الغريب من القصبة.',
                  explanationEn: 'Excellent action; Heimlich maneuver uses residual lung air to dislodge object from trachea.',
                  consequenceAr: 'انطلقت القطعة المحشورة وعاد الطفل للتنفس بسلام.',
                  consequenceEn: 'Obstruction popped out and child resumed normal breathing.',
                ),
                ScenarioOption(
                  id: 'opt_hm9_1_b',
                  stepId: 'step_hm9_1',
                  textAr: 'إدخال الأصابع عشوائياً داخل حلق الطفل للحفر عن القطعة',
                  textEn: 'Perform blind finger sweeps inside child throat to dig out the toy',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الحفر العشوائي بالأصابع يدفع القطعة لعمق أكبر في القصبة الهوائية.',
                  explanationEn: 'Dangerous; blind finger sweeps push object deeper into trachea causing full occlusion.',
                  consequenceAr: 'اندفعت القطعة لأسفل وانقفل مجرى الهواء بالكامل.',
                  consequenceEn: 'Toy piece pushed further down totally sealing airway.',
                ),
              ],
            ),
          ],
        ),

        // ---------------- EVACUATION (4 to 9) ----------------
        Scenario(
          id: 'sc_evacuation_4',
          categoryId: 'evacuation',
          titleAr: 'إنذار إخلاء برج سكني مرتفع ليلاً',
          titleEn: 'Nighttime Evacuation Alarm in High-Rise Residential Tower',
          descriptionAr: 'استيقظت الساعة 2 فجراً على صفارات إخلاء المبنى الرئسي بالبرج السكني في الطابق 15.',
          descriptionEn: 'Waking up at 2 AM to fire alarm in a 15th floor apartment tower.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'corporate_fare',
          colorHex: 0xFF8E24AA,
          steps: [
            ScenarioStep(
              id: 'step_ev4_1',
              scenarioId: 'sc_evacuation_4',
              stepOrder: 1,
              situationAr: 'صفارات الإنذار تعمل بالكامل بالبرج. كيف تخلي شقتك بالطابق 15 بأمان؟',
              situationEn: 'Building alarm screaming on 15th floor. How to evacuate safely?',
              visualTheme: 'evacuation',
              hintAr: 'استخدم سلم الإخلاء المقاوم للحريق ولا تستخدم المصعد',
              hintEn: 'Use fire exit stairs; never take elevators during alarms',
              options: [
                ScenarioOption(
                  id: 'opt_ev4_1_a',
                  stepId: 'step_ev4_1',
                  textAr: 'إغلاق باب الشقة دون قفله، والنزول عبر درج الطوارئ والمخرج الأخضر المضاء حتى الأرضي',
                  textEn: 'Close apartment door unlocked, descend via designated fire exit stairs to ground assembly point',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الصحيح؛ أدراج الطوارئ تكون معزولة وضد الدخان، والمصاعد قد تتعطل بالكهرباء.',
                  explanationEn: 'Correct procedure; fire exit stairwells are smoke-pressurized and safe.',
                  consequenceAr: 'وصلت لنقطة التجمع الخارجية بأمان.',
                  consequenceEn: 'Reached outdoor safe assembly area without issue.',
                ),
                ScenarioOption(
                  id: 'opt_ev4_1_b',
                  stepId: 'step_ev4_1',
                  textAr: 'انتظار المصعد الكهربائي السريع للنزول بأسرع وقت',
                  textEn: 'Wait for the express elevator to ride down quickly',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ المصاعد تتوقف وتتجمع فيها غازات الحريق السامة عند انقطاع الكهرباء.',
                  explanationEn: 'Hazardous; elevators stall and trap occupants inside smoke-filled shafts.',
                  consequenceAr: 'انقطعت الكهرباء واحتجز المصعد بالطابق العاشر.',
                  consequenceEn: 'Power cut out stalling elevator between floors.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_evacuation_5',
          categoryId: 'evacuation',
          titleAr: 'التدافع والاندفاع عند بوابة الخروج بملعب رياضي',
          titleEn: 'Crowd Crush & Stampede at Stadium Exit Gate',
          descriptionAr: 'عقب نهاية مباراة جماهيرية، حدث تدافع وانحشار شديد عند إحدى بوابات الخروج الرئيسية.',
          descriptionEn: 'Post-match crowd surge causes severe bottlenecking and stampede risk at stadium exit gate.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'corporate_fare',
          colorHex: 0xFF8E24AA,
          steps: [
            ScenarioStep(
              id: 'step_ev5_1',
              scenarioId: 'sc_evacuation_5',
              stepOrder: 1,
              situationAr: 'الضغط يزداد والجمهور يدفع من الخلف. كيف تحمي نفسك من الانحشار وسحق الصدر؟',
              situationEn: 'Crowd pressure intensifying behind you. How to protect yourself from chest crushing?',
              visualTheme: 'evacuation',
              hintAr: 'ضع ذراعيك أمام صدرك لمقاومة الضغط، والتحرك مع اتجاه التيار جانباً',
              hintEn: 'Fold arms across chest like a boxer to create breathing space and move diagonally',
              options: [
                ScenarioOption(
                  id: 'opt_ev5_1_a',
                  stepId: 'step_ev5_1',
                  textAr: 'رفع الذراعين وحماية الصدر بوُضعية الملاكم (Boxer Pose)، والتحرك بالورب مع تدفق الجمهور نحو الأطراف',
                  textEn: 'Hold arms in front of chest (boxer stance) to create breathing space, move diagonally to edges',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء وقائي ممتاز؛ وضعية الملاكم تحمي القفص الصدري من الانسحاق وتتيح للتنفس الاستمرار.',
                  explanationEn: 'Excellent survival technique; boxer posture shields lungs from compressive asphyxia.',
                  consequenceAr: 'حافظت على التوازن وتسللت لأطراف الممر الخالي بأمان.',
                  consequenceEn: 'Maintained balance and safely navigated out to crowd perimeter.',
                ),
                ScenarioOption(
                  id: 'opt_ev5_1_b',
                  stepId: 'step_ev5_1',
                  textAr: 'الدفع المعاكس لقوة الحشود والصراخ أو السقوط التقاط الأشياء',
                  textEn: 'Push backwards hard against the crowd or bend down to pick up dropped items',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'قاتل وشديد الخطورة؛ الانحناء أو الدفع العكسي يسبب السقوط والدهس تحت أقدام الجمهور.',
                  explanationEn: 'Fatal mistake; bending down or resisting wave causes trip and trampling underfoot.',
                  consequenceAr: 'اختل التوازن وكاد يحدث سقوط تحت الأقدام.',
                  consequenceEn: 'Lost balance and nearly fell beneath stampeding crowd.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_evacuation_6',
          categoryId: 'evacuation',
          titleAr: 'إخلاء قسم الطوارئ في مستشفى بسبب الدخان',
          titleEn: 'Hospital Emergency Ward Evacuation Due to Smoke',
          descriptionAr: 'انطلق إنذار الحريق بقسم التنويم بالمستشفى وبدأ الدخان بالتسرب في الممرات.',
          descriptionEn: 'Fire alarm triggers in hospital ward as smoke spreads down clinical corridors.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'corporate_fare',
          colorHex: 0xFF8E24AA,
          steps: [
            ScenarioStep(
              id: 'step_ev6_1',
              scenarioId: 'sc_evacuation_6',
              stepOrder: 1,
              situationAr: 'هناك مرصى مقعدين بحاجة للإخلاء الأفقي أولاً. ما هي أولوية الإخلاء بالمستشفيات؟',
              situationEn: 'Bedridden patients need evacuation. What is hospital horizontal evacuation protocol?',
              visualTheme: 'evacuation',
              hintAr: 'الإخلاء الأفقي خلف أبواب الحريق المجاورة أولاً قبل السلالم',
              hintEn: 'Perform horizontal evacuation past smoke-barrier fire doors first',
              options: [
                ScenarioOption(
                  id: 'opt_ev6_1_a',
                  stepId: 'step_ev6_1',
                  textAr: 'نقل المرضى أفقياً خلف الأبواب المقاومة للحريق بالمنطقة المجاورة (Horizontal Evacuation)',
                  textEn: 'Move patients horizontally through fire barrier doors into adjacent safe building compartment',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'بروتوكول المستشفيات المعترف به؛ الإخلاء الأفقي يحمي المرضى المقعدين خلف قطاعات الحريق.',
                  explanationEn: 'Standard hospital protocol; horizontal compartmentation protects non-ambulatory patients.',
                  consequenceAr: 'تم نقل المرضى لقطاع آمن دون الحاجة لنزول السلالم الشاقة.',
                  consequenceEn: 'Patients transferred safely to adjacent fire-safe compartment zone.',
                ),
                ScenarioOption(
                  id: 'opt_ev6_1_b',
                  stepId: 'step_ev6_1',
                  textAr: 'محاولة نقل أسرة المرضى الثقيلة عبر أدراج الطوارئ الضيقة',
                  textEn: 'Attempt carrying heavy hospital beds down narrow emergency exit stairs',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر ومسدود؛ الأسرة تحشر بالسلالم وتغلق مسار خروج باقي كوادر الإخلاء.',
                  explanationEn: 'Hazardous roadblock; hospital beds jam stairwells blocking exit for everyone.',
                  consequenceAr: 'انحشر السرير في بيت الدرج وعرقل الحركة.',
                  consequenceEn: 'Hospital bed wedged in stairwell blocking escape route.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_evacuation_7',
          categoryId: 'evacuation',
          titleAr: 'انطلاق جرس الإخلاء في مدرسة ابتدائية',
          titleEn: 'Primary School Emergency Evacuation Drill & Alarm',
          descriptionAr: 'أثناء الدوام المدرسي، انطلق جرس الإخلاء وانبعث دخان من معمل العلوم بالطابق العلوي.',
          descriptionEn: 'Evacuation alarm rings during school day due to chemical smoke in upper science lab.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'corporate_fare',
          colorHex: 0xFF8E24AA,
          steps: [
            ScenarioStep(
              id: 'step_ev7_1',
              scenarioId: 'sc_evacuation_7',
              stepOrder: 1,
              situationAr: 'الطلاب في الفصل يصابون بالذعر. كيف يوجه المعلم الطلاب للإخلاء المنظم؟',
              situationEn: 'Students panic in classroom. How does teacher organize safe class evacuation?',
              visualTheme: 'evacuation',
              hintAr: 'التنظيم في خط قاطرة واحد، ومغادرة الفصل دون أمتعة لنقطة التجمع',
              hintEn: 'Form single file line, leave schoolbags behind, walk to assembly yard',
              options: [
                ScenarioOption(
                  id: 'opt_ev7_1_a',
                  stepId: 'step_ev7_1',
                  textAr: 'توجيه الطلاب بالاصطفاف في قاطرة واحدة، وترك الحقائب، والسير بهدوء لنقطة التجمع بملعب المدرسة',
                  textEn: 'Form students into a single file line, leave backpacks behind, walk calmly to school yard assembly point',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء مدرسي مثالي؛ ترك الحقائب يسرّع الحركة ويمنع التعثر، والقاطرة تمنع الضياع.',
                  explanationEn: 'Ideal school protocol; leaving bags prevents tripping and single line maintains headcount.',
                  consequenceAr: 'وصل جميع الطلاب للملعب وتم حصر الأعداد بسلام.',
                  consequenceEn: 'All students reached assembly yard and headcount was verified 100%.',
                ),
                ScenarioOption(
                  id: 'opt_ev7_1_b',
                  stepId: 'step_ev7_1',
                  textAr: 'السماح للطلاب بجمع ممتلكاتهم والتدافع نحو الباب الرئيسي',
                  textEn: 'Allow students to pack up personal belongings and rush doors randomly',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ جمع الحقائب يضيع ثوانٍ ثمينة والتدافع يسبب سقوط الأطفال على الباب.',
                  explanationEn: 'Dangerous; packing bags wastes critical seconds and rushing causes student pile-ups.',
                  consequenceAr: 'سقط بعض الطلاب عند مخرج الفصل وتأخر الإخلاء.',
                  consequenceEn: 'Students tripped at doorway delaying classroom evacuation.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_evacuation_8',
          categoryId: 'evacuation',
          titleAr: 'احتجاز وتوقف المصعد الكهربائي بين طابقين',
          titleEn: 'Passenger Elevator Trapped Between Floors',
          descriptionAr: 'انقطعت الكهرباء فجأة وتوقف المصعد الذي تركبه بين الطابقين الرابع والخامس في الظلام.',
          descriptionEn: 'Sudden power outage stalls elevator between 4th and 5th floors in complete darkness.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'corporate_fare',
          colorHex: 0xFF8E24AA,
          steps: [
            ScenarioStep(
              id: 'step_ev8_1',
              scenarioId: 'sc_evacuation_8',
              stepOrder: 1,
              situationAr: 'المصعد متوقف في الظلام والحرارة ترتفع قليلاً. ما التصرف الآمن بالداخل؟',
              situationEn: 'Elevator stalled in dark. What is safe conduct inside cabin?',
              visualTheme: 'evacuation',
              hintAr: 'استخدم زر الإنذار/الجوال لطلب الدفاع المدني والبقاء هادئاً دون محاولة فتح الباب',
              hintEn: 'Press alarm/intercom button, stay calm, call 911; do not pry doors open',
              options: [
                ScenarioOption(
                  id: 'opt_ev8_1_a',
                  stepId: 'step_ev8_1',
                  textAr: 'الضغط على زر جرس الطوارئ بالكبينة، والاتصال بالصيانة أو 911، والبقاء هادئاً بالداخل',
                  textEn: 'Press emergency intercom button, call building maintenance or 911, and remain calm inside',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ كبينات المصاعد بها تهوية كافية، والبقاء بالداخل يضمن عدم السقوط في البئر.',
                  explanationEn: 'Safe procedure; elevator cabs have safety brakes and ventilation; staying put prevents shaft falls.',
                  consequenceAr: 'حضرت فرقة الصيانة وتم تحريك المصعد للطابق وأخرج الجميع بسلام.',
                  consequenceEn: 'Technicians arrived, manually releasrd brake and rescued passengers.',
                ),
                ScenarioOption(
                  id: 'opt_ev8_1_b',
                  stepId: 'step_ev8_1',
                  textAr: 'محاولة فتح أبواب المصعد باليدين والتسلق في فتحة البئر بين الطابقين',
                  textEn: 'Force doors open manually and try climbing out into open shaft between floors',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'شديد الخطورة والفتك؛ القفز أو التسلق من مصعد معلق قد يؤدي لسقوط الشخص في بئر المصعد.',
                  explanationEn: 'Lethal hazard; trying to climb out of half-open trapped elevator risks falling down open shaft.',
                  consequenceAr: 'كادت تزل القدم في فتحة البئر أسفل الكبينة.',
                  consequenceEn: 'Foot slipped near dangerous open hoistway drop.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_evacuation_9',
          categoryId: 'evacuation',
          titleAr: 'إخلاء شخص من كبار السن مقعد حركة أثناء الحريق',
          titleEn: 'Evacuating Wheelchair Elderly Relative During Emergency',
          descriptionAr: 'انطلق إنذار الطوارئ بالمنزل، وعليك مساعدة جدك المقعد على الكرسي المتحرك بالطابق العلوي.',
          descriptionEn: 'Emergency alarm sounds while assisting a mobility-impaired elderly relative on upper floor.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'corporate_fare',
          colorHex: 0xFF8E24AA,
          steps: [
            ScenarioStep(
              id: 'step_ev9_1',
              scenarioId: 'sc_evacuation_9',
              stepOrder: 1,
              situationAr: 'المصعد متوقف والدخان يبدأ بالتسرب. كيف تنقل الشخص المقعد عبر السلالم بأمان؟',
              situationEn: 'Elevator disabled and smoke seeping. How do you carry wheelchair user down stairs safely?',
              visualTheme: 'evacuation',
              hintAr: 'استخدم تقنية الحمل الثنائي (Two-Person Carry) أو كرسي الإخلاء اليدوي',
              hintEn: 'Use a two-person forearm carry method or manual evacuation chair down stairs',
              options: [
                ScenarioOption(
                  id: 'opt_ev9_1_a',
                  stepId: 'step_ev9_1',
                  textAr: 'الاستعانة بفرد آخر لحمل المسن بتقنية الساعد المزدوج (Two-Person Carry) أو كرسي الإخلاء الدرجي',
                  textEn: 'Enlist a second helper to perform a two-person carry technique or specialized stair evac chair',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء ممتاز؛ الحمل الثنائي المنسق يمنع سقوط المسن وينزل به السلالم بأمان وسرعة.',
                  explanationEn: 'Excellent procedure; coordinated two-person carry safely moves non-ambulatory persons down stairs.',
                  consequenceAr: 'تمت نجدة المسن وإخلاؤه لنقطة التجمع الخرجية بسلام.',
                  consequenceEn: 'Elderly relative successfully evacuated to outdoor safe zone.',
                ),
                ScenarioOption(
                  id: 'opt_ev9_1_b',
                  stepId: 'step_ev9_1',
                  textAr: 'دفع الكرسي المتحرك بكامل ثقله على درجات السلم المباشرة',
                  textEn: 'Push the heavy wheelchair directly over top stair step down flight',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ انزلاق الكرسي على السلم يسبب انقلابه وهوي المسن على الدرج.',
                  explanationEn: 'Dangerous; rolling heavy wheelchair down stairs causes catastrophic tumble.',
                  consequenceAr: 'اختل توازن الكرسي على الدرج وتسبب بسقوط.',
                  consequenceEn: 'Wheelchair tipped violently over stair steps.',
                ),
              ],
            ),
          ],
        ),

        // ---------------- ELECTRIC (4 to 9) ----------------
        Scenario(
          id: 'sc_electric_4',
          categoryId: 'electric',
          titleAr: 'سلك كهربائي مكشوف وملامس للماء في الحديقة',
          titleEn: 'Exposed Live Wire Touching Wet Garden Grass',
          descriptionAr: 'أثناء تواجدك بالحديقة، لاحظت سلك مضخة المياه مكشوفاً ومغموراً في بقعة مياه قرب الأطفال.',
          descriptionEn: 'Noticed a frayed exposed pump power cable submerged in standing water puddle near kids playing.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          steps: [
            ScenarioStep(
              id: 'step_el4_1',
              scenarioId: 'sc_electric_4',
              stepOrder: 1,
              situationAr: 'المياه قد تكون مكهربة والأطفال يلعبون بالجوار. ما التصرف الأول الوقائي؟',
              situationEn: 'Water puddle might be energized with playing kids nearby. What is first protective action?',
              visualTheme: 'electric',
              hintAr: 'فصل القاطع الرئيسي فوراً وإبعاد الأطفال دون لمس المياه',
              hintEn: 'Disconnect main power breaker immediately and keep kids away from water',
              options: [
                ScenarioOption(
                  id: 'opt_el4_1_a',
                  stepId: 'step_el4_1',
                  textAr: 'إبعاد الأطفال فوراً عن بقعة الماء، وفصل القاطع الكهربائي المغذي للحديقة من اللوحة الرئيسية',
                  textEn: 'Immediately order kids away from puddle, then trip main outdoor garden breaker at panel',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ عزل التيار من اللوحة يضمن قطع الكهرباء عن المياه قبل الاقتراب منها.',
                  explanationEn: 'Correct procedure; tripping circuit breaker at main board de-energizes water before approach.',
                  consequenceAr: 'تم انقطاع التيار وتأمين الحديقة بأمان.',
                  consequenceEn: 'Power safely isolated and garden area secured.',
                ),
                ScenarioOption(
                  id: 'opt_el4_1_b',
                  stepId: 'step_el4_1',
                  textAr: 'الخوض في بقعة الماء بيدين حافيتين لسحب السلك المكشوف',
                  textEn: 'Wade into water puddle barefoot to grab and pull exposed cable out',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'قاتل وشديد الخطورة؛ الدخول في مياه مكهربة يسبب الصعق الفوري والموت.',
                  explanationEn: 'Fatal hazard; stepping into electrified water causes immediate fatal shock.',
                  consequenceAr: 'تعرض الشخص لتكهرب حاد وسقوط بالماء.',
                  consequenceEn: 'Person suffered severe electric shock upon stepping in water.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_electric_5',
          categoryId: 'electric',
          titleAr: 'شرر ودخان من وحدة التكييف السبلت بالجدار',
          titleEn: 'Sparking & Smoke Outbreak from Wall Split AC Unit',
          descriptionAr: 'صدر صوت فرقعة وتصاعد دخان أسود ورائحة حريق بلاستيك من وحدة المكيف الجداري بالصالة.',
          descriptionEn: 'Loud popping sound followed by black smoke and burning smell from wall split AC unit.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          steps: [
            ScenarioStep(
              id: 'step_el5_1',
              scenarioId: 'sc_electric_5',
              stepOrder: 1,
              situationAr: 'الدخان يزداد من وحدة التكييف. ما الحركة الأولى الصحيحة للإطفاء؟',
              situationEn: 'Smoke intensifying from split AC unit. What is the immediate safety protocol?',
              visualTheme: 'electric',
              hintAr: 'إطفاء المفتاح الجداري وقفل القاطع الخاص بالمكيف',
              hintEn: 'Shut off wall isolator switch and flip AC circuit breaker off',
              options: [
                ScenarioOption(
                  id: 'opt_el5_1_a',
                  stepId: 'step_el5_1',
                  textAr: 'فصل مفتاح الأمان الجداري الخاص بالمكيف (Isolator) وقاطع لوحة التوزيع، واستخدام طفاية ثاني أكسيد الكربون',
                  textEn: 'Switch off wall isolator switch, trip breaker on main DB board, deploy CO2 extinguisher if needed',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ فصل مفتاح المكيف يمنع استمرار الشرر ويقضي على مصدر الاشتعال الكهربائي.',
                  explanationEn: 'Safe procedure; opening dedicated wall isolator cuts high current preventing fires.',
                  consequenceAr: 'انقطع التيار وتوقف الدخان والشرر بسلام.',
                  consequenceEn: 'Electrical arc ceased and smoking unit was isolated safely.',
                ),
                ScenarioOption(
                  id: 'opt_el5_1_b',
                  stepId: 'step_el5_1',
                  textAr: 'رش رذاذ الماء على وحدة المكيف وهي موصولة بالكهرباء',
                  textEn: 'Spray water mist directly onto flaming AC unit while running',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ رش الماء على التكييف الموصول بالكهرباء يسبب ماساً وانفجاراً باللوحة.',
                  explanationEn: 'Dangerous; spraying water on live electrical appliance causes severe shock and short-circuit explosion.',
                  consequenceAr: 'حدث انفجار كهربائي باللوحة الداخلية للمكيف.',
                  consequenceEn: 'Short circuit explosion damaged unit control board.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_electric_6',
          categoryId: 'electric',
          titleAr: 'انصهار وتصاعد دخان من توصيلة كهربائية متعددة',
          titleEn: 'Melting Power Strip Extension Cord Fire Hazard',
          descriptionAr: 'تم توصيل دفاية ومكواة وغلاية على توصيلة واحدة سخنت وانصهر البلاستيك الخارجي وبدأ الدخان.',
          descriptionEn: 'Overloading power strip with heater, iron, and kettle causes plastic casing to melt and smoke.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          steps: [
            ScenarioStep(
              id: 'step_el6_1',
              scenarioId: 'sc_electric_6',
              stepOrder: 1,
              situationAr: 'التوصيلة تنصهر وتخرج رغوة ودخان. كيف تتدخل دون لمس السلك المنصهر؟',
              situationEn: 'Power strip melting with burning plastic smoke. How to intervene safely?',
              visualTheme: 'electric',
              hintAr: 'افصل الفيش الرئيسي من المقبس الجداري أو قاطِع الجدار',
              hintEn: 'Unplug main extension plug from wall socket or trip wall breaker',
              options: [
                ScenarioOption(
                  id: 'opt_el6_1_a',
                  stepId: 'step_el6_1',
                  textAr: 'فصل القابس الرئيسي للتوصيلة من مقبس الجدار بحذر أو قفل قاطع الغرفة، واستبدال التوصيلة التالفة',
                  textEn: 'Unplug main power strip plug from wall outlet carefully or trip room breaker, discard damaged strip',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء سليم؛ عزل التوصيلة المفرطة الأحمال ينقذ المنزل من حرائق التوصيلات الشائعة.',
                  explanationEn: 'Correct procedure; unplugging overloaded extension removes high thermal amp load.',
                  consequenceAr: 'انقطع الحمل الكهربائي وسلِم الموقع من حريق التوصيلات.',
                  consequenceEn: 'Load disconnected preventing electrical extension fire.',
                ),
                ScenarioOption(
                  id: 'opt_el6_1_b',
                  stepId: 'step_el6_1',
                  textAr: 'سحب الأسلاك المنصهرة باليدين وهي تعمل وإضافة أجهزة أخرى',
                  textEn: 'Yank melting hot cords with bare hands while active',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ لمس البلاستيك المنصهر يكشف النحاس الكهربائي المباشر ويسبب حروقاً وصعقاً.',
                  explanationEn: 'Dangerous; touching molten insulation exposes live copper conductors leading to shock.',
                  consequenceAr: 'تعرضت الأيدي للحروق وصدمة كهربائية.',
                  consequenceEn: 'Bare hands suffered thermal burns and electric shock.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_electric_7',
          categoryId: 'electric',
          titleAr: 'سقوط كابل ضغط عالي فوق سطح السيارة أثناء العاصفة',
          titleEn: 'High-Voltage Power Line Falls onto Car Roof',
          descriptionAr: 'أثناء قيادتك في عاصفة، سقط كابل كهربائي ضغط عالي من عمود انكسر واستقر فوق سقف مركبتك.',
          descriptionEn: 'Storm downs a utility pole dropping a live high-voltage power line right onto your car roof.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          steps: [
            ScenarioStep(
              id: 'step_el7_1',
              scenarioId: 'sc_electric_7',
              stepOrder: 1,
              situationAr: 'الكابل يفرز شرارات ضخمة فوق سقف السيارة. كيف تبقى حياً بالداخل؟',
              situationEn: 'High-voltage line sparking violently on car roof. How do you survive inside?',
              visualTheme: 'electric',
              hintAr: 'ابقَ داخل السيارة ولا تلمس هيكلها الخارجي أو تترجل منها، واطلب 933/911',
              hintEn: 'Stay inside car; do not step out or touch metal frame until utility de-energizes wire',
              options: [
                ScenarioOption(
                  id: 'opt_el7_1_a',
                  stepId: 'step_el7_1',
                  textAr: 'البقاء داخل المركبة دون الخروج أو لمس الهيكل المعدني، والاتصال بطوارئ 911 و 933 لعزل التيار',
                  textEn: 'Remain seated inside car, do not touch metal frame or step outside, call 911 & 933 to de-energize line',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء منقذ للحياة؛ الإطارات العازلة تجعل هيكل السيارة قفص فاراداي آمناً طالما لم يلمس السائق الأرض.',
                  explanationEn: 'Life-saving physics move; rubber tires insulate vehicle body acting as safe Faraday cage.',
                  consequenceAr: 'بقيت سالماً بالداخل حتى حضرت طوارئ الكهرباء وفصلت الكابل.',
                  consequenceEn: 'Remained 100% safe inside until electricity crews turned off power grid line.',
                ),
                ScenarioOption(
                  id: 'opt_el7_1_b',
                  stepId: 'step_el7_1',
                  textAr: 'فتح باب السيارة ووضع قدم على الأرض وقدم بالسيارة للترجل',
                  textEn: 'Open car door and step one foot onto ground while holding car frame',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'قاتل وشديد الخطورة؛ وضع قدم على الأرض أثناء لمس السيارة يكمل الدائرة الكهربائية ويصعق فوراً.',
                  explanationEn: 'Fatal error; stepping onto ground while touching electrified car completes path to ground causing death.',
                  consequenceAr: 'حدثت قوس كهربائية وصدمة قاتلة.',
                  consequenceEn: 'Current surged through body causing severe electrocution.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_electric_8',
          categoryId: 'electric',
          titleAr: 'دخول مياه السيل إلى القواطع والمقابس الأرضية',
          titleEn: 'Floodwater Inundating Low Floor Electric Sockets',
          descriptionAr: 'دخلت مياه السيل للغرفة السفلية وغمرت المقابس والأفياش الكهربائية الجدارية المنخفضة.',
          descriptionEn: 'Floodwater breaches ground room covering low-mounted wall power sockets and extension blocks.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          steps: [
            ScenarioStep(
              id: 'step_el8_1',
              scenarioId: 'sc_electric_8',
              stepOrder: 1,
              situationAr: 'المياه تغطي المقابس والأفياش على الجدار. ما الخطوة الوحيدة الآمنة قبل البدء بسحب المياه؟',
              situationEn: 'Water covers wall sockets. What is single mandatory safe step before water cleanup?',
              visualTheme: 'electric',
              hintAr: 'افصل القاطع الرئيسي من لوحة العداد الخارجية فوراً',
              hintEn: 'Disconnect main circuit breaker at outside DB panel first',
              options: [
                ScenarioOption(
                  id: 'opt_el8_1_a',
                  stepId: 'step_el8_1',
                  textAr: 'فصل المفتاح الرئيسي العام لقواطع المنـزل (Main Breaker) من اللوحة الخارجية قبل لمس أي مياه',
                  textEn: 'Disengage main utility service breaker on main distribution board before entering water',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ عزل اللوحة الرئيسية يضمن تفريغ الكهرباء من جميع أفياش الغرفة المغمورة.',
                  explanationEn: 'Safe protocol; disconnecting main service breaker kills all power to flooded wall outlets.',
                  consequenceAr: 'انقطعت الكهرباء وبدأت عمليات نزح المياه بأمان تام.',
                  consequenceEn: 'Electricity fully isolated enabling safe water extraction.',
                ),
                ScenarioOption(
                  id: 'opt_el8_1_b',
                  stepId: 'step_el8_1',
                  textAr: 'النزول في المياه ونسزع القوابس المغمورة باليدين مباشرة',
                  textEn: 'Step into floodwater and manually pull submerged plugs from outlets',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ لمس المقابس المغمورة بالماء أثناء جريان التيار يسبب صعقاً كهربائياً قاتلاً.',
                  explanationEn: 'Dangerous; touching submerged live wall outlets electrocutes person instantly.',
                  consequenceAr: 'تعرض الشخص لصدمة كهربائية بالماء.',
                  consequenceEn: 'Person received electric shock in standing water.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_electric_9',
          categoryId: 'electric',
          titleAr: 'صعق كهربائي لشخص يلمس غسالة ملابس',
          titleEn: 'Electric Shock Victim Touching Laundry Washing Machine',
          descriptionAr: 'أثناء غسيل الملابس، صرخ أحد أفراد الأسرة وسقط بجانب الغسالة نتيجة تسرب كهربائي بهيكلها المعدني.',
          descriptionEn: 'Family member collapses next to washing machine screaming due to internal short grounding to metal chassis.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
          steps: [
            ScenarioStep(
              id: 'step_el9_1',
              scenarioId: 'sc_electric_9',
              stepOrder: 1,
              situationAr: 'المصاب ملقى بجانب الغسالة وقد يكون جسمه مكهرباً. كيف تنقذه دون أن تتكهرب معه؟',
              situationEn: 'Victim lying next to machine and may be energized. How to rescue without touching him directly?',
              visualTheme: 'electric',
              hintAr: 'افصل القاطع الرئيسي أولاً أو استخدم عصا خشبية عازلة لإبعاد المصاب',
              hintEn: 'Cut power at breaker panel first or use dry non-conductive wooden broom to push victim free',
              options: [
                ScenarioOption(
                  id: 'opt_el9_1_a',
                  stepId: 'step_el9_1',
                  textAr: 'فصل القاطع الرئيسي فوراً، أو استخدام لوح/عصا خشبية جافة عازلة لإبعاد المصاب عن الغسالة',
                  textEn: 'Cut main circuit breaker immediately, or use a dry wooden broomstick to push victim away from machine',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إسعاف ممتاز؛ استخدام الأدوات العازلة والخشبية يمنع انتقال التيار للمنقذ ويحرر المصاب.',
                  explanationEn: 'Excellent first aid; using non-conductive wooden objects isolates rescuer from electric shock.',
                  consequenceAr: 'تم فصل التيار وتحرير المصاب وفحص تنفسه وإسعافه.',
                  consequenceEn: 'Power isolated, victim freed safely and evaluated for CPR.',
                ),
                ScenarioOption(
                  id: 'opt_el9_1_b',
                  stepId: 'step_el9_1',
                  textAr: 'الإمساك بيد المصاب المكهرب مباشرة بيدك المكشوفة لسحبه',
                  textEn: 'Grab the shocked victim hands directly with your bare hands to pull him away',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ لمس شخص يتكهرب يمرر التيار لجسدك فتصبح ضحية ثانية بالصعق.',
                  explanationEn: 'Hazardous; touching an energized shock victim passes current through your body.',
                  consequenceAr: 'انتقل التيار للمنقذ وتكهرب الاثنان.',
                  consequenceEn: 'Electric current jumped to rescuer causing double electrocution.',
                ),
              ],
            ),
          ],
        ),

        // ---------------- EMERGENCY KIT (4 to 9) ----------------
        Scenario(
          id: 'sc_kit_4',
          categoryId: 'emergency_kit',
          titleAr: 'تجهيز وتصنيف أدوية الأمراض المزمنة في الحقيبة',
          titleEn: 'Organizing Chronic Prescription Medicines in Emergency Kit',
          descriptionAr: 'تقوم بتجهيز حقيبة طوارئ 72 ساعة للعائلة وبك أفراد يعانون من الضغط والسكر وأمراض الربو.',
          descriptionEn: 'Packing a 72-hour family emergency kit for household members with hypertension, diabetes, and asthma.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'backpack',
          colorHex: 0xFF009688,
          steps: [
            ScenarioStep(
              id: 'step_kt4_1',
              scenarioId: 'sc_kit_4',
              stepOrder: 1,
              situationAr: 'كيف تضمن توفير الأدوية الضرورية بالحقيبة دون تلفها أو نسيان الجرعات؟',
              situationEn: 'How to properly pack chronic medications in kit ensuring safety and dosage continuity?',
              visualTheme: 'emergency_kit',
              hintAr: 'توفير كمية تكفي أسابيع في حافظة عازلة للرؤوبة مع تدوين الوصفات',
              hintEn: 'Pack 2-week supply in waterproof labeled container with doctor prescription notes',
              options: [
                ScenarioOption(
                  id: 'opt_kt4_1_a',
                  stepId: 'step_kt4_1',
                  textAr: 'تضمين جرعات تكفي أسبوعين على الأقل في حافظة محكمة وعازلة للماء مع صور الوصفات الطبية',
                  textEn: 'Pack at least a 2-week supply of all prescription drugs in waterproof labeled container with prescription copies',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ حفظ الأدوية بحافظة عازلة وتوفير رصيد كافٍ يدعم صحة الأسرة أثناء الانقطاعات.',
                  explanationEn: 'Correct procedure; waterproof storage and ample supply maintains medical stability during crises.',
                  consequenceAr: 'تم تجهيز الأدوية بأمان تام وضمان استمرار العلاج.',
                  consequenceEn: 'Medications packed securely guaranteeing medical continuity.',
                ),
                ScenarioOption(
                  id: 'opt_kt4_1_b',
                  stepId: 'step_kt4_1',
                  textAr: 'الاعتماد على شرائها عند وقوع الكارثة من صيدليات الشارع',
                  textEn: 'Rely on buying prescription drugs from local pharmacies after disasters happen',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ الصيدليات قد تقفل أبوابها أو تنقطع الإمدادات أثناء الكوارث والسيول.',
                  explanationEn: 'Dangerous; pharmacies often close or run out of stock during emergency floods/outages.',
                  consequenceAr: 'تعذر الحصول على الأدوية أثناء الكارثة.',
                  consequenceEn: 'Unable to locate required prescription drugs during emergency.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_kit_5',
          categoryId: 'emergency_kit',
          titleAr: 'فحص ومراجعة تاريخ صلاحية المستلزمات الطبية',
          titleEn: 'Bi-Annual Expiration Inspection of Medical Supplies',
          descriptionAr: 'حان موعد الفحص الدوري السداسي لحقيبة الطوارئ المنزلية للتأكد من جاهزيتها.',
          descriptionEn: 'Conducting the bi-annual routine check on household 72-hour emergency kit supplies.',
          difficulty: 'مبتدئ',
          timeLimitSeconds: 15,
          icon: 'backpack',
          colorHex: 0xFF009688,
          steps: [
            ScenarioStep(
              id: 'step_kt5_1',
              scenarioId: 'sc_kit_5',
              stepOrder: 1,
              situationAr: 'وجدت بعض المعقمات والمأكولات قريبة من انتهاء الصلاحية. ما الإجراء الصحيح؟',
              situationEn: 'Found antiseptics and canned food nearing expiration dates. What is the standard routine?',
              visualTheme: 'emergency_kit',
              hintAr: 'استبدال المواد منتهية الصلاحية بفور وتجربة البطاريات والراديو',
              hintEn: 'Rotate and replace expiring rations/drugs immediately; test batteries and radio',
              options: [
                ScenarioOption(
                  id: 'opt_kt5_1_a',
                  stepId: 'step_kt5_1',
                  textAr: 'استبدال المستلزمات والمأكولات القريبة من الانتهاء بأخرى حديثة، واختبار عمل بطاريات الكشاف وراديو الطوارئ',
                  textEn: 'Rotate and replace aging rations/drugs with fresh stock, test flashlight and radio battery charge',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء ممتاز؛ تدوير المخزون الفصلي يضمن جاهزية الحقيبة بنسبة 100% دون خذلان أثناء الكوارث.',
                  explanationEn: 'Excellent maintenance; periodic stock rotation ensures 100% kit reliability when disaster strikes.',
                  consequenceAr: 'أصبحت الحقيبة محدثة وجاهزة للاستخدام الفوري.',
                  consequenceEn: 'Emergency kit updated and fully verified for immediate deployment.',
                ),
                ScenarioOption(
                  id: 'opt_kt5_1_b',
                  stepId: 'step_kt5_1',
                  textAr: 'ترك المواد منتهية الصلاحية بالحقيبة وعدم تغيير البطاريات',
                  textEn: 'Leave expired items in the kit and ignore testing flashlight batteries',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ الأدوية والأغذية المنتهية قد تتسبب بتسمم أو فشل العلاج، والبطاريات التالفة تسرب أسيداً.',
                  explanationEn: 'Hazardous; expired medical/food items cause poisoning and dead batteries corrode devices.',
                  consequenceAr: 'تعطل الكشاف وفسد المعقم بالحقيبة.',
                  consequenceEn: 'Flashlight failed due to corroded battery acid leakage.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_kit_6',
          categoryId: 'emergency_kit',
          titleAr: 'استخدام جهاز إنعاش القلب الخارجي (AED) لمصاب متوقف القلب',
          titleEn: 'Deploying Automated External Defibrillator (AED) on Cardiac Arrest',
          descriptionAr: 'سقط شخص بالمركز الرياضي فاقد الوعي والتنفس وأحضر لك أحد المتواجدين جهاز إنعاش القلب الذكي AED.',
          descriptionEn: 'Person collapses in sports club without pulse; bystander brings Automated External Defibrillator (AED).',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'backpack',
          colorHex: 0xFF009688,
          steps: [
            ScenarioStep(
              id: 'step_kt6_1',
              scenarioId: 'sc_kit_6',
              stepOrder: 1,
              situationAr: 'جهاز الـ AED متاح بجانبك. كيف تشغله وتطبق منصات الصدمة الكهربائية؟',
              situationEn: 'AED unit is right beside you. How to operate and apply defibrillation pads correctly?',
              visualTheme: 'emergency_kit',
              hintAr: 'تشغيل الجهاز، وإلصاق منصات الصدمة على صدر المصاب العاري، واتباع التعليمات الصوتية',
              hintEn: 'Turn on AED, apply adhesive pads to bare chest, follow voice prompts without touching victim during shock',
              options: [
                ScenarioOption(
                  id: 'opt_kt6_1_a',
                  stepId: 'step_kt6_1',
                  textAr: 'تشغيل جهاز AED، وتثبيت الوسادات اللاصقة على الصدر الجاف العاري، واتباع التعليمات الصوتية للجهاز بدقة',
                  textEn: 'Power on AED, attach pads to dry bare chest, follow clear voice instructions and clear victim before shock',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء طبي منقذ للحياة؛ أجهزة الـ AED الذكية تحلل نظم القلب وتصدم تلقائياً عند الحاجة بدقة.',
                  explanationEn: 'Life-saving emergency step; automated AEDs analyze rhythm and deliver defibrillation safely.',
                  consequenceAr: 'حلل الجهاز النبض وأعطى صدمة مصلحة وعاد النبض للمصاب.',
                  consequenceEn: 'AED analyzed lethal rhythm, delivered shock and restored perfusing heart pulse.',
                ),
                ScenarioOption(
                  id: 'opt_kt6_1_b',
                  stepId: 'step_kt6_1',
                  textAr: 'إلصاق الوسادات فوق ملابس المصاب المبتلة ولمسه أثناء إعطاء الصدمة',
                  textEn: 'Stick electrode pads directly over wet clothing and hold victim during shock delivery',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الملصقات يجب أن تلامس الجلد الجاف المباشر، ولمس المصاب أثناء الصدمة ينقل التيار للمنقذ.',
                  explanationEn: 'Dangerous; pads require bare skin contact, and touching victim passes electric shock to rescuer.',
                  consequenceAr: 'تعطل الجهاز وانتقلت صدمة للمنقذ.',
                  consequenceEn: 'Shock misfired and current zapped rescuer holding victim.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_kit_7',
          categoryId: 'emergency_kit',
          titleAr: 'التعامل مع نزيف شرياني حاد في الفخذ',
          titleEn: 'Controlling Severe Arterial Leg Bleeding with Pressure Dressing',
          descriptionAr: 'تعرض شخص لإصابة حادة بزجاج مكسور وبدأ الدم ينزف بشكل نابض وغزير (نزيف شرياني) من الفخذ.',
          descriptionEn: 'Glass accident causes deep thigh laceration with spurting bright red arterial blood loss.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'backpack',
          colorHex: 0xFF009688,
          steps: [
            ScenarioStep(
              id: 'step_kt7_1',
              scenarioId: 'sc_kit_7',
              stepOrder: 1,
              situationAr: 'النزيف الشرياني نابض وغزير ويشكل خطراً على الحياة. ما الإجراء الفوري بالضماد الضاغط؟',
              situationEn: 'Arterial spurting blood threatens life within minutes. What is immediate pressure technique?',
              visualTheme: 'emergency_kit',
              hintAr: 'الضغط المباشر القوي بشاش معقم ورفع الطرف وإستخدام عاصبة النزيف (Tourniquet)',
              hintEn: 'Apply immediate direct pressure with sterile gauze, elevate leg, use CAT Tourniquet if uncontrolled',
              options: [
                ScenarioOption(
                  id: 'opt_kt7_1_a',
                  stepId: 'step_kt7_1',
                  textAr: 'الضغط المباشر القوي جداً بضماد معقم على موضع النزيف، وربط عاصبة النزيف (Tourniquet) أعلى الإصابة',
                  textEn: 'Apply forceful direct pressure with sterile gauze, apply CAT Tourniquet 5cm above wound site, call 997',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'تصرف طبي حاسم؛ الضغط المباشر والعاصبة الشريانية توقف النزيف الشديد وتمنع الصدمة الوعائية.',
                  explanationEn: 'Critical emergency action; direct pressure and tourniquet application halts arterial exsanguination.',
                  consequenceAr: 'توقف النزيف الشديد واستقرت حالة المصاب حتى نقل الهلال الأحمر.',
                  consequenceEn: 'Severe hemorrhage controlled preventing fatal blood loss.',
                ),
                ScenarioOption(
                  id: 'opt_kt7_1_b',
                  stepId: 'step_kt7_1',
                  textAr: 'غسل الجرح بالماء وغسله ودعكه بمنديل خفيف دون ضغط',
                  textEn: 'Rinse arterial wound with water and wipe gently with paper napkin without pressure',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر وشديد الفتك؛ النزيف الشرياني يتطلب ضغطاً مستمراً كاسحاً والعناية الخفيفة تسبب الوفاة استنزافاً.',
                  explanationEn: 'Fatal mistake; arterial bleeding requires heavy firm compression; paper wipes do nothing.',
                  consequenceAr: 'استمر النزيف الغزير وانخفض ضغط الدم.',
                  consequenceEn: 'Profuse bleeding continued unabated causing hemorrhagic shock.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_kit_8',
          categoryId: 'emergency_kit',
          titleAr: 'تأمين المستلزمات الخاصة بالرضع وكبار السن بالحقيبة',
          titleEn: 'Securing Infant & Elderly Special Medical Needs in Kit',
          descriptionAr: 'تعد حقيبة الطوارئ لأسرة تضم طفلاً رضيعاً وجداً مسناً يحتاج حفاضات وعلاجات خاصة.',
          descriptionEn: 'Packing emergency 72h kit for multi-generational household with infants and senior citizens.',
          difficulty: 'مبتدئ',
          timeLimitSeconds: 15,
          icon: 'backpack',
          colorHex: 0xFF009688,
          steps: [
            ScenarioStep(
              id: 'step_kt8_1',
              scenarioId: 'sc_kit_8',
              stepOrder: 1,
              situationAr: 'ما هي أهم المكونات الخاصة بالرضع والمسنين التي يجب ألا تخلو منها حقيبة الطوارئ؟',
              situationEn: 'What essential infant and geriatric supplies must be included in household kit?',
              visualTheme: 'emergency_kit',
              hintAr: 'حليب أطفال بودرة، زجاجات معقمة، حفاضات، وأجهزة قياس الضغط والسكر للمسنين',
              hintEn: 'Powdered infant formula, sterilized bottles, diapers, and senior BP/glucose monitors',
              options: [
                ScenarioOption(
                  id: 'opt_kt8_1_a',
                  stepId: 'step_kt8_1',
                  textAr: 'تجهيز عبوات حليب رضّع بودرة، ومياه معقمة، وحفاضات، وأجهزة قياس الضغط والسكر مع بطاريات إضافية',
                  textEn: 'Pack baby formula, sterile water bottles, diapers, plus senior BP/glucose monitors with extra batteries',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إعداد شاطر ومكتمل؛ تلبية احتياجات الفئات الأكثر هشاشة بالأسرة يضمن استقرارهم أثناء الإخلاء.',
                  explanationEn: 'Comprehensive planning; meeting vulnerable family members needs maintains stability.',
                  consequenceAr: 'تم توفير جميع المستلزمات الخاصة بالرضيع والمسن بنجاح.',
                  consequenceEn: 'Infant and elderly essential items successfully secured in kit.',
                ),
                ScenarioOption(
                  id: 'opt_kt8_1_b',
                  stepId: 'step_kt8_1',
                  textAr: 'الاهتمام بالأغذية المعلبة للبالغين فقط وتجاهل مستلزمات الرضع كبار السن',
                  textEn: 'Pack adult canned food only and ignore specialized infant/senior supplies',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ الرضع وكبار السن لا يستطيعون تناول الأغذية الصلبة المعلبة ويحتاجون رعاية تخصصية.',
                  explanationEn: 'Dangerous; infants and seniors cannot digest solid adult cans and require specialized care.',
                  consequenceAr: 'حدثت معاناة ونقص في حليب الرضيع أثناء الانقطاع.',
                  consequenceEn: 'Infant experienced nutritional distress during emergency blackout.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_kit_9',
          categoryId: 'emergency_kit',
          titleAr: 'الاتصال وإبلاغ مركز طوارئ 911 عند فقدان التغطية',
          titleEn: 'Making Emergency Calls via SOS Satellite/No Network Coverage',
          descriptionAr: 'احتُجزت في منطقة جبلية نائية وتظهر على جوالك عبارة (لا توجد تغطية) أو (مكالمات الطوارئ فقط).',
          descriptionEn: 'Stranded in remote mountain valley with smartphone displaying "No Service / Emergency Calls Only".',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'backpack',
          colorHex: 0xFF009688,
          steps: [
            ScenarioStep(
              id: 'step_kt9_1',
              scenarioId: 'sc_kit_9',
              stepOrder: 1,
              situationAr: 'الشاشة تعطي (لا توجد خدمة شبكة). هل يمكنك الاتصال بطوارئ 911؟',
              situationEn: 'Screen shows No Service. Can you still place a 911 emergency rescue call?',
              visualTheme: 'emergency_kit',
              hintAr: 'نعم! اتصل بـ 911 فمكالمات الطوارئ ترتبط بأي شبكة متاحة مجاناً',
              hintEn: 'Yes! Dial 911 as emergency calls route through ANY available network tower automatically',
              options: [
                ScenarioOption(
                  id: 'opt_kt9_1_a',
                  stepId: 'step_kt9_1',
                  textAr: 'الاتصال المباشر بـ 911؛ حيث تتصل الهواتف الذكية تلقائياً بأي أبراج شبكة متبقية للمزودين الآخرين',
                  textEn: 'Dial 911 directly; smartphones automatically roam and lock onto ANY active provider tower for emergency SOS',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'معلومة تقنية منقذة للحياة؛ مكالمات 911 تتجاوز شريحة المزود وتتصل بأي برج قريب متاح مجاناً.',
                  explanationEn: 'Life-saving tech fact; 911 SOS calls bypass SIM carrier limits connecting to any available tower.',
                  consequenceAr: 'تم ربط الاتصال بمركز العمليات 911 وتم إبلاغ الموقع الدقيق.',
                  consequenceEn: 'Emergency SOS call connected to 911 dispatch center successfully.',
                ),
                ScenarioOption(
                  id: 'opt_kt9_1_b',
                  stepId: 'step_kt9_1',
                  textAr: 'إغلاق الجوال تماماً وعدم محاولة الاتصال بـ 911 لعدم وجود أبراج شريحتك',
                  textEn: 'Power off smartphone completely without trying 911 assuming no SIM towers exist',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطأ وتفويت فرصة؛ عدم تجربة 911 حرمك من خدمة التوليد التلقائي لشبكات الطوارئ الأخرى.',
                  explanationEn: 'Mistake; failing to dial 911 misses automatic emergency SOS roaming across other towers.',
                  consequenceAr: 'ضاع الوقت دون إبلاغ فرق الطوارئ عن الموقع.',
                  consequenceEn: 'Wasted opportunity without alerting emergency services.',
                ),
              ],
            ),
          ],
        ),
"""

print("Added categories Home, Evac, Electric, Kit code successfully")
