import sys

scenarios_code = """
        // ==========================================
        // ADDED SCENARIOS (3X MULTIPLIED CONTENT: 9 SCENARIOS PER CATEGORY)
        // ==========================================

        // ---------------- HEAT (4 to 9) ----------------
        Scenario(
          id: 'sc_heat_4',
          categoryId: 'heat',
          titleAr: 'ضربة شمس مفاجئة لمعتمر أثناء الطواف بالصحن الخارجي',
          titleEn: 'Heat Stroke Incident During Outdoor Pilgrimage',
          descriptionAr: 'أثناء الطواف بالصحن الخارجي في درجة حرارة 46°C، سقط شخص مجاور فجأة وغاب عن الوعي وجلده جاف ومحمّر.',
          descriptionEn: 'Pilgrim collapses outdoors at 46°C with dry hot flushed skin and loss of consciousness.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          steps: [
            ScenarioStep(
              id: 'step_h4_1',
              scenarioId: 'sc_heat_4',
              stepOrder: 1,
              situationAr: 'المصاب فاقد للوعي وجلده حار وجاف جداً. ما الإجراء الفوري المنقذ للحياة قبل نقل الهلال الأحمر؟',
              situationEn: 'Victim is unconscious with hot dry skin. What is the immediate life-saving first aid?',
              visualTheme: 'heat',
              hintAr: 'انقله فوراً للظل وقم بتبريد جسمه بالماء والتهوية',
              hintEn: 'Move immediately to shade and cool body with water spray and fan',
              options: [
                ScenarioOption(
                  id: 'opt_h4_1_a',
                  stepId: 'step_h4_1',
                  textAr: 'نقل المصاب فوراً للظل، ورش جسمه بالماء الفاتر والتهوية عليه بكثافة، والاتصال بـ 997',
                  textEn: 'Move victim immediately to shaded area, spray body with cool water and fan aggressively while calling 997',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ ضربة الشمس تتطلب التبريد السريع جداً لمنع تلف خلايا الدماغ.',
                  explanationEn: 'Correct action; heat stroke requires aggressive rapid cooling to prevent brain cell damage.',
                  consequenceAr: 'بدأت حرارة الجسد بالانخفاض واستعاد المصاب الوعي جزئياً.',
                  consequenceEn: 'Core body temperature began dropping until Red Crescent paramedics arrived.',
                ),
                ScenarioOption(
                  id: 'opt_h4_1_b',
                  stepId: 'step_h4_1',
                  textAr: 'محاولة سكب الماء داخل فمه وهو فاقد للوعي لإجباره على الشرب',
                  textEn: 'Force water down the throat of the unconscious victim to rehydrate him',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ إعطاء السوائل لفاقد الوعي يسبب دخول الماء للرئة واختناقه (Aspiration).',
                  explanationEn: 'Hazardous; giving fluids to an unconscious person causes liquid aspiration into lungs.',
                  consequenceAr: 'دخل الماء لمجرى التنفس وتسبب بسعال شديد واختناق.',
                  consequenceEn: 'Water entered airway causing aspiration choking risk.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_heat_5',
          categoryId: 'heat',
          titleAr: 'عطل تكييف المركز التجاري المكتظ في الذروة الصيفية (49°C)',
          titleEn: 'Mall HVAC Breakdown During 49°C Heatwave Peak',
          descriptionAr: 'توقف تكييف مركز تجاري مكتظ في منتصف الظهيرة وارتفعت الحرارة والحرارة بالداخل بشكل خانق.',
          descriptionEn: 'Air conditioning fails in crowded shopping center during 49°C peak afternoon.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          steps: [
            ScenarioStep(
              id: 'step_h5_1',
              scenarioId: 'sc_heat_5',
              stepOrder: 1,
              situationAr: 'الحرارة ترتفع داخل الصالة المغلقة والناس تشعر بالدوار والاستياء. كيف تتصرف لحماية عائلتك؟',
              situationEn: 'Temperature soaring indoors with crowds feeling dizzy. How do you protect your family?',
              visualTheme: 'heat',
              hintAr: 'توجّه فوراً نحو المخارج الخارجي وشراء المياه للترطيب',
              hintEn: 'Head directly to air-conditioned vehicles/exits and hydrate',
              options: [
                ScenarioOption(
                  id: 'opt_h5_1_a',
                  stepId: 'step_h5_1',
                  textAr: 'الشراء السريع لمياه الشرب والخروج المبكر للمركبة المكيفة وتجنب الازدحام',
                  textEn: 'Obtain drinking water immediately and exit building calmly to cooled vehicle',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ مغادرة المكان المغلق الحار تمنع حالات الإجهاد الحراري الجماعي.',
                  explanationEn: 'Safe action; leaving hot unventilated space averts mass heat exhaustion.',
                  consequenceAr: 'خرجت العائلة بأمان وتجنبتم الدوار والإغماء.',
                  consequenceEn: 'Family safely exited before suffering heat fatigue.',
                ),
                ScenarioOption(
                  id: 'opt_h5_1_b',
                  stepId: 'step_h5_1',
                  textAr: 'البقاء في الأدوار العلوية والتسوق كالمعتاد',
                  textEn: 'Stay on upper floors and continue shopping normally',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ الحرارة ترتفع للأعلى بالصالات المغلقة مما يضاعف خطر الإنهاك الحراري.',
                  explanationEn: 'Dangerous; heat rises upward inside buildings accelerating dehydration and fainting.',
                  consequenceAr: 'شعرت العائلة بغثيان ودوار شديد من شدة السخونة.',
                  consequenceEn: 'Family members suffered dizziness from trapped upper floor heat.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_heat_6',
          categoryId: 'heat',
          titleAr: 'شاهدت طفلاً محتجزاً داخل مركبة مغلقة في مواقف الشارع',
          titleEn: 'Child Trapped inside Sealed Car in Sunlit Parking',
          descriptionAr: 'أثناء مرورك بالمواقف تحت الشمس، لاحظت طفلاً يبكي ومحتجزاً داخل سيارة مغلقة النوافذ والمحرك مطفأ.',
          descriptionEn: 'Noticed a crying infant trapped inside a locked parked car in direct sunlight with engine off.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          steps: [
            ScenarioStep(
              id: 'step_h6_1',
              scenarioId: 'sc_heat_6',
              stepOrder: 1,
              situationAr: 'الحرارة داخل السيارة قد تتجاوز 60°C والطفل يظهر عليه الإرهاق الشديد. ما الإجراء الفوري؟',
              situationEn: 'In-car temp can top 60°C and child shows extreme lethargy. What is the emergency action?',
              visualTheme: 'heat',
              hintAr: 'اتصل بالطوارئ 911 فوراً ويكسر زجاج النافذة البعيدة عن الطفل إن كان غير مغمى عليه',
              hintEn: 'Call 911 immediately and break the window farthest from child if in severe distress',
              options: [
                ScenarioOption(
                  id: 'opt_h6_1_a',
                  stepId: 'step_h6_1',
                  textAr: 'الاتصال بالشرطة 911 فوراً وكباش كسر النافذة البعيدة عن الطفل برفق لإخراجه وتظليله ورشه بالماء',
                  textEn: 'Call 911 immediately, break the window farthest from child to rescue him, move to shade and hydrate',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء منقذ للحياة؛ حرارة المركبة المغلقة ترتفع بسرعة قاتلة للأطفال وتتطلب التدخل الفوري.',
                  explanationEn: 'Life-saving move; locked car interior reaches lethal heat levels for toddlers in minutes.',
                  consequenceAr: 'تم إخراج الطفل وتبريده حتى وصول إسعاف الهلال الأحمر.',
                  consequenceEn: 'Child rescued in nick of time and cooled down until paramedics arrived.',
                ),
                ScenarioOption(
                  id: 'opt_h6_1_b',
                  stepId: 'step_h6_1',
                  textAr: 'البحث عن صاحب السيارة في المحلات المجاورة أولاً الانتظار عودته',
                  textEn: 'Walk around neighboring shops first looking for the car owner',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ إضاعة الوقت في البحث قد تسبب ضربة شمس قاتلة للطفل بالداخل.',
                  explanationEn: 'Fatal delay; wasting minutes searching for owner leads to heatstroke death inside car.',
                  consequenceAr: 'تأخر الوقت وتدهورت حالة الطفل الصحبة.',
                  consequenceEn: 'Critical time was lost worsening child condition.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_heat_7',
          categoryId: 'heat',
          titleAr: 'الإجهاد الحراري والإنهاك أثناء التمرين في الطقس الرطب',
          titleEn: 'Heat Exhaustion During Humid Outdoor Exercise',
          descriptionAr: 'أثناء ممارسة المشي في ممشى ساحلي برطوبة عالية وحرارة مرتفعة، شعرت بتعرق كثيف ودوار وشحوب الوجه.',
          descriptionEn: 'Walking on coastal trail during high humidity and temperature causes heavy sweating and dizziness.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          steps: [
            ScenarioStep(
              id: 'step_h7_1',
              scenarioId: 'sc_heat_7',
              stepOrder: 1,
              situationAr: 'بدأت تشعر بعدم التوازن وزغللة العينين. ما الإجراء الفوري لتفادي ضربة الشمس؟',
              situationEn: 'You feel unstable with blurred vision. What is the immediate preventative step?',
              visualTheme: 'heat',
              hintAr: 'توقف عن التمرين فوراً، واجلس في مكان مكيف وشرب السوائل',
              hintEn: 'Stop exercise immediately, sit in air-conditioned room and sip fluids',
              options: [
                ScenarioOption(
                  id: 'opt_h7_1_a',
                  stepId: 'step_h7_1',
                  textAr: 'التوقف الفوري عن الجري، والجلوس في مكان مكيف أو مظلل، وشرب الماء المحتوي على أملاح تبريد',
                  textEn: 'Stop exercising immediately, rest in an air-conditioned or shaded spot, and sip electrolyte water',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ إيقاف النشاط والترطيب بالأملاح يمنع تطور الإجهاد الحراري إلى ضربة شمس.',
                  explanationEn: 'Correct step; stopping physical effort and replenishing electrolytes prevents full heat stroke.',
                  consequenceAr: 'استعادت أجهزة الجسم توازنها وزالت أعراض الدوار.',
                  consequenceEn: 'Body equilibrium recovered and dizziness subsided.',
                ),
                ScenarioOption(
                  id: 'opt_h7_1_b',
                  stepId: 'step_h7_1',
                  textAr: 'مواصلة الجري وزيادة السرعة لتخطي مرحلة التعب',
                  textEn: 'Push through the fatigue and increase running speed to finish workout',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ الإصرار على التمرين أثناء الإنهاك الحراري يسبب الفشل الحراري والتلف العضوي.',
                  explanationEn: 'Dangerous; pushing body during heat exhaustion leads to collapse and organ distress.',
                  consequenceAr: 'حدث إغماء وسقوط مفاجئ على الممشى.',
                  consequenceEn: 'Collapsed suddenly on walking track from heat exhaustion.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_heat_8',
          categoryId: 'heat',
          titleAr: 'انفجار بنك طاقة (PowerBank) في السيارة بسبب أشعة الشمس',
          titleEn: 'PowerBank Battery Explosion inside Hot Car',
          descriptionAr: 'تركت شاحن متنقل (باور بنك) فوق طابلوه السيارة ورجعت لجد تصاعد دخان وانفجار الخلية الليثيوم.',
          descriptionEn: 'Lithium powerbank left on hot car dashboard swells and explodes under intense sun glare.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          steps: [
            ScenarioStep(
              id: 'step_h8_1',
              scenarioId: 'sc_heat_8',
              stepOrder: 1,
              situationAr: 'البطارية تخرج دخاناً كثيفاً وشرراً داخل المقاعد. كيف تسيطر على الحريق؟',
              situationEn: 'Battery smoking heavily and sparking on seat fabric. How to extinguish lithium fire?',
              visualTheme: 'heat',
              hintAr: 'افتح الأبواب لتهوية الدخان السام واستخدم طفاية السيارة البودرة',
              hintEn: 'Open doors to vent toxic fumes and use car dry powder extinguisher',
              options: [
                ScenarioOption(
                  id: 'opt_h8_1_a',
                  stepId: 'step_h8_1',
                  textAr: 'فتح الأبواب لتهوية الدخان، واستخدام طفاية حريق السيارة البودرة لإخماد البطارية وتجنب استنشاق الدخان',
                  textEn: 'Open car doors to vent toxic smoke, deploy car powder extinguisher directly onto battery',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'تصرف صحيح؛ بطاريات الليثيوم تطلق غازات حارقة وسامة، والبودرة تسيطر على الاشتعال.',
                  explanationEn: 'Correct procedure; lithium fires vent toxic gases and dry chemical powder smothers thermal fire.',
                  consequenceAr: 'انطفأ حريق البطارية وتم سحبها بأمان للخارج.',
                  consequenceEn: 'Battery fire suppressed safely and car ventilated.',
                ),
                ScenarioOption(
                  id: 'opt_h8_1_b',
                  stepId: 'step_h8_1',
                  textAr: 'أخذ البطارية المشتعلة بيدك المكشوفة وإلقائها خارج النافذة',
                  textEn: 'Grab the burning hot lithium battery with bare hands to hurl it out window',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر شديد؛ حرارة البطارية المشتعلة تتجاوز 500°C وتسبب حروقاً بالغة وانفجار بالأيدي.',
                  explanationEn: 'Severe danger; flaming lithium battery exceeds 500°C causing third degree hand burns.',
                  consequenceAr: 'تعرضت الأيدي لحروق حادة وانفجرت الخلية الثانوية.',
                  consequenceEn: 'Hands suffered severe burn injury from thermal runaway blast.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_heat_9',
          categoryId: 'heat',
          titleAr: 'ضربة حرارية لفني صيانة يعمل في السطح المفتوح',
          titleEn: 'Thermal Exhaustion of Maintenance Technician on Roof',
          descriptionAr: 'أثناء صيانة مكيفات السطح ظهيرة الصيف، اشتكى الفني من ثقل بالرأس وغثيان وسقط جالساً.',
          descriptionEn: 'Technician repairing rooftop AC in summer afternoon heat complains of headache and drops to floor.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
          steps: [
            ScenarioStep(
              id: 'step_h9_1',
              scenarioId: 'sc_heat_9',
              stepOrder: 1,
              situationAr: 'الفني غير قادر على الوقوف على السطح المباشر للشمس. كيف تسعفه؟',
              situationEn: 'Technician unable to stand on scorching roof. How to deliver first aid?',
              visualTheme: 'heat',
              hintAr: 'انقله لداخل المبنى المكيف ورش جسمه بالماء ورفع قدميه',
              hintEn: 'Move indoor to air-conditioned area, apply cool water compress and elevate feet',
              options: [
                ScenarioOption(
                  id: 'opt_h9_1_a',
                  stepId: 'step_h9_1',
                  textAr: 'مساعدة الفني للدخول فوراً للممر الداخلي المكيف، وتبريد رأسه وجسمه بضغطات ماء بارد ورفع قدميه قليلاً',
                  textEn: 'Assist technician inside air-conditioned corridor, apply cool wet cloths to head and elevate feet',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إسعاف ممتاز؛ نقل الفني من السطح الحار وتبريده مع رفع القدمين يدعم الدورة الدموية للمخ.',
                  explanationEn: 'Excellent first aid; relocating from sunlit roof and elevating legs restores cerebral blood flow.',
                  consequenceAr: 'استعاد الفني وعيه واستقرت مؤشرات العلامات الحيوية.',
                  consequenceEn: 'Technician regained full orientation and vital signs stabilized.',
                ),
                ScenarioOption(
                  id: 'opt_h9_1_b',
                  stepId: 'step_h9_1',
                  textAr: 'إعطائه وجبة دسمة وقهوة ساخنة لزيادة نشاطه',
                  textEn: 'Serve him a heavy meal and hot coffee to boost his energy',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر؛ الكافيين والوجبات الثقيلة تزيد الجفاف وتجهد الجهاز الدوري في حالات الإنهاك.',
                  explanationEn: 'Dangerous; caffeine and heavy food aggravate dehydration and strain circulatory system.',
                  consequenceAr: 'تفاقم الغثيان وزاد الجفاف.',
                  consequenceEn: 'Nausea worsened due to dehydration from coffee.',
                ),
              ],
            ),
          ],
        ),
"""

print("Added Heat scenarios code successfully")
