import os

content = r'''import '../../models/category.dart';
import '../../models/scenario.dart';
import '../../models/scenario_step.dart';
import '../../models/scenario_option.dart';
import '../../models/badge.dart';
import '../../models/knowledge_article.dart';
import '../../models/emergency_contact.dart';
import '../../models/user_profile.dart';

class InitialSeedData {
  // 1. Initial Categories (10 Categories)
  static List<SimulationCategory> get categories => [
        const SimulationCategory(
          id: 'fire',
          titleAr: 'الحرائق والإطفاء',
          titleEn: 'Fire & Extinguishment',
          descriptionAr: 'التصرف السليم أثناء اندلاع الحرائق واستخدام أدوات الإطفاء والإخلاء',
          descriptionEn: 'Proper actions during fire outbreaks and using firefighting tools',
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
        ),
        const SimulationCategory(
          id: 'flood',
          titleAr: 'السيول والأمطار الغزيرة',
          titleEn: 'Floods & Torrential Rains',
          descriptionAr: 'إجراءات السلامة أثناء جريان الأودية والأنفاق وتجمع المياه',
          descriptionEn: 'Safety procedures during flash floods and heavy rainfalls',
          icon: 'water',
          colorHex: 0xFF0288D1,
        ),
        const SimulationCategory(
          id: 'heat',
          titleAr: 'الحرارة الشديدة وضربات الشمس',
          titleEn: 'Extreme Heat & Sunstroke',
          descriptionAr: 'التعامل مع الإنهاك الحراري والوقاية أثناء الموجات الحارة صيفاً',
          descriptionEn: 'Handling heat exhaustion and sunstrokes during peak summer',
          icon: 'wb_sunny',
          colorHex: 0xFFF57C00,
        ),
        const SimulationCategory(
          id: 'traffic',
          titleAr: 'حوادث الطرق والسلامة المرورية',
          titleEn: 'Road Accidents & Traffic Safety',
          descriptionAr: 'الاستجابة الأولى للحوادث على الطرق السريعة وتأمين الموقع',
          descriptionEn: 'First response to highway accidents and site securing',
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
        ),
        const SimulationCategory(
          id: 'home',
          titleAr: 'السلامة المنزلية والغاز',
          titleEn: 'Home & Gas Safety',
          descriptionAr: 'تسرب الغاز، حرائق المطبخ، والتسمم بالمنظفات داخل المنزل',
          descriptionEn: 'Gas leaks, kitchen fires, and household chemical hazards',
          icon: 'home',
          colorHex: 0xFF43A047,
        ),
        const SimulationCategory(
          id: 'evacuation',
          titleAr: 'الإخلاء والتدافع في المنشآت',
          titleEn: 'Evacuation & Crowd Safety',
          descriptionAr: 'إدارة الهروب الآمن والتعامل مع التدافع والفعاليات الكبرى',
          descriptionEn: 'Safe crowd evacuation and emergency exit procedures',
          icon: 'corporate_fare',
          colorHex: 0xFFD81B60,
        ),
        const SimulationCategory(
          id: 'electric',
          titleAr: 'المخاطر والصدمات الكهربائية',
          titleEn: 'Electrical Hazards & Shocks',
          descriptionAr: 'التعامل مع الماس الكهربائي، الصعق، والوقاية من أحمال التماس',
          descriptionEn: 'Handling electrical short circuits, shocks, and overloaded plugs',
          icon: 'bolt',
          colorHex: 0xFFFBC02D,
        ),
        const SimulationCategory(
          id: 'emergency_kit',
          titleAr: 'الاستعداد للطوارئ وحقيبة الإسعاف',
          titleEn: 'Emergency Readiness & First Aid',
          descriptionAr: 'تجهيز خطة الطوارئ الأسرية وحقيبة الإمدادات والإسعافات الأولية',
          descriptionEn: 'Family emergency planning, survival kit, and basic first aid',
          icon: 'medical_services',
          colorHex: 0xFF00897B,
        ),
        const SimulationCategory(
          id: 'desert_safety',
          titleAr: 'سلامة الكشتات والرحلات البرية',
          titleEn: 'Saudi Desert & Trip Safety',
          descriptionAr: 'التعامل مع السيول المنقولة بالأودية، الانغراز بالرمال، والنجاة بالصحراء',
          descriptionEn: 'Flash flood wadi safety, desert sand stuck recovery, and wilderness survival',
          icon: 'landscape',
          colorHex: 0xFFD97706,
        ),
        const SimulationCategory(
          id: 'cyber_safety',
          titleAr: 'أمن المعلومات والوقاية التقنية',
          titleEn: 'Cybersecurity & Tech Safety',
          descriptionAr: 'الوقاية من رسائل الاحتيال البنكي، اختراق الواتساب، وتأمين كاميرات المنزل',
          descriptionEn: 'Protection against phishing SMS, banking fraud, 2FA leaks, and IoT security',
          icon: 'security',
          colorHex: 0xFF6366F1,
        ),
      ];

  // 2. Default User Profiles
  static List<UserProfile> get defaultProfiles => [];

  // 3. Official Saudi Emergency Contacts
  static List<EmergencyContact> get emergencyContacts => [
        const EmergencyContact(
          id: 'ec_911',
          nameAr: 'المركز الوطني للعمليات الأمنية (911)',
          nameEn: 'National Center for Security Operations (911)',
          number: '911',
          icon: 'emergency',
          descriptionAr: 'الرقم الموحد للطوارئ الأمنية والمرورية والدفاع المدني في مناطق المملكة',
          descriptionEn: 'Unified emergency number for security, traffic, and civil defense',
          priority: 1,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_998',
          nameAr: 'الدفاع المدني السعودي',
          nameEn: 'Saudi Civil Defense',
          number: '998',
          icon: 'local_fire_department',
          descriptionAr: 'طوارئ الحرائق، الإنقاذ، حوادث الاحتجاز، مخاطر السيول، والانهيارات',
          descriptionEn: 'Firefighting, search and rescue, flood rescue, and structural collapses',
          priority: 2,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_997',
          nameAr: 'الهلال الأحمر السعودي',
          nameEn: 'Saudi Red Crescent Authority',
          number: '997',
          icon: 'medical_services',
          descriptionAr: 'الإسعاف الطبي الطارئ، الحالات الحرجة، النقل الإسعافي، والإصابات',
          descriptionEn: 'Emergency medical ambulance and paramedic urgent response',
          priority: 3,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_996',
          nameAr: 'القوات الخاصة لأمن الطرق',
          nameEn: 'Special Highway Security Forces',
          number: '996',
          icon: 'add_road',
          descriptionAr: 'حوادث وبلاغات الطرق السريعة بين مدن ومحافظات المملكة',
          descriptionEn: 'Highway security and accident assistance across Saudi intercity roads',
          priority: 4,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_999',
          nameAr: 'الدوريات الأمنية (الشرطة)',
          nameEn: 'Police Patrols',
          number: '999',
          icon: 'local_police',
          descriptionAr: 'البلاغات الجنائية، حفظ الأمن العام، والاستجابة الأمنية الفورية',
          descriptionEn: 'Criminal reporting, public safety, and immediate police response',
          priority: 5,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_933',
          nameAr: 'طوارئ الكهرباء (الشركة السعودية للكهرباء)',
          nameEn: 'Saudi Electricity Emergency',
          number: '933',
          icon: 'bolt',
          descriptionAr: 'انقطاع التيار، شرر المحولات، سقوط الكابلات الكهربائية والأعمدة',
          descriptionEn: 'Power outages, sparking transformers, and fallen electrical wires',
          priority: 6,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_939',
          nameAr: 'طوارئ المياه (شركة المياه الوطنية)',
          nameEn: 'National Water Emergency',
          number: '939',
          icon: 'water_damage',
          descriptionAr: 'انكسار خطوط المياه الرئيسية، تسرب الشبكات العامة، والفيضانات المائية',
          descriptionEn: 'Main water line bursts and public network leaks',
          priority: 7,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_najm',
          nameAr: 'شركة نجم لخدمات الحوادث',
          nameEn: 'Najm Insurance Services',
          number: '199033',
          icon: 'car_crash',
          descriptionAr: 'مباشرة الحوادث المرورية المؤمنة في المملكة وتخطيط الحادث',
          descriptionEn: 'Reporting insured vehicular traffic accidents and damage assessment',
          priority: 8,
          isOfficial: true,
        ),
        const EmergencyContact(
          id: 'ec_937',
          nameAr: 'مركز صحة (وزارة الصحة)',
          nameEn: 'MOH Medical Consultation (937)',
          number: '937',
          icon: 'support_agent',
          descriptionAr: 'الاستشارات الطبية العاجلة، حالات التسمم، وتوجيه لأقرب مركز طوارئ',
          descriptionEn: 'Urgent medical consultations, poison control advice, and hospital directions',
          priority: 9,
          isOfficial: true,
        ),
      ];

  // 4. Gamification Badges
  static List<SafetyBadge> get defaultBadges => [
        const SafetyBadge(
          id: 'b_first_sim',
          code: 'first_sim',
          titleAr: 'أول محاكاة',
          titleEn: 'First Simulation',
          descriptionAr: 'أكملت أول سيناريو تدريبي بنجاح ودخلت عالم الجاهزية',
          descriptionEn: 'Successfully completed your first training scenario',
          icon: 'play_circle_filled',
          requiredXp: 50,
          categoryId: 'general',
        ),
        const SafetyBadge(
          id: 'b_fire_hero',
          code: 'fire_hero',
          titleAr: 'مدافع الحريق',
          titleEn: 'Fire Defender',
          descriptionAr: 'أظهرت معرفة تامة بإجراءات إخلاء المباني وإطفاء الحرائق',
          descriptionEn: 'Demonstrated complete mastery in fire evacuation and response',
          icon: 'local_fire_department',
          requiredXp: 150,
          categoryId: 'fire',
        ),
        const SafetyBadge(
          id: 'b_flood_guard',
          code: 'flood_guard',
          titleAr: 'درع السيول',
          titleEn: 'Flood Guard',
          descriptionAr: 'اتخذت القرارات الصائبة لحماية النفس والمركبة من مخاطر السيول',
          descriptionEn: 'Made correct decisions safeguarding life and vehicle during floods',
          icon: 'tsunami',
          requiredXp: 150,
          categoryId: 'flood',
        ),
        const SafetyBadge(
          id: 'b_fast_responder',
          code: 'fast_responder',
          titleAr: 'مستجيب سريع',
          titleEn: 'Quick Responder',
          descriptionAr: 'استجبت في أقل من 10 ثوانٍ واتخذت قراراً آثراً بحكمة',
          descriptionEn: 'Responded in under 10 seconds making a safe decision',
          icon: 'bolt',
          requiredXp: 100,
          categoryId: 'general',
        ),
        const SafetyBadge(
          id: 'b_ready_champion',
          code: 'ready_champion',
          titleAr: 'بطل الجاهزية',
          titleEn: 'Readiness Champion',
          descriptionAr: 'حققت درجة جاهزية شاملة تفوق 90% عبر جميع مجالات السلامة',
          descriptionEn: 'Achieved an overall preparedness score above 90% across all domains',
          icon: 'military_tech',
          requiredXp: 500,
          categoryId: 'general',
        ),
        const SafetyBadge(
          id: 'b_desert_master',
          code: 'desert_master',
          titleAr: 'بطل البر والسيول',
          titleEn: 'Desert & Wadi Master',
          descriptionAr: 'أظهرت حكمة بالغة في تجنب السيول المنقولة والانغراز التكتيكي في البر',
          descriptionEn: 'Mastered wadi flash flood avoidance and desert navigation tactics',
          icon: 'landscape',
          requiredXp: 200,
          categoryId: 'desert_safety',
        ),
        const SafetyBadge(
          id: 'b_cyber_shield',
          code: 'cyber_shield',
          titleAr: 'درع الحماية الرقمية',
          titleEn: 'Cyber Shield Master',
          descriptionAr: 'كشفت محاولات الاحتيال البنكي وحميت حسابات الأسرة وكاميراتها',
          descriptionEn: 'Identified phishing scams and protected family accounts & IoT devices',
          icon: 'security',
          requiredXp: 200,
          categoryId: 'cyber_safety',
        ),
      ];

  // 5. Complete Interactive Multi-Station Scenarios (5 Stations Each)
  static List<Scenario> get initialScenarios => [
        // ==========================================
        // DESERT SAFETY SCENARIO 1: 5 STATIONS
        // ==========================================
        Scenario(
          id: 'sc_desert_1',
          categoryId: 'desert_safety',
          titleAr: 'انغراز المركبة في الكثبان الرملية (التغريز بالدهناء) - 5 محطات',
          titleEn: 'Vehicle Stuck in Sand Dunes - 5 Stations',
          descriptionAr: 'رحلة إنقاذ متكاملة من 5 محطات لتأمين واستخراج المركبة وتفادي الهلاك بالصحراء.',
          descriptionEn: 'Comprehensive 5-station scenario to recover stuck 4WD in deep desert sand dunes.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'landscape',
          colorHex: 0xFFD97706,
          steps: [
            // Station 1
            ScenarioStep(
              id: 'step_des1_1',
              scenarioId: 'sc_desert_1',
              stepOrder: 1,
              situationAr: 'المحطة 1: غوص الإطارات في الرمال المتحركة ودورانها في مكانها. ما تصرفك الأولي؟',
              situationEn: 'Station 1: Tires sink into soft sand spinning freely. Initial reaction?',
              visualTheme: 'desert_safety',
              hintAr: 'توقف عن الضغط على دواسة البنزين فوراً لمنع حفر الرمال أكثر',
              hintEn: 'Stop pressing gas pedal immediately to avoid digging deeper',
              options: [
                ScenarioOption(
                  id: 'opt_des1_1_a',
                  stepId: 'step_des1_1',
                  textAr: 'التوقف الفوري عن الضغط على البنزين والترجل لفحص الرمال وضغط الإطارات',
                  textEn: 'Stop pressing gas immediately and inspect sand depth and tire pressure',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'ممتاز؛ التوقف السريع يمنع وصول شاصي السيارة إلى سطح الرمال.',
                  explanationEn: 'Excellent; stopping prevents vehicle chassis from resting on sand.',
                  outcomeSummaryAr: 'منعت غوص السيارة بالكامل وتوجهت للمحطة الثانية.',
                  outcomeSummaryEn: 'Prevented total bottoming out, proceeding to Station 2.',
                ),
                ScenarioOption(
                  id: 'opt_des1_1_b',
                  stepId: 'step_des1_1',
                  textAr: 'مواصلة الضغط الجائر على البنزين بأقصى سرعة للخروج بقوة المحرك',
                  textEn: 'Floor gas pedal continuously hoping to break free with raw engine power',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'خطأ؛ الدوران الجائر يحفر الرمال ويُعلق السيارة على بطنها.',
                  explanationEn: 'Error; aggressive tire spinning buries the vehicle completely.',
                  outcomeSummaryAr: 'تسببت في تعليق المركبة بالكامل.',
                  outcomeSummaryEn: 'Vehicle chassis settled onto deep sand.',
                ),
              ],
            ),
            // Station 2
            ScenarioStep(
              id: 'step_des1_2',
              scenarioId: 'sc_desert_1',
              stepOrder: 2,
              situationAr: 'المحطة 2: الإطارات متضخمة بالهواء الزائد (35 PSI). ما مقدار التنسيم المطلوب؟',
              situationEn: 'Station 2: Tires are overinflated at 35 PSI. What pressure target is needed?',
              visualTheme: 'desert_safety',
              hintAr: 'تخفيض الضغط لـ 10-15 PSI يضاعف مسطح احتكاك الإطار بالرمال',
              hintEn: 'Lowering pressure to 10-15 PSI doubles tire surface contact on sand',
              options: [
                ScenarioOption(
                  id: 'opt_des1_2_a',
                  stepId: 'step_des1_2',
                  textAr: 'تنسيم جميع الإطارات إلى 10-15 PSI باستخدام مفك أو عيار التنسيم',
                  textEn: 'Deflate all four tires down to 10-15 PSI using tire deflator gauge',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'تصرف احترافي؛ يزيد التلامس ويعطي الإطار مرونة للسير فوق الكثبان.',
                  explanationEn: 'Pro move; increases traction footprint for sand dune travel.',
                  outcomeSummaryAr: 'تفرغ الهواء وتم تجهيز الإطارات للمحطة 3.',
                  outcomeSummaryEn: 'Tires deflated properly, moving to Station 3.',
                ),
                ScenarioOption(
                  id: 'opt_des1_2_b',
                  stepId: 'step_des1_2',
                  textAr: 'إبقاء ضغط الإطارات مرتفعاً كما هو لعدم إتلاف الجنوط',
                  textEn: 'Keep high pressure unchanged to avoid rim damage',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'خطأ؛ الضغط المرتفع يمنع التلامس ويجعل الإطار يقطع الرمال كالسيف.',
                  explanationEn: 'Error; high pressure cuts through sand like a blade.',
                  outcomeSummaryAr: 'استمرت الإطارات بالانغراز.',
                  outcomeSummaryEn: 'Tires continued sinking continuously.',
                ),
              ],
            ),
            // Station 3
            ScenarioStep(
              id: 'step_des1_3',
              scenarioId: 'sc_desert_3',
              stepOrder: 3,
              situationAr: 'المحطة 3: إزالة الكثبان حول الإطارات وتجهيز الواح الإنقاذ (الماكس تراك). كيف تثبتها؟',
              situationEn: 'Station 3: Clearing sand and placing recovery tracks. How to position them?',
              visualTheme: 'desert_safety',
              hintAr: 'الحفر أمام الإطارات ودفع الصفائح بزاوية 45 درجة تحت الإطار الموجه',
              hintEn: 'Digging in front of tires and wedging tracks at 45 degree angle under tread',
              options: [
                ScenarioOption(
                  id: 'opt_des1_3_a',
                  stepId: 'step_des1_3',
                  textAr: 'الحفر أمام الإطارات لتسهيل المسار ودفع صفائح الماكس تراك بزاوية 45 درجة تحت الإطار',
                  textEn: 'Dig sand in front of tires and wedge recovery tracks at 45° angle under tread',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'ممتاز؛ يمنح الإطار زاوية ثبات فورية للصعود فوق ألواح التماس.',
                  explanationEn: 'Excellent; provides instant tire grip to climb onto recovery tracks.',
                  outcomeSummaryAr: 'تم تثبيت الألواح بنجاح والانتقال للمحطة 4.',
                  outcomeSummaryEn: 'Tracks secured successfully, proceeding to Station 4.',
                ),
                ScenarioOption(
                  id: 'opt_des1_3_b',
                  stepId: 'step_des1_3',
                  textAr: 'رمي الألواح بعيداً عن الإطارات دون حفر الرمال',
                  textEn: 'Throw recovery tracks loosely far from tires without clearing sand',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'خطأ؛ الألواح ستتطاير بالهواء دون أن تمسك بها الإطارات.',
                  explanationEn: 'Error; loose tracks will shoot backward without gripping tire.',
                  outcomeSummaryAr: 'تطايرت الألواح دون نتيجة.',
                  outcomeSummaryEn: 'Tracks shot out without providing traction.',
                ),
              ],
            ),
            // Station 4
            ScenarioStep(
              id: 'step_des1_4',
              scenarioId: 'sc_desert_1',
              stepOrder: 4,
              situationAr: 'المحطة 4: تشغيل الدبل (4WD). ما الوضعية الأنسب للانطلاق فوق صفائح التماس؟',
              situationEn: 'Station 4: Engaging 4WD mode. Which transfer case gear to select for recovery?',
              visualTheme: 'desert_safety',
              hintAr: 'استخدام الدبل الخفيف 4H أو الثقيل 4L بلمسات بنزين هادئة ومتزنة',
              hintEn: 'Engage 4L/4H low gear with smooth progressive throttle control',
              options: [
                ScenarioOption(
                  id: 'opt_des1_4_a',
                  stepId: 'step_des1_4',
                  textAr: 'تعشيق الدبل الثقيل 4L مع ضبط المقود بشكل مستقيم والضغط المتزن على دواسة البنزين',
                  textEn: 'Engage 4L low range 4WD, keep steering straight, apply smooth progressive throttle',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'اختيار محترف؛ يقدم أعلى عزم سحب هادئ دون تفحيط الإطارات.',
                  explanationEn: 'Professional choice; provides maximum torque without tire slippage.',
                  outcomeSummaryAr: 'صعدت السيارة فوق الألواح وخرجت للمحطة 5.',
                  outcomeSummaryEn: 'Vehicle mounted tracks smoothly, advancing to Station 5.',
                ),
                ScenarioOption(
                  id: 'opt_des1_4_b',
                  stepId: 'step_des1_4',
                  textAr: 'القيادة بالدفع الخلفي العادي 2H وتدوير عجلة القيادة يميناً ويساراً بسرعة',
                  textEn: 'Drive in 2WD mode rapidly jerking steering wheel back and forth',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'خطأ؛ الدفع الثنائي لا يكفي للخروج من الرمال العميقة.',
                  explanationEn: 'Error; 2WD lacks traction required for deep sand recovery.',
                  outcomeSummaryAr: 'فشلت محاولة الخروج بالدفع الثنائي.',
                  outcomeSummaryEn: 'Recovery failed under 2WD power.',
                ),
              ],
            ),
            // Station 5
            ScenarioStep(
              id: 'step_des1_5',
              scenarioId: 'sc_desert_1',
              stepOrder: 5,
              situationAr: 'المحطة 5: تحركت السيارة وخرجت من الحفرة. كيف تؤمن موضع التوقف النهائِي؟',
              situationEn: 'Station 5: Vehicle freed from sand. Where to bring car to safe complete stop?',
              visualTheme: 'desert_safety',
              hintAr: 'عدم التوقف في الرمال الناعمة المجاورة، واختيار أرض صخرية صلبة مرتفعة',
              hintEn: 'Do not stop in soft adjacent sand, reach solid elevated rocky ground before stopping',
              options: [
                ScenarioOption(
                  id: 'opt_des1_5_a',
                  stepId: 'step_des1_5',
                  textAr: 'مواصلة السير ببطء دون توقف حتى الوصول لأرض صلبة مرتفعة، ثم إعادة نفخ الإطارات',
                  textEn: 'Keep moving steadily until reaching hard elevated ground before stopping to reinflate tires',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 35,
                  safetyScore: 100,
                  explanationAr: 'إتمام ناجح؛ التوقف على الأرض الصلبة يمنع التغريز المجدد ويضمن سلامة الرحلة.',
                  explanationEn: 'Successful completion; stopping on hard ground prevents re-stucking and secures trip.',
                  outcomeSummaryAr: 'أكملت محطات الإنقاذ بنجاح ووصلت لبر الأمان.',
                  outcomeSummaryEn: 'Completed all 5 recovery stations safely.',
                ),
                ScenarioOption(
                  id: 'opt_des1_5_b',
                  stepId: 'step_des1_5',
                  textAr: 'التوقف الفوري والمفاجئ بجانب الحفرة نفسها في وسط الرمال الناعمة',
                  textEn: 'Stop immediately beside the same soft sand hole',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'خطأ؛ التوقف في الرمل الناعم يعيد غوص الإطارات فوراً.',
                  explanationEn: 'Error; stopping in soft sand immediately re-buries tires.',
                  outcomeSummaryAr: 'انغرزت السيارة مجدداً في الرمل.',
                  outcomeSummaryEn: 'Vehicle sank again in adjacent soft sand.',
                ),
              ],
            ),
          ],
        ),

        // ==========================================
        // CYBER SAFETY SCENARIO 1: 5 STATIONS
        // ==========================================
        Scenario(
          id: 'sc_cyber_1',
          categoryId: 'cyber_safety',
          titleAr: 'رسالة احتيال بنكية ومحاولة اختراق الحساب - 5 محطات',
          titleEn: 'Bank Phishing SMS & Fraud Response - 5 Stations',
          descriptionAr: 'محاكاة سيبرانية متكاملة من 5 محطات لكشف رسائل الاحتيال، حماية البيانات، وإبلاغ السلطات.',
          descriptionEn: 'Full 5-station cyber security scenario to counter banking fraud SMS and account takeover.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'security',
          colorHex: 0xFF6366F1,
          steps: [
            // Station 1
            ScenarioStep(
              id: 'step_cyb1_1',
              scenarioId: 'sc_cyber_1',
              stepOrder: 1,
              situationAr: 'المحطة 1: وصلتك رسالة SMS: "تم تجميد حسابك، اضغط الرابط لتحديث بياناتك". ما أول تصرف؟',
              situationEn: 'Station 1: SMS arrived: "Account frozen, click link to update". Initial action?',
              visualTheme: 'cyber_safety',
              hintAr: 'البنوك السعودية الرسمية لا ترسل روابط تحديث بيانات عبر رسائل SMS إطلاقاً',
              hintEn: 'Saudi official banks NEVER send data update links via SMS text messages',
              options: [
                ScenarioOption(
                  id: 'opt_cyb1_1_a',
                  stepId: 'step_cyb1_1',
                  textAr: 'تجاهل الرابط، فحص رابط العنوان، وعدم إدخال أي معلومات بنكية',
                  textEn: 'Ignore link, inspect URL address, and refrain from entering bank credentials',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'وعي ممتاز؛ كشفت محاولة الهندسة الاجتماعية وتجنبت الفخ.',
                  explanationEn: 'Excellent awareness; detected social engineering attempt avoiding phishing link.',
                  outcomeSummaryAr: 'حميت بياناتك وانتقلت للمحطة 2.',
                  outcomeSummaryEn: 'Secured credentials, proceeding to Station 2.',
                ),
                ScenarioOption(
                  id: 'opt_cyb1_1_b',
                  stepId: 'step_cyb1_1',
                  textAr: 'النقر على الرابط بسرعة وإدخال رقم بطاقتك لتفادي تجميد الحساب',
                  textEn: 'Click link quickly and submit card details to prevent account freezing',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'اختراق مالي؛ أدخلت معلوماتك البنكية في صفحة احتيالية مزيفة.',
                  explanationEn: 'Financial breach; submitted credentials to fake cloned phishing portal.',
                  outcomeSummaryAr: 'تم تعريض البطاقة البنكية للاحتيال.',
                  outcomeSummaryEn: 'Card credentials compromised to scammers.',
                ),
              ],
            ),
            // Station 2
            ScenarioStep(
              id: 'step_cyb1_2',
              scenarioId: 'sc_cyber_1',
              stepOrder: 2,
              situationAr: 'المحطة 2: وردك اتصال من شخص يزعم أنه موظف البنك ويطلب رمز OTP المكون من 6 أرقام.',
              situationEn: 'Station 2: Call received from someone claiming bank staff requesting 6-digit OTP code.',
              visualTheme: 'cyber_safety',
              hintAr: 'رمز OTP سر شخصي، وموظف البنك الحقيقي لا يطلبه منك إطلاقاً',
              hintEn: 'OTP is strictly private; legitimate bank representatives NEVER request it',
              options: [
                ScenarioOption(
                  id: 'opt_cyb1_2_a',
                  stepId: 'step_cyb1_2',
                  textAr: 'رفض إعطاء رمز OTP نهائياً، وإغلاق المكالمة فوراً',
                  textEn: 'Refuse giving OTP code strictly and hang up call immediately',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'حماية رقمية عالية؛ حظرت الوصول المباشر لحسابك البنكي.',
                  explanationEn: 'High digital defense; blocked direct unauthorized account access.',
                  outcomeSummaryAr: 'منعت سرقة الرصيد والانتقال للمحطة 3.',
                  outcomeSummaryEn: 'Prevented fund theft, advancing to Station 3.',
                ),
                ScenarioOption(
                  id: 'opt_cyb1_2_b',
                  stepId: 'step_cyb1_2',
                  textAr: 'إملاء رمز OTP للمتصل لتأكيد هويتك',
                  textEn: 'Read OTP code aloud to caller to confirm your identity',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'اختراق كامل؛ سرقة رمز OTP تمنح المحتال دخولاً كاملاً للحساب.',
                  explanationEn: 'Total compromise; sharing OTP grants hacker full account takeover access.',
                  outcomeSummaryAr: 'تم اختراق الحساب وسحب الأموال.',
                  outcomeSummaryEn: 'Account hijacked and money transferred out.',
                ),
              ],
            ),
            // Station 3
            ScenarioStep(
              id: 'step_cyb1_3',
              scenarioId: 'sc_cyber_1',
              stepOrder: 3,
              situationAr: 'المحطة 3: كيف تقوم بالإبلاغ الرسمي عن الرقم والرسالة النصية الاحتيالية؟',
              situationEn: 'Station 3: How to officially report fraud phone number and SMS text message?',
              visualTheme: 'cyber_safety',
              hintAr: 'إعادة توجيه الرسالة النصية إلى الرقم المجاني لمكافحة الاحتيال البنكي (330330)',
              hintEn: 'Forward phishing SMS to official free anti-fraud reporting number (330330)',
              options: [
                ScenarioOption(
                  id: 'opt_cyb1_3_a',
                  stepId: 'step_cyb1_3',
                  textAr: 'إعادة توجيه الرسالة النصية والرقم إلى خدمة مكافحة الاحتيال (330330) وتطبيق كلنا أمن',
                  textEn: 'Forward SMS and number to anti-fraud 330330 and report on Kollona Aman app',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'مواطنة رقمية مسؤولة؛ الإبلاغ يحظر الأرقام الاحتيالية ويحمي الآخرين.',
                  explanationEn: 'Responsible cyber citizenship; reporting blocks fraud lines protecting others.',
                  outcomeSummaryAr: 'تم رفع البلاغ بنجاح والانتقال للمحطة 4.',
                  outcomeSummaryEn: 'Fraud report submitted, moving to Station 4.',
                ),
                ScenarioOption(
                  id: 'opt_cyb1_3_b',
                  stepId: 'step_cyb1_3',
                  textAr: 'حذف الرسالة وتنسي الموضوع دون تقديم بلاغ للجهات المعنية',
                  textEn: 'Delete message and ignore reporting to security authorities',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'تفويت فرصة؛ عدم الإبلاغ يسمح للمحتال باستمرار استهداف الآخرين.',
                  explanationEn: 'Missed opportunity; failing to report lets scammers target other victims.',
                  outcomeSummaryAr: 'استمر الرقم في ممارسة الاحتيال.',
                  outcomeSummaryEn: 'Fraud number remained active targeting others.',
                ),
              ],
            ),
            // Station 4
            ScenarioStep(
              id: 'step_cyb1_4',
              scenarioId: 'sc_cyber_1',
              stepOrder: 4,
              situationAr: 'المحطة 4: فحص وتأمين التطبيق البنكي الخاص بك على الجوال. ما الخطوة الأجدر؟',
              situationEn: 'Station 4: Securing your mobile banking app settings. Most vital security step?',
              visualTheme: 'cyber_safety',
              hintAr: 'تغيير كلمة المرور وتأمين البصمة الحيوية وإغلاق الجلسات النشطة',
              hintEn: 'Change password, enable biometric login, and terminate open active sessions',
              options: [
                ScenarioOption(
                  id: 'opt_cyb1_4_a',
                  stepId: 'step_cyb1_4',
                  textAr: 'تغيير كلمة السر، تفعيل البصمة الحيوية، ومراجعة قائمة الأجهزة المرتبطة بحسابك',
                  textEn: 'Change password, enable biometric authentication, and audit authorized connected devices',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 30,
                  safetyScore: 100,
                  explanationAr: 'تحصين ممتاز؛ مراجعة الأجهزة تضمن عدم وجود أي طرف غريب متصل بالحساب.',
                  explanationEn: 'Solid hardening; auditing devices ensures zero unauthorized sessions exist.',
                  outcomeSummaryAr: 'تم تحصين التطبيق البنكي والانتقال للمحطة 5.',
                  outcomeSummaryEn: 'App secured, advancing to Station 5.',
                ),
                ScenarioOption(
                  id: 'opt_cyb1_4_b',
                  stepId: 'step_cyb1_4',
                  textAr: 'ترك إعدادات الحساب القديمة كما هي دون مراجعة الجلسات',
                  textEn: 'Keep old security settings unchanged without reviewing sessions',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'ثغرة قائمة؛ الجلسات القديمة قد تظل مفتوحة لدى أطراف أخرى.',
                  explanationEn: 'Security gap; unreviewed sessions may remain active on external devices.',
                  outcomeSummaryAr: 'ظلت الثغرة الأفضل قائمة بالحساب.',
                  outcomeSummaryEn: 'Vulnerability remained in account settings.',
                ),
              ],
            ),
            // Station 5
            ScenarioStep(
              id: 'step_cyb1_5',
              scenarioId: 'sc_cyber_1',
              stepOrder: 1,
              situationAr: 'المحطة 5: تفعيل المصادقة الثنائية (2FA) وتوعية العائلة بالاحتيال. كيف تكتمل الجاهزية؟',
              situationEn: 'Station 5: Enabling 2FA and educating family on scams. Complete readiness step?',
              visualTheme: 'cyber_safety',
              hintAr: 'تفعيل المصادقة الثنائية وتثقيف كبار السن بالأسرة يضمن حماية شاملة للجميع',
              hintEn: 'Enabling 2FA and educating seniors in household ensures complete family defense',
              options: [
                ScenarioOption(
                  id: 'opt_cyb1_5_a',
                  stepId: 'step_cyb1_5',
                  textAr: 'تفعيل المصادقة الثنائية (2FA) ونشر رسائل التوعية الأسرية لحماية كبار السن من الاحتيال',
                  textEn: 'Enable 2FA authentication and educate family seniors regarding phishing calls',
                  isSafe: true,
                  speedScore: 25,
                  xpReward: 35,
                  safetyScore: 100,
                  explanationAr: 'جاهزية فائقة؛ المصادقة الثنائية والتوعية الأسرية يغلقان كافة منافذ اختراق الأسرة.',
                  explanationEn: 'Supreme readiness; 2FA and family awareness close all cyber attack vectors.',
                  outcomeSummaryAr: 'أكملت محطات الأمان الـ 5 بنجاح وحققت وسام الجاهزية الرقمية.',
                  outcomeSummaryEn: 'Completed all 5 cyber security stations achieving full readiness badge.',
                ),
                ScenarioOption(
                  id: 'opt_cyb1_5_b',
                  stepId: 'step_cyb1_5',
                  textAr: 'تجاهل تفعيل المصادقة الثنائية وعدم تنبيه الأهل بخدع الرسائل',
                  textEn: 'Ignore 2FA activation and omit warning family members about scam trends',
                  isSafe: false,
                  speedScore: 0,
                  xpReward: 0,
                  safetyScore: 0,
                  explanationAr: 'ضعف أمني؛ ترك الأهل دون توعية يعرضهم للوقوع بأول رسالة احتيال.',
                  explanationEn: 'Security weakness; leaving family uninformed leaves them vulnerable to phishing.',
                  outcomeSummaryAr: 'ظلت الأسرة عرضة لمخاطر الاحتيال.',
                  outcomeSummaryEn: 'Family members remained vulnerable to cyber fraud.',
                ),
              ],
            ),
          ],
        ),
      ];
}
'''

with open(r'c:\Users\omara\Desktop\m proj\lib\core\database\initial_seed_data.dart', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done writing initial_seed_data.dart")
