import sys

# Scenarios for FLOOD, HEAT, HOME, EVACUATION, ELECTRIC, EMERGENCY_KIT
scenarios_code = """
        // FLOOD (4 to 9)
        Scenario(
          id: 'sc_flood_4',
          categoryId: 'flood',
          titleAr: 'ارتفاع منسوب السيول الجارفة داخل استراحة في مجرى وادي',
          titleEn: 'Rising Torrential Flash Flood inside Valley Farm',
          descriptionAr: 'أثناء تواجدك في استراحة جبلية، انهمر المطر بغزارة وبدأت مياه الوادي بالارتفاع والدخول للصحن الخارجي.',
          descriptionEn: 'Heavy rain causes flash flood waters to breach a valley farmhouse courtyard.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'water',
          colorHex: 0xFF0288D1,
          steps: [
            ScenarioStep(
              id: 'step_fl4_1',
              scenarioId: 'sc_flood_4',
              stepOrder: 1,
              situationAr: 'المياه تغمر الفناء الخارجي وتزداد اندفاعاً وتصل للركب. كيف تحمي من معك؟',
              situationEn: 'Floodwater covers courtyard reaching knee height rapidly. How do you protect everyone?',
              visualTheme: 'flood',
              hintAr: 'اصعد فوراً للسطح أو الأماكن المرتفعة المبنية بالخرسانة',
              hintEn: 'Evacuate immediately to roof or concrete high ground',
              options: [
                ScenarioOption(
                  id: 'opt_fl4_1_a',
                  stepId: 'step_fl4_1',
                  textAr: 'الصعود المباشر لسطح المبنى الخرساني المرتفع وتجنب البقاء بالدور الأرضي أو ركوب السيارة',
                  textEn: 'Move immediately to the reinforced concrete roof, avoiding ground floor and vehicles',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ الأماكن المرتفعة الخرسانية تحميك من قوة انجراف السيل.',
                  explanationEn: 'Correct response; high elevated concrete structure keeps occupants above rushing water.',
                  consequenceAr: 'وصل الجميع للسطح بسلام وتواصلتم مع والدفاع المدني 911.',
                  consequenceEn: 'Everyone reached roof safely and alerted Civil Defense 911.',
                ),
                ScenarioOption(
                  id: 'opt_fl4_1_b',
                  stepId: 'step_fl4_1',
                  textAr: 'الركض نحو السيارة في الفناء ومحاولة قيادتها للخروج عبر مجرى الوادي',
                  textEn: 'Run to car in courtyard and attempt driving out through valley stream',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ ارتفاع 30 سم من مياه السيل الجارفة كفيل بسحب وانقلاب المركبات.',
                  explanationEn: 'Dangerous; just 30cm of rushing water floats and sweeps vehicles away.',
                  consequenceAr: 'انجرفت السيارة بفعل قوة التيار واحتُجزت بالمياه.',
                  consequenceEn: 'Car was swept away and trapped by raging current.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_flood_5',
          categoryId: 'flood',
          titleAr: 'سحب مياه السيل لمركبة جرفتها المياه أمامك',
          titleEn: 'Rescuing Occupants of Swept Vehicle in Torrent',
          descriptionAr: 'شاهدت مركبة يحاول سائقها عبور الشعيب فجرفتها مياه السيل وانحشرت بجانب شجرة كبيرة وسط الوادي.',
          descriptionEn: 'Vehicle attempts crossing flooded stream and gets swept into a large tree mid-river.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'water',
          colorHex: 0xFF0288D1,
          steps: [
            ScenarioStep(
              id: 'step_fl5_1',
              scenarioId: 'sc_flood_5',
              stepOrder: 1,
              situationAr: 'السائق محتجز بالداخل والمياه تغمر النوافذ. كيف تتصرف دون تعريض نفسك للغرق؟',
              situationEn: 'Driver trapped inside with water rising up windows. How do you help safely?',
              visualTheme: 'flood',
              hintAr: 'اتصل بـ 911 واستخدم حبال الإنقاذ من الضفة الجافة دون النزول للسيل',
              hintEn: 'Call 911 and use ropes from dry bank without entering current',
              options: [
                ScenarioOption(
                  id: 'opt_fl5_1_a',
                  stepId: 'step_fl5_1',
                  textAr: 'الابلاغ الفوري لـ 911 وتثبيت حبل إنقاذ متين بشجرة على ضفة الوادي وإلقائه للسائق',
                  textEn: 'Immediately report to 911, secure heavy rescue rope to tree on dry bank and throw to driver',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ الإنقاذ من الضفة يضمن عدم انجراف المنقذ وسرعة وصول المساعدة.',
                  explanationEn: 'Safe protocol; rescuing from dry land prevents rescuer from being swept away.',
                  consequenceAr: 'تمكن السائق من الإمساك بالحبل حتى وصول فرقة إنقاذ الدفاع المدني.',
                  consequenceEn: 'Driver held onto rope safely until Civil Defense water rescue team arrived.',
                ),
                ScenarioOption(
                  id: 'opt_fl5_1_b',
                  stepId: 'step_fl5_1',
                  textAr: 'القفز والسباحة المباشرة وسط مياه السيل الجارفة للوصول للمركبة',
                  textEn: 'Jump directly into the raging torrent and swim toward the stranded vehicle',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر وشديد الفتك؛ سرعة وقوة السيل الصخري تجرف أقوى السباحين وتؤدي للغرق.',
                  explanationEn: 'Fatal hazard; swift current and debris sweep away even master swimmers.',
                  consequenceAr: 'جرف التيار القوي السباح ولم يتمكن من المقاومة.',
                  consequenceEn: 'Current swept rescuer downstream posing double drowning casualty.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_flood_6',
          categoryId: 'flood',
          titleAr: 'انهيار صخري وركامي على خط جبلي أثناء الأمطار',
          titleEn: 'Mountain Landslide & Rockfall During Downpour',
          descriptionAr: 'أثناء السير في طريق عقبة جبلية، تساقطت حجارة وصخور صغيرة على مقدمة الطريق بسبب هطول الأمطار.',
          descriptionEn: 'Driving mountain pass when loose rocks and debris tumble onto road ahead.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'water',
          colorHex: 0xFF0288D1,
          steps: [
            ScenarioStep(
              id: 'step_fl6_1',
              scenarioId: 'sc_flood_6',
              stepOrder: 1,
              situationAr: 'الصخور تتساقط والممر يضيق. ما الإجراء الفوري لتفادي الانهيار الأكبر؟',
              situationEn: 'Rockfall accelerating and lane constricting. What is immediate safe action?',
              visualTheme: 'flood',
              hintAr: 'التوقف في مكان آمن بعيداً عن حافة الجبل والتراجع بحذر',
              hintEn: 'Stop at safe distance from cliff face and reverse carefully',
              options: [
                ScenarioOption(
                  id: 'opt_fl6_1_a',
                  stepId: 'step_fl6_1',
                  textAr: 'التوقف الفوري مسافة 50 متراً قبل موقع التساقط، والتراجع للخلف والتنحي لجانب الطريق الآمن',
                  textEn: 'Stop immediately 50 meters clear of rockfall zone, reverse carefully and signal 996',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء حكيم؛ الابتعاد عن سفح الجبل المنهار يمنع سقوط الصخور الكبيرة على سقف السيارة.',
                  explanationEn: 'Wise action; staying back from falling slope prevents massive boulders from crushing car.',
                  consequenceAr: 'تفاديت الانهيار الكلي وحافظت على سلامة ركاب المركبة.',
                  consequenceEn: 'Avoided major landslide and protected vehicle occupants.',
                ),
                ScenarioOption(
                  id: 'opt_fl6_1_b',
                  stepId: 'step_fl6_1',
                  textAr: 'زيادة السرعة والاندفاع بسرعة فائقة للمرور تحت الصخور المتساقطة',
                  textEn: 'Floor the gas pedal to speed directly underneath falling rocks',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الاندفاع تحت الانهيار يضعك تحت الصخور الكبيرة الساقطة من أعلى.',
                  explanationEn: 'Hazardous; speeding under slide exposes car to heavy falling boulders.',
                  consequenceAr: 'سقطت صخرة ضخمة على مقدمة المركبة وتسببت بأضرار بليغة.',
                  consequenceEn: 'Large boulder hit vehicle hood causing severe damage.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_flood_7',
          categoryId: 'flood',
          titleAr: 'اقتراب مياه السيل من المحول الكهربائي الأرضي للحي',
          titleEn: 'Floodwaters Approaching Ground Level Transformer Substation',
          descriptionAr: 'ارتفع المنسوب في الشارع وبدأت المياه بالاقتراب من غاطس محول الكهربائي الأرضي المجاور للمنازل.',
          descriptionEn: 'Floodwater in neighborhood street reaches base of ground electrical transformer substation.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'water',
          colorHex: 0xFF0288D1,
          steps: [
            ScenarioStep(
              id: 'step_fl7_1',
              scenarioId: 'sc_flood_7',
              stepOrder: 1,
              situationAr: 'المياه تلامس المحول الكهربائي وهناك احتمالية لتكهرب المياه بالشارع. كيف تتصرف؟',
              situationEn: 'Water contacts transformer base risking electrification of flooded street. How to react?',
              visualTheme: 'flood',
              hintAr: 'تجنب المشي في المياه الملامسة للمحول وابلغ 933 وطوارئ 911',
              hintEn: 'Never step into water near transformers; call 933 & 911',
              options: [
                ScenarioOption(
                  id: 'opt_fl7_1_a',
                  stepId: 'step_fl7_1',
                  textAr: 'الابتعاد الفوري والبقاء في الأدوار المرتفعة، والاتصال بطوارئ الكهرباء 933 والإنقاذ 911 لعزل المنطقة',
                  textEn: 'Stay indoors on upper floors, immediately call Electricity 933 and 911 to isolate grid block',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ دخول المياه للمحولات يكرب الشارع بالكامل وقد يسبب الصعق القاتل للمارة.',
                  explanationEn: 'Correct protocol; water touching live transformers energizes flooded street leading to electrocution.',
                  consequenceAr: 'فصلت شركة الكهرباء التيار عن المحول وسلِم جميع السكان.',
                  consequenceEn: 'Utility remotely de-energized transformer preventing electric shock casualties.',
                ),
                ScenarioOption(
                  id: 'opt_fl7_1_b',
                  stepId: 'step_fl7_1',
                  textAr: 'الخوض في المياه نحو المحول لمحاولة تغطيته بشراع بلاستيكي',
                  textEn: 'Wade through floodwater toward transformer to try covering it with plastic tarp',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'شديد الخورة والفتك؛ الخوض في مياه ملامسة لمحول كهربائي يسبب الصعق الفوري.',
                  explanationEn: 'Lethal danger; stepping in water touching live high-voltage gear causes fatal shock.',
                  consequenceAr: 'تعرض الشارع لشرارة كهربائية وكاد يحدث صعق حاد.',
                  consequenceEn: 'Electrical arc energized water posing severe electrocution danger.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_flood_8',
          categoryId: 'flood',
          titleAr: 'مداهمة الصواعق الرعدية الكثيفة في مكان مفتوح',
          titleEn: 'Severe Lightning Storm in Open Flat Land',
          descriptionAr: 'أثناء تواجدك في منطقة برية مفتوحة، بدأت عاصفة رعدية شديدة وانطلقت صواعق متتالية تضرب الأرض.',
          descriptionEn: 'Stuck in open flat desert terrain when violent thunderstorm brings frequent ground lightning strikes.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'water',
          colorHex: 0xFF0288D1,
          steps: [
            ScenarioStep(
              id: 'step_fl8_1',
              scenarioId: 'sc_flood_8',
              stepOrder: 1,
              situationAr: 'أنت في السهل المفتوح دون وجود أبنية والقشعريرة تسري في جلدك (مؤشر اقتراب الصاعقة). ماذا تفعل؟',
              situationEn: 'In open plain with no buildings and hair stands on end (sign of imminent strike). What to do?',
              visualTheme: 'flood',
              hintAr: 'انخفض وتكور دون الاستلقاء المباشر على الأرض أو الوقوف قرب الأشجار',
              hintEn: 'Crouch down low on balls of feet; do not lie flat or stand under isolated trees',
              options: [
                ScenarioOption(
                  id: 'opt_fl8_1_a',
                  stepId: 'step_fl8_1',
                  textAr: 'الانخفاض وحني الرأس بين الركبتين والوقوف على أطراف أصابع القدمين (Crouch) أو اللجوء داخل المركبة',
                  textEn: 'Crouch low with feet together, head tucked, or take shelter inside a hard-topped vehicle',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ وضعية التكور تقرر مساحة التلامس وتمنع جذب الصاعقة، والمركبة تعمل كقفس فاراداي.',
                  explanationEn: 'Safe physics move; lightning crouch minimizes ground contact and cars act as safe Faraday cages.',
                  consequenceAr: 'حفظت نفسك وسلِم الجسد حتى زوال العاصفة الرعدية.',
                  consequenceEn: 'Remained safe from direct strike until storm passed over.',
                ),
                ScenarioOption(
                  id: 'opt_fl8_1_b',
                  stepId: 'step_fl8_1',
                  textAr: 'الوقوف تحت شجرة منفردة مرتفعة أو رفع عمود معدني للإشارة',
                  textEn: 'Stand directly underneath a tall isolated tree or raise a metal pole',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الأشجار المرتفعة والمعادن تجذب الصاعقة الرعدية مباشرة وتسبب الوفاة.',
                  explanationEn: 'Hazardous; tall trees and metal objects attract lightning ground strikes directly.',
                  consequenceAr: 'ضربت صاعقة قريبة الشجرة وتسببت باحتراقها.',
                  consequenceEn: 'Lightning struck tree directly causing severe shock blast.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_flood_9',
          categoryId: 'flood',
          titleAr: 'انقطاع الاتصالات الجوالة أثناء السيول بالصحراء',
          titleEn: 'Cellular Signal Blackout During Desert Flash Flood',
          descriptionAr: 'توقفت شبكة الجوال تماماً أثناء احتجازك في منطقة مرتفعة بالصحراء بسبب الأمطار والسيول.',
          descriptionEn: 'Mobile network completely dies while stranded on high ground during desert flash flood.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'water',
          colorHex: 0xFF0288D1,
          steps: [
            ScenarioStep(
              id: 'step_fl9_1',
              scenarioId: 'sc_flood_9',
              stepOrder: 1,
              situationAr: 'لا توجد تغطية اتصال والسيل يحيط بالمكان المرتفع. كيف ترسل إشارة استغاثة لفرق الإنقاذ الجوي؟',
              situationEn: 'No mobile signal and flood surrounds high mound. How do you signal aerial search teams?',
              visualTheme: 'flood',
              hintAr: 'استخدم الصفارة والعواكس الضوئية أو قماش فاقع اللون من أعلى نقطة',
              hintEn: 'Use emergency whistle, mirrors/flashlights or bright cloth from highest visible point',
              options: [
                ScenarioOption(
                  id: 'opt_fl9_1_a',
                  stepId: 'step_fl9_1',
                  textAr: 'استخدام صفارة الطوارئ وتلويح بقماش فاقع اللون واستخدام مرآة العاكس الضوئي من أعلى نقطة في التلة',
                  textEn: 'Use emergency whistle, wave high-visibility bright fabric, and reflect sunlight/flashlight from hill top',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'تصرف كشفي ممتاز؛ الإشارات البصرية والصوتية تمكّن طائرات البحث من تحديد موقعك بسهولة.',
                  explanationEn: 'Excellent survival action; visual and audio signals allow search aircraft to pinpoint location.',
                  consequenceAr: 'شاهدت طائرة طوارئ الدفاع المدني الإشارة وتم تحديد الموقع والإنقاذ.',
                  consequenceEn: 'Civil Defense helicopter spotted visual signal and completed air rescue.',
                ),
                ScenarioOption(
                  id: 'opt_fl9_1_b',
                  stepId: 'step_fl9_1',
                  textAr: 'المخاطرة وقطع مياه السيل بالقدمين للبحث عن برج تغطية قريب',
                  textEn: 'Risk wading on foot through swift floodwaters to search for a cell tower',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر وشديد الفتك؛ قطع السيول بالقدمين يؤدي للانجراف والغرق المؤكد.',
                  explanationEn: 'Fatal error; wading through flash floods leads to drowning.',
                  consequenceAr: 'جرف السيل القدمين وسقط في مجرى الوادي.',
                  consequenceEn: 'Fast current swept feet away creating drowning emergency.',
                ),
              ],
            ),
          ],
        ),
"""

print("Added Flood scenarios successfully")
