import sys

new_scenarios_code = """
        // ==========================================
        // ADDED SCENARIOS (TRIPLE CONTENT 3X - 9 SCENARIOS PER CATEGORY)
        // ==========================================

        // TRAFFIC (4 to 9)
        Scenario(
          id: 'sc_traffic_4',
          categoryId: 'traffic',
          titleAr: 'انفجار إطار المركبة المفاجئ على سرعة 120 كم/س',
          titleEn: 'Sudden Tire Blowout at 120 km/h on Highway',
          descriptionAr: 'أثناء قيادتك على طريق الرياض - السريع، انفجر الإطار الخلفي فجأة وسمعت صوتاً مدوياً واهتزت عجلة القيادة.',
          descriptionEn: 'Driving on highway when a rear tire suddenly blows out with heavy vehicle vibration.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          steps: [
            ScenarioStep(
              id: 'step_tr4_1',
              scenarioId: 'sc_traffic_4',
              stepOrder: 1,
              situationAr: 'انفجر الإطار وبدأت المركبة بالانحراف الخفيف مع صوت ضجيج قوي. ماذا تفعل فورا؟',
              situationEn: 'Tire blew out and car started veering slightly. What is your immediate action?',
              visualTheme: 'traffic',
              hintAr: 'تجنب الضغط الفجائي على المكابح لمنع الانقلاب',
              hintEn: 'Avoid sudden braking to prevent rollover',
              options: [
                ScenarioOption(
                  id: 'opt_tr4_1_a',
                  stepId: 'step_tr4_1',
                  textAr: 'الإمساك بعجلة القيادة بكلتا اليدين بقوة ورفع القدم تدريجياً عن دواسة الوقود دون الضغط على المكابح',
                  textEn: 'Grip steering wheel firmly with both hands, ease off gas pedal gradually without touching brakes',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الصحيح والآمن؛ الضغط على المكابح عند انفجار الإطار يسبب اختلال توازن المركبة وانقلابها الفوري.',
                  explanationEn: 'Correct response; braking during blowout causes loss of control and instant rollover.',
                  consequenceAr: 'حافظت على استقرار المركبة وبدأت سرعتها بالانخفاض بأمان.',
                  consequenceEn: 'Vehicle maintained stability and speed decreased safely.',
                ),
                ScenarioOption(
                  id: 'opt_tr4_1_b',
                  stepId: 'step_tr4_1',
                  textAr: 'الضغط بقوة وعلى الفور على دواسة المكابح لإيقاف السيارة بسرعة',
                  textEn: 'Slam hard on the brake pedal to stop quickly',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الكبح المفاجئ يسبب اختلال كلي في مركز التوازن وانحراف المركبة وانقلابها.',
                  explanationEn: 'Dangerous; hard braking causes immediate loss of control and rollover.',
                  consequenceAr: 'انحرفت السيارة بشدة وكادت تتدهور على الطريق.',
                  consequenceEn: 'Car veered violently risking severe rollover.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_traffic_5',
          categoryId: 'traffic',
          titleAr: 'تعطل المكابح في المنحدرات الجبلية (الهدا/عسير)',
          titleEn: 'Brake Failure Down Mountain Passes (Hada/Asir)',
          descriptionAr: 'أثناء نزولك من العقبة الجبلية الملتوية، لاحظت تحجر دواسة الفرامل وعدم استجابتها لتبطيء السيارة.',
          descriptionEn: 'Descending steep mountain pass when brake pedal solidifies and stops responding.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          steps: [
            ScenarioStep(
              id: 'step_tr5_1',
              scenarioId: 'sc_traffic_5',
              stepOrder: 1,
              situationAr: 'السيارة تتسارع مع المنحدر والمكابح لا تستجيب. كيف تتباطأ بأمان؟',
              situationEn: 'Vehicle is accelerating down steep slope with no brakes. How do you decelerate safely?',
              visualTheme: 'traffic',
              hintAr: 'استخدم الغيارات العكسية للمحرك (الفرملة بالمحرك)',
              hintEn: 'Use engine braking downshifting',
              options: [
                ScenarioOption(
                  id: 'opt_tr5_1_a',
                  stepId: 'step_tr5_1',
                  textAr: 'تغيير ناقل الحركة تدريجياً للغيار الأقل (Engine Braking) وشحن فرملة اليد بحذر تدريجي',
                  textEn: 'Downshift gears incrementally to use engine braking and apply handbrake slowly',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'الفرملة بالمحرك تخفض السرعة بأمان وتمنع احتراق واستنزاف الفرامل في المنحدرات.',
                  explanationEn: 'Engine braking reduces speed safely preventing total runaway momentum.',
                  consequenceAr: 'انخفضت سرعة المركبة وتمكنت من التوجيه نحو مسار الرمل الاحتياطي للطوارئ.',
                  consequenceEn: 'Speed reduced and driver safely steered into emergency runaway ramp.',
                ),
                ScenarioOption(
                  id: 'opt_tr5_1_b',
                  stepId: 'step_tr5_1',
                  textAr: 'إطفاء المحرك فوراً وسحب مفتاح التشغيل لإيقاف السيارة',
                  textEn: 'Turn off the engine immediately and pull the ignition key out',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر قاتل؛ إطفاء المحرك يقفل عجلة القيادة ويمنع التوجيه بالكامل ويقطع الهيدروليك.',
                  explanationEn: 'Fatal error; turning off engine locks steering wheel and hydraulic assist.',
                  consequenceAr: 'انقفل المقود وانعدمت السيطرة تماماً على المنعطف الجبلي.',
                  consequenceEn: 'Steering locked up leading to loss of control on sharp curve.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_traffic_6',
          categoryId: 'traffic',
          titleAr: 'التعطل الفجائي في المسار الأيسر السريع',
          titleEn: 'Sudden Breakdown in Fast Left Lane',
          descriptionAr: 'توقف محرك سيارتك فجأة وأنت في مسار أقصى اليسار على طريق سريع مكتظ.',
          descriptionEn: 'Engine suddenly stalls while driving in the leftmost fast lane on a busy highway.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          steps: [
            ScenarioStep(
              id: 'step_tr6_1',
              scenarioId: 'sc_traffic_6',
              stepOrder: 1,
              situationAr: 'المحرك انطفأ والسيارة تتباطأ في المسار الأسرع. ما هو التصرف الأنسب فوراً؟',
              situationEn: 'Engine died in the fast lane. What is your immediate safe move?',
              visualTheme: 'traffic',
              hintAr: 'استغل الزخم المتبقي للانتقال بأمان للأكتاف اليمين',
              hintEn: 'Use remaining inertia to safely coast to right shoulder',
              options: [
                ScenarioOption(
                  id: 'opt_tr6_1_a',
                  stepId: 'step_tr6_1',
                  textAr: 'تشغيل أضواء التحذير (الرباعي) واستغلال اندفاع السيارة التدريجي للانتقال للأكتاف اليمنى بأمان',
                  textEn: 'Turn on hazard lights and use remaining momentum to steer to the right shoulder safely',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ تنبيه المركبات خلفك وتفريغ الطريق من المسارات السريعة يمنع الحوادث.',
                  explanationEn: 'Correct; warning traffic behind and clearing fast lanes avoids rear-end crashes.',
                  consequenceAr: 'وصلت للمسار الآمن بالأكتاف اليمنى وقمت بالاتصال بأمن الطرق 996.',
                  consequenceEn: 'Safely reached right shoulder and alerted Highway Patrol 996.',
                ),
                ScenarioOption(
                  id: 'opt_tr6_1_b',
                  stepId: 'step_tr6_1',
                  textAr: 'الخروج فوراً من السيارة والوقوف أمامها بالمسار الأيسر لطلب المساعدة',
                  textEn: 'Step out of car immediately and stand in front of it in fast lane to flag help',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'شديد الخطورة؛ الوقوف في مسار سريع يعرضك للدهس الفوري من السيارات القادمة.',
                  explanationEn: 'Extremely hazardous; standing in fast lane causes high-speed impact collision.',
                  consequenceAr: 'تعرضت المركبة لصدم خلفي عنيف من السيارات القادمة بسرعة.',
                  consequenceEn: 'Car was violently rear-ended by oncoming high-speed traffic.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_traffic_7',
          categoryId: 'traffic',
          titleAr: 'اندلاع حريق في محرك مركبة مجاورة وسط الزحام',
          titleEn: 'Engine Fire in Neighboring Car During Traffic Jam',
          descriptionAr: 'أثناء توقفك في ازدحام مروري، لاحظت تصاعد ألسنة لهب ودخان من أسفل كبوت المركبة التي أمامك.',
          descriptionEn: 'Trapped in traffic gridlock when flames start erupting under the hood of car ahead.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          steps: [
            ScenarioStep(
              id: 'step_tr7_1',
              scenarioId: 'sc_traffic_7',
              stepOrder: 1,
              situationAr: 'الدخان يزداد والسائق في السيارة الأمامية يبدو غير منتبه للحريق. كيف تتدخل؟',
              situationEn: 'Smoke escalates and driver ahead appears unaware of fire under hood. How do you respond?',
              visualTheme: 'traffic',
              hintAr: 'نبه السائق بآلة التنبيه وحافظ على مسافة أمان',
              hintEn: 'Warn driver with horn while keeping safe distance',
              options: [
                ScenarioOption(
                  id: 'opt_tr7_1_a',
                  stepId: 'step_tr7_1',
                  textAr: 'استخدام المنبه والإشارات لتنبيه السائق، وركن مركبتك بمشافة أمان واستخدام طفاية الحريق إن أمكن',
                  textEn: 'Use horn and lights to alert driver, park at safe distance and assist with fire extinguisher if safe',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء مثالي؛ ينبه السائق للإخلاء ويضمن سلامتك ويساعد بالطفاية المساندة.',
                  explanationEn: 'Optimal procedure; alerts victim to evacuate while maintaining personal safety.',
                  consequenceAr: 'خرج السائق بأمان وتمت السيطرة على الحريق الأولية بطفاية السيارة.',
                  consequenceEn: 'Driver safely exited and fire was suppressed using car extinguisher.',
                ),
                ScenarioOption(
                  id: 'opt_tr7_1_b',
                  stepId: 'step_tr7_1',
                  textAr: 'فتح كبوت سيارته المشتعلة بقوة بيدك مباشرة لإطفائه بالماء',
                  textEn: 'Pop open the flaming car hood directly with bare hands to pour water inside',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ فتح الكبوت يزود النار بالأكسجين فيحدث انفجار لهبي يسبب حروقاً شديدة.',
                  explanationEn: 'Dangerous; opening flaming hood supplies oxygen causing fireball backdraft.',
                  consequenceAr: 'اندفعت كرة لهب شديدة واكتوت اليدين بالحرارة.',
                  consequenceEn: 'Fireball erupted burning hands and face.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_traffic_8',
          categoryId: 'traffic',
          titleAr: 'غمر المياه المفاجئ لنفق مروري أثناء الهطول الغزير',
          titleEn: 'Sudden Tunnel Inundation During Severe Rainfall',
          descriptionAr: 'أثناء دخولك نفور مروري، تفاجأت بارتفاع منسوب مياه الأمطار وتراكمها بسرعة حتى غمرت الإطارات.',
          descriptionEn: 'Entering a highway tunnel when sudden heavy rain pools deep water above wheel hubs.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          steps: [
            ScenarioStep(
              id: 'step_tr8_1',
              scenarioId: 'sc_traffic_8',
              stepOrder: 1,
              situationAr: 'المياه ترتفع بسرعة في النفق وتوقفت المحركات المحيطة. ماذا تفعل قبل انغلاق الأبواب؟',
              situationEn: 'Water is rapidly rising inside tunnel and cars are stalling. What do you do before doors lock?',
              visualTheme: 'traffic',
              hintAr: 'لا تتردد في غادر المركبة فوراً نحو مخرج النفق المرتفع',
              hintEn: 'Do not hesitate; abandon car immediately to high ground exit',
              options: [
                ScenarioOption(
                  id: 'opt_tr8_1_a',
                  stepId: 'step_tr8_1',
                  textAr: 'إيقاف المحرك، وفتح النوافذ، ومغادرة المركبة فوراً والصعود للأرصفة الجانبية المرتفعة للنفق',
                  textEn: 'Turn off engine, roll down windows, exit car immediately and head up tunnel emergency stairs',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف المنقذ للحياة؛ البقاء داخل السيارة يسبب الاحتجاز والغرق عند تعطل الكهرباء.',
                  explanationEn: 'Life saving move; remaining inside causes entrapment and drowning as water rises.',
                  consequenceAr: 'صعدت لدرج الإخلاء المرتفع بالنفق بأمان وتم إبلاغ 911.',
                  consequenceEn: 'Safely climbed elevated tunnel emergency escape stairs and called 911.',
                ),
                ScenarioOption(
                  id: 'opt_tr8_1_b',
                  stepId: 'step_tr8_1',
                  textAr: 'البقاء داخل المركبة وإغلاق النوافذ بالكامل وانتظار شفط المياه',
                  textEn: 'Stay inside car with all windows rolled up tight waiting for water to drain',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر قاتل؛ ارتفع المياه يضغط الأبواب ويحاصر السائق بالداخل مع انقطاع الكهرباء.',
                  explanationEn: 'Fatal mistake; rising water pressure seals doors shut trapping occupants inside.',
                  consequenceAr: 'تعطلت كهرباء السيارة واحتجزت الأبواب مع ارتفاع المنسوب.',
                  consequenceEn: 'Car electronics shorted locking occupants inside as water surged.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_traffic_9',
          categoryId: 'traffic',
          titleAr: 'اعترضت إبل سائبة الطريق ليلاً في خط نائي',
          titleEn: 'Stray Camels Crossing Remote Highway at Night',
          descriptionAr: 'تسويد الطريق النائي ليلاً وفجأة ظهرت جمل سائب على بعد مسافة قصيرة وسط المسار.',
          descriptionEn: 'Driving on unlit remote desert road at night when stray camel suddenly crosses path.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'directions_car',
          colorHex: 0xFF5E35B1,
          steps: [
            ScenarioStep(
              id: 'step_tr9_1',
              scenarioId: 'sc_traffic_9',
              stepOrder: 1,
              situationAr: 'الجمل يقطع الطريق أمامك مباشرة والمسافة قصيرة. كيف تتفادى اصطدامه الفتاك؟',
              situationEn: 'Camel is right in front of your lane. How do you avoid a fatal high-level impact?',
              visualTheme: 'traffic',
              hintAr: 'التوجيه نحو خلفية الجمل (الاتجاه الذي أتى منه)',
              hintEn: 'Steer toward the rear of the camel (behind its motion)',
              options: [
                ScenarioOption(
                  id: 'opt_tr9_1_a',
                  stepId: 'step_tr9_1',
                  textAr: 'التخفيف من السرعة فوراً والتوجيه باتجاه خلف الجمل (حيث كان يسير) وليس أمامه',
                  textEn: 'Brake firmly and steer toward the rear of the camel (the direction it walked from)',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'قاعدة سلامة؛ الجمل يتحرك للأمام دائماً، والتوجيه خلفه يضمن تفادي الاصطدام بالكامل.',
                  explanationEn: 'Safety rule; camels move forward, steering behind them prevents catastrophic impact.',
                  consequenceAr: 'تفاديت الجمل بنجاح دون الانحراف عن الطريق.',
                  consequenceEn: 'Successfully avoided the camel without veering off road.',
                ),
                ScenarioOption(
                  id: 'opt_tr9_1_b',
                  stepId: 'step_tr9_1',
                  textAr: 'التوجيه بسرعة إلى الأمام في الاتجاه الذي يركض إليه الجمل',
                  textEn: 'Steer sharply forward into the direction the camel is walking',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ التوجيه أمام الجمل يجعلك تصطدم به مباشرة حيث يتقدم ليمحو زجاج المركبة.',
                  explanationEn: 'Dangerous; steering ahead collides directly into moving camel crushing windshield.',
                  consequenceAr: 'حدث اصطدام مباشر بقوائم الجمل وسقط على الزجاج.',
                  consequenceEn: 'Direct impact occurred with camel landing on windshield.',
                ),
              ],
            ),
          ],
        ),

        // FIRE (4 to 9)
        Scenario(
          id: 'sc_fire_4',
          categoryId: 'fire',
          titleAr: 'اشتغال شاحن هاتف محمول متصل بالكهرباء في غرفة النوم',
          titleEn: 'Mobile Charger Fire Outbreak in Bedroom',
          descriptionAr: 'أثناء تواجدك في الصالة، انبعثت رائحة بلاستيك محترق من غرفة النوم وتبين اشتعال شاحن هاتف غير أصلي فوق الفراش.',
          descriptionEn: 'Burning plastic smell leads to discovery of cheap phone charger catching fire on bedroom mattress.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          steps: [
            ScenarioStep(
              id: 'step_f4_1',
              scenarioId: 'sc_fire_4',
              stepOrder: 1,
              situationAr: 'الشاحن يشتعل والنار بدأت تمسك بطرف الفراش. ما التصرف الأول الصحيح؟',
              situationEn: 'Charger flaming and igniting mattress edge. What is the immediate correct step?',
              visualTheme: 'fire',
              hintAr: 'افصل مصدر الكهرباء أولاً قبل الإطفاء',
              hintEn: 'Cut off electricity power before extinguishing',
              options: [
                ScenarioOption(
                  id: 'opt_f4_1_a',
                  stepId: 'step_f4_1',
                  textAr: 'فصل القاطع الكهربائي الرئيسي للغرفة فوراً ثم استخدام طفاية البودرة/ثاني أكسيد الكربون',
                  textEn: 'Switch off main room circuit breaker immediately, then use Powder/CO2 extinguisher',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف الآمن؛ عزل مصدر الكهرباء يمنع الصعق وسرعة السيطرة بالطفاية تلغي خطر السكيب.',
                  explanationEn: 'Safe procedure; isolating electrical supply prevents shock allowing safe extinguishment.',
                  consequenceAr: 'تمت السيطرة على الحريق في بدايته بسلام دون إصابات.',
                  consequenceEn: 'Fire successfully extinguished early without electrical hazards.',
                ),
                ScenarioOption(
                  id: 'opt_f4_1_b',
                  stepId: 'step_f4_1',
                  textAr: 'سكب سطل ماء مباشر على الشاحن المحترق وهو موصول بالكهرباء',
                  textEn: 'Pour a bucket of water directly onto burning charger while plugged in',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ سكب الماء على جهاز موصل بالكهرباء يسبب صعقاً كهربائياً حاداً وانتشار النار.',
                  explanationEn: 'Dangerous; pouring water on live electricity causes severe electrocution hazard.',
                  consequenceAr: 'حدثت شرارة وانفجار كهربائي حاد وتسبب بصعق.',
                  consequenceEn: 'Electric arc flash occurred causing shock injury.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_fire_5',
          categoryId: 'fire',
          titleAr: 'حريق قماش الديكور في صالة مناسبات مغلقة',
          titleEn: 'Fabric Decoration Fire in Enclosed Event Hall',
          descriptionAr: 'أثناء حضورك مناسبة، اشتعلت إحدى الستائر بواسطة شرر المؤثرات الضوئية وبدأ الدخان ينتشر بالصالة.',
          descriptionEn: 'Lighting spark ignites hall curtain wall decor causing smoke inside crowded venue.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          steps: [
            ScenarioStep(
              id: 'step_f5_1',
              scenarioId: 'sc_fire_5',
              stepOrder: 1,
              situationAr: 'الدخان يتصاعد بسرعة نحو السقف والناس بدأت تتدافع. كيف تتصرف لقيادة نفسك والآخرين؟',
              situationEn: 'Smoke rises fast toward ceiling as panic sets in. How do you navigate evacuation?',
              visualTheme: 'fire',
              hintAr: 'انخفض تحت مستوى الدخان واتجه لأقرب مخرج طوارئ مضاء',
              hintEn: 'Stay low below smoke layer and move to green exit sign',
              options: [
                ScenarioOption(
                  id: 'opt_f5_1_a',
                  stepId: 'step_f5_1',
                  textAr: 'الانخفاض وحني الجسد أسفل طبقة الدخان، والتوجه بهدوء نحو مخرج الطوارئ الأخضر الجانبي',
                  textEn: 'Crouch low underneath smoke layer, guiding others calmly to designated green side exit',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'تصرف احترافي؛ الهواء النقي يكون بالأرقاب السفلية والمخارج الجانبية تمنع اختناق التدافع.',
                  explanationEn: 'Professional safety move; breathable air sits low and side exits prevent crush.',
                  consequenceAr: 'خرجت والجميع بأمان دون استنشاق الغازات السامة.',
                  consequenceEn: 'Evacuated safely without inhaling toxic combustion fumes.',
                ),
                ScenarioOption(
                  id: 'opt_f5_1_b',
                  stepId: 'step_f5_1',
                  textAr: 'الوقوف منتصباً والصراخ بأعلى صوت والتراكض نحو المدخل الرئيسي المكتظ',
                  textEn: 'Stand straight up, scream loudly and rush toward the jammed main front entrance',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ الوقوف يعرضك لاستنشاق أول أكسيد الكربون السام والاندفاع للمدخل الرئيسي يسبب الدهس.',
                  explanationEn: 'Hazardous; standing straight causes inhalation of toxic carbon monoxide.',
                  consequenceAr: 'تعرضت للاختناق والتدافع الشديد عند البوابة.',
                  consequenceEn: 'Suffered toxic smoke inhalation and trampling at main door.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_fire_6',
          categoryId: 'fire',
          titleAr: 'اشتعال مقلاة الزيت العميق فوق الموقد بالمطبخ',
          titleEn: 'Deep Fryer Pan Oil Fire on Kitchen Stove',
          descriptionAr: 'أثناء الطهي بالمطبخ، ارتفعت حرارة الزيت واشتعلت مقلاة الزيت بلهب مرتفع وصل للشفاط.',
          descriptionEn: 'Overheated cooking oil catches fire in a deep pan on the kitchen stove.',
          difficulty: 'متوسط',
          timeLimitSeconds: 15,
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          steps: [
            ScenarioStep(
              id: 'step_f6_1',
              scenarioId: 'sc_fire_6',
              stepOrder: 1,
              situationAr: 'مقلاة الزيت تشتعل بلهب قوي. ما هي الطريقة الصحيحة والخالية من الخطر لإطفائها؟',
              situationEn: 'Oil pan is burning with intense flames. What is the safe method to extinguish it?',
              visualTheme: 'fire',
              hintAr: 'تغطية المقلاة بغطاء معدني أو بطانية حريق (خنق النار)',
              hintEn: 'Cover pan with metal lid or fire blanket to smother flames',
              options: [
                ScenarioOption(
                  id: 'opt_f6_1_a',
                  stepId: 'step_f6_1',
                  textAr: 'إغلاق مفتاح موقد الغاز فوراً، وتغطية المقلاة بغطاء معدني أو غطاء بطانية حريق لخنق الأكسجين',
                  textEn: 'Turn off gas stove burner immediately, cover pan with metal lid or fire blanket to choke oxygen',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف العلمي الصحيح؛ خنق حرائق الزيوت يطفئها بسلام ودون تناثر.',
                  explanationEn: 'Scientific correct method; smothering oil fire cuts off oxygen safely.',
                  consequenceAr: 'انكتم اللهب وانطفأت النار بالكامل دون انتشاره.',
                  consequenceEn: 'Flames smothered completely without any oil splatter.',
                ),
                ScenarioOption(
                  id: 'opt_f6_1_b',
                  stepId: 'step_f6_1',
                  textAr: 'صب كوب كبير من مياه الصنبور مباشرة داخل مقلاة الزيت المشتعلة',
                  textEn: 'Pour a large glass of tap water directly into the flaming oil pan',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'كارثي وخطر جداً؛ صب الماء على الزيت المحترق يسبب تبخراً انفجارياً وتناثر الزيت المشتعل.',
                  explanationEn: 'Catastrophic; water turns to steam instantly causing explosive fireball oil splash.',
                  consequenceAr: 'حدث انفجار ناري شديد وتناثر الزيت المشتعل بالمطبخ.',
                  consequenceEn: 'Explosive oil fireball erupted setting kitchen curtains on fire.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_fire_7',
          categoryId: 'fire',
          titleAr: 'شرر وحريق في قاطع وعدّاد الكهرباء الخارجي للمنزل',
          titleEn: 'Sparking Fire in Outdoor Electrical Meter Box',
          descriptionAr: 'انقطعت الكهرباء وسُمِع صوت طقطقة وشرر، وتبين اندلاع حريق داخل كابينة العداد الكهربائي الخارجي.',
          descriptionEn: 'Power cuts out accompanied by crackling sparks and fire inside outdoor electrical meter box.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          steps: [
            ScenarioStep(
              id: 'step_f7_1',
              scenarioId: 'sc_fire_7',
              stepOrder: 1,
              situationAr: 'النار تشتعل داخل كابينة العداد الخارجي وتتطاير الشرارات. ما الإجراء الفوري؟',
              situationEn: 'Fire raging inside meter box with flying electrical arcs. What is the immediate protocol?',
              visualTheme: 'fire',
              hintAr: 'اتصل بطوارئ الكهرباء 933 والدفاع المدني 998/911 واستخدم طفاية البودرة',
              hintEn: 'Call Electricity 933, Civil Defense 911, and use CO2/Dry Powder only',
              options: [
                ScenarioOption(
                  id: 'opt_f7_1_a',
                  stepId: 'step_f7_1',
                  textAr: 'الابتعاد مسافة آمنة، والاتصال بطوارئ الكهرباء 933 والدفاع المدني 911، واستخدام ططفية البودرة من بعد',
                  textEn: 'Keep safe distance, call Electricity 933 & Civil Defense 911, use Dry Powder extinguisher from distance',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'التصرف السليم؛ حرائق العدادات عالية الفولتية تتطلب عزل الفولت من الشركة واستخدام البودرة الجافة.',
                  explanationEn: 'Correct action; high voltage meter fires require power isolation by utility and dry chemicals.',
                  consequenceAr: 'وصلت فرقة الطوارئ وتم عزل الكابل وإخفاء اللهب بسلام.',
                  consequenceEn: 'Utility team arrived, isolated power grid and extinguished fire safely.',
                ),
                ScenarioOption(
                  id: 'opt_f7_1_b',
                  stepId: 'step_f7_1',
                  textAr: 'إحضار خرطوم مياه الحديقة ورش الماء بكثافة داخل كابينة العداد',
                  textEn: 'Grab garden hose and spray water stream heavily inside electrical meter box',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'قاتل وشديد الخطورة؛ تيار الضغط العالي ينتقل عبر تيار الماء ليصعق مستخدم الخرطوم.',
                  explanationEn: 'Fatal hazard; high voltage current travels up water stream electrocuting operator.',
                  consequenceAr: 'حدثت قوس كهربائية وصدمة شديدة.',
                  consequenceEn: 'Electrical arc flashed back causing severe electric shock.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_fire_8',
          categoryId: 'fire',
          titleAr: 'تسرب واشتعال السولار في المولد الاحتياطي للمبنى',
          titleEn: 'Diesel Fuel Leak & Fire in Standby Generator Room',
          descriptionAr: 'أثناء عمل المولد الاحتياطي، حدث تسرب سولار على الشكمان الساخن واشتعلت النيران بغرفة المولدات.',
          descriptionEn: 'Diesel fuel leaks onto hot generator exhaust igniting a room fire.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          steps: [
            ScenarioStep(
              id: 'step_f8_1',
              scenarioId: 'sc_fire_8',
              stepOrder: 1,
              situationAr: 'نار الوقود تسري على الأرضية والغرفة ممتلئة بالدخان. كيف تتعامل مع حريق وقود السولار؟',
              situationEn: 'Fuel fire spreading on floor and room filled with smoke. How do you fight liquid fuel fire?',
              visualTheme: 'fire',
              hintAr: 'استخدم طفاية الرغوة (Foam) أو البودرة الجافة وقفل صمام الوقود',
              hintEn: 'Use Foam/Dry Powder extinguisher and shut fuel supply valve',
              options: [
                ScenarioOption(
                  id: 'opt_f8_1_a',
                  stepId: 'step_f8_1',
                  textAr: 'إغلاق صمام الوقود الرئيسي، وضغط زر الإيقاف الفوري للمولد، واستخدام طفاية الرغوة/البودرة',
                  textEn: 'Shut main fuel valve, press emergency stop on generator, and deploy Foam/Dry Powder extinguisher',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'إجراء ممتاظ؛ قطع تزويد الوقود واستخدام الرغوة يعزل الأكسجين ويحصر السولار المشتعل.',
                  explanationEn: 'Excellent action; cutting fuel line and blanketing liquid with foam smothers fire.',
                  consequenceAr: 'تم إيقاف الوقود واحتواء الحريق بأمان.',
                  consequenceEn: 'Fuel source isolated and fire completely suppressed.',
                ),
                ScenarioOption(
                  id: 'opt_f8_1_b',
                  stepId: 'step_f8_1',
                  textAr: 'رش الماء من سطل نحو أرضية السولار المشتعلة',
                  textEn: 'Splash buckets of water onto the burning diesel floor',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'خطر جداً؛ السولار يطوف فوق سطح الماء فينشر النيران لمساحة أكبر بالمبنى.',
                  explanationEn: 'Dangerous; liquid fuel floats on water spreading fire across wider floor area.',
                  consequenceAr: 'طاف السولار المحترق فوق الماء واتسعت رقعة النار.',
                  consequenceEn: 'Burning diesel floated on water expanding fire footprint.',
                ),
              ],
            ),
          ],
        ),

        Scenario(
          id: 'sc_fire_9',
          categoryId: 'fire',
          titleAr: 'محاصرة الدخان الكثيف داخل غرفة نوم مغلقة',
          titleEn: 'Trapped by Dense Smoke inside Locked Bedroom',
          descriptionAr: 'استيقظت على صوت إنذار الحريق ووجدت الدخان الكثيف يملأ الممر الخارجي وتسرب تحت باب غرفتك.',
          descriptionEn: 'Waking up to fire alarm to find thick smoke filling hallway and seeping under bedroom door.',
          difficulty: 'متقدم',
          timeLimitSeconds: 15,
          icon: 'local_fire_department',
          colorHex: 0xFFE64A19,
          steps: [
            ScenarioStep(
              id: 'step_f9_1',
              scenarioId: 'sc_fire_9',
              stepOrder: 1,
              situationAr: 'الباب الخارجي ساخن جداً والدخان يدخل من أسفله. كيف تحمي نفسك حتى وصول الإنقاذ؟',
              situationEn: 'Door handle is scalding hot and smoke seeps underneath. How do you survive until rescue?',
              visualTheme: 'fire',
              hintAr: 'لا تفتح الباب الساخن، وسد الشقوق بأقمشة مبللة وتأشر من النافذة',
              hintEn: 'Do not open hot door; seal gaps with wet towels and signal from window',
              options: [
                ScenarioOption(
                  id: 'opt_f9_1_a',
                  stepId: 'step_f9_1',
                  textAr: 'إغلاق الباب وعدم فتحه، وسد شقوق الباب بأقمشة ومناشف مبللة بالماء، وطلب 911 والإشارة من النافذة',
                  textEn: 'Keep door shut, seal bottom gaps with wet towels, call 911 and signal location from window',
                  isCorrect: true,
                  safetyPoints: 100,
                  explanationAr: 'تصرف منقذ للحياة؛ الباب المغلق والأقمشة المبللة تمنع دخول الغازات المميته وتوفر وقتاً للإنقاذ.',
                  explanationEn: 'Life-saving protocol; wet seals block deadly carbon monoxide giving firefighters time.',
                  consequenceAr: 'بقيت الغرفة خالية من الدخان حتى وصل رجال الدفاع المدني عبر السلم الخارجي.',
                  consequenceEn: 'Bedroom remained smoke-free until firefighters rescued via window ladder.',
                ),
                ScenarioOption(
                  id: 'opt_f9_1_b',
                  stepId: 'step_f9_1',
                  textAr: 'فتح الباب الساخن بسرعة والركض وسط الممر المليء بالدخان الأسود',
                  textEn: 'Fling hot door open and sprint blindly into black smoke-filled hallway',
                  isCorrect: false,
                  safetyPoints: 0,
                  explanationAr: 'قاتل؛ فتح الباب يسحب لهب الحرارة المرتفعة (Flashover) واستنشاق نفحة واحدة من الدخان يسبب غيبوبة.',
                  explanationEn: 'Fatal; opening hot door pulls in superheated gases and one breath of smoke knocks you out.',
                  consequenceAr: 'اندفعت موجة حرارة ودخان أسود تسببت بالإغماء الفوري.',
                  consequenceEn: 'Superheated smoke burst inside causing instant asphyxiation.',
                ),
              ],
            ),
          ],
        ),
"""

print("Generated code length:", len(new_scenarios_code))
