import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('ar'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'ar': {
      'appName': 'جاهز للطوارئ',
      'appSubtitle': 'تعلم. تدرب. كن جاهزًا.',
      'appSlogan': 'تعلم من خلال التجربة والمحاكاة، وليس القراءة فقط.',
      'welcome': 'مرحبًا بك',
      'areYouReady': 'هل أنت مستعد لمواجهة الطوارئ؟',
      'startSimulation': 'ابدأ محاكاة',
      'home': 'الرئيسية',
      'simulations': 'المحاكاة',
      'learning': 'التعلم',
      'achievements': 'إنجازاتي',
      'settings': 'الإعدادات',
      'lastTraining': 'آخر تدريب',
      'readinessScore': 'درجة الجاهزية',
      'dailyChallenge': 'تحدي اليوم',
      'knowledgeCenter': 'مركز المعرفة',
      'emergencyNumbers': 'أرقام ومعلومات الطوارئ',
      'familyMode': 'نمط العائلة',
      'categories': 'مجالات المحاكاة والتدريب',
      'chooseCategory': 'اختر المجال للبدء بالسيناريوهات العملية',
      'scenarioTitle': 'سيناريو المحاكاة',
      'decision': 'ماذا ستفعل؟',
      'safeDecision': 'قرار آمن وسليم ✅',
      'unsafeDecision': 'قرار غير آمن ومحفوف بالمخاطر ⚠️',
      'moderateDecision': 'قرار يحتاج إلى تصحيح ℹ️',
      'whyThisDecision': 'التفسير والتحليل العلمي:',
      'consequence': 'النتيجة المباشرة:',
      'nextStep': 'المتابعة للحدث التالي',
      'finishSimulation': 'إنهاء وعرض التقييم',
      'simulationComplete': 'اكتملت المحاكاة بنجاح',
      'yourScore': 'النتيجة الإجمالية',
      'decisionSpeed': 'سرعة اتخاذ القرار',
      'safety': 'معيار السلامة',
      'knowledge': 'المعرفة بالإجراءات',
      'response': 'كفاءة الاستجابة',
      'strengths': 'نقاط القوة والأداء المتميز',
      'areasForImprovement': 'ما تحتاج إلى تحسينه ومراجعته',
      'educationalAdvice': 'النصيحة والتوجيه التعليمي',
      'retrySimulation': 'إعادة المحاكاة',
      'anotherSimulation': 'محاكاة أخرى',
      'backToHome': 'العودة للرئيسية',
      'xpEarned': 'نقاط خبرة مكتسبة',
      'badgeUnlocked': 'تم فتح وسام جديد!',
      'level': 'المستوى',
      'badges': 'الأوسمة والإنجازات',
      'simulationHistory': 'سجل التدريبات والمحاكاة',
      'noHistoryYet': 'لم تقم بأي محاكاة بعد. ابدأ أول تدريب الآن!',
      'emergencyGuide': 'دليل إجراءات الطوارئ الرسمية',
      'call': 'اتصال فوري',
      'copied': 'تم نسخ الرقم',
      'adminMode': 'إدارة المحتوى والمحاكاة (Admin)',
      'enterAdminPin': 'أدخل الرمز السري للإدارة',
      'incorrectPin': 'الرمز السري غير صحيح',
      'searchArticles': 'ابحث في مواضيع السلامة والإسعافات...',
      'doList': 'ما يجب فعله (افعل)',
      'dontList': 'ما يجب تجنبه (لا تفعل)',
      'stepByStep': 'خطوات الاستجابة الصحيحة',
      'switchProfile': 'تبديل الملف الشخصي',
      'addNewProfile': 'إضافة فرد جديد',
      'profileName': 'اسم المستخدم',
      'profileRole': 'الصفة العائلية',
      'father': 'الأب',
      'mother': 'الأم',
      'son': 'الابن',
      'daughter': 'الابنة',
      'member': 'فرد العائلة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'edit': 'تعديل',
      'delete': 'حذف',
      'darkMode': 'الوضع الليلي',
      'soundEffects': 'المؤثرات الصوتية والاهتزاز',
      'timerEnabled': 'المؤقت الزمني أثناء المحاكاة',
      'language': 'اللغة / Language',
      'offlineBadge': 'يعمل بالكامل بدون إنترنت 100%',
      'difficulty': 'مستوى الصعوبة',
      'beginner': 'مبتدئ',
      'intermediate': 'متوسط',
      'advanced': 'متقدم',
      'seconds': 'ثانية',
      'points': 'نقطة',
      'excellent': 'ممتاز - جاهزية استثنائية',
      'veryGood': 'جيد جداً - جاهزية عالية',
      'good': 'جيد - مستوى مقبول',
      'needsWork': 'مستوى قابل للتطوير',
      'fireSafety': 'السلامة من الحرائق',
      'evacuation': 'الإخلاء والطوارئ',
      'homeSafety': 'السلامة المنزلية',
      'trafficSafety': 'السلامة المرورية',
      'weatherSafety': 'الأحوال الجوية والسيول',
      'emergencyReadiness': 'الاستعداد للطوارئ',
      'heatSafety': 'الحرارة الشديدة',
      'electricSafety': 'المخاطر الكهربائية',
    },
    'en': {
      'appName': 'Emergency Ready',
      'appSubtitle': 'Learn. Train. Be Ready.',
      'appSlogan': 'Learn through real interactive simulations, not just reading.',
      'welcome': 'Welcome',
      'areYouReady': 'Are you ready for emergencies?',
      'startSimulation': 'Start Simulation',
      'home': 'Home',
      'simulations': 'Simulations',
      'learning': 'Learning',
      'achievements': 'Achievements',
      'settings': 'Settings',
      'lastTraining': 'Last Training',
      'readinessScore': 'Readiness Score',
      'dailyChallenge': 'Daily Challenge',
      'knowledgeCenter': 'Knowledge Center',
      'emergencyNumbers': 'Emergency Numbers & Info',
      'familyMode': 'Family Mode',
      'categories': 'Simulation Categories',
      'chooseCategory': 'Select a domain to start real-life emergency scenarios',
      'scenarioTitle': 'Scenario Simulation',
      'decision': 'What will you do?',
      'safeDecision': 'Safe & Sound Decision ✅',
      'unsafeDecision': 'Unsafe & Risky Decision ⚠️',
      'moderateDecision': 'Decision needs correction ℹ️',
      'whyThisDecision': 'Scientific Analysis & Explanation:',
      'consequence': 'Direct Consequence:',
      'nextStep': 'Proceed to Next Event',
      'finishSimulation': 'Finish & Show Evaluation',
      'simulationComplete': 'Simulation Completed Successfully',
      'yourScore': 'Overall Score',
      'decisionSpeed': 'Decision Speed',
      'safety': 'Safety Standard',
      'knowledge': 'Procedure Knowledge',
      'response': 'Response Efficiency',
      'strengths': 'Key Strengths',
      'areasForImprovement': 'Areas for Improvement',
      'educationalAdvice': 'Educational Guidance & Tip',
      'retrySimulation': 'Retry Simulation',
      'anotherSimulation': 'Another Simulation',
      'backToHome': 'Back to Home',
      'xpEarned': 'Earned XP',
      'badgeUnlocked': 'New Badge Unlocked!',
      'level': 'Level',
      'badges': 'Badges & Milestones',
      'simulationHistory': 'Training & Simulation History',
      'noHistoryYet': 'No simulations completed yet. Start your first session now!',
      'emergencyGuide': 'Official Emergency Procedures Guide',
      'call': 'Emergency Call',
      'copied': 'Number copied to clipboard',
      'adminMode': 'Content & Simulation Admin',
      'enterAdminPin': 'Enter Admin PIN',
      'incorrectPin': 'Incorrect PIN code',
      'searchArticles': 'Search safety topics, first aid, guides...',
      'doList': "What to do (Do's)",
      'dontList': "What to avoid (Don'ts)",
      'stepByStep': 'Step-by-step Correct Response',
      'switchProfile': 'Switch Profile',
      'addNewProfile': 'Add New Family Member',
      'profileName': 'Profile Name',
      'profileRole': 'Family Role',
      'father': 'Father',
      'mother': 'Mother',
      'son': 'Son',
      'daughter': 'Daughter',
      'member': 'Family Member',
      'save': 'Save',
      'cancel': 'Cancel',
      'edit': 'Edit',
      'delete': 'Delete',
      'darkMode': 'Dark Mode',
      'soundEffects': 'Sound Effects & Haptics',
      'timerEnabled': 'Simulation Countdown Timer',
      'language': 'Language / اللغة',
      'offlineBadge': '100% Completely Offline Capable',
      'difficulty': 'Difficulty Level',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'seconds': 'seconds',
      'points': 'pts',
      'excellent': 'Excellent - Outstanding Readiness',
      'veryGood': 'Very Good - High Readiness',
      'good': 'Good - Acceptable Readiness',
      'needsWork': 'Needs More Training & Practice',
      'fireSafety': 'Fire Safety',
      'evacuation': 'Evacuation & Crowd',
      'homeSafety': 'Home Safety',
      'trafficSafety': 'Traffic & Road Safety',
      'weatherSafety': 'Weather & Flood Safety',
      'emergencyReadiness': 'Emergency Readiness',
      'heatSafety': 'Extreme Heat',
      'electricSafety': 'Electrical Hazards',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['ar']?[key] ??
        key;
  }

  bool get isArabic => locale.languageCode == 'ar';
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
